project_id = "qwkitwlppplhiabquxsx"

[functions.devocionalzeiro-chat]
verify_jwt = true

[functions.chapter-explanation]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.daily-whatsapp-reminders]
verify_jwt = false
