// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de PERSONAGEM (por `id`) das cenas de 1kings. Vem por import() junto com
// o roteiro do livro: quem lê Rute não baixa os nomes de Crônicas.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHARS: Record<string, StageInfo> = {
  davi: { title: "Davi", subtitle: "O pastor de Belém, ungido rei (1Sm 16–31)", text: "O oitavo e menor filho de Jessé, apascentando ovelhas quando Samuel derramou sobre ele o azeite no meio dos irmãos — \"e desde aquele dia em diante o Espírito do Senhor se apoderou de Davi\" (1Sm 16:13). Tocava harpa para aliviar Saul, matou o leão e o urso do rebanho antes de matar o gigante, e derrubou Golias com uma funda e cinco pedras lisas em nome do \"Senhor dos Exércitos, o Deus dos exércitos de Israel\" (1Sm 17:45). Amado por Jônatas e pelo povo (\"Saul feriu os seus milhares, porém Davi os seus dez milhares\"), foi caçado por dez anos pelo rei que servira — e por duas vezes teve Saul na ponta da mão e não estendeu a mão contra \"o ungido do Senhor\" (1Sm 24:6; 26:9). Homem \"segundo o coração de Deus\" (1Sm 13:14), autor de grande parte dos Salmos, e o rei de cuja casa Deus prometeu um trono eterno (2Sm 7:16) — cumprido em Jesus, \"o filho de Davi\" (Mt 1:1)." },
  abiatar: { title: "Abiatar", subtitle: "O único sacerdote que escapou de Nobe (1Sm 22:20)", text: "Filho de Aimeleque, escapou do massacre e fugiu para Davi, que assumiu a culpa diante dele: \"eu dei ocasião à morte de todas as almas da casa de teu pai. Fica comigo, não temas... estarás em segurança comigo\" (1Sm 22:22-23). Trouxe consigo o ÉFODE, e por ele Davi passou a consultar o SENHOR nas horas decisivas — em Queila (1Sm 23:9-12) e em Ziclague (1Sm 30:7-8). Foi sacerdote durante todo o reinado de Davi, carregou a arca e chorou com ele na fuga de Absalão; mas apoiou Adonias na sucessão e foi deposto por Salomão, \"para que se cumprisse a palavra do Senhor, que tinha dito sobre a casa de Eli em Siló\" (1Rs 2:27)." },
  joabe: { title: "Joabe", subtitle: "Filho de Zeruia, o futuro capitão de Davi", text: "Sobrinho de Davi e irmão de Abisai e Asael, aparece já no bando do deserto e se tornaria o comandante do exército durante quase todo o reinado (2Sm 8:16). Soldado de altíssima competência e de consciência curta: matou Abner à traição em Hebrom (2Sm 3:27), executou a ordem que pôs Urias na linha de frente (2Sm 11:16-17) e matou Absalão contra a ordem expressa do rei (2Sm 18:14). Sabia, porém, dizer a Davi o que ninguém dizia (2Sm 19:5-7). Foi finalmente alcançado pela justiça que adiara, agarrado às pontas do altar (1Rs 2:28-34) — figura da lealdade sem temor de Deus." },
  nata: { title: "Natã", subtitle: "O profeta que disse a Davi \"Tu és este homem\" (2Sm 12:7)", text: "Aparece primeiro aprovando depressa o que o rei tinha no coração — \"Vai, e faze tudo quanto está no teu coração; porque o Senhor é contigo\" (2Sm 7:3) —, e naquela mesma noite a palavra do SENHOR o desmentiu: não seria Davi a edificar a casa, seria Deus a fazer casa a Davi, com um trono \"firme para sempre\" (2Sm 7:11-16). Anos depois voltou com uma parábola de cordeira, deixou o rei condenar-se pela própria boca e cravou a sentença: \"Tu és este homem\" (12:7). Anunciou a espada que nunca mais sairia daquela casa, ouviu a confissão \"Pequei contra o Senhor\" e respondeu com o perdão que não cancelava o castigo (12:10,13). Quando nasceu Salomão, foi pela sua mão que Deus mandou chamá-lo JEDIDIAS, \"por amor ao Senhor\" (12:25). Na última hora do reinado ainda entrou no quarto do velho rei para desfazer o golpe de Adonias, e desceu a Giom com Zadoque a ungir Salomão (1Rs 1:11,32-34). Escreveu parte da história do reinado (1Cr 29:29): profeta de corte que nunca virou bajulador." },
  "bate-seba": { title: "Bate-Seba", subtitle: "Filha de Eliã, mulher de Urias, o heteu (2Sm 11:3)", text: "O relato é sóbrio e devastador: \"numa tarde Davi se levantou do seu leito, e andava passeando no terraço da casa real, e viu do terraço a uma mulher que se estava lavando\" (11:2). Mandaram indagar quem era, mandaram buscá-la, e o recado que voltou tem duas palavras: \"Estou grávida\" (11:5). Chorou o marido morto pela carta que ele mesmo carregara, e \"passado o luto\" foi recolhida à casa do rei (11:26-27). O primeiro filho adoeceu e morreu ao sétimo dia; do segundo o texto diz apenas \"e o Senhor o amou\" — Salomão (12:24). Era filha de Eliã, e aquele Eliã era filho de Aitofel, o gilonita (23:34), o conselheiro que depois trairia Davi. Reapareceu decisiva na velhice do rei, cobrando o juramento antigo — \"Salomão, teu filho, reinará depois de mim\" (1Rs 1:17) — e sentou-se depois como rainha-mãe. Mateus não a nomeia na genealogia do Messias: chama-a \"a que foi mulher de Urias\" (Mt 1:6), para que a ferida entrasse inteira na linhagem de Cristo." },
  urias: { title: "Urias, o heteu", subtitle: "Um dos valentes de Davi, marido de Bate-Seba (2Sm 23:39)", text: "Estrangeiro — heteu, de um povo cananeu — e ainda assim inscrito na lista de honra do reino, o último nome dos trinta e sete valentes de Davi (23:39). Chamado da frente de batalha para encobrir o adultério do rei, recusou-se a descer à própria casa: \"A arca, e Israel, e Judá ficaram em tendas; e Joabe, meu senhor, e os servos de meu senhor estão acampados no campo; e hei de eu entrar na minha casa, para comer e beber, e para me deitar com minha mulher?\" (11:11). Dormiu à porta da casa real com os servos; embebedado de propósito, dormiu à porta outra vez — sóbrio ou bêbado, mais fiel do que o ungido. Levou nas próprias mãos a carta que o condenava: \"Ponde a Urias na frente da maior força da peleja; e retirai-vos de detrás dele, para que seja ferido e morra\" (11:15). Morreu junto ao muro de Rabá, e a notícia chegou a Jerusalém escondida no meio de uma lista de baixas. Foi por causa dele que Natã pronunciou a sentença — \"não se apartará a espada jamais da tua casa\" (12:10) — e é o nome dele, não o dela, que Mateus preservou na genealogia do Messias (Mt 1:6)." },
  simei: { title: "Simei", subtitle: "Filho de Gera, que amaldiçoou o rei em Baurim (2Sm 16:5)", text: "Benjamita da linhagem da casa de Saul, saiu de Baurim para acompanhar o cortejo do rei em fuga, \"e, saindo, ia amaldiçoando\", atirando pedras e levantando poeira ao longo do monte (16:5-6,13). O que gritava era: \"Sai, sai, homem de sangue, e homem de Belial... eis-te agora na tua desgraça, porque és um homem de sangue\" (16:7-8). Abisai quis resolver como sempre — \"Deixa-me passar, e lhe tirarei a cabeça\" —, e ouviu do rei a resposta que só cabe num homem quebrantado: \"Deixai-o, que amaldiçoe; porque o Senhor lho disse. Porventura o Senhor olhará para a minha miséria\" (16:9-12). Na volta foi o primeiro de toda a casa de José a descer ao Jordão, com mil benjamitas, prostrando-se e confessando: \"teu servo deveras confessa que pecou\" (19:16-20). Davi lhe jurou a vida — \"Não morrerás\" (19:23) —, mas legou a conta ao filho: \"não o tenhas por inculpável, pois és homem sábio... para que faças com que as suas cãs desçam à sepultura com sangue\" (1Rs 2:9). Confinado por Salomão a Jerusalém, quebrou o confinamento atrás de dois escravos fugidos e morreu pela mão de Benaia (1Rs 2:36-46): a maldição daquele dia levou anos a cobrar, mas cobrou." },
  zadoque: { title: "Zadoque", subtitle: "O sacerdote, filho de Aitube (2Sm 8:17; 15:24-29)", text: "Descendente de Eleazar, filho de Arão, serviu ao lado de Abiatar durante todo o reinado de Davi (8:17). Na noite da fuga saiu de Jerusalém com todos os levitas e a arca da aliança, e o rei o mandou de volta com ela: \"Torna a levar a arca de Deus à cidade; que, se achar graça nos olhos do Senhor, ele me tornará a trazer para lá e me deixará ver a ela e a sua habitação\" (15:25) — Davi recusou usar a arca como amuleto, como Israel fizera em Ebenézer. Ficou dentro da cidade ocupada como os olhos e os ouvidos do rei, mandando por Aimaás e Jônatas os avisos que salvaram o exército inteiro (15:35-36; 17:15-21). Na volta, trabalhou para que Judá fosse o primeiro a buscar o rei (19:11). Foi ele quem ungiu Salomão em Giom, tomando \"o chifre de azeite do tabernáculo\" (1Rs 1:39). E quando Abiatar caiu por apoiar Adonias, \"a Zadoque, o sacerdote, pôs o rei em lugar de Abiatar\" (1Rs 2:35): dele veio a casa sacerdotal que substituiu a de Eli, e são os \"filhos de Zadoque\" que Ezequiel guarda para o serviço do santuário na visão do templo (Ez 44:15)." },
  hadadezer: { title: "Hadadezer", subtitle: "Filho de Reobe, rei de Zobá (2Sm 8:3)", text: "Rei arameu de Zobá, a maior potência da Síria no seu tempo, ferido por Davi \"quando ele ia recuperar o seu domínio sobre o rio Eufrates\" (8:3). Perdeu numa só campanha mil carros, setecentos cavaleiros e vinte mil homens de pé; e Davi jarretou todos os cavalos dos carros, reservando apenas cem (8:4) — Israel não quis a cavalaria das nações, obedecendo à lei do rei, que mandava que o rei \"não multiplicará para si cavalos\" (Dt 17:16). Os sírios de Damasco vieram socorrê-lo e caíram vinte e dois mil (8:5). Os escudos de ouro dos seus servos e o muito bronze de Betá e Berotai foram levados a Jerusalém e consagrados ao SENHOR (8:7-8,11). Ainda tentou refazer-se uma segunda vez, chamando os sírios do outro lado do rio sob o comando de Sobaque, e perdeu tudo em Helã (10:16-18). No fim, \"todos os reis, servos de Hadadezer, que foram feridos diante de Israel, fizeram paz com Israel, e o serviram\" (10:19) — e o bronze do inimigo virou material do culto do Deus vivo." },
  hirao: { title: "Hirão, rei de Tiro", subtitle: "O aliado fenício de Davi e de Salomão (2Sm 5:11; 1Rs 5)", text: "Rei da cidade portuária de Tiro, foi o primeiro soberano estrangeiro a reconhecer o reinado de Davi sobre todo o Israel: \"enviou mensageiros a Davi, e madeira de cedro, e carpinteiros, e pedreiros que edificaram a Davi uma casa\" (2Sm 5:11) — e foi diante desse palácio novo que Davi entendeu que o SENHOR exaltara o seu reino \"por amor do seu povo\" (2Sm 5:12). A amizade atravessou uma geração: \"Hirão sempre tinha amado a Davi\", e por isso ele mandou os seus servos a Salomão assim que soube da unção (1Rs 5:1). O acordo do templo é dele: os sidônios, que sabiam cortar madeira como ninguém, derrubaram os CEDROS DO LÍBANO, que desceram em jangadas pelo mar, em troca de trigo e azeite batido para a sua casa, ano após ano (1Rs 5:6-11). Enviou também o artífice de cobre que fundiu as duas colunas e o mar (1Rs 7:13-14), e os seus marinheiros levaram a frota de Salomão a Ofir (1Rs 9:27). Nem tudo foi harmonia: as vinte cidades da Galileia que recebeu em pagamento não lhe agradaram, e ele perguntou \"Que cidades são estas que me deste, irmão meu?\" — o lugar ficou chamado \"Terra de Cabul, até hoje\" (1Rs 9:13). A casa do SENHOR foi levantada com madeira estrangeira e mãos estrangeiras — sinal antigo de que aquele Nome atrairia gente de \"terra remota\" (1Rs 8:41)." },
  benaia: { title: "Benaia", subtitle: "Filho de Joiada, sobre os quereteus e peleteus (2Sm 8:18; 23:20-23)", text: "De Cabzeel, filho de um homem valoroso e ele mesmo \"grande em obras\": feriu dois fortes heróis de Moabe e \"desceu ele, e feriu um leão no meio duma cova, no tempo da neve\" (23:20) — a Escritura guarda até o detalhe do tempo, porque descer a um poço gelado atrás de um leão é o retrato inteiro do homem. Enfrentou também um egípcio de respeito armado de lança levando apenas um cajado, \"e arrancou a lança da mão do egípcio, e com ela o matou\" (23:21). Nos anais dos valentes ficou registrado que \"teve nome entre três poderosos\", embora não chegasse aos três primeiros, e Davi o pôs sobre a sua guarda pessoal, os quereteus e os peleteus (23:22-23; 8:18). Nunca aparece do lado errado: não vacilou na fuga de Absalão, não entrou na conspiração de Adonias, e foi um dos três que Davi chamou para descer a Giom e ungir Salomão (1Rs 1:32-38). Foi ele quem executou as sentenças que fecharam a conta do reinado — Joabe agarrado às pontas do altar, e depois Simei (1Rs 2:34,46) — e recebeu o comando do exército (1Rs 2:35). O homem do leão na cova acabou general." },
  "abisague": {
    title: "Abisague, a sunamita",
    subtitle: "A moça que aquecia o rei Davi na velhice (1Rs 1:3)",
    text: "Entra na Escritura como remédio para a velhice de um rei: \"cobriam-no de roupas, porém não se aquecia\" (1:1), e os servos saíram a procurar. \"E buscaram por todos os termos de Israel uma moça formosa, e acharam a Abisague, sunamita; e a trouxeram ao rei\" (1:3). O texto guarda dela duas coisas juntas, e as duas importam: \"E era a moça sobremaneira formosa; e tinha cuidado do rei, e o servia; porém o rei não a conheceu\" (1:4). Estava ali, servindo em silêncio, na câmara em que Bate-Seba e Natã travaram a disputa que decidiu o trono de Israel (1:15). Depois da morte de Davi, tornou-se o pretexto de uma sentença de morte: Adonias pediu por ela, e Salomão leu no pedido o que ele de fato era — \"E por que pedes a Abisague, a sunamita, para Adonias? Pede também para ele o reino\" (2:22). Nunca fala uma palavra em todo o livro, e por causa dela um príncipe morreu no mesmo dia (2:24). É a figura muda a quem os poderosos atribuem sentidos que ela não escolheu.",
  },
  "adonias": {
    title: "Adonias",
    subtitle: "Filho de Hagite, o príncipe que se proclamou rei (1Rs 1:5)",
    text: "\"Então Adonias, filho de Hagite, se levantou, dizendo: Eu reinarei\" (1:5) — não foi ungido, não foi chamado, apenas se levantou. Imitou o irmão morto até nos detalhes: \"E preparou carros, e cavaleiros, e cinqüenta homens, que corressem adiante dele\" (1:5), exatamente como Absalão. E o versículo seguinte explica a vida inteira num aparte devastador: \"E nunca seu pai o tinha contrariado, dizendo: Por que fizeste assim? E era ele também muito formoso de parecer\" (1:6). Fez-se um banquete junto à pedra de Zoelete e convidou a todos, menos a Natã, a Benaia e a Salomão (1:9-10); mas o som das trombetas de Giom chegou ao meio da festa, e \"estremeceram e se levantaram todos os convidados\" (1:49). Correu ao santuário e \"apegou-se às pontas do altar\" (1:50), e Salomão o poupou com uma condição exata: \"Se for homem de bem, nem um de seus cabelos cairá em terra; se, porém, se achar nele maldade, morrerá\" (1:52). Não se achou homem de bem: voltou por Bate-Seba a pedir Abisague, começando com a frase que o entregou — \"Bem sabes que o reino era meu\" (2:15). Morreu naquele mesmo dia pela mão de Benaia (2:24-25). O filho que nunca ouviu um \"Por que fizeste assim?\" do pai acabou ouvindo do irmão a única palavra que ninguém adia.",
  },
  "salomao": {
    title: "Salomão",
    subtitle: "O rei sábio de Gibeom, o construtor do templo, o coração desviado (1Rs 1–11)",
    text: "Ungido em Giom sobre a mula do pai enquanto Adonias banqueteava (1:38-40), recebeu de Davi a ordem de partida: \"esforça-te, pois, e sê homem\" (2:2). Em Gibeom, Deus lhe abriu um cheque em branco — \"Pede o que queres que eu te dê\" (3:5) — e ele não pediu vida longa, nem riquezas, nem a morte dos inimigos: \"sou apenas um menino pequeno; não sei como sair, nem como entrar\" (3:7), \"dá um coração entendido para julgar a teu povo\" (3:9). Deus lhe deu o que pediu e o que não pediu: \"te dei um coração tão sábio e entendido, que antes de ti igual não houve, e depois de ti igual não se levantará\" (3:12). A espada pedida diante das duas prostitutas provou-o diante de Israel (3:24-28); \"disse três mil provérbios, e foram os seus cânticos mil e cinco\" (4:32), e sete anos de obra levantaram a casa do SENHOR, onde a nuvem entrou de tal modo que \"os sacerdotes não podiam permanecer em pé para ministrar\" (8:11). Ali orou a oração mais lúcida jamais feita por um construtor: \"Mas, na verdade, habitaria Deus na terra? Eis que os céus, e até o céu dos céus, não te poderiam conter, quanto menos esta casa que eu tenho edificado\" (8:27) — e nela pediu que Deus ouvisse também \"ao estrangeiro, que não for do teu povo Israel\" (8:41). E então a tragédia lenta: setecentas princesas e trezentas concubinas, e \"suas mulheres lhe perverteram o coração\" (11:3); altos a Quemós e a Moloque no monte diante de Jerusalém (11:7). O homem que orara pelo estrangeiro acabou adorando os deuses dele. \"certamente rasgarei de ti este reino, e o darei a teu servo\" (11:11): a sabedoria era dom, não blindagem.",
  },
  "mae-verdadeira": {
    title: "A mãe verdadeira",
    subtitle: "A que preferiu perder o filho a vê-lo dividido (1Rs 3:26)",
    text: "Uma das \"duas mulheres prostitutas\" que vieram ao rei sem testemunha nenhuma para sustentar a sua causa: \"nenhum estranho estava conosco na casa; somente nós duas naquela casa\" (3:16-18). Contou a noite inteira — o filho da outra morto porque \"se deitara sobre ele\", a troca à meia-noite, e a descoberta terrível ao amanhecer: \"atentando pela manhã para ele, eis que não era meu filho, que eu havia tido\" (3:19-21). Quando o rei mandou trazer uma espada e ordenou dividir o menino, foi o corpo dela que respondeu antes da boca: \"porque as suas entranhas se lhe enterneceram por seu filho\", e disse: \"Ah! senhor meu, dai-lhe o menino vivo, e de modo nenhum o mateis\" (3:26). Renunciou ao filho para que o filho vivesse — e foi exatamente essa renúncia que o rei leu como prova: \"Dai a esta o menino vivo, e de maneira nenhuma o mateis, porque esta é sua mãe\" (3:27). O amor verdadeiro é o que abre mão de possuir; e uma mulher sem nome e sem honra na cidade ensinou a Israel o que era a sabedoria de Deus (3:28).",
  },
  "mae-falsa": {
    title: "A mãe falsa",
    subtitle: "A que aceitou a divisão do menino (1Rs 3:26)",
    text: "A outra das duas mulheres do juízo de Salomão: dormiu sobre o próprio filho e o matou, e à meia-noite trocou os meninos enquanto a companheira dormia (3:19-20). Diante do rei, sustentou a mentira em plena inversão: \"Não, mas o vivo é meu filho, e teu filho o morto\" (3:22). Quando a espada foi trazida e a sentença dada — \"Dividi em duas partes o menino vivo; e dai metade a uma, e metade a outra\" (3:25) —, ela não recuou; disse a frase que a condenou para sempre: \"Nem teu nem meu seja; dividi-o\" (3:26). É o retrato exato da inveja: já não quer o bem, quer que ninguém o tenha. Não perdeu a causa por falta de provas, mas porque abriu a boca; a sabedoria de Deus não interrogou testemunhas, apenas deu a cada coração a chance de se mostrar.",
  },
  "hirao-artifice": {
    title: "Hirão, o artífice de cobre",
    subtitle: "Filho de uma viúva de Naftali, fundidor do templo (1Rs 7:13-14)",
    text: "Salomão mandou buscá-lo em Tiro, e o texto se detém na sua origem misturada: \"Era ele filho de uma mulher viúva, da tribo de Naftali, e fora seu pai um homem de Tiro, que trabalhava em cobre; e era cheio de sabedoria, e de entendimento, e de ciência para fazer toda a obra de cobre\" (7:14). A mesma palavra usada para o dom do rei — sabedoria — é usada para as mãos deste operário: o templo foi levantado por um rei sábio e fundido por um fundidor sábio. Suas obras ficaram de pé na porta da casa de Deus: as duas colunas de dezoito côvados, e \"levantando a coluna direita, pôs-lhe o nome de Jaquim; e levantando a coluna esquerda, pôs-lhe o nome de Boaz\" (7:21); \"o mar de fundição, de dez côvados de uma borda até à outra borda, perfeitamente redondo\" (7:23), que \"firmava-se sobre doze bois\" voltados para os quatro ventos (7:25); as dez bases, as pias, as pás e as bacias, \"todos eram de cobre polido\" (7:45). Fundiu tudo longe do templo, na lama do vale: \"Na planície do Jordão, o rei os fundiu em terra barrenta; entre Sucote e Zaretã\" (7:46). Filho de viúva israelita e de pai estrangeiro, é a prova antecipada da oração que Salomão faria naquela casa a favor do estrangeiro (8:41-43).",
  },
  "rainha-de-saba": {
    title: "A rainha de Sabá",
    subtitle: "A que veio de longe provar Salomão com enigmas (1Rs 10:1)",
    text: "\"E ouvindo a rainha de Sabá a fama de Salomão, acerca do nome do SENHOR, veio prová-lo com questões difíceis\" (10:1) — repare no que a moveu: não a fama do ouro, mas a fama ligada ao Nome. \"E chegou a Jerusalém com uma grande comitiva; com camelos carregados de especiarias, e muitíssimo ouro, e pedras preciosas; e foi a Salomão, e disse-lhe tudo quanto tinha no seu coração\" (10:2). Não sobrou enigma: \"nada houve que não lhe pudesse esclarecer\" (10:3). Vendo a sabedoria, a casa, a mesa, os servos e os holocaustos que ele oferecia, \"ficou fora de si\" (10:5) — a ARC guarda assim o fôlego que lhe faltou. Então fez a confissão de quem descobre que a realidade excedeu o boato: \"eu não cria naquelas palavras, até que vim e os meus olhos o viram; eis que não me disseram metade\" (10:7), e terminou louvando não o rei, mas quem o pusera ali: \"Bendito seja o Senhor teu Deus, que teve agrado em ti, para te pôr no trono de Israel\" (10:9). Deu cento e vinte talentos de ouro e voltou para a sua terra (10:10,13). Jesus a levantaria como testemunha contra a própria geração dele: veio dos confins da terra ouvir a sabedoria de Salomão, e ali estava alguém maior do que Salomão (Mt 12:42).",
  },
  "aias-silonita": {
    title: "Aías, o silonita",
    subtitle: "O profeta da capa rasgada em doze pedaços (1Rs 11:29; 14:2)",
    text: "Encontrou Jeroboão fora dos muros, longe de ouvidos: \"o profeta Aías, o silonita, o encontrou no caminho, e ele estava vestido com uma roupa nova, e os dois estavam sós no campo\" (11:29). Então fez a profecia com as mãos, não com a boca: \"E Aías pegou na roupa nova que tinha sobre si, e a rasgou em doze pedaços\", e disse \"Toma para ti os dez pedaços\" (11:30-31). Ainda no mesmo oráculo guardou a promessa que salvaria Judá do nada: \"para que Davi, meu servo, sempre tenha uma lâmpada diante de mim em Jerusalém\" (11:36). Anos depois, cego em Siló — \"já Aías não podia ver, porque os seus olhos estavam já escurecidos por causa da sua velhice\" (14:4) —, recebeu a visita da mulher disfarçada do rei que ele mesmo ungira. Deus o avisou antes, e o velho reconheceu-a pelo som: \"ouvindo Aías o ruído de seus pés, entrando ela pela porta, disse-lhe ele: Entra, mulher de Jeroboão; por que te disfarças assim? Pois eu sou enviado a ti com duras novas\" (14:6). É a lição mais dura do livro sobre disfarces: os olhos cegos do profeta viram o que a fantasia da rainha quis esconder, porque quem enxergava não eram os olhos dele.",
  },
  "jeroboao": {
    title: "Jeroboão, filho de Nebate",
    subtitle: "O servo valente que fez os dois bezerros de ouro (1Rs 11:26; 12:28)",
    text: "O texto o apresenta como \"efrateu, de Zereda, servo de Salomão (cuja mãe era mulher viúva, por nome Zerua)\" (11:26): começou de baixo e subiu por mérito — \"E o homem Jeroboão era forte e valente; e vendo Salomão a este jovem, que era laborioso, ele o pôs sobre todo o cargo da casa de José\" (11:28). Aías lhe deu dez pedaços de uma capa nova e uma promessa condicional imensa: se andasse nos caminhos de Deus, \"te edificarei uma casa firme, como edifiquei a Davi\" (11:38). Salomão tentou matá-lo, e ele fugiu ao Egito, a Sisaque (11:40). Voltou como porta-voz do povo em Siquém e recebeu dez tribos das mãos de Deus. E então, com o reino já na mão, fez as contas do medo no coração: se o povo subisse a Jerusalém para sacrificar, voltaria a Roboão \"e me matarão\" (12:27). Da política de sobrevivência nasceu o pecado que nomeou uma dinastia inteira: \"fez dois bezerros de ouro; e lhes disse: Muito trabalho vos será o subir a Jerusalém; vês aqui teus deuses, ó Israel, que te fizeram subir da terra do Egito\" (12:28), a mesma frase do bezerro de Arão. \"E pôs um em Betel, e colocou o outro em Dã\" (12:29), inventou uma festa no oitavo mês e \"constituiu sacerdotes dos mais baixos do povo, que não eram dos filhos de Levi\" (12:31). Em Betel, quando estendeu a mão contra o profeta, \"a sua mão, que estendera contra ele, se secou\" (13:4) — e a mão foi restituída pela oração do mesmo homem que ele quisera prender, sem que nada mudasse nele: \"Nem depois destas coisas deixou Jeroboão o seu mau caminho\" (13:33). Ficou na Bíblia como a fórmula do desastre do norte: aquele \"que fez pecar a Israel\" (14:16).",
  },
  "mulher-de-jeroboao": {
    title: "A mulher de Jeroboão",
    subtitle: "A rainha disfarçada que perdeu o filho no limiar (1Rs 14:2)",
    text: "Quando Abias adoeceu, o rei mandou a própria esposa em missão de espionagem religiosa: \"Levanta-te agora, e disfarça-te, para que não conheçam que és mulher de Jeroboão; e vai a Siló\" (14:2) — atrás do mesmo profeta que lhe dera o reino, agora consultado às escondidas como se fosse um adivinho de aldeia. Ela levou a paga humilde combinada, \"dez pães, e bolos, e uma botija de mel\" (14:3), e entrou na casa de um cego. Deus, porém, tinha avisado Aías: \"há de ser que, entrando ela, fingirá ser outra\" (14:5). E veio a saudação que desmontou tudo à porta: \"Entra, mulher de Jeroboão; por que te disfarças assim? Pois eu sou enviado a ti com duras novas\" (14:6). Ouviu de pé a sentença sobre a casa do marido e sobre o próprio filho, e a única misericórdia foi a mais dolorosa de todas: só aquele menino teria sepultura, \"porquanto se achou nele coisa boa para com o Senhor Deus de Israel em casa de Jeroboão\" (14:13). Voltou sabendo que a morte a esperava no fim do caminho: \"chegando ela ao limiar da porta, morreu o menino\" (14:17). Não tem nome no livro; tem só o passo que a denunciou e a soleira em que o filho lhe morreu.",
  },
  "roboao": {
    title: "Roboão",
    subtitle: "O filho de Salomão que partiu o reino em Siquém (1Rs 12)",
    text: "Foi a Siquém para ser feito rei e encontrou um povo com uma queixa concreta: \"Teu pai agravou o nosso jugo; agora, pois, alivia tu a dura servidão de teu pai\" (12:4). Pediu três dias e ouviu dois conselhos. Os anciãos lhe deram o retrato do reinado que salva: \"Se hoje fores servo deste povo, e o servires, e respondendo-lhe, lhe falares boas palavras, todos os dias serão teus servos\" (12:7). \"Porém ele deixou o conselho que os anciãos lhe tinham dado\" (12:8) e escolheu os que haviam crescido com ele, que lhe ensinaram a fanfarronice: \"Meu dedo mínimo é mais grosso do que os lombos de meu pai\" (12:10). No terceiro dia \"o rei respondeu ao povo duramente\" (12:13): \"meu pai vos castigou com açoites, porém eu vos castigarei com escorpiões\" (12:14). Dez tribos responderam com o grito que rasgou Israel em dois: \"Que parte temos nós com Davi?\" (12:16). Mandou Adorão, o da leva, e o viu ser apedrejado; escapou por pouco, \"o rei Roboão se animou a subir ao carro para fugir para Jerusalém\" (12:18). Ajuntou cento e oitenta mil homens para reconquistar o norte, e desistiu à palavra de Semaías (12:21-24). Reinou dezessete anos em Judá; sob ele o povo edificou altos e imagens de Aserá (14:23), Sisaque levou os tesouros do templo, e \"era o nome de sua mãe Naamá, amonita\" (14:21). \"porque esta revolta vinha do Senhor\" (12:15): a soberania de Deus não desculpou a estupidez do rei, apenas se serviu dela.",
  },
  "adorao": {
    title: "Adorão",
    subtitle: "O encarregado dos tributos, apedrejado pelo povo (1Rs 12:18)",
    text: "Aparece uma só vez, e para morrer. Diante da revolta das dez tribos, Roboão não mandou negociador nem sacerdote: mandou o cobrador. \"Então o rei Roboão enviou a Adorão, que estava sobre os tributos; e todo o Israel o apedrejou, e ele morreu\" (12:18). O nome está ligado ao mesmo ofício que Salomão criara — Adonirão, filho de Abda, \"sobre o tributo\" (4:6), e o mesmo Adonirão \"estava sobre a leva de gente\" que subia mês a mês ao Líbano (5:14). Era o rosto visível do jugo pesado de que o povo se queixara em Siquém, e foi nele que a raiva de vinte anos de trabalho forçado se descarregou. O rei, que não soubera ouvir, ainda mandou adiante o homem mais odiado do reino, e depois escapou de carro (12:18). É a lição amarga dos funcionários de reis imprudentes: quem paga a conta da soberba do trono raramente é quem se senta nele.",
  },
  "sisaque": {
    title: "Sisaque",
    subtitle: "O rei do Egito que levou os escudos de ouro (1Rs 14:25)",
    text: "Aparece primeiro como asilo político: fugindo de Salomão, \"Jeroboão se levantou, e fugiu para o Egito, a ter com Sisaque, rei do Egito; e esteve no Egito até que Salomão morreu\" (11:40) — o Egito outra vez abrigando aquele que Israel queria matar. Depois volta como cobrador do juízo: \"no quinto ano do rei Roboão, Sisaque, rei do Egito, subiu contra Jerusalém\" (14:25). Não houve batalha narrada, houve esvaziamento: \"E tomou os tesouros da casa do Senhor e os tesouros da casa do rei; e levou tudo. Também tomou todos os escudos de ouro que Salomão tinha feito\" (14:26). E então vem um dos detalhes mais tristes de todo o livro dos Reis: \"em lugar deles fez o rei Roboão escudos de cobre\" (14:27), guardados na câmara da guarda e levados na entrada do rei como se nada tivesse mudado. Cinco anos depois da glória de Salomão, a mesma pompa continuava a desfilar — só que em metal barato. É assim que a decadência costuma começar: sem estrondo, trocando o ouro pelo cobre e mantendo o cerimonial.",
  },
  "homem-de-deus-de-juda": {
    title: "O homem de Deus que veio de Judá",
    subtitle: "O que clamou contra o altar de Betel e morreu no caminho (1Rs 13)",
    text: "\"E eis que, por ordem do SENHOR, veio, de Judá a Betel, um homem de Deus; e Jeroboão estava junto ao altar, para queimar incenso\" (13:1). Não falou ao rei: falou à pedra. \"Altar, altar! Assim diz o Senhor: Eis que um filho nascerá à casa de Davi, cujo nome será Josias, o qual sacrificará sobre ti os sacerdotes dos altos\" (13:2) — profecia que nomeou um rei trezentos anos antes de ele nascer, e que 2 Reis 23 veria cumprir-se letra por letra. Deu um sinal na hora: \"Eis que o altar se fenderá, e a cinza, que nele está, se derramará\" (13:3), e assim se fendeu; a mão do rei estendida contra ele secou, e ele orou por essa mão e ela sarou (13:4-6). Recusou o convite do palácio com uma firmeza exemplar: \"Ainda que me desses metade da tua casa, não iria contigo, nem comeria pão nem beberia água neste lugar\" (13:8). Resistiu ao rei — e caiu diante de um velho da mesma profissão que lhe disse \"Também eu sou profeta como tu\" (13:18). Voltou, comeu, e ouviu a sentença à própria mesa (13:21-22); no caminho \"um leão o encontrou no caminho, e o matou\" (13:24), e o prodígio ficou parado na estrada para que ninguém pensasse em acaso: \"o leão não tinha devorado o corpo, nem tinha despedaçado o jumento\" (13:28). A palavra que ele pregou se cumpriu; a que ele desobedeceu também. Nenhum púlpito dispensa a obediência de quem sobe nele.",
  },
  "profeta-velho-de-betel": {
    title: "O velho profeta de Betel",
    subtitle: "O que mentiu e depois pranteou \"Ah, irmão meu!\" (1Rs 13:11,30)",
    text: "\"E morava em Betel um velho profeta\" (13:11) — morava, isto é, tinha ficado; vivia na cidade do bezerro e não clamara contra o altar. Ouviu dos filhos o que o forasteiro de Judá fizera, mandou albardar o jumento e o foi buscar: \"achou-o assentado debaixo de um carvalho\" (13:14). Diante da recusa, usou a única arma que o outro não sabia repelir — a autoridade profética: \"Também eu sou profeta como tu, e um anjo me falou por ordem do Senhor, dizendo: Faze-o voltar contigo à tua casa\" (13:18). O texto acrescenta o parêntese seco que julga tudo: \"porém mentiu-lhe\". E então acontece o mais estranho: à mesa, a palavra verdadeira do SENHOR veio justamente sobre ele, e foi o mentiroso quem teve de anunciar a morte do homem que enganara (13:20-22). Foi buscar o cadáver, pôs no seu próprio sepulcro e chorou como irmão: \"prantearam-no, dizendo: Ah, irmão meu!\" (13:30). Depois mandou aos filhos: \"ponde os meus ossos junto aos ossos dele\" (13:31), porque acreditava que a palavra contra o altar de Betel se cumpriria — e, séculos depois, foram esses ossos misturados que salvaram o seu sepulcro da fogueira de Josias (2Rs 23:18). Um homem pode mentir em nome de Deus e ainda assim tremer diante do que Deus disse. O arrependimento chegou; o dano, não voltou atrás.",
  },
  "asa": {
    title: "Asa",
    subtitle: "O rei de Judá que depôs a própria avó e queimou o ídolo dela (1Rs 15:11-13)",
    text: "Depois de dois reinados maus, Judá respirou: \"E Asa fez o que era reto aos olhos do Senhor, como Davi seu pai\" (15:11). Limpou a terra — \"tirou da terra os sodomitas, e removeu todos os ídolos que seus pais fizeram\" (15:12) — e foi até onde quase nenhum rei chega, ao próprio sangue: \"E até a Maaca, sua mãe, removeu para que não fosse rainha, porquanto tinha feito um horrível ídolo a Aserá; também Asa desfez o seu ídolo horrível, e o queimou junto ao ribeiro de Cedrom\" (15:13). O texto chama-lhe \"sua mãe\" no sentido de rainha-mãe, pois Maaca fora mulher de Abias, seu pai (15:2): quem ele depôs foi a avó, e queimou publicamente, no vale, o ídolo que ela mandara fazer. Ainda assim a reforma teve limite: \"Os altos, porém, não foram tirados; todavia foi o coração de Asa reto para com o Senhor todos os seus dias\" (15:14). E teve deslize: pressionado por Baasa, esvaziou os tesouros do templo para comprar a espada da Síria — \"Haja acordo entre mim e ti, como houve entre meu pai e teu pai\" (15:19) —, e Ben-Hadade feriu por ele as cidades do norte. Reinou quarenta e um anos, e \"no tempo da sua velhice, padeceu dos pés\" (15:23). Rei bom, reforma pela metade, fé que ao fim se apoiou na cavalaria alheia.",
  },
  "maaca": {
    title: "Maaca",
    subtitle: "A rainha-mãe deposta por causa do ídolo de Aserá (1Rs 15:13)",
    text: "Filha de Absalão e mulher de Roboão, é nomeada duas vezes com a mesma fórmula: \"era o nome de sua mãe Maaca, filha de Absalão\", para Abias (15:2) e ainda para Asa, seu neto (15:10) — sinal de que conservou o posto de rainha-mãe atravessando dois reinados, um poder que em Judá não era pequeno. Usou esse poder para uma coisa só que o texto registra: \"tinha feito um horrível ídolo a Aserá\" (15:13). O neto, no auge da reforma, tirou-lhe o cargo: \"E até a Maaca, sua mãe, removeu para que não fosse rainha\", e o ídolo não foi guardado nem escondido — \"também Asa desfez o seu ídolo horrível, e o queimou junto ao ribeiro de Cedrom\". Uma neta de Absalão, dentro do palácio de Davi, fabricando aquilo que a Lei mandava destruir; e o culto que ela sustentou não morreu com ela — as imagens de Aserá tinham brotado \"sobre todo o alto outeiro e debaixo de toda a árvore verde\" já nos dias de Roboão (14:23). É a demonstração de que a idolatria de Judá não veio só de fora: brotou da própria casa real, e foi preciso um rei disposto a enfrentar a própria família para arrancá-la.",
  },
  "baasa": {
    title: "Baasa",
    subtitle: "O de Issacar que exterminou a casa de Jeroboão e repetiu-lhe os pecados (1Rs 15:27)",
    text: "\"E conspirou contra ele Baasa, filho de Aías, da casa de Issacar, e feriu-o Baasa em Gibetom, que era dos filisteus\" (15:27) — matou Nadabe no cerco e tomou o trono no ano terceiro de Asa. Foi ele o instrumento visível de uma sentença antiga: \"feriu a toda a casa de Jeroboão; nada de Jeroboão deixou que tivesse fôlego, até o destruir, conforme à palavra do Senhor que dissera pelo ministério de seu servo Aías, o silonita\" (15:29). E aqui está a ironia que o livro faz questão de sublinhar: cumprir o juízo de Deus não santificou quem o executou. \"E fez o que era mau aos olhos do Senhor; e andou no caminho de Jeroboão\" (15:34) — matou a casa do pecado e adotou o pecado da casa. Reinou vinte e quatro anos em Tirza, guerreou com Asa e fortificou Ramá para asfixiar Judá (15:17,32). Então veio Jeú, filho de Hanani, com uma acusação em duas partes: \"Porquanto te levantei do pó, e te pus por príncipe sobre o meu povo Israel, e tu tens andado no caminho de Jeroboão\" (16:2), e ainda \"porque o havia ferido\" (16:7). A mesma sentença dada a Jeroboão caiu sobre ele, palavra por palavra: \"Quem morrer dos de Baasa, na cidade, os cães o comerão\" (16:4). Foi enterrado em Tirza, e Zinri não deixou da sua casa \"homem algum, nem a seus parentes, nem a seus amigos\" (16:11).",
  },
  "ela": {
    title: "Elá",
    subtitle: "O rei de Israel morto bêbado na casa do mordomo (1Rs 16:9)",
    text: "\"Elá, filho de Baasa, começou a reinar em Tirza sobre Israel; e reinou dois anos\" (16:8). Não há dele nenhum ato, nenhuma guerra, nenhuma palavra: o livro guarda apenas onde ele estava quando morreu. \"E Zinri, seu servo, capitão de metade dos carros, conspirou contra ele, estando ele em Tirza, bebendo e embriagando-se em casa de Arsa, mordomo em Tirza\" (16:9). O pai morrera na cama e fora sepultado com honra; o filho morreu à mesa de um funcionário, sem defesa e sem juízo: \"Entrou, pois, Zinri, e o feriu, e o matou\" (16:10). A sentença dada a Baasa cumpriu-se nele e na parentela toda, \"Por todos os pecados de Baasa, e os pecados de Elá, seu filho, que cometeram, e com que fizeram pecar a Israel, irritando ao Senhor Deus de Israel com as suas vaidades\" (16:13). Duas linhas de reinado e um cálice na mão: o retrato de um trono que já não governava nada, nem a si mesmo.",
  },
  "zinri": {
    title: "Zinri",
    subtitle: "Sete dias de reinado, que queimou o paço sobre si (1Rs 16:15,18)",
    text: "Capitão de metade dos carros de Elá, matou o senhor a quem servia enquanto este bebia (16:9-10) e sentou-se no trono. Mal se assentou, \"feriu a toda a casa de Baasa; não lhe deixou homem algum, nem a seus parentes, nem a seus amigos\" (16:11), cumprindo sem o saber a palavra de Jeú, filho de Hanani (16:12). Mas o exército estava acampado contra Gibetom, e a notícia correu: \"Zinri tem conspirado, e até matou o rei\" (16:16). No mesmo dia, no arraial, as tropas proclamaram Onri, subiram e cercaram Tirza. \"No ano vigésimo sétimo de Asa, rei de Judá, reinou Zinri sete dias em Tirza\" (16:15) — sete dias, o reinado mais curto de Israel. E o fim foi feito por ele mesmo: \"Zinri, vendo que a cidade era tomada, foi ao paço da casa do rei e queimou-a sobre si; e morreu\" (16:18). Não faltou coragem, faltou tudo o mais; o epitáfio que o texto lhe dá é o mesmo dos outros, \"Por causa dos pecados que cometera, fazendo o que era mau aos olhos do Senhor\" (16:19). Uma semana bastou para provar que tomar um trono e sustentá-lo são coisas diferentes.",
  },
  "onri": {
    title: "Onri",
    subtitle: "O capitão do exército que comprou o monte de Samaria (1Rs 16:24)",
    text: "Chegou ao poder pelo caminho mais direto: o arraial o aclamou. \"Todo o Israel pois, no mesmo dia, no arraial, constituiu rei sobre Israel a Onri, capitão do exército\" (16:16); ele subiu de Gibetom, cercou Tirza e recebeu o reino das mãos do fogo em que Zinri se matou. Ainda teve de vencer uma guerra civil de anos: \"metade do povo seguia a Tibni, filho de Ginate, para o fazer rei, e a outra metade seguia a Onri\" (16:21), até que \"Tibni morreu, e Onri reinou\" (16:22). Sua obra mais duradoura foi um negócio imobiliário: \"E de Semer comprou o monte de Samaria por dois talentos de prata, e edificou nele; e chamou a cidade que edificou Samaria, do nome de Semer, dono do monte\" (16:24) — deu ao reino do norte uma capital em posição forte, que carregaria o nome do vendedor por toda a Escritura até o Novo Testamento. Os anais do mundo lembram Onri como o fundador de uma dinastia poderosa; a Escritura o despacha em quatro versículos com uma frase: \"E fez Onri o que era mau aos olhos do Senhor; e fez pior do que todos quantos foram antes dele\" (16:25). Deus mede reis por outra régua que não a dos historiadores.",
  },
  "acabe": {
    title: "Acabe",
    subtitle: "O rei de Israel que fez mais mal do que todos antes dele (1Rs 16:30)",
    text: "\"E fez Acabe, filho de Onri, o que era mau aos olhos do Senhor, mais do que todos os que foram antes dele\" (16:30), e o texto explica por quê: os bezerros de Jeroboão já lhe pareciam pouco, e \"ainda tomou por mulher a Jezabel, filha de Etbaal, rei dos sidônios; e foi e serviu a Baal, e o adorou\" (16:31), levantando altar e casa a Baal em Samaria. Chamou o profeta de \"És tu o perturbador de Israel?\" (18:17) e depois de \"Já me achaste, inimigo meu?\" (21:20). Não era, porém, um homem de uma peça só: viu o fogo cair no Carmelo e a chuva voltar; poupou Ben-Hadade chamando-lhe \"meu irmão\" (20:32) quando Deus o entregara à destruição; deitou-se na cama com o rosto virado por causa de uma horta, e deixou a mulher matar Nabote em seu nome (21:4-16). O julgamento é implacável e exato: \"Porém ninguém fora como Acabe, que se vendera para fazer o que era mau aos olhos do Senhor; porque Jezabel, sua mulher, o incitava\" (21:25). E, mesmo assim, quando ouviu a sentença, \"rasgou as suas vestes, e cobriu a sua carne de saco, e jejuou; e jazia em saco, e andava mansamente\" (21:27) — e Deus, que vê até a humilhação de um homem vendido, adiou o golpe: \"Não viste que Acabe se humilha perante mim?\" (21:29). Morreu disfarçado em Ramote de Gileade, porque disfarce nenhum desvia uma flecha: \"um homem armou o arco, e atirou a esmo, e feriu o rei de Israel por entre as fivelas e as couraças\" (22:34). Ficou de pé no carro até a tarde, e ao lavarem o carro \"os cães lamberam o seu sangue\" (22:38).",
  },
  "jezabel": {
    title: "Jezabel",
    subtitle: "A filha de Etbaal que armou o jejum e as cartas seladas (1Rs 16:31; 21:8)",
    text: "Princesa fenícia, \"Jezabel, filha de Etbaal, rei dos sidônios\" (16:31), trouxe consigo o culto de Baal para dentro do palácio de Samaria e tratou a fé de Israel como um estorvo administrativo: sustentava à sua mesa \"os quatrocentos profetas de Aserá\" (18:19) enquanto ia \"destruindo Jezabel os profetas do Senhor\" (18:4) — foi por causa dela que Obadias escondeu cem deles em duas covas. Depois do Carmelo, não se abalou nem discutiu: mandou recado, com a serenidade de quem marca hora, \"Assim me façam os deuses, e outro tanto, se de certo amanhã a estas horas não puser a tua vida como a de um deles\" (19:2), e pôs em fuga o homem que enfrentara quatrocentos e cinqüenta. O seu retrato definitivo é a vinha: diante do marido de cara virada para a parede, perguntou \"Governas tu agora no reino de Israel?\" (21:7) e resolveu o assunto com papelada. \"Então escreveu cartas em nome de Acabe, e as selou com o seu sinete\" (21:8), e nelas mandou o roteiro completo — \"Apregoai um jejum, e ponde Nabote diante do povo\" (21:9), dois falsos testemunhos, e o apedrejamento. Usou a religião como instrumento do crime: convocou jejum para matar um justo. A palavra do SENHOR sobre ela é uma das mais duras da Bíblia: \"Os cães comerão a Jezabel junto ao antemuro de Jizreel\" (21:23).",
  },
  "elias": {
    title: "Elias, o tisbita",
    subtitle: "O profeta dos corvos, do fogo do Carmelo e da voz mansa e delicada (1Rs 17–19)",
    text: "Entra na história sem genealogia e sem aviso, \"Elias, o tisbita, dos moradores de Gileade\", plantado diante de Acabe: \"Vive o SENHOR Deus de Israel, perante cuja face estou, que nestes anos nem orvalho nem chuva haverá, senão segundo a minha palavra\" (17:1) — atacou Baal exatamente onde Baal dizia reinar, na chuva. Escondido em Querite, foi sustentado pelo que a Lei chamava imundo: \"E os corvos lhe traziam pão e carne pela manhã; como também pão e carne à noite\" (17:6). Em Sarepta, terra da própria Jezabel, viveu do último punhado de farinha de uma viúva e viu o milagre da provisão diária: \"A farinha da panela não se acabará, e o azeite da botija não faltará\" (17:14). No Carmelo pôs Israel diante da única pergunta que importava — \"Até quando coxeareis entre dois pensamentos? Se o Senhor é Deus, segui-o, e se Baal, segui-o\" (18:21) —, encharcou o altar de água e orou uma oração de trinta segundos; \"Então caiu fogo do Senhor, e consumiu o holocausto, e a lenha, e as pedras, e o pó, e ainda lambeu a água que estava no rego\" (18:38), e o povo caiu de rosto: \"Só o Senhor é Deus!\" (18:39). E no dia seguinte, uma ameaça de mulher o pôs a correr: \"foi sentar-se debaixo de um zimbro; e pediu para si a morte\", dizendo \"Já basta, ó Senhor; toma agora a minha vida, pois não sou melhor do que meus pais\" (19:4). Deus não o repreendeu: mandou um anjo com pão e água, deixou-o dormir, e o levou quarenta dias até Horebe. Ali não estava no vento, nem no terremoto, nem no fogo — \"e depois do fogo uma voz mansa e delicada\" (19:12) —, e a pergunta que ouviu duas vezes foi \"Que fazes aqui, Elias?\" (19:13). À queixa \"só eu fiquei\" (19:14), a resposta desfez a solidão do herói: \"Também deixei ficar em Israel sete mil: todos os joelhos que não se dobraram a Baal\" (19:18). Deus lhe deu trabalho, um sucessor e companhia — e é assim que se cura um profeta esgotado.",
  },
  "viuva-de-sarepta": {
    title: "A viúva de Sarepta",
    subtitle: "A estrangeira que deu o último punhado de farinha (1Rs 17:9)",
    text: "Deus mandou o profeta para fora de Israel, para a terra de Sidom, de onde vinha Jezabel: \"eis que eu ordenei ali a uma mulher viúva que te sustente\" (17:9) — e o \"ordenei\" veio antes de ela saber de nada. Elias a encontrou na porta da cidade, \"uma mulher viúva apanhando lenha\" (17:10), e pediu água e pão a quem estava preparando a última refeição da vida: \"nem um bolo tenho, senão somente um punhado de farinha numa panela, e um pouco de azeite numa botija; e vês aqui apanhei dois cavacos, e vou prepará-lo para mim e para o meu filho, para que o comamos, e morramos\" (17:12). O pedido foi duro — faze primeiro para mim — e ela fez; e o milagre não veio em despensa cheia, veio em fundo de panela que nunca raspava: \"Da panela a farinha não se acabou, e da botija o azeite não faltou\" (17:16). Quando o filho morreu, atirou ao profeta a dor toda: \"Que tenho eu contigo, homem de Deus? vieste tu a mim para trazeres à memória a minha iniqüidade, e matares a meu filho?\" (17:18). Recebeu-o vivo das mãos de Elias e fez a confissão que fecha o capítulo: \"Nisto conheço agora que tu és homem de Deus, e que a palavra do Senhor na tua boca é verdade\" (17:24). Jesus a citaria em Nazaré, para escândalo dos seus: em Israel havia muitas viúvas, e o profeta foi enviado a esta (Lc 4:25-26).",
  },
  "filho-da-viuva-de-sarepta": {
    title: "O filho da viúva de Sarepta",
    subtitle: "O menino que morreu e tornou a viver (1Rs 17:17-23)",
    text: "É o menino por quem a mãe preparava o último bolo antes de morrerem juntos de fome (17:12), e que sobreviveu à fome para adoecer depois: \"adoeceu o filho desta mulher, dona da casa; e a sua doença se agravou muito, até que nele nenhum fôlego ficou\" (17:17). Elias o tomou do regaço da mãe, subiu com ele ao quarto onde morava, deitou-o na sua própria cama e discutiu com Deus: \"Ó Senhor meu Deus, também até a esta viúva, com quem me hospedo, afligiste, matando-lhe o filho?\" (17:20). Então fez o gesto mais estranho e mais corporal de toda a profecia antiga: \"se estendeu sobre o menino três vezes, e clamou ao Senhor, e disse: Ó Senhor meu Deus, rogo-te que a alma deste menino torne a entrar nele\" (17:21). \"E o Senhor ouviu a voz de Elias; e a alma do menino tornou a entrar nele, e reviveu\" (17:22). É a primeira ressurreição registrada na Escritura, e ela não acontece no templo nem em Jerusalém, mas no quarto de cima de uma casa pobre em terra de sidônios. Elias desceu com ele nos braços e disse à mãe as três palavras que a Bíblia repetiria em Naim e em Betânia: \"Vês aí, teu filho vive\" (17:23).",
  },
  "obadias-mordomo": {
    title: "Obadias",
    subtitle: "O mordomo de Acabe que escondeu cem profetas em duas covas (1Rs 18:3-4)",
    text: "\"E Acabe chamou a Obadias, o mordomo; e Obadias temia muito ao Senhor\" (18:3): as duas metades da frase estão em tensão o livro inteiro — mordomo-mor da casa de Acabe e Jezabel, e homem tementíssimo a Deus. Enquanto a rainha varria os profetas do SENHOR, ele montou uma operação de resgate dentro do próprio palácio: \"Obadias tomou cem profetas, e de cinqüenta em cinqüenta os escondeu numa cova, e os sustentou com pão e água\" (18:4) — e, em plena seca, alimentar cem homens escondidos era gastar o que não havia. Enviado pelo rei a procurar erva para os cavalos, encontrou Elias no caminho e caiu por terra: \"prostrou-se sobre o seu rosto, e disse: És tu o meu senhor Elias?\" (18:7). Teve medo de ser morto por anunciá-lo e alegou o seu currículo com uma sinceridade comovente: \"eu, teu servo, temo ao Senhor desde a minha mocidade\" (18:12), e \"Como escondi a cem homens dos profetas do SENHOR, de cinqüenta em cinqüenta, numa cova, e os sustentei com pão e água?\" (18:13). Não subiu ao Carmelo nem chamou fogo do céu; salvou cem vidas com pão, água e silêncio. Ao lado do profeta que enfrenta reis, a Escritura põe o funcionário fiel que serve dentro da casa errada sem se vender a ela.",
  },
  "eliseu": {
    title: "Eliseu",
    subtitle: "O lavrador das doze juntas, chamado pela capa de Elias (1Rs 19:19)",
    text: "Deus o nomeou antes de ele saber: \"a Eliseu, filho de Safate de Abel-Meolá, ungirás profeta em teu lugar\" (19:16) — resposta do céu a um profeta que pedira a morte debaixo de um zimbro. Elias o encontrou no trabalho: \"achou a Eliseu, filho de Safate, que andava lavrando com doze juntas de bois adiante dele, e ele estava com a duodécima\" (19:19), sinal de uma casa próspera, com terra e gado que ele estava para herdar. O chamado veio sem discurso, sem oráculo, sem imposição de mãos: \"e lançou a sua capa sobre ele\". Ele correu atrás e pediu só uma coisa: \"Deixa-me beijar a meu pai e a minha mãe, e então te seguirei\" (19:20). Voltou — e a despedida foi um incêndio: \"tomou a junta de bois, e os matou, e com os aparelhos dos bois cozeu as carnes, e as deu ao povo, e comeram\" (19:21). Queimou o arado para cozinhar os próprios bois e repartiu o banquete com a aldeia: não deixou meio de voltar atrás. \"então se levantou e seguiu a Elias, e o servia\" — e por anos a sua função foi essa, servir, antes de qualquer milagre. Quem põe a mão no arado e olha para trás não é apto (Lc 9:62); Eliseu resolveu o problema queimando o arado.",
  },
  "ben-hadade": {
    title: "Ben-Hadade",
    subtitle: "O rei da Síria dos trinta e dois reis, poupado por Acabe (1Rs 20)",
    text: "Rei de Damasco, aparece primeiro como espada de aluguel: Asa lhe mandou a prata e o ouro do templo, e ele feriu por encomenda as cidades do norte de Israel (15:18-20). Depois sobe como senhor de guerra, com trinta e dois reis vassalos, e cerca Samaria exigindo tudo: \"A tua prata e o teu ouro são meus; e tuas mulheres e os melhores de teus filhos são meus\" (20:3). Gabou-se de que \"o pó de Samaria não bastará para encher as mãos de todo o povo que me segue\" (20:10) e recebeu de volta o provérbio que o desmascarou: \"Não se gabe quem se cinge das armas, como aquele que as descinge\" (20:11). Foi derrotado à hora do meio-dia enquanto \"estava bebendo e embriagando-se nas tendas, ele e os reis, os trinta e dois reis\" (20:16). No ano seguinte voltou com a teologia dos seus conselheiros: \"Seus deuses são deuses dos montes, por isso foram mais fortes do que nós; mas pelejemos com eles em campo raso\" (20:23) — e o SENHOR o desmentiu em pessoa, com o vale escolhido por ele: \"Porquanto os sírios disseram: O Senhor é Deus dos montes, e não Deus dos vales; toda esta grande multidão entregarei nas tuas mãos\" (20:28). Escondendo-se de câmara em câmara em Afeque, salvou-se pela reputação alheia: \"ponhamos, pois, sacos aos lombos, e cordas às cabeças\" (20:31), e a mensagem \"Diz o teu servo Ben-Hadade: Deixa-me viver\" (20:32) fez Acabe abrir os braços — \"Pois ainda vive? É meu irmão\". A clemência mal colocada custou a Acabe a própria vida (20:42).",
  },
  "nabote": {
    title: "Nabote, o jizreelita",
    subtitle: "O que não vendeu a herança de seus pais (1Rs 21:3)",
    text: "\"Nabote, o jizreelita, tinha uma vinha em Jizreel junto ao palácio de Acabe, rei de Samaria\" (21:1) — a proximidade é a tragédia: o rei queria uma horta e o vizinho tinha a terra. A oferta era justa por qualquer critério de mercado, outra vinha melhor ou o valor em dinheiro (21:2). A recusa não foi de preço, foi de fé: \"Guarde-me o Senhor de que eu te dê a herança de meus pais\" (21:3). Em Israel a terra não era mercadoria, era porção recebida do SENHOR e guardada para os filhos (Lv 25:23; Nm 36:7), e Nabote sabia disso melhor do que o seu rei. Morreu por causa dessa lealdade, e pelo instrumento mais cínico possível: um culto. \"Apregoai um jejum, e ponde Nabote diante do povo\" (21:9); dois filhos de Belial juraram \"Nabote blasfemou contra Deus e contra o rei\", e os anciãos e nobres da sua própria cidade obedeceram às cartas seladas — \"E o levaram para fora da cidade, e o apedrejaram, e morreu\" (21:13). O julgamento veio pela boca de Elias, na vinha ainda quente: \"No lugar em que os cães lamberam o sangue de Nabote lamberão também o teu próprio sangue\" (21:19). Deus não esqueceu um pequeno proprietário assassinado por um jejum falso; nenhum sangue de justo cai na terra sem que o céu tome nota.",
  },
  "micaias": {
    title: "Micaías, filho de Inlá",
    subtitle: "O profeta de quem Acabe dizia que nunca lhe profetizava o bem (1Rs 22:8)",
    text: "Estava preso, ou pelo menos afastado, e o rei o descreveu antes de o chamar: \"Ainda há um homem por quem podemos consultar ao Senhor; porém eu o odeio, porque nunca profetiza de mim o que é bom, mas só o mal; este é Micaías, filho de Inlá\" (22:8). O mensageiro tentou comprá-lo pelo caminho, sugerindo que falasse como os quatrocentos, e ouviu a única regra do ofício: \"Vive o Senhor que o que o Senhor me disser isso falarei\" (22:14). Diante dos dois tronos, começou pela ironia, repetindo o coro dos profetas de corte — \"Sobe, e serás bem sucedido\" (22:15) — até que o rei, sem perceber a armadilha, o conjurou a dizer a verdade. Então veio a visão do exército disperso: \"Vi a todo o Israel disperso pelos montes, como ovelhas que não tem pastor\" (22:17), isto é, o rei já morto. E veio a cena mais assombrosa: \"Vi ao Senhor assentado sobre o seu trono, e todo o exército do céu estava junto a ele\" (22:19), e um espírito que se ofereceu — \"Eu sairei, e serei um espírito de mentira na boca de todos os seus profetas\" (22:22). Levou uma bofetada de Zedequias e foi mandado ao cárcere \"com o pão de angústia, e com água de amargura, até que eu venha em paz\" (22:27). Respondeu com a aposta de toda a sua vida: \"Se tu voltares em paz, o Senhor não tem falado por mim\" (22:28). Acabe não voltou. Quatrocentos concordaram e erraram; um discordou e tinha razão — porque a verdade não se decide por maioria.",
  },
  "zedequias-filho-de-quenaana": {
    title: "Zedequias, filho de Quenaaná",
    subtitle: "O dos chifres de ferro, que esbofeteou Micaías (1Rs 22:11,24)",
    text: "Porta-voz dos quatrocentos profetas de corte, entendeu que uma palavra bonita rende mais quando vem com encenação: \"E Zedequias, filho de Quenaaná, fez para si uns chifres de ferro, e disse: Assim diz o Senhor: Com estes ferirás aos sírios, até de todo os consumir\" (22:11). Usou a fórmula dos verdadeiros profetas — \"Assim diz o Senhor\" — e um símbolo tirado da bênção de Moisés a José (Dt 33:17), para dizer ao rei exatamente o que o rei queria ouvir. Quando Micaías revelou o espírito de mentira posto na boca dos profetas, não argumentou: bateu. \"Então Zedequias, filho de Quenaaná, chegou, e feriu a Micaías no queixo, e disse: Por onde saiu de mim o Espírito do Senhor para falar a ti?\" (22:24) — a pergunta de quem tem certeza absoluta de estar do lado de Deus. A resposta foi um endereço e uma data: \"Eis que o verás naquele mesmo dia, quando entrares de câmara em câmara para te esconderes\" (22:25). É o retrato do falso profeta em três traços: o cenário, a fórmula sagrada e a violência contra quem contradiz. Sinceridade não é credencial; sinceramente enganado, ele levou um rei à morte.",
  },
  "josafa": {
    title: "Jeosafá",
    subtitle: "O rei de Judá que pediu para consultar a palavra do SENHOR (1Rs 22:5)",
    text: "Filho de Asa, reinou vinte e cinco anos em Jerusalém e \"andou em todos os caminhos de seu pai Asa, não se desviou deles, fazendo o que era reto aos olhos do Senhor\" (22:43); \"era o nome de sua mãe Azuba, filha de Sili\" (22:42). Fez a paz com o reino do norte depois de gerações de guerra — \"E Jeosafá esteve em paz com o rei de Israel\" (22:45) —, e essa paz foi ao mesmo tempo a sua virtude e a sua armadilha. Aliou-se a Acabe com uma entrega quase excessiva: \"Serei como tu, e o meu povo como o teu povo, e os meus cavalos como os teus cavalos\" (22:4). Mas, no meio do entusiasmo militar, foi ele — não o rei de Israel — quem se lembrou de Deus: \"Peço-te, consulta hoje a palavra do Senhor\" (22:5); e, ouvindo os quatrocentos aplaudirem em coro, insistiu com a pergunta que salva reinos: \"Não há aqui ainda algum profeta do Senhor, ao qual possamos consultar?\" (22:7). Ao ouvir Acabe reclamar de Micaías, repreendeu-o com delicadeza: \"Não fale o rei assim\" (22:8). Ainda assim subiu à batalha, vestido de rei enquanto o aliado se disfarçava, e quase morreu por isso: \"porém Jeosafá gritou\" (22:32), e os capitães o largaram. \"Todavia os altos não se tiraram\" (22:44), e os seus navios de Társis se quebraram em Eziom-Geber (22:49). Um rei bom, que perguntava certo e escolhia mal as companhias.",
  },
  "abiao": {
    title: "Abias, rei de Judá",
    subtitle: "O rei mau a quem foi dada uma lâmpada por amor de Davi (1Rs 15:1-5)",
    text: "Subiu ao trono \"no décimo oitavo ano do rei Jeroboão, filho de Nebate\" (15:1), e o seu reinado inteiro cabe num versículo: \"E reinou três anos em Jerusalém; e era o nome de sua mãe Maaca, filha de Absalão\" (15:2) — três anos apenas, e o veredicto é seco: \"E andou em todos os pecados que seu pai tinha cometido antes dele; e seu coração não foi perfeito para com o Senhor seu Deus como o coração de Davi, seu pai\" (15:3). O que segura a casa em pé não é ele: \"Mas por amor de Davi o Senhor seu Deus lhe deu uma lâmpada em Jerusalém, levantando a seu filho depois dele, e confirmando a Jerusalém\" (15:4). A lâmpada é a promessa feita a Davi, e ela arde num reinado que não a merece — o trono continua porque Deus prometeu, não porque o rei serviu. O texto ainda explica em que consistia a fidelidade de Davi, e com uma honestidade rara: \"não se tinha desviado de tudo quanto lhe ordenara em todos os dias da sua vida, senão só no negócio de Urias, o heteu\" (15:5). Guerreou com o norte todos os seus dias (15:7) e deixou o trono a Asa, que faria o que ele não fez. Não confundir com Abias, o menino filho de Jeroboão, que morreu em Tirza no mesmo período (14:17).",
  },
  "nadabe": {
    title: "Nadabe",
    subtitle: "O filho de Jeroboão, morto no cerco de Gibetom (1Rs 15:25-28)",
    text: "\"E Nadabe, filho de Jeroboão, começou a reinar sobre Israel no ano segundo de Asa, rei de Judá; e reinou sobre Israel dois anos\" (15:25). Herdou o trono e, com ele, o culto dos bezerros: \"E fez o que era mau aos olhos do Senhor; e andou nos caminhos de seu pai, e no seu pecado com que seu pai fizera pecar a Israel\" (15:26). Morreu em campanha, cercando uma cidade filisteia, traído por um dos seus: Baasa \"feriu-o Baasa em Gibetom, que era dos filisteus, quando Nadabe e todo o Israel cercavam a Gibetom\" (15:27), \"E matou-o, pois, Baasa no ano terceiro de Asa, rei de Judá, e reinou em seu lugar\" (15:28). Com ele acabou a casa de Jeroboão, que Aías anunciara e Baasa executou sem deixar \"que tivesse fôlego\" (15:29). Foi o irmão do menino Abias, o único da família a quem coube pranto e sepultura — e a diferença entre os dois destinos foi só uma: naquele \"se achou nele coisa boa para com o Senhor Deus de Israel\" (14:13), neste não se achou nada.",
  },
  "tibni": {
    title: "Tibni, filho de Ginate",
    subtitle: "O rei que metade de Israel seguiu e que a história perdeu (1Rs 16:21)",
    text: "Depois dos sete dias de Zinri, o reino do norte não teve um sucessor, teve dois: \"Então o povo de Israel se dividiu em dois partidos: metade do povo seguia a Tibni, filho de Ginate, para o fazer rei, e a outra metade seguia a Onri\" (16:21). Não sabemos de que tribo era, nem o que prometeu, nem quanto tempo durou a disputa — só que metade de Israel apostou nele. O desfecho cabe num versículo: \"Mas o povo que seguia a Onri foi mais forte do que o povo que seguia a Tibni, filho de Ginate; e Tibni morreu, e Onri reinou\" (16:22). O texto não diz que Deus o levantou nem que o rejeitou; não lhe dá sequer a fórmula de juízo que dá a todos os reis. É uma nota de rodapé sangrenta sobre um reino que já trocara três dinastias em poucos anos, e um lembrete de como a Escritura mede as coisas: a força que decidiu quem reinaria em Samaria não rendeu mais do que duas linhas.",
  },
  "semaias": {
    title: "Semaías",
    subtitle: "O homem de Deus que impediu a guerra entre irmãos (1Rs 12:22-24)",
    text: "Roboão já tinha o exército pronto — \"cento e oitenta mil escolhidos, destros para a guerra\" (12:21) — para retomar à força as dez tribos e reunificar o reino. Foi então que \"veio a palavra de Deus a Semaías, homem de Deus\" (12:22), mandando falar não só ao rei, mas a toda a casa de Judá, a Benjamim e ao restante do povo — porque a ordem tinha de chegar a quem já estava com a espada na mão. A mensagem é curta e desmonta o argumento inteiro: \"Assim diz o Senhor: Não subireis nem pelejareis contra vossos irmãos, os filhos de Israel; volte cada um para a sua casa, porque eu é que fiz esta obra\" (12:24). Duas coisas ali: são irmãos, e a divisão é obra de Deus, não acidente de política. E aconteceu o milagre mais raro do livro dos Reis — obedeceram: \"E ouviram a palavra do Senhor, e voltaram segundo a palavra do Senhor\". Um profeta sem sinais, sem fogo e sem confronto evitou uma guerra civil entre cento e oitenta mil homens dizendo uma frase. Nem todo ministério profético é espetacular; alguns apenas mandam o povo para casa, e salvam uma geração.",
  },
  "jeu-filho-de-hanani": {
    title: "Jeú, filho de Hanani",
    subtitle: "O profeta que sentenciou a casa de Baasa (1Rs 16:1)",
    text: "\"Então veio a palavra do SENHOR a Jeú, filho de Hanani, contra Baasa\" (16:1) — não é o Jeú, filho de Ninsi, que Elias receberia ordem de ungir rei (19:16), mas um profeta, filho de profeta, cuja família reaparece em Judá gerações depois. A sua mensagem começa lembrando a origem humilde do acusado: \"Porquanto te levantei do pó, e te pus por príncipe sobre o meu povo Israel, e tu tens andado no caminho de Jeroboão, e tens feito pecar a meu povo Israel\" (16:2) — o pecado é agravado pelo favor recebido. Depois vem a sentença que copia palavra por palavra a que fora dada à casa que Baasa exterminara: \"farei a tua casa como a casa de Jeroboão, filho de Nebate\" (16:3), \"Quem morrer dos de Baasa, na cidade, os cães o comerão; e o que dele morrer no campo, as aves do céu o comerão\" (16:4). E o oráculo acrescenta um motivo que faz pensar: Baasa é condenado pelo mal que fez \"e porque o havia ferido\" (16:7) — cumpriu o juízo de Deus sobre Jeroboão com as mãos sujas do próprio interesse. Anos mais tarde o narrador registra o cumprimento \"conforme à palavra do Senhor que, contra Baasa, ele falara pelo ministério do profeta Jeú\" (16:12). Deus usa homens maus como vara; e depois julga a vara.",
  },
  "hadade": {
    title: "Hadade, o edomeu",
    subtitle: "O príncipe de Edom criado na casa de Faraó (1Rs 11:14)",
    text: "\"Levantou, pois, o Senhor contra Salomão um adversário, Hadade, o edomeu; ele era da descendência do rei em Edom\" (11:14) — o texto é claro sobre a autoria: o adversário foi levantado por Deus, e a paz do reinado sábio começou a rachar por dentro. A sua história vem de longe: quando Joabe passou seis meses em Edom até destruir \"a todo o homem em Edom\" (11:16), este menino escapou com alguns servos do pai; \"era, porém, Hadade muito jovem\" (11:17). Foi acolhido pelo Egito com honras de casa real: \"E achou Hadade grande graça diante de Faraó, de maneira que lhe deu por mulher a irmã de sua mulher, a irmã de Tafnes, a rainha\" (11:19), e o filho Genubate cresceu \"na casa de Faraó, entre os filhos de Faraó\" (11:20). Ao saber que Davi e Joabe tinham morrido, pediu licença para voltar; Faraó estranhou, e ele repetiu o pedido sem explicar nada: \"Nada, mas todavia despede-me\" (11:22). Não precisava explicar — Faraó sabia. É a memória de uma matança antiga voltando como política externa uma geração depois: o sangue derramado em Edom nos dias de Davi cobrou o preço nos dias de Salomão.",
  },
  "rezom": {
    title: "Rezom, filho de Eliada",
    subtitle: "O chefe de bando que reinou em Damasco (1Rs 11:23)",
    text: "O segundo espinho levantado contra Salomão: \"Também Deus lhe levantou outro adversário, a Rezom, filho de Eliada, que tinha fugido de seu senhor Hadadezer, rei de Zobá\" (11:23). Começou como desertor, virou capitão de bando — \"ajuntou homens, e foi capitão de um esquadrão, quando Davi os matou\" (11:24) — e acabou fundando um poder que atormentaria Israel por séculos: \"e, indo-se para Damasco, habitaram ali, e reinaram em Damasco\". Enquanto Salomão recebia a rainha de Sabá e enchia Jerusalém de prata como pedras, um bandido tomava a cidade da qual sairiam os Ben-Hadades e os Hazaéis que sangrariam o reino do norte. O resumo que o texto lhe dá é de ódio persistente: \"E foi adversário de Israel, por todos os dias de Salomão, e isto além do mal que Hadade fazia; porque detestava a Israel, e reinava sobre a Síria\" (11:25). Está no capítulo do coração desviado, e não por acaso: quando um rei se afasta de Deus, os adversários não precisam ser criados do nada — basta que Deus deixe de os conter.",
  },
  "acazias": {
    title: "Acazias",
    subtitle: "O filho de Acabe que serviu a Baal (1Rs 22:52-54)",
    text: "\"Assim dormiu Acabe com seus pais; e Acazias, seu filho, reinou em seu lugar\" (22:40). Reinou pouco: \"E Acazias, filho de Acabe, começou a reinar sobre Israel, em Samaria, no ano dezessete de Jeosafá, rei de Judá; e reinou dois anos sobre Israel\" (22:52). O veredicto sobre ele soma três heranças, e a do meio é a que mais pesa: \"E fez o que era mau aos olhos do Senhor; porque andou no caminho de seu pai, como também no caminho de sua mãe, e no caminho de Jeroboão, filho de Nebate, que fez pecar a Israel\" (22:53). Poucos reis recebem essa menção explícita à mãe — mas era Jezabel, e a casa que ela montou continuou de pé depois de morto o marido. O último traço é a religião escolhida sem disfarce: \"E serviu a Baal, e adorou-o, e provocou a ira do Senhor Deus de Israel, conforme a tudo quanto fizera seu pai\" (22:54). Ainda tentou sociedade marítima com Judá, e foi recusado: \"Vão os meus servos com os teus servos nos navios. Porém Jeosafá não quis\" (22:50). O fogo do Carmelo caíra diante dos olhos da geração dele; não bastou. A fé não se herda por sangue, e o filho de Acabe é a prova.",
  },
  "hiel-o-betelita": {
    title: "Hiel, o betelita",
    subtitle: "O que reedificou Jericó sobre os próprios filhos (1Rs 16:34)",
    text: "Um único versículo, encaixado entre a idolatria de Acabe e a chegada de Elias, e ele carrega o peso de uma maldição de quinhentos anos: \"Em seus dias Hiel, o betelita, edificou a Jericó; em Abirão, seu primogênito, a fundou, e em Segube, seu filho menor, pôs as suas portas; conforme a palavra do Senhor, que falara pelo ministério de Josué, filho de Num\" (16:34). Josué jurara que quem reedificasse aquela cidade a fundaria à custa do primogênito e lhe poria as portas à custa do caçula (Js 6:26). Hiel construiu assim mesmo — e perdeu o primeiro filho ao lançar os alicerces e o último ao pendurar os portões, do começo ao fim da obra. O narrador põe isso exatamente ali de propósito: nos dias de Acabe, quando Israel tratava a palavra do SENHOR como folclore de outra era, um homem provou na própria casa que ela não caducou. É o prólogo silencioso do capítulo seguinte, em que um profeta chega dizendo que não haverá orvalho nem chuva senão segundo a sua palavra (17:1). Deus não esqueceu o que disse por Josué; e não esqueceria o que ia dizer por Elias.",
  },
  "semer-dono-do-monte": {
    title: "Semer",
    subtitle: "O dono do monte que deu nome a Samaria (1Rs 16:24)",
    text: "Aparece só como vendedor, num negócio de duas linhas: \"E de Semer comprou o monte de Samaria por dois talentos de prata, e edificou nele; e chamou a cidade que edificou Samaria, do nome de Semer, dono do monte\" (16:24). Não sabemos nada dele — nem tribo, nem descendência, nem se resistiu ou negociou de bom grado com o novo rei. Vendeu um monte por dois talentos de prata, e o nome ficou. Ficou na capital do reino do norte durante mais de cento e cinqüenta anos; ficou nos oráculos de Amós e Oseias contra a cidade; ficou no cativeiro da Assíria; ficou nos samaritanos do Novo Testamento, na mulher do poço e no bom samaritano da parábola. Não há na Escritura melhor exemplo de quanto um homem comum pode marcar a história sem ter feito nada de extraordinário: um proprietário anônimo emprestou o próprio nome ao lugar onde Acabe levantaria a casa de Baal e onde Elias enfrentaria reis.",
  },
  "arsa-mordomo": {
    title: "Arsa",
    subtitle: "O mordomo em Tirza, em cuja casa Elá foi morto (1Rs 16:9)",
    text: "O nome aparece uma vez, como endereço de um assassinato: \"E Zinri, seu servo, capitão de metade dos carros, conspirou contra ele, estando ele em Tirza, bebendo e embriagando-se em casa de Arsa, mordomo em Tirza\" (16:9). Era o encarregado da casa do rei na capital — o mesmo cargo que Obadias teria com Acabe (18:3) —, e foi o seu telhado que abrigou a noite em que a dinastia de Baasa acabou. O texto não diz se ele foi cúmplice, testemunha ou apenas anfitrião de um rei que bebia demais; deixa só o detalhe, e o detalhe basta. Um rei de Israel morreu embriagado na sala de um funcionário, longe do campo de batalha onde o exército inteiro estava acampado contra Gibetom (16:15). Arsa é o nome que a Escritura conservou de um homem que estava no lugar errado, na noite errada, servindo o senhor errado.",
  },
  "etbaal-rei-dos-sidonios": {
    title: "Etbaal",
    subtitle: "Rei dos sidônios, pai de Jezabel (1Rs 16:31)",
    text: "Nomeado uma só vez, numa frase que explica meio livro: \"ainda tomou por mulher a Jezabel, filha de Etbaal, rei dos sidônios; e foi e serviu a Baal, e o adorou\" (16:31). Sidom era a potência fenícia com que Israel sempre negociara — dela vieram os cortadores de madeira do templo, \"porque bem sabes tu que entre nós ninguém há que saiba cortar a madeira como os sidônios\" (5:6) —, mas dela veio também Astarote, que Salomão seguiu na velhice, a \"deusa dos sidônios\" (11:5,33). Ao casar o filho com a filha de Etbaal, a casa de Onri comprou aliança comercial e recebeu, no mesmo pacote, um culto de Estado. O próprio nome do sogro traz Baal dentro, e a filha que ele criou não veio a Samaria para se converter: veio para converter. Etbaal não faz nada na narrativa, e é justamente esse o ponto — os grandes desastres espirituais de Israel entram quase sempre por um contrato bem-sucedido, assinado por homens que só pensavam em política.",
  },
  "azuba": {
    title: "Azuba",
    subtitle: "Filha de Sili, mãe de Jeosafá (1Rs 22:42)",
    text: "\"E era Jeosafá da idade de trinta e cinco anos quando começou a reinar; e vinte e cinco anos reinou em Jerusalém; e era o nome de sua mãe Azuba, filha de Sili\" (22:42). É tudo o que a Escritura diz dela, e mesmo assim ela está ali por um motivo: no livro dos Reis, a fórmula que nomeia a mãe de cada rei de Judá é parte do julgamento do reinado — é por ela que sabemos que Maaca corrompeu Abias com o ídolo de Aserá (15:2,13) e que Naamá, a amonita, criou Roboão (14:21). Azuba é a mãe de um dos poucos reis de quem o texto diz que \"andou em todos os caminhos de seu pai Asa, não se desviou deles, fazendo o que era reto aos olhos do Senhor\" (22:43). Foi mulher de Asa, o rei que queimou o ídolo da rainha-mãe anterior no Cedrom, e criou o filho na geração em que Judá voltou a temer o SENHOR. A Bíblia guarda o nome sem contar a história — e o silêncio, aqui, é elogio: nada de ruim há para dizer.",
  },
  "naama-amonita": {
    title: "Naamá, a amonita",
    subtitle: "A mãe de Roboão, nomeada duas vezes (1Rs 14:21,31)",
    text: "O texto a nomeia no começo e no fim do reinado do filho, com a mesma fórmula: \"era o nome de sua mãe Naamá, amonita\" (14:21) e, de novo, ao sepultar Roboão, \"era o nome de sua mãe Naamá, amonita\" (14:31). Não é repetição descuidada; é o narrador cravando duas vezes a mesma informação para que ninguém a perca. Era uma das \"muitas mulheres estrangeiras\" que Salomão amou, \"moabitas, amonitas, edomitas, sidônias e hetéias\" (11:1), das nações de que Deus dissera \"perverterão o vosso coração para seguirdes os seus deuses\" (11:2). O rei que edificou um alto \"a Moloque, a abominação dos filhos de Amom\" (11:7) teve por herdeiro um filho de mulher amonita. E o reinado desse filho é descrito assim: \"E fez Judá o que era mau aos olhos do Senhor\" (14:22), e \"também eles edificaram altos, e estátuas, e imagens de Aserá sobre todo o alto outeiro e debaixo de toda a árvore verde\" (14:23). O aviso da Lei não era xenofobia — Rute, a moabita, está na genealogia de Davi. Era sobre o culto que entra em casa junto com o casamento; e Naamá é o nome que a Escritura pôs, duas vezes, nessa advertência.",
  },
  "filha-de-farao": {
    title: "A filha de Faraó",
    subtitle: "A mulher egípcia de Salomão, que subiu da Cidade de Davi (1Rs 3:1; 9:24)",
    text: "Abre a era de ouro e a assombra ao mesmo tempo: \"E Salomão se aparentou com Faraó, rei do Egito; e tomou a filha de Faraó, e a trouxe à cidade de Davi, até que acabasse de edificar a sua casa, e a casa do SENHOR, e a muralha de Jerusalém em redor\" (3:1). O casamento era diplomacia do mais alto nível — nenhum rei antes de Salomão recebera uma princesa do Egito —, e veio com dote de guerra: \"Porque Faraó, rei do Egito, subiu e tomou a Gezer, e a queimou a fogo, e matou os cananeus que moravam na cidade, e a deu em dote à sua filha, mulher de Salomão\" (9:16). O rei lhe construiu palácio próprio, \"também para a filha de Faraó, que Salomão tomara por mulher, fez uma casa semelhante àquele pórtico\" (7:8), e registrou a mudança com um cuidado que revela desconforto: \"Subiu, porém, a filha de Faraó da cidade de Davi, à sua casa, que Salomão lhe edificara\" (9:24) — tirou-a do bairro onde estivera a arca. Ela encabeça a lista fatal: \"E o rei Salomão amou muitas mulheres estrangeiras, além da filha de Faraó\" (11:1). O Egito de onde Deus tirara Israel voltou a Jerusalém pela porta da frente, como sogro do rei; e, uma geração depois, voltaria outra vez, com Sisaque, pela porta do tesouro (14:25-26).",
  },
  "abias-filho-de-jeroboao": {
    title: "Abias, filho de Jeroboão",
    subtitle: "O menino em quem se achou coisa boa para com o SENHOR (1Rs 14:13)",
    text: "\"Naquele tempo adoeceu Abias, filho de Jeroboão\" (14:1) — e um reino inteiro se moveu por causa de uma febre de criança: o pai, que erguera bezerros de ouro para não precisar de Jerusalém, mandou a mulher disfarçada a Siló consultar o profeta do SENHOR (14:2-3). Deus, que não é consultado às escondidas, mandou pelo cego Aías a sentença sobre a casa toda: \"destruirei de Jeroboão todo o homem até ao menino\", e os que morressem seriam comidos pelos cães e pelas aves (14:10-11). No meio dessa condenação, um versículo se abre como uma janela: \"E todo o Israel o pranteará, e o sepultará; porque de Jeroboão só este entrará em sepultura, porquanto se achou nele coisa boa para com o Senhor Deus de Israel em casa de Jeroboão\" (14:13). Numa casa que o texto descreve como esterco a ser varrido (14:10), Deus achou alguma coisa boa — e foi num menino. A morte veio no instante marcado: \"chegando ela ao limiar da porta, morreu o menino\" (14:17), e todo o Israel o pranteou (14:18). Morrer cedo foi a misericórdia que lhe coube: foi levado antes do juízo, e é o único da sua casa a ter sepultura e lágrimas. Deus lê corações um por um, mesmo dentro da família mais condenada do livro.",
  },
  "anjo-do-senhor": { title: "O anjo do SENHOR", subtitle: "O mensageiro por quem o SENHOR fala e fere em 2 Reis (2Rs 1:3; 19:35)", text: "Não é Deus desenhado como figura, mas o mediador visível por quem a sua palavra chega: \"Mas o anjo do Senhor disse a Elias, o tisbita: Levanta-te, sobe para te encontrares com os mensageiros do rei de Samaria\" (2Rs 1:3). Ao terceiro capitão, que se pôs de joelhos e suplicou, é ele quem autoriza a descida: \"Desce com este, não temas\" (2Rs 1:15) — a mesma presença que consumira dois cinqüenta poupa o que suplica. E, na noite em que Jerusalém não tinha exército, \"saiu o anjo do Senhor, e feriu no arraial dos assírios a cento e oitenta e cinco mil deles\" (2Rs 19:35). Onde a Assíria contava carros, o SENHOR não precisou de nenhum." },
  "jeorao": { title: "Jeorão", subtitle: "Rei de Judá, filho de Jeosafá, casado com a filha de Acabe (2Rs 8:16-18)", text: "\"E andou no caminho dos reis de Israel, como também fizeram os da casa de Acabe, porque tinha por mulher a filha de Acabe\" (2Rs 8:18) — foi por esse casamento que a idolatria do Norte entrou na casa de Davi. Nos seus dias Judá perdeu Edom e Libna (2Rs 8:20,22). E, no meio do relato do seu mal, a narrativa para para dizer por que o reino não caiu: \"Porém o Senhor não quis destruir a Judá por amor de Davi, seu servo, como lhe tinha falado que lhe daria, para sempre, uma lâmpada, a ele e a seus filhos\" (2Rs 8:19). Não é a fidelidade dos reis que sustenta a promessa; é a promessa que sustenta os reis." },
  "jonatas-filho-de-abiatar": { title: "Jônatas", subtitle: "Filho do sacerdote Abiatar, o portador da notícia (1Rs 1:42)", text: "O mesmo Jônatas que, com Aimaás, servira de correio a Davi na fuga de Absalão, escondido junto à fonte de Rogel (2Sm 15:36; 17:17). Anos depois chegou àquela mesma fonte, onde Adonias banqueteava os seus, e foi recebido com esperança: \"Entra, porque és homem valente, e trarás boas novas\" (1Rs 1:42). Trouxe o contrário: \"Certamente nosso senhor, rei Davi, constituiu rei a Salomão\" (1Rs 1:43), ungido em Giom por Zadoque e Natã, montado na mula do rei. E rematou sem piedade: \"E também Salomão está assentado no trono do reino\" (1Rs 1:46). Ao ouvi-lo, \"estremeceram e se levantaram todos os convidados que estavam com Adonias; e cada um se foi ao seu caminho\" (1Rs 1:49) — a festa do usurpador desfez-se diante de uma só palavra verdadeira." },
  "amom-governador-da-cidade": {
    title: "Amom, o governador da cidade de Samaria",
    subtitle: "A quem Acabe entregou Micaías preso (2Cr 18:25)",
    text: "Existe na Escritura para receber um preso. \"Então disse o rei de Israel: Tomai a Micaías, e tornai a levá-lo a Amom, o governador da cidade, e a Joás, filho do rei\" (2Cr 18:25). O verbo é \"tornai a levá-lo\": o profeta já tinha estado sob a guarda deles antes, o que explica por que Acabe sabia exatamente onde encontrá-lo quando Jeosafá pediu um profeta do SENHOR. A ordem que Amom recebe é curta e tem prazo: \"Colocai este homem na casa do cárcere; e sustentai-o com pão de angústia, e com água de angústia, até que eu volte em paz\" (2Cr 18:26). O prazo nunca venceu — o rei que o fixou morreu ao pôr do sol daquele mesmo dia, encostado em pé no carro (2Cr 18:34) —, e o carcereiro ficou com um preso cuja soltura dependia de um homem que não voltou.",
  },
  "abias-rei-de-juda": {
    title: "Abias, rei de Judá",
    subtitle: "2Cr 13 — o rei que pregou em cima do monte de Zemaraim ao exército inimigo",
    text: "Reinou três anos e ficou na Escritura por um discurso. Filho de Roboão e de Maaca, foi escolhido herdeiro por preferência do pai — \"Roboão designou Abias, filho de Maaca, para ser chefe e líder entre os seus irmãos, porque queria fazê-lo rei\" (2Cr 11:22) — e herdou uma guerra: \"e houve guerra entre Abias e Jeroboão\" (2Cr 13:2). Com quatrocentos mil homens contra oitocentos mil, fez o que nenhum outro rei fez: \"E pôs-se Abias em pé em cima do monte de Zemaraim, que está na montanha de Efraim, e disse: Ouvi-me, Jeroboão e todo o Israel\" (2Cr 13:4). O argumento é inteiramente teológico — o direito perpétuo de Davi \"por uma aliança de sal\" (2Cr 13:5); a acusação de que Jeroboão era \"servo de Salomão\" rebelado contra o seu senhor (2Cr 13:6); os bezerros de ouro feitos para deuses (2Cr 13:8); o sacerdócio que se compra \"com um novilho e sete carneiros\" (2Cr 13:9); e, do outro lado, o serviço que não parou, com \"os pães da proposição sobre a mesa pura, e o castiçal de ouro\" (2Cr 13:11). Termina gritando do alto: \"E eis que Deus está conosco, à nossa frente\" (2Cr 13:12). Jeroboão respondeu com emboscada pela retaguarda; Judá, cercado por diante e por detrás, \"clamaram ao Senhor; e os sacerdotes tocaram as trombetas\" (2Cr 13:14), e o desfecho não é dele: \"Deus feriu a Jeroboão e a todo o Israel diante de Abias e de Judá\" (2Cr 13:15). Tomou Betel, Jesana e Efrom, fortificou-se, tomou catorze mulheres, e morreu com três anos de reinado. 1 Reis dá dele um veredicto duro (1Rs 15:3); 2 Crônicas guarda o sermão inteiro, escrito \"na história do profeta Ido\" (2Cr 13:22).",
  },
};
