// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de PERSONAGEM (por `id`) das cenas de deuteronomy. Vem por import() junto com
// o roteiro do livro: quem lê Rute não baixa os nomes de Crônicas.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHARS: Record<string, StageInfo> = {
  josue: { title: "Josué, filho de Num", subtitle: "O servo de Moisés que introduz Israel na terra (Js 1:1)", text: "Da tribo de Efraim, foi o \"moço\" que servia a Moisés e um dos dois espias que creram na promessa (Nm 14:6-9). Moisés lhe mudou o nome de Oséias para Josué — \"o Senhor é salvação\" — e sobre ele pôs as mãos, cheio do Espírito de sabedoria (Nm 27:18; Dt 34:9). A ele Deus repetiu: \"Esforça-te e tem bom ânimo... o Senhor teu Deus é contigo\" (Js 1:9). Atravessou o Jordão, tomou a terra e a repartiu, e no fim desafiou o povo: \"eu e a minha casa serviremos ao Senhor\" (Js 24:15). Prefigura Jesus, que leva o povo ao verdadeiro descanso (Hb 4:8)." },
  calebe: { title: "Calebe, filho de Jefoné", subtitle: "O espia fiel, herdeiro de Hebrom (Js 14:6)", text: "O quenezeu que, com Josué, trouxe bom relato da terra e creu contra a incredulidade dos dez: \"subamos animosamente... porque bem poderemos com ela\" (Nm 13:30). Por seguir \"integralmente\" ao Senhor, foi dos únicos daquela geração a entrar (Nm 14:24). Aos 85 anos, com a mesma fé de 45 anos antes, reivindicou o monte dos anaquins: \"dá-me este monte de que o Senhor falou\" (Js 14:12), e tomou Hebrom. Modelo de quem persevera na promessa até vê-la cumprida." },
  eleazar: { title: "Eleazar, filho de Arão", subtitle: "O sumo sacerdote que repartiu a terra (Js 14:1)", text: "Terceiro filho de Arão, sucedeu-lhe no sumo sacerdócio quando Deus revestiu Eleazar com as vestes no monte Hor (Nm 20:26-28). Ao lado de Josué, lançou as sortes \"perante o Senhor\" para dividir a herança entre as tribos (Js 14:1; 19:51) — o sacerdote e o capitão juntos, palavra e espada a serviço da promessa. Morreu ao fim do livro e foi sepultado no outeiro de Finéias, seu filho, em Efraim (Js 24:33)." },
  balaao: { title: "Balaão, filho de Beor", subtitle: "O adivinho que quis amaldiçoar Israel (Js 13:22)", text: "Adivinho de Petor, junto ao Eufrates, contratado por Balaque para amaldiçoar Israel — mas Deus lhe torceu a boca em bênção (Nm 22-24). Amou \"o prêmio da injustiça\" (2Pe 2:15) e ensinou Balaque a seduzir o povo em Baal-Peor. Josué registra o seu fim: foi morto à espada entre os reis de Midiã (Js 13:22), lembrança de que nem toda ciência do oculto livra o coração cobiçoso do juízo." },
  amom: { title: "O rei dos filhos de Amom", subtitle: "Dt 2:19 — a terra que Deus não deu a Israel", text: "Não é o rei Amom de Judá, séculos depois: aqui Amom é o povo descendente de Ló (Gn 19:38), e o rei é o senhor da terra por onde Israel passa a caminho de Canaã. A ordem foi de não tocar: \"chegando-te defronte dos filhos de Amom, não os molestes, e com eles não contendas; porque da terra dos filhos de Amom te não darei possessão, porquanto aos filhos de Ló a tenho dado por possessão\" (Dt 2:19). Deus reparte terra também a quem não é o seu povo, e o limite de Israel é traçado por Ele, não pela força." },
  "data": { title: "Datã", subtitle: "Filho de Eliabe, rubenita, na rebelião de Coré (Nm 16:1)", text: "Rubenita que se ajuntou a Coré e a Abirão contra Moisés (Nm 16:1). Chamado à presença dele, respondeu com a recusa que virou o seu retrato: \"Não subiremos\" (Nm 16:12). Chamou ao Egito da servidão \"uma terra que mana leite e mel\" e acusou o libertador de querer \"fazer-te príncipe sobre nós\" (Nm 16:13) — a promessa invertida é o coração de toda rebeldia. Veio o sinal: \"a terra abriu a sua boca, e os tragou com as suas casas\" (Nm 16:32). Israel nunca esqueceu; Moisés o recorda a uma nova geração (Dt 11:6)." },
};
