// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de PERSONAGEM (por `id`) das cenas de esther. Vem por import() junto com
// o roteiro do livro: quem lê Rute não baixa os nomes de Crônicas.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHARS: Record<string, StageInfo> = {
  "assuero-rei-da-persia": {
    title: "Assuero, rei da Pérsia",
    subtitle: "Et 1–10 • o rei que reinou desde a Índia até a Etiópia, sobre cento e vinte e sete províncias",
    text: "\"E sucedeu nos dias de Assuero, o Assuero que reinou desde a India até a Etiópia, sobre cento e vinte e sete províncias\" (Et 1:1) — o livro começa medindo o homem pelo mapa, e depois gasta dez capítulos mostrando que ele nunca decide nada. Faz um banquete de cento e oitenta dias \"para mostrar as riquezas da glória do seu reino\" (Et 1:4); manda buscar a rainha \"estando já o coração do rei alegre do vinho\" (Et 1:10) e, recusado, pergunta aos advogados o que fazer (Et 1:13-15). Entrega o anel do império a Hamã sem perguntar o nome do povo que vai matar: \"Essa prata te é dada como também esse povo, para fazeres dele o que bem parecer aos teus olhos\" (Et 3:11). Numa noite em que \"fugiu o sono do rei\" (Et 6:1), manda ler as crônicas e descobre uma dívida de quatro capítulos. Estende o cetro de ouro a Ester duas vezes (Et 5:2; 8:4), oferece \"até metade do reino\" quatro vezes sem que ninguém lhe cobre, e quando quer salvar os judeus esbarra na própria lei: \"o documento que se escreve em nome do rei, e que se sela com o anel do rei, não se pode revogar\" (Et 8:8) — então entrega o selo a outro homem e sai da frente, como fizera com Hamã. Termina o livro impondo tributo \"sobre a terra, e sobre as ilhas do mar\" (Et 10:1). Em dez capítulos nunca menciona um deus, e nunca se diz que soube o que passou por debaixo do seu trono.",
  },
  "vasti-a-rainha": {
    title: "Vasti, a rainha que recusou vir",
    subtitle: "Et 1:9-19 • a mulher cujo não pôs em movimento o livro inteiro",
    text: "Ela aparece três vezes e some. Primeiro dando a sua própria festa, longe do vinho dos homens: \"Também a rainha Vasti deu um banquete às mulheres, na casa real do rei Assuero\" (Et 1:9). Depois, chamada no sétimo dia por sete camareiros para ser exibida \"com a coroa real, para mostrar aos povos e aos príncipes a sua beleza, porque era formosa à vista\" (Et 1:11) — convocada não como rainha, mas como a última peça do mostruário que vinha sendo aberto havia cento e oitenta dias. E enfim recusando: \"Porém a rainha Vasti recusou vir conforme a palavra do rei, por meio dos camareiros; assim o rei muito se enfureceu, e acendeu nele a sua ira\" (Et 1:12). O texto não dá o motivo, não a elogia nem a condena, e não a defende. O que registra é o pânico dos conselheiros — \"a notícia do que fez a rainha chegará a todas as mulheres\" (Et 1:17) — e o edito irrevogável \"que Vasti não entre mais na presença do rei Assuero, e o rei dê o reino dela a outra que seja melhor do que ela\" (Et 1:19). Volta uma única vez, como lembrança de um homem que já não pode desfazer o que assinou: \"apaziguado já o furor do rei Assuero, lembrou-se de Vasti\" (Et 2:1). O trono vago que ela deixou é por onde entra a judia de Susã.",
  },
  "ester-a-rainha": {
    title: "Ester, isto é, Hadassa, filha de Abiail",
    subtitle: "Et 2–10 • a órfã do cativeiro que virou rainha da Pérsia e escreveu a lei do Purim",
    text: "\"Este criara a Hadassa (que é Ester, filha de seu tio), porque não tinha pai nem mãe; e era jovem bela de presença e formosa; e, morrendo seu pai e sua mãe, Mardoqueu a tomara por sua filha\" (Et 2:7). É gente do desterro: a casa dela veio de Jerusalém \"com os cativos que foram levados com Jeconias, rei de Judá\" (Et 2:6). Levada à casa das mulheres sem que ninguém lhe pergunte nada, atravessa os doze meses de purificação e não pede nada além do que Hegai indicou (Et 2:15); recebe a coroa real na cabeça (Et 2:17) e continua calada sobre quem é, \"porque Mardoqueu lhe tinha ordenado que o não declarasse\" (Et 2:10). Quando o decreto chega, a primeira reação é jurídica e humana — a lei do pátio interior e trinta dias sem ser chamada (Et 4:11) —, e a segunda é a frase que sustenta o livro: \"E assim irei ter com o rei, ainda que não seja segundo a lei; e se perecer, pereci\" (Et 4:16). Entra de trajes reais, toca a ponta do cetro, adia o pedido por dois banquetes, e no segundo aponta o convidado: \"O homem, o opressor, e o inimigo, é este mau Hamã\" (Et 7:6). Depois chora aos pés do rei pelo povo (Et 8:3-6), pede mais um dia em Susã (Et 9:13) e assina, com Mardoqueu, as cartas de paz e verdade — \"E o mandado de Ester estabeleceu os sucessos daquele Purim; e escreveu-se no livro\" (Et 9:32). Em nenhum momento o texto lhe põe na boca o nome de Deus. A pergunta que lhe fizeram ficou sem resposta escrita: \"e quem sabe se para tal tempo como este chegaste a este reino?\" (Et 4:14).",
  },
  "mardoqueu-o-judeu": {
    title: "Mardoqueu, filho de Jair, filho de Simei, filho de Quis, homem benjamita",
    subtitle: "Et 2–10 • o judeu da porta do rei que acabou o segundo depois de Assuero",
    text: "\"Havia então um homem judeu na fortaleza de Susã, cujo nome era Mardoqueu, filho de Jair, filho de Simei, filho de Quis, homem benjamita\" (Et 2:5). A genealogia é uma acusação guardada: Quis, benjamita, é o nome do pai de Saul (1Sm 9:1) — e o inimigo que entrará no capítulo seguinte é \"filho de Hamedata, agagita\" (Et 3:1), da casa de Agague, rei dos amalequitas que Saul poupou e Samuel despedaçou em Gilgal (1Sm 15:8, 33). Nenhum dos dois menciona a história; ela apenas continua. Mardoqueu veio no cativeiro de Jeconias (Et 2:6), criou a prima órfã como filha, mandou-a esconder a origem (Et 2:10) e passeava \"cada dia diante do pátio da casa das mulheres\" (Et 2:11). Denuncia Bigtã e Teres, e o serviço é anotado e esquecido: \"e foi escrito nas crônicas perante o rei\" (Et 2:23). Não se inclina diante de Hamã, e a única razão que dá é \"que era judeu\" (Et 3:4). Rasga as vestes, veste saco e cinza, clama pelo meio da cidade e para diante da porta (Et 4:1-2). Manda a Ester a certeza sem sujeito — \"socorro e livramento de outra parte sairá para os judeus\" — e a pergunta que é o mais perto que este livro chega de nomear a providência: \"e quem sabe se para tal tempo como este chegaste a este reino?\" (Et 4:14). É levado a cavalo pelas ruas com a veste real (Et 6:11), recebe o anel tirado de Hamã (Et 8:2), escreve a segunda carta e institui o Purim (Et 9:20-22), e termina assim: \"o judeu Mardoqueu foi o segundo depois do rei Assuero, e grande entre os judeus, e estimado pela multidão de seus irmãos, procurando o bem do seu povo\" (Et 10:3).",
  },
  "hama-o-agagita": {
    title: "Hamã, filho de Hamedata, o agagita",
    subtitle: "Et 3–9 • o homem que teve o assento acima de todos os príncipes e morreu na forca do próprio quintal",
    text: "\"Depois destas coisas o rei Assuero engrandeceu a Hamã, filho de Hamedata, agagita, e o exaltou, e pôs o seu assento acima de todos os príncipes que estavam com ele\" (Et 3:1). Agagita: da casa de Agague, o rei amalequita que Saul tomou vivo quando devia destruí-lo (1Sm 15:8-9) — e do outro lado do pátio há um benjamita da casa de Quis. A guerra que o Êxodo declarou \"de geração em geração\" (Êx 17:16) e que Deuteronômio mandou terminar (Dt 25:17-19) chega assim a Susã, sem que nenhum dos dois a nomeie. Enfurecido porque um homem não se curva, Hamã \"teve como pouco, nos seus propósitos, o pôr as mãos só em Mardoqueu\" (Et 3:6) e vai atrás do povo inteiro. Lança o pur, isto é, a sorte (Et 3:7), e monta diante do rei uma acusação que é quase toda verdade e nunca diz o nome do acusado (Et 3:8). Compra o extermínio por dez mil talentos de prata e recebe o anel (Et 3:9-10). É o retrato do homem que tem tudo e não goza de nada: conta em casa \"a glória das suas riquezas, a multidão de seus filhos, e tudo em que o rei o tinha engrandecido\" e conclui \"Porém tudo isto não me satisfaz, enquanto eu vir o judeu Mardoqueu assentado à porta do rei\" (Et 5:11-13). Manda levantar uma forca de cinquenta côvados, dita sem saber a própria humilhação (Et 6:6-9), volta para casa \"triste, e de cabeça coberta\" (Et 6:12), é apontado à mesa da rainha (Et 7:6) e enforcado \"na forca, que ele tinha preparado para Mardoqueu\" (Et 7:10). O livro não chama isso de juízo divino; diz apenas que \"o furor do rei se aplacou\".",
  },
  "zeres-mulher-de-hama": {
    title: "Zeres, mulher de Hamã",
    subtitle: "Et 5:10-14 e 6:13 • a mulher que mandou levantar a forca e depois sentenciou o próprio marido",
    text: "Zeres aparece duas vezes e as duas são decisivas. Na primeira, o marido volta do banquete furioso com o judeu da porta e a chama junto com os amigos para ouvir o inventário da vaidade dele — \"a glória das suas riquezas, a multidão de seus filhos, e tudo em que o rei o tinha engrandecido\" (Et 5:11) — e a queixa que anula tudo. A ideia é dela: \"Então lhe disseram Zeres, sua mulher, e todos os seus amigos: Faça-se uma forca de cinqüenta côvados de altura, e amanhã dize ao rei que nela seja enforcado Mardoqueu; e então entra alegre com o rei ao banquete\" (Et 5:14). Vinte e quatro horas depois, o mesmo homem chega correndo \"triste, e de cabeça coberta\" (Et 6:12) e conta a humilhação, e ela diz a frase mais estranha do livro — uma profecia certeira na boca de uma persa, sem profeta, sem oráculo e sem nomear deus nenhum: \"Se Mardoqueu, diante de quem já começaste a cair, é da descendência dos judeus, não prevalecerás contra ele, antes certamente cairás diante dele\" (Et 6:13). Ela nomeia a descendência, e não o homem. A conversa é cortada no meio pelos camareiros que vêm buscar Hamã para o banquete (Et 6:14), e ela não reaparece — nem quando os dez filhos que o marido lhe contou como glória são mortos e pendurados num só dia (Et 9:7-14).",
  },
  "hegai-guarda-das-mulheres": {
    title: "Hegai, camareiro do rei, guarda das mulheres",
    subtitle: "Et 2:3-15 • o eunuco que administrava a casa das mulheres e favoreceu Ester desde o primeiro dia",
    text: "\"E ponha o rei oficiais em todas as províncias do seu reino, que ajuntem a todas as moças virgens e formosas, na fortaleza de Susã, na casa das mulheres, aos cuidados de Hegai, camareiro do rei, guarda das mulheres, e dêem-se-lhes os seus enfeites\" (Et 2:3). É um funcionário de carreira, encarregado do harém do rei e do regulamento dos doze meses de purificação — \"seis meses com óleo de mirra, e seis meses com especiarias\" (Et 2:12). O que o texto registra dele é um favor imediato e sem explicação: \"E a moça pareceu formosa aos seus olhos, e alcançou graça perante ele; por isso se apressou a dar-lhe os seus enfeites, e os seus quinhões, como também em lhe dar sete moças de respeito da casa do rei; e a fez passar com as suas moças ao melhor lugar da casa das mulheres\" (Et 2:9). E o conselho dele é o que Ester segue quando chega a sua vez, contra o costume de cada moça levar consigo tudo quanto desejasse: \"coisa nenhuma pediu, senão o que disse Hegai, camareiro do rei, guarda das mulheres\" (Et 2:15). Um eunuco persa que sabia do que o rei gostava, e uma judia que preferiu ouvi-lo a se enfeitar por conta própria. O livro não diz que isso foi arranjado por ninguém; diz só que ela agradou e que ele se apressou.",
  },
  "saasgaz-guarda-das-concubinas": {
    title: "Saasgaz, camareiro do rei, guarda das concubinas",
    subtitle: "Et 2:14 • o eunuco da segunda casa das mulheres, para onde iam as que já não voltavam",
    text: "\"À tarde entrava, e pela manhã tornava à segunda casa das mulheres, sob os cuidados de Saasgaz, camareiro do rei, guarda das concubinas; não tornava mais ao rei, salvo se o rei a desejasse, e fosse chamada pelo nome\" (Et 2:14). Saasgaz aparece uma vez só, e a função dele é a linha mais fria de todo o capítulo: administrar o dormitório das esquecidas. A casa de Hegai é a das que ainda esperam; a de Saasgaz é a das que já foram e não têm mais nada a esperar, a não ser um nome chamado por acaso. É o contexto exato em que Ester entrou e do qual saiu — não porque o sistema fosse justo, mas porque \"o rei amou a Ester mais do que a todas as mulheres\" (Et 2:17). O livro descreve o mecanismo sem uma palavra de indignação e sem uma palavra de aprovação; deixa que ele fale por si. Todas as moças ajuntadas por decreto nas cento e vinte e sete províncias (Et 2:3) terminaram naquela segunda casa, menos uma.",
  },
  "hataque-eunuco-de-ester": {
    title: "Hatá, um dos camareiros do rei posto para servir a Ester",
    subtitle: "Et 4:5-12 • o eunuco por cujos pés passou o diálogo inteiro entre Ester e Mardoqueu",
    text: "\"Então Ester chamou a Hatá (um dos camareiros do rei, que este tinha posto para servi-la), e deu-lhe ordem para ir a Mardoqueu, para saber que era aquilo, e porquê\" (Et 4:5). Hatá é um funcionário de Assuero destacado para a rainha, e no capítulo 4 é o único canal existente entre os dois protagonistas: ela não pode sair, ele não pode entrar de saco pelas portas do rei (Et 4:2), e os dois nunca aparecem juntos em cena antes do capítulo 8. Todo o eixo do livro atravessa \"à praça da cidade, que estava diante da porta do rei\" (Et 4:6) nos pés deste homem. Ele leva a soma exata do dinheiro prometido por Hamã e \"a cópia da lei escrita, que se publicara em Susã, para os destruir\" (Et 4:8); traz a objeção da lei do pátio interior e os trinta dias sem ser chamada (Et 4:11); leva a resposta que contém a pergunta \"e quem sabe se para tal tempo como este chegaste a este reino?\" (Et 4:14); e traz de volta \"se perecer, pereci\" (Et 4:16). Um eunuco persa carregando, sem saber, a sobrevivência de um povo dentro de um recado, e o livro não lhe dá nem uma linha de comentário.",
  },
  "harbona-eunuco-do-rei": {
    title: "Harbona, um dos camareiros que serviam diante do rei",
    subtitle: "Et 1:10 e 7:9 • o eunuco que foi buscar Vasti no primeiro capítulo e lembrou a forca no sétimo",
    text: "Harbona é nomeado duas vezes, e a segunda muda o livro. Na primeira é um dos sete: \"mandou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete camareiros que serviam na presença do rei Assuero\" (Et 1:10), enviados a buscar a rainha e obrigados a voltar de mãos vazias. Na segunda está de pé na sala do banquete do vinho, com Hamã já de rosto coberto, e diz a frase que fecha a armadilha: \"Então disse Harbona, um dos camareiros que serviam diante do rei: Eis que também a forca de cinqüenta côvados de altura que Hamã fizera para Mardoqueu, que falara em defesa do rei, está junto à casa de Hamã. Então disse o rei: Enforcai-o nela\" (Et 7:9). Note o que este eunuco sabe: sabe da forca do quintal, sabe para quem foi feita, e sabe o detalhe que arremata tudo — que Mardoqueu \"falara em defesa do rei\", isto é, o feito lido nas crônicas na madrugada anterior (Et 6:2). Um criado de palácio junta as duas pontas do enredo em um versículo, e o rei só precisa dizer duas palavras. O livro não explica como ele sabia, nem por que falou naquela hora.",
  },
  "meuma-camareiro-do-rei": {
    title: "Meumã, o primeiro dos sete camareiros",
    subtitle: "Et 1:10 • um dos eunucos mandados buscar a rainha Vasti no sétimo dia do banquete",
    text: "\"E ao sétimo dia, estando já o coração do rei alegre do vinho, mandou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete camareiros que serviam na presença do rei Assuero\" (Et 1:10). O livro nomeia os sete um a um, e o faz de propósito: são eunucos da câmara real, gente de confiança absoluta, os únicos com acesso ao aposento do rei e ao das mulheres — e a missão que recebem é levar a rainha ao salão \"com a coroa real, para mostrar aos povos e aos príncipes a sua beleza\" (Et 1:11). Meumã encabeça a lista e por isso encabeça o fracasso: a recusa de Vasti se dá \"por meio dos camareiros\" (Et 1:12), e são estes sete homens que atravessam o palácio de volta com um não na boca e veem a ira do rei se acender. É o cargo mais próximo do trono e o mais exposto: quando um eunuco volta sem cumprir a ordem, não é por culpa dele, mas é diante dele que o furor sobe. Um desses sete nomes, Harbona, reaparece em 7:9 para dizer a frase que enforca Hamã — o livro guarda os seus figurantes por seis capítulos.",
  },
  "bizta-camareiro-do-rei": {
    title: "Bizta, um dos sete camareiros que serviam na presença do rei",
    subtitle: "Et 1:10 • um dos eunucos enviados a buscar Vasti com a coroa real",
    text: "\"mandou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete camareiros que serviam na presença do rei Assuero\" (Et 1:10). Bizta é um dos eunucos da câmara — a expressão \"que serviam na presença do rei\" é técnica e designa o círculo com acesso pessoal ao soberano, o mesmo privilégio que os sete príncipes de 1:14 têm no conselho e que Ester perderá em 4:11. A ordem que ele carrega é a de introduzir a rainha no salão dos convidados \"para mostrar aos povos e aos príncipes a sua beleza, porque era formosa à vista\" (Et 1:11), no sétimo dia de um banquete em que se bebia \"por lei, sem constrangimento\" (Et 1:8). É a única missão que a Escritura lhe atribui, e ela fracassa: \"Porém a rainha Vasti recusou vir conforme a palavra do rei, por meio dos camareiros\" (Et 1:12). Os sete voltam sem a rainha, e um império de cento e vinte e sete províncias trava numa palavra.",
  },
  "bigta-eunuco-do-rei": {
    title: "Bigtá, um dos sete camareiros que serviam na presença do rei",
    subtitle: "Et 1:10 • o eunuco de Et 1 — não confundir com Bigtã, o conspirador de Et 2:21",
    text: "\"mandou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete camareiros que serviam na presença do rei Assuero\" (Et 1:10). Bigtá é o quarto da lista dos eunucos enviados a buscar Vasti \"com a coroa real\" (Et 1:11) e a voltar sem ela (Et 1:12). O nome é muito próximo do de um outro homem que aparece no capítulo seguinte e num papel oposto — \"dois camareiros do rei, dos guardas da porta, Bigtã e Teres\" (Et 2:21), que conspiraram contra Assuero e foram pendurados numa forca. São cargos diferentes: os de 1:10 servem na presença do rei, dentro da câmara; os de 2:21 são da guarda da porta. O livro não os identifica um com o outro, e a cena os mantém separados. O que os dois grupos têm em comum é a posição: eunucos com acesso ao corpo do rei — a mesma proximidade que num caso executa uma ordem humilhante e no outro se transforma em atentado.",
  },
  "abagta-camareiro-do-rei": {
    title: "Abagta, um dos sete camareiros que serviam na presença do rei",
    subtitle: "Et 1:10 • um dos eunucos que trouxeram de volta o não da rainha Vasti",
    text: "\"mandou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete camareiros que serviam na presença do rei Assuero\" (Et 1:10). O texto podia ter escrito \"mandou os seus camareiros\" e não escreveu: deu os sete nomes, como daria os sete nomes dos príncipes quatro versículos adiante (Et 1:14) e os dez nomes dos filhos de Hamã oito capítulos adiante (Et 9:7-9). Este livro nomeia com cuidado quem carrega ordens. Abagta é um desses portadores: atravessa o palácio do salão dos homens à casa real das mulheres com a convocação mais humilhante que uma rainha podia receber — comparecer à festa dos bêbados do sétimo dia, de coroa, para ser vista. E volta sem ela. Todo o resto do livro — o edito de Memucã, a busca das virgens, a coroa na cabeça de Ester, o decreto de Hamã, o Purim — pende deste recado que não foi cumprido.",
  },
  "zetar-camareiro-do-rei": {
    title: "Zetar, um dos sete camareiros que serviam na presença do rei",
    subtitle: "Et 1:10 • um dos eunucos da câmara real mandados ao banquete de Vasti",
    text: "\"mandou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete camareiros que serviam na presença do rei Assuero\" (Et 1:10). Zetar é o sexto da lista. Os sete são eunucos do serviço interno, os homens que circulam entre a ala dos homens e a das mulheres sem quebrar a etiqueta do palácio — por isso são eles, e não um arauto qualquer, os enviados a interromper o banquete que \"a rainha Vasti deu... às mulheres, na casa real do rei Assuero\" (Et 1:9). A ordem que levam é curta e o texto a repete com o motivo: \"Que introduzissem na presença do rei a rainha Vasti, com a coroa real, para mostrar aos povos e aos príncipes a sua beleza, porque era formosa à vista\" (Et 1:11). A resposta é mais curta ainda, e é dada a eles — \"por meio dos camareiros\" (Et 1:12). Zetar não fala nenhuma palavra na Escritura; só faz o caminho de ida e o de volta.",
  },
  "carcas-camareiro-do-rei": {
    title: "Carcas, o sétimo dos camareiros que serviam na presença do rei",
    subtitle: "Et 1:10 • o último nome da lista dos eunucos enviados a buscar a rainha",
    text: "\"mandou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete camareiros que serviam na presença do rei Assuero\" (Et 1:10). Sete é o número que este capítulo repete: sete dias de banquete para o povo de Susã (Et 1:5), sete camareiros, sete príncipes dos persas e dos medos (Et 1:14). Mandar sete eunucos buscar uma pessoa não é escolta, é protocolo de estado — o rei quis que a rainha entrasse no salão como quem entra numa cerimônia, para ser exibida ao fim de cento e oitenta dias de exposição do tesouro. Carcas fecha a lista e participa do fracasso coletivo: \"Porém a rainha Vasti recusou vir conforme a palavra do rei, por meio dos camareiros; assim o rei muito se enfureceu, e acendeu nele a sua ira\" (Et 1:12). Nenhum destes sete homens torna a aparecer, exceto Harbona, que reaparece seis capítulos depois, no momento exato em que a forca precisava ser lembrada (Et 7:9).",
  },
  "carsena-principe-dos-persas": {
    title: "Carsena, o primeiro dos sete príncipes dos persas e dos medos",
    subtitle: "Et 1:14 • um dos que viam a face do rei e se assentavam como principais no reino",
    text: "\"E os mais chegados a ele eram: Carsena, Setar, Admata, Társis, Meres, Marsena, e Memucã, os sete príncipes dos persas e dos medos, que viam a face do rei, e se assentavam como principais no reino\" (Et 1:14). A expressão \"que viam a face do rei\" (Et 1:14) é linguagem técnica de corte persa: designa o pequeno grupo com direito de entrar na presença do soberano sem ser anunciado — exatamente o privilégio que Ester diz não ter em 4:11, quando explica que quem entra no pátio interior sem ser chamado morre, \"salvo se o rei estender para ele o cetro de ouro\". Carsena encabeça esse conselho, convocado para uma questão que o texto trata com toda a solenidade do direito imperial: \"O que, segundo a lei, se devia fazer à rainha Vasti, por não ter obedecido ao mandado do rei Assuero, por meio dos camareiros\" (Et 1:15). Sete dos homens mais poderosos do mundo conhecido reunidos para decidir o que fazer com uma esposa que não veio a um jantar. Da deliberação sai um edito irrevogável mandando que \"cada homem fosse senhor em sua casa\" (Et 1:22).",
  },
  "setar-principe-dos-persas": {
    title: "Setar, um dos sete príncipes dos persas e dos medos",
    subtitle: "Et 1:14 • um dos sábios que entendiam dos tempos, chamados a julgar a recusa de Vasti",
    text: "\"Então perguntou o rei aos sábios que entendiam dos tempos (porque assim se tratavam os negócios do rei na presença de todos os que sabiam a lei e o direito; E os mais chegados a ele eram: Carsena, Setar, Admata, Társis, Meres, Marsena, e Memucã\" (Et 1:13-14). Setar é um desses sete. A expressão \"sábios que entendiam dos tempos\" descreve conselheiros de corte encarregados de ler precedentes e ocasiões — o equivalente persa dos homens de Issacar, \"destros na ciência dos tempos, para saberem o que Israel devia fazer\" (1Cr 12:32) —, e o negócio que lhes põem à frente é doméstico. O que sai daquela sala não é uma sentença sobre uma mulher, é uma lei sobre todas: o parecer de Memucã é aceito, \"e pareceram bem estas palavras aos olhos do rei e dos príncipes\" (Et 1:21), e partem cartas para as cento e vinte e sete províncias. Estes homens escreveram, sem saber, a primeira das duas leis irrevogáveis que vão prender o próprio rei — a de 1:19, que o impede de chamar Vasti de volta (Et 2:1), e a de 8:8, que o impede de revogar o decreto contra os judeus.",
  },
  "admata-principe-dos-persas": {
    title: "Admata, um dos sete príncipes dos persas e dos medos",
    subtitle: "Et 1:14 • um dos sete que se assentavam como principais no reino de Assuero",
    text: "\"E os mais chegados a ele eram: Carsena, Setar, Admata, Társis, Meres, Marsena, e Memucã, os sete príncipes dos persas e dos medos, que viam a face do rei, e se assentavam como principais no reino\" (Et 1:14). Admata é o terceiro da lista. O conselho de que faz parte reúne \"todos os que sabiam a lei e o direito\" (Et 1:13) e é convocado no momento mais ridículo do livro: o rei, humilhado diante dos convidados porque a mulher não veio ao salão, pergunta aos juristas do império o que a lei manda fazer. A resposta que o conselho aprova transforma um desaforo doméstico em pânico político — \"Porque a notícia do que fez a rainha chegará a todas as mulheres, de modo que aos seus olhos desprezarão a seus maridos\" (Et 1:17) — e produz o primeiro documento selado do livro. É a mesma sala, o mesmo tipo de gente e o mesmo mecanismo que, dois capítulos adiante, vai despachar uma sentença de morte contra um povo inteiro sem que ninguém pergunte o nome dele (Et 3:8-12).",
  },
  "tarsis-principe-dos-persas": {
    title: "Társis, um dos sete príncipes dos persas e dos medos",
    subtitle: "Et 1:14 • um dos conselheiros que viam a face do rei na fortaleza de Susã",
    text: "\"E os mais chegados a ele eram: Carsena, Setar, Admata, Társis, Meres, Marsena, e Memucã, os sete príncipes dos persas e dos medos, que viam a face do rei, e se assentavam como principais no reino\" (Et 1:14). Társis é o quarto nome. O que a Escritura registra deste conselho é o processo, não o debate: o rei pergunta \"o que, segundo a lei, se devia fazer à rainha Vasti\" (Et 1:15), um deles fala, e \"pareceram bem estas palavras aos olhos do rei e dos príncipes\" (Et 1:21). Nenhum dos sete contesta. O detalhe que o livro faz questão de gravar é a irrevogabilidade daquilo que assinaram: \"escreva-se nas leis dos persas e dos medos, e não se revogue\" (Et 1:19). É a característica do direito persa que a narrativa vai usar duas vezes como armadilha — contra o próprio rei quando ele se lembra de Vasti (Et 2:1), e contra os judeus quando o decreto de Hamã já não pode ser desfeito e obriga a escrever uma segunda carta (Et 8:8).",
  },
  "meres-principe-dos-medos": {
    title: "Meres, um dos sete príncipes dos persas e dos medos",
    subtitle: "Et 1:14 • um dos principais do reino, no conselho que julgou a recusa da rainha",
    text: "\"E os mais chegados a ele eram: Carsena, Setar, Admata, Társis, Meres, Marsena, e Memucã, os sete príncipes dos persas e dos medos, que viam a face do rei, e se assentavam como principais no reino\" (Et 1:14). A fórmula \"dos persas e dos medos\" aparece no livro sempre ligada à lei que não se revoga (Et 1:19) e é a assinatura do império que sucedeu à Babilônia — o mesmo que Daniel viu de dentro, com a mesma cláusula usada contra ele na cova dos leões: \"conforme a lei dos medos e dos persas, que não se pode revogar\" (Dn 6:8). Meres é um dos sete homens dessa engrenagem. Chamado a opinar sobre um desaforo de banquete, aprova sem uma objeção registrada uma lei imperial sobre o comportamento das esposas em cento e vinte e sete províncias, despachada \"a cada província segundo a sua escrita, e a cada povo segundo a sua língua\" (Et 1:22). O império inteiro traduzindo, com todo o cuidado filológico, um decreto nascido de vinho e vergonha.",
  },
  "marsena-principe-dos-medos": {
    title: "Marsena, um dos sete príncipes dos persas e dos medos",
    subtitle: "Et 1:14 • o penúltimo da lista dos que se assentavam como principais no reino",
    text: "\"E os mais chegados a ele eram: Carsena, Setar, Admata, Társis, Meres, Marsena, e Memucã, os sete príncipes dos persas e dos medos, que viam a face do rei, e se assentavam como principais no reino\" (Et 1:14). Marsena vem imediatamente antes de Memucã, que é o único dos sete a quem o texto dá uma fala. Os outros seis existem no livro como o coro que aprova: o parecer é dado \"na presença do rei e dos príncipes\" (Et 1:16), e o resultado é registrado no plural — \"E pareceram bem estas palavras aos olhos do rei e dos príncipes; e fez o rei conforme a palavra de Memucã\" (Et 1:21). É assim que este livro mostra o poder funcionando: um homem fala, seis calam, e cento e vinte e sete províncias recebem cartas. O mesmo padrão se repete em 3:8-11, quando Hamã fala sozinho diante do rei e ninguém no salão levanta a mão para perguntar de que povo ele está falando.",
  },
  "memuca-principe-da-persia": {
    title: "Memucã, o príncipe que respondeu por todos",
    subtitle: "Et 1:16-21 • o conselheiro que transformou a recusa de uma esposa em lei imperial irrevogável",
    text: "É o único dos sete príncipes a quem o livro dá voz, e o que ele diz muda a escala do problema: \"Então disse Memucã na presença do rei e dos príncipes: Não somente contra o rei pecou a rainha Vasti, porém também contra todos os príncipes, e contra todos os povos que há em todas as províncias do rei Assuero\" (Et 1:16). O argumento inteiro dele é sobre o que as mulheres vão dizer: \"Porque a notícia do que fez a rainha chegará a todas as mulheres, de modo que aos seus olhos desprezarão a seus maridos\" (Et 1:17), e \"neste mesmo dia as senhoras da Pérsia e da Média, ouvindo o que fez a rainha, dirão o mesmo a todos os príncipes do rei; e assim haverá muito desprezo e indignação\" (Et 1:18). A solução que propõe tem duas partes, e a segunda é a que abre o livro: um edito escrito \"nas leis dos persas e dos medos\" para que não se revogue, \"que Vasti não entre mais na presença do rei Assuero, e o rei dê o reino dela a outra que seja melhor do que ela\" (Et 1:19). O rei obedece — \"fez o rei conforme a palavra de Memucã\" (Et 1:21) — e o trono vago é por onde entrará uma judia do cativeiro de Jeconias. Memucã nunca mais aparece; o decreto dele atravessa o livro inteiro, porque é ele que o rei já não pode desfazer quando \"lembrou-se de Vasti\" (Et 2:1).",
  },
  "bigta-o-conspirador": {
    title: "Bigtã, camareiro do rei, dos guardas da porta",
    subtitle: "Et 2:21-23 e 6:2 • o conspirador cuja denúncia foi escrita nas crônicas e esquecida por quatro capítulos",
    text: "\"Naqueles dias, assentando-se Mardoqueu à porta do rei, dois camareiros do rei, dos guardas da porta, Bigtã e Teres, grandemente se indignaram, e procuraram atentar contra o rei Assuero\" (Et 2:21). O texto não diz o motivo da indignação, e o silêncio é típico deste livro. Bigtã é um eunuco da guarda da porta — cargo de acesso, o mesmo lugar onde Mardoqueu se assentava —, e é justamente essa proximidade que o traiu: \"E veio isto ao conhecimento de Mardoqueu, e ele o fez saber à rainha Ester; e Ester o disse ao rei, em nome de Mardoqueu. E inquiriu-se o negócio, e se descobriu, e ambos foram pendurados numa forca; e foi escrito nas crônicas perante o rei\" (Et 2:22-23). Ninguém agradece a Mardoqueu; fica só a tinta no rolo. Quatro capítulos depois, numa noite em que o sono foge do rei e alguém abre esse mesmo rolo, é o nome de Bigtã que reaparece: \"E achou-se escrito que Mardoqueu tinha denunciado Bigtã e Teres, dois dos camareiros do rei, da guarda da porta, que tinham procurado lançar mão do rei Assuero\" (Et 6:2). Um conspirador morto e esquecido é a peça que salva um povo inteiro, e o livro nunca diz de quem foi o arranjo.",
  },
  "teres-o-conspirador": {
    title: "Teres, camareiro do rei, dos guardas da porta",
    subtitle: "Et 2:21-23 e 6:2 • o segundo conspirador, pendurado numa forca e anotado num rolo",
    text: "\"dois camareiros do rei, dos guardas da porta, Bigtã e Teres, grandemente se indignaram, e procuraram atentar contra o rei Assuero\" (Et 2:21). Teres é o segundo nome da conspiração, e o seu destino é descrito em oito palavras: \"e ambos foram pendurados numa forca\" (Et 2:23) — a mesma pena que, cinco capítulos adiante, cairá sobre Hamã, e no mesmo tipo de madeira. O que sobrevive dele é uma linha de arquivo: \"e foi escrito nas crônicas perante o rei\". Este livro é feito de objetos e registros que ficam guardados até a hora certa — a forca do quintal, a sorte lançada em Nisã, o anel que muda de mão — e o rolo em que o nome de Teres foi anotado é o mais importante de todos. Na madrugada de 6:1, com Hamã já a caminho do pátio para pedir a morte de Mardoqueu, é essa página que se abre: \"E achou-se escrito que Mardoqueu tinha denunciado Bigtã e Teres\" (Et 6:2). O texto registra a coincidência com toda a frieza e não a explica; o comentário mais próximo que a Escritura oferece está em outro livro: \"A sorte se lança no regaço, mas do Senhor procede toda a determinação\" (Pv 16:33).",
  },
  "parsandata-filho-de-hama": {
    title: "Parsandata, o primeiro dos dez filhos de Hamã",
    subtitle: "Et 9:7 • um dos dez que caíram na fortaleza de Susã no dia treze de Adar",
    text: "\"Como também a Parsandata, e a Dalfom e a Aspata\" (Et 9:7). Parsandata abre a lista dos dez, que o livro dá nome por nome em três versículos (Et 9:7-9) do mesmo modo minucioso com que deu os sete camareiros de 1:10 e os sete príncipes de 1:14. Estes são a \"multidão de seus filhos\" de que o pai se gabara diante da mulher e dos amigos, na noite em que mandou levantar a forca: \"E contou-lhes Hamã a glória das suas riquezas, a multidão de seus filhos, e tudo em que o rei o tinha engrandecido\" (Et 5:11). O que o texto diz da morte deles vem colado à frase que o capítulo repete três vezes: \"Os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus, mataram, porém ao despojo não estenderam a sua mão\" (Et 9:10). A casa de Agague termina em Susã sem que ninguém leve nada dela — o contrário exato de 1 Samuel 15, onde Saul poupou o rei amalequita e \"o melhor das ovelhas e das vacas\" (1Sm 15:9).",
  },
  "dalfom-filho-de-hama": {
    title: "Dalfom, o segundo dos dez filhos de Hamã",
    subtitle: "Et 9:7 • um dos dez mortos em Susã e depois pendurados numa forca",
    text: "\"Como também a Parsandata, e a Dalfom e a Aspata\" (Et 9:7). Os dez filhos de Hamã morrem no dia treze de Adar, dentro da fortaleza de Susã, no mesmo dia em que os judeus mataram ali quinhentos homens (Et 9:6). No dia seguinte, a pedido da rainha, os corpos são expostos: \"Então disse Ester: Se bem parecer ao rei, conceda-se aos judeus que se acham em Susã que também façam amanhã conforme ao mandado de hoje; e pendurem numa forca os dez filhos de Hamã\" (Et 9:13), \"e enforcaram os dez filhos de Hamã\" (Et 9:14). Era o fim público de uma casa, na mesma madeira em que o pai fora pendurado (Et 7:10) — a que ele mandara levantar no próprio quintal para outro homem. O resumo do capítulo 9 junta as duas gerações numa frase só: \"Mas, vindo isto perante o rei, mandou ele por cartas que o mau intento que Hamã formara contra os judeus, se tornasse sobre a sua cabeça; pelo que penduraram a ele e a seus filhos numa forca\" (Et 9:25).",
  },
  "aspata-filho-de-hama": {
    title: "Aspata, o terceiro dos dez filhos de Hamã",
    subtitle: "Et 9:7 • um dos dez nomeados um a um no dia em que sucedeu o contrário",
    text: "\"Como também a Parsandata, e a Dalfom e a Aspata\" (Et 9:7). O livro podia ter escrito \"e os dez filhos de Hamã\" — e escreve isso também, no versículo 10 —, mas antes gasta três versículos dando os nomes. É o mesmo cuidado com que nomeou os sete eunucos que foram buscar Vasti e os sete príncipes que a condenaram: quando este texto quer marcar o fim de uma coisa, ele a soletra. O que se encerra aqui é a casa de Agague em Susã, do agagita que quis destruir \"todos os judeus, o povo de Mardoqueu, que havia em todo o reino de Assuero\" (Et 3:6). E o dia é o que o pai escolheu: o treze de Adar, tirado por sorte em Nisã, \"para cada dia, e para cada mês, até ao duodécimo mês\" (Et 3:7). A data marcada para o extermínio dos judeus é a data em que a família dele acaba, e o versículo de abertura do capítulo diz apenas: \"sucedeu o contrário\" (Et 9:1).",
  },
  "porata-filho-de-hama": {
    title: "Porata, o quarto dos dez filhos de Hamã",
    subtitle: "Et 9:8 • um dos dez que caíram no dia que o pai escolheu por sorte",
    text: "\"E a Porata, e a Adalia, e a Aridata\" (Et 9:8). Porata é um dos dez filhos que Hamã contou como parte da sua glória — \"a multidão de seus filhos\" (Et 5:11) — na noite em que o pai não conseguia gozar de nada \"enquanto eu vir o judeu Mardoqueu assentado à porta do rei\" (Et 5:13). A ironia que o livro monta e não comenta é essa: o homem que tinha filhos, riquezas e o assento acima de todos os príncipes perdeu tudo isso por causa de um velho sentado num banco. Sobre a morte dos dez, o texto insiste na única coisa que quer que se note: \"porém ao despojo não estenderam a sua mão\" (Et 9:10). Havia decreto autorizando o saque, tanto na carta de Hamã (Et 3:13) quanto na de Mardoqueu (Et 8:11), e ninguém tocou em nada. Quatrocentos anos antes, um rei benjamita tinha feito o contrário com os bens de Amaleque e perdido o reino por isso (1Sm 15:19-23).",
  },
  "adalia-filho-de-hama": {
    title: "Adalia, o quinto dos dez filhos de Hamã",
    subtitle: "Et 9:8 • um dos dez mortos na fortaleza de Susã no dia treze do mês de Adar",
    text: "\"E a Porata, e a Adalia, e a Aridata\" (Et 9:8). Os dez irmãos aparecem na Escritura uma vez só, e é para morrer. O contexto é o mais duro do livro e também o mais contido: os judeus de Susã \"se ajuntaram para pôr as mãos naqueles que procuravam o seu mal\" (Et 9:2), conforme a carta que lhes permitia \"que se reunissem, e se dispusessem para defenderem as suas vidas\" (Et 8:11). Não é uma ofensiva; é o dia marcado por outro para matá-los, e eles estão vivos no fim dele. Os filhos do agagita caem dentro da fortaleza, junto com os quinhentos homens de Susã (Et 9:6), e o rei, ao receber o número, faz a conta em voz alta e pergunta à rainha o que mais ela quer (Et 9:12). O que ela quer é o dia seguinte e a forca (Et 9:13) — o fim público da casa que quis acabar com o povo dela.",
  },
  "aridata-filho-de-hama": {
    title: "Aridata, o sexto dos dez filhos de Hamã",
    subtitle: "Et 9:8 • um dos dez nomes que fecham a casa de Hamã, o agagita",
    text: "\"E a Porata, e a Adalia, e a Aridata\" (Et 9:8). O nome está numa lista que serve de contrapeso a outra, escrita seis capítulos antes: a dos que iam morrer \"desde o jovem até ao velho, crianças e mulheres, em um mesmo dia\" (Et 3:13). O decreto de Hamã não pouparia idade nenhuma; o dia que ele escolheu por sorte terminou com os seus dez filhos entre os mortos. O texto não comemora: nomeia, conta e passa adiante para a frase que lhe importa — \"porém ao despojo não estenderam a sua mão\" (Et 9:10). O eco de 1 Samuel 15 é exato e o livro nunca o menciona: um benjamita da casa de Quis (Et 2:5) acabando com a casa de Agague (Et 3:1) e não tocando no despojo, quatrocentos anos depois de Saul ter poupado Agague e se ter lançado ao despojo (1Sm 15:8-9, 19).",
  },
  "farmasta-filho-de-hama": {
    title: "Farmasta, o sétimo dos dez filhos de Hamã",
    subtitle: "Et 9:9 • um dos dez que o pai contara entre as suas glórias",
    text: "\"E a Farmasta, e a Arisai, e a Aridai, e a Vaisata\" (Et 9:9). O último versículo da lista traz quatro nomes de uma vez, e com ele se fecha a única coisa que Hamã, no capítulo 5, apresentou como orgulho ao lado do dinheiro e do cargo: \"a glória das suas riquezas, a multidão de seus filhos, e tudo em que o rei o tinha engrandecido, e como o tinha exaltado sobre os príncipes e servos do rei\" (Et 5:11). Riquezas, filhos e cargo — os três desaparecem em quatro capítulos: a casa passa a Ester (Et 8:1), o anel passa a Mardoqueu (Et 8:2), e os filhos caem no dia treze de Adar (Et 9:10). O livro registra o desmonte peça por peça e não atribui a ninguém. A única voz que anunciou isso de antemão foi a da própria mulher dele: \"não prevalecerás contra ele, antes certamente cairás diante dele\" (Et 6:13).",
  },
  "arisai-filho-de-hama": {
    title: "Arisai, o oitavo dos dez filhos de Hamã",
    subtitle: "Et 9:9 • um dos dez mortos e depois pendurados numa forca em Susã",
    text: "\"E a Farmasta, e a Arisai, e a Aridai, e a Vaisata\" (Et 9:9). Estes dez foram mortos no dia treze e expostos no dia catorze, a pedido de Ester e por edito do rei: \"Então disse o rei que assim se fizesse; e publicou-se um edito em Susã, e enforcaram os dez filhos de Hamã\" (Et 9:14). Pendurar os corpos não era matar duas vezes: era declarar publicamente extinta a casa que tinha comprado, por dez mil talentos de prata, o direito de acabar com um povo (Et 3:9). O texto resume o caso do pai e dos filhos numa frase de sentença: \"mandou ele por cartas que o mau intento que Hamã formara contra os judeus, se tornasse sobre a sua cabeça; pelo que penduraram a ele e a seus filhos numa forca\" (Et 9:25). A forca é a mesma que Zeres mandou levantar numa noite (Et 5:14), no quintal da casa deles.",
  },
  "aridai-filho-de-hama": {
    title: "Aridai, o nono dos dez filhos de Hamã",
    subtitle: "Et 9:9 • um dos dez nomes da casa que caiu no dia marcado por ela mesma",
    text: "\"E a Farmasta, e a Arisai, e a Aridai, e a Vaisata\" (Et 9:9). O capítulo 9 é o único do livro em que morre gente em cena, e é escrito com uma sobriedade que chama a atenção: dá os números — quinhentos em Susã no dia treze, trezentos no dia catorze, setenta e cinco mil nas províncias (Et 9:6, 15, 16) —, dá os dez nomes, e repete três vezes a mesma ressalva sobre o que NÃO foi feito: \"porém ao despojo não estenderam a sua mão\". Não há canto de vitória, não há altar, não há sacrifício de ação de graças; há descanso e comida repartida: \"e descansaram no dia catorze, e fizeram, daquele dia, dia de banquetes e de alegria\" (Et 9:17), com \"presentes uns aos outros, e dádivas aos pobres\" (Et 9:22). Um povo que não tocou nos bens dos inimigos repartiu os seus próprios.",
  },
  "vaizata-filho-de-hama": {
    title: "Vaisata, o décimo dos filhos de Hamã",
    subtitle: "Et 9:9 • o último nome da lista, e o fim da casa do agagita",
    text: "\"E a Farmasta, e a Arisai, e a Aridai, e a Vaisata\" (Et 9:9). Com este nome termina a lista e termina a casa. O livro começou apresentando o pai por três palavras — \"filho de Hamedata, agagita\" (Et 3:1) — que ligam a história a uma dívida antiga: Agague, rei dos amalequitas, que Saul tomou vivo contra a ordem recebida (1Sm 15:8-9) e que Samuel despedaçou em Gilgal (1Sm 15:33), do povo contra o qual fora dito que haveria \"guerra do Senhor contra Amaleque de geração em geração\" (Êx 17:16) e cuja memória Israel devia apagar de debaixo do céu (Dt 25:19). Em Susã, quatrocentos anos e um império depois, um benjamita da casa de Quis vê essa casa acabar sem estender a mão ao despojo (Et 9:10). O livro de Ester não cita 1 Samuel, não cita Êxodo, não cita Deuteronômio e não nomeia Deus. Só conta o que aconteceu, e deixa quem lê fazer a conta.",
  },
};
