// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de PERSONAGEM (por `id`) das cenas de job. Vem por import() junto com
// o roteiro do livro: quem lê Rute não baixa os nomes de Crônicas.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHARS: Record<string, StageInfo> = {
  "jo": {
    title: "Jó, o homem da terra de Uz",
    subtitle: "Jó 1-42 • o maior de todos os do oriente, assentado no meio da cinza",
    text: "\"Havia um homem na terra de Uz, cujo nome era Jó; e era este homem íntegro, reto e temente a Deus e desviava-se do mal\" (Jó 1:1) — quatro palavras que o livro repetirá na boca do próprio Deus (1:8; 2:3), para que ninguém leia a desgraça que vem como castigo merecido. Uz fica a leste, fora de Israel e fora da aliança: Jó não é hebreu, não tem sacerdote e não tem templo, e mesmo assim \"se levantava de madrugada, e oferecia holocaustos segundo o número de todos eles\" pelos dez filhos, \"porque dizia Jó: Porventura pecaram meus filhos\" (1:5). Tinha \"sete mil ovelhas, três mil camelos, quinhentas juntas de bois e quinhentas jumentas\" e era \"maior do que todos os do oriente\" (1:3). Perde tudo em quatro notícias que se atropelam, e responde adorando: \"o Senhor o deu, e o Senhor o tomou: bendito seja o nome do Senhor\" (1:21). Ferido depois \"de úlceras malignas, desde a planta do pé até ao alto da cabeça\" (2:7), toma um caco de telha para se raspar e senta-se na cinza — e dali não sai até o fim do livro. Ali diz as duas frases que se contradizem sem se anular: \"receberemos o bem de Deus, e não receberíamos o mal?\" (2:10) e \"pereça o dia em que nasci\" (3:3). Ezequiel o põe ao lado de Noé e de Daniel entre os justos (Ez 14:14) e Tiago fecha a conta: \"Ouvistes qual foi a paciência de Jó, e vistes o fim que o Senhor lhe deu\" (Tg 5:11).",
  },
  "mulher-de-jo": {
    title: "A mulher de Jó",
    subtitle: "Jó 2:9 • a única voz da casa que sobrou, e a mais dura do livro",
    text: "\"Então sua mulher lhe disse: Ainda reténs a tua sinceridade? Amaldiçoa a Deus, e morre\" (Jó 2:9). É a única fala dela na Escritura inteira, e costuma ser lida como traição — mas convém lembrar o que ela perdeu no mesmo dia em que ele perdeu: os mesmos sete filhos e as mesmas três filhas, a mesma casa, o mesmo gado, e depois o marido coberto de chagas de que ela tem de cuidar. O que ela propõe é exatamente o que o adversário apostou na corte do céu — \"verás se não blasfema contra ti na tua face\" (1:11; 2:5) —, e por isso a resposta dele é firme sem ser cruel: \"Como fala qualquer doida, falas tu; receberemos o bem de Deus, e não receberíamos o mal?\" (2:10). Ele não a chama de doida: diz que ela está falando como quem perdeu o juízo, que é outra coisa. Jó volta a falar dela no auge da amargura — \"O meu hálito se fez estranho à minha mulher\" (19:17) —, prova de que ela continuou por perto. E quando \"o Senhor virou o cativeiro de Jó\" (42:10) e nasceram outros sete filhos e três filhas, foi ela quem os teve.",
  },
  "satanas-o-adversario": {
    title: "Satanás, o adversário, que veio entre os filhos de Deus",
    subtitle: "Jó 1:6-12; 2:1-7 • o acusador que se apresenta na corte celestial",
    text: "\"E num dia em que os filhos de Deus vieram apresentar-se perante o Senhor, veio também Satanás entre eles\" (Jó 1:6). No hebraico a palavra vem com artigo — ha-satan, O ADVERSÁRIO —, que é o nome de uma função antes de ser o nome de uma pessoa: o que se opõe, o que acusa. Por isso a cena viva o desenha como um dos da corte, de veste escura e sem auréola, e não como o dragão de sete cabeças do Apocalipse: aqui ele ENTRA no céu, responde a uma pergunta e sai — \"De rodear a terra, e passear por ela\" (1:7) —, e não pode tocar em nada sem licença (\"somente contra ele não estendas a tua mão\", 1:12; \"porém guarda a sua vida\", 2:6). A acusação dele não é contra a conduta de Jó, é contra o valor da piedade: \"Porventura teme Jó a Deus debalde?\" (1:9). É o mesmo papel que Zacarias vê à direita do sumo sacerdote Josué \"para se lhe opor\" (Zc 3:1), o que pediu para cirandar Simão como trigo (Lc 22:31) e o que João ouve ser derrubado, \"o acusador de nossos irmãos... o qual diante do nosso Deus os acusava de dia e de noite\" (Ap 12:10). Pedro o descreve fazendo em terra o mesmo giro de Jó 1:7: \"o diabo, vosso adversário, anda em derredor, bramando como leão\" (1Pe 5:8).",
  },
  "elifaz-o-temanita": {
    title: "Elifaz, o temanita — o mais velho dos três amigos",
    subtitle: "Jó 2:11; 4-5; 15; 22 • o que veio de Temã e o que teve a visão da noite",
    text: "\"Ouvindo, pois, três amigos de Jó todo este mal que tinha vindo sobre ele, vieram cada um do seu lugar: Elifaz o temanita\" (Jó 2:11) — e é ele que fala primeiro, três vezes, sempre à frente dos outros. Temã é praça de Edom, cidade que a Escritura associa exatamente àquilo que ele exibe: \"Acaso não há mais sabedoria em Temã? Pereceu o conselho dos entendidos?\" (Jr 49:7; cf. Ob 8). Começa com respeito, lembrando o que Jó foi para os outros — \"Eis que ensinaste a muitos, e tens fortalecido as mãos fracas\" (4:3) — e sustenta a sua doutrina inteira numa observação: \"qual é o inocente que jamais pereceu?\" (4:7), \"os que lavram iniqüidade, e semeiam mal, segam o mesmo\" (4:8). O seu argumento de autoridade não é um texto, é uma experiência que ele mesmo conta: um sussurro na noite, o espanto, os cabelos arrepiados e um vulto que pergunta \"Seria porventura o homem mais justo do que Deus?\" (4:12-17). Sabe dizer coisas belíssimas — \"ele faz a chaga, e ele mesmo a liga; ele fere, e as suas mãos curam\" (5:18) — e mesmo assim é a ele que Deus se dirige no fim: \"A minha ira se acendeu contra ti, e contra os teus dois amigos, porque não falastes de mim o que era reto, como o meu servo Jó\" (42:7).",
  },
  "bildade-o-suita": {
    title: "Bildade, o suíta — o homem da tradição dos pais",
    subtitle: "Jó 2:11; 8; 18; 25 • o que manda perguntar às gerações passadas",
    text: "Segundo dos três a falar, \"Bildade o suíta\" (Jó 2:11) — o nome liga-o provavelmente a Suá, filho de Abraão com Quetura, mandado \"para a terra oriental\" (Gn 25:2,6), gente do mesmo oriente de Jó. Onde Elifaz apela para uma visão que teve, Bildade apela para o que sempre se soube: \"pergunta agora às gerações passadas; e prepara-te para a inquirição de seus pais... porque nós somos de ontem, e nada sabemos\" (8:8-9). É o mais curto e o mais frio dos três: abre a boca comparando a fala de Jó a \"um vento impetuoso\" (8:2) e, sete dias depois de dez enterros, diz na cara do pai que \"se teus filhos pecaram contra ele, também ele os lançou na mão da sua transgressão\" (8:4). O seu retrato do ímpio é o mais bem feito do bloco — o papiro que não cresce sem lodo, a confiança que \"será como a teia de aranha\" (8:14), a planta viçosa cujo lugar, arrancada ela, dirá \"Nunca te vi!\" (8:18). No terceiro discurso reduz-se a seis versículos e a uma pergunta que o livro inteiro estava perseguindo: \"Como, pois, seria justo o homem para com Deus, e como seria puro aquele que nasce de mulher?\" (25:4). Também sobre ele cai a repreensão de 42:7, e só é perdoado quando Jó ora pelos três (42:8-10).",
  },
  "zofar-o-naamatita": {
    title: "Zofar, o naamatita — o mais áspero dos três",
    subtitle: "Jó 2:11; 11; 20 • o que diz a Jó que Deus lhe exige menos do que ele merece",
    text: "\"E Zofar o naamatita\" (Jó 2:11), o terceiro e o último a falar em cada rodada — e o único que não chega a uma terceira vez: no lugar dele, no fim do ciclo, cai o silêncio dos amigos. Fala só duas vezes, e as duas com a mesma dureza: chama Jó de \"homem falador\" (11:2), diz que as suas palavras são mentiras e dispara a frase mais cruel do bloco — \"sabe, pois, que Deus exige de ti menos do que merece a tua iniqüidade\" (11:6), isto é, você está sendo tratado com brandura. E, no entanto, a peça central do seu discurso é grande e verdadeira: \"Como as alturas dos céus é a sua sabedoria; que poderás tu fazer? É mais profunda do que o inferno, que poderás tu saber? Mais comprida é a sua medida do que a terra, e mais larga do que o mar\" (11:7-9). O erro de Zofar não está na doutrina, está no uso: ele emprega a imensidão de Deus para calar um homem, quando é justamente essa imensidão que, no fim, responde a Jó de dentro de um redemoinho (38:1) sem nunca dar razão aos três (42:7).",
  },
  "mensageiro-dos-bois-e-jumentas": {
    title: "O primeiro mensageiro — o que escapou dos sabeus",
    subtitle: "Jó 1:14-15 • a notícia da lavoura e das quinhentas jumentas",
    text: "\"Que veio um mensageiro a Jó, e lhe disse: Os bois lavravam, e as jumentas pastavam junto a eles; E deram sobre eles os sabeus, e os tomaram, e aos servos feriram ao fio da espada; e só eu escapei para trazer-te a nova\" (Jó 1:14-15). Ele abre a frase pelo lado mais pacífico possível — o dia de trabalho comum, a junta no sulco, os animais soltos ao lado — e só depois deixa cair a espada dentro dela. Os sabeus são gente do sul da Arábia, do comércio de ouro e incenso e das caravanas que atravessavam o deserto (cf. Gn 10:7; 1Rs 10:1-2); aqui aparecem no outro ofício da estrada, o saque. O que este homem traz não é apenas a perda das \"quinhentas juntas de bois e quinhentas jumentas\" (1:3): é a morte dos boiadeiros que trabalhavam com ele. A frase com que termina — \"e só eu escapei para trazer-te a nova\" — será repetida palavra por palavra pelos outros três, e é ela que dá à cena o seu efeito: nenhuma das quatro desgraças tem tempo de ser chorada antes da seguinte.",
  },
  "mensageiro-do-fogo-de-deus": {
    title: "O segundo mensageiro — o que escapou do fogo caído do céu",
    subtitle: "Jó 1:16 • \"Fogo de Deus caiu do céu\"",
    text: "\"Estando este ainda falando, veio outro e disse: Fogo de Deus caiu do céu, e queimou as ovelhas e os servos, e os consumiu, e só eu escapei para trazer-te a nova\" (Jó 1:16). Este é o único dos quatro que interpreta o que viu, e a interpretação dele é o coração da provação: chama de FOGO DE DEUS aquilo que o leitor sabe ter sido soltado pela mão do adversário (1:12). Nada no palco vem do alto — a fala é dele, um pastor sobrevivente, não uma voz do céu; o que domina o quadro é o traço da queimada. Sete mil ovelhas (1:3) e os pastores que dormiam com elas desapareceram numa só descarga, e a notícia chega em cima da anterior, sem intervalo. É a mesma confusão em que os amigos vão cair nos capítulos seguintes: ler o golpe como sentença e a sentença como veredicto de Deus sobre o caráter de quem o recebeu.",
  },
  "mensageiro-dos-caldeus": {
    title: "O terceiro mensageiro — o que escapou das três tropas dos caldeus",
    subtitle: "Jó 1:17 • a notícia dos três mil camelos levados",
    text: "\"Estando ainda este falando, veio outro, e disse: Ordenando os caldeus três tropas, deram sobre os camelos, e os tomaram, e aos servos feriram ao fio da espada; e só eu escapei para trazer-te a nova\" (Jó 1:17). Se os sabeus vieram do sul, estes vêm do norte, do outro extremo do mundo conhecido de Uz — gente da Mesopotâmia, a terra de onde saíra Abraão, \"Ur dos caldeus\" (Gn 11:28), e cujo nome a Escritura mais tarde dará a um império inteiro: \"eis que suscito os caldeus, nação amarga e impetuosa\" (Hc 1:6). O detalhe militar que ele traz é o que faz diferença: TRÊS TROPAS, ordenadas, cercando o acampamento por mais de um lado. Não é bando de oportunistas, é operação — e sai levando os três mil camelos, que eram o capital de transporte da casa e o que ligava Jó ao comércio do oriente. Entre a segunda notícia e esta não houve pausa: as desgraças de cima e as de baixo, o fogo do céu e a espada dos homens, chegam pela mesma porta.",
  },
  "mensageiro-do-vento-do-deserto": {
    title: "O quarto mensageiro — o que escapou da casa caída sobre os filhos",
    subtitle: "Jó 1:18-19 • o grande vento dalém do deserto e os quatro cantos da casa",
    text: "\"Estando ainda este falando, veio outro, e disse: Estando teus filhos e tuas filhas comendo e bebendo vinho, em casa de seu irmão primogênito, Eis que um grande vento sobreveio dalém do deserto, e deu nos quatro cantos da casa, que caiu sobre os jovens, e morreram; e só eu escapei para trazer-te a nova\" (Jó 1:18-19). Este é o pior dos quatro e vem por último de propósito: os três primeiros tiraram o gado e os servos, este tira os dez filhos de uma vez. O detalhe dos QUATRO CANTOS diz que não foi rajada de um lado só — a casa foi tomada por inteiro —, e o lugar é o mesmo banquete por turno que o pai santificava de madrugada, temendo justamente que ali seus filhos pecassem (1:5). Note-se que ele repete a fórmula dos outros três sem mudar uma sílaba: \"e só eu escapei para trazer-te a nova\". Depois dele não vem mais ninguém, e é então que Jó se levanta, rasga o manto, rapa a cabeça, lança-se em terra — e adora (1:20).",
  },
  "eliu-filho-de-baraquel-o-buzita": {
    title: "Eliú, filho de Baraquel, o buzita, da família de Rão",
    subtitle: "Jó 32–37 — o moço que estava calado no monturo desde o capítulo 3",
    text: "Ninguém o apresenta. Ele não vem com os três em 2:11, não é contado entre os consoladores, e aparece de repente quando o debate morre: \"Então aqueles três homens cessaram de responder a Jó; porque era justo aos seus próprios olhos\" (Jó 32:1). O texto insiste em duas coisas sobre ele, e o palco tem de mostrar as duas. A primeira é que esteve ali o tempo todo, ouvindo: \"Eis que aguardei as vossas palavras, e dei ouvidos às vossas considerações, até que buscásseis razões\" (Jó 32:11). A segunda é que é MOÇO — \"Eliú, porém, esperou para falar a Jó, porquanto tinham mais idade do que ele\" (Jó 32:4); \"Eu sou de menos idade, e vós sois idosos\" (Jó 32:6) —, e é por isso que ele é `homem` no meio de quatro `patriarca`s. A sua ira acende-se duas vezes e por motivos opostos: contra Jó, \"porque se justificava a si mesmo, mais do que a Deus\", e contra os três amigos, \"porque, não achando que responder, todavia condenavam a Jó\" (Jó 32:2-3). O que o autoriza a falar não é a idade, é o sopro: \"Na verdade, há um espírito no homem, e a inspiração do TodoPoderoso o faz entendido. Os grandes não são os sábios, nem os velhos entendem o que é direito\" (Jó 32:8-9). Ele descreve-se como um odre a estourar — \"Eis que dentro de mim sou como o mosto, sem respiradouro, prestes a arrebentar, como odres novos\" (Jó 32:19) — e promete não bajular ninguém: \"Porque não sei usar de lisonjas; em breve me levaria o meu Criador\" (Jó 32:22). Nos seis capítulos que se seguem diz coisas que nenhum dos três disse: chama Jó pelo nome, põe-se no mesmo barro que ele (\"Eis que vim de Deus, como tu; do barro também eu fui formado\", Jó 33:6), afirma que Deus fala pelo sonho e pela dor, apresenta o mensageiro intérprete \"um entre milhares\" com o resgate na boca (Jó 33:23-24), e ensina que a aflição abre o ouvido pela mesma corda que aperta (Jó 36:8-10). Nos dois últimos capítulos vira hino: a chuva destilada do vapor, o gado que dá notícia do temporal que sobe, a neve que recebe ordem, o gelo pelo sopro de Deus e os céus \"firmes como espelho fundido\". A frase com que se cala é a última palavra humana antes de Deus: \"Ao Todo-Poderoso não podemos alcançar; grande é em poder\" (Jó 37:23) — e no versículo seguinte o SENHOR responde de um redemoinho. Guarde-se o detalhe do epílogo, que muda a leitura de tudo o que ele disse: quando a ira do SENHOR se acende \"contra ti, e contra os teus dois amigos\" (Jó 42:7), Eliú não é nomeado, não é repreendido e não tem holocausto nenhum a oferecer.",
  },
  "jemima": {
    title: "Jemima, a primeira filha do último estado de Jó",
    subtitle: "Jó 42:14-15 — a filha nomeada, com herança entre seus irmãos",
    text: "\"E chamou o nome da primeira Jemima\" (Jó 42:14). Os sete filhos varões do segundo estado de Jó não são nomeados; as três filhas são, e este é um dos poucos lugares da Escritura em que isso acontece. O nome liga-se à pomba e à luz do dia, e é escolha de um homem que passou trinta e nove capítulos coberto de cinza e no escuro — \"esperando eu a luz, veio a escuridão\" (Jó 30:26). Ela nasce depois do redemoinho, na casa que foi refeita, e nunca conheceu o monturo senão de ouvir contar. O que o texto diz dela e das irmãs vem em duas linhas, e a segunda é jurídica: \"E em toda a terra não se acharam mulheres tão formosas como as filhas de Jó; e seu pai lhes deu herança entre seus irmãos\" (Jó 42:15). Herança entre os irmãos, havendo sete varões vivos, é fora do costume: no direito de Israel a filha só herdava na falta de filho homem, e mesmo isso foi exceção conquistada pelas filhas de Zelofeade (Nm 27:1-11). É o mesmo homem que jurou não ter desprezado \"o direito do meu servo ou da minha serva\", porque \"Aquele que me formou no ventre não o fez também a ele?\" (Jó 31:13,15). Jemima é o rosto dessa coerência.",
  },
  "quezia": {
    title: "Quezia, a segunda filha do último estado de Jó",
    subtitle: "Jó 42:14-15 — o nome de um perfume, dado por um homem que cheirava a cinza",
    text: "\"E o nome da segunda Quezia\" (Jó 42:14). Quezia é a cássia, a casca aromática que entrava na composição do óleo santo da unção — \"e de cássia quinhentos siclos, segundo o siclo do santuário\" (Êx 30:24) — e que reaparece entre os perfumes da veste do rei no Salmo 45:8. Chamar assim a uma filha é dizer que a casa voltou a ter cheiro bom, e quem lhe pôs o nome é o homem cuja pele se enegrecera sobre ele e cujos ossos estavam queimados do calor (Jó 30:30). Nasce na casa refeita, depois de o SENHOR ter virado o cativeiro de Jó \"quando orava pelos seus amigos\" (Jó 42:10). Dela e das irmãs o texto diz o que não diz de nenhuma outra mulher da Bíblia com tanta simplicidade: \"em toda a terra não se acharam mulheres tão formosas como as filhas de Jó\" — e acrescenta o que vale mais do que o elogio, \"e seu pai lhes deu herança entre seus irmãos\" (Jó 42:15), coisa que a lei só previa quando não havia filho varão (Nm 27:1-11), e Jó tinha sete.",
  },
  "quere-hapuque": {
    title: "Quéren-Hapuque, a terceira filha do último estado de Jó",
    subtitle: "Jó 42:14-15 — \"frasco de pintura de olhos\", o nome mais improvável do livro",
    text: "\"E o nome da terceira Quéren-Hapuque\" (Jó 42:14). O nome quer dizer, ao pé da letra, chifre ou frasco de pûk — o antimônio com que se realçavam as pálpebras, o mesmo com que Jezabel \"pintou-se em volta dos olhos\" (2Rs 9:30) e que Jeremias usa como imagem (Jr 4:30). É o pote de maquiagem da casa. Quem dá esse nome a uma filha é o homem que disse \"Lançou-me na lama, e fiquei semelhante ao pó e à cinza\" (Jó 30:19) e que se arrependeu \"no pó e na cinza\" (Jó 42:6): o epílogo põe na boca dele, sem uma palavra de comentário, a alegria de uma casa em que se voltou a cuidar da aparência. E o versículo seguinte fecha o livro com um gesto que a época não pedia a ninguém: \"E em toda a terra não se acharam mulheres tão formosas como as filhas de Jó; e seu pai lhes deu herança entre seus irmãos\" (Jó 42:15) — herança de filha ao lado da de sete varões vivos, quando o direito só a concedia na ausência deles (Nm 27:1-11; Js 17:3-6).",
  },
};
