// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de PERSONAGEM (por `id`) das cenas de joshua. Vem por import() junto com
// o roteiro do livro: quem lê Rute não baixa os nomes de Crônicas.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHARS: Record<string, StageInfo> = {
  ruben: { title: "Rúben", subtitle: "O primogênito de Jacó e Lia (Gn 29:32)", text: "O primeiro filho de Lia: \"Porque o Senhor atendeu à minha aflição\" (Gn 29:32). \"Minha força e o princípio de meu vigor\", diz dele a bênção de Jacó (Gn 49:3) — mas por ter subido ao leito do pai (Gn 35:22) perdeu a primazia: \"Impetuoso como a água, não serás o mais excelente\" (Gn 49:4). Foi ele, contudo, quem tentou livrar José da morte (Gn 37:21-22)." },
  simeao: { title: "Simeão", subtitle: "2º filho de Lia (Gn 29:33)", text: "Segundo filho de Lia — \"Porquanto o Senhor ouviu que eu era desprezada\" (Gn 29:33). Com o irmão Levi, tomou da espada e vingou a desonra de Diná, matando os homens de Siquém (Gn 34:25). Por isso a bênção de Jacó pesou-lhe a mão: \"suas espadas são instrumentos de violência... eu os dividirei em Jacó, e os espalharei em Israel\" (Gn 49:5-7)." },
  issacar: { title: "Issacar", subtitle: "5º filho de Lia (Gn 30:17-18)", text: "Quinto filho de Lia, dado quando \"ouviu Deus a Lia\": \"Deus me tem dado o meu galardão\" (Gn 30:17-18). Na bênção de Jacó é retratado como \"jumento de fortes ossos, deitado entre dois fardos\", que viu que \"o descanso era bom, e que a terra era deliciosa\", e abaixou o ombro ao trabalho (Gn 49:14-15)." },
  zebulom: { title: "Zebulom", subtitle: "6º filho de Lia (Gn 30:19-20)", text: "Sexto e último filho de Lia: \"Deus me deu uma boa dádiva... desta vez morará o meu marido comigo\" (Gn 30:20). Jacó lhe profetizou vocação de mar e comércio: \"Zebulom habitará no porto dos mares, e será como porto dos navios, e o seu termo será para Sidom\" (Gn 49:13)." },
  da: { title: "Dã", subtitle: "1º filho de Bila (Gn 30:5-6)", text: "Primeiro filho de Bila, serva de Raquel: \"Julgou-me Deus, e também ouviu a minha voz\" — daí o nome Dã, ligado a \"julgar\" (Gn 30:6). A bênção de Jacó ecoa o próprio nome: \"Dã julgará o seu povo, como uma das tribos de Israel\", e o compara à serpente astuta \"junto ao caminho\" (Gn 49:16-17)." },
  naftali: { title: "Naftali", subtitle: "2º filho de Bila (Gn 30:7-8)", text: "Segundo filho de Bila: nasceu no auge da rivalidade das irmãs — \"Com grandes lutas tenho lutado com minha irmã; também venci\" (Gn 30:8). Jacó o abençoou com imagem de liberdade e beleza: \"Naftali é uma gazela solta; ele dá palavras formosas\" (Gn 49:21)." },
  gade: { title: "Gade", subtitle: "1º filho de Zilpa (Gn 30:10-11)", text: "Primeiro filho de Zilpa, serva de Lia: ao vê-lo, Lia exclamou \"Afortunada!\", e o chamou Gade (Gn 30:11). A bênção de Jacó joga com o sentido guerreiro do nome: \"uma tropa o acometerá; mas ele a acometerá por fim\" (Gn 49:19)." },
  aser: { title: "Aser", subtitle: "2º filho de Zilpa (Gn 30:12-13)", text: "Segundo filho de Zilpa: \"Para minha ventura; porque as filhas me terão por bem-aventurada\" — Aser significa \"feliz, bem-aventurado\" (Gn 30:13). Jacó lhe prometeu fartura: \"De Aser, o seu pão será gordo, e ele dará delícias reais\" (Gn 49:20)." },
  benjamim: { title: "Benjamim", subtitle: "O caçula de Jacó (Gn 35:18)", text: "O décimo segundo filho, único nascido em Canaã. Morrendo no parto, Raquel chamou-o Benoni, \"filho da minha dor\"; mas o pai lhe deu o nome de Benjamim, \"filho da destra\" (Gn 35:18). Amado por Jacó como último elo de Raquel, tornou-se a chave da provação dos irmãos no Egito (Gn 42-45). Jacó o profetizou como \"lobo que despedaça\" (Gn 49:27)." },
  manasses: { title: "Manassés", subtitle: "Primogênito de José, nascido no Egito (Gn 41:51)", text: "Primeiro filho que José teve no Egito, de Asenate: \"Deus me fez esquecer de todo o meu trabalho, e de toda a casa de meu pai\" — daí Manassés, \"o que faz esquecer\" (Gn 41:51). Jacó o adotou como seu, ao lado de Rúben e Simeão (Gn 48:5); mas, sendo o mais velho, recebeu do avô a mão esquerda, cedendo a bênção maior ao irmão menor (Gn 48:14)." },
  josue: { title: "Josué, filho de Num", subtitle: "O servo de Moisés que introduz Israel na terra (Js 1:1)", text: "Da tribo de Efraim, foi o \"moço\" que servia a Moisés e um dos dois espias que creram na promessa (Nm 14:6-9). Moisés lhe mudou o nome de Oséias para Josué — \"o Senhor é salvação\" — e sobre ele pôs as mãos, cheio do Espírito de sabedoria (Nm 27:18; Dt 34:9). A ele Deus repetiu: \"Esforça-te e tem bom ânimo... o Senhor teu Deus é contigo\" (Js 1:9). Atravessou o Jordão, tomou a terra e a repartiu, e no fim desafiou o povo: \"eu e a minha casa serviremos ao Senhor\" (Js 24:15). Prefigura Jesus, que leva o povo ao verdadeiro descanso (Hb 4:8)." },
  calebe: { title: "Calebe, filho de Jefoné", subtitle: "O espia fiel, herdeiro de Hebrom (Js 14:6)", text: "O quenezeu que, com Josué, trouxe bom relato da terra e creu contra a incredulidade dos dez: \"subamos animosamente... porque bem poderemos com ela\" (Nm 13:30). Por seguir \"integralmente\" ao Senhor, foi dos únicos daquela geração a entrar (Nm 14:24). Aos 85 anos, com a mesma fé de 45 anos antes, reivindicou o monte dos anaquins: \"dá-me este monte de que o Senhor falou\" (Js 14:12), e tomou Hebrom. Modelo de quem persevera na promessa até vê-la cumprida." },
  raabe: { title: "Raabe", subtitle: "A meretriz de Jericó que creu (Js 2:1)", text: "Prostituta de Jericó que escondeu os dois espias e confessou a fé que já corria em seu coração: \"o Senhor vosso Deus é Deus em cima nos céus e embaixo na terra\" (Js 2:11). Pediu misericórdia e a recebeu: o cordão de escarlata à janela salvou toda a sua casa quando os muros caíram (Js 6:22-25). A gentia redimida entrou em Israel, tornou-se mãe de Boaz e antepassada de Davi e de Cristo (Mt 1:5); Hebreus e Tiago a louvam pela fé viva e obediente (Hb 11:31; Tg 2:25)." },
  eleazar: { title: "Eleazar, filho de Arão", subtitle: "O sumo sacerdote que repartiu a terra (Js 14:1)", text: "Terceiro filho de Arão, sucedeu-lhe no sumo sacerdócio quando Deus revestiu Eleazar com as vestes no monte Hor (Nm 20:26-28). Ao lado de Josué, lançou as sortes \"perante o Senhor\" para dividir a herança entre as tribos (Js 14:1; 19:51) — o sacerdote e o capitão juntos, palavra e espada a serviço da promessa. Morreu ao fim do livro e foi sepultado no outeiro de Finéias, seu filho, em Efraim (Js 24:33)." },
  aca: { title: "Acã, filho de Carmi", subtitle: "O que tomou do anátema em Jericó (Js 7:1)", text: "Da tribo de Judá, transgrediu o interdito de Jericó: cobiçou e escondeu \"uma boa capa babilônica, e duzentos siclos de prata, e uma cunha de ouro\" debaixo da sua tenda (Js 7:21). Por isso Israel foi ferido diante de Ai, pois \"pecou Israel\" na pessoa de um só (Js 7:11). Descoberto pela sorte, confessou; foi apedrejado no vale de Acor — \"vale da perturbação\" —, sério aviso de que o pecado escondido de um contamina todo o povo (Js 7:24-26)." },
  fineias: { title: "Finéias, filho de Eleazar", subtitle: "O sacerdote zeloso, mediador da paz (Js 22:13)", text: "Neto de Arão, ficou conhecido pelo zelo em Baal-Peor, que estancou a praga e lhe valeu \"o pacto de um sacerdócio perpétuo\" (Nm 25:11-13). Em Josué 22 é enviado às tribos de além-Jordão para apurar o altar que haviam erguido; ouvindo que era altar de testemunho, e não de rebeldia, alegrou-se e evitou a guerra entre irmãos: \"hoje sabemos que o Senhor está no meio de nós\" (Js 22:31). Homem de zelo e de discernimento para a paz." },
  acsa: { title: "Acsa, filha de Calebe", subtitle: "A que pediu as fontes de água (Js 15:16)", text: "Dada por esposa a Otniel, que tomou Quiriate-Sefer, pediu ousadamente ao pai mais do que o campo do Neguebe: \"dá-me também fontes de águas\" — e Calebe lhe deu as fontes superiores e as inferiores (Js 15:19). Sabendo que a terra seca precisa de água viva, buscou a bênção completa; imagem de quem não se contenta com a herança pela metade, mas pede as fontes que a fazem frutificar." },
  otniel: { title: "Otniel, filho de Quenaz", subtitle: "O que tomou Quiriate-Sefer, primeiro juiz (Js 15:17)", text: "Parente de Calebe, conquistou Debir (Quiriate-Sefer) e por isso recebeu Acsa por mulher (Js 15:16-17). Mais tarde, quando Israel serviu a um rei da Mesopotâmia, \"o Senhor suscitou um libertador... a Otniel\", sobre quem veio o Espírito do Senhor, e a terra teve quarenta anos de descanso (Jz 3:9-11) — o primeiro dos juízes de Israel." },
  balaao: { title: "Balaão, filho de Beor", subtitle: "O adivinho que quis amaldiçoar Israel (Js 13:22)", text: "Adivinho de Petor, junto ao Eufrates, contratado por Balaque para amaldiçoar Israel — mas Deus lhe torceu a boca em bênção (Nm 22-24). Amou \"o prêmio da injustiça\" (2Pe 2:15) e ensinou Balaque a seduzir o povo em Baal-Peor. Josué registra o seu fim: foi morto à espada entre os reis de Midiã (Js 13:22), lembrança de que nem toda ciência do oculto livra o coração cobiçoso do juízo." },
  balaque: { title: "Balaque, filho de Zipor", subtitle: "O rei de Moabe que temeu Israel (Js 24:9)", text: "Rei de Moabe que, aterrorizado com a multidão que saíra do Egito, mandou chamar Balaão para amaldiçoar Israel (Nm 22:2-6). Na aliança de Siquém, Josué recorda o episódio como prova do cuidado de Deus: \"levantou-se Balaque... e chamou a Balaão para que vos amaldiçoasse; porém eu não quis ouvir a Balaão... e livrei-vos da sua mão\" (Js 24:9-10)." },
  tera: { title: "Terá", subtitle: "O pai de Abraão, além do Rio (Js 24:2)", text: "Na aliança de Siquém, Josué recua até a raiz de tudo: \"Além do rio habitaram antigamente vossos pais, Terá, pai de Abraão e de Naor, e serviram a outros deuses\" (Js 24:2). Terá, idólatra da Mesopotâmia, é o retrato da origem de onde a graça arrancou Israel — a eleição de Abraão não brotou de mérito, mas do puro chamado do Senhor que \"tomou\" o patriarca de além do Eufrates (Js 24:3)." },
  "maala": { title: "Maalá", subtitle: "Filha de Zelofeade, diante de Josué na partilha da terra (Js 17:3-4)", text: "A primeira das cinco irmãs de Manassés — \"Maalá, Noa, Hogla, Milca e Tirza\" (Js 17:3) —, que uma geração antes haviam obtido de Moisés, no deserto, o direito de herdar (Nm 27:1-11). Chegada a partilha de Canaã, vieram cobrar a palavra dada, apresentando-se \"diante de Eleazar, o sacerdote, e diante de Josué, filho de Num, e diante dos príncipes\" e dizendo: \"O Senhor ordenou a Moisés que se nos desse herança no meio de nossos irmãos\" (Js 17:4). Não alegaram mérito, e sim a promessa; e foram atendidas: \"conforme a ordem do Senhor, lhes deu herança no meio dos irmãos de seu pai\" (Js 17:4). Por elas Manassés contou dez quinhões além de Gileade e Basã, porque \"as filhas de Manassés receberam herança entre os filhos dele\" (Js 17:5-6). O que Deus promete numa geração, cumpre na seguinte." },
  "adoni": { title: "Adoni-Zedeque", subtitle: "Rei de Jerusalém, cabeça dos cinco reis amorreus (Js 10:1)", text: "\"Adoni-Zedeque, rei de Jerusalém\" (Js 10:1) — o nome traz dentro de si a palavra justiça, num eco distante de Melquisedeque, mas o homem foi o primeiro a coligar reis contra o povo de Deus. Da notícia de que Ai caíra e de que Gibeom fizera paz com Israel nasceu o pânico: \"Temeram muito, porque Gibeom era uma cidade grande\" (Js 10:2). Então mandou recado a Hebrom, Jarmute, Laquis e Eglom: \"Subi a mim, e ajudai-me, e firamos a Gibeom\" (Js 10:4). Os cinco sitiaram Gibeom e foram desbaratados no dia em que \"o Senhor lançou sobre eles, do céu, grandes pedras\" e o sol parou (Js 10:11-13). Achados na cova de Maquedá, foram trazidos a Josué, que disse aos capitães: \"Chegai, ponde os vossos pés sobre os pescoços destes reis\" (Js 10:24). Enforcados em cinco madeiros, foram lançados de volta à cova, com grandes pedras à boca dela (Js 10:26-27)." },
};
