// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de PERSONAGEM (por `id`) das cenas de judges. Vem por import() junto com
// o roteiro do livro: quem lê Rute não baixa os nomes de Crônicas.
import type { StageInfo } from "@/lib/rpgStageInfo";

const HOSTE_DE_MIDIA: StageInfo = {
  title: "A hoste de Midiã, Amaleque e os filhos do oriente",
  subtitle: "Juízes 6-8 • os que subiam como gafanhotos contra a seara",
  text: "São os saqueadores do oriente que por sete anos subiam contra Israel bem no tempo da colheita: \"acampavam-se contra eles, e destruíam os frutos da terra... e não deixavam mantimento algum em Israel, nem ovelhas, nem bois, nem jumentos\" (Jz 6:3-4). Vinham \"com os seus gados e as suas tendas, como gafanhotos, em grande multidão\", e os seus camelos eram sem conta (Jz 6:5). Contra esse mar de gente Deus não pôs exército, mas trezentos homens com buzinas, cântaros e tochas — \"e o Senhor tornou a espada de um contra o outro, e isto em todo o arraial\" (Jz 7:22). A multidão que parecia invencível debandou por dentro, para que Israel não pudesse dizer \"a minha mão me livrou\" (Jz 7:2).",
};
const CORTE_DE_HAZOR: StageInfo = {
  title: "A corte de Jabim, rei de Canaã, em Hazor",
  subtitle: "Juízes 4 • os oficiais do trono que oprimiu vinte anos",
  text: "São os homens do palácio do rei que reinava em Hazor — a cidade que fora \"a cabeça de todos estes reinos\" (Js 11:10) e que Israel não guardou destruída. Dali torna a pesar o jugo: \"o Senhor os vendeu na mão de Jabim, rei de Canaã, que reinava em Hazor; e Sísera era o capitão do seu exército\" (Jz 4:2), e por vinte anos \"oprimia violentamente os filhos de Israel\" (Jz 4:3). Confiavam no ferro dos seus carros e no trono do norte; mas do ribeiro de Quisom voltou a notícia de que \"nem um só ficou\" (Jz 4:16), e a mão de Israel foi endurecendo sobre Jabim \"até que exterminaram a Jabim\" (Jz 4:24).",
};
const CARROS_DE_FERRO: StageInfo = {
  title: "Os novecentos carros de ferro de Sísera",
  subtitle: "Juízes 4 • a hoste que desceu de Harosete ao ribeiro de Quisom",
  text: "São os homens de Harosete dos Gentios convocados assim que anunciaram a Sísera que Baraque subira ao monte Tabor: \"ajuntou Sísera todos os seus carros, novecentos carros de ferro, e todo o povo que estava com ele\" (Jz 4:12-13). O carro de ferro era exatamente o que fizera a conquista parar — \"não expulsou os moradores do vale, porquanto tinham carros de ferro\" (Jz 1:19; cf. Js 17:16). Mas foi o próprio Senhor quem os atraiu ao leito do Quisom (Jz 4:7): ali a torrente antiga os arrastou e \"os cascos dos cavalos se despedaçaram\" (Jz 5:21-22). A arma em que o inimigo confia é a armadilha na mão de Deus (Sl 20:7).",
};

export const CHARS: Record<string, StageInfo> = {
  simeao: { title: "Simeão", subtitle: "2º filho de Lia (Gn 29:33)", text: "Segundo filho de Lia — \"Porquanto o Senhor ouviu que eu era desprezada\" (Gn 29:33). Com o irmão Levi, tomou da espada e vingou a desonra de Diná, matando os homens de Siquém (Gn 34:25). Por isso a bênção de Jacó pesou-lhe a mão: \"suas espadas são instrumentos de violência... eu os dividirei em Jacó, e os espalharei em Israel\" (Gn 49:5-7)." },
  juda: { title: "Judá", subtitle: "4º filho de Lia (Gn 29:35)", text: "Quarto filho de Lia: \"Esta vez louvarei ao Senhor\" — e o chamou Judá, \"louvor\" (Gn 29:35). Propôs vender José aos ismaelitas (Gn 37:26-27), mas depois ofereceu-se como fiador de Benjamim diante do irmão que não reconhecia (Gn 44:33). Sobre ele repousou a promessa maior: \"O cetro não se arredará de Judá... até que venha Siló\" (Gn 49:10) — a linhagem do Messias." },
  issacar: { title: "Issacar", subtitle: "5º filho de Lia (Gn 30:17-18)", text: "Quinto filho de Lia, dado quando \"ouviu Deus a Lia\": \"Deus me tem dado o meu galardão\" (Gn 30:17-18). Na bênção de Jacó é retratado como \"jumento de fortes ossos, deitado entre dois fardos\", que viu que \"o descanso era bom, e que a terra era deliciosa\", e abaixou o ombro ao trabalho (Gn 49:14-15)." },
  zebulom: { title: "Zebulom", subtitle: "6º filho de Lia (Gn 30:19-20)", text: "Sexto e último filho de Lia: \"Deus me deu uma boa dádiva... desta vez morará o meu marido comigo\" (Gn 30:20). Jacó lhe profetizou vocação de mar e comércio: \"Zebulom habitará no porto dos mares, e será como porto dos navios, e o seu termo será para Sidom\" (Gn 49:13)." },
  naftali: { title: "Naftali", subtitle: "2º filho de Bila (Gn 30:7-8)", text: "Segundo filho de Bila: nasceu no auge da rivalidade das irmãs — \"Com grandes lutas tenho lutado com minha irmã; também venci\" (Gn 30:8). Jacó o abençoou com imagem de liberdade e beleza: \"Naftali é uma gazela solta; ele dá palavras formosas\" (Gn 49:21)." },
  aser: { title: "Aser", subtitle: "2º filho de Zilpa (Gn 30:12-13)", text: "Segundo filho de Zilpa: \"Para minha ventura; porque as filhas me terão por bem-aventurada\" — Aser significa \"feliz, bem-aventurado\" (Gn 30:13). Jacó lhe prometeu fartura: \"De Aser, o seu pão será gordo, e ele dará delícias reais\" (Gn 49:20)." },
  manasses: { title: "Manassés", subtitle: "Primogênito de José, nascido no Egito (Gn 41:51)", text: "Primeiro filho que José teve no Egito, de Asenate: \"Deus me fez esquecer de todo o meu trabalho, e de toda a casa de meu pai\" — daí Manassés, \"o que faz esquecer\" (Gn 41:51). Jacó o adotou como seu, ao lado de Rúben e Simeão (Gn 48:5); mas, sendo o mais velho, recebeu do avô a mão esquerda, cedendo a bênção maior ao irmão menor (Gn 48:14)." },
  josue: { title: "Josué, filho de Num", subtitle: "O servo de Moisés que introduz Israel na terra (Js 1:1)", text: "Da tribo de Efraim, foi o \"moço\" que servia a Moisés e um dos dois espias que creram na promessa (Nm 14:6-9). Moisés lhe mudou o nome de Oséias para Josué — \"o Senhor é salvação\" — e sobre ele pôs as mãos, cheio do Espírito de sabedoria (Nm 27:18; Dt 34:9). A ele Deus repetiu: \"Esforça-te e tem bom ânimo... o Senhor teu Deus é contigo\" (Js 1:9). Atravessou o Jordão, tomou a terra e a repartiu, e no fim desafiou o povo: \"eu e a minha casa serviremos ao Senhor\" (Js 24:15). Prefigura Jesus, que leva o povo ao verdadeiro descanso (Hb 4:8)." },
  calebe: { title: "Calebe, filho de Jefoné", subtitle: "O espia fiel, herdeiro de Hebrom (Js 14:6)", text: "O quenezeu que, com Josué, trouxe bom relato da terra e creu contra a incredulidade dos dez: \"subamos animosamente... porque bem poderemos com ela\" (Nm 13:30). Por seguir \"integralmente\" ao Senhor, foi dos únicos daquela geração a entrar (Nm 14:24). Aos 85 anos, com a mesma fé de 45 anos antes, reivindicou o monte dos anaquins: \"dá-me este monte de que o Senhor falou\" (Js 14:12), e tomou Hebrom. Modelo de quem persevera na promessa até vê-la cumprida." },
  fineias: { title: "Finéias, filho de Eleazar", subtitle: "O sacerdote zeloso, mediador da paz (Js 22:13)", text: "Neto de Arão, ficou conhecido pelo zelo em Baal-Peor, que estancou a praga e lhe valeu \"o pacto de um sacerdócio perpétuo\" (Nm 25:11-13). Em Josué 22 é enviado às tribos de além-Jordão para apurar o altar que haviam erguido; ouvindo que era altar de testemunho, e não de rebeldia, alegrou-se e evitou a guerra entre irmãos: \"hoje sabemos que o Senhor está no meio de nós\" (Js 22:31). Homem de zelo e de discernimento para a paz." },
  acsa: { title: "Acsa, filha de Calebe", subtitle: "A que pediu as fontes de água (Js 15:16)", text: "Dada por esposa a Otniel, que tomou Quiriate-Sefer, pediu ousadamente ao pai mais do que o campo do Neguebe: \"dá-me também fontes de águas\" — e Calebe lhe deu as fontes superiores e as inferiores (Js 15:19). Sabendo que a terra seca precisa de água viva, buscou a bênção completa; imagem de quem não se contenta com a herança pela metade, mas pede as fontes que a fazem frutificar." },
  otniel: { title: "Otniel, filho de Quenaz", subtitle: "O que tomou Quiriate-Sefer, primeiro juiz (Js 15:17)", text: "Parente de Calebe, conquistou Debir (Quiriate-Sefer) e por isso recebeu Acsa por mulher (Js 15:16-17). Mais tarde, quando Israel serviu a um rei da Mesopotâmia, \"o Senhor suscitou um libertador... a Otniel\", sobre quem veio o Espírito do Senhor, e a terra teve quarenta anos de descanso (Jz 3:9-11) — o primeiro dos juízes de Israel." },
  balaque: { title: "Balaque, filho de Zipor", subtitle: "O rei de Moabe que temeu Israel (Js 24:9)", text: "Rei de Moabe que, aterrorizado com a multidão que saíra do Egito, mandou chamar Balaão para amaldiçoar Israel (Nm 22:2-6). Na aliança de Siquém, Josué recorda o episódio como prova do cuidado de Deus: \"levantou-se Balaque... e chamou a Balaão para que vos amaldiçoasse; porém eu não quis ouvir a Balaão... e livrei-vos da sua mão\" (Js 24:9-10)." },
  "debora-juiza": { title: "Débora", subtitle: "Profetisa e juíza de Israel (Jz 4:4)", text: "\"Débora, mulher profetisa, mulher de Lapidote, julgava a Israel naquele tempo\" — e o povo subia até ela, que se assentava debaixo da sua palmeira entre Ramá e Betel (Jz 4:4-5). Chamou Baraque à guerra contra Sísera e foi com ele quando ele não quis ir só; por isso a honra da vitória coube a uma mulher (Jz 4:9). No seu cântico chama a si mesma \"mãe em Israel\" (Jz 5:7) — em tempo de covardia, uma mulher creu na palavra do Senhor e conduziu a nação." },
  baraque: { title: "Baraque, filho de Abinoão", subtitle: "O capitão convocado por Débora (Jz 4:6)", text: "De Quedes-Naftali, foi chamado a levar dez mil homens ao monte Tabor contra os novecentos carros de ferro de Sísera. Hesitou: \"Se fores comigo, irei; porém, se não fores comigo, não irei\" (Jz 4:8). Desceu do Tabor e o Senhor derrotou Sísera diante dele. Apesar da fé vacilante, Hebreus o conta entre os que \"pela fé venceram reinos\" (Hb 11:32-33)." },
  jael: { title: "Jael, mulher de Héber", subtitle: "A que feriu Sísera na tenda (Jz 4:17)", text: "Queneia, acolheu na sua tenda o general fugitivo, deu-lhe leite em vez da água que ele pedira e o cobriu; e enquanto ele dormia exausto, tomou a estaca da tenda e o martelo e o traspassou (Jz 4:18-21). O cântico a proclama \"bendita sobre as mulheres\" (Jz 5:24). Numa tenda, com as ferramentas domésticas de uma mulher, caiu o poder que oprimira Israel vinte anos." },
  sisera: { title: "Sísera", subtitle: "O capitão do exército de Jabim (Jz 4:2)", text: "Chefe militar de Jabim, rei de Canaã, tinha novecentos carros de ferro e oprimira Israel violentamente por vinte anos (Jz 4:2-3). No Quisom, \"o Senhor derrotou a Sísera\", e ele desceu do carro e fugiu a pé, para morrer pela mão de uma mulher (Jz 4:15-21). O cântico o mostra pela última vez pelos olhos da mãe, à janela, esperando o filho que não volta (Jz 5:28)." },
  eude: { title: "Eúde, filho de Gera", subtitle: "O juiz canhoto, libertador de Moabe (Jz 3:15)", text: "Benjamita canhoto, cingiu à coxa direita uma espada de dois gumes — onde ninguém revistaria — e a levou à câmara de verão de Eglom, rei de Moabe, dizendo: \"Tenho uma palavra secreta para ti\" (Jz 3:16-19). Morto o opressor, tocou a buzina em Efraim, tomou os vaus do Jordão, e a terra sossegou oitenta anos (Jz 3:27-30) — o maior descanso do livro." },
  sangar: { title: "Sangar, filho de Anate", subtitle: "O que feriu seiscentos com uma aguilhada (Jz 3:31)", text: "Um só versículo o guarda: \"feriu seiscentos homens dos filisteus com uma aguilhada de bois; e também ele libertou a Israel\" (Jz 3:31). Sem exército e sem espada, com a ferramenta do lavrador, tornou-se libertador — e no cântico de Débora os seus dias são lembrados como tempo em que \"cessaram os caminhos\" (Jz 5:6). Deus salva por quem quer e com o que houver na mão." },
  gideao: { title: "Gideão (Jerubaal)", subtitle: "O juiz dos trezentos (Jz 6:11)", text: "O anjo do Senhor o achou malhando trigo escondido no lagar, por causa dos midianitas, e o saudou: \"O Senhor é contigo, homem valoroso\" (Jz 6:12). Ele se dizia o menor da casa mais pobre de Manassés, pediu sinais e o velo — e ainda assim derrubou o altar de Baal (por isso Jerubaal) e desceu com trezentos homens, trombetas, cântaros e tochas contra um arraial \"como a areia\" (Jz 7:12,20). Recusou a coroa — \"o Senhor sobre vós dominará\" (Jz 8:23) —, mas o éfode de ouro que fez virou laço para a sua casa." },
  jotao: { title: "Jotão, filho de Jerubaal", subtitle: "O caçula que escapou e falou a parábola (Jz 9:5)", text: "O menor dos setenta filhos de Gideão, escondeu-se e sobreviveu à matança sobre a pedra em Ofra (Jz 9:5). Do alto do monte Gerizim bradou a primeira parábola da Escritura: as árvores que buscam um rei e acabam sob o espinheiro, de quem sai fogo que devora os cedros do Líbano (Jz 9:8-15). A maldição que pronunciou cumpriu-se três anos depois, sobre Abimeleque e sobre Siquém (Jz 9:20,57)." },
  "abimeleque-jz": { title: "Abimeleque, filho de Gideão", subtitle: "O que se fez rei em Siquém (Jz 9:1)", text: "Filho da concubina de Gideão em Siquém, comprou homens ociosos com prata do templo de Baal-Berite e matou os setenta irmãos sobre uma pedra (Jz 9:4-5). Reinou três anos — o primeiro a usurpar a realeza em Israel — até que Deus enviou \"um mau espírito\" entre ele e Siquém (Jz 9:23). Queimou a torre de Siquém e morreu em Tebes, quando uma mulher lhe lançou do muro um pedaço de mó sobre a cabeça (Jz 9:53)." },
  jefte: { title: "Jefté, o gileadita", subtitle: "O rejeitado que se tornou chefe (Jz 11:1)", text: "\"Era filho de uma prostituta\" e foi expulso pelos irmãos da casa do pai; na terra de Tobe, homens vadios se ajuntaram a ele (Jz 11:1-3). Quando Amom veio à guerra, os mesmos anciãos que o lançaram fora foram buscá-lo — a pedra rejeitada virou cabeça. Argumentou com Amom pela história e pela justiça de Deus (Jz 11:27), venceu, mas fez um voto precipitado que lhe custou a filha única. Hebreus ainda o nomeia entre os homens de fé (Hb 11:32)." },
  "filha-jefte": { title: "A filha de Jefté", subtitle: "A única, que saiu com adufes (Jz 11:34)", text: "\"Ela era única; não tinha ele outro filho nem filha\" — e foi ela quem saiu a recebê-lo com adufes e com danças (Jz 11:34). Sabendo do voto do pai, não fugiu: \"faze de mim conforme o que prometeste\", pedindo só dois meses nos montes com as companheiras (Jz 11:36-37). A Escritura não lhe dá nome, mas guarda o seu costume em Israel, quatro dias por ano. Sua história é o retrato mais amargo do que custa jurar levianamente diante de Deus (Ec 5:2-5)." },
  manoa: { title: "Manoá", subtitle: "O pai de Sansão, de Zorá (Jz 13:2)", text: "Danita de Zorá, rogou ao Senhor que o varão de Deus voltasse para lhes ensinar o que fazer ao menino que havia de nascer (Jz 13:8). Perguntou o nome ao anjo e ouviu: \"por que perguntas assim pelo meu nome, visto que é maravilhoso?\" (Jz 13:18). Quando a chama subiu do altar com o mensageiro, caiu com o rosto em terra e disse à mulher: \"certamente morreremos, porquanto temos visto a Deus\" (Jz 13:22)." },
  "mulher-manoa": { title: "A mulher de Manoá", subtitle: "A estéril a quem o anjo apareceu (Jz 13:3)", text: "A Escritura não lhe dá o nome, mas foi a ela — e não ao marido — que o anjo do Senhor apareceu duas vezes, anunciando: \"tu és estéril, e nunca tens dado à luz; porém conceberás, e darás à luz um filho\" (Jz 13:3). Recebeu a lei do nazireado ainda no ventre. E foi a sua fé serena que sossegou o medo de Manoá: \"se o Senhor nos quisera matar, não aceitaria da nossa mão o holocausto\" (Jz 13:23)." },
  sansao: { title: "Sansão", subtitle: "O nazireu de Deus desde o ventre (Jz 13:5)", text: "Danita consagrado antes de nascer — \"navalha não subirá à sua cabeça... e ele começará a livrar a Israel da mão dos filisteus\" (Jz 13:5). O Espírito do Senhor o assaltava com força espantosa: despedaçou o leão, feriu mil com uma queixada, carregou as portas de Gaza. Mas a força que os inimigos não venceram, a paixão desatou: nos joelhos de Dalila perdeu os cabelos e, o que é pior, \"não sabia que já o Senhor se tinha retirado dele\" (Jz 16:20). Cego e moendo na prisão, orou uma última vez e derrubou a casa de Dagom — \"os que matou na sua morte foram mais do que os que matara na sua vida\" (Jz 16:30); e Hebreus o conta entre os que pela fé \"das fraquezas tiraram forças\" (Hb 11:32-34)." },
  dalila: { title: "Dalila", subtitle: "A mulher do vale de Soreque (Jz 16:4)", text: "Amada por Sansão e comprada pelos príncipes dos filisteus, cada um por mil e cem moedas de prata, para descobrir em que estava a sua grande força (Jz 16:5). Três vezes ele mentiu e três vezes ela o entregou; \"e sucedeu que, importunando-o ela todos os dias com as suas palavras... a sua alma se angustiou até à morte\" (Jz 16:16). Ela é o retrato da sedução que arranca o segredo do coração e o vende — o inimigo que dorme dentro de casa." },
  mica: { title: "Mica, o efraimita", subtitle: "O da imagem de escultura e do levita alugado (Jz 17:1)", text: "Devolveu à mãe as mil e cem moedas de prata que lhe furtara, e dela saiu o dinheiro para o ourives fazer uma imagem de escultura e de fundição (Jz 17:2-4). Fez uma casa de deuses, um éfode, terafins, consagrou um filho por sacerdote e depois alugou um levita por dez peças de prata por ano, dizendo: \"agora sei que o Senhor me fará bem\" (Jz 17:13). É a religião virada superstição doméstica — culto ao Senhor pelo nome, com ídolos e sacerdote comprado; do seu santuário saiu a idolatria de toda a tribo de Dã (Jz 18:30-31)." },
  profeta: { title: "O profeta enviado antes de Gideão", subtitle: "O varão anônimo do SENHOR a Israel (Jz 6:8)", text: "Ao clamor de Israel debaixo de Midiã, Deus responde primeiro com uma palavra, e não com um libertador: \"o Senhor enviou um homem, um profeta, aos filhos de Israel\" (Jz 6:8). A Escritura não lhe dá o nome; dá-lhe a mensagem, e ela começa pela memória do livramento: \"Do Egito vos fiz subir, e vos tirei da casa da servidão... e vos livrei da mão dos egípcios, e da mão de todos os que vos oprimiam\" (Jz 6:8-9). Depois vem a acusação, que é o coração dos três versículos: \"Eu sou o Senhor vosso Deus; não temais os deuses dos amorreus, em cuja terra habitais; mas não destes ouvidos à minha voz\" (Jz 6:10). Antes de mandar o juiz, Deus manda o diagnóstico — não há livramento verdadeiro sem que o povo saiba do que precisa ser livrado (cf. Ne 9:9-10)." },
  "midianita-sonho": { title: "O midianita que sonhou com o pão de cevada", subtitle: "O sonho ouvido por Gideão na noite (Jz 7:13)", text: "É o soldado do arraial de Midiã a quem Gideão, descido às sentinelas, ouve contar ao companheiro: \"Eis que sonhei um sonho; e eis que um pão de cevada torrado rodava pelo arraial dos midianitas, e chegava até à tenda, e a feriu, e caiu, e a transtornou de cima para baixo, e ficou caída\" (Jz 7:13). O pão de cevada é o pão dos pobres — a comida do Israel esfomeado que se escondia nas covas dos montes. Deus dá o sonho dentro do acampamento inimigo e o faz contar justamente na hora em que o seu servo medroso passa por ali: até os sonhos dos pagãos servem ao propósito do Senhor e à fé de um homem (cf. Gn 41:25; Dn 2:28)." },
  companheiro: { title: "O companheiro que interpretou o sonho", subtitle: "\"Não é isto senão a espada de Gideão\" (Jz 7:14)", text: "O outro midianita responde sem hesitar: \"Isto não é outra coisa senão a espada de Gideão, filho de Joás, varão israelita; Deus pôs na sua mão a Midiã e a todo este arraial\" (Jz 7:14). O inimigo confessa a derrota antes de a batalha começar, como Raabe confessara em Jericó: \"todos os moradores da terra estão desmaiados diante de vós\" (Js 2:9). Gideão ouve, adora ali mesmo no escuro — antes de qualquer vitória — e volta ao arraial dizendo: \"Levantai-vos, porque o Senhor tem dado o arraial de Midiã nas vossas mãos\" (Jz 7:15). Deus condescende com o medo do seu servo e lhe dá a certeza pela boca do adversário." },
  "sentinela-midia": { title: "A sentinela do arraial de Midiã", subtitle: "O extremo da guarda, na noite da descida (Jz 7:11)", text: "É a guarda do acampamento até cujo extremo Gideão e o moço Purá descem, na noite em que o Senhor lhe disse: \"Levanta-te, e desce ao arraial, porque o tenho dado na tua mão\" (Jz 7:9-11). Vigia uma hoste que jazia no vale \"como gafanhotos em multidão\", com camelos \"como a areia que há na praia do mar, em multidão\" (Jz 7:12). Guardam tudo, menos o que importa: naquela mesma noite o temor já corria dentro das tendas, e o arraial cairia sem que Israel desembainhasse a espada (Jz 7:22). \"Se o Senhor não guardar a cidade, em vão vigia a sentinela\" (Sl 127:1)." },
  midianita1: HOSTE_DE_MIDIA,
  midianita2: HOSTE_DE_MIDIA,
  midianita3: HOSTE_DE_MIDIA,
  midianita4: HOSTE_DE_MIDIA,
  "oficial-hazor1": CORTE_DE_HAZOR,
  "oficial-hazor2": CORTE_DE_HAZOR,
  "carro-ferro1": CARROS_DE_FERRO,
  "carro-ferro2": CARROS_DE_FERRO,
  "carro-ferro3": CARROS_DE_FERRO,
  jonatas: { title: "Jônatas", subtitle: "Filho de Saul, o amigo de Davi (1Sm 13–31)", text: "Guerreiro de fé ousada: com o pajem apenas, subiu de gatinhas pelos penhascos de Bozez e Sené contra a guarnição filisteia, dizendo \"para com o Senhor nenhum impedimento há de livrar com muitos ou com poucos\" (1Sm 14:6). Provou o mel na ponta da vara sem saber do juramento do pai, e o povo o resgatou da morte (1Sm 14:27,45). Amou Davi \"como à sua própria alma\", despiu-se da própria capa, espada, arco e cinto para vesti-lo (1Sm 18:1-4) e fez com ele aliança diante do SENHOR — sabendo que estava entregando o trono que lhe caberia: \"tu reinarás sobre Israel, e eu serei o segundo depois de ti\" (1Sm 23:17). Defendeu-o do pai arriscando a própria vida sob a lança (1Sm 19:4; 20:33). Morreu ao lado de Saul em Gilboa, e Davi o pranteou: \"a tua amizade me era mais maravilhosa do que o amor de mulheres\" (2Sm 1:26)." },
  "adoni-bezeque": { title: "Adoni-Bezeque", subtitle: "O rei cananeu achado em Bezeque (Jz 1:5-7)", text: "Rei cananeu que Judá encontrou ao subir para a conquista: \"E acharam Adoni-Bezeque em Bezeque, e pelejaram contra ele\" (Jz 1:5). Fugiu, foi preso, e \"cortaram-lhe os dedos polegares das mãos e dos pés\" (Jz 1:6) — exatamente a mutilação que ele impusera a outros. E foi da sua própria boca que saiu a sentença sobre a sua vida: \"Setenta reis, com os dedos polegares das mãos e dos pés cortados, apanhavam as migalhas debaixo da minha mesa; assim como eu fiz, assim Deus me pagou\" (Jz 1:7). É a primeira voz do livro dos Juízes a confessar a justiça retributiva de Deus — e vem de um pagão, não de Israel. \"E levaram-no a Jerusalém, e morreu ali\" (Jz 1:7)." },
  "joas": { title: "Joás", subtitle: "O abiezrita de Ofra, pai de Gideão (Jz 6:11)", text: "Dono do carvalho de Ofra e do altar de Baal que o próprio filho derrubou de noite, por temer a casa do pai e os homens da cidade (Jz 6:11,25-27). Ao amanhecer, a cidade cercou-lhe a porta: \"Tira para fora a teu filho; para que morra; pois derribou o altar de Baal\" (Jz 6:30). O pai que sustentava o altar do ídolo defendeu o filho com o argumento que desmonta toda idolatria: \"Contendereis vós por Baal? Livrá-lo-eis vós? Qualquer que por ele contender ainda esta manhã será morto; se é deus, por si mesmo contenda\" (Jz 6:31). Um deus que precisa de advogados não é deus. Daquele dia veio o segundo nome do filho: \"lhe chamaram Jerubaal, dizendo: Baal contenda contra ele, pois derrubou o seu altar\" (Jz 6:32)." },
  "zeba": { title: "Zeba", subtitle: "Um dos dois reis dos midianitas presos por Gideão (Jz 8:5-21)", text: "\"Zeba e Salmuna, reis dos midianitas\" (Jz 8:5) escaparam da derrota noturna e fugiram até Carcor com quinze mil homens, tudo o que restava do exército do oriente (Jz 8:10). Foi por causa deles que Sucote e Penuel negaram pão aos trezentos exaustos, zombando: \"Estão já, Zeba e Salmuna, em tua mão, para que demos pão ao teu exército?\" (Jz 8:6). Preso enfim, confessou sem rodeios a matança dos irmãos de Gideão no Tabor: \"Como és tu, assim eram eles; cada um parecia filho de rei\" (Jz 8:18). E quando Jeter, o primogênito menino, não teve coragem de puxar da espada, foi o próprio cativo quem exigiu morte de guerreiro: \"Levanta-te, e acomete-nos; porque, qual o homem, tal a sua valentia\" (Jz 8:21). Gideão o matou, e tomou os ornamentos que estavam nos pescoços dos seus camelos." },
  "gaal": { title: "Gaal", subtitle: "Filho de Ebede, o agitador de Siquém (Jz 9:26)", text: "Forasteiro que chegou a Siquém no tempo da vindima com seus irmãos, e de quem se diz que \"os cidadãos de Siquém confiaram nele\" (Jz 9:26). Bebido o vinho da festa na casa do seu deus, levantou a voz contra o rei que a própria cidade fizera: \"Quem é Abimeleque, e quem é Siquém, para que o sirvamos?\" (Jz 9:28), e gabou-se: \"Ah! se este povo estivera na minha mão, eu expulsaria a Abimeleque\" (Jz 9:29). Zebul, o maioral da cidade, o denunciou às escondidas; e na madrugada seguinte, vendo tropas descerem os montes, Gaal ouviu do mesmo Zebul o escárnio: \"Onde está agora a tua boca, com a qual dizias: Quem é Abimeleque, para que o sirvamos?\" (Jz 9:38). Saiu a pelejar, fugiu ferido e foi expulso (Jz 9:39-41). A sua bravata só apressou a ruína que a maldição de Jotão anunciara sobre Siquém (Jz 9:20)." },
  "zebul": { title: "Zebul", subtitle: "Maioral de Siquém, mordomo de Abimeleque (Jz 9:28,30)", text: "\"Zebul, o maioral da cidade\" (Jz 9:30), posto em Siquém por Abimeleque — e foi Gaal quem o apontou com desprezo: \"E não é Zebul o seu mordomo?\" (Jz 9:28). Ouvindo as palavras do sublevado, acendeu-se-lhe a ira e \"enviou astutamente mensageiros a Abimeleque\", avisando que \"eles estão sublevando esta cidade contra ti\" (Jz 9:31), e aconselhando a emboscada de noite e o golpe ao raiar do sol. Na manhã da armadilha, segurou Gaal na porta com uma mentira fria: \"As sombras dos montes vês como se fossem homens\" (Jz 9:36); e só quando já não havia recuo o empurrou para fora: \"Sai pois, peço-te, e peleja contra ele\" (Jz 9:38). \"E Zebul expulsou a Gaal e a seus irmãos, para que não pudessem habitar em Siquém\" (Jz 9:41). É a astúcia posta a serviço de um trono nascido do sangue de setenta irmãos." },
  "mae-sisera": { title: "A mãe de Sísera", subtitle: "A que esperou na janela o carro que não voltava (Jz 5:28)", text: "O cântico de Débora fecha com a cena mais cruel do livro, vista de dentro da casa do inimigo: \"A mãe de Sísera olhava pela janela, e exclamava pela grade: Por que tarda em vir o seu carro? Por que se demoram os ruídos dos seus carros?\" (Jz 5:28). As damas do palácio a consolam com a conta do despojo — \"Uma ou duas moças a cada homem?\" (Jz 5:30) —, e ela mesma repete a si a resposta que quer ouvir. Mas quem canta já sabe o que ela não sabe: o filho está morto numa tenda, com uma estaca cravada na fonte pela mão de outra mulher (Jz 4:21). A janela dela é o contraponto exato da tenda de Jael, e a espera vazia é o retrato de toda confiança posta na violência. Por isso o cântico salta dali direto para a oração final: \"Assim, ó Senhor, pereçam todos os teus inimigos! Porém os que te amam sejam como o sol quando sai na sua força\" (Jz 5:31)." },
  "mae-de-mica": { title: "A mãe de Mica", subtitle: "A que consagrou a prata e mandou fundir o ídolo (Jz 17:2-4)", text: "Mulher da montanha de Efraim cuja prata roubada abre o apêndice mais sombrio de Juízes. Confessado o furto pelo filho, ela desfez a maldição com uma bênção: \"Bendito do Senhor seja meu filho\" (Jz 17:2). E então, com toda a linguagem da piedade e nenhum temor da lei, dedicou o dinheiro ao mesmo Deus que proibira o que ela ia fazer: \"Inteiramente tenho dedicado este dinheiro da minha mão ao Senhor, para meu filho fazer uma imagem de escultura e uma de fundição\" (Jz 17:3). Das mil e cem moedas deu duzentas ao ourives, e a casa de Mica ganhou éfode, terafins e um sacerdote fabricado (Jz 17:4-5). É a idolatria com o nome do Senhor na boca — e dela sairá o santuário que corromperá a tribo de Dã (Jz 18:30-31). O comentário do narrador cai como sentença: \"cada um fazia o que parecia bem aos seus olhos\" (Jz 17:6)." },
};
