// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de PERSONAGEM (por `id`) das cenas de nehemiah. Vem por import() junto com
// o roteiro do livro: quem lê Rute não baixa os nomes de Crônicas.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHARS: Record<string, StageInfo> = {
  "zorobabel-filho-de-sealtiel": {
    title: "Zorobabel, filho de Sealtiel",
    subtitle: "O príncipe da casa de Davi que conduziu o regresso e reergueu o templo (Ed 2:2; 3:8; 5:2)",
    text: "É o primeiro nome da lista dos que subiram — \"Os quais vieram com Zorobabel, Jesua, Neemias…\" (Ed 2:2) —, e o nome, ironicamente, é babilônico: \"semente de Babilônia\", dado no cativeiro a um bisneto de Joaquim. Governa sem coroa: manda edificar o altar com Jesuá antes de qualquer parede (Ed 3:2), começa a obra no segundo mês do segundo ano (Ed 3:8), recusa a ajuda dos adversários com fundamento escrito — \"nós sozinhos a edificaremos ao Senhor Deus de Israel, como nos ordenou o rei Ciro\" (Ed 4:3) — e, dezesseis anos depois, levanta-se outra vez quando dois profetas falam (Ed 5:2). Ageu e Zacarias falaram diretamente a ele, e com palavras enormes: \"Não por força nem por violência, mas sim pelo meu Espírito, diz o Senhor dos Exércitos\" (Zc 4:6); \"As mãos de Zorobabel têm lançado os alicerces desta casa; também as suas mãos a acabarão\" (Zc 4:9); e, contra o desânimo de quem comparava a obra nova com a antiga, \"quem despreza o dia das coisas pequenas? Pois esses se alegrarão, vendo o prumo na mão de Zorobabel\" (Zc 4:10). Ageu foi mais longe: \"tomar-te-ei, ó Zorobabel, servo meu, filho de Sealtiel… e far-te-ei como um anel de selar\" (Ag 2:23) — o anel que Jeremias arrancara da mão de Deus na pessoa de Conias (Jr 22:24) é reposto no neto dele. É o último príncipe davídico a governar em Jerusalém, e Mateus escreve-lhe o nome na linha que leva a Cristo (Mt 1:12-13).",
  },
  "artaxerxes-rei-da-persia": {
    title: "Artaxerxes, rei da Pérsia",
    subtitle: "O rei que mandou impedir a obra — e o mesmo que depois enviaria Esdras e Neemias (Ed 4:21; 7:11-13)",
    text: "Recebe a carta de Samaria, manda revistar o arquivo e decide pelo que o arquivo diz: \"buscaram e acharam, que de tempos antigos aquela cidade se levantou contra os reis, e nela se têm feito rebelião e sedição\" (Ed 4:19). A acusação venceu porque era verdadeira quanto ao passado — Jerusalém tinha mesmo se rebelado contra Babilônia — e mentirosa quanto ao presente. Segue-se a ordem: \"Agora, pois, dai ordem para impedirdes aqueles homens, a fim de que não se edifique aquela cidade, até que eu dê uma ordem\" (Ed 4:21), com a advertência final \"E guardai-vos de serdes remissos nisto\" (Ed 4:22). Repare na fresta que ele deixa: \"ATÉ QUE EU DÊ UMA ORDEM\". Nem este rei fecha a porta de todo. E é o mesmo Artaxerxes que, anos depois, assina a carta que manda Esdras subir com prata, ouro e autoridade — \"Tudo quanto se ordenar, segundo o mandado do Deus do céu, prontamente se faça para a casa do Deus dos céus\" (Ed 7:23) —, e que dá a Neemias licença, madeira e escolta para reerguer os muros (Ne 2:7-8). O livro nomeia-o nas duas pontas: no decreto de Ciro e Dario \"e de Artaxerxes, rei da Pérsia\", conta-se o acabamento da casa (Ed 6:14).",
  },
  "esdras-o-escriba": {
    title: "Esdras, o sacerdote e escriba hábil na lei de Moisés",
    subtitle: "Ed 7–10 • Ne 8 — o homem que subiu de babilônia com um rolo na mão",
    text: "Filho de Seraías, o último sumo sacerdote de Jerusalém, morto por Nabucodonosor em Ribla (2Rs 25:18-21), Esdras é sacerdote de nascimento e escriba de ofício: \"Este Esdras subiu de babilônia; e era escriba hábil na lei de Moisés, que o SENHOR Deus de Israel tinha dado\" (Ed 7:6). Sobe no sétimo ano de Artaxerxes, cinquenta e oito anos depois de acabada a casa, e não traz pedreiro nenhum. O versículo que o define e que governa o livro é este: \"Porque Esdras tinha preparado o seu coração para buscar a lei do Senhor e para cumpri-la e para ensinar em Israel os seus estatutos e os seus juízos\" (Ed 7:10) — buscar, cumprir, ensinar, e nunca a terceira antes da segunda. Junto ao rio Aava atenta para o povo e descobre que não há ali um só filho de Levi (Ed 8:15); apregoa jejum em vez de pedir escolta, porque \"tive vergonha de pedir ao rei exército e cavaleiros para nos defenderem do inimigo pelo caminho\" (Ed 8:22); e atravessa o deserto com vinte toneladas de prata e ouro sem um soldado à frente. Quando lhe trazem a notícia dos casamentos estrangeiros, não legisla: rasga as vestes, arranca os cabelos da cabeça e da barba e senta-se atônito até o sacrifício da tarde (Ed 9:3-4), e a oração que faz de joelhos diz sempre NÓS, embora ele não fosse culpado de nada — e acaba sem pedir coisa alguma: \"eis que estamos diante de ti, na nossa culpa\" (Ed 9:15). Em Neemias, o mesmo homem aparece de pé sobre um púlpito de madeira, lendo a lei desde a alva até o meio-dia diante de homens, mulheres e todos os que podiam ouvir com entendimento (Ne 8:2-4). Deus não lhe fala uma única vez nestes quatro capítulos; o que o texto repete é a MÃO — \"segundo a boa mão do seu Deus sobre ele\" (Ed 7:9).",
  },
  "meremote-filho-de-urias": {
    title: "Meremote, filho do sacerdote Urias, por cuja mão se pesou tudo em Jerusalém",
    subtitle: "Ed 8:33 • Ne 3:4,21 — o homem que recebeu a prata e depois reparou dois trechos do muro",
    text: "\"E no quarto dia se pesou a prata, o ouro e os utensílios, na casa do nosso Deus, por mão de Meremote, filho do sacerdote Urias\" (Ed 8:33). É a ele que a caravana entrega o que carregou por quatro meses de deserto, e a conta bate: \"Tudo foi contado e pesado; e todo o peso foi registrado na mesma ocasião\" (Ed 8:34). Nada de arredondamento e nada de confiança no ar — números na chegada conferidos contra números da partida. O mesmo Meremote aparece em Neemias como um dos poucos homens a reparar DOIS trechos do muro, o da Porta do Peixe e o defronte da casa de Eliasibe (Ne 3:4,21). É o retrato do funcionário fiel: recebe o dinheiro dos outros, assina o peso e depois volta a trabalhar com as mãos.",
  },
  "neemias-filho-de-hacalias": {
    title: "Neemias, filho de Hacalias, copeiro do rei e governador de Judá",
    subtitle: "Ne 1–13 — o homem que rezou de olhos abertos no meio de uma audiência",
    text: "Nasceu em Susã, serviu vinho a Artaxerxes e nunca vira Jerusalém quando o irmão lhe trouxe a notícia: \"o muro de Jerusalém fendido e as suas portas queimadas a fogo\" (Ne 1:3). Chorou, jejuou quatro meses e, quando o rei lhe perguntou o que queria, fez a oração mais curta da Escritura sem fechar os olhos nem calar a conversa — \"E o rei me disse: Que me pedes agora? Então orei ao Deus dos céus\" (Ne 2:4). Chegado à cidade, ficou três dias calado, rondou as ruínas de noite sem dizer a ninguém, até onde \"não havia lugar por onde pudesse passar o animal em que estava montado\" (Ne 2:14), e só então falou. Não é sacerdote nem profeta: é administrador, e a sua teologia cabe numa frase que repete o livro inteiro — \"segundo a boa mão de Deus sobre mim\" (Ne 2:8). Governou doze anos sem cobrar o pão do governador, pôs cento e cinquenta homens à sua mesa cada dia à sua custa, recusou quatro convites para descer ao vale de Ono com a resposta que ficou — \"Faço uma grande obra, de modo que não poderei descer\" (Ne 6:3) —, e acabou o muro em cinquenta e dois dias. Sacudiu as abas da veste contra os usurários, mandou fechar as portas antes do sábado, contendeu com os nobres, arrancou os cabelos aos que tinham casado com asdoditas, e escreveu quatro vezes o mesmo pedido, que é a última palavra da história de Israel no Antigo Testamento: \"lembra-te de mim, Deus meu, para bem\" (Ne 13:31). Deus não lhe fala uma única vez nos treze capítulos.",
  },
  "hanani-irmao-de-neemias": {
    title: "Hanani, um dos irmãos de Neemias, que trouxe a notícia de Jerusalém e ficou a governá-la",
    subtitle: "Ne 1:2 • 7:2 — o mensageiro do primeiro versículo, encarregado da cidade no fim",
    text: "\"Que veio Hanani, um de meus irmãos, ele e alguns de Judá; e perguntei-lhes pelos judeus que escaparam, e que restaram do cativeiro, e acerca de Jerusalém\" (Ne 1:2). Ele é a causa de tudo: sem esta viagem — quatro meses de estrada de Judá até Susã — não há livro nenhum. A resposta que dá é curta e não poupa o irmão: \"Os restantes, que ficaram do cativeiro, lá na província estão em grande miséria e desprezo; e o muro de Jerusalém fendido e as suas portas queimadas a fogo\" (Ne 1:3). Hanani volta a aparecer seis capítulos depois, e agora do outro lado da história: acabado o muro, Neemias entrega-lhe a cidade — \"Eu nomeei a Hanani, meu irmão, e a Hananias, líder da fortaleza, sobre Jerusalém\" (Ne 7:2). O homem que trouxe a notícia da ruína é o que fica responsável pela cidade reparada, e o critério da nomeação está escrito no mesmo versículo: fidelidade e temor de Deus, mais do que muitos. Provavelmente é ainda o mesmo Hanani que aparece na dedicação do muro, entre os que iam \"com os instrumentos musicais de Davi\" (Ne 12:36).",
  },
  "sambalate-o-horonita": {
    title: "Sambalate, o horonita, o adversário de fora do muro",
    subtitle: "Ne 2:10,19 • 4 • 6 • 13:28 — o homem que ria, conspirou, escreveu e casou uma filha para dentro",
    text: "Aparece pela primeira vez como reação: \"O que ouvindo Sambalate, o horonita, e Tobias, o servo amonita, lhes desagradou extremamente que alguém viesse a procurar o bem dos filhos de Israel\" (Ne 2:10). Era, pelos documentos da época, o governador de Samaria — o poder regional a norte de Judá —, e por isso um muro em Jerusalém lhe custava influência, comércio e rota. A sua campanha percorre todos os degraus. Primeiro o escárnio, dito diante do exército de Samaria: \"Que fazem estes fracos judeus?… Vivificarão dos montões do pó as pedras que foram queimadas?\" (Ne 4:2). Depois a conjura armada com árabes, amonitas e asdoditas (Ne 4:8). Depois a diplomacia envenenada: quatro convites para Ono, e uma carta ABERTA na mão de um moço acusando Neemias de se querer fazer rei (Ne 6:5-7). Depois o suborno de profetas dentro da cidade, Semaías e a profetisa Noadia (Ne 6:12-14). E, quando nada resulta, a infiltração pelo casamento — no último capítulo do livro, um neto do sumo sacerdote é \"genro de Sambalate, o horonita, por isso o afugentei de mim\" (Ne 13:28). O julgamento sobre ele está numa oração de Neemias, não numa batalha: \"Lembra-te, meu Deus, de Tobias e de Sambalate, conforme a estas suas obras\" (Ne 6:14).",
  },
  "tobias-o-servo-amonita": {
    title: "Tobias, o servo amonita, o inimigo que tinha família dentro de Jerusalém",
    subtitle: "Ne 2:10 • 4:3 • 6:17-19 • 13:4-8 — o que ganhou um quarto dentro da casa de Deus",
    text: "Neemias chama-lhe sempre \"o servo amonita\" (Ne 2:10), e as duas palavras são acusações: amonita, porque a lei dizia que \"nenhum amonita nem moabita entrará na congregação do Senhor\" (Dt 23:3); servo, porque é subalterno de Sambalate, apesar de ter mais gente sua dentro de Jerusalém do que qualquer outro adversário. A frase pela qual ficou conhecido é a piada do capítulo 4: \"Ainda que edifiquem, contudo, vindo uma raposa, derrubará facilmente o seu muro de pedra\" (Ne 4:3). Mas o perigo dele nunca foi militar, e sim doméstico: era genro de Secanias, filho de Ará, um chefe de casa paterna do rol dos que voltaram, e o filho dele casara com a filha de Mesulão, filho de Berequias, um dos homens que repararam o muro — \"Porque muitos em Judá lhe eram ajuramentados\" (Ne 6:18). As cartas iam e vinham, e os nobres contavam as boas ações dele diante do governador (Ne 6:19). O ponto mais fundo chega quando Neemias está ausente: o sacerdote Eliasibe, aparentado com ele, esvazia a câmara das ofertas do templo e faz-lhe ali um aposento — \"lancei todos os móveis da casa de Tobias fora da câmara\" (Ne 13:8). O amonita que a lei não deixava entrar na congregação tinha conseguido cama dentro do santuário.",
  },
  "gesem-o-arabio": {
    title: "Gesém, o árabe, o terceiro dos adversários",
    subtitle: "Ne 2:19 • 6:1-6 — o chefe do deserto do sul, que fechava o cerco pelo outro lado",
    text: "\"O que ouvindo Sambalate, o horonita, e Tobias, o servo amonita, e Gesém, o árabe, zombaram de nós, e desprezaram-nos, e disseram: Que é isto que fazeis? Quereis rebelar-vos contra o rei?\" (Ne 2:19). Com ele o cerco fica completo: Sambalate a norte, em Samaria; Tobias a leste, em Amom; Gesém a sul, com as tribos árabes que dominavam as rotas de caravana do Neguebe até ao Egito. Uma Jerusalém murada punha uma alfândega no meio do seu comércio. É ele quem convida com Sambalate para o vale de Ono (Ne 6:2), e é o nome dele que a carta aberta invoca para dar peso à calúnia: \"Entre os gentios se ouviu, e Gasmu diz: Tu e os judeus intentais rebelar-vos, então edificas o muro; e tu te farás rei deles\" (Ne 6:6) — a acusação de rebelião contra a Pérsia era a única que podia parar a obra por decreto, como já parara uma vez no tempo de Artaxerxes (Ed 4:21-23). Neemias responde com uma frase seca: \"De tudo o que dizes coisa nenhuma sucedeu; mas tu, do teu coração, o inventas\" (Ne 6:8).",
  },
  "asafe-guarda-da-floresta-do-rei": {
    title: "Asafe, guarda da floresta do rei",
    subtitle: "Ne 2:8 — o funcionário persa sem o qual Jerusalém não teria portas",
    text: "\"Como também uma carta para Asafe, guarda da floresta do rei, para que me dê madeira para cobrir as portas do paço da casa, para o muro da cidade e para a casa em que eu houver de entrar. E o rei mas deu, segundo a boa mão de Deus sobre mim\" (Ne 2:8). Aparece uma vez e nunca mais, e sem ele o livro não tem portas: em Judá não há mata de porte, e as vigas das portas do muro, as travessas dos portais e os telhados só podem sair de um bosque real administrado pelo império. O nome é hebraico, o que sugere um judeu do cativeiro no serviço florestal persa — mais um dos muitos que o livro mostra dentro da máquina do império, como o próprio copeiro e como Petaías, que estava \"à mão do rei, em todos os negócios do povo\" (Ne 11:24). Repare no que Neemias faz com este versículo: pede uma carta comercial, recebe-a, e credita o resultado a Deus na mesma frase. É esse o padrão inteiro do livro — não há voz do céu em nenhum capítulo, há uma mão boa que se reconhece depois, nos despachos que saem certos.",
  },
  "eliasibe-o-sumo-sacerdote": {
    title: "Eliasibe, o sumo sacerdote, que abriu a obra do muro e acabou a alugar uma câmara do templo a Tobias",
    subtitle: "Ne 3:1,20-21 • 12:10 • 13:4-9,28 — a mesma pessoa nas duas pontas do livro",
    text: "É o primeiro nome do canteiro de obras: \"E levantou-se Eliasibe, o sumo sacerdote, com os seus irmãos, os sacerdotes, e reedificaram a porta do gado, a qual consagraram\" (Ne 3:1). Neto de Jesuá, que voltara com Zorobabel (Ne 12:10), consagra a porta por onde entram os animais do sacrifício e trabalha nela com as próprias mãos; Baruque e Meremote reparam depois \"até à porta da casa de Eliasibe\" e \"até à extremidade da casa de Eliasibe\" (Ne 3:20-21), o que mostra o tamanho da sua residência dentro da cidade. E é o mesmo homem que aparece no último capítulo do outro lado: \"Ora, antes disto, Eliasibe, sacerdote, que presidia sobre a câmara da casa do nosso Deus, se tinha aparentado com Tobias; e fizera-lhe uma câmara grande, onde dantes se depositavam as ofertas de alimentos, o incenso, os utensílios, os dízimos do grão, do mosto e do azeite\" (Ne 13:4-5). Deu ao amonita o armazém que sustentava os levitas — e por isso os levitas fugiram para os seus campos. Um neto seu era genro de Sambalate (Ne 13:28). A carreira de Eliasibe é a advertência silenciosa do livro: consagrar uma porta não impede ninguém de, vinte anos depois, abrir outra.",
  },
  "salum-filho-de-haloes": {
    title: "Salum, filho de Haloés, líder da outra meia parte de Jerusalém, que reparou o muro ele e suas filhas",
    subtitle: "Ne 3:12 — o único chefe de obra da Bíblia cujas filhas entram no relatório",
    text: "\"E ao seu lado reparou Salum, filho de Haloés, líder da outra meia parte de Jerusalém, ele e suas filhas\" (Ne 3:12). É chefe de distrito — governa metade de Jerusalém, o mesmo posto de Refaías, filho de Hur, que aparece três versículos antes (Ne 3:9) —, e portanto tinha gente para mandar. O que o texto regista, porém, é que trabalhou com as filhas, no mesmo formato com que nomeia ourives, boticários, sacerdotes e homens de Jericó. Não há paralelo em toda a Escritura: nenhuma outra lista de obra pública, censo de trabalhadores ou registo de reparação nomeia filhas a levantar pedra. Uma leitura possível é que não tivesse filhos varões e que a casa toda tenha ido para o andaime; outra é que fossem simplesmente as mãos que ele tinha. Em qualquer dos casos o Espírito Santo mandou escrever, e ficou — a poucos versículos da nota inversa e vergonhosa sobre os nobres de Tecoa, que \"não submeteram a cerviz ao serviço de seu Senhor\" (Ne 3:5). Num mesmo capítulo: fidalgos que não desceram do lugar, e as filhas de um chefe de distrito que subiram ao muro.",
  },
  "filha-mais-velha-de-salum": {
    title: "A filha mais velha de Salum, filho de Haloés, no trecho do muro do pai",
    subtitle: "Ne 3:12 — \"ele e suas filhas\"",
    text: "\"E ao seu lado reparou Salum, filho de Haloés, líder da outra meia parte de Jerusalém, ele e suas filhas\" (Ne 3:12). São três palavras e são únicas: em nenhum outro lugar da Bíblia aparecem filhas dentro de um relatório de obra, nomeadas ao lado dos ourives, dos boticários e dos sacerdotes que repararam a volta da cidade. A mais velha é quem organiza as irmãs — quem mede o trecho com o pai, quem enche e passa o cesto, quem assenta a fiada de baixo enquanto ele trabalha a de cima. Fazia-se isto sob a mesma ordem que valia para todos, e a partir do capítulo 4 com a arma ao lado da pedra: \"cada um com uma das mãos fazia a obra e na outra tinha as armas\" (Ne 4:17). O muro em que ela trabalhou é o mesmo por cima do qual, doze capítulos adiante, os dois grandes coros hão de andar cantando, e a alegria de Jerusalém se ouviu de longe (Ne 12:43). Uma parte daquela pedra é dela.",
  },
  "segunda-filha-de-salum": {
    title: "A segunda filha de Salum, filho de Haloés, no muro de Jerusalém",
    subtitle: "Ne 3:12 — a metade de Jerusalém que o pai governava",
    text: "O pai é \"líder da outra meia parte de Jerusalém\" (Ne 3:12): um chefe de distrito com autoridade sobre metade da cidade, que podia ter mandado trabalhar em vez de trabalhar. Foi para o andaime e levou as filhas. O trecho que lhes coube fica na volta ocidental do muro, entre a torre dos fornos e a porta do vale, o lado por onde Neemias saíra na sua ronda noturna e vira as portas consumidas pelo fogo (Ne 2:13). Repare no que o capítulo 3 faz com o trabalho: não descreve nenhum, e mesmo assim conta tudo — quem, com quem, e em que ponto da cidade. Por isso esta linha basta. Numa lista onde os nobres de Tecoa entraram para a história por NÃO terem submetido a cerviz (Ne 3:5), três irmãs entraram por terem carregado pedra ao lado do pai.",
  },
  "terceira-filha-de-salum": {
    title: "A terceira filha de Salum, filho de Haloés, na obra do muro",
    subtitle: "Ne 3:12 — a mais nova das que repararam com o pai",
    text: "\"ele e suas filhas\" (Ne 3:12). O plural não diz quantas eram, e o desenho da cena escolhe três; o que o texto garante é que foram mais do que uma e que estavam lá. A mais nova é a que carrega água aos que trabalham, tira o pó das pedras queimadas, corre o recado ao trecho seguinte — e faz parte da obra tanto quanto o ourives Uziel, quatro versículos antes. Havia razões de sobra para ficar em casa: a cidade estava sem muro, os inimigos rondavam, e um mês depois seria preciso trabalhar de espada cingida aos lombos, \"desde a subida da alva até ao sair das estrelas\" (Ne 4:21). Elas ficaram. Quando o muro se fechou em cinquenta e dois dias e os povos em redor \"reconheceram que o nosso Deus fizera esta obra\" (Ne 6:16), a conta incluía o trecho de Salum, filho de Haloés, e das filhas dele.",
  },
  "uziel-dos-ourives": {
    title: "Uziel, filho de Haraías, um dos ourives, que reparou até ao muro largo",
    subtitle: "Ne 3:8 — o homem do ouro fino a assentar pedra bruta",
    text: "\"Ao seu lado reparou Uziel, filho de Haraías, um dos ourives; e ao seu lado reparou Hananias, filho de um dos boticários; e fortificaram a Jerusalém até ao muro largo\" (Ne 3:8). O ourives é o artesão mais especializado de uma cidade antiga: trabalha a fio, a martelo pequeno e a balança, e as suas mãos valem pelo que é fino. Aqui está a levantar alvenaria — e o texto, que podia ter dito apenas \"Uziel, filho de Haraías\", faz questão de anotar o ofício, porque é isso que impressiona. Os ourives de Jerusalém aparecem ainda no fim da volta, a fechar o circuito ao lado dos mercadores: \"E entre a câmara do canto e a porta do gado, repararam os ourives e os mercadores\" (Ne 3:32). Não é uma corporação a pagar um trecho: é uma corporação a construí-lo. O \"muro largo\" que Uziel ajudou a fortificar é a secção espessa do lado ocidental, provavelmente a que Ezequias mandara reforçar contra a Assíria — pedra velha de duzentos e cinquenta anos, reaproveitada por um homem que ganhava a vida a fundir ouro.",
  },
  "hananias-dos-perfumistas": {
    title: "Hananias, filho de um dos boticários, que reparou o muro largo com o ourives",
    subtitle: "Ne 3:8 — o perfumista no andaime",
    text: "\"e ao seu lado reparou Hananias, filho de um dos boticários; e fortificaram a Jerusalém até ao muro largo\" (Ne 3:8). O boticário — o perfumista — é o ofício das especiarias, dos óleos e das resinas, e no Israel antigo tinha um estatuto quase sacerdotal, porque era essa a arte com que se compunha o óleo santo da unção e o incenso do santuário, \"obra do perfumista\" (Êx 30:25). É gente de mãos limpas, de dedos que medem gramas, e o capítulo põe-na a carregar pedra ao lado do ourives, ombro com ombro com os homens de Jericó, com os sacerdotes de Eliasibe e com os netineus de Ofel. Este versículo é o retrato da estratégia inteira de Neemias: não recrutou pedreiros, recrutou a cidade. E a cidade veio como era — com os seus ourives, os seus perfumistas, os seus mercadores e as filhas de um chefe de distrito.",
  },
  "semaias-filho-de-delaias": {
    title: "Semaías, filho de Delaías, o filho de Meetabel, que estava encerrado em casa",
    subtitle: "Ne 6:10-13 — o profeta alugado para o fazer pecar",
    text: "\"E, entrando eu em casa de Semaías, filho de Delaías, o filho de Meetabel (que estava encerrado), disse ele: Vamos juntamente à casa de Deus, ao meio do templo, e fechemos as portas do templo; porque virão matar-te; sim, de noite virão matar-te\" (Ne 6:10). É a mais fina das cinco armadilhas do capítulo, porque vem de dentro, de um homem com credenciais proféticas, e o conselho até parece piedade. O \"encerrado\" pode ser um sinal profético encenado ou um recolhimento ritual — em qualquer caso, obriga Neemias a ir ter com ele, e não o contrário. A resposta é uma das grandes frases do livro, e é feita de duas perguntas: \"Um homem como eu fugiria? E quem há, como eu, que entre no templo para que viva? De maneira nenhuma entrarei\" (Ne 6:11). Neemias não é sacerdote; entrar no santo lugar seria pecado público, e um governador escondido no templo estaria acabado como líder na manhã seguinte. Ele percebe a mão que paga: \"E percebi que não era Deus quem o enviara; mas esta profecia falou contra mim, porquanto Tobias e Sambalate o subornaram\" (Ne 6:12), e o objetivo declarado era \"para me atemorizar, e para que assim fizesse, e pecasse\" (Ne 6:13).",
  },
  "noadias-a-profetisa": {
    title: "Noadia, a profetisa que procurou atemorizar Neemias",
    subtitle: "Ne 6:14 — o único versículo em que aparece, e o título não lhe é retirado",
    text: "\"Lembra-te, meu Deus, de Tobias e de Sambalate, conforme a estas suas obras, e também da profetisa Noadia, e dos mais profetas que procuraram atemorizar-me\" (Ne 6:14). Uma linha, e é tudo o que a Escritura diz dela — mas diz muito. Tem ofício profético reconhecido em Jerusalém, o mesmo título de Débora, que julgou Israel debaixo da palmeira, de Hulda, a quem o rei Josias mandou consultar, e de Ana, que reconheceu o menino no templo. E usou-o contra a obra, ao lado de Semaías e dos outros profetas alugados por Tobias e Sambalate. O texto não a chama falsa profetisa nem lhe tira o nome: nomeia-a com o título intacto e entrega-a a Deus, que é o que Neemias faz sempre que não pode julgar. É uma advertência colocada exatamente onde dói — no capítulo em que o muro se acaba, o perigo maior não veio do exército de Samaria, veio de gente que falava em nome de Deus dentro da cidade.",
  },
  "hananias-o-maioral-da-fortaleza": {
    title: "Hananias, líder da fortaleza, posto sobre Jerusalém porque era homem fiel e temente a Deus mais do que muitos",
    subtitle: "Ne 7:2-3 — a nomeação cujo critério vem escrito",
    text: "\"Eu nomeei a Hanani, meu irmão, e a Hananias, líder da fortaleza, sobre Jerusalém; porque ele era homem fiel e temente a Deus, mais do que muitos\" (Ne 7:2). É das poucas vezes em que a Escritura explica POR QUE um homem foi nomeado, e o currículo tem dois itens, nenhum deles técnico: fidelidade e temor de Deus. A fortaleza é a birâ, o forte que dominava o templo pelo lado norte — o posto militar mais importante da cidade —, e ele já a comandava. As ordens que recebe desenham uma disciplina de cidade recém-murada: \"Não se abram as portas de Jerusalém até que o sol aqueça\"… \"e vós trancai-as\"… \"cada um na sua guarda, e cada um diante da sua casa\" (Ne 7:3). Abrir tarde, fechar cedo, trancar, e transformar cada morador em sentinela do seu pedaço de rua. Neemias vai partir para Susã anos depois, e é a homens assim que a cidade fica entregue.",
  },
  "matanias-que-comecava-as-acoes-de-gracas": {
    title: "Matanias, filho de Mica, dos filhos de Asafe, o chefe que iniciava as ações de graças na oração",
    subtitle: "Ne 11:17 • 12:8,25 — o homem que dava o tom ao louvor de Jerusalém",
    text: "\"E Matanias, filho de Mica, filho de Zabdi, filho de Asafe, o chefe, que iniciava as ações de graças na oração, e Bacbuquias, o segundo de seus irmãos; depois Abda, filho de Samua, filho de Galal, filho de Jedutum\" (Ne 11:17). É um cargo que só aparece aqui em toda a Escritura: o homem que COMEÇA — que entoa a primeira linha da ação de graças e a quem o coro responde. Descende de Asafe, o cantor que Davi pusera à frente do louvor cinco séculos antes, e a sua função é a prova de que o ofício sobreviveu ao exílio inteiro sem cair: \"Porque já nos dias de Davi e Asafe, desde a antiguidade, havia chefes dos cantores, e dos cânticos de louvores e de ação de graças a Deus\" (Ne 12:46). Aparece de novo entre os levitas que \"dirigiam os louvores\" (Ne 12:8) e entre os porteiros das tesourarias (Ne 12:25). Quando os dois grandes coros subirem ao muro na dedicação, a voz que dá a partida sai desta casa.",
  },
  "artaxerxes-rei-de-babilonia": {
    title: "Artaxerxes, rei de babilônia, no ano trinta e dois do seu reinado",
    subtitle: "Ne 13:6 — o mesmo rei, chamado pelo nome do império antigo",
    text: "\"Mas durante tudo isto não estava eu em Jerusalém, porque no ano trinta e dois de Artaxerxes, rei de babilônia, fui ter com o rei; mas após alguns dias tornei a alcançar licença do rei\" (Ne 13:6). É o mesmo Artaxerxes que no capítulo 2 lhe deu as cartas e a escolta, aqui chamado \"rei de babilônia\" — o título fala do território, e não da dinastia: para um judeu da província, o senhor de Babilônia é o senhor do mundo, seja ele caldeu ou persa. Este versículo é a explicação inteira do último capítulo do livro. Doze anos de governo (Ne 5:14), depois a viagem obrigatória à corte para prestar contas, e nesse intervalo tudo se desfaz: a câmara das ofertas vira quarto de Tobias, os dízimos deixam de ser entregues, os levitas fogem para os seus campos, os lagares laboram ao sábado e os filhos falam asdodita. O rei dá a licença de regresso, e Neemias volta a limpar tudo — mas o livro fecha sem entregar a nenhum trono a garantia do que fica: \"lembra-te de mim, Deus meu, para bem\" (Ne 13:31).",
  },
  "zacur-filho-de-imri": {
    title: "Zacur, filho de Imri, que edificou ao lado dos homens de Jericó",
    subtitle: "Ne 3:2 — o segundo trecho da volta do muro",
    text: "\"E junto a ele edificaram os homens de Jericó; também ao seu lado edificou Zacur, filho de Imri\" (Ne 3:2). É o terceiro nome do capítulo, logo depois do sumo sacerdote e das turmas de Jericó, e o seu lugar diz o método da obra: cada trecho começa onde acaba o anterior — \"junto a ele\", \"ao seu lado\", \"depois dele\" —, e é essa corrente que fecha o perímetro em cinquenta e dois dias. Zacur trabalha na secção norte, entre a porta do gado e a porta do peixe, o lado mais vulnerável de Jerusalém, por onde entraram todos os exércitos que a tomaram, porque é o único que não tem vale a defendê-lo. Não se sabe mais nada dele; um Zacur reaparece entre os levitas que selam a firme aliança (Ne 10:12) e um outro é avô de Hanã, um dos quatro tesoureiros achados fiéis no fim do livro (Ne 13:13). É assim a lista inteira: nomes que aparecem uma vez, com a coordenada exata do pedaço de muro que levantaram.",
  },
  "baruque-filho-de-zabai": {
    title: "Baruque, filho de Zabai, que reparou com grande ardor",
    subtitle: "Ne 3:20 — o único homem do capítulo de quem se diz COMO trabalhou",
    text: "\"Depois dele reparou com grande ardor Baruque, filho de Zabai, outra medida, desde a esquina até à porta da casa de Eliasibe, o sumo sacerdote\" (Ne 3:20). O capítulo 3 é uma lista técnica: quem, onde, e que porta. Quarenta e tal trechos, e apenas um adjetivo — este. Alguém que ali estava reparou que aquele homem trabalhava de outra maneira, e o Espírito Santo mandou pôr no relatório. É o contraponto exato dos nobres de Tecoa, quinze versículos antes, dos quais se escreveu que \"não submeteram a cerviz ao serviço de seu Senhor\" (Ne 3:5): a mesma lista guarda a memória de quem não trabalhou e de quem trabalhou com ardor. O trecho de Baruque não é pequeno — vai da esquina até à porta da casa do sumo sacerdote —, e ele fá-lo como \"outra medida\", isto é, além do que já lhe cabia. Um Baruque aparece depois entre os sacerdotes que selam a firme aliança (Ne 10:6), e outro é pai de Maaséias, dos filhos de Perez, que se mudou para dentro de Jerusalém (Ne 11:5).",
  },
  "mesulao-filho-de-berequias": {
    title: "Mesulão, filho de Berequias, o filho de Mesezabeel, que reparou dois trechos e casou a filha com o filho de Tobias",
    subtitle: "Ne 3:4,30 • 6:18 — o construtor do muro com um genro do outro lado dele",
    text: "Aparece duas vezes no relatório da obra, o que é raro: primeiro no lado norte, \"e ao seu lado reparou Mesulão, filho de Berequias, o filho de Mesezabeel\" (Ne 3:4), e depois no lado oriental, \"depois dele reparou Mesulão, filho de Berequias, defronte da sua câmara\" (Ne 3:30) — tinha um aposento junto ao templo, o que indica família de posição. E aparece uma terceira vez, num contexto que estraga tudo: \"e seu filho Joanã se casara com a filha de Mesulão, filho de Berequias\" (Ne 6:18), o filho de Tobias, o amonita. O homem que assentou pedra em dois pontos do muro é sogro da casa do inimigo que dizia que uma raposa o derrubaria. Não há repreensão contra ele no texto; há apenas a constatação do capítulo 6 de que \"muitos em Judá lhe eram ajuramentados\" a Tobias. É a linha que explica por que o problema dos casamentos volta no capítulo 13 e por que Neemias reage a ele com tanta violência: numa província pequena, a fronteira mais difícil de guardar passava dentro das famílias que tinham construído o muro.",
  },
  "secanias-filho-de-ara": {
    title: "Secanias, filho de Ará, sogro de Tobias",
    subtitle: "Ne 6:18 — o chefe de casa paterna que ligou a nobreza de Judá ao amonita",
    text: "\"Porque muitos em Judá lhe eram ajuramentados, porque era genro de Secanias filho de Ará\" (Ne 6:18). Os filhos de Ará estão no rol dos que subiram do cativeiro, seiscentos e cinquenta e dois deles (Ne 7:10) — uma das casas paternas grandes do regresso. Secanias é o chefe dessa casa, e casou a filha com Tobias, o servo amonita. Um casamento assim não é um episódio privado: cria uma rede de obrigações juradas que atravessa a cidade inteira, e é isso que o versículo diz com a palavra AJURAMENTADOS. Por isso as cartas iam e vinham (Ne 6:17), por isso as boas ações de Tobias eram contadas ao governador (Ne 6:19), e por isso o sacerdote Eliasibe, também aparentado com ele, acabou por lhe dar uma câmara dentro da casa de Deus (Ne 13:4). O muro fechou-se em cinquenta e dois dias; esta rede levou o livro inteiro e não se fechou nunca.",
  },
  "joana-filho-de-tobias": {
    title: "Joanã, filho de Tobias, casado com a filha de Mesulão, filho de Berequias",
    subtitle: "Ne 6:18 — a segunda geração da aliança pelo casamento",
    text: "\"e seu filho Joanã se casara com a filha de Mesulão, filho de Berequias\" (Ne 6:18). Repare no desenho: o pai, Tobias, casou com a filha de Secanias, chefe de uma casa paterna do rol; o filho casou com a filha de Mesulão, um dos homens que repararam o muro com as próprias mãos em dois trechos. Duas gerações e duas alianças matrimoniais no coração da nobreza de Judá — é assim que um amonita, a quem a lei proibia a entrada na congregação (Dt 23:3), se torna alguém a quem \"muitos em Judá lhe eram ajuramentados\". Joanã não tem falas e não faz nada no livro; a sua importância é ser a prova de que a estratégia de Tobias funcionava. O capítulo 13 mostra o resultado final: quando Neemias se ausenta, o pai deste homem tem mobília instalada numa câmara do templo, e é preciso o governador voltar de Susã e atirá-la escadas abaixo com as próprias mãos (Ne 13:8).",
  },
  "filha-de-mesulao-casada-com-o-filho-de-tobias": {
    title: "A filha de Mesulão, filho de Berequias, casada com Joanã, filho de Tobias",
    subtitle: "Ne 6:18 — a noiva que fica entre o muro e quem zombava dele",
    text: "\"e seu filho Joanã se casara com a filha de Mesulão, filho de Berequias\" (Ne 6:18). O pai dela está na lista de honra do capítulo 3, e não uma vez: reparou o trecho junto à porta do peixe (Ne 3:4) e outro defronte da sua própria câmara, do lado oriental (Ne 3:30). O sogro dela é o homem que disse que uma raposa derrubaria aquele muro (Ne 4:3). Não há uma palavra de acusação contra ela no texto — o livro não a julga, apenas a coloca ali, exatamente sobre a linha que divide as duas metades da história. Casamentos assim faziam-se por negócio e por posição, e numa província do tamanho de Judá eram o modo normal de uma família subir; o que este casamento custou está escrito nos capítulos 6 e 13. Ela é o rosto da cláusula que a firme aliança tentaria fechar quatro capítulos adiante: \"que não daríamos as nossas filhas aos povos da terra, nem tomaríamos as filhas deles para os nossos filhos\" (Ne 10:30).",
  },
};
