// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de PERSONAGEM (por `id`) das cenas de ruth. Vem por import() junto com
// o roteiro do livro: quem lê Rute não baixa os nomes de Crônicas.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHARS: Record<string, StageInfo> = {
  naassom: { title: "Naassom, filho de Aminadabe", subtitle: "Príncipe de Judá (Nm 1:7)", text: "Cabeça da maior das tribos — setenta e quatro mil e seiscentos homens (Nm 1:26-27) — e o primeiro a mover-se: Judá acampa e parte à frente, ao oriente (Nm 2:3; 10:14). Foi ele quem abriu os doze dias da dedicação, oferecendo no primeiro dia (Nm 7:12-17). Cunhado de Arão (Êx 6:23), está na linhagem que desce até Boaz, Davi e o Cristo (Rt 4:20; Mt 1:4): o cetro que Jacó prometera a Judá já vai adiante do arraial." },
  noemi: { title: "Noemi", subtitle: "A que voltou vazia a Belém (Rt 1:2)", text: "Mulher de Elimeleque, desceu com ele a Moabe por causa da fome e ali perdeu o marido e os dois filhos. Voltou a Belém dizendo: \"Não me chameis Noemi; chamai-me Mara, porque grande amargura me tem dado o Todo-Poderoso... cheia parti, porém vazia o Senhor me fez tornar\" (Rt 1:20-21). Falou verdade, mas não a verdade toda: nos braços trazia Rute, e no fim as vizinhas lhe põem ao colo um menino, dizendo \"a Noemi nasceu um filho\" (Rt 4:17)." },
  rute: { title: "Rute, a moabita", subtitle: "A que se apegou a Noemi e ao seu Deus (Rt 1:4)", text: "Viúva moabita — de um povo excluído da congregação (Dt 23:3) —, recusou voltar aos seus e fez o juramento que se tornou o coração do livro: \"aonde quer que fores irei... o teu povo é o meu povo, e o teu Deus é o meu Deus\" (Rt 1:16). Respigou nos campos de Boaz para sustentar a sogra, e dele ouviu: \"o Senhor galardoe o teu feito... sob cujas asas te vieste abrigar\" (Rt 2:12). A estrangeira que buscou refúgio no Deus de Israel tornou-se bisavó de Davi e entrou na genealogia do Messias (Rt 4:17; Mt 1:5)." },
  boaz: { title: "Boaz", subtitle: "O remidor, homem valente e rico (Rt 2:1)", text: "Parente de Elimeleque em Belém, saudava os segadores com \"o Senhor seja convosco\" e mandou que deixassem punhados de propósito para a estrangeira (Rt 2:4,16). Na eira, ouviu o pedido de Rute — \"estende pois tua capa sobre a tua serva, porque tu és o remidor\" — e prometeu resolvê-lo pela lei, sem pressa nem escândalo (Rt 3:9-13). À porta da cidade resgatou a herança e tomou Rute por mulher diante dos anciãos. Nele se vê a figura do Redentor que paga o preço e traz o excluído para dentro da família (Lv 25:25; Ef 1:7)." },
  orfa: { title: "Orfa", subtitle: "A nora que voltou ao seu povo (Rt 1:4)", text: "A outra moabita, casada com um dos filhos de Noemi. Chorou, beijou a sogra e voltou — \"eis que tua cunhada tornou ao seu povo e aos seus deuses; torna tu também após a tua cunhada\" (Rt 1:14-15). Não fez nada de perverso: fez o razoável, o que a sogra lhe aconselhara. Fica na história como o contraste que faz brilhar a escolha de Rute — dois caminhos na mesma encruzilhada, e só um leva a Belém." },
  goel: { title: "O remidor mais chegado", subtitle: "O parente que recusou o resgate (Rt 4:1)", text: "A Escritura de propósito não lhe dá nome — Boaz o chama apenas de \"fulano\" à porta da cidade (Rt 4:1). Aceitou de bom grado resgatar a terra, até saber que com ela vinha Rute e o dever de levantar o nome do morto: \"não poderei redimi-la, para que não prejudique a minha herança\" (Rt 4:6). Descalçou o sapato e saiu da história sem nome. Quem calcula a herança acima do dever perde justamente aquilo que buscava guardar." },
  jesse: { title: "Jessé", subtitle: "O belemita, pai de Davi (1Sm 16:1)", text: "Neto de Boaz e Rute (Rt 4:17,22), criador de gado em Belém de Judá e pai de oito filhos. Quando Samuel veio com a bezerra do sacrifício, apresentou sete deles e não se lembrou de mandar chamar o caçula, que estava com as ovelhas — e o profeta teve de dizer: \"não nos assentaremos até que ele venha aqui\" (1Sm 16:11). Foi então que Deus deu a regra: \"o homem vê o que está diante dos olhos, porém o Senhor olha para o coração\" (1Sm 16:7). O seu nome ficou como o do tronco messiânico: \"sairá um rebento do tronco de Jessé\" (Is 11:1), e assim Cristo é \"a raiz e a geração de Davi\" (Ap 22:16)." },
  davi: { title: "Davi", subtitle: "O pastor de Belém, ungido rei (1Sm 16–31)", text: "O oitavo e menor filho de Jessé, apascentando ovelhas quando Samuel derramou sobre ele o azeite no meio dos irmãos — \"e desde aquele dia em diante o Espírito do Senhor se apoderou de Davi\" (1Sm 16:13). Tocava harpa para aliviar Saul, matou o leão e o urso do rebanho antes de matar o gigante, e derrubou Golias com uma funda e cinco pedras lisas em nome do \"Senhor dos Exércitos, o Deus dos exércitos de Israel\" (1Sm 17:45). Amado por Jônatas e pelo povo (\"Saul feriu os seus milhares, porém Davi os seus dez milhares\"), foi caçado por dez anos pelo rei que servira — e por duas vezes teve Saul na ponta da mão e não estendeu a mão contra \"o ungido do Senhor\" (1Sm 24:6; 26:9). Homem \"segundo o coração de Deus\" (1Sm 13:14), autor de grande parte dos Salmos, e o rei de cuja casa Deus prometeu um trono eterno (2Sm 7:16) — cumprido em Jesus, \"o filho de Davi\" (Mt 1:1)." },
};
