// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de OBJETO-MARCO (por `tag`) das cenas de esther.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const TAGS: Record<string, StageInfo> = {
  "coroa-real-da-persia": {
    title: "A coroa real da Pérsia",
    subtitle: "Et 1:11 • 2:17 — a coroa que Vasti recusou usar e que foi posta na cabeça de Ester",
    text: "É o mesmo objeto em dois momentos opostos do livro. Primeiro é o motivo da convocação que trava o império: os sete camareiros são mandados \"que introduzissem na presença do rei a rainha Vasti, com a coroa real, para mostrar aos povos e aos príncipes a sua beleza, porque era formosa à vista\" (Et 1:11) — a coroa aqui não honra ninguém, é o adereço da peça exposta ao fim de cento e oitenta dias de mostruário. Vasti recusa, e o edito de Memucã manda que \"o rei dê o reino dela a outra que seja melhor do que ela\" (Et 1:19). Um capítulo depois, o mesmo círculo de ouro aparece sem plateia nenhuma: \"e pôs a coroa real na sua cabeça, e a fez rainha em lugar de Vasti\" (Et 2:17). Ninguém no salão sabe que a cabeça que agora a leva é a de uma judia do cativeiro de Jeconias." },
  "leis-dos-persas-e-dos-medos": {
    title: "As leis dos persas e dos medos",
    subtitle: "Et 1:19 — a letra que não se revoga",
    text: "\"Se bem parecer ao rei, saia da sua parte um edito real, e escreva-se nas leis dos persas e dos medos, e não se revogue\" (Et 1:19). É a cláusula que governa o livro inteiro e que transforma cada assinatura numa armadilha. Ela prende primeiro o próprio rei: \"apaziguado já o furor do rei Assuero, lembrou-se de Vasti, e do que fizera, e do que se tinha decretado a seu respeito\" (Et 2:1) — pode governar cento e vinte e sete províncias e não pode chamar a mulher de volta. Prende depois o povo condenado, porque nem o rei arrependido pode desfazer a carta de Hamã: \"o documento que se escreve em nome do rei, e que se sela com o anel do rei, não se pode revogar\" (Et 8:8); a saída não é apagar a lei, é escrever outra. É o mesmo direito medo-persa que Daniel enfrentou na cova dos leões, \"conforme a lei dos medos e dos persas, que não se pode revogar\" (Dn 6:8)." },
  "riquezas-da-gloria-do-reino-de-assuero": {
    title: "As riquezas da glória do reino de Assuero",
    subtitle: "Et 1:4 — cento e oitenta dias de tesouro aberto",
    text: "\"Para mostrar as riquezas da glória do seu reino, e o esplendor da sua excelente grandeza, por muitos dias, a saber: cento e oitenta dias\" (Et 1:4). Meio ano de vitrine: as arcas do tesouro abertas de propósito para que os governadores e nobres das cento e vinte e sete províncias vissem por dentro. É a primeira coisa que o livro diz que este rei fez com o seu poder, e ela dá a medida do homem — o mesmo que, dois capítulos depois, aceitará dez mil talentos de prata para deixar que se mate um povo cujo nome nem pergunta (Et 3:9-11). No fim do livro, a curva se fecha na direção contrária: em vez de mostrar o que tem, ele cobra — \"impôs o rei Assuero tributo sobre a terra, e sobre as ilhas do mar\" (Et 10:1)." },
  "colunas-de-marmore-do-jardim-do-palacio": {
    title: "As colunas de mármore do pátio do jardim",
    subtitle: "Et 1:6 — as colunas que seguravam as tapeçarias brancas, verdes e azul celeste",
    text: "\"As tapeçarias eram de pano branco, verde, e azul celeste, pendentes de cordões de linho fino e púrpura, e argolas de prata, e colunas de mármore; os leitos de ouro e de prata, sobre um pavimento de mármore vermelho, e azul, e branco, e preto\" (Et 1:6). O texto para a narrativa inteira para descrever a decoração de uma festa, e isso é intencional: nos sete dias abertos \"a todo o povo que se achava na fortaleza de Susã, desde o maior até ao menor\" (Et 1:5), o assunto é o luxo, e nada mais acontece. As mesmas cores voltam num único outro lugar do livro, e aí já significam outra coisa: \"Então Mardoqueu saiu da presença do rei com veste real azul-celeste e branca... e com uma capa de linho fino e púrpura\" (Et 8:15)." },
  "leitos-de-ouro-e-de-prata": {
    title: "Os leitos de ouro e de prata",
    subtitle: "Et 1:6 — os divãs do banquete dos sete dias, sobre o pavimento de mármore",
    text: "\"os leitos de ouro e de prata, sobre um pavimento de mármore vermelho, e azul, e branco, e preto\" (Et 1:6). São os divãs em que os convidados se reclinavam para comer, postos ao ar livre no pátio do jardim do palácio real, sobre pedra lavrada de quatro cores. O detalhe importa porque este livro conta a história pelos móveis: é reclinado num leito assim que se bebe \"por lei, sem constrangimento\" (Et 1:8); é sobre um leito de banquete que Hamã cairá prostrado aos pés da rainha e assinará a própria sentença — \"Hamã tinha caído prostrado sobre o leito em que estava Ester\" (Et 7:8); e é para o melhor lugar da casa das mulheres que Hegai fará Ester passar (Et 2:9). Ouro e prata aqui não são riqueza guardada: são mobília." },
  "copos-de-ouro-do-banquete-de-assuero": {
    title: "Os copos de ouro, diferentes uns dos outros",
    subtitle: "Et 1:7 — a louça do banquete dos sete dias em Susã",
    text: "\"E dava-se de beber em copos de ouro, e os copos eram diferentes uns dos outros; e havia muito vinho real, segundo a generosidade do rei\" (Et 1:7). O detalhe de que nenhum copo repetia o outro é ostentação levada ao absurdo — não bastava servir em ouro, era preciso que nem duas peças fossem iguais. E o versículo seguinte explica a regra da casa: \"E o beber era por lei, sem constrangimento; porque assim tinha ordenado o rei expressamente a todos os oficiais da sua casa, que fizessem conforme a vontade de cada um\" (Et 1:8). Num império onde tudo é lei irrevogável, a única liberdade legislada é a de beber quanto se quiser. É desse vinho que sai, no sétimo dia, a ordem que derruba a rainha: \"estando já o coração do rei alegre do vinho\" (Et 1:10)." },
  "coroa-real-de-vasti": {
    title: "A coroa que Vasti não veio buscar",
    subtitle: "Et 1:11-12 — o adereço da ordem que voltou sem ser cumprida",
    text: "\"Que introduzissem na presença do rei a rainha Vasti, com a coroa real, para mostrar aos povos e aos príncipes a sua beleza, porque era formosa à vista\" (Et 1:11). Sete eunucos atravessam o palácio para buscar uma mulher e a coroa dela, no sétimo dia de uma festa de sete dias, para exibi-la a um salão de convidados bêbados. A resposta cabe numa linha e derruba o capítulo: \"Porém a rainha Vasti recusou vir conforme a palavra do rei, por meio dos camareiros; assim o rei muito se enfureceu, e acendeu nele a sua ira\" (Et 1:12). O texto não diz por que ela recusou, não a elogia e não a condena. A coroa fica sem cabeça até 2:17, quando é posta na de Ester — e o trono vago que este objeto deixou é por onde entra o resto do livro." },
  "edito-real-que-nao-se-revoga": {
    title: "O edito real que não se revoga",
    subtitle: "Et 1:19-22 — a lei nascida de um desaforo de banquete",
    text: "\"Se bem parecer ao rei, saia da sua parte um edito real, e escreva-se nas leis dos persas e dos medos, e não se revogue, a saber: que Vasti não entre mais na presença do rei Assuero, e o rei dê o reino dela a outra que seja melhor do que ela\" (Et 1:19). O conselho é de Memucã, e o argumento que o sustenta é o medo do que as mulheres do império vão dizer aos maridos (Et 1:17-18). O resultado é o primeiro documento selado do livro, e o mais ridículo: \"que cada homem fosse senhor em sua casa, e que se falasse conforme a língua do seu povo\" (Et 1:22). O trono do mundo conhecido gastou a sua máquina de escrivães, correios e traduções para decretar isso. E a cláusula que os príncipes puseram nele — não se revoga — voltará contra o próprio rei em 2:1 e contra os judeus em 8:8." },
  "cartas-do-edito-de-memuca": {
    title: "As cartas do edito de Memucã",
    subtitle: "Et 1:22 — a cada província segundo a sua escrita, e a cada povo segundo a sua língua",
    text: "\"Então enviou cartas a todas as províncias do rei, a cada província segundo a sua escrita, e a cada povo segundo a sua língua; que cada homem fosse senhor em sua casa, e que se falasse conforme a língua do seu povo\" (Et 1:22). É a primeira das três grandes expedições de correios do livro, e a fórmula \"a cada província segundo a sua escrita, e a cada povo segundo a sua língua\" se repetirá nas outras duas com um peso muito diferente: em 3:12, para despachar a ordem de destruir todos os judeus; em 8:9, para despachar a licença de defenderem a vida — e ali, pela primeira vez, acrescenta-se \"como também aos judeus segundo o seu modo de escrever, e conforme a sua língua\". A mesma máquina, os mesmos cavalos, os mesmos selos, servindo à vaidade, ao ódio e depois à sobrevivência." },
  "mandado-do-rei-para-ajuntar-as-mocas": {
    title: "O mandado que ajuntou as moças em Susã",
    subtitle: "Et 2:3-8 — o decreto que recolheu virgens nas cento e vinte e sete províncias",
    text: "\"E ponha o rei oficiais em todas as províncias do seu reino, que ajuntem a todas as moças virgens e formosas, na fortaleza de Susã, na casa das mulheres, aos cuidados de Hegai, camareiro do rei, guarda das mulheres, e dêem-se-lhes os seus enfeites\" (Et 2:3). A ideia é dos cortesãos (Et 2:2), a assinatura é do rei, e a execução é burocrática: oficiais nomeados por província recolhendo meninas por decreto, com a mesma máquina que recolhe tributo. É por esse mandado que Ester entra na história, e o verbo do texto não deixa dúvida sobre a escolha que ela teve: \"Sucedeu que, divulgando-se o mandado do rei e a sua lei, e ajuntando-se muitas moças na fortaleza de Susã, aos cuidados de Hegai, também levaram Ester à casa do rei, sob a custódia de Hegai, guarda das mulheres\" (Et 2:8)." },
  "fardos-dos-cativos-levados-com-jeconias": {
    title: "Os fardos dos cativos levados com Jeconias",
    subtitle: "Et 2:6 — a bagagem do desterro, um século antes de Susã",
    text: "\"Que fora transportado de Jerusalém, com os cativos que foram levados com Jeconias, rei de Judá, o qual transportara Nabucodonosor, rei de babilônia\" (Et 2:6). Antes de ser o homem da porta do rei, Mardoqueu é isto: gente de trouxa às costas, saída de Jerusalém na leva de Jeconias — a deportação que 2 Reis descreve arrastando \"a mãe do rei, as mulheres do rei, os seus oficiais e os poderosos da terra\" (2Rs 24:15). É a mesma memória que este projeto acabou de desenhar no fim de 2 Crônicas. Estes fardos explicam por que o livro se passa num palácio pagão e não em Jerusalém, por que a rainha de um império é órfã, e por que a ordem de Mardoqueu à filha adotiva foi esconder de que povo ela era (Et 2:10). Um povo que perdeu a terra aprendeu a viver de identidade guardada." },
  "oleo-de-mirra-da-purificacao": {
    title: "O óleo de mirra dos doze meses de purificação",
    subtitle: "Et 2:12 — seis meses com óleo de mirra e seis com especiarias",
    text: "\"E, chegando a vez de cada moça, para vir ao rei Assuero, depois que fora feito a ela segundo a lei das mulheres, por doze meses (porque assim se cumpriam os dias das suas purificações, seis meses com óleo de mirra, e seis meses com especiarias, e com as coisas para a purificação das mulheres)\" (Et 2:12). Um ano inteiro de preparo para uma noite. O texto descreve o regulamento com frieza de manual e não comenta nada, e é essa frieza que dá o tamanho da casa das mulheres: as moças recolhidas por decreto nas províncias passavam doze meses sendo preparadas e depois iam para a segunda casa, \"sob os cuidados de Saasgaz, camareiro do rei, guarda das concubinas; não tornava mais ao rei, salvo se o rei a desejasse, e fosse chamada pelo nome\" (Et 2:14). Contra esse pano de fundo é que se lê o gesto de Ester: \"coisa nenhuma pediu, senão o que disse Hegai\" (Et 2:15)." },
  "melhor-lugar-da-casa-das-mulheres": {
    title: "O melhor lugar da casa das mulheres",
    subtitle: "Et 2:9 — o aposento para onde Hegai fez Ester passar",
    text: "\"E a moça pareceu formosa aos seus olhos, e alcançou graça perante ele; por isso se apressou a dar-lhe os seus enfeites, e os seus quinhões, como também em lhe dar sete moças de respeito da casa do rei; e a fez passar com as suas moças ao melhor lugar da casa das mulheres\" (Et 2:9). É o primeiro favor que Ester recebe em Susã, e o livro não explica de onde veio: o funcionário responsável pelo harém se apressa a favorecer uma recém-chegada — enfeites, quinhões, sete criadas e o melhor aposento. A expressão \"alcançou graça\" reaparecerá nela três vezes (Et 2:9, 2:15, 2:17) e mais duas diante do rei (Et 5:2, 5:8; 7:3). O texto registra o favor e cala sobre a causa. Não diz que Deus o deu; diz que ela agradou e que ele se apressou." },
  "porta-do-rei-em-susa": {
    title: "A porta do rei em Susã",
    subtitle: "Et 2:19 • 3:2 • 4:2 • 5:13 • 6:10 — o umbral em que este livro inteiro se decide",
    text: "\"E reunindo-se segunda vez as virgens, Mardoqueu estava assentado à porta do rei\" (Et 2:19). Não é uma soleira qualquer: a porta do rei é o posto administrativo onde se despacham os negócios e onde se cumprimenta quem entra — por isso é ali que \"todos os servos do rei, que estavam à porta do rei, se inclinavam e se prostravam perante Hamã; porque assim tinha ordenado o rei acerca dele; porém Mardoqueu não se inclinava nem se prostrava\" (Et 3:2). É ali que a lei barra o luto: \"E chegou até diante da porta do rei, porque ninguém vestido de saco podia entrar pelas portas do rei\" (Et 4:2). É a vista dela que estraga toda a glória de Hamã: \"enquanto eu vir o judeu Mardoqueu assentado à porta do rei\" (Et 5:13). E é para lá que Mardoqueu volta depois de ter sido levado a cavalo pelas ruas com a veste real, como se nada tivesse acontecido: \"Depois disto Mardoqueu voltou para a porta do rei\" (Et 6:12)." },
  "coroa-real-de-ester": {
    title: "A coroa real posta na cabeça de Ester",
    subtitle: "Et 2:17 — a coroa de Vasti numa cabeça judia que ninguém sabe que é judia",
    text: "\"E o rei amou a Ester mais do que a todas as mulheres, e alcançou perante ele graça e benevolência mais do que todas as virgens; e pôs a coroa real na sua cabeça, e a fez rainha em lugar de Vasti\" (Et 2:17). É o mesmo objeto que Vasti se recusou a trazer ao salão dos convidados (Et 1:11), agora posto sem plateia. E o versículo seguinte celebra num grande banquete uma coisa que ninguém no salão sabe: \"Ester, porém, não declarava a sua parentela e o seu povo, como Mardoqueu lhe ordenara\" (Et 2:20). A coroa da Pérsia numa órfã dos levados com Jeconias, e o segredo guardado por mais quatro capítulos, até que ela mesma o revele numa mesa de três pessoas: \"dê-se-me a minha vida como minha petição, e o meu povo como meu desejo\" (Et 7:3)." },
  "presentes-do-banquete-de-ester": {
    title: "Os presentes do banquete de Ester",
    subtitle: "Et 2:18 — o alívio às províncias e as dádivas segundo a generosidade do rei",
    text: "\"Então o rei deu um grande banquete a todos os seus príncipes e aos seus servos; era o banquete de Ester; e deu alívio às províncias, e fez presentes segundo a generosidade do rei\" (Et 2:18). O \"alívio\" é uma isenção de tributo ou de serviço decretada em honra da nova rainha: o império inteiro sente no bolso a chegada desta mulher, e ninguém sabe de que povo ela é. Vale comparar com o outro momento em que este livro fala de presentes: no primeiro Purim, os judeus fazem \"dias de banquetes e de alegria, e de mandarem presentes uns aos outros, e dádivas aos pobres\" (Et 9:22). Aqui os presentes descem do trono para as províncias; ali eles atravessam de vizinho para vizinho, e sobra para o pobre." },
  "livro-das-cronicas-perante-o-rei": {
    title: "As crônicas em que se escreveu o feito de Mardoqueu",
    subtitle: "Et 2:23 — a linha anotada e esquecida que salvaria um povo",
    text: "\"E inquiriu-se o negócio, e se descobriu, e ambos foram pendurados numa forca; e foi escrito nas crônicas perante o rei\" (Et 2:23). É o objeto mais importante do livro e ele entra em cena como rotina administrativa: um escriba registra que Mardoqueu denunciou a conspiração de Bigtã e Teres, e o capítulo acaba. Ninguém agradece; a pergunta \"Que honra e distinção se deu por isso a Mardoqueu?\" só será feita quatro capítulos depois, e a resposta será \"Coisa nenhuma se lhe fez\" (Et 6:3). O rolo fica guardado numa estante e é aberto numa noite em que o sono foge do rei, com Hamã já a caminho do pátio para pedir a forca (Et 6:1-4). O livro registra a coincidência e não a explica — nem aqui, nem lá. Quem quiser o comentário tem de buscá-lo em Pv 16:33." },
  "assento-de-hama-acima-dos-principes": {
    title: "O assento de Hamã, posto acima de todos os príncipes",
    subtitle: "Et 3:1 — a cadeira de que nasce a ordem de se prostrarem",
    text: "\"Depois destas coisas o rei Assuero engrandeceu a Hamã, filho de Hamedata, agagita, e o exaltou, e pôs o seu assento acima de todos os príncipes que estavam com ele\" (Et 3:1). O móvel é o cargo: uma cadeira posta fisicamente acima das outras, no salão em que se assentavam \"como principais no reino\" os sete príncipes dos persas e dos medos (Et 1:14). Dela decorre a ordem que gera todo o conflito — \"todos os servos do rei, que estavam à porta do rei, se inclinavam e se prostravam perante Hamã; porque assim tinha ordenado o rei acerca dele; porém Mardoqueu não se inclinava nem se prostrava\" (Et 3:2). No fim do livro, o mesmo lugar é ocupado por outro homem, e o texto usa o mesmo verbo de 3:1 para dizê-lo: \"porque o homem Mardoqueu ia sendo engrandecido\" (Et 9:4), até ser \"o segundo depois do rei Assuero\" (Et 10:3)." },
  "mesa-onde-se-lancou-o-pur-perante-hama": {
    title: "A mesa em que se lançou o pur perante Hamã",
    subtitle: "Et 3:7 — a sorte que escolheu o dia da matança e acabou dando nome à festa",
    text: "\"No primeiro mês (que é o mês de Nisã), no ano duodécimo do rei Assuero, se lançou Pur, isto é, a sorte, perante Hamã, para cada dia, e para cada mês, até ao duodécimo mês, que é o mês de Adar\" (Et 3:7). A sorte é lançada em Nisã, o primeiro mês, e cai no décimo segundo: onze meses de prazo para um povo já sentenciado — tempo suficiente para que uma rainha jejue três dias, um rei perca o sono e uma segunda carta atravesse o império a cavalo. O livro não atribui o resultado a ninguém. A Escritura o comenta em outro lugar, e é o comentário exato deste versículo: \"A sorte se lança no regaço, mas do Senhor procede toda a determinação\" (Pv 16:33). E o nome dessa sorte pagã ficou: \"Por isso àqueles dias chamam Purim, do nome Pur\" (Et 9:26)." },
  "dez-mil-talentos-de-prata-de-hama": {
    title: "Os dez mil talentos de prata de Hamã",
    subtitle: "Et 3:9 — o preço oferecido por um povo inteiro",
    text: "\"Se bem parecer ao rei, decrete-se que os matem; e eu porei nas mãos dos que fizerem a obra dez mil talentos de prata, para que entrem nos tesouros do rei\" (Et 3:9). É uma fortuna de estado — proposta como se fosse contrato de obra, com a expressão fria \"os que fizerem a obra\". A resposta do rei é entregar o anel e devolver o dinheiro no mesmo gesto: \"Essa prata te é dada como também esse povo, para fazeres dele o que bem parecer aos teus olhos\" (Et 3:11). O valor volta uma vez no livro, na boca de Mardoqueu, quando ele manda a Ester pelo eunuco Hatá \"a soma exata do dinheiro, que Hamã dissera que daria para os tesouros do rei, pelos judeus, para destruí-los\" (Et 4:7). Ele fez questão de que ela soubesse o número: o povo dela tinha preço, e o preço estava escrito." },
  "decreto-selado-com-o-anel-do-rei": {
    title: "O decreto de Hamã, selado com o anel do rei",
    subtitle: "Et 3:12-13 — a ordem de destruir, matar e fazer perecer num só dia",
    text: "\"Então chamaram os escrivães do rei no primeiro mês, no dia treze do mesmo e, conforme a tudo quanto Hamã mandou, se escreveu aos príncipes do rei, e aos governadores que havia sobre cada província, e aos líderes, de cada povo; a cada província segundo a sua escrita, e a cada povo segundo a sua língua; em nome do rei Assuero se escreveu, e com o anel do rei se selou\" (Et 3:12). O conteúdo vem no versículo seguinte, sem eufemismo: \"para que destruíssem, matassem, e fizessem perecer a todos os judeus, desde o jovem até ao velho, crianças e mulheres, em um mesmo dia, a treze do duodécimo mês (que é o mês de Adar), e que saqueassem os seus bens\" (Et 3:13). Um genocídio redigido com todo o esmero de forma, traduzido com cuidado filológico para cada povo poder lê-lo na sua língua. O selo é o anel que o rei tirou do dedo sem perguntar de quem se tratava (Et 3:10) — e que voltará à sua mão em 8:2." },
  "rol-das-provincias-do-reino-de-assuero": {
    title: "O rol das províncias do reino de Assuero",
    subtitle: "Et 3:6 — o mapa sobre o qual Hamã mediu o tamanho do seu ódio",
    text: "\"Porém teve como pouco, nos seus propósitos, o pôr as mãos só em Mardoqueu (porque lhe haviam declarado de que povo era Mardoqueu); Hamã, pois, procurou destruir a todos os judeus, o povo de Mardoqueu, que havia em todo o reino de Assuero\" (Et 3:6). O rolo é a lista administrativa das cento e vinte e sete províncias que o livro nomeia no primeiro versículo, \"desde a India até a Etiópia\" (Et 1:1), e é sobre ela que a conta é feita: um homem não se curvou, e a resposta passa a ser um povo inteiro em todo o território do império. O mesmo rol serve depois às duas expedições de correios — a de 3:12-13, com a ordem de destruir, e a de 8:9-10, com a licença de defender a vida —, e a mesma dispersão que Hamã apresentou ao rei como ameaça (\"Existe espalhado e dividido entre os povos em todas as províncias do teu reino um povo\", Et 3:8) é o que, no último versículo, é simplesmente o mapa de uma comunidade viva e estimada (Et 10:3)." },
  "copia-da-lei-escrita-publicada-em-susa": {
    title: "A cópia da lei escrita publicada em Susã",
    subtitle: "Et 4:8 — o papel que Mardoqueu mandou a Ester pelas mãos de Hatá",
    text: "\"Também lhe deu a cópia da lei escrita, que se publicara em Susã, para os destruir, para que a mostrasse a Ester, e a fizesse saber; e para lhe ordenar que fosse ter com o rei, e lhe pedisse e suplicasse na sua presença pelo seu povo\" (Et 4:8). Mardoqueu não manda um recado emocionado: manda o documento. Junto com ele vai \"a soma exata do dinheiro, que Hamã dissera que daria para os tesouros do rei\" (Et 4:7) — o preço e a sentença, por escrito, atravessando a praça da cidade nas mãos de um eunuco. Dentro do palácio, a rainha sabia da tristeza de Mardoqueu por terceiros (Et 4:4); a partir deste papel ela sabe o teor da lei, a data e o valor. É a leitura desta cópia que produz a resposta de 4:16 — \"se perecer, pereci\"." },
  "roupas-que-ester-mandou-a-mardoqueu": {
    title: "As roupas que Ester mandou e Mardoqueu não aceitou",
    subtitle: "Et 4:4 — a primeira reação da rainha, e a recusa que a corrigiu",
    text: "\"Então vieram as servas de Ester, e os seus camareiros, e fizeram-na saber, do que a rainha muito se doeu; e mandou roupas para vestir a Mardoqueu, e tirar-lhe o pano de saco; porém ele não as aceitou\" (Et 4:4). É um gesto sincero e insuficiente, e o livro o registra sem nenhum comentário: a rainha, que ainda não sabe o teor do decreto, tenta resolver o problema visível — o velho está de saco na praça, e saco não pode passar da porta do rei (Et 4:2). Mardoqueu devolve as roupas. O luto não é para ser vestido por cima, e o problema não era a aparência dele. Só depois da recusa é que Ester manda Hatá perguntar \"que era aquilo, e porquê\" (Et 4:5) — e a história começa a andar." },
  "mesa-vazia-do-jejum-de-tres-dias": {
    title: "A mesa vazia dos três dias de jejum",
    subtitle: "Et 4:16 — a única cena religiosa do livro, e ela não tem altar nenhum",
    text: "\"Vai, ajunta a todos os judeus que se acharem em Susã, e jejuai por mim, e não comais nem bebais por três dias, nem de dia nem de noite, e eu e as minhas servas também assim jejuaremos\" (Et 4:16). É o momento mais próximo de culto em todo o livro, e é preciso notar o que NÃO está escrito nele: não há altar, não há sacerdote, não há oração citada, não há um nome invocado. Há três dias e três noites sem comer nem beber, numa cidade pagã, por uma mulher que ia entrar sem ser chamada. O jejum aparece de novo no último capítulo da história, quando as cartas do Purim confirmam a memória dos dias \"acerca do jejum e do seu clamor\" (Et 9:31) — a comunidade fez questão de que a festa lembrasse também a mesa vazia que veio antes dela." },
  "riquezas-e-glorias-de-hama": {
    title: "As riquezas e a glória que Hamã contou em casa",
    subtitle: "Et 5:11 — o inventário da vaidade, na noite em que a forca foi encomendada",
    text: "\"E contou-lhes Hamã a glória das suas riquezas, a multidão de seus filhos, e tudo em que o rei o tinha engrandecido, e como o tinha exaltado sobre os príncipes e servos do rei\" (Et 5:11). Ele reúne a mulher e os amigos em casa só para isso: listar em voz alta o que tem. E a lista termina com uma frase que anula tudo: \"Porém tudo isto não me satisfaz, enquanto eu vir o judeu Mardoqueu assentado à porta do rei\" (Et 5:13). Riquezas, filhos e cargo — os três itens do inventário desaparecem em quatro capítulos: a casa passa a Ester (Et 8:1), o anel passa a Mardoqueu (Et 8:2), e os dez filhos caem no dia treze de Adar (Et 9:10). O livro desmonta o inventário peça por peça e não atribui isso a ninguém." },
  "livro-de-registro-das-cronicas": {
    title: "O livro de registro das crônicas, trazido na noite sem sono",
    subtitle: "Et 6:1-2 — o rolo que se abriu na página certa na madrugada certa",
    text: "\"Naquela mesma noite fugiu o sono do rei; então mandou trazer o livro de registro das crônicas, as quais se leram diante do rei\" (Et 6:1). É o eixo do livro inteiro, e é feito de nada: um insone manda ler anais administrativos para passar a madrugada. \"E achou-se escrito que Mardoqueu tinha denunciado Bigtã e Teres, dois dos camareiros do rei, da guarda da porta, que tinham procurado lançar mão do rei Assuero\" (Et 6:2) — justamente a linha anotada em 2:23 e nunca paga. E, no minuto seguinte, quem está no pátio exterior é o homem que veio pedir a forca de Mardoqueu (Et 6:4). O texto não diz por que o sono fugiu, não diz por que o rolo se abriu ali, não diz por que Hamã chegou naquela hora. Registra as três coisas em quatro versículos e cala sobre todas." },
  "coroa-real-na-cabeca-do-cavalo": {
    title: "A coroa real posta na cabeça do cavalo",
    subtitle: "Et 6:8-11 — o detalhe que Hamã inventou para si e teve de pôr em outro",
    text: "\"Tragam a veste real que o rei costuma vestir, como também o cavalo em que o rei costuma andar montado, e ponha-se-lhe a coroa real na sua cabeça\" (Et 6:8). Hamã, convencido de que a honra seria dele — \"De quem se agradaria o rei para lhe fazer honra mais do que a mim?\" (Et 6:6) —, detalha a cerimônia dos seus sonhos: veste do rei, cavalo do rei, coroa no animal, um príncipe dos mais nobres conduzindo e um pregão pelas ruas. O rei aceita tudo e troca um nome: \"faze assim para com o judeu Mardoqueu, que está assentado à porta do rei; e coisa nenhuma omitas de tudo quanto disseste\" (Et 6:10). Coisa nenhuma omitas — nem a coroa. E o autor do plano é quem puxa as rédeas: \"e o levou a cavalo pelas ruas da cidade, e apregoou diante dele: Assim se fará ao homem a quem o rei deseja honrar!\" (Et 6:11)." },
  "fortaleza-de-susa": {
    title: "A fortaleza de Susã",
    subtitle: "Et 1:2 • 3:15 • 9:6 — a cidadela em que o livro inteiro se passa",
    text: "\"assentando-se o rei Assuero no trono do seu reino, que estava na fortaleza de Susã\" (Et 1:2). Susã é a capital de inverno do império persa, e a \"fortaleza\" é a acrópole murada onde ficam o palácio, os pátios, a casa das mulheres e a porta do rei — um recinto separado da cidade baixa. Essa distinção é o que torna legíveis várias cenas: a lei se proclama na fortaleza enquanto \"a cidade de Susã estava confusa\" (Et 3:15); o segundo decreto é publicado ali (Et 8:14); e o dia treze de Adar é contado em duas partes, os quinhentos mortos \"na fortaleza de Susã\" (Et 9:6) e o dia extra pedido por Ester para os judeus \"que se acham em Susã\" (Et 9:13-15). É também onde Neemias servia como copeiro quando ouviu as notícias de Jerusalém (Ne 1:1)." },
  "leito-do-banquete-do-vinho": {
    title: "O leito do banquete do vinho",
    subtitle: "Et 7:8 — o divã em que Hamã caiu prostrado e perdeu a vida",
    text: "\"Tornando, pois, o rei do jardim do palácio à casa do banquete do vinho, Hamã tinha caído prostrado sobre o leito em que estava Ester. Então disse o rei: Porventura quereria ele também forçar a rainha perante mim nesta casa? Saindo esta palavra da boca do rei, cobriram o rosto de Hamã\" (Et 7:8). O móvel decide o capítulo. Hamã ficou para trás quando o rei saiu furioso, e ficou por um motivo compreensível — \"Hamã se pôs em pé, para rogar à rainha Ester pela sua vida; porque viu que já o mal lhe estava determinado pelo rei\" (Et 7:7) —, mas ao suplicar cai sobre o divã da rainha, e é essa a cena que o rei encontra da porta. O homem diante de quem todos se prostravam por ordem real (Et 3:2) morre por ter-se prostrado no lugar errado." },
  "cartas-seladas-com-o-anel-do-rei": {
    title: "As cartas da segunda lei, seladas com o anel do rei",
    subtitle: "Et 8:8-10 — o que não se pode revogar e por isso teve de ser escrito outra vez",
    text: "\"Escrevei, pois, aos judeus, como parecer bem aos vossos olhos, em nome do rei, e selai-o com o anel do rei; porque o documento que se escreve em nome do rei, e que se sela com o anel do rei, não se pode revogar\" (Et 8:8). É a lei persa fechando o cerco pela segunda vez no livro: como não se apaga a carta de Hamã, escreve-se a contrária. O que a nova concede não é vingança gratuita: \"Nelas o rei concedia aos judeus, que havia em cada cidade, que se reunissem, e se dispusessem para defenderem as suas vidas\" (Et 8:11), no mesmo dia treze de Adar tirado pelo pur. E o selo é o mesmo objeto de 3:10 — o anel que condenou o povo, agora na mão de um judeu: \"E tirou o rei o seu anel, que tinha tomado de Hamã, e o deu a Mardoqueu\" (Et 8:2)." },
  "copia-da-carta-publicada-em-todas-as-provincias": {
    title: "A cópia da segunda carta, publicada em todas as províncias",
    subtitle: "Et 8:13-14 — o mesmo muro em que se afixara a sentença de morte",
    text: "\"E uma cópia da carta seria divulgada como decreto em todas as províncias, e publicada entre todos os povos, para que os judeus estivessem preparados para aquele dia, para se vingarem dos seus inimigos\" (Et 8:13). A frase é a gêmea de 3:14 — \"Uma cópia do despacho que determinou a divulgação da lei em cada província, foi enviada a todos os povos, para que estivessem preparados para aquele dia\" —, palavra por palavra, com um sujeito trocado. O mesmo formato, o mesmo prazo, o mesmo muro da praça: só muda quem está preparado. \"Os correios, sobre ginetes velozes, saíram apressuradamente, impelidos pela palavra do rei; e esta ordem foi publicada na fortaleza de Susã\" (Et 8:14) — e a expressão \"impelidos pela palavra do rei\" também é copiada de 3:15." },
  "grande-coroa-de-ouro-de-mardoqueu": {
    title: "A grande coroa de ouro de Mardoqueu",
    subtitle: "Et 8:15 — a saída da presença do rei, com veste azul-celeste e capa de linho e púrpura",
    text: "\"Então Mardoqueu saiu da presença do rei com veste real azul-celeste e branca, como também com uma grande coroa de ouro, e com uma capa de linho fino e púrpura, e a cidade de Susã exultou e se alegrou\" (Et 8:15). As cores são exatamente as das tapeçarias do primeiro capítulo — \"pano branco, verde, e azul celeste, pendentes de cordões de linho fino e púrpura\" (Et 1:6) —, e é a mesma decoração de um império que agora veste um judeu do cativeiro de Jeconias. Não é a coroa real da Pérsia, que está na cabeça de Ester (Et 2:17): é uma insígnia de cargo, o distintivo do segundo homem do reino (Et 10:3). Quem sai assim à rua é o mesmo que atravessou essa cidade em saco e cinza, clamando \"com grande e amargo clamor\" (Et 4:1), quatro capítulos antes." },
  "despojo-a-que-nao-estenderam-a-mao": {
    title: "O despojo a que não estenderam a sua mão",
    subtitle: "Et 9:10, 15, 16 — a frase que o capítulo repete três vezes",
    text: "\"Os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus, mataram, porém ao despojo não estenderam a sua mão\" (Et 9:10); e outra vez em Susã no dia catorze (Et 9:15); e outra vez nas províncias (Et 9:16). Três repetições numa página só, e é a coisa que este capítulo mais quer que se note. Havia autorização: o decreto de Hamã mandava saquear os bens dos judeus (Et 3:13) e o de Mardoqueu permitia o mesmo contra os inimigos deles (Et 8:11). Não pegaram nada — não era saque, era sobrevivência. E o eco é exato: quatrocentos anos antes, um rei benjamita mandado destruir Amaleque poupou o rei Agague e \"o melhor das ovelhas e das vacas\" (1Sm 15:9), e ouviu de Samuel a acusação \"antes te lançaste ao despojo, e fizeste o que parecia mau aos olhos do Senhor\" (1Sm 15:19). Agora um benjamita da casa de Quis (Et 2:5) acaba com a casa do agagita (Et 3:1) e não toca em nada. O livro nunca faz essa conta em voz alta." },
  "conta-dos-mortos-na-fortaleza-de-susa": {
    title: "A conta dos mortos na fortaleza de Susã",
    subtitle: "Et 9:11-12 — o relatório lido ao rei no fim do dia treze",
    text: "\"No mesmo dia foi comunicado ao rei o número dos mortos na fortaleza de Susã\" (Et 9:11). É assim que Assuero aparece pela última vez em ação: recebendo uma estatística. E a reação dele é de administrador, com uma extrapolação feita em voz alta que só ele acharia natural: \"Na fortaleza de Susã os judeus mataram e destruíram quinhentos homens, e os dez filhos de Hamã; nas mais províncias do rei que teriam feito? Qual é, pois, a tua petição? E dar-se-te-á\" (Et 9:12). O livro dá os números sem comemorar nenhum — quinhentos no dia treze em Susã, trezentos no dia catorze, setenta e cinco mil nas províncias (Et 9:6, 15, 16) — e emenda em cada um deles a mesma ressalva sobre o que não foi tomado. O que se celebra depois não é a matança: é o descanso do dia seguinte (Et 9:17-18)." },
  "carta-de-purim-de-mardoqueu-e-da-rainha-ester": {
    title: "A carta do Purim, escrita por Mardoqueu e pela rainha Ester",
    subtitle: "Et 9:20-32 — a festa que tomou o nome da sorte lançada por Hamã",
    text: "\"E Mardoqueu escreveu estas coisas, e enviou cartas a todos os judeus que se achavam em todas as províncias do rei Assuero, aos de perto, e aos de longe, ordenando-lhes que guardassem o dia catorze do mês de Adar, e o dia quinze do mesmo, todos os anos\" (Et 9:20-21). A razão é dada em uma linha: \"o mês que se lhes mudou de tristeza em alegria, e de luto em dia de festa\" (Et 9:22), e a forma da festa é banquete, presentes uns aos outros e dádivas aos pobres. Depois vem a segunda carta, com o nome dela primeiro: \"Então a rainha Ester, filha de Abiail, e Mardoqueu, o judeu, escreveram com toda autoridade uma segunda vez, para confirmar a carta a respeito de Purim\" (Et 9:29), enviada \"com palavras de paz e verdade\" (Et 9:30) e lembrando também \"acerca do jejum e do seu clamor\" (Et 9:31). O nome da festa vem da palavra persa para a sorte que Hamã lançou a fim de escolher o dia de matá-los (Et 3:7; 9:26). O livro registra a ironia e não a explica. E fecha: \"E o mandado de Ester estabeleceu os sucessos daquele Purim; e escreveu-se no livro\" (Et 9:32)." },
  "livro-das-cronicas-dos-reis-da-media-e-da-persia": {
    title: "O livro das crônicas dos reis da Média e da Pérsia",
    subtitle: "Et 10:2 — o arquivo a que o livro remete o leitor no último versículo",
    text: "\"E todos os atos do seu poder e do seu valor, e o relato da grandeza de Mardoqueu, a quem o rei exaltou, porventura não estão escritos no livro das crônicas dos reis da Média e da Pérsia?\" (Et 10:2). A fórmula é a mesma com que os livros dos Reis encerram cada reinado de Israel e de Judá, aplicada aqui a um monarca pagão — e o nome que ela carrega ao lado do rei é o de um judeu do cativeiro. Vale lembrar o que um arquivo persa já fez neste mesmo livro: em 2:23 um escriba anotou uma linha esquecida; em 6:1 essa linha foi lida por acaso numa noite de insônia; e por causa dela um povo inteiro não morreu. O livro termina mandando o leitor consultar as crônicas do império — e, sem dizê-lo, deixando o leitor lembrado de que já foi uma página dessas que virou a história." },
};
