// GERADO por scripts/split-stage-info.mjs — não edite à mão o cabeçalho.
// Fichas de OBJETO-MARCO (por `tag`) das cenas de ezra.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const TAGS: Record<string, StageInfo> = {
  "vasos-da-casa-do-senhor-levados-a-babilonia": {
    title: "Os vasos da casa do SENHOR postos no templo de Nabucodonosor em Babilônia",
    subtitle: "2Cr 36:7 • a prateleira de um templo estrangeiro, com o ouro de Jerusalém nela",
    text: "\"Também alguns dos vasos da casa do SENHOR levou Nabucodonosor a babilônia, e pô-los no seu templo em babilônia\" (2Cr 36:7). No mundo antigo, pôr no templo do seu deus os utensílios do deus vencido era publicar a vitória: o objeto na prateleira dizia quem mandava no céu. Foi o que os filisteus tentaram com a arca, na casa de Dagom — e não deu certo (1Sm 5:2-4). Aqui deu, aparentemente, por setenta anos. Estes vasos reaparecem duas vezes na Escritura, e as duas fecham a conta. A primeira é numa festa: \"Havendo Belsazar provado o vinho, mandou trazer os vasos de ouro e de prata, que Nabucodonosor, seu pai, tinha tirado do templo que estava em Jerusalém, para que bebessem neles o rei, os seus príncipes, as suas mulheres e concubinas\" (Dn 5:2) — e naquela mesma noite apareceu a mão escrevendo na parede e o rei foi morto. A segunda é numa lista de devolução: Ciro \"tirou os utensílios da casa do Senhor, que Nabucodonosor tinha trazido de Jerusalém, e que tinha posto na casa de seus deuses\" (Ed 1:7), cinco mil e quatrocentas peças contadas uma a uma.",
  },
  "pregao-de-ciro-rei-da-persia": {
    title: "O pregão que Ciro fez passar por todo o seu reino, e também por escrito",
    subtitle: "2Cr 36:22 • a sala do rei da Pérsia, no primeiro ano do seu reinado",
    text: "\"Porém, no primeiro ano de Ciro, rei da Pérsia (para que se cumprisse a palavra do Senhor pela boca de Jeremias), despertou o Senhor o espírito de Ciro, rei da Pérsia, o qual fez passar pregão por todo o seu reino, como também por escrito\" (2Cr 36:22). O livro que começou em Adão acaba num decreto persa, e o verbo que o produz é de Deus: quem desperta o espírito do rei é o SENHOR. Isaías tinha nomeado este homem quase dois séculos antes de ele nascer, e com títulos que espantam — \"Que digo de Ciro: É meu pastor, e cumprirá tudo o que me apraz\" (Is 44:28) e \"Assim diz o SENHOR ao seu ungido, a Ciro, a quem tomo pela mão direita\" (Is 45:1), com a ressalva \"ainda que não me conhecesses\" (Is 45:4). O detalhe \"como também por escrito\" é administração persa pura: o pregão corre pela voz dos arautos e ao mesmo tempo sai em cópia selada para os arquivos das províncias — e foi justamente uma dessas cópias, achada depois em Ecbátana, que salvou a obra do templo quando os adversários tentaram embargá-la (Ed 6:1-5).",
  },
  "casa-a-edificar-em-jerusalem": {
    title: "A casa que Ciro foi encarregado de edificar em Jerusalém, que está em Judá",
    subtitle: "2Cr 36:23 • o último quadro do livro, com a ordem de subir",
    text: "\"Assim diz Ciro, rei da Pérsia: O Senhor Deus dos céus me deu todos os reinos da terra, e me encarregou de lhe edificar uma casa em Jerusalém, que está em Judá. Quem há entre vós, de todo o seu povo, o Senhor seu Deus seja com ele, e suba\" (2Cr 36:23). São as últimas palavras das Crônicas e, na ordem hebraica dos livros, as últimas do Antigo Testamento inteiro — e são uma ordem de subir. Quatro versículos antes a casa estava a arder; agora um rei estrangeiro se diz encarregado de reedificá-la. O Cronista corta o decreto no meio: em Esdras a frase continua — \"e suba a Jerusalém, que está em Judá, e edifique a casa do Senhor Deus de Israel\" (Ed 1:3) —, mas aqui ele para em \"e suba\", deixando o livro aberto no imperativo. Para a comunidade que lia isto de volta na terra, reconstruindo um templo menor que o de Salomão e chorando ao ver os alicerces (Ed 3:12), a mensagem era a régua inteira do livro: a casa de Deus não depende de exército nem de dinastia, e a palavra que anunciou setenta anos foi a mesma que os contou até o fim.",
  },
  "prata-ouro-e-coisas-preciosas-dos-vizinhos": {
    title: "A prata, o ouro, os bens e as coisas preciosas com que os vizinhos firmaram as mãos dos que subiam",
    subtitle: "Ed 1:4,6 • a bacia posta na soleira, na rua de quem fica",
    text: "O decreto de Ciro pensa em duas pessoas ao mesmo tempo: a que sobe e a que não sobe. \"E todo aquele que ficar atrás em algum lugar em que andar peregrinando, os homens do seu lugar o ajudarão com prata, com ouro, com bens, e com gados, além das dádivas voluntárias para a casa de Deus\" (Ed 1:4) — e o versículo seguinte diz que foi cumprido: \"E todos os que habitavam nos arredores lhes firmaram as mãos com vasos de prata, com ouro, com bens e com gado, e com coisas preciosas; além de tudo o que voluntariamente se deu\" (Ed 1:6). A expressão \"firmaram as mãos\" é a que dá o tom: no capítulo 4 as mesmas mãos serão DEBILITADAS pelo povo da terra (Ed 4:4), e no fim do capítulo 6 será Deus a fortalecê-las de novo (Ed 6:22). É também a repetição de um gesto antigo: na saída do Egito, os filhos de Israel \"pediram aos egípcios jóias de prata, e jóias de ouro, e roupas\" e \"o Senhor deu ao povo graça aos olhos dos egípcios\" (Êx 12:35-36). Dois êxodos, o mesmo detalhe — quem sai leva na mão o que os vizinhos deram.",
  },
  "idolos-da-casa-dos-deuses-de-babilonia": {
    title: "O ídolo fundido da casa dos deuses onde Nabucodonosor guardou os utensílios de Jerusalém",
    subtitle: "Ed 1:7 • o santuário babilônio de onde os vasos saíram por ordem do próprio rei",
    text: "\"Também o rei Ciro tirou os utensílios da casa do Senhor, que Nabucodonosor tinha trazido de Jerusalém, e que tinha posto na casa de seus deuses\" (Ed 1:7). Pôr no templo do seu deus os objetos do deus vencido era, no mundo antigo, publicar quem mandava no céu — foi o que os filisteus tentaram com a arca na casa de Dagom, e não deu certo (1Sm 5:2-4). Aqui pareceu dar, durante setenta anos, e o ídolo desta cena é a testemunha calada de todo esse tempo. Belsazar ainda mandaria trazer aquelas peças para uma festa: \"os vasos de ouro e de prata, que Nabucodonosor, seu pai, tinha tirado do templo que estava em Jerusalém, para que bebessem neles o rei, os seus príncipes, as suas mulheres e concubinas\" (Dn 5:2) — e naquela mesma noite apareceu a mão a escrever na parede. Isaías tinha desenhado a queda destes deuses como uma mudança atrapalhada: \"Bel está abatido, Nebo se encurvou, os seus ídolos são postos sobre os animais e sobre as feras; as cargas dos vossos fardos são canseiras para as feras já cansadas\" (Is 46:1). O ídolo tem de ser carregado; o Deus de Israel é quem carrega.",
  },
  "trinta-bacias-de-ouro-e-mil-de-prata": {
    title: "As travessas e as bacias de ouro e de prata contadas peça por peça na câmara do tesouro",
    subtitle: "Ed 1:9-10 • o inventário sobre a mesa alta, à luz do candeeiro",
    text: "\"E este é o número deles: trinta travessas de ouro, mil travessas de prata, vinte e nove facas, Trinta bacias de ouro, mais outras quatrocentas e dez bacias de prata, e mil outros utensílios\" (Ed 1:9-10). O texto podia ter dito \"os utensílios\" e seguido em frente; preferiu copiar a folha do escrivão inteira, com as vinte e nove facas e tudo. É a assinatura do livro de Esdras: um povo que perdeu o país aprende a guardar as contas, e a exatidão é uma forma de fé. Estas peças foram feitas para o culto — travessa, bacia, faca são utensílios de sacrifício —, passaram setenta anos numa prateleira estrangeira e voltam ainda antes de existir um altar onde usá-las. Voltam, além disso, pesadas por mão persa: \"pela mão de Mitredate, o tesoureiro, que os entregou contados a Sesbazar, príncipe de Judá\" (Ed 1:8). Nada de heroico, nada de milagroso — só um número escrito duas vezes para que ninguém o pudesse discutir depois. E foi por causa dessa mania de escrever que, cinco capítulos adiante, um rolo achado em Acmeta salvou a obra (Ed 6:2).",
  },
  "conta-dos-utensilios-entregues-a-sesbazar": {
    title: "A folha da conta dos utensílios entregues, contados, a Sesbazar",
    subtitle: "Ed 1:8-11 • o rolo aberto ao lado da mesa da contagem",
    text: "\"Estes tirou Ciro, rei da Pérsia, pela mão de Mitredate, o tesoureiro, que os entregou contados a Sesbazar, príncipe de Judá\" (Ed 1:8). A palavra decisiva é CONTADOS: a devolução não é um gesto simpático, é um ato administrativo com recibo, e o recibo está aqui. O rolo desta cena registra travessas, facas, bacias e \"mil outros utensílios\" (Ed 1:10), e fecha com o total: \"Todos os utensílios de ouro e de prata foram cinco mil e quatrocentos\" (Ed 1:11). Uma folha destas protege quem carrega e quem recebe — e é por isso que a mesma prática se repete quando Esdras subir com a segunda caravana, oitenta anos depois: pesa a prata e o ouro diante dos sacerdotes, entrega por conta e por peso e manda pesar outra vez na chegada, para que nada se perdesse pelo caminho (Ed 8:24-30). Num povo que voltava com fama de rebelde, a papelada em ordem era defesa. Este pequeno rolo é o antepassado direto do rolo de Acmeta: em Esdras, quem escreve sobrevive.",
  },
  "cinco-mil-e-quatrocentos-utensilios-de-ouro-e-prata": {
    title: "Os cinco mil e quatrocentos utensílios de ouro e de prata que subiram com os do cativeiro",
    subtitle: "Ed 1:11 • as caixas amarradas no lombo dos jumentos, na estrada de Jerusalém",
    text: "\"Todos os utensílios de ouro e de prata foram cinco mil e quatrocentos; todos estes levou Sesbazar, quando os do cativeiro subiram de babilônia para Jerusalém\" (Ed 1:11). O primeiro capítulo do livro acaba com um número em movimento: cinco mil e quatrocentas peças a atravessar o deserto num comboio de jumentos. Estas mesmas peças tinham saído de Jerusalém em três levas de saque, e o Cronista marcou os degraus — primeiro \"alguns dos vasos\" (2Cr 36:7), depois \"os mais preciosos vasos\" (2Cr 36:10), por fim \"todos os vasos da casa de Deus, grandes e pequenos\" (2Cr 36:18). Falsos profetas tinham prometido em Jerusalém que voltariam em dois anos, e Jeremias desmentiu-os, dizendo que os que restavam também iriam, e que só voltariam \"até o dia em que eu os visitarei\" (Jr 27:22). Voltaram — setenta anos depois, contados um a um, antes de haver templo, antes de haver altar, antes de haver parede. O ouro chegou primeiro do que a casa.",
  },
  "jerusalem-para-onde-subiram-os-do-cativeiro": {
    title: "Jerusalém no alto do horizonte, o destino da primeira caravana do regresso",
    subtitle: "Ed 1:11 • a cidade ainda pequena ao fim da estrada de Babilônia",
    text: "\"todos estes levou Sesbazar, quando os do cativeiro subiram de babilônia para Jerusalém\" (Ed 1:11). O verbo é sempre SUBIR — sobe-se a Jerusalém venha-se de onde se vier —, e é o verbo do pregão: \"Quem há entre vós, de todo o seu povo, seja seu Deus com ele, e suba a Jerusalém, que está em Judá\" (Ed 1:3). A cidade que está no fim desta estrada não é a de Salomão: é um monte de entulho com muros derrubados, sem templo, sem rei e sem porta. A maior parte de quem caminha para ela nunca a viu, porque nasceu junto aos rios da Babilônia — e é essa gente que cantava \"Se eu me esquecer de ti, ó Jerusalém, esqueça-se a minha direita da sua destreza\" (Sl 137:5) sem nunca lá ter posto os pés. Quando finalmente chegam, o salmo das subidas ganha o seu sentido mais literal: \"Alegrei-me quando me disseram: Vamos á casa do SENHOR. Os nossos pés estão dentro das tuas portas, ó Jerusalém\" (Sl 122:1-2). Nesta cena a cidade é só uma silhueta ao longe, e vale por toda a viagem.",
  },
  "arrolamento-dos-que-subiram-do-cativeiro": {
    title: "O rolo do arrolamento dos filhos da província que subiram do cativeiro",
    subtitle: "Ed 2:1-2,62 • o rolo aberto sobre o caixote, e depois na mesa do escriba",
    text: "\"Estes são os filhos da província, que subiram do cativeiro, dentre os exilados, que Nabucodonosor, rei de babilônia, tinha transportado a babilônia, e tornaram a Jerusalém e a Judá, cada um para a sua cidade\" (Ed 2:1). O rolo desta cena é o documento mais importante que este povo possui: sem exército, sem rei e sem fronteira reconhecida, o que prova que Israel existe é uma lista de nomes. Ela abre pelos onze cabeças — \"Zorobabel, Jesua, Neemias, Seraías, Reelaías, Mardoqueu, Bilsã, Mizpar, Bigvai, Reum e Baaná\" (Ed 2:2) —, arrola casas paternas, depois cidades, depois ofícios, e fecha na soma. E tem dentes: quem não aparece nela perde direitos. Os que subiram de Tel-Melá \"não puderam provar que as suas famílias e a sua linhagem eram de Israel\" (Ed 2:59), e os sacerdotes que procuraram o seu registro \"mas não se acharam nelas\" foram excluídos do sacerdócio (Ed 2:62). É por isso que o mesmo rolo é recopiado quase inteiro por Neemias meio século depois (Ne 7:6-73): um povo pequeno guarda a sua certidão a sete chaves.",
  },
  "posto-dos-porteiros-da-casa-de-deus": {
    title: "A soleira dos porteiros — Salum, Ater, Talmom, Acube, Hatita e Sobai, cento e trinta e nove ao todo",
    subtitle: "Ed 2:42 • a folha da porta encostada ao portal de uma casa que ainda não existe",
    text: "\"Os filhos dos porteiros: os filhos de Salum, os filhos de Ater, os filhos de Talmom, os filhos de Acube, os filhos de Hatita, os filhos de Sobai; ao todo, cento e trinta e nove\" (Ed 2:42). Seis casas e cento e trinta e nove homens para guardar portas de um templo que ainda não tem uma pedra assentada — é o ofício mais estranho desta lista e o mais cheio de fé: apresentam-se ao serviço antes de existir a soleira. A instituição vem de Davi, que sorteara as bandas porta por porta, \"E caiu a sorte do oriente a Selemias; e lançou-se a sorte por seu filho Zacarias, conselheiro entendido, e saiu-lhe a do norte\" (1Cr 26:14), e o posto era levado a sério a ponto de o Cronista registrar que, no tempo de Josias, \"os porteiros a cada porta; não necessitaram de se desviarem do seu ministério\" (2Cr 35:15). O porteiro não decide quem é santo: decide quem entra e o que entra — e o salmo escreveu-lhe o elogio: \"Preferiria estar à porta da casa do meu Deus, a habitar nas tendas dos ímpios\" (Sl 84:10).",
  },
  "registro-das-genealogias-que-nao-se-achou": {
    title: "O registro das genealogias em que os filhos dos sacerdotes procuraram o seu nome e não o acharam",
    subtitle: "Ed 2:61-63 • o rolo aberto sob o candeeiro, e o dedo do escriba parado no vazio",
    text: "\"E dos filhos dos sacerdotes: os filhos de Habaías, os filhos de Coz, os filhos de Barzilai, que tomou mulher das filhas de Barzilai, o gileadita, e que foi chamado do seu nome. Estes procuraram o seu registro entre os que estavam arrolados nas genealogias, mas não se acharam nelas; assim, por imundos, foram excluídos do sacerdócio\" (Ed 2:61-62). O caso de Barzilai é quase um aviso: um sacerdote casou com a filha do rico gileadita que sustentara Davi em Maanaim (2Sm 19:32) e passou a ser chamado pelo nome do sogro — e é o nome do pai que agora lhe falta na linha. A sentença que se segue é a mais delicada do livro porque não fecha: \"E o governador lhes disse que não comessem das coisas consagradas, até que houvesse sacerdote com Urim e com Tumim\" (Ed 2:63). Não é \"não\", é \"ainda não\": o peitoral do juízo, com \"Urim e Tumim\" sobre o coração de Arão (Êx 28:30), não voltou do exílio, e a Escritura nunca diz que voltou. Ficam à espera de um sacerdote que possa decidir — e essa espera atravessa os quatro séculos que separam este rolo do Evangelho.",
  },
  "quarenta-e-dois-mil-trezentos-e-sessenta": {
    title: "A soma de toda a congregação junta: quarenta e dois mil trezentos e sessenta",
    subtitle: "Ed 2:64 • o rolo do número lido em voz alta do alto do degrau",
    text: "\"Toda esta congregação junta foi de quarenta e dois mil trezentos e sessenta\" (Ed 2:64), \"Afora os seus servos e as suas servas, que foram sete mil trezentos e trinta e sete; também tinha duzentos cantores e cantoras\" (Ed 2:65). É pouco, e o livro não disfarça: um povo que saíra do Egito com seiscentos mil homens de pé volta do exílio com menos de cinquenta mil almas ao todo. Curiosamente, a soma das parcelas da lista não fecha exatamente com este total — nem em Esdras nem em Neemias, que repete o mesmo número final, \"Toda esta congregação junta foi de quarenta e dois mil, trezentos e sessenta\" (Ne 7:66) —, e o autor deixa a diferença lá, sem a corrigir: copiou o documento como estava. O número é pequeno para um império e grande para um vale em ruínas. Foi para esta gente, e não para uma nação imaginária, que Zacarias perguntou: \"quem despreza o dia das coisas pequenas?\" (Zc 4:10).",
  },
  "setecentos-e-trinta-e-seis-cavalos": {
    title: "Os setecentos e trinta e seis cavalos e os duzentos e quarenta e cinco mulos da caravana",
    subtitle: "Ed 2:66 • o descampado onde o gado do regresso é apartado e contado",
    text: "\"Os seus cavalos, setecentos e trinta e seis; os seus mulos, duzentos e quarenta e cinco\" (Ed 2:66). Setecentos e trinta e seis cavalos para quarenta e dois mil pessoas é uma proporção que diz tudo: isto não é um exército, é uma mudança. Não há carros de guerra na lista, não há armas, não há cavalaria — há animais de sela e de carga para chefes de casa e para o transporte de fardos. E é a maneira certa de voltar, para um povo que aprendeu à sua custa onde não se deve pôr a confiança: \"Ai dos que descem ao Egito a buscar socorro, e se estribam em cavalos; e têm confiança em carros, porque são muitos; e nos cavaleiros, porque são poderosíssimos; e não atentam para o Santo de Israel\" (Is 31:1). A caravana que sobe de Babilônia atravessa o deserto sem escolta militar nenhuma — e Esdras, na segunda leva, explicaria por que se envergonhou de pedir uma ao rei: \"tive vergonha de pedir ao rei exército e cavaleiros para nos defenderem do inimigo pelo caminho\" (Ed 8:22).",
  },
  "seis-mil-setecentos-e-vinte-jumentos": {
    title: "Os seis mil setecentos e vinte jumentos — o verdadeiro animal desta viagem",
    subtitle: "Ed 2:67 • a fila de carga que não cabe no quadro",
    text: "\"Os seus camelos, quatrocentos e trinta e cinco; os jumentos, seis mil setecentos e vinte\" (Ed 2:67). A lista dos bens acaba no jumento, e é justo: nove vezes mais jumentos do que cavalos, porque quem volta do exílio não volta a cavalo — volta a pé, com o que tem amarrado no lombo de um burro. É o animal do trabalho, do moinho, da lenha e da mudança, e é ele que carrega as cinco mil e quatrocentas peças do templo, as roupas, os sacos de semente e as crianças. A Escritura guarda para este animal humilde a honra maior de todas, e a profecia foi escrita justamente nesta época, pela boca de um dos dois profetas que fizeram esta casa subir: \"Alegra-te muito, ó filha de Sião; exulta, ó filha de Jerusalém; eis que o teu rei virá a ti, justo e Salvador, pobre, e montado sobre um jumento, e sobre um jumentinho, filho de jumenta\" (Zc 9:9). Seis mil setecentos e vinte deles entraram em Jerusalém nesta caravana; quinhentos anos depois, um só entrou pela porta com o Rei em cima.",
  },
  "ofertas-voluntarias-para-a-casa-de-deus": {
    title: "As ofertas voluntárias dos chefes dos pais: sessenta e uma mil dracmas de ouro, cinco mil libras de prata e cem vestes sacerdotais",
    subtitle: "Ed 2:68-69 • a bacia do ouro posta em cima das pedras do fundamento antigo",
    text: "\"E alguns dos chefes dos pais, vindo à casa do Senhor, que habita em Jerusalém, deram ofertas voluntárias para a casa de Deus, para a estabelecerem no seu lugar\" (Ed 2:68). Chegam a um terreno de entulho e a primeira coisa que fazem é dar — antes de haver parede, antes de haver altar, antes de haver planta. O detalhe final da conta é o que a torna humana: \"Conforme as suas posses, deram para o tesouro da obra, em ouro, sessenta e uma mil dracmas, e em prata cinco mil libras, e cem vestes sacerdotais\" (Ed 2:69). Cem vestes, porque de nada serve o dinheiro se não houver quem se possa vestir para servir. \"Conforme as suas posses\" é a medida da lei, e é a mesma que o Novo Testamento repetirá. O gesto tem dois antepassados diretos: a oferta do tabernáculo, quando \"veio todo o homem, a quem o seu coração moveu, e todo aquele cujo espírito voluntariamente o excitou\" (Êx 35:21), e a do templo de Salomão, em que \"o povo se alegrou porque contribuíram voluntariamente; porque, com coração perfeito, voluntariamente deram ao Senhor\" (1Cr 29:9). Três casas de Deus, o mesmo advérbio.",
  },
  "altar-do-deus-de-israel-sobre-as-suas-bases": {
    title: "O altar do Deus de Israel, firmado sobre as suas bases antes de haver uma só parede",
    subtitle: "Ed 3:2-3 • a primeira coisa levantada em Jerusalém, com o povo em volta ainda com medo",
    text: "\"E levantou-se Jesuá, filho de Jozadaque, e seus irmãos, os sacerdotes, e Zorobabel, filho de Sealtiel, e seus irmãos, e edificaram o altar do Deus de Israel, para oferecerem sobre ele holocaustos, como está escrito na lei de Moisés, o homem de Deus\" (Ed 3:2). Antes da planta, antes da pedra de cantaria, antes do dinheiro aos pedreiros: o altar. E é assentado no lugar exato do antigo — \"sobre as suas bases\" —, porque o endereço não é escolha de arquiteto. O versículo seguinte diz o que ninguém esperaria de um texto oficial: \"E firmaram o altar sobre as suas bases, porque o terror estava sobre eles, por causa dos povos das terras; e ofereceram sobre ele holocaustos ao Senhor, holocaustos pela manhã e à tarde\" (Ed 3:3). Levantaram-no com medo — e o medo não os impediu, apressou-os. A lei sempre quis este altar simples e sem enfeite: \"E se me fizeres um altar de pedras, não o farás de pedras lavradas; se sobre ele levantares o teu buril, profaná-lo-ás\" (Êx 20:25). Durante quase um ano, este foi o templo inteiro: pedra bruta, fogo e dois holocaustos por dia num chão vazio (Ed 3:6).",
  },
  "barco-que-trouxe-os-cedros-do-libano-a-jope": {
    title: "A jangada de cedros do Líbano trazida por mar até Jope, segundo a concessão de Ciro",
    subtitle: "Ed 3:7 • a praia de Jope com os troncos descarregados na areia",
    text: "\"Deram, pois, o dinheiro aos pedreiros e carpinteiros, como também comida e bebida, e azeite aos sidônios, e aos tírios, para trazerem do Líbano madeira de cedro ao mar, para Jope, segundo a concessão que lhes tinha feito Ciro, rei da Pérsia\" (Ed 3:7). Nada aqui é improvisado: é o mesmo contrato, com os mesmos fenícios, pelo mesmo trajeto, quatro séculos e meio depois do primeiro templo. Hirão escrevera a Salomão: \"E nós cortaremos tanta madeira no Líbano, quanta houveres mister, e ta traremos em jangadas pelo mar até Jope, e tu a farás subir a Jerusalém\" (2Cr 2:16), e o próprio Salomão reconhecera que \"entre nós ninguém há que saiba cortar a madeira como os sidônios\" (1Rs 5:6). Paga-se em comida, bebida e azeite, como antes. Jope é o único porto natural que Judá alcança, e é a mesma praia onde Jonas, séculos antes, \"achou um navio que ia para Társis; pagou, pois, a sua passagem\" para fugir da presença do Senhor (Jn 1:3) — de um lado do cais, um profeta a fugir de uma cidade pagã; do outro, cedros a chegar para a casa de Deus.",
  },
  "fundamentos-da-casa-do-senhor": {
    title: "Os fundamentos da casa do SENHOR, lançados no segundo mês do segundo ano",
    subtitle: "Ed 3:10-13; 5:16 • a linha de pedras que fez uns gritarem e outros chorarem",
    text: "\"Quando, pois, os edificadores lançaram os alicerces do templo do Senhor, então apresentaram-se os sacerdotes, já vestidos e com trombetas, e os levitas, filhos de Asafe, com címbalos, para louvarem ao Senhor conforme à instituição de Davi, rei de Israel\" (Ed 3:10). Nesta linha de pedra encostam-se, no mesmo instante, as duas metades do povo: \"muitos dos sacerdotes, e levitas e chefes dos pais, já idosos, que viram a primeira casa, choraram em altas vozes… mas muitos levantaram as vozes com júbilo e com alegria\" (Ed 3:12), \"De maneira que não discernia o povo as vozes do júbilo de alegria das vozes do choro do povo\" (Ed 3:13). O alicerce é o assunto e continua a sê-lo dezesseis anos depois, quando os anciãos o citam a Tatenai: \"Então veio este Sesbazar, e pôs os fundamentos da casa de Deus, que está em Jerusalém, e desde então para cá se está reedificando, e ainda não está acabada\" (Ed 5:16). Zacarias prometeu a estas mesmas pedras um acabamento: \"As mãos de Zorobabel têm lançado os alicerces desta casa; também as suas mãos a acabarão\" (Zc 4:9). E o fundamento que estas pedras anunciam já tinha sido descrito por Isaías: \"Eis que eu assentei em Sião uma pedra, uma pedra já provada, pedra preciosa de esquina, que está bem firme e fundada\" (Is 28:16).",
  },
  "acusacao-contra-os-habitantes-de-juda": {
    title: "A acusação escrita contra os habitantes de Judá e de Jerusalém no reinado de Assuero",
    subtitle: "Ed 4:6 • o quarto do escrivão à luz do candeeiro, com o rolo por escrever",
    text: "\"No reinado de Assuero, no princípio do seu reinado, escreveram uma acusação contra os habitantes de Judá e de Jerusalém\" (Ed 4:6). Um versículo só, sem o teor, sem os nomes dos signatários e sem o resultado — e é essa secura que o torna assustador. Aqui o capítulo 4 abandona a ordem do tempo e passa a empilhar, num bloco, todas as cartas escritas contra Jerusalém ao longo de reinados sucessivos: Assuero neste versículo, Artaxerxes no seguinte, e só no versículo 24 o relato volta ao ponto em que a obra parou, no tempo de Dario. O autor está a dizer uma coisa sobre o hábito, não sobre um episódio: sempre que Jerusalém tenta erguer-se, alguém pega numa pena. Repare no que não há neste capítulo — não há batalha, não há cerco, não há incêndio. A obra da casa de Deus foi parada por documentos, e é por um documento, achado num arquivo poeirento de Média, que ela voltará a andar (Ed 6:2).",
  },
  "carta-escrita-em-caracteres-siriacos": {
    title: "A carta a Artaxerxes escrita em caracteres siríacos e na língua siríaca",
    subtitle: "Ed 4:7 • o rolo estendido na chancelaria de Samaria, com a escrita estrangeira à vista",
    text: "\"E nos dias de Artaxerxes escreveram Bislão, Mitredate, Tabeel, e os outros seus companheiros, a Artaxerxes, rei da Pérsia; e a carta estava escrita em caracteres siríacos, e na língua siríaca\" (Ed 4:7). O detalhe da língua não é enfeite: o aramaico — o \"siríaco\" desta tradução — era o idioma oficial da chancelaria persa, de modo que a carta chegava a Susã pronta para ser lida sem tradutor e para entrar no arquivo como peça válida. Quem escreve isto sabe como funciona a máquina do império e usa-a com precisão. E o livro faz uma coisa notável a partir deste versículo: muda de idioma. O próprio texto de Esdras passa a citar em aramaico os documentos do processo, e só volta ao hebraico bastante depois — o autor cola no relato as peças tal como saíram das gavetas, sem as reescrever. É por isso que o rolo, nestes capítulos, é o verdadeiro personagem: quem fala é quem lê.",
  },
  "carta-de-reum-e-sinsai-contra-jerusalem": {
    title: "A carta de Reum, o chanceler, e de Sinsai, o escrivão, contra a \"rebelde e malvada cidade\"",
    subtitle: "Ed 4:8-16 • o rolo grande aberto no gabinete, escrito devagar, palavra por palavra",
    text: "\"Escreveram, pois, Reum, o chanceler, e Sinsai, o escrivão, uma carta contra Jerusalém, ao rei Artaxerxes, do teor seguinte\" (Ed 4:8). O documento é uma peça de retórica montada com frieza. Começa por arrolar signatários como quem arrola um exército — nove povos numa linha, \"dinaítas, afarsaquitas, tarpelitas, afarsitas, arquevitas, babilônios, susanquitas, deavitas, elamitas\" (Ed 4:9). Depois pinta o quadro que quer que o rei veja: os judeus \"reedificam aquela rebelde e malvada cidade, e vão restaurando os seus muros, e reparando os seus fundamentos\" (Ed 4:12) — e repare que tudo isso é verdade; a mentira está no adjetivo. Em seguida vai ao bolso: \"eles não pagarão os direitos, os tributos e os pedágios; e assim se danificará a fazenda dos reis\" (Ed 4:13). Manda conferir no arquivo (Ed 4:15) e fecha com a ameaça: \"não terás porção alguma deste lado do rio\" (Ed 4:16). No meio, denuncia-se sem querer: \"porquanto somos assalariados do palácio\" (Ed 4:14). Esta folha conseguiu o que nenhum exército tentara: dezesseis anos de canteiro parado.",
  },
  "livro-das-cronicas-dos-pais-do-rei": {
    title: "O livro das crônicas dos pais do rei, em que se buscou a rebelião antiga de Jerusalém",
    subtitle: "Ed 4:15,19 • o rolo do arquivo aberto na mesa da corte persa",
    text: "\"Para que se busque no livro das crônicas de teus pais. E acharás no livro das crônicas, e saberás que aquela foi uma cidade rebelde, e danosa aos reis e províncias, e que nela houve rebelião em tempos antigos\" (Ed 4:15). O acusador aposta no arquivo — e ganha: \"E, ordenando-o eu, buscaram e acharam, que de tempos antigos aquela cidade se levantou contra os reis, e nela se têm feito rebelião e sedição\" (Ed 4:19). O que o rolo diz é verdade: Jerusalém rebelara-se mesmo contra Babilônia, e foi por isso que ardeu. A carta usa um fato antigo para condenar um presente que nada tem com ele. O detalhe grande deste objeto é que ele reaparece do outro lado do tabuleiro duas vezes: numa noite de insônia em Susã, \"então mandou trazer o livro de registro das crônicas, as quais se leram diante do rei\" — e o que se leu salvou Mardoqueu (Et 6:1); e, no capítulo 6 deste mesmo livro, é outra busca em arquivo que encontra o memorial de Ciro e salva o templo (Ed 6:1-2). O mesmo móvel de gavetas condena e absolve, conforme o rolo que se abre.",
  },
  "salario-dos-conselheiros-alugados-contra-juda": {
    title: "O salário dos conselheiros alugados contra Judá, para frustrarem o seu plano",
    subtitle: "Ed 4:5 • o caixote da paga no meio do canteiro parado",
    text: "\"E alugaram contra eles conselheiros, para frustrarem o seu plano, todos os dias de Ciro, rei da Pérsia, até ao reinado de Dario, rei da Pérsia\" (Ed 4:5). Recusados de frente e sem força para derrubar a obra, os adversários compram influência: pagam a homens que sabem por onde correm os papéis do império e que hão de trabalhar contra Judá durante décadas — o versículo cobre um reinado inteiro numa linha. É a arma mais barata e a mais eficaz do livro. A Escritura conhece bem este orçamento: Balaque alugou um profeta para amaldiçoar Israel e o profeta não pôde entregar a encomenda (Nm 22-24); e Sambalate e Tobias alugaram um homem para assustar Neemias dentro do templo, o que este percebeu a tempo — \"E percebi que não era Deus quem o enviara; mas esta profecia falou contra mim, porquanto Tobias e Sambalate o subornaram\" (Ne 6:12). O detalhe mais amargo deste caixote é o que acontece com ele no capítulo 6: o mesmo tesouro imperial que financiou os conselheiros contra a casa passa a pagar as pedras e o gado do altar dela (Ed 6:8-9).",
  },
  "resposta-do-rei-artaxerxes": {
    title: "A resposta selada do rei Artaxerxes, que mandou impedir a obra",
    subtitle: "Ed 4:17-22 • o rolo já lacrado sobre a mesa da sala do trono",
    text: "\"E o rei enviou esta resposta a Reum, o chanceler, e a Sinsai, o escrivão, e aos demais seus companheiros, que habitavam em Samaria; como também aos demais que estavam dalém do rio: Paz! em tal tempo\" (Ed 4:17). O rei confirma que ouviu — \"A carta que nos enviastes foi explicitamente lida diante de mim\" (Ed 4:18) —, manda revistar o arquivo, encontra a rebelião antiga e mede a cidade pela única régua que lhe interessa: \"Também houve reis poderosos sobre Jerusalém que dalém do rio dominaram em todo o lugar, e se lhes pagaram direitos, tributos e pedágios\" (Ed 4:20). Vem então a ordem: \"Agora, pois, dai ordem para impedirdes aqueles homens, a fim de que não se edifique aquela cidade, até que eu dê uma ordem\" (Ed 4:21), com o aperto final \"E guardai-vos de serdes remissos nisto\" (Ed 4:22). Repare no fim da frase, que é a coisa mais importante deste rolo: ATÉ QUE EU DÊ UMA ORDEM. O decreto que parece fechar a porta deixa-a encostada — e é por essa fresta que o despacho de Dario entrará dois capítulos adiante.",
  },
  "rol-dos-nomes-dos-que-edificavam": {
    title: "O rol em que o escrivão de Tatenai anotou os nomes dos homens que edificavam",
    subtitle: "Ed 5:4,10 • o rolo em branco no meio da obra, aberto para tomar nomes",
    text: "\"Disseram-lhes, mais: E quais são os nomes dos homens que construíram este edifício?\" (Ed 5:4). Num império, esta é a pergunta que assusta mais do que a primeira: uma lista de nomes entregue à autoridade errada é uma lista de réus, e todos ali sabiam o que uma carta de Samaria já tinha conseguido fazer (Ed 4:23). A carta explica depois por que os quiseram: \"Além disso, lhes perguntamos também pelos seus nomes, para tos declararmos; para que te pudéssemos escrever os nomes dos homens que entre eles são os chefes\" (Ed 5:10). O extraordinário é que os anciãos deram os nomes e continuaram a trabalhar, e o texto explica em uma linha por que isso não acabou mal: \"Porém os olhos de Deus estavam sobre os anciãos dos judeus, e não os impediram, até que o negócio chegasse a Dario\" (Ed 5:5). Este rolo é gêmeo do arrolamento de Esdras 2 e o seu contrário: lá, os nomes escritos garantiam pertença; aqui, podiam custar a cabeça. É o mesmo povo, contado duas vezes, com duas intenções opostas.",
  },
  "carta-de-tatenai-ao-rei-dario": {
    title: "A carta de Tatenai ao rei Dario — o relatório honesto que destravou a obra",
    subtitle: "Ed 5:6-17 • o rolo comprido aberto na chancelaria de além do rio",
    text: "\"Cópia da carta que Tatenai, o governador dalém do rio, com Setar-Bozenai e os seus companheiros, os afarsaquitas, que estavam dalém do rio, enviaram ao rei Dario\" (Ed 5:6). Vale pô-la ao lado da carta de Reum, do capítulo anterior: aquela chamava Jerusalém \"rebelde e malvada\"; esta começa com \"Toda a paz ao rei Dario\" (Ed 5:7) e descreve o que o governador viu com os próprios olhos, sem uma linha de calúnia — \"a qual se edifica com grandes pedras, e a madeira já está sendo posta nas paredes; e esta obra vai sendo feita com diligência, e se adianta em suas mãos\" (Ed 5:8). Reproduz palavra por palavra a resposta dos anciãos, inclusive a parte que os incrimina — \"Mas depois que nossos pais provocaram à ira o Deus dos céus, ele os entregou nas mãos de Nabucodonosor\" (Ed 5:12) — e a que os apresenta: \"Nós somos servos do Deus dos céus e da terra\" (Ed 5:11). E fecha sem tomar partido, pedindo apenas verificação: \"busque-se na casa dos tesouros do rei, que está em babilônia, se é verdade\" (Ed 5:17). Um funcionário imperial escreveu, sem querer, a melhor defesa que a obra recebeu.",
  },
  "casa-destruida-por-nabucodonosor": {
    title: "A casa que Nabucodonosor destruiu, na lembrança que os anciãos contaram a Tatenai",
    subtitle: "Ed 5:12 • o incêndio antigo trazido de volta ao quadro, sem cidade nenhuma de pé",
    text: "\"Mas depois que nossos pais provocaram à ira o Deus dos céus, ele os entregou nas mãos de Nabucodonosor, rei de babilônia, o caldeu, o qual destruiu esta casa, e transportou o povo para babilônia\" (Ed 5:12). O que impressiona nesta resposta é a honestidade: interrogados por um governador estrangeiro, os anciãos podiam ter contado a história como vítimas de um imperador — e contam-na como culpados diante de Deus. O sujeito da frase não é Nabucodonosor: é o Deus dos céus, que \"os entregou\". O incêndio a que se referem tem data e nome de executor: no décimo dia do quinto mês, Nebuzaradã \"queimou a casa do Senhor e a casa do rei, como também todas as casas de Jerusalém\" (2Rs 25:9), e o salmo escreveu de dentro da fumaça: \"Lançaram fogo no teu santuário; profanaram, derrubando-a até ao chão, a morada do teu nome\" (Sl 74:7). É por cima destas cinzas que se levantam as \"grandes pedras\" do versículo 8 — e é este parágrafo de confissão que dá credibilidade a todo o resto da carta.",
  },
  "rolo-achado-em-acmeta-na-provincia-de-media": {
    title: "O rolo do memorial de Ciro achado em Acmeta, no palácio da província de Média",
    subtitle: "Ed 6:2-5 • o objeto que é o personagem do versículo, aberto no meio do arquivo",
    text: "\"Então o rei Dario deu ordem, e buscaram nos arquivos, onde se guardavam os tesouros em babilônia. E em Acmeta, no palácio, que está na província de Média, se achou um rolo, e nele estava escrito um memorial que dizia assim\" (Ed 6:1-2). Procuraram em Babilônia e não estava lá: estava em Ecbátana, a capital da Média, onde os reis persas passavam o verão — e é por isso que o achado é notável, porque o decreto tinha sido lavrado no primeiro ano de Ciro, provavelmente durante uma estada de verão, e ficara arquivado onde ninguém procuraria primeiro. O teor é obra pública detalhada: a casa \"se reedificará para lugar em que se ofereçam sacrifícios, e seus fundamentos serão firmes; a sua altura de sessenta côvados, e a sua largura de sessenta côvados\" (Ed 6:3), \"Com três carreiras de grandes pedras, e uma carreira de madeira nova; e a despesa se fará da casa do rei\" (Ed 6:4), e ainda a restituição dos utensílios, \"para que voltem ao seu lugar\" (Ed 6:5). Setenta anos antes, um escriba anônimo copiou um decreto e guardou-o numa arca. Foi essa folha que, dezesseis anos depois de a obra parar, a fez recomeçar.",
  },
  "decreto-de-dario-para-que-se-faca-a-obra": {
    title: "O decreto de Dario: apartai-vos dali, faça-se a obra, pague-se da fazenda do rei",
    subtitle: "Ed 6:6-12 • o rolo selado que passa de mão em mão no pátio do palácio",
    text: "Achado o memorial, Dario não se limita a permitir: manda, paga e ameaça. Manda o governador afastar-se — \"que habitais dalém do rio, apartai-vos dali\" (Ed 6:6); manda prosseguir — \"Deixai que se faça a obra desta casa de Deus; que o governador dos judeus e os seus anciãos reedifiquem esta casa de Deus no seu lugar\" (Ed 6:7); manda pagar do próprio tesouro — \"que da fazenda do rei, dos tributos dalém do rio se pague prontamente a despesa a estes homens, para que não interrompam a obra\" (Ed 6:8); e manda abastecer o altar todos os dias, \"de dia em dia, para que não haja falta\" (Ed 6:9). A sanção é brutal e é literal: quem mudar o decreto, \"se arrancará um madeiro da sua casa, e, levantado, o pendurarão nele, e da sua casa se fará por isso um monturo\" (Ed 6:11). E o fecho é o mais estranho de tudo — um rei pagão invoca o Deus de Israel contra os seus próprios sucessores: \"O Deus, pois, que fez habitar ali o seu nome derrube a todos os reis e povos que estenderem a sua mão para mudar o decreto… Eu, Dario, baixei o decreto; com diligência se faça\" (Ed 6:12).",
  },
  "provisao-de-dia-em-dia-da-fazenda-do-rei": {
    title: "A provisão de dia em dia — bezerros, carneiros, cordeiros, trigo, sal, vinho e azeite por conta do rei",
    subtitle: "Ed 6:9 • o depósito da obra abastecido, \"para que não haja falta\"",
    text: "\"E o que for necessário, como bezerros, carneiros, e cordeiros, para holocaustos ao Deus dos céus, trigo, sal, vinho e azeite, segundo o rito dos sacerdotes que estão em Jerusalém, dê-se-lhes, de dia em dia, para que não haja falta\" (Ed 6:9). É a lista de compras do altar, escrita por um imperador persa e paga com o dinheiro dos tributos de além do rio. Repare em duas coisas. A primeira é a frase \"segundo o rito dos sacerdotes que estão em Jerusalém\": o rei não legisla sobre o culto, manda que se faça como os sacerdotes daquela casa disserem. A segunda é o SAL, que não serve para queimar nem para comer — está ali porque a lei o exige em cada oferta, e um funcionário qualquer foi ao ponto de o incluir na conta. \"De dia em dia, para que não haja falta\" é frase de despenseiro, não de teólogo, e desenha-se por acumulação: sacos, cântaros, gado à porta. O mesmo tesouro que no capítulo 4 pagou os conselheiros alugados contra a casa (Ed 4:5) passa aqui a abastecê-la — e o rei pede em troca apenas que \"orem pela vida do rei e de seus filhos\" (Ed 6:10).",
  },
  "casa-de-deus-acabada-em-jerusalem": {
    title: "A casa de Deus acabada no terceiro dia do mês de Adar, no sexto ano de Dario",
    subtitle: "Ed 6:15-22 • o segundo templo de pé, vinte e um anos depois do primeiro alicerce",
    text: "\"E acabou-se esta casa no terceiro dia do mês de Adar, no sexto ano do reinado do rei Dario\" (Ed 6:15). Dia, mês e ano — este povo aprendeu a desconfiar de promessas sem calendário. Entre o alicerce do capítulo 3 e esta manhã passaram-se cerca de vinte e um anos, dos quais dezesseis de obra parada. A casa é menor e mais pobre do que a de Salomão, e o livro nunca o esconde; nela não há arca, e Ageu tinha respondido a essa vergonha com a promessa maior do Antigo Testamento sobre um prédio: \"A glória desta última casa será maior do que a da primeira, diz o Senhor dos Exércitos, e neste lugar darei a paz\" (Ag 2:9). O que se fez dentro dela justifica a frase: aqui os sacerdotes voltaram às suas turmas \"conforme ao que está escrito no livro de Moisés\" (Ed 6:18), aqui se comeu a primeira páscoa livre em setenta anos (Ed 6:19), e é este mesmo edifício — remodelado por Herodes séculos depois — em cujos átrios o Menino seria apresentado, o rapaz de doze anos ficaria a ouvir os doutores e o Filho ensinaria todos os dias. A casa pequena recebeu, de facto, uma glória que a grande não teve.",
  },
  "livro-de-moises-lido-na-casa-acabada": {
    title: "O livro de Moisés, pelo qual os sacerdotes foram postos nas suas turmas e os levitas nas suas divisões",
    subtitle: "Ed 6:18 • o rolo da lei aberto no adro do templo acabado",
    text: "\"E puseram os sacerdotes nas suas turmas e os levitas nas suas divisões, para o ministério de Deus, em Jerusalém, conforme ao que está escrito no livro de Moisés\" (Ed 6:18). Acabada a casa, a primeira coisa que se faz dentro dela não é uma cerimônia: é abrir um livro e reorganizar o serviço por ele. As turmas em questão são as vinte e quatro que Davi sorteara — \"E saiu a primeira sorte a Jeoiaribe, a segunda a Jedaías\" (1Cr 24:7) —, das quais só quatro casas voltaram do exílio (Ed 2:36-39); a ordem é recomposta com o que há. Repare no que sustentou este povo durante setenta anos sem templo, sem altar e sem país: um rolo. Foi o livro que atravessou o cativeiro, e é por isso que a figura central da segunda metade de Esdras não é um rei nem um sacerdote, mas um escriba \"hábil na lei de Moisés\" (Ed 7:6). O gesto deste versículo prepara a cena mais bonita da restauração, quando \"todo o povo se ajuntou como um só homem, na praça, diante da porta das águas; e disseram a Esdras, o escriba, que trouxesse o livro da lei de Moisés\" (Ne 8:1).",
  },
  "genealogia-de-esdras-ate-arao": {
    title: "A genealogia de Esdras, que sobe dezesseis degraus até Arão",
    subtitle: "Ed 7:1-5 — o rolo aberto de ponta a ponta na câmara dos rolos em babilônia",
    text: "O livro não apresenta o seu protagonista pelo cargo: abre um rolo e sobe. \"Esdras, filho de Seraías, filho de Azarias, filho de Hilquias\" (Ed 7:1), e daí a Salum, Zadoque, Aitube, Amarias, Azarias, Meraiote, Zeraquias, Uzi, Buqui, Abisua, até parar em \"Finéias, filho de Eleazar, filho de Arão, o sumo sacerdote\" (Ed 7:5). A lista salta gerações de propósito — comparada com 1 Crônicas 6:3-15, faltam nomes —, porque não é censo, é título de direito: no segundo templo, quem não achava o seu registro entre os arrolados nas genealogias era, \"por imundos\", excluído do sacerdócio (Ed 2:62). Este rolo é o que autoriza o homem a manejar o outro rolo, o da lei. Repare em quem está no meio da escada: Zadoque, que ungiu Salomão em Giom (1Rs 1:39); Amarias, que Josafá pôs à frente de \"todo o negócio do Senhor\" (2Cr 19:11); Hilquias, o sacerdote que achou o livro da lei na casa do SENHOR nos dias de Josias (2Rs 22:8); e Seraías, o pai, morto em Ribla quando Jerusalém caiu (2Rs 25:18-21). A família já tinha tido a lei nas mãos duas vezes antes dele.",
  },
  "vara-de-arao-que-floresceu": {
    title: "A vara de Arão, que floresceu e deu amêndoas",
    subtitle: "Nm 17:8 — o pau seco que reverdeceu, de pé no quadro em que a genealogia alcança o sumo sacerdote",
    text: "Depois da contenda de Corá, Datã e Abirão sobre quem tinha direito de ministrar, Moisés recolheu doze varas, uma por casa paterna, e as pôs diante do testemunho na tenda. \"Sucedeu, pois, que no dia seguinte Moisés entrou na tenda do testemunho, e eis que a vara de Arão, pela casa de Levi, florescia; porque produzira flores e brotara renovos e dera amêndoas\" (Nm 17:8). Um pedaço de pau morto com flor, broto e fruto ao mesmo tempo, e o SENHOR mandou guardá-la perante o testemunho \"por sinal para os filhos rebeldes\" (Nm 17:10) — junto com o maná e as tábuas, dentro da arca (Hb 9:4). No quadro de Esdras 7:5 ela está de pé no meio do santuário antigo porque é ali que a subida da genealogia termina: a linhagem que o escriba acabou de recitar é a mesma que aquela vara autenticou. E a imagem diz de Arão o que a lista não diz — que o direito de ministrar não foi tomado, foi dado, e a prova disso é uma coisa seca que Deus fez florescer.",
  },
  "lei-do-senhor-que-esdras-buscou": {
    title: "A lei do SENHOR que Esdras preparou o coração para buscar, cumprir e ensinar",
    subtitle: "Ed 7:10 • 9:12 • 10:3 — o rolo que atravessa os quatro capítulos e domina cada quadro em que aparece",
    text: "É o objeto central do livro inteiro, e o versículo que o explica é o que governa tudo o mais: \"Porque Esdras tinha preparado o seu coração para buscar a lei do Senhor e para cumpri-la e para ensinar em Israel os seus estatutos e os seus juízos\" (Ed 7:10). Três verbos em ordem obrigatória — buscar antes de cumprir, cumprir antes de ensinar —, e é essa ordem que faz a diferença entre um escriba e um funcionário. O mesmo rolo reaparece em cada momento decisivo: quando a oração do capítulo 9 para de argumentar e passa a citar, \"vossas filhas não dareis a seus filhos, e suas filhas não tomareis para vossos filhos\" (Ed 9:12), que é palavra de Deuteronômio 7:3; quando Secanias propõe a aliança e conclui \"e faça-se conforme a lei\" (Ed 10:3); e quando os chefes juram diante da casa (Ed 10:5). Trata-se dos cinco livros de Moisés, o mesmo texto que Esdras leria em voz alta \"desde a alva até ao meio-dia\" sobre um púlpito de madeira, diante de homens, mulheres e todos os que podiam ouvir com entendimento (Ne 8:2-4). Na cena ele é desenhado grande e no centro: neste livro, quem manda no quadro é o rolo.",
  },
  "carta-de-artaxerxes-a-esdras": {
    title: "A carta de Artaxerxes, rei dos reis, ao sacerdote Esdras",
    subtitle: "Ed 7:11-26 — o documento que o texto copia por extenso, em aramaico, do trono ao tesouro",
    text: "\"Esta é, pois, a cópia da carta que o rei Artaxerxes deu ao sacerdote Esdras, o escriba das palavras dos mandamentos do Senhor, e dos seus estatutos sobre Israel\" (Ed 7:11) — e o livro a transcreve inteira, no aramaico oficial da chancelaria persa, sem resumir nada. Abre com o protocolo do império: \"Artaxerxes, rei dos reis, ao sacerdote Esdras, escriba da lei do Deus do céu, paz perfeita, em tal tempo\" (Ed 7:12). Depois vêm as cláusulas: quem quiser ir, vá (v. 13); leve a prata e o ouro voluntários (v. 15-16); compre com o dinheiro novilhos, carneiros, cordeiros, ofertas de alimentos e libações (v. 17); restitua os utensílios (v. 19); tire da casa dos tesouros do rei o que faltar, até cem talentos de prata, cem coros de trigo, cem batos de vinho, cem batos de azeite, \"e sal à vontade\" (v. 22); nada de tributo, contribuição ou renda sobre os ministros da casa (v. 24); e autoridade para nomear magistrados e juízes, com pena de \"morte, quer desterro, quer multa sobre os seus bens, quer prisão\" (v. 26). A carta é o caso mais claro deste arquivo de MEDIADOR DE OBJETO: Deus não fala uma vez nestes capítulos, e o balão sai de quem dita e lê o rolo. Quem o recebe não credita o favor ao trono: \"Bendito seja o Senhor Deus de nossos pais, que tal inspirou ao coração do rei\" (Ed 7:27).",
  },
  "lei-do-teu-deus-que-esta-na-tua-mao": {
    title: "A lei do teu Deus, que está na tua mão",
    subtitle: "Ed 7:14,25-26 — o rolo entregue pelo rei, com autoridade de julgar dalém do rio",
    text: "É a expressão do próprio decreto persa, e diz mais do que parece: \"Porquanto és enviado da parte do rei e dos seus sete conselheiros para fazeres inquirição a respeito de Judá e de Jerusalém, conforme à lei do teu Deus, que está na tua mão\" (Ed 7:14). O império reconhece por escrito que existe um código que não é o dele e manda aplicá-lo. Duas cláusulas adiante, a delegação fica completa: \"E tu, Esdras, conforme a sabedoria do teu Deus, que possues, nomeia magistrados e juízes, que julguem a todo o povo que está dalém do rio, a todos os que sabem as leis do teu Deus; e ao que não as sabe, lhe ensinarás\" (Ed 7:25) — julgar quem sabe, ensinar quem não sabe. E a sanção é dupla e dura: \"E todo aquele que não observar a lei do teu Deus e a lei do rei, seja julgado prontamente; quer seja morte, quer desterro, quer multa sobre os seus bens, quer prisão\" (Ed 7:26). A partir deste ponto do capítulo o trono e a coroa recuam para o fundo do quadro e quem manda na cena é o rolo. A frase inteira, no entanto, mede a distância do livro: a lei está na mão de um homem, e o resto de Esdras 9 e 10 é o que acontece quando ela chega ao chão.",
  },
  "prata-e-ouro-da-oferta-voluntaria": {
    title: "A prata e o ouro da oferta voluntária do rei, dos conselheiros e do povo de babilônia",
    subtitle: "Ed 7:15-16 — as caixas do tesouro que a carta manda recolher em toda a província",
    text: "A carta manda levar duas coisas diferentes na mesma caixa. Primeiro, o donativo do império: \"E para levares a prata e o ouro que o rei e os seus conselheiros voluntariamente deram ao Deus de Israel, cuja habitação está em Jerusalém\" (Ed 7:15) — um monarca pagão e os seus sete conselheiros dando espontaneamente para um santuário que nunca viram. Depois, a coleta dos que ficam: \"E toda a prata e o ouro que achares em toda a província de babilônia, com as ofertas voluntárias do povo e dos sacerdotes, que voluntariamente oferecerem, para a casa de seu Deus, que está em Jerusalém\" (Ed 7:16). Boa parte deste metal sai da mão de gente que não vai subir e manda o que tem no lugar do corpo. É o mesmo padrão de todas as grandes obras da Escritura — o do tabernáculo, feito com o que trouxe \"todo o homem, a quem o seu coração moveu\" (Êx 35:21), e o das ofertas do primeiro retorno (Ed 2:68-69). Pesado no rio Aava, isto dará seiscentos e cinquenta talentos de prata, cem talentos de ouro, cem talentos em vasos de prata e vinte bacias de ouro (Ed 8:26-27), e atravessará quatro meses de deserto sem escolta armada nenhuma.",
  },
  "banca-onde-se-compram-os-novilhos-e-carneiros": {
    title: "A banca do mercado onde se compram os novilhos, os carneiros e os cordeiros da carta",
    subtitle: "Ed 7:17 — o portão do palácio, onde o dinheiro persa vira sacrifício de Israel",
    text: "A carta do rei não se contenta em soltar o dinheiro: especifica a compra. \"Portanto diligentemente comprarás com este dinheiro novilhos, carneiros, cordeiros, com as suas ofertas de alimentos, e as suas libações, e as oferecerás sobre o altar da casa de vosso Deus, que está em Jerusalém\" (Ed 7:17). O advérbio é do monarca — DILIGENTEMENTE —, e a lista que ele dita é exatamente a de Números 15:1-10: o animal nunca sobe sozinho, vai sempre com a oferta de alimentos e a libação de vinho. Um rei persa a redigir o ritual levítico por escrito, com o cuidado de quem teme errar a fórmula: \"Tudo quanto se ordenar, segundo o mandado do Deus do céu, prontamente se faça para a casa do Deus dos céus\" (Ed 7:23). A banca em cena é a feira do portão: postes, toldo listrado, fruta na bancada e o gado ao lado. É aqui que a prata voluntária de babilônia se transforma em bicho vivo, e é este bicho que subirá a estrada de quatro meses e acabará em fogo no pátio de Jerusalém (Ed 8:35).",
  },
  "utensilios-da-casa-de-deus-restituidos": {
    title: "Os utensílios da casa de Deus, restituídos perante o Deus de Jerusalém",
    subtitle: "Ed 7:19 — os vasos do santuário que a Pérsia devolve pela segunda vez",
    text: "\"E os utensílios que te foram dados para o serviço da casa de teu Deus, restitui-os perante o Deus de Jerusalém\" (Ed 7:19). O verbo é RESTITUIR, não doar: aquilo nunca foi da Pérsia. Nabucodonosor levara os vasos do templo para a casa dos seus deuses em babilônia (2Cr 36:7,18); Belsazar bebeu por eles na noite em que a escrita apareceu na parede (Dn 5:2-5); Ciro mandou tirá-los da casa dos tesouros e contá-los a Sesbazar, cinco mil e quatrocentos ao todo (Ed 1:7-11). Este segundo lote sobe agora com Esdras, e será pesado duas vezes: uma na mão de doze sacerdotes junto ao rio Aava, com o encargo \"Vós sois santos ao Senhor, e são santos estes utensílios\" (Ed 8:28), e outra na câmara da casa de nosso Deus, ao quarto dia depois da chegada — \"Tudo foi contado e pesado\" (Ed 8:34). A devolução dos vasos é o modo como este livro conta o fim do exílio: o que fora tirado do lugar santo volta ao lugar santo, peça por peça, sem faltar nenhuma.",
  },
  "casa-dos-tesouros-do-rei": {
    title: "A casa dos tesouros do rei, aberta em conta corrente para a casa de Deus",
    subtitle: "Ed 7:20-22 — o depósito do palácio persa, com o teto do gasto escrito na carta",
    text: "\"E tudo mais que for necessário para a casa de teu Deus, que te convenha dar, dá-lo-ás da casa dos tesouros do rei\" (Ed 7:20). É uma conta aberta, e o decreto vai adiante e obriga toda a administração provincial a honrá-la: \"E por mim mesmo, o rei Artaxerxes, se decreta a todos os tesoureiros que estão dalém do rio que tudo quanto vos pedir o sacerdote Esdras, escriba da lei do Deus dos céus, prontamente se faça\" (Ed 7:21). Só então vem o limite, e ele é generoso: \"Até cem talentos de prata, e até cem coros de trigo, e até cem batos de vinho, e até cem batos de azeite; e sal à vontade\" (Ed 7:22) — quatro tetos e uma única coisa sem teto, o sal, que era o que temperava toda oferta de manjares (Lv 2:13) e nunca podia faltar no altar. O motivo declarado é de império: \"pois, para que haveria grande ira sobre o reino do rei e de seus filhos?\" (Ed 7:23). Na cena, é a porta do fundo com as caixas empilhadas, os cântaros e a bacia do peso — e um guarda que já não pergunta mais nada.",
  },
  "genealogia-dos-que-subiram-com-esdras": {
    title: "A genealogia dos chefes das casas paternas que subiram com Esdras",
    subtitle: "Ed 8:1-14 — o rolo aberto sobre a caixa, no portão do rio em babilônia, ao amanhecer",
    text: "\"Estes, pois, são os chefes das casas paternas e esta a genealogia dos que subiram comigo de babilônia no reinado do rei Artaxerxes\" (Ed 8:1). O que vem a seguir não é arquivo: é a chamada de embarque, lida em voz alta com a fila já formada. Catorze casas, cada uma com o seu chefe à frente e o seu número atrás — Zacarias de Parós com cento e cinquenta \"segundo a genealogia\" (v. 3), Elioenai com duzentos, o filho de Jeaziel com trezentos, Ebede com cinquenta, Jesaías com setenta, Zebadias com oitenta, Obadias com duzentos e dezoito, cento e sessenta de Selomite, vinte e oito de Bebai, cento e dez de Azgade, sessenta com os últimos filhos de Adonicão, setenta com Bigvai. Cerca de mil e quinhentos homens, contra os quarenta e dois mil trezentos e sessenta da primeira volta (Ed 2:64). A lista abre pelo sacerdócio — Finéias e Itamar (v. 2) — e traz, sem alarde nenhum, a casa real de Judá no meio dela: \"dos filhos de Davi, Hatus\". Duas lacunas (v. 5 e v. 10) deixam ver que o rolo foi copiado de um registro já gasto, e o texto não as disfarça. E é logo depois desta leitura que se descobre o buraco: nem um filho de Levi respondeu à chamada (Ed 8:15).",
  },
  "rio-que-vai-a-aava": {
    title: "O rio que vai a Aava",
    subtitle: "Ed 8:15,21,31 — três dias de acampamento, uma chamada que falhou e um jejum sem fogo aceso",
    text: "\"E ajuntei-os perto do rio que vai a Aava, e ficamos ali acampados três dias\" (Ed 8:15). Aava é um canal ou braço de rio na babilônia, e não aparece em mais nenhum lugar da Bíblia: é o ponto de concentração escolhido para conferir a caravana antes de sair do império. E é ali que a conta não fecha — \"Então atentei para o povo e para os sacerdotes, e não achei ali nenhum dos filhos de Levi\". Onze chefes partem para Casifia e voltam com trinta e oito levitas e duzentos e vinte servidores do templo (v. 17-20). Na mesma margem se apregoa o jejum: \"para nos humilharmos diante da face de nosso Deus, para lhe pedirmos caminho seguro para nós, para nossos filhos e para todos os nossos bens\" (Ed 8:21) — e a cena o desenha pelo que falta: fogueira apagada, nenhum cântaro servido, nenhuma tenda aberta, só a água correndo. Ali também se pesa a prata na mão dos doze (v. 24-27). E dali se parte, no dia doze do primeiro mês, sem escolta: \"e a mão do nosso Deus estava sobre nós, e livrou-nos da mão dos inimigos, e dos que nos armavam ciladas pelo caminho\" (Ed 8:31).",
  },
  "seiscentos-e-cinquenta-talentos-de-prata": {
    title: "Os seiscentos e cinquenta talentos de prata pesados na mão dos doze",
    subtitle: "Ed 8:25-26 — o fardo da balança armada na margem do rio Aava, antes de partir",
    text: "\"E pesei-lhes a prata, o ouro e os vasos; que eram a oferta para a casa de nosso Deus, que ofereceram o rei, os seus conselheiros, os seus príncipes e todo o Israel que ali se achou. E pesei em suas mãos seiscentos e cinqüenta talentos de prata, e em vasos de prata cem talentos, e cem talentos de ouro\" (Ed 8:25-26). Um talento anda pelos trinta e quatro quilos: são mais de vinte toneladas de metal, repartidas por doze chefes dos sacerdotes e carregadas por mil e quinhentas pessoas através de mil e quinhentos quilômetros de deserto — sem um soldado à frente, porque o homem que organizou a viagem teve vergonha de pedir escolta ao rei depois de lhe ter dito que \"A mão do nosso Deus é sobre todos os que o buscam\" (Ed 8:22). O procedimento é o oposto da confiança vaga: pesa-se antes, entrega-se por recibo, pesa-se de novo na chegada. É o mesmo cuidado que Paulo teria ao levar a coleta das igrejas, \"Evitando isto, que alguém nos vitupere por esta abundância\" (2Co 8:20). Aqui a soma bate: \"Tudo foi contado e pesado\" (Ed 8:34).",
  },
  "vinte-bacias-de-ouro-de-mil-dracmas": {
    title: "As vinte bacias de ouro, de mil dracmas, e os dois vasos de bom metal lustroso",
    subtitle: "Ed 8:27 — o que estava sobre a mesa da pesagem, ao lado do fardo da prata",
    text: "\"E vinte bacias de ouro, de mil dracmas, e dois vasos de bom metal lustroso, tão precioso como ouro\" (Ed 8:27). Depois das toneladas contadas em talentos, o inventário desce ao detalhe das peças, e é aí que se vê que não é só dinheiro: são utensílios de serviço, bacias de aspersão do altar, feitas para uma função e não para render juros. Os dois últimos objetos ganham uma nota que o escriba não precisava dar — \"de bom metal lustroso, tão precioso como ouro\" —, provavelmente um bronze polido de liga rara, e a nota está ali porque quem pesa tem de dizer também o que não se mede em peso. Tudo isto é entregue com uma frase que muda a natureza do carregamento: \"Vós sois santos ao Senhor, e são santos estes utensílios, como também esta prata e este ouro, oferta voluntária, oferecida ao Senhor Deus de vossos pais\" (Ed 8:28). Deixa de ser carga e passa a ser depósito sagrado — e o encargo que segue é de sentinela, não de estivador: \"Vigiai, pois, e guardai-os\" (Ed 8:29).",
  },
  "utensilios-pesados-na-casa-de-nosso-deus": {
    title: "Os utensílios pesados na casa de nosso Deus, ao quarto dia",
    subtitle: "Ed 8:33-34 — a câmara da pesagem em Jerusalém, e a conta que fechou",
    text: "\"E no quarto dia se pesou a prata, o ouro e os utensílios, na casa do nosso Deus, por mão de Meremote, filho do sacerdote Urias; e com ele Eleazar, filho de Finéias, e com eles Jozabade, filho de Jesuá, e Noadias, filho de Binui, levitas\" (Ed 8:33). Quatro homens em volta de uma balança — dois sacerdotes e dois levitas —, para que nenhuma conta ficasse na mão de um só. Chegaram e repousaram três dias (v. 32); ao quarto, abriram os fardos. O versículo seguinte é o fecho da viagem inteira e a frase mais sóbria do livro: \"Tudo foi contado e pesado; e todo o peso foi registrado na mesma ocasião\" (Ed 8:34). Nada faltou, e o registro foi lavrado na hora, não depois. Vinte toneladas atravessaram quatro meses de estrada sem escolta armada e sem furo. É o cumprimento exato do encargo dado na margem do rio Aava — \"até que os peseis na presença dos chefes dos sacerdotes e dos levitas, e dos chefes dos pais de Israel, em Jerusalém, nas câmaras da casa do Senhor\" (Ed 8:29).",
  },
  "registro-do-peso-de-tudo-em-jerusalem": {
    title: "O registro do peso de tudo, lavrado na mesma ocasião",
    subtitle: "Ed 8:34 — o rolo do escrivão sobre a mesa da câmara da pesagem",
    text: "\"Tudo foi contado e pesado; e todo o peso foi registrado na mesma ocasião\" (Ed 8:34). Este rolo é a prova documental de que a viagem terminou sem perda, e a sua existência diz o que o livro pensa sobre dinheiro consagrado: não basta ser honesto, é preciso ser verificável. Por isso houve balança na saída (Ed 8:25-27), doze depositários nomeados (v. 24), quatro conferentes na chegada (v. 33) e agora um registro escrito no ato — não no fim do mês, \"na mesma ocasião\". O mesmo cuidado atravessa a Escritura: no tempo de Joás, o dinheiro do conserto do templo era entregue aos mestres da obra sem tomar contas, \"porquanto procediam com fidelidade\" (2Rs 12:15), e Paulo levaria a coleta das igrejas acompanhado de irmãos escolhidos por elas para que ninguém pudesse vituperá-lo (2Co 8:19-21). Na cena, o rolo está à direita da balança, aberto, e o candelabro fica aceso ao fundo: a conta é fechada dentro da casa, à vista de todos os que a carregaram.",
  },
  "altar-dos-holocaustos-dos-que-voltaram": {
    title: "O altar dos holocaustos dos que voltaram do cativeiro",
    subtitle: "Ed 8:35 — doze novilhos por todo o Israel, noventa e seis carneiros, setenta e sete cordeiros e doze bodes",
    text: "\"E os exilados, que vieram do cativeiro, ofereceram holocaustos ao Deus de Israel: doze novilhos por todo o Israel, noventa e seis carneiros, setenta e sete cordeiros, e doze bodes em sacrifício pelo pecado; tudo em holocausto ao Senhor\" (Ed 8:35). Os números são teologia. DOZE novilhos e DOZE bodes: uma caravana saída de duas ou três tribos oferece pelas doze, porque não se entende como resto de Judá, e sim como Israel inteiro — a mesma conta que Elias fizera com doze pedras no Carmelo (1Rs 18:31) e que o primeiro retorno já fizera na dedicação da casa, com doze bodes \"segundo o número das tribos de Israel\" (Ed 6:17). Noventa e seis carneiros são oito vezes doze; setenta e sete cordeiros repetem o número da plenitude. Os bodes vêm por último e com destino declarado: sacrifício pelo pecado, o rito de Levítico 4, em que a culpa passa da cabeça do homem para a cabeça do animal. É a primeira coisa que a caravana faz depois de pesar a prata: antes de qualquer reunião, o fogo.",
  },
  "sacrificio-da-tarde-em-jerusalem": {
    title: "O sacrifício da tarde, a hora marcada em que Esdras se levantou da sua aflição",
    subtitle: "Ed 9:4-5 — o altar aceso à direita, com o sol quase encostando no horizonte",
    text: "O holocausto contínuo era oferecido duas vezes por dia, \"Um cordeiro oferecerás pela manhã, e o outro cordeiro oferecerás à tarde\" (Êx 29:39), e é esse relógio — e não a vontade de ninguém — que mede a cena mais imóvel do livro. Ao ouvir a denúncia dos príncipes, Esdras rasga as vestes, arranca os cabelos e senta-se no chão; \"porém eu permaneci sentado atônito até ao sacrifício da tarde\" (Ed 9:4). Horas caladas, com gente em volta e ninguém a dizer nada. \"E perto do sacrifício da tarde me levantei da minha aflição, havendo já rasgado as minhas vestes e o meu manto, e me pus de joelhos, e estendi as minhas mãos para o Senhor meu Deus\" (Ed 9:5). O altar em cena continuou a funcionar o dia todo: o sacerdote de turno acendeu a oferta como em qualquer outro dia, e foi essa rotina que devolveu o movimento a um homem paralisado. É a mesma hora em que Daniel, em babilônia, recebera a visita do varão Gabriel (Dn 9:21), e a mesma em que Elias, no Carmelo, se chegou e orou (1Rs 18:29,36). Aqui não vem visão nenhuma — vem apenas a permissão de se levantar do chão.",
  },
  "estaca-no-seu-santo-lugar": {
    title: "A estaca no seu santo lugar",
    subtitle: "Ed 9:8 — a imagem da oração desenhada: o ponto fixo fincado no chão do santuário",
    text: "\"E agora, por um pequeno momento, se manifestou a graça da parte do Senhor, nosso Deus, para nos deixar alguns que escapem, e para dar-nos uma estaca no seu santo lugar; para nos iluminar os olhos, ó Deus nosso, e para nos dar um pouco de vida na nossa servidão\" (Ed 9:8). A palavra é a do prego ou da estaca de tenda: um ponto fincado que segura o resto e permite armar alguma coisa em cima. Isaías usara a mesma figura em Eliaquim — \"E fixá-lo-ei como a um prego num lugar firme, e será como um trono de honra para a casa de seu pai\" (Is 22:23) —, e Zacarias diria de Judá: \"Dele sairá a pedra de esquina, dele a estaca\" (Zc 10:4). O que Esdras reconhece é modesto de propósito: não um reino restaurado, não um trono, apenas um ponto fixo dentro do santuário e um pouco de vida na servidão. Tudo isso emoldurado por três medidas pequenas — um pequeno momento, alguns que escapem, um pouco de vida —, porque a oração está a contar graça, e graça contada assim não vira mérito. Na cena, é a coluna fincada ao lado da casa do SENHOR de pé outra vez.",
  },
  "pregao-dos-tres-dias-em-jerusalem": {
    title: "O pregão de três dias por Judá e Jerusalém",
    subtitle: "Ed 10:7-8 — o edital do arauto na esquina da praça alta, com prazo e pena escritos",
    text: "\"E fizeram passar pregão por Judá e Jerusalém, a todos os que vieram do cativeiro, para que se ajuntassem em Jerusalém\" (Ed 10:7). O prazo é curto e a pena está no versículo seguinte: \"E que todo aquele que em três dias não viesse, segundo o conselho dos príncipes e dos anciãos, toda a sua fazenda se poria em interdito, e ele seria separado da congregação dos do cativeiro\" (Ed 10:8) — confisco e excomunhão. Interdito é o herem, a coisa votada e retirada do uso comum, a mesma palavra do despojo de Jericó que Acã tomou para si (Js 6:17-18; 7:1). Não é multa: é a fazenda inteira posta fora do alcance do dono. O quadro tem trombeta, rolo do edital, a torre da muralha e a estrada abrindo para as cidades de Judá, e a conta começa a correr assim que o som acaba. Funcionou: no terceiro dia, \"todos os homens de Judá e Benjamim em três dias se ajuntaram em Jerusalém\" (Ed 10:9) — debaixo das grandes chuvas do nono mês.",
  },
  "rol-da-inquiricao-de-mes-a-mes": {
    title: "O rol da inquirição, aberto no primeiro dia do décimo mês",
    subtitle: "Ed 10:16-17 — a mesa comprida da comissão, com o candeeiro aceso desde cedo porque é inverno",
    text: "A assembleia debaixo da chuva não decidiu caso nenhum: decidiu como se decidiria. \"Ora, ponham-se os nossos líderes, por toda a congregação sobre este negócio; e todos os que em nossas cidades casaram com mulheres estrangeiras venham em tempos apontados, e com eles os anciãos de cada cidade, e os seus juízes\" (Ed 10:14) — audiências marcadas, cidade por cidade, com os anciãos e os juízes locais presentes, e não sentença em massa numa praça alagada. \"E assim o fizeram os que voltaram do cativeiro; e o sacerdote Esdras e os homens, chefes dos pais, segundo a casa de seus pais, e todos pelos seus nomes, foram apontados; e assentaram-se no primeiro dia do décimo mês, para inquirirem neste negócio. E no primeiro dia do primeiro mês acabaram de tratar com todos os homens que casaram com mulheres estrangeiras\" (Ed 10:16-17). Três meses inteiros de trabalho, caso a caso, no inverno. Este rolo é o resultado: a lista de nomes que ocupa o resto do capítulo, casa por casa e ofício por ofício, e que acaba no versículo 44 sem uma linha de consolo.",
  },
  "altar-do-delito-dos-sacerdotes": {
    title: "O altar do carneiro do rebanho oferecido pelo delito",
    subtitle: "Ed 10:19 — o único sacrifício de todo o capítulo, oferecido pela primeira casa da lista",
    text: "\"E deram as suas mãos prometendo que despediriam suas mulheres; e, achando-se culpados, ofereceram um carneiro do rebanho pelo seu delito\" (Ed 10:19). Dar a mão é o gesto de penhor, o mesmo que Ezequias pedira a Israel — \"dai a mão ao Senhor\" (2Cr 30:8) —, e o carneiro é a oferta pela culpa de Levítico 5:15, exigida de quem pecasse \"por ignorância nas coisas sagradas do Senhor\": \"um carneiro sem defeito do rebanho\". O detalhe importa: só os quatro sacerdotes da casa de Jesuá, filho de Jozadaque, aparecem oferecendo — a lista dos que se seguem, dezenas de nomes, não traz sacrifício nenhum. Quem servia ao altar teve de passar pelo altar. É o único fogo aceso em Esdras 10, num capítulo que é quase todo chuva, câmara fechada e lista de nomes; e a mão dada, que devia valer por si, é paga com um animal que entra no quadro vivo, ao lado da chama.",
  },
  "banca-da-rua-dos-filhos-de-bani": {
    title: "A banca do mercado na rua dos filhos de Bani",
    subtitle: "Ed 10:37 — meio-dia na feira, e três nomes achados no meio da negociação",
    text: "A casa de Bani é a que mais vezes volta na lista final do livro: abre-se em nove versículos seguidos (Ed 10:34-42) e a cena não a reúne numa sala — espalha-a pelos lugares de trabalho, um trio por vez. Este quadro é o do meio-dia: o toldo listrado, a fruta na bancada, os cachos pendurados, a jarra do azeite, a porta do pátio atrás. \"Matanias, Matnai e Jaasai\" (Ed 10:37) são chamados de dentro da negociação, com a mão ainda na mercadoria. A escolha do lugar diz o que a lista faz: a inquirição de três meses não foi um tribunal com réus algemados, foi gente sendo procurada onde estava — no poço, na eira, no terraço, na vinha, no olival, no campo fora do muro e aqui, na feira. E o nome de cada um foi escrito. É essa a diferença entre o capítulo 10 de Esdras e uma purga: cada homem entra no rol por nome próprio, com casa e ofício declarados, e o texto não esconde que \"alguns deles tinham mulheres de quem tiveram filhos\" (Ed 10:44).",
  },
};
