// Fichas ESPECÍFICAS por (capítulo → papel) de 2 CRÔNICAS 21–26.
// Seis reinados encaixados uns nos outros como caixas de um mesmo desastre: o
// primogênito que se firma no trono matando os seis irmãos e recebe, único em
// toda a Escritura, uma CARTA ESCRITA DE ELIAS; o filho de um ano de reinado
// cuja mãe "era sua conselheira, para proceder impiamente"; a avó que destrói a
// descendência real e o bebê furtado para a câmara dos leitos; o sacerdote que
// "se animou" no sétimo ano e coroou um menino de sete anos com o testemunho na
// mão; o rei que devolveu cem talentos de prata e depois se prostrou diante dos
// deuses do povo que acabara de vencer; e o REI LAVRADOR, que cavou poços no
// deserto porque "era amigo da agricultura" e acabou leproso numa casa separada.
// Cada figurante anônimo da cena é alguém REAL daquele capítulo: o levita que
// leu a carta em voz alta, a ama que escondeu o menino, o homem do povo que
// lançou no cofre furado, o vinhateiro dos montes, o sacerdote que segurou o
// braço do rei leproso junto ao altar do incenso.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_21_26: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- 2Cr 21
  21: {
    anciao: {
      title: "O sacerdote do enterro de Jeosafá, o guardião da lâmpada de Davi, o sacerdote de Libna e o médico da casa do rei",
      subtitle: "2Cr 21 • os homens de cabeça branca que enterram um rei bom, guardam a promessa e veem outro apodrecer por dentro",
      text: "O primeiro entra em cena antes de qualquer maldade: é o sacerdote que recolhe Jeosafá ao jazigo — \"Depois Jeosafá dormiu com seus pais, e foi sepultado junto a eles na cidade de Davi\" (2Cr 21:1) —, o mesmo rei de quem se dirá, capítulos adiante, que \"buscou ao Senhor com todo o seu coração\" (2Cr 22:9). O segundo é o velho do santuário que continua acendendo o candeeiro enquanto o novo rei enche os montes de altos: a razão de o culto não se apagar está escrita em 21:7 — \"Porém o Senhor não quis destruir a casa de Davi, em atenção à aliança que tinha feito com Davi; e porque também tinha falado que lhe daria por todos os dias uma lâmpada, a ele e a seus filhos\". O terceiro é o sacerdote de Libna, e não é detalhe: Libna era cidade dada aos filhos de Arão (Js 21:13), e o texto explica a revolta pelo lado de dentro — \"Libna se revoltou contra o seu mando; porque deixara ao Senhor Deus de seus pais\" (2Cr 21:10); quando até a cidade sacerdotal fecha as portas ao rei, o problema já não é político. O último é o médico da corte, que assiste dois anos a uma doença que nenhuma arte alcança — \"o Senhor o feriu nas suas entranhas com uma enfermidade incurável\" (2Cr 21:18) —, e cuja impotência o avô do rei já experimentara: \"na sua enfermidade, não buscou ao Senhor, mas antes os médicos\" (2Cr 16:12)."
    },
    cavaleiro: {
      title: "O capitão dos carros de Jeorão na saída noturna contra Edom",
      subtitle: "2Cr 21:9 • o oficial que rompeu o cerco de noite e ainda assim perdeu Edom",
      text: "\"Por isso Jeorão passou adiante com os seus príncipes, e todos os carros com ele; levantou-se de noite, e feriu aos edomeus, que o tinham cercado, como também aos capitães dos carros\" (2Cr 21:9). O quadro é de escape, não de vitória: o exército de Judá acordou cercado no planalto vermelho e abriu caminho no escuro para não ser desfeito ao amanhecer. Este homem conduz os carros que salvaram o rei — e o versículo seguinte lhe tira qualquer glória: \"Todavia os edomitas se revoltaram contra o mando de Judá até ao dia de hoje\" (2Cr 21:10). Edom estava sujeito a Judá desde Davi (2Sm 8:14) e ainda no reinado do pai deste rei não tinha rei próprio (1Rs 22:47); foi debaixo de Jeorão que se soltou, e nunca mais voltou. Um oficial pode ganhar a noite e perder o país no mesmo capítulo."
    },
    homem: {
      title: "Azarias, Jeiel, Zacarias, Asarias, Micael e Sefatias, os príncipes de Israel mortos com eles, e os edomeus, os filisteus e os árabes que vieram depois",
      subtitle: "2Cr 21 • os seis irmãos nomeados dois versículos antes de serem apagados, e os inimigos que o SENHOR despertou",
      text: "O capítulo faz questão de dar a lista por extenso, justamente porque ela vai durar dois versículos: \"E teve irmãos, filhos de Jeosafá: Azarias, Jeiel, Zacarias, Asarias, Micael e Sefatias\" (2Cr 21:2). O pai os deixara bem postos — \"muitos presentes de prata, de ouro e de coisas preciosíssimas, juntamente com cidades fortificadas em Judá\" (2Cr 21:3) —, e o irmão mais velho, que recebera o reino inteiro, não suportou nem isso: \"E, subindo Jeorão ao reino de seu pai, e havendo-se fortificado, matou a todos os seus irmãos à espada, como também a alguns dos príncipes de Israel\" (2Cr 21:4). A carta de Elias dirá o que ninguém em Jerusalém teve coragem de dizer: eram \"melhores do que tu\" (2Cr 21:13). Depois deles entram no quadro os inimigos que o texto não atribui ao acaso: os edomeus que cercaram o rei de noite (21:9), os moradores de Libna, os sacerdotes dos altos que ele fez nos montes de Judá (21:11), e por fim os saqueadores — \"Despertou, pois, o Senhor, contra Jeorão o espírito dos filisteus e dos árabes, que estavam do lado dos etíopes\" (2Cr 21:16). No último quadro sobram dois coveiros abrindo uma cova na cidade de Davi, \"porém não nos sepulcros dos reis\" (2Cr 21:20)."
    },
    mulherComum: {
      title: "A filha de Acabe, mulher de Jeorão, e as mulheres do rei levadas cativas do arraial",
      subtitle: "2Cr 21 • o casamento que trouxe o Norte para dentro de Judá, e as esposas arrastadas pelos árabes",
      text: "A frase que explica o reinado inteiro é uma frase de casamento: \"E andou no caminho dos reis de Israel, como fazia a casa de Acabe; porque tinha a filha de Acabe por mulher\" (2Cr 21:6). Atalia entra na casa de Davi por aliança de família — costurada pelo próprio Jeosafá, de quem se diz que \"aparentou-se com Acabe\" (2Cr 18:1) — e vai custar, no capítulo 22, quase toda a linhagem da promessa. Ao lado dela estão as outras mulheres da casa real, que não decidiram nada e pagaram tudo: quando filisteus e árabes sobem contra Judá, \"levaram todos os bens que se achou na casa do rei, como também a seus filhos e a suas mulheres\" (2Cr 21:17). É o cumprimento exato do que o escrito de Elias anunciara — \"o Senhor ferirá com um grande flagelo ao teu povo, aos teus filhos, às tuas mulheres e a todas as tuas fazendas\" (2Cr 21:14). O rei que matou a própria família para reinar sozinho terminou, de fato, sozinho."
    },
    rei: {
      title: "Jeosafá recolhido ao jazigo, Jeorão firmado no trono, e o rei que Edom constituiu para si",
      subtitle: "2Cr 21 • três coroas num capítulo: a que se apaga, a que mata, e a que se levanta contra Judá",
      text: "O capítulo abre com um enterro e uma posse no mesmo versículo: \"Depois Jeosafá dormiu com seus pais, e foi sepultado junto a eles na cidade de Davi; e Jeorão, seu filho, reinou em seu lugar\" (2Cr 21:1). O que herda tem trinta e dois anos e reina oito (21:5), e faz da primeira hora de poder uma chacina de irmãos (21:4). O terceiro trono nasce da revolta: \"Nos seus dias se revoltaram os edomitas contra o mando de Judá, e constituíram para si um rei\" (2Cr 21:8) — a primeira vez, desde Davi, que Edom tem rei próprio, e o cumprimento tardio do que Isaque profetizara a Esaú, \"sacudirás o seu jugo do teu pescoço\" (Gn 27:40). O fim de Jeorão é o mais duro do livro: dois anos de doença nas entranhas, o povo que \"não lhe queimou aroma como queimara a seus pais\" (21:19), e um epitáfio de cinco palavras — \"e foi sem deixar de si saudades\" (2Cr 21:20). Reinou oito anos e ninguém sentiu falta."
    },
    servo: {
      title: "O levita que leu em voz alta o escrito de Elias, os moços do trono e do leito, e Jeoacaz, o mais moço dos filhos do rei",
      subtitle: "2Cr 21 • quem serve num palácio onde a carta do profeta é a única voz honesta",
      text: "O criado principal desta cena é o que ninguém espera: o homem que abriu o rolo diante do rei e leu em voz alta a única palavra ESCRITA de Elias que a Escritura guardou — \"Então lhe veio um escrito da parte de Elias, o profeta, que dizia: Assim diz o Senhor Deus de Davi teu pai\" (2Cr 21:12). Elias não aparece; o que chegou de Israel a Jerusalém foi papel, e o papel disse tudo: \"mataste a teus irmãos da casa de teu pai, melhores do que tu\" (21:13) e \"terás grande enfermidade por causa de uma doença em tuas entranhas, até que elas saiam, de dia em dia\" (21:15). Os outros servos são os que ficam: o moço que acende o candeeiro num salão sem parentes, o levita que guarda a lâmpada de Davi enquanto o rei faz altos nos montes, o criado que troca os panos do leito durante dois anos até que \"saíram-lhe as entranhas por causa da doença\" (21:19). E há, na cena do saque, os filhos do rei levados presos com as mães — todos, menos um: \"de modo que não lhe deixaram filho algum, senão a Jeoacaz, o mais moço de seus filhos\" (2Cr 21:17). Esse menino poupado é o Acazias do capítulo seguinte: a casa de Davi passa por um fio, e passa pelo caçula."
    }
  },

  // ---------------------------------------------------------------- 2Cr 22
  22: {
    anciao: {
      title: "O ancião de Jerusalém que aclamou o filho mais moço por falta de outro",
      subtitle: "2Cr 22:1 • a cabeça branca que faz rei o caçula porque a tropa matou todos os mais velhos",
      text: "\"E os moradores de Jerusalém, em lugar de Jeorão, fizeram rei a Acazias, seu filho mais moço, porque a tropa, que viera com os árabes ao arraial, tinha matado a todos os mais velhos\" (2Cr 22:1). Este é o homem que preside a uma aclamação feita por falta de candidatos: não há assembleia festiva, não há profeta ungindo, não há escolha — há um resto. A casa de Davi chega ao trono pelo que sobrou do saque do capítulo anterior (2Cr 21:17), e o ancião que levanta a mão do rapaz sabe disso. O que o texto acrescenta em seguida é o retrato de uma corte inteira aconselhada pelo Norte: \"porque eles eram seus conselheiros depois da morte de seu pai, para a sua perdição\" (2Cr 22:4). Anciãos existem para lembrar a Lei; estes ficaram calados enquanto a casa de Acabe governava por dentro."
    },
    cavaleiro: {
      title: "O cavaleiro sírio de Hazael que feriu Jorão em Ramote de Gileade",
      subtitle: "2Cr 22:5 • a lança da Síria que abriu a ferida por onde entrou o juízo",
      text: "\"Também andou nos conselhos deles, e foi com Jorão, filho de Acabe, rei de Israel, à peleja contra Hazael, rei da Síria, junto a Ramote de Gileade; e os sírios feriram a Jorão\" (2Cr 22:5). Ramote de Gileade é chão marcado: foi ali que Acabe, o pai deste Jorão, morreu com Jeosafá ao lado (2Cr 18:33-34) — e agora o filho de Acabe e o neto de Jeosafá repetem, ponto por ponto, a mesma aliança e a mesma estrada. O golpe deste cavaleiro não mata ninguém em cena; apenas manda o rei ferido para Jizreel, e é a visita ao ferido que põe Acazias na frente de Jeú. Hazael, que o desfere, era o homem que Eliseu vira com lágrimas nos olhos (2Rs 8:11-13), ungido para ser o açoite de Israel. A lança de um soldado anônimo faz aqui o trabalho de um relógio."
    },
    homem: {
      title: "Os conselheiros da casa de Acabe, os príncipes de Judá e os filhos dos irmãos de Acazias mortos por Jeú, e o algoz que Atalia mandou",
      subtitle: "2Cr 22 • os homens que aconselharam para a perdição, os que morreram no juízo e o que degolou a descendência real",
      text: "Primeiro estão os conselheiros: \"E fez o que era mau aos olhos do Senhor, como a casa de Acabe, porque eles eram seus conselheiros depois da morte de seu pai, para a sua perdição\" (2Cr 22:4). Um rei de um ano de reinado governado por gente do Norte — e o texto não deixa dúvida de quem os pôs ali (22:3). Depois vêm os que caem: \"E sucedeu que, executando Jeú juízo contra a casa de Acabe, achou os príncipes de Judá e os filhos dos irmãos de Acazias, que serviam a Acazias, e os matou\" (2Cr 22:8) — a corte inteira de Jerusalém varrida numa estrada de Israel, porque tinha ido servir onde não devia. E entram, por fim, os homens de Jeú que vasculham Samaria atrás do rei escondido (22:9), e o algoz da rainha-mãe, que executa a ordem mais fria do livro: \"levantou-se e destruiu toda a descendência real da casa de Judá\" (2Cr 22:10). Nenhum inimigo estrangeiro conseguira isso; conseguiu-o uma avó dentro do próprio palácio."
    },
    mulherComum: {
      title: "Atalia, filha de Onri; Jeosabeate, filha do rei; e a ama que segurou o menino no colo",
      subtitle: "2Cr 22 • a mulher que destruiu a semente real e as duas que salvaram a promessa numa noite",
      text: "\"Era da idade de quarenta e dois anos, quando começou a reinar, e reinou um ano em Jerusalém; e era o nome de sua mãe Atalia, filha de Onri\" (2Cr 22:2), e o versículo seguinte diz o resto: \"porque sua mãe era sua conselheira, para proceder impiamente\" (22:3). Morto o filho, ela faz o que a Escritura não registra de mais ninguém em Judá: \"levantou-se e destruiu toda a descendência real da casa de Judá\" (2Cr 22:10). Contra isso levanta-se outra mulher da mesma casa: \"Porém Jeosabeate, filha do rei, tomou a Joás, filho de Acazias, furtando-o dentre os filhos do rei, aos quais matavam, e o pôs com a sua ama na câmara dos leitos\" (2Cr 22:11) — e o Cronista acrescenta o que 2 Reis não diz, que ela era \"mulher do sacerdote Joiada\", o que explica como um bebê pôde sumir dentro do templo. A terceira é a ama, que não tem nome nem fala e faz o serviço mais perigoso da cena: manter uma criança de colo calada e viva por seis anos num quarto sem janela (22:12). Toda a promessa feita a Davi coube, naquela noite, nos braços de duas mulheres."
    },
    multidao: {
      title: "Os moradores de Jerusalém que fizeram rei a Acazias",
      subtitle: "2Cr 22:1 • a cidade que aclamou o único filho que os árabes não levaram",
      text: "\"E os moradores de Jerusalém, em lugar de Jeorão, fizeram rei a Acazias, seu filho mais moço, porque a tropa, que viera com os árabes ao arraial, tinha matado a todos os mais velhos\" (2Cr 22:1). É a mesma cidade que, no capítulo anterior, o pai dele \"fez com que se corrompesse\" (2Cr 21:11), e que agora se ajunta à porta para levantar um rei porque não sobrou outro. A aclamação é legítima e é trágica ao mesmo tempo: o povo faz o que lhe compete e o resultado dura doze meses. Um ano depois, essa mesma multidão estará debaixo do governo de uma mulher de Samaria, e passarão seis anos até que ela torne a se ajuntar num pátio — e daquela vez será para bater palmas por um menino de sete anos (2Cr 23:11-13)."
    },
    rei: {
      title: "Acazias de Judá, Jorão de Israel, Hazael da Síria, Jeú filho de Ninsi — e o menino Joás",
      subtitle: "2Cr 22 • quatro coroas na mesma estrada de Jizreel, e a quinta escondida num quarto",
      text: "Acazias reina um ano (22:2) e o gasta inteiro nos conselhos da casa de Acabe. Vai com Jorão de Israel contra Hazael em Ramote (22:5), desce a Jizreel para ver o ferido, e o Cronista dá ao passeio um nome teológico: \"Foi, pois, da vontade de Deus, que Acazias, para sua ruína, visitasse Jorão\" (2Cr 22:7). Na estrada está Jeú, \"a quem o Senhor tinha ungido para desarraigar a casa de Acabe\" (22:7), cumprindo o que fora dito a Elias em Horebe (1Rs 19:16-17). Acazias é achado escondido em Samaria e morto — e sepultado assim mesmo, por uma razão que atravessa três gerações: \"porque disseram: Filho é de Jeosafá, que buscou ao Senhor com todo o seu coração\" (2Cr 22:9). Um bisavô fiel comprou-lhe uma sepultura. Sobra a quinta coroa, que ninguém vê: \"E esteve com eles seis anos escondido na casa de Deus; e Atalia reinou sobre a terra\" (2Cr 22:12)."
    },
    servo: {
      title: "Os moços do palácio, o servo do leito de Jorão em Jizreel, e os filhos do rei aos quais matavam",
      subtitle: "2Cr 22 • quem serve numa casa onde a ordem do dia é degolar os netos",
      text: "Servir nesta corte é servir a dois senhores: o trono de Judá está em Jerusalém, mas as ordens vêm da casa de Acabe (22:3-4). Um dos criados desta cena passa o capítulo em Jizreel, trocando os panos das feridas do rei do Norte — \"E voltou para curar-se em Jizreel, das feridas que lhe fizeram em Ramá, pelejando contra Hazael, rei da Síria\" (2Cr 22:6) —, e é ele quem abre a porta para a visita que arruinou o rei de Judá. Os outros são os moços do incensário e do ídolo que Atalia instalara dentro do palácio. E há, no quadro mais escuro do livro, as próprias crianças: o texto as chama, sem rodeio, de \"os filhos do rei, aos quais matavam\" (2Cr 22:11) — netos de uma mulher que os matava para reinar. De todos eles escapa um, tirado dali no colo, e é por causa desse um que existe, mil anos depois, uma genealogia que vai de Davi a Cristo (Mt 1:8-9)."
    }
  },

  // ---------------------------------------------------------------- 2Cr 23
  23: {
    anciao: {
      title: "Joiada, o sacerdote que se animou, e os chefes dos pais de Israel ajuntados de todas as cidades de Judá",
      subtitle: "2Cr 23:1-2 • os velhos que passaram seis anos calados e no sétimo ano moveram um país",
      text: "\"Porém no sétimo ano Joiada se animou\" (2Cr 23:1) — o verbo é esse, e é o eixo do capítulo. O sacerdote que escondera o menino na sua própria casa toma consigo em aliança cinco chefes de cem e manda percorrer a terra: \"Estes percorreram a Judá e ajuntaram os levitas de todas as cidades de Judá e os chefes dos pais de Israel, e vieram para Jerusalém\" (2Cr 23:2). Os chefes dos pais são as cabeças das famílias, os homens que respondem pelas casas — e é diante deles, e não diante de um exército, que Joiada mostra a criança: \"Eis que o filho do rei reinará, como o Senhor falou a respeito dos filhos de Davi\" (2Cr 23:3). O argumento não é dinástico, é de palavra dada: a promessa de 2Sm 7:16 posta em pé na frente de gente que a conhecia de cor. Joiada morrerá com cento e trinta anos e será sepultado entre os reis, \"porque tinha feito bem em Israel, e para com Deus e a sua casa\" (2Cr 24:16) — a única honra desse tipo em todo o livro."
    },
    cavaleiro: {
      title: "Os chefes de cem da aliança: Azarias filho de Jeroão, Ismael filho de Joanã, Azarias filho de Obede, Maaséias filho de Adaías e Elisafate filho de Zicri",
      subtitle: "2Cr 23 • os cinco centuriões que armaram o levante e depois tiraram Atalia das fileiras",
      text: "O Cronista dá os cinco nomes, com os patronímicos, porque num golpe de estado se sabe exatamente quem estava dentro: \"e tomou consigo em aliança os chefes de cem, a Azarias, filho de Jeroão, a Ismael, filho de Joanã, a Azarias, filho de Obede, a Maaséias, filho de Adaías, e a Elisafate, filho de Zicri\" (2Cr 23:1). São oficiais de tropa, não sacerdotes, e Joiada os arma com o arsenal do templo: \"Também o sacerdote Joiada deu aos capitàes de cem as lanças, os escudos e as rodelas que foram do rei Davi, os quais estavam na casa de Deus\" (2Cr 23:9). São eles que executam a única ordem de sangue do dia, com o cuidado de não a executar no lugar errado: \"Tirai-a para fora das fileiras, e o que a seguir, morrerá à espada; porque dissera o sacerdote: Não a mateis na casa do Senhor\" (2Cr 23:14). E são eles, ainda, que conduzem o menino do templo ao palácio no fim: \"E tomou os centuriões, os poderosos, os que tinham domínio entre o povo e todo o povo da terra, e conduziram o rei da casa do Senhor\" (2Cr 23:20)."
    },
    homem: {
      title: "Os chefes de cem vindos de Judá, os homens do povo em guarda diante do SENHOR, e os que derrubaram a casa de Baal",
      subtitle: "2Cr 23 • quem toma posto sem entrar no santuário, e quem quebra o templo do outro lado da cidade",
      text: "A ordem de serviço de Joiada é minuciosa e tem uma linha que ninguém pode cruzar: \"Porém ninguém entre na casa do Senhor, senão os sacerdotes e os levitas que ministram; estes entrarão, porque são santos; mas todo o povo fará a guarda diante do Senhor\" (2Cr 23:6). Estes homens são justamente os de fora dessa linha: gente comum, armada, plantada nos pátios e nas portas — \"e todo o povo estará nos pátios da casa do Senhor\" (23:5) —, cumprindo o dia inteiro uma disciplina que num levante costuma ser a primeira coisa a se perder. Depois da coroação, são eles que atravessam a cidade para o único ato de demolição do capítulo: \"Depois todo o povo entrou na casa de Baal, e a derrubaram, e quebraram os seus altares, e as suas imagens, e a Matã, sacerdote de Baal, mataram diante dos altares\" (2Cr 23:17). Coroar o rei legítimo e derrubar o templo estrangeiro são, aqui, um só movimento: a aliança de 23:16 tem consequência de picareta."
    },
    mulherComum: {
      title: "Atalia, que rasgou os seus vestidos e clamou: Traição, traição!",
      subtitle: "2Cr 23:12-15 • os últimos minutos de seis anos de reinado sobre a casa de Davi",
      text: "\"Ouvindo, pois, Atalia a voz do povo que concorria e louvava o rei, veio ao povo, à casa do Senhor\" (2Cr 23:12) — ela vem sozinha, sem guarda, porque não imagina o que vai ver. E vê o impossível: \"E olhou, e eis que o rei estava junto à coluna, à entrada\" (2Cr 23:13), com as trombetas junto ao rei e \"todo o povo da terra estava alegre e tocava as trombetas\" (2Cr 23:13), e \"então Atalia rasgou os seus vestidos, e clamou: Traição, traição!\" (2Cr 23:13). A palavra é dela e é o retrato dela: quem destruiu a descendência real da casa de Judá (22:10) chama de traição a volta do herdeiro legítimo. Joiada não deixa que o santuário seja manchado — \"Não a mateis na casa do Senhor\" (23:14) —, e a sentença sai andando: \"E lançaram mão dela; e ela foi pelo caminho da entrada da porta dos cavalos, à casa do rei, e ali a mataram\" (2Cr 23:15). Sai do templo pela porta de serviço das montarias, e a cidade fica em paz (23:21)."
    },
    multidao: {
      title: "Toda a congregação que fez aliança com o rei na casa de Deus e todo o povo da terra que tocava as trombetas",
      subtitle: "2Cr 23 • o povo que enche os pátios, jura o pacto, aclama o menino e sai em paz",
      text: "É a assembleia que Joiada ajuntou de todas as cidades de Judá (23:2) e que, dentro do templo, se compromete antes de qualquer coisa: \"E toda aquela congregação fez aliança com o rei na casa de Deus\" (2Cr 23:3). Recebe posto e disciplina — \"todo o povo estará nos pátios da casa do Senhor\" (23:5), \"todo o povo fará a guarda diante do Senhor\" (23:6) —, e no instante da coroação irrompe no grito mais curto e mais alegre do livro: \"e o fizeram rei; e Joiada e seus filhos o ungiram, e disseram: Viva o rei!\" (2Cr 23:11); em 2Rs 11:12 acrescenta-se o gesto — \"e bateram as palmas\". Depois vem a segunda aliança, agora entre os três lados: \"E Joiada fez aliança entre si e o povo e o rei, para que fossem o povo do Senhor\" (2Cr 23:16). O capítulo fecha com esta mesma gente indo para casa: \"E todo o povo da terra se alegrou, e a cidade ficou em paz, depois que mataram a Atalia à espada\" (2Cr 23:21)."
    },
    rei: {
      title: "Joás, o filho do rei tirado para fora com a coroa e o testemunho",
      subtitle: "2Cr 23:11 • sete anos de idade, seis deles escondido, e um dia inteiro em pé diante de todos",
      text: "\"Então tiraram para fora ao filho do rei, e lhe puseram a coroa; deram-lhe o testemunho, e o fizeram rei; e Joiada e seus filhos o ungiram, e disseram: Viva o rei!\" (2Cr 23:11). A criança que sai daquela porta passou seis anos escondida na casa de Deus (22:12) e não conhece outra casa; o mundo inteiro dela cabia num quarto, e agora está no eixo de um pátio cheio. Recebe duas coisas ao mesmo tempo, e a ordem importa: a coroa e o TESTEMUNHO — o documento da aliança —, exatamente como a lei mandava que se fizesse com o rei em Israel: \"escreverá para si num livro, um traslado desta lei\" e \"nele lerá todos os dias da sua vida\" (Dt 17:18-19). Depois é levado do templo ao palácio, e não o contrário: \"conduziram o rei da casa do Senhor, e entraram na casa do rei passando pela porta maior, e assentaram-no no trono real\" (2Cr 23:20). Enquanto houver quem lhe leia aquele rolo, o reinado será bom (2Cr 24:2)."
    },
    servo: {
      title: "Os levitas vindos de todas as cidades, os guardas das três portas, os porteiros, os cantores e o sacerdote do holocausto",
      subtitle: "2Cr 23 • quem larga a cidade pequena para fazer turno num golpe de estado — e depois recompõe o culto",
      text: "São os homens que Joiada mandou buscar por Judá inteira (23:2) e que ele reparte em três turmas com precisão de quem preparou aquilo por seis anos: \"uma terça parte de vós, ou seja, dos sacerdotes e dos levitas que entram no sábado, serão guardas das portas\" (2Cr 23:4), \"E uma terça parte estará na casa do rei; e a outra terça parte à porta do fundamento\" (2Cr 23:5). O truque do dia está numa linha administrativa: \"e tomou cada um os seus homens, tanto os que entravam no sábado como os que saíam no sábado; porque o sacerdote Joiada não tinha despedido as turmas\" (2Cr 23:8) — ele dobrou o efetivo sem que ninguém notasse, apenas não mandando embora a guarda que saía. Em volta do menino ficam os que podem estar ali: \"E os levitas cercarão o rei de todos os lados, cada um com as suas armas na mão\" (23:7). Passado o dia, os mesmos homens voltam ao ofício que era deles desde Davi: os cantores que \"dirigiam o cantar de louvores\" (23:13), os holocaustos oferecidos \"como está escrito na lei de Moisés, com alegria e com canto\" (23:18), e os porteiros postos às portas \"para que nela não entrasse ninguém imundo em coisa alguma\" (2Cr 23:19)."
    }
  },

  // ---------------------------------------------------------------- 2Cr 24
  24: {
    anciao: {
      title: "Joiada, o chefe; os sacerdotes convocados pelo rei; e o oficial do sumo sacerdote que esvaziava o cofre",
      subtitle: "2Cr 24 • o velho que criou o rei, os sacerdotes cobrados pela demora e o homem de confiança da contagem",
      text: "O capítulo inteiro pende de um homem: \"E fez Joás o que era reto aos olhos do Senhor, todos os dias do sacerdote Joiada\" (2Cr 24:2). É Joiada quem lhe dá casa — \"E tomou-lhe Joiada duas mulheres\" (24:3) — e é a Joiada que o rei já adulto chama para cobrar: \"E o rei chamou a Joiada, o chefe, e disse-lhe: Por que não requereste dos levitas, que trouxessem de Judá e de Jerusalém o tributo que Moisés, servo do Senhor, ordenou à congregação de Israel, para a tenda do testemunho?\" (2Cr 24:6). Ao lado dele estão os sacerdotes reunidos na primeira convocação (24:5), os que ministram numa casa que os filhos de Atalia arruinaram e cujas coisas sagradas foram \"empregadas em Baalins\" (24:7), e o oficial do sumo sacerdote, que abre o cofre junto com o escrivão do rei — dois homens de casas diferentes conferindo o mesmo dinheiro (24:11). Quando o velho morre com cento e trinta anos e é sepultado com os reis (24:15-16), a estrutura moral do reinado morre com ele: no versículo seguinte já vêm os príncipes lisonjear o rei, \"e o rei os ouviu\" (24:17)."
    },
    cavaleiro: {
      title: "O capitão do exército da Síria que subiu contra Jerusalém com poucos homens",
      subtitle: "2Cr 24:23-24 • o oficial de Damasco a quem o SENHOR entregou um exército mui numeroso",
      text: "\"E sucedeu que, decorrido um ano, o exército da Síria subiu contra ele; e vieram a Judá e a Jerusalém, e destruíram dentre o povo a todos os seus príncipes; e enviaram todo o seu despojo ao rei de Damasco\" (2Cr 24:23). O ano contado é o ano depois do apedrejamento no pátio do templo, e o texto não deixa a coincidência sem explicação: \"Porque ainda que o exército dos sírios viera com poucos homens, contudo o Senhor entregou na sua mão um exército mui numeroso, porquanto deixaram ao Senhor Deus de seus pais. Assim executaram juízos contra Joás\" (2Cr 24:24). É o inverso exato de Gideão e dos trezentos (Jz 7:7): ali Deus reduziu os seus para mostrar quem vencia; aqui deixa que uns poucos estrangeiros desfaçam um exército grande, e pelo mesmo motivo. Os príncipes destruídos são os mesmos que se prostraram diante do rei em 24:17 e o levaram a deixar a casa do SENHOR."
    },
    homem: {
      title: "O arauto do pregão, os príncipes que lançaram no cofre, os pedreiros, carpinteiros e ferreiros da obra — e os que apedrejaram Zacarias no pátio",
      subtitle: "2Cr 24 • os mesmos homens de Judá nas duas metades do capítulo: alegres diante do cofre, e depois com pedras na mão",
      text: "Na primeira metade, este é o país inteiro trabalhando: o arauto que sai pelas praças — \"E publicou-se em Judá e em Jerusalém que trouxessem ao Senhor o tributo de Moisés, o servo de Deus, ordenado a Israel no deserto\" (2Cr 24:9) —, os príncipes e o povo diante da caixa furada — \"Então todos os príncipes e todo o povo se alegraram, e o trouxeram e o lançaram no cofre, até que ficou cheio\" (24:10) —, e o canteiro de obras dentro do templo: \"contrataram pedreiros e carpinteiros, para renovarem a casa do Senhor; como também ferreiros e serralheiros, para repararem a casa do Senhor\" (24:12), até que \"restauraram a casa de Deus no seu estado, e a fortaleceram\" (24:13). Na segunda metade, os mesmos homens mudam de mão: os príncipes vêm lisonjear o rei e o levam a deixar a casa que acabaram de reformar (24:17-18), os profetas enviados encontram gente que \"não deram ouvidos\" (24:19), e no fim há pedra: \"E eles conspiraram contra ele, e o apedrejaram por mandado do rei, no pátio da casa do Senhor\" (2Cr 24:21). Restauraram as paredes e apedrejaram um profeta dentro delas."
    },
    mulherComum: {
      title: "Zíbia de Berseba, mãe do rei, e as duas mulheres que Joiada tomou para Joás",
      subtitle: "2Cr 24:1-3 • as mulheres da casa do menino que cresceu no templo",
      text: "\"Tinha Joás sete anos de idade quando começou a reinar, e quarenta anos reinou em Jerusalém; e era o nome da sua mãe Zíbia, de Berseba\" (2Cr 24:1). O Cronista dá o nome e a cidade da rainha-mãe como faz com todos os reis de Judá, e neste caso a linha vale duplo: a mãe é de Berseba, no extremo sul, e não da casa de Acabe — depois de Atalia, o texto faz questão de dizer de onde veio a mulher que gerou o herdeiro. As outras duas são as esposas que o sacerdote escolheu para o rapaz: \"E tomou-lhe Joiada duas mulheres, e gerou filhos e filhas\" (2Cr 24:3). É Joiada quem cuida da descendência de um menino que quase não teve família — depois de a avó ter destruído \"toda a descendência real da casa de Judá\" (22:10), a lâmpada de Davi volta a ter chama porque um velho sacerdote tratou de casar o último dos filhos do rei."
    },
    multidao: {
      title: "O povo de Judá que ouviu o pregão, lançou no cofre com alegria e enterrou Joiada",
      subtitle: "2Cr 24 • a multidão que resolveu num dia o que vinte e três anos de ordens não resolveram",
      text: "Este povo aparece três vezes, e as três valem a pena. Ouve o edital do tributo de Moisés lido em praça pública, oito séculos depois de ter sido ordenado no deserto (2Cr 24:9). Responde a ele com uma alegria que o texto registra sem economia: \"Então todos os príncipes e todo o povo se alegraram, e o trouxeram e o lançaram no cofre, até que ficou cheio\" (2Cr 24:10) — e o que anos de circulares e de cobranças pelas cidades não conseguiram (24:5), uma caixa posta à porta, à vista de quem entra, resolveu. E enterra o sacerdote com honra de rei: \"E o sepultaram na cidade de Davi com os reis; porque tinha feito bem em Israel, e para com Deus e a sua casa\" (2Cr 24:16). Depois desse enterro, o mesmo povo deixa a casa do SENHOR e serve \"às imagens do bosque e aos ídolos\" (24:18): a devoção de uma multidão pode durar exatamente o tempo de vida do homem que a conduzia."
    },
    patriarca: {
      title: "Os profetas enviados para reconduzir Judá — e Zacarias, filho do sacerdote Joiada",
      subtitle: "2Cr 24:19-22 • as vozes que Deus mandou e a que foi apedrejada no pátio da sua própria casa",
      text: "\"Porém enviou profetas entre eles, para os reconduzir ao Senhor, os quais protestaram contra eles; mas eles não deram ouvidos\" (2Cr 24:19). Deus não abandona sem falar: manda homens, e são ignorados um a um. O último é o mais próximo de todos: \"E o Espírito de Deus revestiu a Zacarias, filho do sacerdote Joiada, o qual se pôs em pé acima do povo, e lhes disse: Assim diz Deus: Por que transgredis os mandamentos do Senhor, de modo que não possais prosperar? Porque deixastes ao Senhor, também ele vos deixará\" (2Cr 24:20). Ele é o filho do homem que criou o rei, e a resposta do rei é a ingratidão mais nua da Escritura: \"Assim o rei Joás não se lembrou da beneficência que Joiada, pai de Zacarias, lhe fizera; porém matou-lhe o filho, o qual, morrendo, disse: O Senhor o verá, e o requererá\" (2Cr 24:22). Seis palavras que atravessam o Antigo Testamento — e chegam ao Novo pela boca do próprio Senhor, que fecha a conta do sangue derramado \"desde o sangue de Abel, o justo, até ao sangue de Zacarias, filho de Baraquias, que matastes entre o santuário e o altar\" (Mt 23:35)."
    },
    rei: {
      title: "Joás, reto todos os dias do sacerdote Joiada — e Amazias, seu filho, que reinou em seu lugar",
      subtitle: "2Cr 24 • quarenta anos de reinado divididos ao meio por um enterro",
      text: "\"E fez Joás o que era reto aos olhos do Senhor, todos os dias do sacerdote Joiada\" (2Cr 24:2): a ressalva é o capítulo inteiro. Enquanto o velho vive, o rei resolve renovar a casa do SENHOR (24:4), cobra os levitas pela demora (24:6), inventa o cofre à porta (24:8) e vê o templo restaurado \"no seu estado\" (24:13). Morto Joiada, tudo desaba num versículo: \"vieram os príncipes de Judá e prostraram-se perante o rei; e o rei os ouviu\" (24:17) — e o mesmo homem que reformou o templo o abandona, manda apedrejar o filho do seu benfeitor no pátio dele (24:21), é ferido pelo pequeno exército da Síria e morre nas mãos dos seus: \"então seus servos conspiraram contra ele por causa do sangue do filho do sacerdote Joiada, e o feriram na sua cama, e morreu; e o sepultaram na cidade de Davi, porém não nos sepulcros dos reis\" (2Cr 24:25). O último versículo abre a página seguinte: \"e Amazias, seu filho, reinou em seu lugar\" (24:27)."
    },
    servo: {
      title: "Os levitas que não se apressaram, os que levavam o cofre de dia em dia — e Zabade e Jeozabade, que feriram o rei na cama",
      subtitle: "2Cr 24 • quem carrega a caixa do dinheiro e quem carrega a espada no fim",
      text: "Começam mal: mandados levantar dinheiro pelas cidades, \"Porém os levitas não se apressaram\" (2Cr 24:5) — quatro palavras que custaram anos de casa arruinada. Depois de o cofre resolver o problema, são eles a rotina que faz a obra andar: \"E sucedia que, quando levavam o cofre pelas mãos dos levitas, segundo o mandado do rei, e vendo-se que já havia muito dinheiro, vinha o escrivão do rei, e o oficial do sumo sacerdote, e esvaziavam o cofre, e tomavam-no e levavam-no de novo ao seu lugar; assim faziam de dia em dia, e ajuntaram dinheiro em abundância\" (2Cr 24:11). São também os que guardam os utensílios feitos do resto — \"colheres, vasos de ouro e de prata\" (24:14) — e os que velam o leito do sacerdote de cento e trinta anos (24:15). No fim do capítulo, porém, os servos da casa do rei aparecem do outro lado da lâmina, e o texto os nomeia com as mães: \"Zabade, filho de Simeate, a amonita, e Jeozabade, filho de Sinrite, a moabita\" (2Cr 24:26) — dois estrangeiros de nascimento executando, dentro do palácio, a conta que Zacarias deixou em aberto (24:22)."
    }
  },

  // ---------------------------------------------------------------- 2Cr 25
  25: {
    anciao: {
      title: "O sacerdote do livro de Moisés na corte de Amazias, Obede-Edom o guarda do tesouro, e o sacerdote do sepultamento do rei",
      subtitle: "2Cr 25 • os homens que lhe abriram a Lei, os que guardaram o ouro e os que o enterraram em Jerusalém",
      text: "O primeiro é o homem que abre o rolo na sala da lei e mostra ao rei o versículo que salvou duas crianças: \"Porém não matou os filhos deles; mas fez segundo está escrito na lei, no livro de Moisés, como o Senhor ordenou, dizendo: Não morrerão os pais pelos filhos, nem os filhos pelos pais; mas cada um morrerá pelo seu pecado\" (2Cr 25:4; a lei citada é Dt 24:16). É o melhor momento do reinado, e é feito com a Escritura aberta na mesa. O segundo é Obede-Edom, o nome que guarda o tesouro da casa de Deus quando Jeoás de Israel arromba Jerusalém: \"Também tomou todo o ouro, a prata, e todos os utensílios que se acharam na casa de Deus com Obede-Edom, e os tesouros da casa do rei, e os reféns\" (2Cr 25:24) — a casa levítica dos porteiros que desde Davi respondia pelas câmaras do tesouro (1Cr 26:15). O terceiro é o sacerdote do enterro: depois de Laquis, \"trouxeram-no sobre cavalos e sepultaram-no com seus pais na cidade de Judá\" (2Cr 25:28). Três velhos e três funções — a lei, o tesouro e a cova."
    },
    cavaleiro: {
      title: "O cavaleiro de Judá em Bete-Semes",
      subtitle: "2Cr 25:21-22 • o soldado montado que viu o exército inteiro fugir para as suas tendas",
      text: "\"E Jeoás, rei de Israel, subiu; e ele e Amazias, rei de Judá, viram-se face a face em Bete-Semes, que está em Judá\" (2Cr 25:21) — o encontro que o próprio Amazias pedira por escrito: \"Vem, vejamo-nos face a face\" (25:17). Este cavaleiro é da tropa que sobrou depois de os cem mil mercenários de Efraim terem sido despedidos (25:10), e está no campo pela decisão mais soberba do reinado, tomada contra o aviso de Jeoás — \"elevou-se o teu coração, para te gloriares; agora, pois, fica em tua casa\" (25:19). O resultado cabe em nove palavras: \"E Judá foi ferido diante de Israel; e fugiu cada um para a sua tenda\" (2Cr 25:22). Bete-Semes fica na Sefelá, em terra de Judá: o rei perdeu a batalha dentro de casa, e o vencedor seguiu estrada acima até derrubar quatrocentos côvados do muro de Jerusalém (25:23)."
    },
    homem: {
      title: "Os trezentos mil escolhidos de Judá e Benjamim, os cem mil valentes de Efraim que voltaram ardendo em ira, e os filhos de Seir lançados do cimo da rocha",
      subtitle: "2Cr 25 • os homens comprados a peso de prata, os que saquearam as cidades no caminho de casa e os que se despedaçaram",
      text: "Primeiro é a resenha: \"e os contou, de vinte anos para cima, e achou deles trezentos mil escolhidos que podiam sair à guerra, e manejar lança e escudo\" (2Cr 25:5). Depois vem a compra — \"Também de Israel tomou a soldo cem mil homens valentes, por cem talentos de prata\" (25:6) — e a devolução: despedidos por ordem do homem de Deus, \"voltaram para as suas casas ardendo em ira\" (25:10), e cobraram a conta sozinhos no caminho: \"deram sobre as cidades de Judá desde Samaria, até Bete-Horom; e feriram deles três mil, e saquearam grande despojo\" (25:13). Do outro lado estão os filhos de Seir: dez mil mortos no Vale do Sal (25:11) e outros dez mil levados vivos ao alto do penhasco — \"e do mais alto da rocha os lançaram abaixo, e todos se despedaçaram\" (2Cr 25:12). É a crueldade que a profecia de Obadias já pusera diante de Edom, o povo que habitava \"nas fendas das rochas\" (Ob 3). No fim do capítulo, homens de Israel derrubam o muro de Jerusalém e carregam o tesouro (25:23-24), e homens de Judá conspiram contra o próprio rei e o perseguem até Laquis (25:27)."
    },
    mulherComum: {
      title: "Joadã de Jerusalém, mãe do rei, e as mulheres das cidades de Judá saqueadas por Efraim",
      subtitle: "2Cr 25 • a rainha-mãe da cidade e as que pagaram por cem talentos de prata mal gastos",
      text: "\"Era Amazias da idade de vinte e cinco anos, quando começou a reinar, e reinou vinte e nove anos em Jerusalém; e era o nome de sua mãe Joadã, de Jerusalém\" (2Cr 25:1). Ao lado dela, sem nome e sem fala, estão as mulheres das cidades da fronteira norte — as que moravam no trecho \"desde Samaria, até Bete-Horom\" (25:13) — sobre quem caiu a ira dos cem mil despedidos. O rei fez a coisa certa ao mandar embora um exército que o SENHOR não estava com ele (25:7-10), mas fizera antes a coisa errada ao contratá-lo, e a conta não veio para ele: veio para três mil mortos e para o povo miúdo de aldeias que nunca souberam o que era um talento de prata. Obediência tardia ainda é obediência, e ainda assim há estragos que já não voltam atrás."
    },
    patriarca: {
      title: "O homem de Deus dos cem talentos e o profeta calado diante dos deuses de Seir",
      subtitle: "2Cr 25:7-9 e 25:15-16 • as duas vozes mandadas a Amazias, uma ouvida e outra mandada calar",
      text: "O primeiro chega sem ser chamado, ao campo do recenseamento: \"Ó rei, não deixes ir contigo o exército de Israel; porque o Senhor não é com Israel, a saber com os filhos de Efraim\" (2Cr 25:7). A objeção do rei é uma calculadora — \"Que se fará, pois, dos cem talentos de prata que dei às tropas de Israel?\" (25:9) —, e a resposta é a frase que resume toda a economia da fé: \"Mais tem o Senhor que te dar do que isso\" (2Cr 25:9). O rei obedece, e vence no Vale do Sal. O segundo profeta chega depois da vitória, quando o vencedor está de joelhos diante dos ídolos dos vencidos, e faz a pergunta que não tem resposta possível: \"Por que buscaste deuses deste povo, os quais não livraram o seu próprio povo da tua mão?\" (2Cr 25:15). Desta vez o rei manda calar — \"Puseram-te por conselheiro do rei? Cala-te!\" —, e o profeta obedece, com uma sentença: \"Então parou o profeta, e disse: Bem vejo eu que já Deus deliberou destruir-te; porquanto fizeste isto, e não deste ouvidos ao meu conselho\" (2Cr 25:16). O silêncio de um profeta pode ser o pior barulho que um rei já ouviu."
    },
    rebanho: {
      title: "Os animais do campo que passaram e pisaram o cardo",
      subtitle: "2Cr 25:18 • o gado solto da parábola do cardo e do cedro do Líbano",
      text: "São a única figura viva da resposta de Jeoás de Israel ao desafio de Amazias: \"O cardo que estava no Líbano mandou dizer ao cedro que estava no Líbano: Dá tua filha por mulher a meu filho; porém os animais do campo, que estavam no Líbano passaram e pisaram o cardo\" (2Cr 25:18). O golpe da parábola está aí: o cardo não é derrubado pelo cedro, nem numa disputa entre iguais — é pisado sem querer por um bando de bichos que passava. Não há batalha nenhuma, só desatenção. É a mesma forma de fábula que Jotão usara em Siquém, com as árvores escolhendo rei e o espinheiro se oferecendo (Jz 9:8-15), e o recado é o mesmo: quem se mede acima do seu tamanho não é vencido, é atropelado. Amazias \"não lhe deu ouvidos, porque isto vinha de Deus\" (25:20), e o cardo foi pisado em Bete-Semes."
    },
    rei: {
      title: "Amazias de Judá, reto porém não com inteireza de coração, e Jeoás de Israel, que lhe respondeu com uma parábola",
      subtitle: "2Cr 25 • o rei que devolveu cem talentos e depois adorou os deuses de quem venceu",
      text: "\"E fez o que era reto aos olhos do Senhor, porém não com inteireza de coração\" (2Cr 25:2) — e o capítulo passa vinte e oito versículos mostrando o que essa ressalva quer dizer na prática. Ele executa os assassinos do pai, mas poupa os filhos deles conforme a lei (25:3-4). Despede os cem mil mercenários e ganha a batalha (25:10-11). E logo depois faz a coisa mais absurda do livro: \"depois que Amazias veio da matança dos edomitas e trouxe consigo os deuses dos filhos de Seir, tomou-os por seus deuses, e prostrou-se diante deles, e queimou-lhes incenso\" (2Cr 25:14). Envaidecido, desafia o Norte — \"Vem, vejamo-nos face a face\" (25:17) — e recebe de Jeoás de Israel a parábola do cardo e do cedro e um conselho que não segue: \"fica em tua casa; por que te entremeterias no mal, para caíres tu e Judá contigo?\" (25:19). Acaba como o pai: derrota, muro arrombado em quatrocentos côvados, conspiração, fuga para Laquis e um corpo trazido de volta sobre cavalos (25:23-28)."
    },
    servo: {
      title: "Os moços da corte, os filhos de Zabade e de Jeozabade poupados pela lei, e o refém levado para Samaria",
      subtitle: "2Cr 25 • quem serve a um rei correto pela metade, e quem foi salvo justamente pela metade correta",
      text: "Os primeiros são as crianças que o capítulo não deixa morrer. O rei mandou matar os servos que feriram o pai na cama (24:25-26; 25:3), \"Porém não matou os filhos deles; mas fez segundo está escrito na lei, no livro de Moisés\" (2Cr 25:4). Num tempo em que a vingança dinástica varria casas inteiras — como Jeú fizera com a de Acabe, e Atalia com a de Davi —, dois meninos amanheceram vivos porque um rei foi ler antes de decidir. Depois vêm os criados do pátio dos ídolos de Seir, que acendem o incensário diante das imagens que o próprio rei trouxe da guerra (25:14); os moços do salão onde o profeta é mandado calar (25:16); e, no fim, os que saem de Jerusalém amarrados na bagagem de Israel: \"e os tesouros da casa do rei, e os reféns; e voltou para Samaria\" (2Cr 25:24). Um reinado que começou salvando duas crianças pela lei termina entregando reféns pela soberba."
    }
  },

  // ---------------------------------------------------------------- 2Cr 26
  26: {
    anciao: {
      title: "Azarias, o sumo sacerdote, e os oitenta sacerdotes valentes que resistiram ao rei junto ao altar do incenso",
      subtitle: "2Cr 26:17-20 • os homens que entraram atrás do rei no santo lugar e lhe disseram na cara que não era o lugar dele",
      text: "\"Porém o sacerdote Azarias entrou após ele, e com ele oitenta sacerdotes do Senhor, homens valentes\" (2Cr 26:17). O adjetivo é do texto e não é enfeite: é preciso valentia para barrar um rei de cinquenta anos de reinado, vitorioso sobre filisteus, árabes e meunitas, dentro do templo. A frase que lhe dizem é curta e não deixa margem: \"A ti, Uzias, não compete queimar incenso perante o Senhor, mas aos sacerdotes, filhos de Arão, que são consagrados para queimar incenso; sai do santuário, porque transgrediste; e não será isto para honra tua da parte do Senhor Deus\" (2Cr 26:18) — a lei que invocam foi escrita depois de Corá — \"que nenhum estranho, que não for da descendência de Arão, se chegue para acender incenso perante o Senhor\" (Nm 16:40). E foi diante deles que aconteceu: \"a lepra lhe saiu à testa perante os sacerdotes, na casa do Senhor, junto ao altar do incenso\" (26:19). Não o feriram nem o expulsaram à força primeiro: \"Então o sumo sacerdote Azarias olhou para ele, como também todos os sacerdotes, e eis que já estava leproso na sua testa, e apressuradamente o lançaram fora\" (26:20). São também estes homens que, anos depois, o enterram fora do jazigo — \"porque disseram: Leproso é\" (26:23)."
    },
    cavaleiro: {
      title: "Hananias, um dos capitàes do rei, sob cuja direção saía o exército em tropas",
      subtitle: "2Cr 26:11 • o oficial que comandava os trezentos e sete mil e quinhentos de Uzias",
      text: "\"Tinha também Uzias um exército de homens destros na guerra, que saíam à guerra em tropas, segundo o número da resenha feita por mão de Jeiel, o escrivão, e Maaséias, oficial, sob a direção de Hananias, um dos capitàes do rei\" (2Cr 26:11). Três nomes numa linha — o escrivão que conta, o oficial que registra e o capitão que comanda — porque este é um exército administrado, não uma leva improvisada: \"O total dos chefes dos pais, homens valentes, era de dois mil e seiscentos\" (26:12), e debaixo deles \"um exército guerreiro de trezentos e sete mil e quinhentos homens, que faziam a guerra com força belicosa, para ajudar o rei contra os inimigos\" (26:13). Hananias comanda a tropa mais bem equipada que Judá teve: escudos, lanças, capacetes, couraças, arcos e fundas preparados pelo próprio rei para todo o exército (26:14). E é justamente essa força que o texto aponta como a raiz da queda: \"Mas, havendo-se já fortificado, exaltou-se o seu coração até se corromper\" (26:16)."
    },
    homem: {
      title: "Os obreiros de Elote, os pedreiros das torres, os lavradores dos campos férteis, os armeiros do arsenal e os engenheiros das máquinas",
      subtitle: "2Cr 26 • os homens de ofício de um rei que passou cinquenta e dois anos construindo",
      text: "Este é o capítulo das mãos que trabalham. Começa no porto do golfo: \"Este edificou a Elote, e a restituiu a Judá, depois que o rei dormiu com seus pais\" (2Cr 26:2) — a escala das frotas de Salomão (1Rs 9:26) reaberta. Segue nos muros filisteus quebrados e nas cidades levantadas em cima deles: \"e quebrou o muro de Gate, o muro de Jabne, e o muro de Asdode; e edificou cidades em Asdode, e entre os filisteus\" (26:6). Depois vêm os pedreiros das três torres de Jerusalém — \"à porta da esquina, e à porta do vale, e à porta do ângulo\" (26:9) — e, no quadro mais bonito do trecho, os homens do campo: \"Também edificou torres no deserto, e cavou muitos poços, porque tinha muito gado, tanto nos vales como nas campinas; tinha lavradores, e vinhateiros, nos montes e nos campos férteis; porque era amigo da agricultura\" (2Cr 26:10). No fim entram os armeiros — \"E preparou Uzias, para todo o exército, escudos, lanças, capacetes, couraças e arcos, e até fundas para atirar pedras\" (26:14) — e os engenheiros: \"Também fez em Jerusalém máquinas da invenção de engenheiros, que estivessem nas torres e nos cantos, para atirarem flechas e grandes pedras\" (2Cr 26:15). Um reinado inteiro de cisternas, muros e engenhos — e o versículo seguinte diz o que a competência fez com o coração do homem."
    },
    mulherComum: {
      title: "Jecolia de Jerusalém, mãe do rei Uzias",
      subtitle: "2Cr 26:3 • a rainha-mãe do reinado mais longo de Judá",
      text: "\"Tinha Uzias dezesseis anos quando começou a reinar, e cinqüenta e dois anos reinou em Jerusalém; e era o nome de sua mãe Jecolia, de Jerusalém\" (2Cr 26:3). O Cronista registra o nome da mãe de cada rei de Judá, e aqui a linha marca o começo do reinado mais longo de toda a dinastia — mais longo que o de Davi, que o de Salomão e que o de Manassés seria depois. O menino que ela vê subir ao trono tem dezesseis anos e foi posto ali pelo povo da terra, depois de o pai ter sido assassinado em Laquis (26:1; 25:27). Ela não reaparece; o filho reina cinquenta e dois anos e morre numa casa separada, leproso, excluído da casa do SENHOR (26:21). Entre uma coisa e outra cabe a vida inteira de Isaías, que datará a sua visão do trono exatamente por esta morte: \"No ano em que morreu o rei Uzias, eu vi também ao Senhor assentado sobre um alto e sublime trono\" (Is 6:1)."
    },
    multidao: {
      title: "Todo o povo da terra que fez rei a Uzias, e o exército guerreiro de trezentos e sete mil e quinhentos",
      subtitle: "2Cr 26 • a multidão que garantiu a sucessão de Davi e a que saía à guerra em tropas",
      text: "A primeira é a assembleia do portão: \"Então todo o povo tomou a Uzias, que tinha dezesseis anos, e o fizeram rei em lugar de Amazias seu pai\" (2Cr 26:1). É a terceira vez, em poucos capítulos, que o \"povo da terra\" segura a casa de Davi de pé quando o palácio falha — depois da conspiração contra Joás (24:25) e da conspiração contra Amazias em Laquis (25:27), é a gente comum que impede a linhagem de se interromper. A segunda multidão é a do campo de guerra: \"E debaixo das suas ordens havia um exército guerreiro de trezentos e sete mil e quinhentos homens, que faziam a guerra com força belicosa, para ajudar o rei contra os inimigos\" (2Cr 26:13). Nunca Judá teve tanto, e o texto não esconde a causa nem a consequência: \"porque foi maravilhosamente ajudado, até que se fortificou\" (26:15), e logo \"exaltou-se o seu coração até se corromper\" (26:16). O socorro de Deus e a ruína do homem separados por uma vírgula."
    },
    pastor: {
      title: "O vinhateiro dos montes de Uzias",
      subtitle: "2Cr 26:10 • o homem das vinhas nos montes e nos campos férteis do rei amigo da agricultura",
      text: "\"tinha lavradores, e vinhateiros, nos montes e nos campos férteis; porque era amigo da agricultura\" (2Cr 26:10). É uma das frases mais inesperadas do livro dos reis: o Cronista para de contar guerras para dizer do que este rei gostava. O vinhateiro que ela põe em cena trabalha nas encostas terraceadas de Judá e no Carmelo — a palavra que a ARC traduz por \"campos férteis\" —, e depende diretamente das obras do rei: as torres de vigia levantadas no deserto e os muitos poços cavados no chão de pedra (26:10). É a mesma paisagem que Isaías, contemporâneo deste reinado, usará para a canção da vinha: \"O meu amado tem uma vinha num outeiro fértil. E cercou-a, e limpando-a das pedras, plantou-a de excelentes vides; e edificou no meio dela uma torre\" (Is 5:1-2). Enquanto o rei buscou ao SENHOR, Deus o fez prosperar (26:5) — e a prosperidade tinha cara de uva madura e cisterna cheia."
    },
    patriarca: {
      title: "Zacarias, que era entendido nas visões de Deus, e Isaías, filho de Amós, que escreveu os atos do rei",
      subtitle: "2Cr 26:5 e 26:22 • o mestre do rei moço e o profeta que datou a sua visão pela morte dele",
      text: "O primeiro aparece numa das ligações mais explícitas da Escritura entre discipulado e bênção: \"Porque deu-se a buscar a Deus nos dias de Zacarias, que era entendido nas visões de Deus; e nos dias em que buscou ao Senhor, Deus o fez prosperar\" (2Cr 26:5). Não se diz mais nada sobre ele — nem a família, nem quando morreu —, e é justamente esse silêncio que pesa: enquanto houve um homem entendido nas visões de Deus ao lado do rei, o rei buscou; o capítulo não volta a mencioná-lo, e é depois disso que o coração se exalta (26:16). O segundo fecha o reinado: \"Quanto ao mais dos atos de Uzias, tanto os primeiros como os últimos, o profeta Isaías, filho de Amós, o escreveu\" (2Cr 26:22). O mesmo Isaías que, no ano da morte deste rei leproso, viu o único Rei que ninguém expulsa do templo: \"No ano em que morreu o rei Uzias, eu vi também ao Senhor assentado sobre um alto e sublime trono; e a cauda do seu manto enchia o templo\" (Is 6:1)."
    },
    rebanho: {
      title: "O muito gado dos vales e das campinas de Uzias",
      subtitle: "2Cr 26:10 • os rebanhos por causa dos quais o rei cavou os poços e levantou as torres do deserto",
      text: "\"Também edificou torres no deserto, e cavou muitos poços, porque tinha muito gado, tanto nos vales como nas campinas\" (2Cr 26:10). A ordem da frase é a explicação inteira: as torres e as cisternas existem POR CAUSA destes animais. Nas campinas da Sefelá e nos vales do sul, um rebanho grande só se sustenta com água armazenada e vigia contra os saqueadores do deserto — os mesmos árabes de Gur-Baal e meunitas contra quem o rei foi ajudado (26:7). O gado de Uzias é, portanto, uma obra de engenharia tanto quanto as máquinas das torres. E é herança antiga: Judá já fora terra de pastores desde os dias em que Davi guardava as ovelhas de seu pai em Belém, e o Cronista guarda o registro dos rebanhos reais como parte do bem que Deus dá — \"nos dias em que buscou ao Senhor, Deus o fez prosperar\" (2Cr 26:5)."
    },
    rei: {
      title: "Uzias, o rei lavrador que entrou no templo com o incensário na mão — e Jotão, seu filho, que tomou o encargo da casa",
      subtitle: "2Cr 26 • cinquenta e dois anos de prosperidade e um único gesto que os fechou atrás de uma porta",
      text: "Feito rei aos dezesseis anos pelo povo da terra (26:1), reinou cinquenta e dois — e o segredo está dito em uma linha: \"nos dias em que buscou ao Senhor, Deus o fez prosperar\" (2Cr 26:5). Quebrou os muros de Gate, de Jabne e de Asdode, foi ajudado contra os árabes e os meunitas, recebeu presentes dos amonitas e teve o nome espalhado \"até à entrada do Egito\" (26:8). Edificou torres em Jerusalém e no deserto, cavou muitos poços, teve lavradores e vinhateiros \"porque era amigo da agricultura\" (26:10), armou trezentos e sete mil e quinhentos homens e montou nas torres as máquinas da invenção de engenheiros (26:15). E então a página vira: \"Mas, havendo-se já fortificado, exaltou-se o seu coração até se corromper; e transgrediu contra o Senhor seu Deus, porque entrou no templo do Senhor para queimar incenso no altar do incenso\" (2Cr 26:16). Indignou-se contra os sacerdotes com o incensário na mão, a lepra lhe saiu à testa, e \"até ele mesmo se deu pressa a sair, visto que o Senhor o ferira\" (26:20). Morou numa casa separada até morrer, \"porque foi excluído da casa do Senhor\", enquanto \"Jotão, seu filho, tinha o encargo da casa do rei, julgando o povo da terra\" (26:21) — um reino governado da antessala por um filho, porque o pai já não podia entrar em lugar nenhum."
    },
    servo: {
      title: "Os moços da corte e da câmara de Zacarias, o levita do santo lugar, e o criado que levava água à casa separada",
      subtitle: "2Cr 26 • quem serve nos cinquenta e dois anos de fartura e quem serve na casa onde o rei acabou sozinho",
      text: "No começo servem numa casa em ascensão: o moço que acende o candeeiro na câmara alta de Zacarias, \"que era entendido nas visões de Deus\" (2Cr 26:5), o do salão dos anais, o dos pátios onde chegam os presentes dos amonitas (26:8). Um deles é o levita do santo lugar, que estava de serviço no dia em que um rei atravessou a porta que não era dele — e viu, junto ao altar do incenso, \"a lepra lhe saiu à testa perante os sacerdotes, na casa do Senhor\" (26:19). Depois disso o serviço muda de endereço: alguém tem de levar comida e água todos os dias a uma casinha fora da cidade, porque \"Assim ficou leproso o rei Uzias até ao dia da sua morte; e morou, por ser leproso, numa casa separada, porque foi excluído da casa do Senhor\" (2Cr 26:21). Este é o criado da casa separada — o último homem a servir de perto um rei que ninguém mais podia tocar, segundo a lei do leproso que devia habitar \"fora do arraial\" (Lv 13:46). No fim, são também mãos de servos que cavam a cova no campo ao lado do jazigo real, \"porque disseram: Leproso é\" (26:23)."
    }
  }
};
