// Fichas ESPECÍFICAS por (capítulo → papel) de 2 CRÔNICAS 5–9.
// O ponto mais alto do livro. A arca sobe de Sião pela última vez nos ombros
// dos levitas e desce ao oráculo debaixo das asas dos querubins, com os varais
// tão compridos que as pontas se veem de dentro e dentro dela nada senão as
// duas tábuas de Horebe; os cantores de linho fino de Asafe, de Hemã e de
// Jedutum fazem "ouvir uma só voz" com cento e vinte trombetas, e a nuvem
// derruba o ministério dos sacerdotes. Depois vem a oração mais longa da
// Escritura, feita de joelhos sobre uma plataforma de metal no meio do pátio, e
// os seus sete casos — o juramento diante do altar, a derrota, o céu fechado,
// os gafanhotos, o ESTRANGEIRO de terras remotas, o exército pelo caminho e o
// cativo que ora voltado para a sua terra. O fogo desce, a glória enche a casa,
// vinte e dois mil bois e cento e vinte mil ovelhas ardem em catorze dias de
// festa, e de noite o SENHOR aparece outra vez para dizer "se o meu povo... se
// humilhar". Do capítulo 8 em diante o livro vira mapa e inventário: cidades,
// tributários, turmas, a frota de Ofir, a rainha de Sabá, o trono de marfim, a
// prata como pedras — e uma fórmula de sepultamento. Aqui o perigo da ficha é o
// culto genérico: cada figurante tem um OFÍCIO que o texto nomeia, e é por ele
// que se diz quem é.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_05_09: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- 2Cr 5
  5: {
    anciao: {
      title: "Os anciãos de Israel e os chefes das tribos convocados a Jerusalém para fazerem subir a arca de Sião",
      subtitle: "2Cr 5:2,4 • a segunda geração da procissão de Davi, e a que aprendeu a não tocar",
      text: "\"Então Salomão congregou em Jerusalém os anciãos de Israel, e todos os chefes das tribos, os chefes dos pais entre os filhos de Israel, para fazerem subir a arca da aliança do Senhor, da cidade de Davi, que é Sião\" (2Cr 5:2). Estes homens já fizeram este caminho uma vez, com o pai do rei: \"Sucedeu, pois, que Davi e os anciãos de Israel, e os capitães dos milhares, foram, com alegria, para fazer subir a arca da aliança do Senhor, da casa de Obede-Edom\" (1Cr 15:25). E carregam na memória o preço da primeira tentativa, a do carro novo e da mão de Uzá: \"Porquanto vós não a levastes na primeira vez, o Senhor nosso Deus fez rotura em nós, porque não o buscamos segundo a ordenança\" (1Cr 15:13). Por isso o versículo seguinte é seco e não explica nada — \"E vieram todos os anciãos de Israel; e os levitas levantaram a arca\" (2Cr 5:4): os anciãos vêm, os levitas levantam, e ninguém troca de função, porque \"ninguém pode levar a arca de Deus, senão os levitas\" (1Cr 15:2). São os últimos homens de Israel a ver a arca ao ar livre. Depois deste dia ela some atrás de um véu, e nenhum ancião jamais tornará a olhá-la.",
    },
    homem: {
      title: "Os sacerdotes que puseram a arca debaixo das asas, o que apontou as pontas dos varais, os que se santificaram sem respeitar as suas turmas, e os cento e vinte das trombetas",
      subtitle: "2Cr 5:5,7-14 • o sacerdócio no único dia em que não houve escala de serviço",
      text: "Estes homens fazem, num dia só, o que nenhuma geração antes nem depois faria. Primeiro carregam a mudança inteira do santuário: \"E fizeram subir a arca, e a tenda da congregação, com todos os objetos sagrados, que estavam na tenda; os sacerdotes e os levitas os fizeram subir\" (2Cr 5:5). Depois entram no lugar de onde vão sair para nunca mais: \"Assim trouxeram os sacerdotes a arca da aliança do Senhor ao seu lugar, ao oráculo da casa, ao lugar santíssimo, até debaixo das asas dos querubins\" (2Cr 5:7). Um deles é a testemunha de um detalhe que só quem esteve lá dentro podia dar: \"os varais sobressaíam para que as pontas dos varais da arca se vissem perante o oráculo, mas não se vissem de fora; e ali tem estado até ao dia de hoje\" (2Cr 5:9). Outro é o que constatou o inventário mais curto da Escritura: \"Na arca não havia coisa alguma senão as duas tábuas, que Moisés tinha posto em Horebe\" (2Cr 5:10) — sem o maná e sem a vara de Arão que a epístola ainda lembraria (Hb 9:4): só a aliança escrita em pedra. E na saída rompe-se a regra que organizava a vida deles: \"todos os sacerdotes, que ali se acharam, se santificaram, sem respeitarem as suas turmas\" (2Cr 5:11) — não havia escala que coubesse naquele dia. Ao oriente do altar ficam ainda \"até cento e vinte sacerdotes, que tocavam as trombetas\" (2Cr 5:12); e no fim nenhum deles está de pé: \"os sacerdotes não podiam permanecer em pé, para ministrar, por causa da nuvem\" (2Cr 5:14). O ofício deles foi interrompido pelo dono da casa.",
    },
    multidao: {
      title: "Todo o Israel congregado na festa do sétimo mês e o coro de Asafe, de Hemã e de Jedutum vestido de linho fino",
      subtitle: "2Cr 5:3,6,12-13 • a assembleia e os cantores que fizeram ouvir uma só voz",
      text: "\"E todos os homens de Israel se congregaram ao rei na ocasião da festa, que foi no sétimo mês\" (2Cr 5:3) — a festa dos tabernáculos, quando o povo mora em cabanas para lembrar o deserto; e é justamente no mês em que Israel finge não ter casa que Deus ganha a sua. No meio da subida a multidão para para sacrificar \"carneiros e bois, que não se podiam contar, nem numerar, por causa da sua abundância\" (2Cr 5:6). Mas o retrato desta congregação é o coro: \"os levitas, que eram cantores, todos eles, de Asafe, de Hemã, de Jedutum, de seus filhos e de seus irmãos, vestidos de linho fino, com címbalos, com saltérios e com harpas, estavam em pé para o oriente do altar\" (2Cr 5:12). São as três casas de música que Davi separou \"para profetizarem com harpas, com címbalos, e com saltérios\" (1Cr 25:1), agora reunidas todas de uma vez, sem turno. E o que o texto sublinha não é o volume, é a unidade: \"quando eles uniformemente tocavam as trombetas, e cantavam, para fazerem ouvir uma só voz\" (2Cr 5:13). A letra é de uma linha só, a antífona que atravessa o livro inteiro e volta na fundação do segundo templo, quando os que voltaram do exílio a cantaram outra vez sobre um alicerce vazio: \"porque é bom; porque a sua benignidade dura para sempre sobre Israel\" (Ed 3:11).",
    },
    rebanho: {
      title: "Os carneiros e os bois que não se podiam contar, sacrificados no caminho diante da arca",
      subtitle: "2Cr 5:6 • a parada do sacrifício no meio da subida de Sião para o monte",
      text: "\"Então o rei Salomão e toda a congregação de Israel, que se tinha reunido com ele diante da arca, sacrificaram carneiros e bois, que não se podiam contar, nem numerar, por causa da sua abundância\" (2Cr 5:6). É o único número do livro que o Cronista se recusa a fechar, ele que conta tudo — os mil holocaustos de Gibeom (2Cr 1:6), os cento e cinquenta mil homens do canteiro (2Cr 2:17-18), os vinte e dois mil bois da dedicação (2Cr 7:5). Aqui a conta é abandonada de propósito. O gesto vem de Davi, que na primeira subida bem-sucedida da arca mandou sacrificar a cada seis passos, e o Cronista registrou o começo: \"ajudando Deus os levitas que levavam a arca da aliança do Senhor, sacrificaram sete novilhos e sete carneiros\" (1Cr 15:26). Sacrificar no meio do caminho é confessar que aquele trajeto não é transporte de móvel: cada parada admite que ninguém tem direito de andar ao lado daquela caixa. Sob o toldo de fumaça deste rebanho a arca faz os últimos metros da sua história ao ar livre.",
    },
    rei: {
      title: "Salomão no dia em que entregou a casa: o que guardou nos tesouros a prata do pai e o que andou atrás da arca até a porta do oráculo",
      subtitle: "2Cr 5:1-2,6 • o rei que acaba a obra e some do próprio capítulo",
      text: "\"Assim se acabou toda a obra que Salomão fez para a casa do SENHOR; então trouxe Salomão as coisas que seu pai Davi havia consagrado, a prata, o ouro e todos os objetos, e pô-los entre os tesouros da casa de Deus\" (2Cr 5:1). O capítulo abre fechando, e o primeiro ato do rei com a casa pronta não é usá-la: é depositar nela o que não é dele. A prata e o ouro que entram nos tesouros foram ajuntados por um homem que morreu sem ver a parede subir — \"Eis que na minha aflição preparei para a casa do Senhor cem mil talentos de ouro\" (1Cr 22:14). Feito isso, Salomão convoca (2Cr 5:2), sacrifica com a congregação diante da arca (2Cr 5:6) — e depois desaparece do próprio capítulo: quem carrega são os levitas, quem entra no oráculo são os sacerdotes, quem canta são os cantores, e quem enche a casa é a nuvem. O construtor não tem função nenhuma no dia da entrega. Só no capítulo seguinte ele reaparece, e reaparece de joelhos.",
    },
    servo: {
      title: "Os levitas que levantaram a arca pela última vez, os que subiram com a tenda e os objetos sagrados, e o do tesouro que recebeu a prata consagrada por Davi",
      subtitle: "2Cr 5:1,4-5,9 • quem carrega, quem guarda e quem serve no lugar santo",
      text: "\"E vieram todos os anciãos de Israel; e os levitas levantaram a arca\" (2Cr 5:4). Esta é a última vez na Escritura que mãos humanas erguem aquela caixa, e elas a erguem do jeito certo, que custou caro para se aprender: \"os filhos dos levitas trouxeram a arca de Deus sobre os seus ombros, pelas varas que nela havia, como Moisés tinha ordenado conforme a palavra do Senhor\" (1Cr 15:15) — nada de carro novo, nada de mão estendida, porque \"no santuário não tocarão para que não morram\" (Nm 4:15). Com a arca sobe o resto de uma mudança de quarenta anos: \"a tenda da congregação, com todos os objetos sagrados, que estavam na tenda\" (2Cr 5:5), a tenda velha que Moisés fizera no deserto e que estivera até ontem no alto de Gibeom (2Cr 1:3). Um destes levitas fica de serviço no lugar santo, de onde se veem as pontas dos varais (2Cr 5:9); outro é o do tesouro, que arruma \"a prata, o ouro e todos os objetos\" que Davi consagrara e nunca usou (2Cr 5:1). Depois deste dia o ofício do carregador acaba para sempre: a arca chegou ao seu lugar, e ninguém mais precisa de ombro para ela.",
    },
  },

  // ---------------------------------------------------------------- 2Cr 6
  6: {
    anciao: {
      title: "Os anciãos da congregação que ficou em pé no pátio — e o ancião levado em cativeiro para terra remota",
      subtitle: "2Cr 6:3,12-13,36-38 • os que ouviram a oração e os que haveriam de precisar dela",
      text: "\"Então o rei virou o seu rosto, e abençoou a toda a congregação de Israel, e toda a congregação de Israel estava em pé\" (2Cr 6:3). O detalhe da postura volta duas vezes, porque é ele que faz do capítulo uma cena e não um discurso: o rei se ajoelha sobre a plataforma \"em presença de toda a congregação de Israel\" (2Cr 6:13) e a congregação continua de pé. Os anciãos são os mais velhos do pátio, gente que se lembra do reinado do pai e talvez dos tempos em que a arca ainda andava de tenda em tenda. E são eles também, quatro séculos depois, os rostos do sétimo caso da oração: \"Quando pecarem contra ti (pois não há homem que não peque)... para que os que os cativarem os levem em cativeiro para alguma terra, remota ou vizinha\" (2Cr 6:36). O ancião do exílio é o que menos tem chance de voltar e o que mais tem memória do que perdeu; e a única coisa que a oração lhe pede é uma direção: \"e orarem para o lado da sua terra\" (2Cr 6:38). Foi o que Daniel fez em Babilônia, já velho e já sob edito de morte: \"ora havia no seu quarto janelas abertas do lado de Jerusalém, e três vezes no dia se punha de joelhos\" (Dn 6:10). A oração deste pátio ensinou um povo inteiro para que lado rezar quando não houvesse mais pátio.",
    },
    cavaleiro: {
      title: "O cavaleiro do exército que sai à peleja pelo caminho por onde Deus o enviar",
      subtitle: "2Cr 6:34-35 • o sexto caso da oração: a tropa que ora virada para trás",
      text: "\"Quando o teu povo sair à guerra contra os seus inimigos, pelo caminho que os enviares, e orarem a ti para o lado desta cidade que escolheste, e desta casa, que edifiquei ao teu nome\" (2Cr 6:34). Este é o único dos sete casos em que o povo não está em desgraça nenhuma: está em marcha, e a marcha é legítima — o caminho é o que Deus enviou. A cláusula que o rei acrescenta é toda de orientação: no meio da estrada, longe de tudo, o soldado se vira para trás e ora na direção da cidade. O pedido correspondente é o mais curto da oração, porque a hora da batalha é curta: \"Ouve, então, desde os céus a sua oração, e a sua súplica, e faze-lhes justiça\" (2Cr 6:35). Vale notar de que cavalaria se está falando: a lei do rei proibira multiplicar cavalos e fazer o povo voltar ao Egito por causa deles (Dt 17:16), e este mesmo reinado acabaria com \"doze mil cavaleiros\" nas cidades dos carros (2Cr 9:25) e cavalos comprados no Egito em tropas (2Cr 1:16-17). O homem em cena é o soldado da máquina de guerra mais cara que Israel já teve — e a oração do seu rei não lhe promete vitória: promete audiência.",
    },
    homem: {
      title: "Os dois litigantes do juramento de maldição, o ferido diante do inimigo, o lavrador do céu fechado, o estrangeiro de terras remotas, o guerreiro em marcha e o cativo que caiu em si",
      subtitle: "2Cr 6:22-38 • os sete casos da oração, cada um com um rosto",
      text: "A oração do púlpito não é geral: é uma lista de desgraças com endereço, e cada figura em cena é um dos casos. O primeiro é jurídico e insolúvel — \"Quando alguém pecar contra o seu próximo, e lhe impuser juramento de maldição, fazendo-o jurar, e o juramento de maldição vier perante o teu altar, nesta casa\" (2Cr 6:22) —, e o que se pede não é clemência, é sentença: \"condenando ao ímpio... e justificando ao justo\" (2Cr 6:23). O segundo é o derrotado, \"ferido diante do inimigo, por ter pecado contra ti\" (2Cr 6:24). O terceiro é o lavrador debaixo de um céu de metal: \"Quando os céus se fecharem, e não houver chuva\" (2Cr 6:26). O quarto é a lista das pragas — \"queima de seara, ou ferrugem, gafanhotos, ou lagarta\" (2Cr 6:28) — e o texto individualiza a dor de cada um, \"conhecendo cada um a sua praga, e a sua dor, e estendendo as suas mãos para esta casa\" (2Cr 6:29). O quinto é o mais surpreendente de todos, e é um homem de fora: \"Assim também ao estrangeiro, que não for do teu povo Israel, quando vier de terras remotas por amor do teu grande nome\" (2Cr 6:32) — e por ele o rei pede sem cláusula nenhuma, \"faze conforme a tudo o que o estrangeiro te suplicar\" (2Cr 6:33), coisa que não pediu por Israel. O sexto é o soldado em marcha (2Cr 6:34). E o sétimo é o cativo, cuja confissão o próprio texto põe na boca dele: \"Pecamos, perversamente procedemos e impiamente agimos\" (2Cr 6:37). Sete homens, sete becos sem saída, e uma só porta — a casa que acabou de ficar pronta.",
    },
    mulherComum: {
      title: "A mulher do poço seco, a da fome na terra, a que estende as mãos para esta casa e a levada presa para a terra do cativeiro",
      subtitle: "2Cr 6:26-29,36-38 • as pragas da oração vistas de dentro de casa",
      text: "Os casos que o rei enumera do alto da plataforma acontecem primeiro dentro das casas, e é ali que esta mulher vive. O céu fechado dá no poço: \"Quando os céus se fecharem, e não houver chuva, por terem pecado contra ti\" (2Cr 6:26) — e quem mede a água que resta e reparte a farinha que sobrou é ela, como a viúva de Sarepta, que juntava dois cavacos \"vou prepará-lo para mim e para o meu filho, para que o comamos, e morramos\" (1Rs 17:12). Depois vem o resto da lista: \"Quando houver fome na terra, quando houver peste, quando houver queima de seara, ou ferrugem, gafanhotos, ou lagarta\" (2Cr 6:28), e a oração faz questão de não somar as dores num total: \"conhecendo cada um a sua praga, e a sua dor, e estendendo as suas mãos para esta casa\" (2Cr 6:29). O último quadro é o pior e o mais concreto: a que sai da cidade na fila dos presos, \"para que os que os cativarem os levem em cativeiro para alguma terra, remota ou vizinha\" (2Cr 6:36). O que o rei pede por ela não é que a desgraça não venha — é que, vindo, ela ainda saiba para que lado se virar: \"e orarem para o lado da sua terra, que deste a seus pais\" (2Cr 6:38).",
    },
    multidao: {
      title: "A congregação de Israel que ficou em pé no pátio durante os quarenta e dois versículos da oração",
      subtitle: "2Cr 6:3,12-13 • o povo diante de um rei ajoelhado",
      text: "Duas vezes o Cronista para a narrativa para dizer onde está o povo e como está: \"toda a congregação de Israel estava em pé\" (2Cr 6:3), e depois, quando o rei sobe à plataforma de metal, \"ajoelhou-se em presença de toda a congregação de Israel, e estendeu as suas mãos para o céu\" (2Cr 6:13). A inversão é o ponto: no pátio de qualquer outro reino do mundo antigo, o rei fica de pé e o povo se prostra. Aqui é ao contrário, e a congregação assiste ao seu monarca de joelhos, em público, por quarenta e dois versículos. É a mesma gente que se congregou \"na ocasião da festa, que foi no sétimo mês\" (2Cr 5:3), que viu a nuvem derrubar o ministério dos sacerdotes, e que no capítulo seguinte estará com o rosto no chão: \"todos os filhos de Israel vendo descer o fogo... encurvaram-se com o rosto em terra sobre o pavimento\" (2Cr 7:3). Enquanto isso, fica de pé — porque ainda não viu nada, e porque toda a oração que está ouvindo é sobre ela: os sete casos são sete desgraças desta multidão, não do rei.",
    },
    rei: {
      title: "Salomão de joelhos sobre a plataforma de metal no meio do pátio — e Davi, o morto cujo nome fecha a oração",
      subtitle: "2Cr 6:12-13,42 • o púlpito de bronze e o último argumento",
      text: "O palco de trinta versículos é uma peça que só o Cronista registra: \"Porque Salomão tinha feito uma plataforma de metal, de cinco côvados de comprimento, de cinco côvados de largura e de três côvados de altura, e a tinha posto no meio do pátio, e pôs-se em pé sobre ela, e ajoelhou-se em presença de toda a congregação de Israel, e estendeu as suas mãos para o céu\" (2Cr 6:13). O rei manda construir um lugar alto e sobe nele para se ajoelhar — a plataforma existe para que todo mundo veja o joelho. O que ele diz de lá em cima começa por uma admissão que nenhuma dedicação de templo ousou fazer: \"Mas, na verdade, habitará Deus com os homens na terra? Eis que os céus, e o céu dos céus, não te podem conter, quanto menos esta casa que tenho edificado?\" (2Cr 6:18). Nos versículos 5 a 9 ele CITA o que o SENHOR disse ao pai — \"bem fizeste de ter isto no teu coração\" e \"contudo tu não edificarás a casa, mas teu filho\" —, e a citação está na boca dele, não em voz do céu: aqui Deus é falado, não fala. E o fecho não é pedido, é convite, tirado quase palavra por palavra do salmo da subida da arca: \"Levanta-te, pois, agora, Senhor Deus, para o teu repouso, tu e a arca da tua fortaleza\" (2Cr 6:41; cf. Sl 132:8-9). A última coisa que este rei alega diante de Deus não é a própria obra: é a lealdade a um morto — \"lembra-te das misericórdias de Davi teu servo\" (2Cr 6:42).",
    },
    servo: {
      title: "O levita da tenda que Davi armou, o carregador das pedras aparelhadas, o levita de serviço no pátio do púlpito e o servo que veio com o estrangeiro de terras remotas",
      subtitle: "2Cr 6:5-11,32-33 • as mãos por trás dos quadros de memória e do quinto caso",
      text: "A oração passeia por quatro séculos, e estes servos são a gente de cada parada. No flashback do deserto e da tenda, o levita que serviu \"desde o dia em que tirei a meu povo da terra do Egito\", quando ainda não havia cidade escolhida nem homem posto (2Cr 6:5). Na tenda de Sião, o que ficou de serviço junto à arca durante os quarenta anos de Davi — \"para ministrarem continuamente perante a arca, segundo se ordenara para cada dia\" (1Cr 16:37) —, porque \"Davi meu pai teve no seu coração o edificar uma casa ao nome do Senhor Deus de Israel\" (2Cr 6:7) e ouviu que não a edificaria. No canteiro, o carregador das pedras aparelhadas da promessa adiada: \"Contudo tu não edificarás a casa, mas teu filho, que há de proceder de teus lombos, esse edificará a casa ao meu nome\" (2Cr 6:9) — pedra que Davi mandou lavrar para uma obra que não veria (1Cr 22:2). No pátio, o levita de serviço ao pé da plataforma durante a oração inteira. E, no quinto caso, o servo que veio na comitiva do homem de fora, \"quando vier de terras remotas por amor do teu grande nome, e da tua poderosa mão, e do teu braço estendido\" (2Cr 6:32): um criado estrangeiro parado à porta de um átrio que não é o seu, dentro de um pedido que Isaías repetiria — \"a minha casa será chamada casa de oração para todos os povos\" (Is 56:7).",
    },
  },

  // ---------------------------------------------------------------- 2Cr 7
  7: {
    anciao: {
      title: "O ancião de rosto em terra sobre o pavimento e o que se converte dos seus maus caminhos",
      subtitle: "2Cr 7:3,14 • o velho que viu o fogo descer e o velho a quem o oráculo se dirige",
      text: "\"E todos os filhos de Israel vendo descer o fogo, e a glória do Senhor sobre a casa, encurvaram-se com o rosto em terra sobre o pavimento, e adoraram e louvaram ao Senhor\" (2Cr 7:3). Não é a reação de um susto: é a reação exata que Israel teve na primeira vez que isto aconteceu, no dia em que Arão foi consagrado — \"o fogo saiu de diante do Senhor, e consumiu o holocausto e a gordura, sobre o altar; o que vendo todo o povo, jubilaram e caíram sobre as suas faces\" (Lv 9:24) — e na eira de Ornã, onde Davi \"invocou o Senhor, o qual lhe respondeu com fogo do céu sobre o altar do holocausto\" (1Cr 21:26). Um ancião no pavimento é quem tem memória para ligar as três coisas. E é a ele, mais do que a qualquer outro, que se endereça a condição do oráculo daquela noite: \"se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar a minha face e se converter dos seus maus caminhos\" (2Cr 7:14). Os quatro verbos vão organizar o resto do livro: humilharam-se os príncipes diante de Sisaque e a ira não se derramou (2Cr 12:6-7); humilhou-se Manassés com grilhões na Babilônia e voltou ao seu reino (2Cr 33:12-13). O caminho de volta que este velho ouve prometido é o mesmo que os seus netos vão precisar de usar.",
    },
    homem: {
      title: "Os sacerdotes que não puderam entrar na casa, o levita dos instrumentos que Davi fez, o das trombetas da consagração e o viajante que há de passar diante da ruína",
      subtitle: "2Cr 7:1-9,21-22 • quem serviu no dia do fogo e quem fará a pergunta no fim",
      text: "\"E acabando Salomão de orar, desceu o fogo do céu, e consumiu o holocausto e os sacrifícios; e a glória do SENHOR encheu a casa\" (2Cr 7:1) — e o efeito imediato sobre os ministros é o mesmo do capítulo 5, agora pior: \"os sacerdotes não podiam entrar na casa do Senhor, porque a glória do Senhor tinha enchido a casa do Senhor\" (2Cr 7:2). Passado o assombro, começa o maior turno de trabalho da história do sacerdócio israelita: \"os sacerdotes, serviam em seus ofícios; como também os levitas com os instrumentos musicais do Senhor, que o rei Davi tinha feito... e os sacerdotes tocavam as trombetas diante deles, e todo o Israel estava em pé\" (2Cr 7:6). Os instrumentos são herança de um morto, e a letra é a mesma de sempre, \"porque a sua benignidade dura para sempre\". O altar não deu conta do volume, e o chão precisou ser promovido: \"Salomão santificou o meio do átrio... porque no altar de metal, que Salomão tinha feito, não podia caber o holocausto\" (2Cr 7:7). No fim do capítulo, porém, aparece outro homem, e ele não é do culto: é o passante da estrada, no dia em que tudo isto for ruína. O próprio oráculo cita a fala dele — \"desta casa, que é tão exaltada, qualquer que passar por ela se espantará e dirá: Por que fez o Senhor assim com esta terra e com esta casa?\" (2Cr 7:21) — e a resposta já está escrita antes de a pergunta existir: \"Porque deixaram ao Senhor Deus de seus pais, que os tirou da terra do Egito\" (2Cr 7:22). Quatro séculos depois o caldeu queimaria a casa (2Rs 25:9), e a pergunta seria feita por gente de carne e osso na beira do caminho.",
    },
    mulherComum: {
      title: "A mulher de rosto em terra no pavimento, a que voltou para a sua tenda alegre e de bom ânimo, e a da terra consumida pelos gafanhotos",
      subtitle: "2Cr 7:3,10,13-14 • a festa e a praga vistas de quem cuida da casa",
      text: "Duas cenas deste capítulo têm mulher dentro, e são opostas. A primeira é o chão do átrio: \"encurvaram-se com o rosto em terra sobre o pavimento, e adoraram e louvaram ao Senhor, dizendo: Porque ele é bom, porque a sua benignidade dura para sempre\" (2Cr 7:3) — todo o Israel quer dizer também as famílias, e a laje do pátio novo é o lugar mais alto a que uma israelita comum chegou naquele mês. A segunda é a estrada de volta: \"no dia vigésimo terceiro do sétimo mês, despediu o povo para as suas tendas, alegres e de bom ânimo, pelo bem que o Senhor tinha feito a Davi, e a Salomão, e a seu povo Israel\" (2Cr 7:10) — catorze dias de festa (2Cr 7:8-9; cf. 1Rs 8:65) e depois a desmontagem das cabanas e a caminhada para casa. A terceira aparição dela é uma hipótese, e é a que o oráculo da noite levanta: \"se ordenar aos gafanhotos que consumam a terra\" (2Cr 7:13). Quem primeiro sabe que a seara foi comida é quem mede a farinha do pote; e é para ela, tanto quanto para o rei, que vem a promessa seguinte — \"então eu ouvirei dos céus, e perdoarei os seus pecados, e sararei a sua terra\" (2Cr 7:14). O verbo é curar, e o objeto é o chão de onde sai o pão.",
    },
    multidao: {
      title: "A congregação desde a entrada de Hamate até ao rio do Egito — catorze dias de festa e a assembleia solene do dia oitavo",
      subtitle: "2Cr 7:8-10 • o maior ajuntamento de Israel em toda a Escritura",
      text: "\"E, assim, naquele mesmo tempo celebrou Salomão a festa por sete dias e todo o Israel com ele, uma grande congregação, desde a entrada de Hamate, até ao rio do Egito\" (2Cr 7:8). O tamanho da multidão é dado por geografia, não por número: de uma ponta a outra do território prometido, do norte da Síria ao uádi da fronteira egípcia. Foram duas semanas emendadas — \"sete dias celebraram a consagração do altar, e sete dias a festa\" (2Cr 7:9) —, com uma assembleia solene no oitavo dia, e o paralelo em Reis faz a soma para quem não quiser fazer: \"por sete dias, e mais sete dias; catorze dias\" (1Rs 8:65). Alimentar essa gente é o que explica os números do sacrifício: \"bois, vinte e dois mil, e de ovelhas, cento e vinte mil\" (2Cr 7:5), porque o sacrifício pacífico volta em carne para quem o trouxe. E o fim é uma das linhas mais humanas do livro: \"despediu o povo para as suas tendas, alegres e de bom ânimo, pelo bem que o Senhor tinha feito a Davi, e a Salomão, e a seu povo Israel\" (2Cr 7:10). É o último momento da história de Israel em que o povo inteiro está no mesmo lugar, contente, e ainda não dividido.",
    },
    rebanho: {
      title: "Os vinte e dois mil bois e as cento e vinte mil ovelhas da consagração da casa",
      subtitle: "2Cr 7:5 • o número que o Cronista fecha depois de ter recusado fechar o do capítulo 5",
      text: "\"E o rei Salomão ofereceu sacrifícios de bois, vinte e dois mil, e de ovelhas, cento e vinte mil; e o rei e todo o povo consagraram a casa de Deus\" (2Cr 7:5). Cento e quarenta e duas mil cabeças em catorze dias: mais de dez mil por dia, o que só se explica porque não é holocausto puro — a maior parte é oferta pacífica, cuja gordura sobe ao altar e cuja carne volta para a mesa de uma congregação que vinha \"desde a entrada de Hamate, até ao rio do Egito\" (2Cr 7:8). O volume estourou o móvel: \"no altar de metal, que Salomão tinha feito, não podia caber o holocausto, e a oferta de alimentos, e a gordura\" (2Cr 7:7), e por isso o rei teve de santificar o próprio chão do átrio. A conta contrasta de propósito com a do capítulo anterior, em que os carneiros e bois da subida da arca \"não se podiam contar, nem numerar\" (2Cr 5:6), e com os mil holocaustos de uma noite em Gibeom (2Cr 1:6). Deste rebanho não ficou nada, e era esse o ponto: a casa não foi inaugurada com uma fita, foi inaugurada com um prejuízo.",
    },
    rei: {
      title: "Salomão no fim da oração e o rei sozinho no seu quarto na noite em que o SENHOR lhe apareceu outra vez",
      subtitle: "2Cr 7:1,11-18 • a única fala de Deus destes cinco capítulos, e por que ela é voz do céu",
      text: "\"E acabando Salomão de orar, desceu o fogo do céu\" (2Cr 7:1): a resposta chega antes de o joelho sair da plataforma, e é MUDA — quando Deus responde por fogo e por nuvem, não argumenta. Só depois de tudo pronto, \"assim Salomão acabou a casa do Senhor, e a casa do rei\" (2Cr 7:11), é que vem a fala: \"E o Senhor apareceu de noite a Salomão, e disse-lhe: Ouvi a tua oração, e escolhi para mim este lugar para casa de sacrifício\" (2Cr 7:12). É por isso que aqui a fala é voz do céu e não personificação: não há mediador nenhum em cena. Não há profeta em cena — nem Natã, nem Aías, nem Ido, os três cujos escritos o livro citará no fim (2Cr 9:29); não há anjo, não há sarça, não há coluna, não há objeto de onde o balão possa sair. É visão noturna e oráculo interior, exatamente como a primeira vez, em Gibeom: \"Naquela mesma noite Deus apareceu a Salomão, e disse-lhe: Pede o que queres que eu te dê\" (2Cr 1:7). Quando Deus fala através de alguém ou de alguma coisa, o balão sai do mediador; aqui não há de onde sair senão do alto, e por isso a glória entra na cena junto com a noite alta. O conteúdo é a resposta ponto por ponto à oração do púlpito — \"se eu fechar os céus... se ordenar aos gafanhotos... se enviar a peste\" (2Cr 7:13) — e chega ao versículo que é o coração de 2 Crônicas inteiro: \"E se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar a minha face e se converter dos seus maus caminhos, então eu ouvirei dos céus, e perdoarei os seus pecados, e sararei a sua terra\" (2Cr 7:14).",
    },
    servo: {
      title: "O levita diante da porta que a glória fechou, o que conduziu o gado do sacrifício, o da gordura das ofertas e o servo da câmara do rei na noite da aparição",
      subtitle: "2Cr 7:2,4-7,12 • o serviço pesado por trás do dia mais alto do livro",
      text: "Enquanto a glória enche a casa, alguém tem de segurar a porta: \"os sacerdotes não podiam entrar na casa do Senhor, porque a glória do Senhor tinha enchido a casa do Senhor\" (2Cr 7:2), e o levita fica de fora, encarando um vão que ninguém atravessa. Passado isso, começa o trabalho bruto: \"o rei e todo o povo ofereciam sacrifícios perante o Senhor\" (2Cr 7:4), e cento e quarenta e duas mil cabeças de gado não chegam ao altar sozinhas — há quem as conduza, quem as segure, quem esfole, quem separe \"os holocaustos e a gordura dos sacrifícios pacíficos\" (2Cr 7:7) e quem lave o que vai subir. É serviço de catorze dias seguidos, com o chão do átrio santificado às pressas porque o altar de metal não dava conta. E, no fim do capítulo, um servo de outro tipo: o da câmara do rei, do lado de fora da porta, na noite em que \"o Senhor apareceu de noite a Salomão\" (2Cr 7:12). Ele não ouve nada — a aparição é sem mediador, e o oráculo é só para quem dorme lá dentro. Guardar a porta de um quarto em que Deus está falando é o ofício mais silencioso deste capítulo inteiro.",
    },
  },

  // ---------------------------------------------------------------- 2Cr 8
  8: {
    cavaleiro: {
      title: "O cavaleiro das cidades dos carros e o capitão de Israel que não foi feito servo da obra",
      subtitle: "2Cr 8:6,9 • a única classe de israelita que o rei não pôs a carregar pedra",
      text: "\"Como também a Baalate, e todas as cidades de provisões, que Salomão tinha, e todas as cidades dos carros e as cidades dos cavaleiros\" (2Cr 8:6). O reino que começou pedindo sabedoria acaba dividido em praças de guarnição, e o homem que as ocupa é este. O Cronista faz questão de dizer o que ele NÃO é: \"Porém, dos filhos de Israel, Salomão não fez servos para sua obra (mas eram homens de guerra, chefes dos seus capitàes, e capitàes dos seus carros e cavaleiros)\" (2Cr 8:9). A distinção é o eixo social do capítulo: quem carrega é o heteu, o amorreu, o perizeu, o heveu e o jebuseu (2Cr 8:7-8); quem monta é o israelita. A conta desta cavalaria já fora dada no primeiro capítulo — \"mil e quatrocentos carros, e doze mil cavaleiros\" (2Cr 1:14) — e voltará no último, com as estrebarias (2Cr 9:25); e o animal vinha do lugar que a lei do rei tinha proibido: \"os cavalos, que tinha Salomão, eram trazidos do Egito\" (2Cr 1:16), contra o expresso \"ele não multiplicará para si cavalos, nem fará voltar o povo ao Egito para multiplicar cavalos\" (Dt 17:16). O privilégio deste cavaleiro é real, e é comprado numa moeda que o Deuteronômio não aceitava.",
    },
    homem: {
      title: "O mestre da obra dos vinte anos, o morador de Tadmor no deserto, o porteiro do ferrolho de Bete-Horom, o heteu que ficou na terra, o cobrador do tributo, o porteiro de cada porta e o servo prático do mar de Hirão",
      subtitle: "2Cr 8:1-18 • os ofícios de um reino já pronto, do canteiro à praia de Edom",
      text: "Vinte anos de obra terminam numa linha — \"E sucedeu, ao fim de vinte anos, nos quais Salomão edificou a casa do SENHOR, e a sua própria casa\" (2Cr 8:1) — e o capítulo vira mapa. Há o que foi habitar as cidades devolvidas por Tiro (2Cr 8:2); o soldado da única campanha do reinado, contada sem uma palavra de comentário: \"Depois foi Salomão a Hamate-Zobá, e a tomou\" (2Cr 8:3); o morador da cidade fundada onde não havia nada, \"Tadmor no deserto\" (2Cr 8:4); e o guarda das duas praças gêmeas do desfiladeiro, \"a alta Bete-Horom, e a baixa Bete-Horom; cidades fortes, com muros, portas e ferrolhos\" (2Cr 8:5). Depois vêm os que a conquista não expulsou: \"todo o povo, que tinha ficado dos heteus, amorreus, perizeus, heveus e jebuseus, que não eram de Israel... Salomão os fez tributários, até ao dia de hoje\" (2Cr 8:7-8), o mesmo arranjo que Reis registra (1Rs 9:20-21) — e ao lado deles o cobrador, e os \"duzentos e cinqüenta, que presidiam sobre o povo\" (2Cr 8:10). No pátio, o serviço entra em regime: sacerdotes nos seus ministérios, levitas nos seus cargos \"e os porteiros pelas suas turmas a cada porta; porque assim tinha mandado Davi, o homem de Deus\" (2Cr 8:14), com a nota de honestidade que o Cronista faz questão de deixar: \"não se desviaram do mandado do rei aos sacerdotes e levitas, em negócio nenhum, nem acerca dos tesouros\" (2Cr 8:15). E na outra ponta do mapa, na praia de Edom, um homem que não é de Israel nem de terra nenhuma: \"enviou-lhe Hirão, por meio de seus servos, navios, e servos práticos do mar\" (2Cr 8:18) — fenícios que sabiam navegar o mar Vermelho, e sem os quais os quatrocentos e cinquenta talentos de Ofir não teriam chegado.",
    },
    mulherComum: {
      title: "A filha de Faraó tirada da cidade de Davi, a amorreia que ficou na terra e a mulher das cidades que Hirão devolveu",
      subtitle: "2Cr 8:2,7-8,11 • as mulheres de um reino que se acomodou com o que não expulsou",
      text: "O verso mais estranho do capítulo é uma mudança de endereço: \"E Salomão fez subir a filha de Faraó da cidade de Davi para a casa que lhe tinha edificado; porque disse: Minha mulher não morará na casa de Davi, rei de Israel, porquanto santos são os lugares nos quais entrou a arca do Senhor\" (2Cr 8:11). A razão dada é litúrgica, não conjugal: não se trata de afastar a mulher, e sim de tirar de cima do chão por onde a arca passou uma casa que não lhe pertence. Ainda assim o Cronista não comenta o resto, que Reis contaria sem piedade: \"o rei Salomão amou muitas mulheres estrangeiras, além da filha de Faraó\" (1Rs 11:1), e \"suas mulheres lhe perverteram o coração\" (1Rs 11:3) — exatamente o que a lei do rei previra, \"tampouco para si multiplicará mulheres, para que o seu coração não se desvie\" (Dt 17:17). Ao lado dela, no mesmo capítulo, estão as mulheres dos povos que ficaram: \"dos seus filhos, que ficaram depois deles na terra, os quais os filhos de Israel não destruíram, Salomão os fez tributários, até ao dia de hoje\" (2Cr 8:8) — a heteia, a amorreia, a jebuseia, cujas famílias entraram na folha de carga do reino. E a israelita comum das cidades refeitas, aquelas \"que Hirão lhe tinha dado; e fez habitar nelas os filhos de Israel\" (2Cr 8:2), que mudou de aldeia por decisão de dois reis.",
    },
    rei: {
      title: "Salomão ao fim de vinte anos: o que fundou cidades no deserto, pôs os que ficaram a tributo e desceu à praia do mar em Edom",
      subtitle: "2Cr 8:1-6,11-18 • o rei administrador, entre o mapa e o calendário do culto",
      text: "Este é o capítulo em que o construtor vira governante. Terminadas \"a casa do SENHOR, e a sua própria casa\" (2Cr 8:1), ele reedifica as cidades devolvidas por Tiro, toma Hamate-Zobá (2Cr 8:3) e planta Tadmor num deserto onde não havia nada (2Cr 8:4). Fortifica os dois degraus do desfiladeiro de Bete-Horom \"com muros, portas e ferrolhos\" (2Cr 8:5) e enche o país de cidades de provisões, de carros e de cavaleiros (2Cr 8:6). Depois arruma o culto pelo calendário e pela ordem do pai: holocaustos \"segundo a ordem de cada dia, fazendo ofertas conforme o mandamento de Moisés, nos sábados e nas luas novas, e nas solenidades, três vezes no ano\" (2Cr 8:13), e as turmas dos sacerdotes, dos levitas e dos porteiros \"conforme à ordem de Davi seu pai\" (2Cr 8:14) — em 2 Crônicas, obedecer a Davi e obedecer a Moisés são a mesma coisa, e por isso o Cronista chama o velho rei de \"o homem de Deus\". O fim do capítulo o leva ao ponto mais distante do reino: \"Então foi Salomão a Eziom-Geber, e a Elote, à praia do mar, na terra de Edom\" (2Cr 8:17), de onde a frota parte para Ofir e volta com \"quatrocentos e cinqüenta talentos de ouro\" (2Cr 8:18) — quatrocentos e vinte na conta de Reis (1Rs 9:28). É o reino no seu maior tamanho, e a última página antes de a rainha de Sabá chegar para ver se é verdade.",
    },
    servo: {
      title: "O jebuseu posto a tributo, o heveu carregador da obra, o servo das cidades de provisões, o levita das turmas do louvor e o que foi a Ofir nos navios de Hirão",
      subtitle: "2Cr 8:8,14,18 • duas escravidões e um ministério no mesmo capítulo",
      text: "Este capítulo separa a mão de obra por nascimento, e diz isso com todas as letras: \"Dos seus filhos, que ficaram depois deles na terra, os quais os filhos de Israel não destruíram, Salomão os fez tributários, até ao dia de hoje\" (2Cr 8:8), e logo em seguida, \"dos filhos de Israel, Salomão não fez servos para sua obra\" (2Cr 8:9). O jebuseu e o heveu em cena carregam pedra e provisão; o israelita, não. É o mesmo sistema que já contara cento e cinquenta e três mil e seiscentos estrangeiros no alistamento do canteiro (2Cr 2:17-18) — e o mesmo rei que, dois capítulos atrás, pediu que Deus atendesse \"a tudo o que o estrangeiro te suplicar\" (2Cr 6:33). O Cronista põe as duas coisas no mesmo livro e deixa o leitor sentir a distância entre elas. No pátio, outro tipo de servo: o levita das turmas do louvor, escalado \"para louvarem e ministrarem diante dos sacerdotes, segundo o que estava ordenado para cada dia\" (2Cr 8:14), e o que conferia as câmaras sem tocar no que era de Deus (2Cr 8:15). E na praia de Edom, o servo de Salomão que embarcou com os fenícios: \"foram com os servos de Salomão a Ofir, e tomaram de lá quatrocentos e cinqüenta talentos de ouro\" (2Cr 8:18) — um israelita do interior, sem tradição nenhuma de mar, num navio conduzido por marinheiros de Tiro.",
    },
  },

  // ---------------------------------------------------------------- 2Cr 9
  9: {
    anciao: {
      title: "O ancião de Jerusalém no sepultamento de Salomão, na cidade de Davi",
      subtitle: "2Cr 9:30-31 • quem enterrou o rei dos quarenta anos e viu o filho assumir",
      text: "\"E reinou Salomão em Jerusalém quarenta anos sobre todo o Israel. E dormiu Salomão com seus pais, e o sepultaram na cidade de Davi seu pai; e Roboão, seu filho, reinou em seu lugar\" (2Cr 9:30-31). Um ancião que esteja neste enterro nasceu no reinado de Davi: viu a arca subir de Sião nos ombros dos levitas, esteve no pátio quando a nuvem derrubou os sacerdotes, ouviu a oração inteira do púlpito de bronze e agora vê a pedra se fechar sobre o homem que fez tudo isso. O Cronista não lhe dá tempo de luto: acaba a frase e o capítulo, e o versículo seguinte já está em Siquém, com Roboão respondendo asperamente ao povo e dez tribos indo embora (2Cr 10). O apogeu e a divisão cabem no espaço de uma linha branca. E o que este velho leva do reinado inteiro não é o ouro nem o marfim — é a frase que ouviu de noite, de segunda mão, e que o resto do livro vai testar rei por rei: \"se o meu povo, que se chama pelo meu nome, se humilhar... então eu ouvirei dos céus\" (2Cr 7:14).",
    },
    cavaleiro: {
      title: "Um dos doze mil cavaleiros das quatro mil estrebarias, repartidos entre as cidades dos carros e Jerusalém",
      subtitle: "2Cr 9:25 • a última conta militar do reinado",
      text: "\"Teve também Salomão quatro mil estrebarias para os cavalos de seus carros, e doze mil cavaleiros; e colocou-os nas cidades dos carros, e junto ao rei em Jerusalém\" (2Cr 9:25). O número dos homens é o mesmo do primeiro capítulo — \"mil e quatrocentos carros, e doze mil cavaleiros\" (2Cr 1:14) —, e o que cresceu foi a estrutura: agora há baias para quatro mil parelhas. O animal continua vindo do sul: \"E do Egito e de todas aquelas terras traziam cavalos a Salomão\" (2Cr 9:28), no mesmo comércio de atravessador que abriu o livro, com o carro a seiscentos siclos e o cavalo a cento e cinquenta (2Cr 1:17). Ler isto ao lado da lei do rei é desconfortável, e o Cronista põe os dois lado a lado sem uma palavra: \"ele não multiplicará para si cavalos, nem fará voltar o povo ao Egito para multiplicar cavalos\" (Dt 17:16). Este cavaleiro é o soldado mais bem equipado que Israel jamais teve, guarnecendo um reino que \"dominava sobre todos os reis, desde o rio até à terra dos filisteus, e até ao termo do Egito\" (2Cr 9:26) — e que se partiria em dois sem uma batalha, no capítulo seguinte.",
    },
    homem: {
      title: "O ministro da mesa do rei, o escriba que pesava os seiscentos e sessenta e seis talentos, o ourives dos paveses de ouro batido, o guarda da casa do bosque do Líbano e o marinheiro dos navios de Társis",
      subtitle: "2Cr 9:4,13-21 • os ofícios do apogeu, do salão de jantar à alfândega",
      text: "O que derrubou a rainha de Sabá não foi um discurso: foi uma casa funcionando. \"E as iguarias da sua mesa, o assentar dos seus servos, o estar dos seus criados, e as vestes deles; e os seus copeiros e as vestes deles; e a sua subida pela qual ele chegava à casa do Senhor, ela ficou como fora de si\" (2Cr 9:4) — cada item dessa lista é um homem com um posto. Depois dela vêm os do tesouro: o escriba que fecha a conta do ano, \"o peso do ouro, que vinha em um ano a Salomão, era de seiscentos e sessenta e seis talentos de ouro\" (2Cr 9:13), e o da alfândega, que recebia o que os \"negociantes e mercadores\" traziam e o que os reis da Arábia mandavam (2Cr 9:14). O ourives bate as armas de aparato: \"duzentos paveses de ouro batido; para cada pavês destinou seiscentos siclos\" (2Cr 9:15) e \"trezentos escudos de ouro batido\" (2Cr 9:16), guardados na casa do bosque do Líbano — e o guarda dessa sala não sabe que está tomando conta de um saque futuro, porque cinco anos depois da morte do rei \"subiu, pois, Sisaque, rei do Egito, contra Jerusalém... também tomou os escudos de ouro, que Salomão fizera\", e Roboão os substituiria por escudos de cobre (2Cr 12:9-10). E na outra ponta do império está o marinheiro: \"indo os navios do rei com os servos de Hirão, a Társis, voltavam os navios de Társis, uma vez em três anos, e traziam ouro e prata, marfim, bugios e pavões\" (2Cr 9:21) — três anos de viagem para trazer, entre o ouro, um carregamento de macacos e aves de enfeite.",
    },
    mulherComum: {
      title: "A rainha de Sabá diante da subida pela qual o rei chegava à casa do SENHOR, a mulher das campinas dos sicômoros e a carpideira do sepulcro",
      subtitle: "2Cr 9:1-9,27,31 • a estrangeira que fez a melhor pergunta e a israelita do fim do reinado",
      text: "Ela veio de longe e veio para testar: \"E ouvindo a rainha de Sabá a fama de Salomão, veio a Jerusalém, para prová-lo com questões difíceis, com um grande séquito, e com camelos carregados de especiarias\" (2Cr 9:1) — e falou com ele \"de tudo o que tinha no seu coração\", sem que houvesse \"nada que não lhe pudesse esclarecer\" (2Cr 9:2). O que a derrubou, porém, não foram as respostas, e sim a última linha do inventário do que viu: \"e a sua subida pela qual ele chegava à casa do Senhor, ela ficou como fora de si\" (2Cr 9:4) — a rampa por onde o rei subia ao templo, isto é, o culto, e não o palácio. E a confissão dela acerta a teologia do livro melhor do que a de muitos reis de Judá: \"Bendito seja o Senhor teu Deus, que se agradou de ti para te colocar no seu trono como rei para o Senhor teu Deus\" (2Cr 9:8) — no seu trono, não no teu. Jesus a citaria como testemunha de acusação: \"A rainha do sul se levantará no dia do juízo com esta geração, e a condenará; porque veio dos confins da terra para ouvir a sabedoria de Salomão. E eis que está aqui quem é maior do que Salomão\" (Mt 12:42). Ao lado dela, no fim do capítulo, ficam as israelitas comuns: a das campinas onde os cedros se tornaram tão baratos \"como as figueiras bravas que há pelas campinas\" (2Cr 9:27), e a que chora na cidade de Davi no dia em que \"dormiu Salomão com seus pais\" (2Cr 9:31).",
    },
    multidao: {
      title: "O povo de Israel dos quarenta anos de Salomão — o que viveu inteiro dentro do apogeu",
      subtitle: "2Cr 9:20,27,30 • a geração que viu a prata reputar-se por nada",
      text: "\"E reinou Salomão em Jerusalém quarenta anos sobre todo o Israel\" (2Cr 9:30). Quem nasceu no ano da dedicação da casa morreu com o reino ainda inteiro; esta multidão é a única geração da história de Israel que não conheceu guerra em casa, invasão nem exílio. E viu coisas que ninguém tornaria a ver: \"todas as taças do rei Salomão eram de ouro... a prata reputava-se por nada nos dias de Salomão\" (2Cr 9:20), e \"o rei fez que houvesse prata em Jerusalém como pedras, e cedros em tanta abundância como as figueiras bravas que há pelas campinas\" (2Cr 9:27) — a madeira mais cara do Levante tratada como o sicômoro da beira do caminho. O Cronista, que escreve para gente que voltou do exílio com pouco, guarda esse quadro sem ironia nenhuma; mas guarda também, do outro lado do livro, a fatura: as cento e cinquenta mil pessoas do canteiro (2Cr 2:17-18), o tributo sobre os que ficaram (2Cr 8:8) e a carga que o povo pediria a Roboão para aliviar no capítulo seguinte — \"agora, pois, alivia tu a dura servidão de teu pai, e o pesado jugo que nos impôs\" (2Cr 10:4). A mesma multidão que aqui olha a prata como pedra vai, três versículos adiante, abandonar a casa de Davi.",
    },
    patriarca: {
      title: "Natã, o profeta, Aías, o silonita, e Ido, o vidente — as três testemunhas que puseram um reinado por escrito",
      subtitle: "2Cr 9:29 • as fontes que o Cronista nomeia no fim da vida de Salomão",
      text: "\"Os demais atos de Salomão, tanto os primeiros como os últimos, porventura não estão escritos no livro das crônicas de Natã, o profeta, e na profecia de Aías, o silonita, e nas visões de Ido, o vidente, acerca de Jeroboão, filho de Nebate?\" (2Cr 9:29). O Cronista fecha o maior reinado da história de Israel remetendo a três arquivos, e todos os três são de profeta: em 2 Crônicas, a memória oficial do reino é guardada por quem falava em nome de Deus, não pelo escriba da corte. Natã é o homem da aliança davídica — foi por essa boca que veio \"eu lhe serei por pai, e ele me será por filho\" (1Cr 17:13) — e foi ele quem ungiu Salomão em Giom (1Rs 1:45). Aías, o silonita, é o do outro lado da conta: encontrou Jeroboão no campo, rasgou a capa nova em doze pedaços e lhe disse \"toma para ti os dez pedaços\" (1Rs 11:30-31). E Ido, o vidente, aparece só nas Crônicas, sempre como fonte — dos atos de Salomão aqui, dos de Roboão em 2Cr 12:15 e dos de Abias em 2Cr 13:22. A menção a \"Jeroboão, filho de Nebate\" no fim do versículo é a rachadura já assinalada dentro do elogio: o livro que acaba de contar o trono de marfim já sabe o nome do homem que vai levar dez tribos embora.",
    },
    rei: {
      title: "Os reis da Arábia e os reis da terra que buscavam a presença de Salomão — e Roboão, que reinou em seu lugar",
      subtitle: "2Cr 9:14,22-24,31 • as coroas estrangeiras diante do trono de marfim e a que herdou tudo",
      text: "\"Assim excedeu o rei Salomão a todos os reis da terra, em riquezas e sabedoria. E todos os reis da terra buscavam a presença de Salomão, para ouvirem a sabedoria que Deus tinha posto no seu coração\" (2Cr 9:22-23). O Cronista faz questão de dizer o que esses reis vinham buscar: não é aliança nem comércio, é sabedoria — e sabedoria que Deus pôs, não que o rei teve. Eles não vêm de mãos vazias: \"cada um trazia o seu presente, vasos de prata, e vasos de ouro, e roupas, armaduras, especiarias, cavalos e mulas; assim faziam de ano em ano\" (2Cr 9:24), e junto com eles \"todos os reis da Arábia, e os governadores da mesma terra traziam a Salomão ouro e prata\" (2Cr 9:14). O móvel diante do qual eles se curvam é único: \"um grande trono de marfim\" com seis degraus, estrado de ouro e doze leões, do qual o texto sentencia \"outro tal não se fez em nenhum reino\" (2Cr 9:17-19). E o último rei do capítulo é o que não fez nada para merecê-lo: \"e Roboão, seu filho, reinou em seu lugar\" (2Cr 9:31) — o homem que, uma página adiante, responderia ao povo \"Meu pai agravou o vosso jugo, porém eu o aumentarei mais\" (2Cr 10:14) e perderia dez tribos em um dia.",
    },
    servo: {
      title: "Os do séquito da rainha de Sabá, os copeiros de Salomão, o que mostrava a casa, o que pesava o ouro do rei e os servos de Hirão nos navios de Társis",
      subtitle: "2Cr 9:1-4,10-12,21 • a criadagem que a rainha veio ver e a marinhagem que sustentava a conta",
      text: "Numa das listas mais curiosas da Escritura, o que impressiona uma rainha estrangeira é o pessoal de serviço: \"o assentar dos seus servos, o estar dos seus criados, e as vestes deles; e os seus copeiros e as vestes deles\" (2Cr 9:4). Não é o ouro: é a ordem — cada um sabendo onde se sentar, como ficar de pé e o que vestir. Do lado dela vêm os do séquito, os que descarregaram os \"camelos carregados de especiarias; ouro em abundância e pedras preciosas\" (2Cr 9:1) e que tornariam a carregá-los mais pesados do que vieram: \"o rei Salomão deu à rainha de Sabá tudo quanto ela desejou, e tudo quanto lhe pediu, mais do que ela mesma trouxera ao rei. Assim voltou e foi para a sua terra, ela e os seus servos\" (2Cr 9:12). Dentro de casa está o do peso, que fecha os seiscentos e sessenta e seis talentos do ano (2Cr 9:13); e fora, no mar, os que fazem o dinheiro entrar: \"os servos de Hirão e os servos de Salomão, que de Ofir tinham trazido ouro, trouxeram madeira de algumins, e pedras preciosas\" (2Cr 9:10), e a frota de Társis que voltava \"uma vez em três anos\" (2Cr 9:21). Um servo israelita passa três anos fora de casa para que a prata de Jerusalém possa reputar-se por nada.",
    },
  },
};
