// Fichas ESPECÍFICAS por (capítulo → papel) de 2 CRÔNICAS 27–31.
// Cinco capítulos que descem ao fundo do poço e voltam: Jotão, que se fortifica
// calado, edifica a porta superior e o muro de Ofel e nunca entra no templo
// porque viu o pai sair leproso de dentro dele; Acaz, que queima os próprios
// filhos no vale do filho de Hinom, sacrifica aos deuses que o feriram e FECHA
// AS PORTAS da casa do SENHOR; e Ezequias, que no primeiro mês do primeiro ano
// ABRE as mesmas portas, passa dezesseis dias tirando imundícia até o ribeiro
// de Cedrom, celebra a páscoa fora do prazo com correios escarnecidos na
// estrada de Zebulom e enche o pátio de MONTÕES que começam no terceiro mês e
// só acabam no sétimo. Cada figurante anônimo destas cenas é alguém REAL
// daquele capítulo — o carregador de pedra de Ofel, o cativo de Judá calçado
// pelas mãos de Efraim, o levita da imundícia, o lavrador das primícias.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_27_31: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- 2Cr 27
  27: {
    rei: {
      title: "O rei dos filhos de Amom, vencido por Jotão e tributário três anos seguidos",
      subtitle: "2Cr 27:5 • a planície a leste do Jordão, e o pagamento que voltou no segundo e no terceiro ano",
      text: "É o rei de Amom que perdeu a guerra e passou a pagar: \"Ele também guerreou contra o rei dos filhos de Amom, e prevaleceu sobre eles, de modo que os filhos de Amom naquele ano lhe deram cem talentos de prata, e dez mil coros de trigo, e dez mil de cevada; isto lhe trouxeram os filhos de Amom também no segundo e no terceiro ano\" (2Cr 27:5). O Cronista não lhe dá nome, e a frase de Judá sobre o vizinho de sempre é dita em números: prata pesada, trigo e cevada medidos em coros — dez mil de cada um, três colheitas inteiras seguidas. Amom era parente antigo e inimigo antigo: descendente de Ló (Gn 19:38), tinha alugado Balaão contra Israel (Dt 23:3-4), fora vencido por Jefté (Jz 11), humilhara os mensageiros de Davi (2Sm 10:4) e voltaria contra Josafá pelo deserto de En-Gedi (2Cr 20:1-2). Contra Jotão não prevaleceu, e a razão está no versículo seguinte, que não é sobre exército: \"Assim se fortificou Jotão, porque dirigiu os seus caminhos na presença do Senhor seu Deus\" (2Cr 27:6). O tributo cessa no terceiro ano — o texto não diz por quê, e a próxima notícia da região já é a pressão da Síria e de Israel sobre o filho deste rei reto (2Rs 15:37).",
    },
    mulherComum: {
      title: "A mulher do povo que ainda se corrompia nos dias do rei reto",
      subtitle: "2Cr 27:2 • a casa comum de Judá, debaixo de um reinado que fez o que era reto",
      text: "É a ressalva mais dura do capítulo, e ela não cai sobre o rei: \"E fez o que era reto aos olhos do Senhor, conforme a tudo o que fizera Uzias, seu pai, exceto que não entrou no templo do Senhor. E o povo ainda se corrompia\" (2Cr 27:2). Enquanto a porta superior era edificada e o muro de Ofel subia, esta mulher continuava sacrificando e queimando incenso nos altos que Reis diz que não foram tirados (2Rs 15:35) — a religião do quintal, herdada da mãe, feita debaixo da árvore verde e não no átrio. Miqueias e Isaías profetizavam exatamente nestes anos, \"nos dias de Uzias, Jotão, Acaz, e Ezequias, reis de Judá\" (Is 1:1; cf. Mq 1:1), e o que denunciavam não era o palácio, era a casa: a mão cheia de sacrifício e o coração longe (Is 1:11-15). Um governo reto não converte ninguém por decreto; o capítulo termina com o rei fortificado e o povo indo embora, e é essa distância que explica por que o reinado seguinte pôde despencar tão depressa.",
    },
    anciao: {
      title: "Os sacerdotes da casa do SENHOR nos dias de Jotão e os anciãos que o sepultaram na cidade de Davi",
      subtitle: "2Cr 27:2,9 • o átrio em que o rei nunca entrou, e a laje do túmulo real",
      text: "São os homens que serviam do lado de dentro da porta que este rei não atravessava. A frase \"exceto que não entrou no templo do Senhor\" (2Cr 27:2) não é elogio nem acusação simples: é a cicatriz de Uzias, que entrara para queimar incenso, fora enfrentado por Azarias e oitenta sacerdotes valentes e saíra com a lepra na testa, \"e até ele mesmo se deu pressa a sair, visto que o Senhor o ferira\" (2Cr 26:20). O filho aprendeu a lição do lugar de cada um: edificou a porta superior da casa do SENHOR (2Cr 27:3) sem tomar o ofício de quem ministra dentro dela. Ao fim dos dezesseis anos, são estes mesmos anciãos e sacerdotes que o acompanham à sepultura — \"E dormiu Jotão com seus pais, e sepultaram-no na cidade de Davi; e Acaz, seu filho, reinou em seu lugar\" (2Cr 27:9) —, e é diante deles que entra o rei que em poucos anos fecharia as portas que o pai tinha ajudado a levantar.",
    },
    servo: {
      title: "Os carregadores de pedra do muro de Ofel, os lenhadores dos bosques de Judá, os portadores do tributo de Amom e o servo da câmara dos rolos",
      subtitle: "2Cr 27:3-5,7 • as mãos que levantaram a obra deste reinado",
      text: "O Cronista resume dezesseis anos de reinado por uma folha de obras, e estes são os que a executaram: \"Ele edificou a porta superior da casa do Senhor, e também edificou muitas obras sobre o muro de Ofel\" (2Cr 27:3) — Ofel é a esporão de rocha entre a cidade de Davi e o monte do templo, a muralha que segura Jerusalém pelo lado leste, e cada pedra dela subiu no ombro de alguém. Depois vieram os bosques: \"Também edificou cidades nas montanhas de Judá, e castelos e torres nos bosques\" (2Cr 27:4), e para isso houve quem cortasse a mata e quem arrastasse o cantaria monte acima. Os outros servos em cena chegam pela estrada do oriente, descarregando o que Amom pagou: prata em talentos, trigo e cevada em coros, três anos seguidos (2Cr 27:5). E o último trabalha sem sol, na câmara onde o escriba lança em rolo \"o restante dos atos de Jotão, e todas as suas guerras e os seus caminhos\" (2Cr 27:7). Nenhum deles é nomeado; a obra que fizeram é a única biografia que o rei tem.",
    },
    homem: {
      title: "O mestre de obra do muro de Ofel, o sentinela da torre dos bosques, o capitão de Judá em Amom, o escriba do livro dos reis — e o homem do povo que ainda se corrompia",
      subtitle: "2Cr 27:2-7 • o canteiro, a fronteira e o cartório de um reinado curto",
      text: "Cinco ofícios seguram este capítulo. O mestre de obra ergue \"muitas obras sobre o muro de Ofel\" (2Cr 27:3) e o portal novo da casa do SENHOR, a porta superior que Reis também registra (2Rs 15:35). O sentinela está nos \"castelos e torres nos bosques\" (2Cr 27:4) — torres de vigia plantadas na mata das montanhas de Judá, porque quem edifica cidade sem quem a vigie está construindo espólio para o próximo invasor. O capitão volta do outro lado do Jordão com a notícia de que o rei \"prevaleceu sobre eles\" (2Cr 27:5). O escriba fecha tudo num rolo: \"eis que estão escritos no livro dos reis de Israel e de Judá\" (2Cr 27:7). E, no meio deles, anda o homem que faz o capítulo doer: o povo de quem se diz, no mesmo fôlego do elogio ao rei, que \"ainda se corrompia\" (2Cr 27:2). Isaías estava pregando a essa gente naqueles anos exatos (Is 1:1) — e a acusação dele não era contra o trono, era contra as mãos cheias de sangue que ainda subiam ao átrio (Is 1:15).",
    },
  },

  // ---------------------------------------------------------------- 2Cr 28
  28: {
    rei: {
      title: "O rei dos sírios que feriu a Acaz e levou grande multidão de presos a Damasco",
      subtitle: "2Cr 28:5 • a primeira das quatro mãos em que Judá foi entregue",
      text: "É Rezim, o rei de Damasco, que Reis nomeia (2Rs 16:5-6) e que o Cronista prefere descrever pelo que fez: \"Por isso o Senhor seu Deus o entregou na mão do rei dos sírios, os quais o feriram, e levaram dele em cativeiro uma grande multidão de presos, que trouxeram a Damasco\" (2Cr 28:5). O verbo decisivo não é dele: quem entrega é o SENHOR, e a Síria é apenas a vara. A pressão já viera anunciada no reinado do pai — \"Naqueles dias começou o Senhor a enviar contra Judá a Rezim, rei da Síria, e a Peca, filho de Remalias\" (2Rs 15:37) —, e foi diante dessa aliança dos dois que Isaías chamou os dois reis de \"dois pedaços de tições fumegantes\" e disse à casa de Davi: \"se não o crerdes, certamente não haveis de permanecer\" (Is 7:4,9). Acaz não creu; comprou a Assíria com a prata da casa do SENHOR, e Tiglate-Pileser subiu contra Damasco, \"e tomou-a e levou cativo o povo para Quir, e matou a Rezim\" (2Rs 16:9). O socorro que veio matou o inimigo e ficou com o cliente.",
    },
    homem: {
      title: "Os homens do reinado de Acaz: o fundidor das imagens de Baalins, os valentes mortos num só dia, o cativo nu vestido do despojo, os quatro cabeças de Efraim e o mensageiro enviado à Assíria",
      subtitle: "2Cr 28 • o capítulo em que Judá é ferido por quatro lados e socorrido pelo inimigo",
      text: "O primeiro homem em cena funde metal: \"Antes andou nos caminhos dos reis de Israel, e, além disso, fez imagens fundidas a Baalins\" (2Cr 28:2). Os últimos são levados em fila. Entre um e outro cabe a conta: \"Porque Peca, filho de Remalias, matou em Judá, num só dia, cento e vinte mil, todos homens valentes; porquanto deixaram ao Senhor Deus de seus pais\" (2Cr 28:6). Depois vem a coisa mais inesperada do livro. O exército de Israel volta com duzentos mil presos, um profeta o intercepta, e \"os homens armados deixaram os cativos e o despojo diante dos príncipes e de toda a congregação\" (2Cr 28:14). Então: \"E os homens que foram apontados por seus nomes se levantaram, e tomaram os cativos, e vestiram do despojo a todos os que dentre eles estavam nus; e vestiram-nos, e calçaram-nos, e deram-lhes de comer e de beber, e os ungiram, e a todos os que estavam fracos levaram sobre jumentos, e conduziram-nos a Jericó, à cidade das palmeiras, a seus irmãos\" (2Cr 28:15) — vestir, calçar, dar de comer e de beber, ungir e carregar: seis verbos que o Senhor repetiria em Mateus 25:35-36 e desenharia outra vez na estrada de Jericó, na parábola do samaritano (Lc 10:33-34). Enquanto isso, outro homem sai de Jerusalém para o norte com prata da casa de Deus e o recado de Acaz aos reis da Assíria (2Cr 28:16,21).",
    },
    servo: {
      title: "Os filhos de Acaz queimados no vale de Hinom, as crianças levadas cativas e o porteiro que fechou as portas da casa do SENHOR",
      subtitle: "2Cr 28:3,8,24 • os mais fracos deste capítulo, e a mão que trancou o templo",
      text: "Nenhum destes escolheu nada. Os primeiros são levados ao lixão ao sul da cidade: \"Também queimou incenso no vale do filho de Hinom, e queimou a seus filhos no fogo, conforme as abominações dos gentios que o Senhor tinha expulsado de diante dos filhos de Israel\" (2Cr 28:3) — é o gê-hinnom que a língua guardaria como nome do inferno (cf. Jr 7:31-32; Mt 5:22), e o rei acende o fogo com a própria casa. Os segundos vão para o norte: \"E os filhos de Israel levaram presos de seus irmãos duzentos mil, mulheres, filhos e filhas\" (2Cr 28:8), e voltariam da estrada de Samaria calçados e a cavalo de jumento pelas mãos de quem os prendera (2Cr 28:15). O último tem a tarefa mais silenciosa e a mais grave: \"E ajuntou Acaz os utensílios da casa de Deus, e fez em pedaços os utensílios da casa de Deus, e fechou as portas da casa do Senhor, e fez para si altares em todos os cantos de Jerusalém\" (2Cr 28:24). Alguém empurrou aquela folha e passou a tranca — e Judá viveu anos com a casa de Deus fechada, até que um filho deste mesmo rei a reabrisse no primeiro mês do seu primeiro ano (2Cr 29:3).",
    },
    mulherComum: {
      title: "As cativas de Judá levadas a Samaria, a mulher que queimava incenso nos altos e a moradora de Bete-Semes tomada pelos filisteus",
      subtitle: "2Cr 28:8,4,18 • as mulheres em que o juízo deste reinado bateu primeiro",
      text: "O texto conta a derrota pela casa, não pelo campo: \"E os filhos de Israel levaram presos de seus irmãos duzentos mil, mulheres, filhos e filhas; e também saquearam deles grande despojo, que levaram para Samaria\" (2Cr 28:8). São irmãs de sangue arrastadas por irmãos de sangue, e é exatamente esse o argumento do profeta que os intercepta: \"E agora vós cuidais em sujeitar a vós os filhos de Judá e Jerusalém, como cativos e cativas\" (2Cr 28:10). Outra destas mulheres não foi levada a lugar nenhum e está igualmente perdida: é a que sobe ao outeiro com o rei, porque ele \"sacrificou, e queimou incenso nos altos e nos outeiros, como também debaixo de toda a árvore verde\" (2Cr 28:4) — o culto de fertilidade que sempre encontrou nas mulheres da terra a sua clientela mais fiel (cf. Jr 44:19; Os 4:13). E a terceira acorda com o inimigo dentro de casa: \"Também os filisteus deram sobre as cidades da campina e do sul de Judá, e tomaram a Bete-Semes, e a Aijalom, e a Gederote e a Socó… e habitaram ali\" (2Cr 28:18). Habitaram — não passaram; ficaram morando na vila dela.",
    },
    anciao: {
      title: "Os príncipes diante de quem o despojo foi largado, e o sacerdote que viu esvaziarem o tesouro da casa do SENHOR",
      subtitle: "2Cr 28:14,21 • os dois lados da mesma balança: em Samaria devolvem, em Jerusalém entregam",
      text: "O primeiro ancião está em Samaria, e é diante dele que o exército vencedor larga a presa: \"Então os homens armados deixaram os cativos e o despojo diante dos príncipes e de toda a congregação\" (2Cr 28:14). Tinha acabado de ouvir de Obede que a vitória fora entregue por Deus e usada com \"uma raiva tal, que chegou até aos céus\" (2Cr 28:9), e a decisão dos cabeças de Efraim foi rara na Escritura: assumir a culpa antes de calculá-la — \"além da nossa culpa contra o Senhor, vós intentais acrescentar mais a nossos pecados e a nossas culpas\" (2Cr 28:13). O segundo ancião está em Jerusalém e assiste ao contrário: \"Porque Acaz tomou despojos da casa do Senhor, e da casa do rei, e dos príncipes, e os deu ao rei da Assíria; porém não o ajudou\" (2Cr 28:21). É um sacerdote vendo sair pela porta o que o povo trouxera para dentro — e a conta final está no versículo seguinte: \"E ao tempo em que este o apertou, então ainda mais transgrediu contra o Senhor, tal era o rei Acaz\" (2Cr 28:22).",
    },
    patriarca: {
      title: "Obede, o profeta do SENHOR que saiu ao encontro do exército vitorioso de Israel",
      subtitle: "2Cr 28:9-11 • a estrada de Samaria, diante de duzentos mil cativos de Judá",
      text: "\"Mas estava ali um profeta do Senhor, cujo nome era Obede, o qual saiu ao encontro do exército que vinha para Samaria\" (2Cr 28:9). Ele não é profeta em Judá: está no reino do Norte, na capital dos bezerros, e a palavra que traz não é contra o inimigo, é contra os seus. Reconhece que a vitória veio de Deus — \"Eis que, irando-se o Senhor Deus de vossos pais contra Judá, os entregou na vossa mão\" — e no mesmo fôlego diz o que fizeram dela: \"e vós os matastes com uma raiva tal, que chegou até aos céus\" (2Cr 28:9). Depois vira a acusação para dentro: \"porventura não sois vós mesmos culpados contra o Senhor vosso Deus?\" (2Cr 28:10), e ordena o impensável a um exército que volta carregado: \"tornai a enviar os prisioneiros que trouxestes cativos de vossos irmãos; porque o ardor da ira do Senhor está sobre vós\" (2Cr 28:11). Foi ouvido. É um dos poucos lugares da Escritura em que uma pregação profética é obedecida no ato e pelo lado vencedor — e o resultado é o versículo 15, com os cativos vestidos, calçados, ungidos e levados sobre jumentos até Jericó.",
    },
  },

  // ---------------------------------------------------------------- 2Cr 29
  29: {
    rei: {
      title: "Ezequias, que no primeiro mês do primeiro ano abriu as portas da casa do SENHOR",
      subtitle: "2Cr 29:3 • a primeira decisão de um reinado, tomada sobre a tranca do pai",
      text: "\"Ele, no primeiro ano do seu reinado, no primeiro mês, abriu as portas da casa do Senhor, e as reparou\" (2Cr 29:3). O Cronista põe a data porque a data é o argumento: não houve consolidação de poder antes, nem cálculo político — a primeira coisa que este rei fez foi desfazer a última coisa que o pai fizera (2Cr 28:24). Tinha vinte e cinco anos, era filho de Abia, filha de Zacarias, \"E fez o que era reto aos olhos do Senhor, conforme a tudo quanto fizera Davi, seu pai\" (2Cr 29:2). O diagnóstico que prega aos levitas na praça oriental é implacável e inclui a própria família: \"nossos pais transgrediram… e desviaram os seus rostos do tabernáculo do Senhor, e lhe deram as costas. Também fecharam as portas do alpendre, e apagaram as lâmpadas\" (2Cr 29:6-7). E a decisão que anuncia é de aliança, não de reforma predial: \"Agora me tem vindo ao coração, que façamos uma aliança com o Senhor Deus de Israel, para que se desvie de nós o ardor da sua ira\" (2Cr 29:10). O capítulo fecha com o alívio de quem não esperava tanto: \"Ezequias, e todo o povo se alegraram, por causa daquilo que Deus tinha preparado para o povo; porque apressuradamente se fez esta obra\" (2Cr 29:36).",
    },
    anciao: {
      title: "Os sacerdotes, filhos de Arão, que purificaram o interior da casa e espargiram o sangue sobre o altar — e os líderes da cidade reunidos de madrugada",
      subtitle: "2Cr 29:16,20-24,34 • o ofício que só eles podiam fazer, e as mãos que faltaram",
      text: "A divisão do trabalho é exata: \"E os sacerdotes entraram na casa do Senhor, para a purificar, e tiraram para fora, ao pátio da casa do Senhor, toda a imundícia que acharam no templo do Senhor\" (2Cr 29:16) — só eles podiam pisar o santuário; os levitas recebiam no pátio e carregavam. São eles que voltam ao rei com o relatório: \"Já purificamos toda a casa do Senhor, como também o altar do holocausto com todos os seus utensílios e a mesa da proposição com todos os seus utensílios\" (2Cr 29:18). Depois vem a madrugada: \"Então o rei Ezequias se levantou de madrugada, e reuniu os líderes da cidade, e subiu à casa do Senhor\" (2Cr 29:20), e são estes anciãos que impõem as mãos sobre os bodes do sacrifício pelo pecado (2Cr 29:23) e espargem o sangue sobre o altar \"para reconciliar a todo o Israel\" (2Cr 29:24). O capítulo, porém, não os poupa: \"Eram, porém, os sacerdotes mui poucos, e não podiam esfolar a todos os holocaustos… porque os levitas foram mais retos de coração, para se santificarem, do que os sacerdotes\" (2Cr 29:34). Dezesseis anos de portas fechadas deixaram a ordem sacerdotal atrasada em relação ao próprio avivamento.",
    },
    homem: {
      title: "Os levitas: os catorze chefes nomeados um a um, os que carregaram a imundícia ao ribeiro de Cedrom, os tangedores dos instrumentos de Davi e os que ajudaram a esfolar",
      subtitle: "2Cr 29:12-17,25-30,34 • dezesseis dias de trabalho braçal e o cântico que começou junto com o fogo",
      text: "\"Então se levantaram os levitas\" (2Cr 29:12) — e o Cronista os nomeia casa por casa: Maate e Joel, dos coatitas; Quis e Azarias, de Merari; Joá e Éden, dos gersonitas; Sinri e Jeuel, de Elisafã; Zacarias e Matanias, de Asafe; Jeuel e Simei, de Hemã; Semaías e Uziel, de Jedutum (2Cr 29:12-14). O serviço deles é sujo e demorado: os sacerdotes tiravam do santuário para o pátio, \"e os levitas a tomaram, para a levarem para fora, ao ribeiro de Cedrom\" (2Cr 29:16), descendo o vale do lado leste da cidade com o entulho de dezesseis anos de abandono. A conta dos dias está no texto: começaram no primeiro dia do primeiro mês, ao oitavo chegaram ao alpendre, \"e no dia décimo sexto do primeiro mês acabaram\" (2Cr 29:17). Terminada a faxina, os mesmos homens pegam os instrumentos: \"Estavam, pois, os levitas em pé com os instrumentos de Davi, e os sacerdotes com as trombetas\" (2Cr 29:26), e então acontece a frase que o capítulo guardava: \"ao tempo em que começou o holocausto, começou também o canto do Senhor\" (2Cr 29:27). No fim ainda arregaçam as mangas de novo, porque os sacerdotes não davam conta de esfolar (2Cr 29:34).",
    },
    servo: {
      title: "O carpinteiro que reparou as portas, os moços do conserto do santuário e as crianças da congregação que se prostraram com os pais",
      subtitle: "2Cr 29:3,15-16,28 • as mãos miúdas de uma obra feita apressuradamente",
      text: "Antes do culto houve marcenaria: \"abriu as portas da casa do Senhor, e as reparou\" (2Cr 29:3) — a folha estava travada desde Acaz e não bastava destrancá-la, foi preciso consertá-la. Depois veio a limpeza, e ela envolveu gente demais para caber em lista: os levitas \"ajuntaram a seus irmãos, e santificaram-se e vieram conforme ao mandado do rei, pelas palavras do Senhor, para purificarem a casa do Senhor\" (2Cr 29:15). Estes moços são os irmãos ajuntados: carregam bacia, raspam piso, enchem caixa, descem o carreiro do Cedrom e voltam para encher outra. Entre eles há também os filhos que vieram com os pais e viram o dia do sacrifício: \"E toda a congregação se prostrou, quando entoavam o canto, e as trombetas eram tocadas; tudo isto até o holocausto se acabar\" (2Cr 29:28) — uma geração que nasceu com o templo fechado e cuja primeira memória de culto é esta. A pressa que o texto elogia no fim (\"apressuradamente se fez esta obra\", 2Cr 29:36) mediu-se nos pés destes servos.",
    },
    mulherComum: {
      title: "A mulher de Judá que esteve em cativeiro e a mulher da congregação que se prostrou quando entoavam o canto",
      subtitle: "2Cr 29:9,28 • a lembrança que o rei cita na praça oriental, e o pátio em que ela se ajoelha",
      text: "Ezequias não prega sobre pecado em tese; aponta para famílias que estão ouvindo: \"Porque eis que nossos pais caíram à espada, e nossos filhos, e nossas filhas, e nossas mulheres; por isso estiveram em cativeiro\" (2Cr 29:9). Ele fala do desastre do reinado anterior — os cento e vinte mil mortos num só dia e os duzentos mil levados a Samaria (2Cr 28:6,8) —, e nesta praça há mulheres que voltaram daquela estrada, calçadas e vestidas do despojo pelas mãos de Efraim (2Cr 28:15). Elas são a prova viva do diagnóstico do rei, e é diante delas que ele diz: \"Agora me tem vindo ao coração, que façamos uma aliança com o Senhor Deus de Israel\" (2Cr 29:10). Poucos dias depois, quando o fogo e o cântico começam juntos, ela está no pátio: \"E toda a congregação se prostrou, quando entoavam o canto, e as trombetas eram tocadas\" (2Cr 29:28). O templo de Jerusalém não tinha câmara separada para mulheres na descrição de Crônicas; a congregação que se prostra é a casa inteira, e ela está nela.",
    },
    rebanho: {
      title: "Os sete novilhos, sete carneiros, sete cordeiros e sete bodes — e depois os setenta bois, cem carneiros, duzentos cordeiros, seiscentos bois e três mil ovelhas",
      subtitle: "2Cr 29:21-24,32-33 • o gado que reabriu o altar do holocausto",
      text: "A primeira conta é de sete em sete, e o texto diz por quem: \"E trouxeram sete novilhos e sete carneiros, e sete cordeiros e sete bodes, para sacrifício pelo pecado, pelo reino, e pelo santuário, e por Judá\" (2Cr 29:21) — o reino, a casa e o povo, cada um com a sua expiação, no número da plenitude. Os bodes têm função distinta e explícita: \"Então trouxeram os bodes para sacrifício pelo pecado, perante o rei e a congregação, e lhes impuseram as suas mãos\" (2Cr 29:23), o gesto de Levítico 4 e 16, em que a culpa passa da cabeça do homem para a cabeça do animal — \"e com o seu sangue fizeram expiação do pecado sobre o altar, para reconciliar a todo o Israel\" (2Cr 29:24). Depois o altar não para: a congregação traz por conta própria \"setenta bois, cem carneiros, duzentos cordeiros\" (2Cr 29:32), e ainda \"seiscentos bois e três mil ovelhas\" de coisas consagradas (2Cr 29:33). Foi tanto animal que os sacerdotes não deram conta de esfolar (2Cr 29:34). Todo esse gado aponta para um só cordeiro: \"Eis o Cordeiro de Deus, que tira o pecado do mundo\" (Jo 1:29).",
    },
    multidao: {
      title: "A congregação que se prostrou ao som do cântico, trouxe ofertas voluntárias e se alegrou porque apressuradamente se fez a obra",
      subtitle: "2Cr 29:28-31,36 • o pátio cheio no dia em que o ministério da casa foi restabelecido",
      text: "Esta multidão fez três coisas seguidas. Primeiro se calou e se dobrou: \"E toda a congregação se prostrou, quando entoavam o canto, e as trombetas eram tocadas; tudo isto até o holocausto se acabar\" (2Cr 29:28). Depois louvou por palavras que não eram suas: o rei e os príncipes \"disseram aos levitas que louvassem ao Senhor com as palavras de Davi, e de Asafe, o vidente. E o louvaram com alegria e se inclinaram e adoraram\" (2Cr 29:30) — os salmos escritos duzentos e cinquenta anos antes voltaram à boca de um povo que crescera sem templo aberto. E por fim abriu a mão, quando Ezequias disse \"Agora vos consagrastes a vós mesmos ao Senhor; chegai-vos e trazei sacrifícios e ofertas de louvor à casa do Senhor\" — \"e todos os dispostos de coração trouxeram holocaustos\" (2Cr 29:31). O fecho não é sobre o esforço deles: \"Ezequias, e todo o povo se alegraram, por causa daquilo que Deus tinha preparado para o povo; porque apressuradamente se fez esta obra\" (2Cr 29:36). Dezesseis anos para fechar, dezesseis dias para reabrir.",
    },
  },

  // ---------------------------------------------------------------- 2Cr 30
  30: {
    rei: {
      title: "Ezequias, que celebrou a páscoa no segundo mês e orou pelos que a comeram sem se purificar",
      subtitle: "2Cr 30:2-4,18-20 • a festa fora do prazo e a oração que o SENHOR ouviu",
      text: "A páscoa é do primeiro mês (Êx 12:6), e este rei a celebra no segundo, por um motivo declarado sem disfarce: \"Porquanto não a puderam celebrar no tempo próprio, porque não se tinham santificado sacerdotes em número suficiente, e o povo não se tinha ajuntado em Jerusalém\" (2Cr 30:3). A lei previa o segundo mês para quem estivesse imundo ou em viagem longa (Nm 9:10-11); Ezequias estende a exceção ao país inteiro, e \"isto pareceu bem aos olhos do rei, e de toda a congregação\" (2Cr 30:4). O convite que manda passar por pregão desde Berseba até Dã inclui o reino que já estava caindo nas mãos da Assíria: \"Filhos de Israel, convertei-vos ao Senhor Deus de Abraão, de Isaque e de Israel\" (2Cr 30:6). E quando a multidão vinda do Norte come a páscoa sem estar purificada, ele não interrompe a festa — ora por ela: \"O Senhor, que é bom, perdoa todo aquele\" que \"tem preparado o seu coração para buscar ao Senhor Deus… ainda que não esteja purificado segundo a purificação do santuário\" (2Cr 30:18-19). A resposta é de cinco palavras: \"E ouviu o Senhor a Ezequias, e sarou o povo\" (2Cr 30:20).",
    },
    homem: {
      title: "Os correios que passaram de cidade em cidade e foram escarnecidos, os pregoeiros de Berseba e de Dã, os zombadores de Efraim e os levitas que mataram os cordeiros pelos que não estavam limpos",
      subtitle: "2Cr 30:5-11,16-17 • a estrada do Norte e o átrio da páscoa",
      text: "\"Foram, pois, os correios com as cartas, do rei e dos seus príncipes, por todo o Israel e Judá\" (2Cr 30:6), levando um convite que não tinha exército por trás: \"dai a mão ao Senhor, e vinde ao seu santuário que ele santificou para sempre\" (2Cr 30:8). O que receberam está numa das frases mais secas do livro: \"E os correios foram passando de cidade em cidade, pela terra de Efraim e Manassés até Zebulom; porém riram-se e zombaram deles\" (2Cr 30:10) — riram na cara de um homem que atravessou o país a pé com uma carta na mão. E não desistiram na primeira vila: foram passando, cidade por cidade, até o extremo norte. O resultado veio pequeno e veio: \"Todavia alguns de Aser, e de Manassés, e de Zebulom, se humilharam, e vieram a Jerusalém\" (2Cr 30:11). Em Jerusalém há outro grupo de homens no meio do trabalho: \"os sacerdotes espargiam o sangue, tomando-o da mão dos levitas\" (2Cr 30:16), e os levitas assumiram o que não era ofício deles \"por todo aquele que não estava limpo, para o santificarem ao Senhor\" (2Cr 30:17) — alguém teve de matar o cordeiro pelo peregrino que não podia fazê-lo.",
    },
    anciao: {
      title: "Os príncipes que tomaram conselho com o rei e os sacerdotes que se envergonharam, se santificaram e abençoaram o povo",
      subtitle: "2Cr 30:2,15,27 • a decisão do conselho e a bênção que chegou até aos céus",
      text: "A páscoa fora do prazo não é capricho de rei: \"Porque o rei tivera conselho com os seus príncipes, e com toda a congregação em Jerusalém, para celebrarem a páscoa no segundo mês\" (2Cr 30:2). Estes anciãos são os que contaram os sacerdotes santificados, viram que não davam e resolveram adiar em vez de fingir. E entre eles estão justamente os sacerdotes que faltavam: \"Então sacrificaram a páscoa no dia décimo quarto do segundo mês; e os sacerdotes e levitas se envergonharam e se santificaram e trouxeram holocaustos à casa do Senhor\" (2Cr 30:15) — a vergonha aqui é boa notícia, é o que os move. No fim do capítulo são eles que fecham a festa com o gesto de Números 6:23-27: \"Então os sacerdotes e os levitas se levantaram e abençoaram o povo; e a sua voz foi ouvida; porque a sua oração chegou até à santa habitação de Deus, até aos céus\" (2Cr 30:27). O Cronista não diz que Deus falou; diz que a oração subiu — e é assim que Deus responde neste capítulo inteiro, calado e por dentro.",
    },
    servo: {
      title: "Os meninos que ouviram o pregão nas praças, subiram com os peregrinos e comeram a páscoa que os pais não podiam preparar",
      subtitle: "2Cr 30:5,13,17-18 • as crianças de uma festa convocada de repente",
      text: "\"E ordenaram que se fizesse passar pregão por todo o Israel, desde Berseba até Dã\" (2Cr 30:5), e um pregão numa vila pequena é ouvido primeiro pelas crianças, que correm atrás do arauto. São elas que fazem a viagem sem entender o calendário: \"E ajuntou-se em Jerusalém muito povo, para celebrar a festa dos pães ázimos, no segundo mês; uma congregação mui grande\" (2Cr 30:13). E são elas, também, parte da multidão que come sem estar purificada — \"Porque uma multidão do povo, muitos de Efraim e Manassés, Issacar e Zebulom, não se tinham purificado, e contudo comeram a páscoa, não como está escrito\" (2Cr 30:18) —, pelas quais os levitas tiveram de matar o cordeiro (2Cr 30:17) e por quem o rei orou. A páscoa foi instituída justamente para que houvesse esta pergunta em casa: \"quando vossos filhos vos disserem: Que culto é este?\" (Êx 12:26). Depois de dezesseis anos de portas fechadas, uma geração inteira de Judá fazia essa pergunta pela primeira vez.",
    },
    mulherComum: {
      title: "A mulher de Efraim que ouviu a carta na porta de casa, a que zombou em Zebulom, a que se humilhou em Manassés e a estrangeira que habitava em Judá",
      subtitle: "2Cr 30:10-11,18,25 • as duas respostas possíveis ao mesmo convite",
      text: "O convite chegou às aldeias do Norte pela boca dos correios, e a mesma rua deu duas respostas. Uma está no versículo 10: \"porém riram-se e zombaram deles\" (2Cr 30:10) — a zombaria de quem já vira Samaria pagar tributo à Assíria e não acreditava mais em nada que viesse de Jerusalém. A outra está no versículo seguinte: \"Todavia alguns de Aser, e de Manassés, e de Zebulom, se humilharam, e vieram a Jerusalém\" (2Cr 30:11), e humilhar-se aqui quer dizer atravessar a fronteira de um reino rival para adorar no templo que os seus pais tinham abandonado. Muitas destas mulheres chegaram sem tempo de se purificar e comeram a páscoa assim mesmo (2Cr 30:18), cobertas pela oração do rei. E o capítulo ainda alarga o círculo mais uma vez, contando quem se alegrou: \"toda a congregação de Judá, e os sacerdotes, e os levitas, toda a congregação de todos os que vieram de Israel, como também os estrangeiros que vieram da terra de Israel e os que habitavam em Judá\" (2Cr 30:25) — a gerim da casa, que a lei já mandava incluir na páscoa (Êx 12:48-49).",
    },
    multidao: {
      title: "A congregação mui grande que encheu Jerusalém no segundo mês e celebrou outros sete dias com alegria",
      subtitle: "2Cr 30:13,21-26 • catorze dias de festa, como não houve desde os dias de Salomão",
      text: "\"E ajuntou-se em Jerusalém muito povo, para celebrar a festa dos pães ázimos, no segundo mês; uma congregação mui grande\" (2Cr 30:13). A primeira coisa que essa multidão fez em Jerusalém não foi comer: \"levantaram-se, e tiraram os altares que havia em Jerusalém; também tiraram todos os altares de incenso, e os lançaram no ribeiro de Cedrom\" (2Cr 30:14) — os altares que Acaz mandara fazer \"em todos os cantos de Jerusalém\" (2Cr 28:24) foram parar no mesmo vale onde os levitas tinham despejado a imundícia do templo. Depois vieram sete dias \"com grande alegria\" e o louvor de dia em dia \"com estrondosos instrumentos ao Senhor\" (2Cr 30:21), e então a festa se recusou a acabar: \"E, tendo toda a congregação conselho para celebrarem outros sete dias, celebraram ainda sete dias com alegria\" (2Cr 30:23). O rei deu mil novilhos e sete mil ovelhas, os príncipes mil novilhos e dez mil ovelhas (2Cr 30:24). E o Cronista mede tudo por uma única régua: \"desde os dias de Salomão, filho de Davi, rei de Israel, tal não houve em Jerusalém\" (2Cr 30:26).",
    },
    rebanho: {
      title: "Os cordeiros da páscoa do segundo mês, os mil novilhos e sete mil ovelhas do rei e os mil novilhos e dez mil ovelhas dos príncipes",
      subtitle: "2Cr 30:15,17,24 • o gado que sustentou catorze dias de festa",
      text: "O primeiro rebanho é o da noite da páscoa: \"Então sacrificaram a páscoa no dia décimo quarto do segundo mês\" (2Cr 30:15), um cordeiro por casa, como em Êxodo 12:3-6 — só que aqui, por causa da multidão impura vinda do Norte, quem os mata não é o chefe de família: \"os levitas tinham o encargo de matarem os cordeiros da páscoa por todo aquele que não estava limpo, para o santificarem ao Senhor\" (2Cr 30:17). O segundo rebanho é o da segunda semana, e é a conta de uma festa que dobrou de tamanho sem aviso: \"Porque Ezequias, rei de Judá, ofereceu à congregação mil novilhos e sete mil ovelhas; e os príncipes ofereceram à congregação mil novilhos e dez mil ovelhas\" (2Cr 30:24). Dezenove mil cabeças saídas da fazenda do rei e dos currais dos príncipes para que ninguém fosse embora com fome no meio do avivamento — a mesma generosidade real de Salomão na dedicação do templo (1Rs 8:63), e o motivo pelo qual o capítulo termina comparando as duas festas (2Cr 30:26).",
    },
  },

  // ---------------------------------------------------------------- 2Cr 31
  31: {
    homem: {
      title: "Os israelitas que quebraram as estátuas e cortaram os bosques, o lavrador que trouxe as primícias, os levitas cantores e porteiros e os que empilharam os montões",
      subtitle: "2Cr 31:1-8 • o que o povo fez depois da festa, antes de voltar para casa",
      text: "O capítulo começa com uma surpresa de logística: acabada a páscoa, a multidão não se dispersa para casa, sai para o campo. \"E acabando tudo isto, todos os israelitas que ali se achavam saíram às cidades de Judá e quebraram as estátuas, cortaram os bosques, e derrubaram os altos e altares por toda Judá e Benjamim, como também em Efraim e Manassés, até que tudo destruíram; então tornaram todos os filhos de Israel, cada um para sua possessão\" (2Cr 31:1) — e note que passaram a fronteira: derrubaram alto em Efraim e Manassés, território que já não era de Judá. Depois vem a segunda leva de homens, e ela chega carregada: \"os filhos de Israel trouxeram muitas primícias de trigo, mosto, azeite, mel, e de todo o produto do campo; também os dízimos de tudo trouxeram em abundância\" (2Cr 31:5), \"e fizeram muitos montões\" (2Cr 31:6). O trabalho dos levitas neste capítulo é de eira e de armazém: empilhar, conferir, recolher — \"No terceiro mês começaram a fazer os primeiros montões; e no sétimo mês acabaram\" (2Cr 31:7). Outros ficam \"às portas dos arraiais do Senhor\" (2Cr 31:2), cantando e guardando; foi para que estes homens pudessem \"se dedicar à lei do Senhor\" (2Cr 31:4) que o resto do povo trouxe a porção.",
    },
    anciao: {
      title: "Os príncipes que vieram ver os montões, os sacerdotes que receberam as primícias e conferiram as câmaras, e os sacerdotes dos campos dos arrabaldes",
      subtitle: "2Cr 31:8-13,19 • a auditoria de uma abundância que ninguém esperava",
      text: "\"Vindo, pois, Ezequias e os príncipes, e vendo aqueles montões, bendisseram ao Senhor e ao seu povo Israel\" (2Cr 31:8). A cena é de gente parada diante de uma pilha que cresceu de mês a mês sem que ninguém a tivesse orçado, e a primeira reação dos anciãos não é administrativa, é de bênção. A pergunta administrativa vem em seguida: \"E perguntou Ezequias aos sacerdotes e aos levitas acerca daqueles montões\" (2Cr 31:9) — o rei quer saber o que aquilo é e o que se faz com aquilo. A resposta cria o resto do capítulo: câmaras preparadas na casa do SENHOR (2Cr 31:11), superintendentes por nome, e a regra de que se recolhe \"fielmente\" (2Cr 31:12). O Cronista ainda segue os anciãos para fora de Jerusalém, até as vilas sacerdotais: \"Também dentre os filhos de Arão, os sacerdotes, que estavam nos campos dos arrabaldes das suas cidades, em cada cidade, havia homens que foram designados pelos seus nomes para distribuírem as porções a todo o homem entre os sacerdotes\" (2Cr 31:19) — as cidades levíticas de Números 35, cheias outra vez porque o dízimo voltou.",
    },
    servo: {
      title: "O moço que traz a parte da fazenda do rei, o menino do cântaro do azeite e as crianças de três anos contadas nas genealogias",
      subtitle: "2Cr 31:3,5,16 • os menores da lista, e um registro que começa muito cedo",
      text: "O primeiro destes serviçais vem do celeiro do próprio rei: \"Também estabeleceu a parte da fazenda do rei para os holocaustos; para os holocaustos da manhã e da tarde, e para os holocaustos dos sábados, e das luas novas, e das solenidades; como está escrito na lei do Senhor\" (2Cr 31:3) — Ezequias não financia o altar com imposto novo, tira da sua própria renda. Os outros sobem a rampa da cidade atrás dos pais, com o cântaro do azeite e o pote do mel, porque o povo trouxe \"primícias de trigo, mosto, azeite, mel, e de todo o produto do campo\" (2Cr 31:5). E há uma linha do capítulo que se recusa a arredondar gente: na distribuição das porções entram \"os que estavam contados pelas genealogias dos homens, da idade de três anos para cima, a todos os que entravam na casa do Senhor, para a obra de cada dia no seu dia\" (2Cr 31:16). Três anos — a idade em que uma criança levítica já aparece pelo nome no registro de quem come da casa de Deus. Nenhum sistema de distribuição da Escritura é tão minucioso com os pequenos.",
    },
    rei: {
      title: "Ezequias, que estabeleceu as turmas, deu a parte da sua fazenda e fez o que era bom, e reto, e verdadeiro",
      subtitle: "2Cr 31:2-4,20-21 • o rei visto pela administração, e não pela batalha",
      text: "Depois do avivamento vem a parte que ninguém canta: escala de serviço. \"E estabeleceu Ezequias as turmas dos sacerdotes e levitas, segundo as suas turmas, a cada um segundo o seu ministério\" (2Cr 31:2), restaurando a ordem que Davi tinha montado (1Cr 24-26). Depois assina a despesa do altar com dinheiro seu (2Cr 31:3) e emite a ordem que sustenta o clero: \"E ordenou ao povo, que morava em Jerusalém, que desse a parte dos sacerdotes e levitas, para que eles pudessem se dedicar à lei do Senhor\" (2Cr 31:4) — a razão do sustento é declarada, e é o estudo e o ensino, não o privilégio (cf. Ml 2:7; 1Co 9:13-14). Vendo os montões, pergunta o que são e manda preparar câmaras (2Cr 31:9-11). E o Cronista fecha o retrato com dois versículos que valem por uma biografia: \"E assim fez Ezequias em todo o Judá; e fez o que era bom, e reto, e verdadeiro, perante o Senhor seu Deus\" (2Cr 31:20); \"E toda a obra que começou no serviço da casa de Deus, e na lei, e nos mandamentos, para buscar a seu Deus, ele a fez de todo o seu coração, e prosperou\" (2Cr 31:21).",
    },
    mulherComum: {
      title: "A moradora de Jerusalém que deu a porção dos sacerdotes, a que trouxe o dízimo do mel e a mãe que levou a criança ao registro",
      subtitle: "2Cr 31:4-5,18 • a ordem que caiu sobre as casas da cidade, e as mulheres nas genealogias",
      text: "A ordem do rei tem endereço doméstico: \"E ordenou ao povo, que morava em Jerusalém, que desse a parte dos sacerdotes e levitas, para que eles pudessem se dedicar à lei do Senhor\" (2Cr 31:4). Quem separa a porção na despensa é a casa, e a lista do que subiu é a lista de uma cozinha: \"primícias de trigo, mosto, azeite, mel, e de todo o produto do campo\" (2Cr 31:5) — o mel é o único item da lista que não se colhe em eira nem em lagar, e é justamente o que uma mulher de Judá guardava em pote. O texto ainda faz questão de dizer que a fartura foi imediata: \"depois que se divulgou esta ordem\" (2Cr 31:5) — não houve fiscal, houve pregão. E no registro do fim do capítulo elas aparecem nomeadamente incluídas, o que é raro num rol levítico: \"Como também conforme às genealogias, com todas as suas crianças, suas mulheres, e seus filhos, e suas filhas, por toda a congregação. Porque com fidelidade estes se santificavam nas coisas consagradas\" (2Cr 31:18). Mulher e filha entram na conta de quem come da casa de Deus.",
    },
    rebanho: {
      title: "Os dízimos dos bois e das ovelhas trazidos pelas cidades de Judá",
      subtitle: "2Cr 31:6 • o décimo do curral, somado aos montões do pátio",
      text: "\"E os filhos de Israel e de Judá, que habitavam nas cidades de Judá, também trouxeram dízimos dos bois e das ovelhas, e dízimos das coisas dedicadas que foram consagradas ao Senhor seu Deus; e fizeram muitos montões\" (2Cr 31:6). O dízimo do gado é o mais difícil de dar, porque não se corta ao meio: a lei mandava fazer passar o rebanho debaixo da vara e apartar o décimo, \"Não se investigará entre o bom e o mau, nem o trocará\" (Lv 27:33) — o que sair, sai. E o versículo marca quem faz isso: os que habitavam nas cidades de Judá, gente de fora de Jerusalém que teve de tanger animal por estrada até o templo. Note ainda que o texto diz \"os filhos de Israel e de Judá\": há nesta conta gente do Norte que ficou depois da páscoa do capítulo 30, dizimando num santuário que não era o dos seus pais. O resultado é a frase que Azarias diria ao rei: \"temos comido e temos fartado, e ainda sobejou em abundância\" (2Cr 31:10).",
    },
    patriarca: {
      title: "Azarias, o sumo sacerdote da casa de Zadoque, que explicou os montões ao rei",
      subtitle: "2Cr 31:10 • a resposta que fecha o trecho, dita diante das pilhas do pátio",
      text: "Ezequias perguntou aos sacerdotes e aos levitas o que eram aqueles montões (2Cr 31:9), e quem responde é o cabeça da casa sacerdotal: \"E Azarias, o sumo sacerdote da casa de Zadoque, lhe respondeu, dizendo: Desde que se começou a trazer estas ofertas à casa do Senhor, temos comido e temos fartado, e ainda sobejou em abundância; porque o Senhor abençoou ao seu povo, e sobejou esta abastança\" (2Cr 31:10). A resposta é um balanço e uma teologia ao mesmo tempo: primeiro o fato — comemos, fartamos, sobrou —, e depois a causa, que não é a boa safra nem a boa administração, mas a bênção. Zadoque é a linhagem que ficou com Davi na fuga de Absalão e ungiu Salomão (2Sm 15:24-29; 1Rs 1:39), e a que Ezequiel veria servindo no santuário restaurado (Ez 44:15). Este Azarias reaparece três versículos adiante como \"Azarias, líder da casa de Deus\" (2Cr 31:13), a quem os superintendentes das câmaras respondem junto com o rei — o mesmo homem que contou a sobra é o que fica encarregado de guardá-la.",
    },
    multidao: {
      title: "O povo de Judá que prosperou com Ezequias — o mesmo que saiu quebrando os altos e voltou trazendo os montões",
      subtitle: "2Cr 31:1,5-7,21 • do terceiro mês ao sétimo, a terra coberta de primícias",
      text: "É a mesma multidão do capítulo anterior, e o Cronista a mostra em dois movimentos opostos que são um só. Primeiro derrubando: \"todos os israelitas que ali se achavam saíram às cidades de Judá e quebraram as estátuas, cortaram os bosques, e derrubaram os altos e altares… até que tudo destruíram\" (2Cr 31:1). Depois enchendo: \"os filhos de Israel trouxeram muitas primícias de trigo, mosto, azeite, mel, e de todo o produto do campo; também os dízimos de tudo trouxeram em abundância\" (2Cr 31:5), \"e fizeram muitos montões\" (2Cr 31:6). O calendário da fartura está anotado: \"No terceiro mês começaram a fazer os primeiros montões; e no sétimo mês acabaram\" (2Cr 31:7) — do começo da ceifa do trigo até o fim da vindima e da colheita da azeitona, cinco meses de gente subindo carregada. É a promessa de Provérbios 3:9-10 acontecendo por escrito: honra ao SENHOR com as primícias, e os celeiros se enchem. E o versículo final credita tudo ao coração de um homem que não se acomodou depois da festa: \"ele a fez de todo o seu coração, e prosperou\" (2Cr 31:21).",
    },
  },
};
