// Fichas ESPECÍFICAS por (capítulo → papel) de 2 CRÔNICAS 1–4.
// Quatro capítulos em que Israel tem dois santuários e nenhuma casa: a arca em
// Jerusalém, debaixo da tenda que Davi lhe armou, e o tabernáculo de Moisés com
// o altar de cobre de Bezaleel envelhecendo no alto de Gibeom. É lá que o rei
// novo queima mil holocaustos e ouve, de noite e sem mediador nenhum, "pede o
// que queres que eu te dê" — a única voz do céu do bloco. Do capítulo 2 em
// diante o livro vira canteiro de obras e folha de pagamento: setenta mil de
// carga, oitenta mil talhando pedra na montanha, três mil e seiscentos
// inspetores, os cortadores sidônios do Líbano, as jangadas até Jope, o
// artífice mandado de Tiro, os douradores do lugar santíssimo, os fundidores da
// terra argilosa entre Sucote e Zeredá e os sacerdotes que se lavavam no mar de
// cobre. Aqui o perigo da ficha é o inventário: cada figurante tem um OFÍCIO
// que o texto nomeia, e é por ele que se diz quem é.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_01_04: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- 2Cr 1
  1: {
    anciao: {
      title: "Os juízes e os governadores convocados a todo o Israel — e o conselho que Salomão herdou de Davi",
      subtitle: "2Cr 1:2 • os anciãos do reino chamados antes de qualquer decisão",
      text: "\"E falou Salomão a todo o Israel, aos capitães de mil e de cem, aos juízes e a todos os governadores em todo o Israel, chefes das famílias\" (2Cr 1:2). A primeira coisa que o rei faz com o reino já firme não é decidir: é convocar. Os juízes desta cena são os que Davi separara entre os levitas — \"Destes havia vinte e quatro mil, para promoverem a obra da casa do Senhor, e seis mil oficiais e juízes\" (1Cr 23:4) — e os que respondiam pela vida civil do país, \"Quenanias e seus filhos... postos sobre Israel como oficiais e como juízes, dos negócios externos\" (1Cr 26:29). Ao lado deles ainda estão homens do conselho do velho rei, gente como \"Jônatas, tio de Davi... homem entendido, e também escriba\" (1Cr 27:32). São estes rostos que dão peso ao pedido da noite seguinte: quando Salomão pede \"sabedoria e conhecimento, para que possa sair e entrar perante este povo\" (2Cr 1:10), ele está olhando para a máquina inteira de julgar que acabou de herdar — e confessando que não sabe tocá-la.",
    },
    cavaleiro: {
      title: "Um dos doze mil cavaleiros repartidos entre as cidades dos carros e Jerusalém",
      subtitle: "2Cr 1:14 • a cavalaria nova, comprada onde a lei do rei proibia comprar",
      text: "\"E Salomão ajuntou carros e cavaleiros, e teve mil e quatrocentos carros, e doze mil cavaleiros; os quais pôs nas cidades dos carros, e junto ao rei em Jerusalém\" (2Cr 1:14). Este homem é guarnição de uma das praças fortes do reino — Hazor, Megido, Gezer, \"as cidades dos carros, e as cidades dos cavaleiros\" (1Rs 9:19) —, e o animal que ele monta veio do lugar mais perigoso possível: \"E os cavalos, que tinha Salomão, eram trazidos do Egito\" (2Cr 1:16). O pai fizera o contrário, jarretando os cavalos tomados em batalha e reservando \"deles para cem carros\" (1Cr 18:4), e a lei do rei era expressa: \"ele não multiplicará para si cavalos, nem fará voltar o povo ao Egito para multiplicar cavalos; pois o Senhor vos tem dito: Nunca mais voltareis por este caminho\" (Dt 17:16). O Cronista põe essa cavalaria logo depois do dom da sabedoria e não comenta — mas o salmo comenta por ele: \"Uns confiam em carros e outros em cavalos, mas nós faremos menção do nome do Senhor nosso Deus\" (Sl 20:7).",
    },
    homem: {
      title: "Os capitães de mil e de cem que subiram a Gibeom, o condutor do carro do rei e o mercador que recebia os cavalos em tropas",
      subtitle: "2Cr 1:2,5,14,16-17 • a chefia militar convocada e os homens do negócio dos cavalos",
      text: "\"E falou Salomão a todo o Israel, aos capitães de mil e de cem\" (2Cr 1:2): são os oficiais das doze turmas de vinte e quatro mil homens que serviam mês a mês no reinado de Davi (1Cr 27:1), e é com eles que a nação sobe ao alto para buscar o altar de cobre — \"e Salomão e a congregação o buscavam\" (2Cr 1:5). Descido o monte, os homens em cena trocam de ofício: o condutor de um dos mil e quatrocentos carros que o rei pôs \"nas cidades dos carros, e junto ao rei em Jerusalém\" (2Cr 1:14) e o negociante que ia buscá-los no sul — \"E os cavalos, que tinha Salomão, eram trazidos do Egito; e os mercadores do rei os recebiam em tropas, cada uma pelo seu preço\" (2Cr 1:16). O preço está escriturado, e é o preço de um reino que virou entreposto: \"cada carro por seiscentos siclos de prata, e cada cavalo por cento e cinqüenta\" (2Cr 1:17). O mesmo capitão que viu mil bois arderem no alto de Gibeom fecha o capítulo dentro de um mercado de carruagem egípcia.",
    },
    multidao: {
      title: "Toda a congregação que subiu com o rei ao alto de Gibeom",
      subtitle: "2Cr 1:3,5,13 • a nação inteira diante da tenda que Moisés fizera no deserto",
      text: "\"E foi Salomão, e toda a congregação com ele, ao alto que estava em Gibeom, porque ali estava a tenda da congregação de Deus, que Moisés, servo do Senhor, tinha feito no deserto\" (2Cr 1:3). Em 1 Reis quem sobe é o rei sozinho — \"E foi o rei a Gibeom para lá sacrificar, porque aquele era o alto maior\" (1Rs 3:4) —, e o Cronista faz questão de pôr Israel inteiro atrás dele: a busca é de dois sujeitos, não de um, \"e Salomão e a congregação o buscavam\" (2Cr 1:5). É a mesma gente que acabara de ver Davi morrer em boa velhice e de aclamar o filho \"segunda vez\" (1Cr 29:22); vê agora mil holocaustos arderem sobre o altar de Bezaleel e volta com o rei — \"Assim Salomão veio a Jerusalém, do alto que estava em Gibeom, de diante da tenda da congregação; e reinou sobre Israel\" (2Cr 1:13). Nada do que Deus deu naquela noite foi pedido por um particular: foi pedido no meio de um povo e por causa dele.",
    },
    patriarca: {
      title: "Zadoque e os sacerdotes que ministravam diante do tabernáculo do SENHOR no alto de Gibeom",
      subtitle: "2Cr 1:3-6 • o sacerdócio do santuário velho, onde ficara o altar de Bezaleel",
      text: "Israel tinha dois endereços sagrados ao mesmo tempo, e este é o mais antigo dos dois. Davi \"deixou a Zadoque, o sacerdote, e a seus irmãos, os sacerdotes, diante do tabernáculo do Senhor, no alto que está em Gibeom, para oferecerem holocaustos ao Senhor continuamente, pela manhã e à tarde, sobre o altar dos holocaustos\" (1Cr 16:39-40). É esse sacerdote que recebe o rei: ele guarda a tenda feita no deserto e o \"altar de cobre que tinha feito Bezaleel, filho de Uri, filho de Hur\" (2Cr 1:5) — o artífice a quem Deus enchera \"do Espírito de Deus, de sabedoria, e de entendimento, e de ciência, em todo o lavor\" (Êx 31:3), e cuja obra ainda estava de pé quase quinhentos anos depois. Numa noite só passam pelas mãos dele mil holocaustos (2Cr 1:6). E todo o seu ofício está prestes a mudar de lugar: quando a casa ficar pronta, \"fizeram subir a arca, e a tenda da congregação, com todos os objetos sagrados, que estavam na tenda; os sacerdotes e os levitas os fizeram subir\" (2Cr 5:5) — e Gibeom deixa de ser santuário para sempre.",
    },
    rebanho: {
      title: "Os mil holocaustos queimados sobre o altar de cobre de Gibeom",
      subtitle: "2Cr 1:6 • o gado de uma noite inteira de fogo diante da tenda de Moisés",
      text: "\"E Salomão ofereceu ali sacrifícios perante o Senhor, sobre o altar de cobre que estava na tenda da congregação; e ofereceu sobre ele mil holocaustos\" (2Cr 1:6). Holocausto é a oferta que não volta para quem a trouxe: \"o sacerdote tudo isso queimará sobre o altar; holocausto é, oferta queimada, de cheiro suave ao Senhor\" (Lv 1:9) — mil cabeças e nenhuma porção de volta. O número repete o do dia em que Israel confirmou o reino do moço, \"mil bezerros, mil carneiros, mil cordeiros, com as suas libações\" (1Cr 29:21), e ainda ficará pequeno diante do que arderá na dedicação da casa: \"sacrifícios de bois, vinte e dois mil, e de ovelhas, cento e vinte mil\" (2Cr 7:5). O que o texto sublinha não é a conta e sim a ordem dos fatos: o rei gasta primeiro e só depois recebe a pergunta — \"Naquela mesma noite Deus apareceu a Salomão, e disse-lhe: Pede o que queres que eu te dê\" (2Cr 1:7).",
    },
    rei: {
      title: "Os reis dos heteus e os reis da Síria, compradores das tropas de cavalos de Salomão",
      subtitle: "2Cr 1:17 • os fregueses estrangeiros do comércio de carros do Egito",
      text: "\"E faziam subir e sair do Egito cada carro por seiscentos siclos de prata, e cada cavalo por cento e cinqüenta; e assim, por meio deles eram para todos os reis dos heteus, e para os reis da Síria\" (2Cr 1:17). Os \"heteus\" aqui não são os cananeus da conquista, e sim os reinos neo-heteus do norte da Síria — Carquemis, Hamate —, e os \"reis da Síria\" são os principados arameus de Damasco e arredores. Israel, assentado na estrada entre o Egito e o norte, deixa de ser só freguês e vira atravessador: compra no sul, revende no norte, e a prata entra em Jerusalém \"como pedras\" (2Cr 1:15). Estes mesmos fregueses reapareceriam num susto: cercada Samaria, foi um ruído de carros que fez o exército sírio fugir de noite, dizendo uns aos outros \"Eis que o rei de Israel alugou contra nós os reis dos heteus e os reis dos egípcios, para virem contra nós\" (2Rs 7:6). A fama que Salomão fez no mercado ainda assustava os inimigos de Israel muito depois da sua morte.",
    },
    servo: {
      title: "Os levitas das duas tendas — a de Moisés em Gibeom e a que Davi armou para a arca — e os servos do tesouro, da forragem e das tropas de cavalos",
      subtitle: "2Cr 1:3-6,14-16 • quem serve nos dois santuários e quem toca a casa do rei",
      text: "O reino tinha dois lugares de serviço ao mesmo tempo, e estes servos são a gente dos dois. Em Jerusalém, junto à tenda nova, ficaram \"Asafe e a seus irmãos, para ministrarem continuamente perante a arca, segundo se ordenara para cada dia\" (1Cr 16:37), porque \"Davi tinha feito subir a arca de Deus de Quiriate-Jearim ao lugar que lhe preparara; porque lhe tinha armado uma tenda em Jerusalém\" (2Cr 1:4). Em Gibeom, o levita que serve ao altar de cobre e à tenda velha do deserto na noite dos mil holocaustos (2Cr 1:5-6). Depois de Gibeom o serviço muda de assunto e fica bem mundano: o do tesouro, que arruma o que o texto diz haver \"em Jerusalém como pedras\" (2Cr 1:15); o das cocheiras, porque alguém tinha de trazer \"a cevada e a palha para os cavalos e para os ginetes\" (1Rs 4:28); e o tratador que recebia os animais no lote, pois \"os mercadores do rei os recebiam em tropas, cada uma pelo seu preço\" (2Cr 1:16). Um capítulo só emprega mãos no altar e mãos na estrebaria — e o Cronista deixa o leitor notar a diferença.",
    },
  },

  // ---------------------------------------------------------------- 2Cr 2
  2: {
    homem: {
      title: "Os três mil e seiscentos inspetores da obra, o escrivão do rol, o arauto que leu a carta em Tiro, o escriba de Hirão e os peritos que Davi preparou em Judá",
      subtitle: "2Cr 2:2,7,11,17-18 • a chefia do canteiro e os dois lados da correspondência",
      text: "A obra começa por uma folha de pessoal: \"E designou Salomão setenta mil homens de carga, e oitenta mil que talhavam pedras na montanha, e três mil e seiscentos inspetores sobre eles\" (2Cr 2:2), e o encargo do inspetor é dito sem eufemismo no fecho do capítulo — \"três mil e seiscentos inspetores, para fazerem trabalhar o povo\" (2Cr 2:18). O escrivão em cena é o do alistamento, porque \"Salomão contou todos os homens estrangeiros, que havia na terra de Israel, conforme o censo com que os contara Davi seu pai\" (2Cr 2:17). O arauto é a boca do rei em terra alheia: a carta a Hirão é lida diante de um trono fenício, e nela Salomão pede o artífice \"juntamente com os peritos que estão comigo em Judá e em Jerusalém, os quais Davi, meu pai, preparou\" (2Cr 2:7) — ourives que já estavam formados havia anos, treinados pelo velho rei para uma casa que ele não veria. Do outro lado da mesa há outro escriba, porque a resposta não veio por recado de boca: \"E Hirão, rei de Tiro, respondeu por escrito que enviou a Salomão\" (2Cr 2:11).",
    },
    mulherComum: {
      title: "A mãe de Hirão Abiú — uma das filhas de Dã, casada com um homem de Tiro",
      subtitle: "2Cr 2:14 • a mulher israelita de quem saiu o artífice do templo",
      text: "\"Filho de uma mulher das filhas de Dã, e cujo pai foi homem de Tiro\" (2Cr 2:14). A carta do rei fenício apresenta o seu melhor artífice pela mãe, e é essa metade israelita que faz dele mais do que um estrangeiro contratado. Em 1 Reis a mesma notícia vem com outro recorte: \"filho de uma mulher viúva, da tribo de Naftali, e fora seu pai um homem de Tiro, que trabalhava em cobre\" (1Rs 7:14) — danita de nascimento, casada e enviuvada no norte, a um dia de viagem do porto. E a tribo dela não está ali por acaso: quando Deus mandou fazer o tabernáculo, deu Bezalel de Judá e, ao lado dele, \"Aoliabe, o filho de Aisamaque, da tribo de Dã\" (Êx 31:6), a quem também \"dispôs o coração para ensinar a outros\" (Êx 35:34). O segundo artífice do deserto era danita; a mãe do artífice do templo também. Nenhum dos dois santuários de Israel foi levantado só pelas mãos das tribos de honra.",
    },
    multidao: {
      title: "Os cento e cinqüenta e três mil e seiscentos estrangeiros contados na terra de Israel",
      subtitle: "2Cr 2:2,17-18 • o rol dos de fora alistado para o canteiro do templo",
      text: "\"E Salomão contou todos os homens estrangeiros, que havia na terra de Israel, conforme o censo com que os contara Davi seu pai; e acharam-se cento e cinqüenta e três mil e seiscentos\" (2Cr 2:17). São os restos dos povos da terra — \"amorreus, heteus, perizeus, heveus, e jebuseus, e que não eram dos filhos de Israel\", a quem Salomão \"reduziu a tributo servil, até hoje\" (1Rs 9:20-21) —, e a ideia não é dele: Davi já \"deu ordem... que se ajuntassem os estrangeiros que estavam na terra de Israel; e ordenou cortadores de pedras, para que lavrassem pedras de cantaria, para edificar a casa de Deus\" (1Cr 22:2). O alistamento reparte a multidão em três: \"setenta mil carregadores, e oitenta mil cortadores na montanha; como também três mil e seiscentos inspetores\" (2Cr 2:18). É gente que serve sem ser do povo — e o mesmo rei que a arregimenta abrirá a boca por ela na dedicação: \"Assim também ao estrangeiro, que não for do teu povo Israel, quando vier de terras remotas por amor do teu grande nome... ouve tu desde os céus\" (2Cr 6:32-33).",
    },
    patriarca: {
      title: "O sacerdote do incenso aromático, do pão contínuo e dos holocaustos da manhã e da tarde",
      subtitle: "2Cr 2:4 • o culto para o qual a casa está sendo encomendada",
      text: "Antes de pedir uma tora de cedro, Salomão explica a Hirão para que serve o prédio: \"Eis que estou para edificar uma casa ao nome do Senhor meu Deus, para lhe consagrar, para queimar perante ele incenso aromático, e para a apresentação contínua do pão da proposição, para os holocaustos da manhã e da tarde, nos sábados e nas luas novas, e nas festividades do Senhor nosso Deus; o que é obrigação perpétua de Israel\" (2Cr 2:4). O sacerdote em cena é quem executa essa lista: os doze pães postos em duas fileiras \"em cada dia de sábado... perante o Senhor continuamente, pelos filhos de Israel, por aliança perpétua\" (Lv 24:8), o cordeiro da manhã e o da tarde, o incenso puro. A palavra decisiva da carta é \"perpétua\": a casa não se levanta para ser vista, levanta-se para que um ofício que não pode parar tenha onde acontecer. E o rei já sabe o limite do que está encomendando — \"quem seria capaz de lhe edificar uma casa, visto que os céus e até os céus dos céus o não podem conter? E quem sou eu, que lhe edificasse casa, salvo para queimar incenso perante ele?\" (2Cr 2:6).",
    },
    rei: {
      title: "Dois tronos e uma carta entre eles: o rei que encomenda a casa e o rei de Tiro que responde por escrito",
      subtitle: "2Cr 2:3,11-12 • a correspondência que abre o canteiro do templo",
      text: "O capítulo inteiro é uma troca de cartas entre dois reinos. De Jerusalém sai o pedido, e ele começa por uma dívida de família: \"Como fizeste com Davi meu pai, mandando-lhe cedros, para edificar uma casa em que morasse, assim também faze comigo\" (2Cr 2:3). De Tiro vem a resposta \"por escrito\" (2Cr 2:11), e o espantoso é a teologia dela: um rei fenício, de uma cidade que servia a Melcarte, escreve \"Bendito seja o Senhor Deus de Israel, que fez os céus e a terra; o que deu ao rei Davi um filho sábio, de grande prudência e entendimento, que edifique casa ao Senhor, e para o seu reino\" (2Cr 2:12) — e lê corretamente a razão daquele trono: \"Porque o Senhor tem amado o seu povo, te constituiu sobre ele rei\" (2Cr 2:11). O acordo é comercial até o osso: trigo, cevada, vinho e azeite em troca de madeira (2Cr 2:10,15). Mas o Cronista, escrevendo para um povo pequeno e cercado de impérios, quer que se veja quem foi o primeiro estrangeiro a bendizer o Deus de Israel por causa desta casa.",
    },
    servo: {
      title: "Os setenta mil de carga, os oitenta mil que talhavam na montanha, os cortadores sidônios do Líbano, os jangadeiros de Jope e o medidor dos coros e dos batos",
      subtitle: "2Cr 2:2,8-10,16,18 • as mãos e a paga do maior canteiro de obras de Israel",
      text: "\"E designou Salomão setenta mil homens de carga, e oitenta mil que talhavam pedras na montanha\" (2Cr 2:2) — cento e cinquenta mil homens antes de a primeira pedra ser assentada. No Líbano quem derruba não é israelita, e o rei o diz sem constrangimento nenhum: \"porque bem sei eu que os teus servos sabem cortar madeira no Líbano; e eis que os meus servos estarão com os teus servos\" (2Cr 2:8), o mesmo reconhecimento que a narrativa de Reis registra — \"entre nós ninguém há que saiba cortar a madeira como os sidônios\" (1Rs 5:6). A paga é comida, e alguém passa o dia com a medida na mão: \"vinte mil coros de trigo malhado, vinte mil coros de cevada, vinte mil batos de vinho e vinte mil batos de azeite\" (2Cr 2:10). O transporte é por água, com os toros amarrados uns aos outros: \"E nós cortaremos tanta madeira no Líbano, quanta houveres mister, e ta traremos em jangadas pelo mar até Jope, e tu a farás subir a Jerusalém\" (2Cr 2:16). Quatro séculos e um exílio depois, os que voltaram refizeram o mesmo trajeto com o mesmo contrato: dinheiro aos pedreiros e carpinteiros, \"e azeite aos sidônios, e aos tírios, para trazerem do Líbano madeira de cedro ao mar, para Jope\" (Ed 3:7).",
    },
  },

  // ---------------------------------------------------------------- 2Cr 3
  3: {
    homem: {
      title: "O mestre de obras dos sessenta côvados, o escrivão que anota a medida, o entalhador das palmas e das cadeias e o tecelão do véu",
      subtitle: "2Cr 3:3-5,7,14 • os ofícios que levantam a casa no monte Moriá",
      text: "\"E estes foram os fundamentos que Salomão pôs para edificar a casa de Deus: o comprimento em côvados, segundo a primeira medida, era de sessenta côvados, e a largura de vinte côvados\" (2Cr 3:3) — e a ressalva \"segundo a primeira medida\" é trabalho de escrivão: o Cronista avisa em que côvado está falando, porque escreve para uma geração que já mede de outro jeito. O mestre de obras responde pelo pórtico, cuja \"altura era de cento e vinte; e por dentro o revestiu com ouro puro\" (2Cr 3:4). O entalhador entra depois da forra de madeira: \"E a casa grande forrou com madeira de faia; e então a revestiu com ouro fino; e fez sobre ela palmas e cadeias\" (2Cr 3:5), e \"lavrou querubins nas paredes\" (2Cr 3:7) — palmeira, corrente e querubim, o jardim e a sua guarda talhados na parede de uma casa. E o tecelão fecha a lista com a peça mais carregada de sentido do templo inteiro: \"Também fez o véu de azul, púrpura, carmesim e linho fino; e pôs sobre ele querubins\" (2Cr 3:14) — a cortina que, no dia da cruz, \"se rasgou em dois, de alto a baixo\" (Mt 27:51).",
    },
    mulherComum: {
      title: "A fiandeira do linho fino e das lãs de azul, púrpura e carmesim do véu",
      subtitle: "2Cr 3:14 • a mão que fia o pano que fecha o lugar santíssimo",
      text: "\"Também fez o véu de azul, púrpura, carmesim e linho fino; e pôs sobre ele querubins\" (2Cr 3:14). As quatro matérias são as mesmas do véu do tabernáculo, e no deserto o texto diz de quem eram as mãos que as preparavam: \"E todas as mulheres sábias de coração fiavam com as suas mãos, e traziam o que tinham fiado, o azul e a púrpura, o carmesim e o linho fino\" (Êx 35:25). Fiar é trabalho lento e invisível: a púrpura saía do múrice apanhado na costa de Tiro, o carmesim de um inseto, e o linho fino exigia fio parelho do começo ao fim do rolo. Dessa paciência sai a única peça do templo que ninguém podia atravessar. Esta mulher jamais entraria no lugar que a sua obra fecha — e foi justamente esse pano que Deus mandou rasgar, para que houvesse \"ousadia para entrar no santuário, pelo sangue de Jesus, pelo novo e vivo caminho que ele nos consagrou, pelo véu, isto é, pela sua carne\" (Hb 10:19-20).",
    },
    multidao: {
      title: "O povo do adro no dia em que Jaquim e Boaz foram levantadas diante da casa",
      subtitle: "2Cr 3:15-17 • a assistência das duas colunas de trinta e cinco côvados",
      text: "\"E levantou as colunas diante do templo, uma à direita, e outra à esquerda; e chamou o nome da que estava à direita Jaquim, e o nome da que estava à esquerda Boaz\" (2Cr 3:17). São trinta e cinco côvados de cobre subindo à vista de todo mundo, com capitel de cinco, cadeias no alto e \"cem romãs, as quais pôs entre as cadeias\" (2Cr 3:16) — obra que não sustenta telhado nenhum e existe só para ser lida por quem chega. Jaquim quer dizer \"ele estabelecerá\"; Boaz, \"nele há força\". O povo que se junta no adro é o mesmo que encherá este pátio dois capítulos adiante, quando os cantores e as trombetas fizerem \"ouvir uma só voz\" e \"a casa se encheu de uma nuvem\", de modo que \"os sacerdotes não podiam permanecer em pé, para ministrar\" (2Cr 5:13-14). Diante da porta, o primeiro sermão do templo é feito de dois pilares e dois nomes: o que se firma ali não se firma pela mão de quem entra.",
    },
    patriarca: {
      title: "O sacerdote na eira de Ornã, o jebuseu — o chão do monte Moriá onde a peste parou",
      subtitle: "2Cr 3:1 • o endereço do templo, escolhido por uma aparição e não por conveniência",
      text: "\"E começou Salomão a edificar a casa do SENHOR em Jerusalém, no monte Moriá, onde o SENHOR aparecera a Davi seu pai, no lugar que Davi tinha preparado na eira de Ornã, o jebuseu\" (2Cr 3:1). Três memórias se cruzam neste chão. Moriá é a terra para onde Abraão levou o filho: \"vai-te à terra de Moriá, e oferece-o ali em holocausto sobre uma das montanhas, que eu te direi\" (Gn 22:2). A eira é o lugar onde o anjo da peste parou e onde Davi recusou receber o terreno de presente — \"Não, antes, pelo seu valor, a quero comprar; porque não tomarei o que é teu, para o Senhor, para que não ofereça holocausto sem custo\" (1Cr 21:24) —, pagando \"o peso de seiscentos siclos de ouro\" (1Cr 21:25). E ali \"invocou o Senhor, o qual lhe respondeu com fogo do céu sobre o altar do holocausto\" (1Cr 21:26), depois do que o velho rei sentenciou: \"Esta será a casa do SENHOR Deus, e este será o altar do holocausto para Israel\" (1Cr 22:1). O sacerdote desta cena pisa um chão que já foi eira de trilhar trigo, altar improvisado e sinal de misericórdia — e que agora vira alicerce.",
    },
    rei: {
      title: "O rei que começa a edificar no segundo dia do segundo mês do quarto ano",
      subtitle: "2Cr 3:1-2 • a data exata em que a casa saiu do papel",
      text: "\"E começou a edificar no segundo mês, no segundo dia, no ano quarto do seu reinado\" (2Cr 3:2). O Cronista data a obra como quem lavra escritura, e a narrativa paralela amplia a conta: foi \"no ano de quatrocentos e oitenta, depois de saírem os filhos de Israel do Egito... no mês de Zive (este é o mês segundo)\" (1Rs 6:1) — a casa nasce dentro do calendário que começa no êxodo, porque é o mesmo Deus e o mesmo povo. Quatro anos separam o pedido de sabedoria em Gibeom da primeira pedra assentada, e neles couberam o censo de cento e cinquenta mil homens, duas cartas a Tiro e os cedros descidos em jangadas até Jope. O rei que aparece aqui não é o do trono, é o do canteiro — e nem o risco é dele: a planta veio pronta da mão do pai, \"a planta do alpendre com as suas casas, e as suas tesourarias, e os seus cenáculos, e as suas recâmaras interiores\" (1Cr 28:11), sobre a qual Davi declarou: \"fez-me entender o Senhor, por escrito da sua mão\" (1Cr 28:19).",
    },
    servo: {
      title: "O do cordel da medida, os douradores do pórtico e do lugar santíssimo, o aprendiz do buril e os que levantaram as colunas",
      subtitle: "2Cr 3:3-5,8-9,15-17 • as mãos que cobrem de ouro e erguem o cobre",
      text: "Estes servos fazem o trabalho mais repetitivo e mais caro da Escritura: bater ouro em folha e assentá-lo sobre madeira, dia após dia. O pórtico, \"por dentro o revestiu com ouro puro\" (2Cr 3:4); a casa grande, forrada de faia e revestida \"com ouro fino\" (2Cr 3:5); o lugar santíssimo, vinte por vinte, \"revestiu-a de ouro fino, do peso de seiscentos talentos\" (2Cr 3:8); e até o que ninguém tornaria a ver depois de cravado entrou na balança — \"O peso dos pregos era de cinqüenta siclos de ouro; e as câmaras cobriu de ouro\" (2Cr 3:9). Ao lado deles está o aprendiz que serve o buril do entalhador nas palmas, nas cadeias e nos querubins das paredes (2Cr 3:5,7), e o que estica o cordel para conferir os sessenta côvados por vinte do alicerce (2Cr 3:3). No fim do capítulo o serviço vira força bruta: aprumar duas colunas de trinta e cinco côvados diante da porta, \"uma à direita, e outra à esquerda\" (2Cr 3:17). O ouro é do rei e o nome das colunas é de Deus; a lombeira é destes homens.",
    },
  },

  // ---------------------------------------------------------------- 2Cr 4
  4: {
    homem: {
      title: "O mestre das redes e dos capitéis, o escrivão das quatrocentas romãs e o ourives do ouro finíssimo",
      subtitle: "2Cr 4:12-13,18,21 • quem conta e quem confere o inventário da casa",
      text: "O capítulo 4 é uma lista, e lista precisa de quem a escreva. As peças do alto são as mais difíceis de conferir: \"As duas colunas, os globos, e os dois capitéis sobre as cabeças das colunas; e as duas redes, para cobrir os dois globos dos capitéis, que estavam sobre a cabeça das colunas\" (2Cr 4:12) — e sobre as redes vem a conta que só um escrivão teria paciência de fechar: \"E as quatrocentas romãs para as duas redes; duas carreiras de romãs para cada rede\" (2Cr 4:13). Ainda assim o inventário chega a um limite e o admite por escrito: \"E fez Salomão todos estes objetos em grande abundância, que não se podia averiguar o peso do cobre\" (2Cr 4:18) — o mesmo que já sucedera com o metal que Davi ajuntou, \"de cobre e de ferro que não se pesou, porque era em abundância\" (1Cr 22:14). O ourives fecha o rol pelo outro extremo, o das miudezas que se contam uma a uma: \"E as flores, as lâmpadas e os espevitadores eram de ouro, do mais finíssimo ouro\" (2Cr 4:21).",
    },
    patriarca: {
      title: "Os sacerdotes do átrio: o que se lava no mar de cobre, o que acende as lâmpadas perante o oráculo e o que põe os pães da proposição",
      subtitle: "2Cr 4:6,8,19-20 • o ofício para o qual cada peça de cobre e de ouro foi feita",
      text: "O inventário deste capítulo só faz sentido pelos homens que vão usá-lo. O tanque de dez côvados não é ornamento: \"o que pertencia ao holocausto o lavavam nelas; porém o mar era para que os sacerdotes se lavassem nele\" (2Cr 4:6) — é a pia do tabernáculo crescida até virar mar, e a ordem que a instituiu não admitia descuido: \"Quando entrarem na tenda da congregação, lavar-se-ão com água, para que não morram\" (Êx 30:20). As dez mesas recebem o pão que se troca de sábado em sábado, \"as mesas, sobre as quais estavam os pães da proposição\" (2Cr 4:19), posto em ordem \"por aliança perpétua\" (Lv 24:8). E os dez castiçais têm hora e regra: \"E os castiçais com as suas lâmpadas de ouro finíssimo, para as acenderem segundo o costume, perante o oráculo\" (2Cr 4:20) — o costume é o do deserto, azeite puro de oliveiras batido e as lâmpadas em ordem \"desde a tarde até a manhã, perante o Senhor\" (Êx 27:20-21). Lavar, alimentar e acender: o sacerdote do átrio de Salomão faz em ouro o que os filhos de Arão faziam em cobre debaixo de uma tenda.",
    },
    rebanho: {
      title: "Os doze bois de cobre debaixo do mar de fundição — três para cada rumo do céu",
      subtitle: "2Cr 4:4,15 • as figuras fundidas que sustentavam o mar no pátio dos sacerdotes",
      text: "\"E o mar estava posto sobre doze bois; três que olhavam para o norte, três que olhavam para o ocidente, três que olhavam para o sul e três que olhavam para o oriente; e o mar estava posto sobre eles; e as suas partes posteriores estavam todas para o lado de dentro\" (2Cr 4:4). Não são animais vivos, e sim quatro grupos de cobre fundido, cada um encarando um ponto do horizonte — doze, como as tribos, carregando a água em que os sacerdotes se lavavam antes de ministrar. O resumo da obra os repete no fecho: \"Um mar, e os doze bois debaixo dele\" (2Cr 4:15). O fim deles ficou escrito em dois tempos, e nenhum é bom: primeiro Acaz, que \"tirou o mar de sobre os bois de cobre, que estavam debaixo dele, e pô-lo sobre um pavimento de pedra\" (2Rs 16:17); depois os caldeus, que quebraram tudo e levaram o metal — \"Quanto às duas colunas, ao único mar, e aos doze bois de bronze, que estavam debaixo das bases, que fizera o rei Salomão para a casa do Senhor, o peso do bronze de todos estes utensílios era incalculável\" (Jr 52:20).",
    },
    rei: {
      title: "O rei que desceu a fundição para a campina do Jordão",
      subtitle: "2Cr 4:17-18 • o cobre moldado na terra argilosa entre Sucote e Zeredá",
      text: "\"Na campina do Jordão os fundiu o rei, na terra argilosa, entre Sucote e Zeredá\" (2Cr 4:17). O maior objeto de metal já feito em Israel não saiu de Jerusalém: a obra desceu ao vale, quase mil metros abaixo, porque ali havia o barro que segura o molde, a lenha dos bosques do rio e a água à mão. É chão de história antiga — Sucote foi a cidade que negou pão aos homens cansados de Gideão (\"Estão já, Zeba e Salmuna, em tua mão, para que demos pão ao teu exército?\", Jz 8:6), e a campina é a que Ló escolheu por ser \"toda bem regada... como o jardim do Senhor\" (Gn 13:10). Foi nessa terra comum que se fundiu o mar sobre os doze bois. E a conta ficou aberta de propósito: \"E fez Salomão todos estes objetos em grande abundância, que não se podia averiguar o peso do cobre\" (2Cr 4:18) — o metal que Davi ajuntara sem pesar \"porque era em abundância\" (1Cr 22:14) voltou do fogo em forma de altar, de mar, de bases e de pias.",
    },
    servo: {
      title: "Os fundidores da terra argilosa, o moldador de barro do vale, o polidor do cobre, o levita que lava o holocausto e o porteiro do pátio dos sacerdotes",
      subtitle: "2Cr 4:6,9,16-17 • as mãos que fundem, poliem, lavam e guardam",
      text: "\"Semelhantemente as caldeiras, as pás, os garfos e todos os seus utensílios, fez Hirão Abiú ao rei Salomão, para a casa do Senhor, de cobre polido\" (2Cr 4:16): polir é serviço de servo — dias de areia, pano e braço até o metal responder à luz. Antes dele vieram o moldador, que abriu as formas na argila do vale, e o fundidor que despejou o cobre derretido: \"Na campina do Jordão os fundiu o rei, na terra argilosa, entre Sucote e Zeredá\" (2Cr 4:17). Já dentro do pátio, o levita das dez pias tem uma tarefa suja e exata: \"o que pertencia ao holocausto o lavavam nelas\" (2Cr 4:6) — a vítima não sobe ao altar com a terra do caminho. E o porteiro responde pelas duas cercas que este capítulo levanta: \"Fez mais o pátio dos sacerdotes, e o grande átrio; como também as portas para o pátio, as quais revestiu de cobre\" (2Cr 4:9). Daqui em diante há um lugar para o povo e outro para quem ministra, e um homem de carne e osso guarda a porta entre os dois.",
    },
  },
};
