// Fichas ESPECÍFICAS por (capítulo → papel) de 2 CRÔNICAS 15–20.
// Seis capítulos em que a palavra de Deus não desce nenhuma vez do céu: ela
// atravessa a praça na boca de cinco homens — Azarias, filho de Odede, na
// estrada do despojo de Zerá; Hanani, o vidente, no dia da vitória comprada
// com a prata da casa do SENHOR; Micaías, filho de Inlá, contra quatrocentos
// profetas e dois tronos na porta de Samaria; Jeú, filho de Hanani, à porta de
// casa de um rei que voltou vivo de uma guerra que não era sua; e Jaaziel, o
// levita dos filhos de Asafe, no meio de uma congregação que estava em pé com
// as suas crianças e as suas mulheres. No meio disso, uma rainha-mãe deposta e
// o seu ídolo queimado no ribeiro de Cedrom, um vidente na casa do tronco, um
// rei que adoece dos pés e busca os médicos, príncipes mandados ensinar com o
// livro da lei pelas cidades de Judá, uma flecha atirada a esmo que acha a
// brecha de uma couraça, juízes postos de cidade em cidade e cantores saindo
// ADIANTE dos armados para o deserto de Tecoa.
// Cada figurante anônimo da cena é alguém REAL daquele capítulo.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_15_20: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- 2Cr 15
  15: {
    anciao: {
      title: "Os chefes das casas paternas de Judá e de Benjamim que entraram na aliança do terceiro mês",
      subtitle: "2Cr 15:9-15 • os cabeças de casa que juraram em alta voz diante do altar renovado",
      text: "São os homens que respondem à convocação depois que o rei ouve o profeta: \"E reuniu a todo o Judá, e Benjamim, e com eles os estrangeiros de Efraim e Manassés, e de Simeão\" (2Cr 15:9), e a razão dada é que \"muitos de Israel tinham passado a ele, vendo que o Senhor seu Deus era com ele\". Sobem a Jerusalém na data marcada — \"E ajuntaram-se em Jerusalém no terceiro mês; no ano décimo do reinado de Asa\" (2Cr 15:10) —, o mês de Pentecostes, o mês em que Israel recebeu a lei no Sinai, e ali refazem a aliança: \"E entraram na aliança para buscarem o Senhor Deus de seus pais, com todo o seu coração, e com toda a sua alma\" (2Cr 15:12). Nada disso é feito em surdina. \"E juraram ao Senhor, em alta voz, com júbilo e com trombetas e buzinas\" (2Cr 15:14) — o juramento tem testemunhas, tem barulho e tem data. Estes chefes são os mesmos que, dez anos antes, tinham visto a terra em paz e o rei mandar \"a Judá que buscasse ao Senhor Deus de seus pais, e que observasse a lei e o mandamento\" (2Cr 14:4). O resultado é registrado como coisa recebida, não conquistada: \"e de toda a sua vontade o buscaram, e o acharam; e o Senhor lhes deu repouso ao redor\" (2Cr 15:15)."
    },
    homem: {
      title: "Os homens de Judá e de Benjamim que voltavam do despojo, o viajante sem paz e os dois guerreiros de cidade contra cidade",
      subtitle: "2Cr 15 • quem ouve o oráculo na estrada, quem aparece dentro do retrato dos dias sem lei e quem continua subindo ao alto",
      text: "Os primeiros vêm carregados do saque de Zerá, o etíope, que saíra contra Judá \"com um exército de um milhão e com trezentos carros\" (2Cr 14:9) e ficou pelo caminho: são eles que estão atrás do rei quando Azarias sai ao encontro e diz \"Ouvi-me, Asa, e todo o Judá e Benjamim\" (2Cr 15:2) — o oráculo é dirigido a eles também, e não só ao trono. Depois entram os que povoam o quadro que o profeta pinta: o homem dos dias em que \"Israel esteve por muitos dias sem o verdadeiro Deus, e sem sacerdote que o ensinasse, e sem lei\" (2Cr 15:3); o viajante que ficou parado entre duas cidades, porque \"naqueles tempos não havia paz, nem para o que saía, nem para o que entrava\" (2Cr 15:5); e os dois armados frente a frente, cada um saído da sua terra, porque \"nação contra nação e cidade contra cidade se despedaçavam; porque Deus os perturbara com toda a angústia\" (2Cr 15:6). Também é homem de Judá quem carrega para fora as abominações que o rei tirou \"de toda a terra, de Judá e de Benjamim, como também das cidades que tomara nas montanhas de Efraim\" (2Cr 15:8), e é homem quem vem de Efraim e de Manassés atrás de um Deus que não achava mais em casa (2Cr 15:9). E, no fim, é um homem de Judá que continua subindo ao outeiro depois de tudo, porque os altos \"não foram tirados de Israel\" (2Cr 15:17): a reforma de um rei não alcança o pé que já pegou o caminho."
    },
    mulherComum: {
      title: "Maaca, a rainha-mãe deposta, a mulher que entrou na aliança e a mulher dos dias sem lei",
      subtitle: "2Cr 15 • a que perdeu o posto por causa de um ídolo e as que juraram debaixo da mesma cláusula que os homens",
      text: "A aliança do terceiro mês não abre exceção de sexo nem de tamanho: quem não buscasse ao SENHOR morreria, \"assim o menor como o maior, tanto o homem como a mulher\" (2Cr 15:13) — a mulher de Judá está no juramento em pé de igualdade, e por isso está no quadro. E é exatamente essa cláusula sem exceção que explica o gesto seguinte, o mais duro do reinado: \"E também a Maaca, sua mãe, o rei Asa depôs, para que não fosse mais rainha, porquanto fizera um horrível ídolo, a Aserá\" (2Cr 15:16). Maaca, neta de Absalão (1Rs 15:2, 10), era a gebirá, a mulher mais poderosa da corte, e a única a quem o rei devia obediência de filho. Asa não se contenta em tirá-la do posto: \"e Asa destruiu o seu horrível ídolo, e o despedaçou, e o queimou junto ao ribeiro de Cedrom\" (2Cr 15:16) — o mesmo ribeiro em que Josias mandaria queimar os vasos de Baal gerações depois (2Rs 23:4, 6). Antes disso, no retrato dos dias sem lei, está a mulher que criou os filhos numa terra sem sacerdote que ensinasse (2Cr 15:3) e que se ajoelhou quando \"na sua angústia voltaram para o Senhor Deus de Israel, e o buscaram, o acharam\" (2Cr 15:4)."
    },
    multidao: {
      title: "A congregação de todo o Judá e Benjamim ajuntada em Jerusalém no terceiro mês",
      subtitle: "2Cr 15:10-15 • o povo que sacrificou do despojo e jurou com júbilo, trombetas e buzinas",
      text: "É o ajuntamento do décimo ano de Asa, e a Escritura anota o mês porque o mês diz alguma coisa: \"E ajuntaram-se em Jerusalém no terceiro mês\" (2Cr 15:10), o mês da festa das semanas, quando Israel subia com os primeiros frutos. Os primeiros frutos, desta vez, são o saque do etíope: \"E no mesmo dia ofereceram em sacrifício ao Senhor, do despojo que trouxeram, setecentos bois e sete mil ovelhas\" (2Cr 15:11) — nada do que veio da vitória fica guardado no palácio. Depois vem o juramento, e o cronista descreve o barulho como parte da coisa: \"E juraram ao Senhor, em alta voz, com júbilo e com trombetas e buzinas\" (2Cr 15:14). O que se ouve não é entusiasmo obrigado: \"E todo o Judá se alegrou deste juramento; porque de todo o seu coração juraram, e de toda a sua vontade o buscaram, e o acharam; e o Senhor lhes deu repouso ao redor\" (2Cr 15:15). É a demonstração pública da frase de Azarias — \"se o buscardes, o achareis\" (2Cr 15:2) — cumprida no mesmo capítulo em que foi dita."
    },
    patriarca: {
      title: "Azarias, filho de Odede, sobre quem veio o Espírito de Deus",
      subtitle: "2Cr 15:1-7 • o profeta que sai ao encontro do rei na estrada de volta do despojo",
      text: "Aparece do nada e some no mesmo capítulo: \"Então veio o Espírito de Deus sobre Azarias, filho de Odede\" (2Cr 15:1). Não há genealogia, não há cidade, não há um só milagre — há uma frase, e a frase governa 2 Crônicas inteiro: \"O Senhor está convosco, enquanto vós estais com ele, e, se o buscardes, o achareis; porém, se o deixardes, vos deixará\" (2Cr 15:2). O lugar em que ele a diz é o que a torna difícil de ouvir: o rei vem voltando de uma vitória esmagadora, carregado de despojo, e é justamente aí que o profeta o alcança. Para provar que a condição é séria, abre diante dele o retrato dos anos em que Israel viveu \"sem o verdadeiro Deus, e sem sacerdote que o ensinasse, e sem lei\" (2Cr 15:3) — os dias dos juízes, sem paz \"nem para o que saía, nem para o que entrava\" (2Cr 15:5) — e fecha com um imperativo, não com uma ameaça: \"Mas esforçai-vos, e não desfaleçam as vossas mãos; porque a vossa obra tem uma recompensa\" (2Cr 15:7). O efeito é imediato e é medido em atos: \"Ouvindo, pois, Asa estas palavras, e a profecia do profeta Odede, cobrou ânimo\" (2Cr 15:8)."
    },
    rebanho: {
      title: "Os setecentos bois e as sete mil ovelhas tirados do despojo de Zerá",
      subtitle: "2Cr 15:11 • o sacrifício do terceiro mês, pago inteiro com o que veio da batalha",
      text: "Este gado não nasceu nos currais de Judá: veio de Gerar, no rastro da derrota do etíope, quando \"feriram todas as cidades nos arredores de Gerar\" e \"Também feriram as malhadas do gado; e levaram ovelhas em abundância, e camelos, e voltaram para Jerusalém\" (2Cr 14:14-15). No dia do ajuntamento ele volta a sair pela porta, mas para cima do altar: \"E no mesmo dia ofereceram em sacrifício ao Senhor, do despojo que trouxeram, setecentos bois e sete mil ovelhas\" (2Cr 15:11). O detalhe teológico está em \"do despojo que trouxeram\" — a vitória tinha sido pedida de mãos vazias (\"em ti confiamos, e no teu nome viemos contra esta multidão\", 2Cr 14:11), e o lucro dela é devolvido a quem a deu. É o oposto exato do capítulo seguinte, em que a prata guardada na casa do SENHOR sai pela porta para comprar uma espada estrangeira (2Cr 16:2)."
    },
    rei: {
      title: "Asa, rei de Judá, no ano décimo do seu reinado",
      subtitle: "2Cr 15 • o rei que cobrou ânimo, renovou o altar e depôs a própria mãe",
      text: "Chega ao capítulo vindo do maior triunfo da sua vida e recebe uma condição, não um elogio: \"O Senhor está convosco, enquanto vós estais com ele\" (2Cr 15:2). E responde como poucos reis respondem a um profeta — com obras: \"cobrou ânimo e tirou as abominações de toda a terra, de Judá e de Benjamim, como também das cidades que tomara nas montanhas de Efraim, e renovou o altar do Senhor, que estava diante do pórtico do Senhor\" (2Cr 15:8). Renovar o altar diante do pórtico é confessar que o altar do templo de Salomão estava em ruína a menos de sessenta anos da dedicação. Convoca, sacrifica do despojo, entra na aliança e jura em alta voz (2Cr 15:9-14). E então faz o que quase nenhum rei tem estômago para fazer: depõe a própria mãe do posto de rainha e queima o ídolo dela junto ao Cedrom (2Cr 15:16). O cronista lhe dá o veredicto mais generoso possível, e no mesmo fôlego marca o limite: \"Os altos, porém, não foram tirados de Israel; contudo o coração de Asa foi perfeito todos os seus dias\" (2Cr 15:17). Este é o Asa que o capítulo seguinte vai desmentir na prática, sem apagar uma linha do que ele fez aqui."
    },
    servo: {
      title: "O sacerdote do sacrifício do despojo, o tocador de trombeta do juramento, os que despedaçaram o ídolo e os que carregaram a prata para o tesouro",
      subtitle: "2Cr 15 • as mãos que executam a reforma, do altar renovado ao ribeiro de Cedrom",
      text: "Uma reforma se faz com gente carregando coisa. São servos que tiram \"as abominações de toda a terra\" (2Cr 15:8) e que refazem a alvenaria do altar diante do pórtico; são sacerdotes que degolam e queimam os setecentos bois e as sete mil ovelhas do despojo num só dia (2Cr 15:11); são levitas com trombetas e buzinas nos cantos do átrio quando o povo jura \"em alta voz, com júbilo\" (2Cr 15:14). São servos que descem ao vale com o horrível ídolo de Aserá para o despedaçar e o queimar (2Cr 15:16) — trabalho sujo, feito à vista de todos, para que ninguém pudesse depois recolher os pedaços. E são servos que fecham o capítulo carregando o cofre para dentro: \"E trouxe, à casa de Deus, as coisas consagradas por seu pai, e as coisas que ele mesmo tinha consagrado: prata, ouro e vasos\" (2Cr 15:18). Vale a pena guardar a imagem: é esta mesma prata, entrando pela porta do tesouro em 15:18, que sairá dela em 16:2 para pagar a Ben-Hadade. Entre os que ouvem o oráculo na estrada está também o morador da terra perturbada, curvado — o Judá que vivera \"muitas perturbações sobre todos os habitantes daquelas terras\" (2Cr 15:5) e agora ouve que há recompensa para a obra."
    }
  },

  // ---------------------------------------------------------------- 2Cr 16
  16: {
    anciao: {
      title: "O ancião que guarda o arquivo de Judá e o velho do pranto de Asa",
      subtitle: "2Cr 16:11-14 • quem escreve o reinado no livro dos reis e quem acompanha o enterro",
      text: "Quarenta e um anos de reinado cabem numa remissão de arquivo: \"E eis que os atos de Asa, tanto os primeiros, como os últimos, estão escritos no livro dos reis de Judá e Israel\" (2Cr 16:11). O ancião que guarda esse rolo é o homem que viu tudo — o menino que subiu ao trono depois de Abias, os dez anos de terra em paz (2Cr 14:1), o milhão de Zerá desfeito em Maressa, o juramento do terceiro mês, a rainha-mãe deposta — e agora tem de registrar também a prata da casa do SENHOR indo para Damasco e o vidente na casa do tronco. No fim, os mesmos velhos estão à beira do sepulcro que o rei cavara para si na cidade de Davi, quando o sepultaram \"no seu sepulcro, que tinha cavado para si na cidade de Davi, havendo-o deitado na cama, que se enchera de perfumes e especiarias preparadas segundo a arte dos perfumistas; e, destas coisas fizeram-lhe uma grande queima\" (2Cr 16:14). Aquela queima é honra pública: o cronista faz questão de dizer, cinco capítulos adiante, que a Jeorão \"o seu povo não lhe queimou aroma como queimara a seus pais\" (2Cr 21:19). Judá enterrou Asa com todas as honras — e ainda assim não escondeu no arquivo os últimos cinco anos dele."
    },
    cavaleiro: {
      title: "Os capitães dos exércitos de Ben-Hadade e o cavaleiro etíope que Judá venceu de mãos vazias",
      subtitle: "2Cr 16 • a cavalaria comprada com prata e a cavalaria que Deus entregou de graça",
      text: "Os primeiros descem de Damasco por encomenda: \"E Ben-Hadade deu ouvidos ao rei Asa, e enviou os capitães dos seus exércitos, contra as cidades de Israel, e eles feriram a Ijom, a Dã, a Abel-Maim, e a todas as cidades-armazéns de Naftali\" (2Cr 16:4). São mercenários eficientes — Baasa larga a obra de Ramá no mesmo instante (2Cr 16:5) — e é justamente a eficiência que o profeta acusa: \"Porquanto confiaste no rei da Síria, e não confiaste no Senhor teu Deus, por isso o exército do rei da Síria escapou da tua mão\" (2Cr 16:7). O outro cavaleiro em cena vem da memória: os carros de Zerá, que Hanani põe diante dos olhos do rei para o envergonhar — \"Porventura não foram os etíopes e os líbios um grande exército, com muitíssimos carros e cavaleiros? Confiando tu, porém, no Senhor, ele os entregou nas tuas mãos\" (2Cr 16:8). Judá não tinha carro nenhum naquele dia (2Cr 14:8-12) e ganhou; agora tem cavalaria paga, ganha a partida e perde a mão que a Síria devia ter caído dentro."
    },
    homem: {
      title: "O vigia do muro de Ramá, os moradores de Abel-Maim, os oprimidos do povo e os médicos de Asa",
      subtitle: "2Cr 16 • quem viveu o cerco, quem pagou a guerra alheia e quem foi chamado à cabeceira do rei",
      text: "Ramá fica a uma hora de Jerusalém, na estrada do norte, e é ali que Baasa fecha a porta de Judá: sobe \"e edificou a Ramá, para não deixar ninguém sair, nem chegar a Asa, rei de Judá\" (2Cr 16:1) — o vigia daquele muro está murando um povo, não uma cidade. Os moradores que pagam a conta são de outra terra: Ijom, Dã e Abel-Maim, na fronteira norte de Israel, feridas pela cavalaria que a prata de Judá alugou (2Cr 16:4). Depois vêm os homens de Judá que carregam as pedras do muro inimigo para levantar Geba e Mizpá (2Cr 16:6) — os únicos do capítulo que saem com lucro. E vêm os dois grupos que o texto põe lado a lado no fim: os que apanham do rei — \"também Asa, no mesmo tempo, oprimiu a alguns do povo\" (2Cr 16:10) — e os que o assistem na cama: \"E, no ano trinta e nove do seu reinado, Asa caiu doente de seus pés, a sua doença era em extremo grave; contudo, na sua enfermidade, não buscou ao Senhor, mas antes os médicos\" (2Cr 16:12). O médico não é o vilão do versículo; o pecado é o \"mas antes\". Foi a mesma troca de 16:2 — ir buscar socorro onde se vê, e não onde se crê — agora feita dentro do próprio corpo."
    },
    patriarca: {
      title: "Hanani, o vidente, que entrou no pátio no dia da vitória comprada",
      subtitle: "2Cr 16:7-10 • o profeta que disse ao rei o preço do que ele tinha ganhado, e foi para a casa do tronco",
      text: "Chega no pior momento possível, que é o melhor: \"Naquele mesmo tempo veio Hanani, o vidente, a Asa, rei de Judá\" (2Cr 16:7) — o inimigo tinha recuado, a obra de Ramá estava desmanchada e as pedras já viravam Geba e Mizpá. Ele não acusa fracasso, acusa êxito: \"Porquanto confiaste no rei da Síria, e não confiaste no Senhor teu Deus, por isso o exército do rei da Síria escapou da tua mão\" (2Cr 16:7). Lembra o milhão de Zerá vencido de mãos vazias (2Cr 16:8) e diz a frase larga que ficou: \"Porque, quanto ao Senhor, seus olhos passam por toda a terra, para mostrar-se forte para com aqueles cujo coração é perfeito para com ele; nisto, pois, procedeste loucamente porque desde agora haverá guerras contra ti\" (2Cr 16:9) — Zacarias veria os mesmos olhos como sete lâmpadas percorrendo a terra (Zc 4:10). A resposta do rei que uma vez depusera a própria mãe por causa de um ídolo: \"Porém Asa se indignou contra o vidente, e lançou-o na casa do tronco; porque estava enfurecido contra ele, por causa disto\" (2Cr 16:10). Hanani não sai mais do texto. Mas sai da história: o filho dele, Jeú, estará à porta de Jerusalém três capítulos adiante, dizendo a verdade ao filho do rei que prendeu o seu pai (2Cr 19:2)."
    },
    rei: {
      title: "Asa de Judá, Baasa de Israel e Ben-Hadade da Síria, que habitava em Damasco",
      subtitle: "2Cr 16 • três tronos e uma aliança comprada com a prata do tesouro do templo",
      text: "Baasa abre o capítulo com um bloqueio: no trigésimo sexto ano de Asa \"subiu contra Judá e edificou a Ramá, para não deixar ninguém sair, nem chegar a Asa, rei de Judá\" (2Cr 16:1) — o mesmo Baasa a quem Jeú, filho de Hanani, já profetizara a ruína da casa (1Rs 16:1-4). Asa responde abrindo duas câmaras de uma vez: \"Então Asa tirou a prata e o ouro dos tesouros da casa do Senhor, e da casa do rei\" (2Cr 16:2). O terceiro trono é o de Damasco, e a proposta enviada é de uma franqueza constrangedora: \"Acordo há entre mim e ti, como houve entre meu pai e o teu; eis que te envio prata e ouro; vai, pois, e anula o teu acordo com Baasa, rei de Israel, para que se retire de sobre mim\" (2Cr 16:3) — Asa está comprando um aliado que já era comprado, e pede a ele a mesma deslealdade que um dia sofrerá. Ben-Hadade cumpre o combinado (2Cr 16:4), Baasa recua (2Cr 16:5), e a manobra funciona por completo. É a lição amarga do capítulo: dá para vencer sem Deus, e a conta chega em outro lugar — \"desde agora haverá guerras contra ti\" (2Cr 16:9)."
    },
    servo: {
      title: "Os servos enviados a Damasco, os pedreiros de Ramá, o escrivão dos atos de Asa e os perfumistas do sepultamento",
      subtitle: "2Cr 16 • quem carrega a prata para fora, quem carrega as pedras para dentro e quem prepara a cama de especiarias",
      text: "O capítulo inteiro se move nas costas de gente sem nome. Primeiro são os que levam o dinheiro: \"e enviou servos a Ben-Hadade, rei da Síria, que habitava em Damasco\" (2Cr 16:2) — carregam prata e ouro que tinham entrado na casa de Deus um capítulo antes (2Cr 15:18) e falam a proposta na cara do sírio (2Cr 16:3). Depois são os que trazem carga para casa: \"Então o rei Asa tomou a todo o Judá, e levaram as pedras de Ramá, e a sua madeira, com que Baasa edificara; e com elas edificou a Geba e a Mizpá\" (2Cr 16:6) — cada pedra do bloqueio vira fronteira de Judá. Há o carcereiro que fecha o tronco sobre o vidente (2Cr 16:10) e o servo do pátio que assiste a tudo calado. Há o escrivão que arquiva a vida do rei \"no livro dos reis de Judá e Israel\" (2Cr 16:11). E há, no último versículo, os artesãos do luto: o rei é posto \"na cama, que se enchera de perfumes e especiarias preparadas segundo a arte dos perfumistas; e, destas coisas fizeram-lhe uma grande queima\" (2Cr 16:14). Um reinado que começou buscando ao SENHOR termina cercado de especialistas — médicos à cabeceira, perfumistas no sepulcro — e nenhum profeta na sala, porque o único que veio está no tronco."
    }
  },

  // ---------------------------------------------------------------- 2Cr 17
  17: {
    anciao: {
      title: "Bene-Hail e Obadias, príncipes; Semaías, o levita; Elisama e Jeorão, os sacerdotes da comitiva que foi ensinar",
      subtitle: "2Cr 17:7-9 • a escola itinerante que Jeosafá mandou pelas cidades de Judá no terceiro ano",
      text: "É a coisa mais original que um rei de Judá fez, e o cronista dá os nomes um por um: \"E no terceiro ano do seu reinado enviou ele os seus príncipes, a Bene-Hail, a Obadias, a Zacarias, a Natanael e a Micaías, para ensinarem nas cidades de Judá\" (2Cr 17:7). Não vão cobrar tributo nem recrutar: vão dar aula. Com os cinco príncipes seguem nove levitas e dois sacerdotes, também nomeados — \"E com eles os levitas, Semaías, Netanias, Zebadias, Asael, Semiramote, Jônatas, Adonias, Tobias e Tobe-Adonias e, com estes levitas, os sacerdotes, Elisama e Jeorão\" (2Cr 17:8) —, e a autoridade da comitiva não está nos príncipes, está no que eles carregam: \"E ensinaram em Judá, levando consigo o livro da lei do Senhor; e foram a todas as cidades de Judá, ensinando entre o povo\" (2Cr 17:9). É a resposta exata ao diagnóstico que Azarias dera ao pai deste rei — Israel vivera \"sem sacerdote que o ensinasse, e sem lei\" (2Cr 15:3). Jeosafá manda sacerdote e manda lei. E o resultado registrado não é conquista, é dissuasão: \"E veio o temor do Senhor sobre todos os reinos das terras, que estavam ao redor de Judá, e não guerrearam contra Jeosafá\" (2Cr 17:10)."
    },
    cavaleiro: {
      title: "O cavaleiro da ala de Jozabade, dos cento e oitenta mil armados para a guerra",
      subtitle: "2Cr 17:18 • a última coluna da resenha, a que ficava pronta a sair a qualquer hora",
      text: "Fecha o rol dos chefes por casas paternas: \"E depois dele Jozabade, e com ele cento e oitenta mil, armados para a guerra\" (2Cr 17:18). A expressão distingue esta coluna das outras: Adna e Joanã têm \"homens valentes\", Eliada tem gente \"armados de arco e de escudo\" (2Cr 17:17), e a de Jozabade está armada para a guerra — equipada e engatada. Toda essa força, somada, passa de um milhão de homens, e o cronista a alinha no mesmo capítulo em que conta a comitiva que saiu com um rolo debaixo do braço, sem escolta. A ironia é do próprio texto: a segurança do reino não veio da resenha, veio do temor do SENHOR sobre os vizinhos (2Cr 17:10). E o rol termina lembrando que nem tudo estava ali: \"Estes estavam no serviço do rei; afora os que o rei tinha posto nas cidades fortes por todo o Judá\" (2Cr 17:19)."
    },
    homem: {
      title: "Os soldados das cidades fortificadas, os cinco príncipes que foram ensinar, os filisteus do tributo e os capitães do rol das casas paternas",
      subtitle: "2Cr 17 • a guarnição, a sala de aula na praça da aldeia e o campo da resenha fora da muralha",
      text: "O reinado começa com muros: \"E pôs soldados em todas as cidades fortificadas de Judá, e estabeleceu guarnições na terra de Judá, como também nas cidades de Efraim, que Asa seu pai tinha tomado\" (2Cr 17:2). Mas o homem que define o capítulo não é o da guarnição: é o príncipe que sai com um rolo — Bene-Hail, Obadias, Zacarias, Natanael e Micaías, mandados \"para ensinarem nas cidades de Judá\" (2Cr 17:7) — e o morador da aldeia que para o trabalho para ouvir a lei lida em voz alta na praça, porque foram \"a todas as cidades de Judá, ensinando entre o povo\" (2Cr 17:9). Depois vêm os estrangeiros que chegam sem espada: \"E alguns dentre os filisteus traziam presentes a Jeosafá, e prata como tributo\" (2Cr 17:11) — os mesmos filisteus que faziam guerra a Judá desde os juízes. E o capítulo fecha no campo da resenha, com os capitães nomeados um a um: \"o chefe Adna, e com ele trezentos mil homens valentes\" (2Cr 17:14), \"E depois dele o capitão Joanã, e com ele duzentos e oitenta mil\" (2Cr 17:15), \"E de Benjamim, Eliada, homem valente, e com ele duzentos mil, armados de arco e de escudo\" (2Cr 17:17) — Benjamim continua sendo a tribo do arco, como era nos dias de Aod e de Saul. E há um em toda a lista que o cronista não consegue apresentar sem elogiar: \"E depois Amasias, filho de Zicri, que voluntariamente se entregou ao Senhor, e com ele duzentos mil homens valentes\" (2Cr 17:16)."
    },
    mulherComum: {
      title: "A mulher da aldeia de Judá que parou para ouvir o livro da lei",
      subtitle: "2Cr 17:9 • quem estava no poço quando a comitiva do rei chegou com o rolo",
      text: "\"E ensinaram em Judá, levando consigo o livro da lei do Senhor; e foram a todas as cidades de Judá, ensinando entre o povo\" (2Cr 17:9). Em Israel, ensinar \"entre o povo\" quer dizer na praça, junto ao poço e à sombra, onde estão as mulheres e as crianças — a lei nunca foi só do átrio. Moisés mandara ler a lei diante de \"os homens e as mulheres, os meninos e os estrangeiros que estão dentro das tuas portas, para que ouçam e aprendam\" (Dt 31:12), e Neemias faria o mesmo depois do exílio, diante da congregação, \"tanto de homens como de mulheres, e todos os que podiam ouvir com entendimento\" (Ne 8:2). Esta mulher é a geração inteira que cresceu numa terra onde havia sacerdote que ensinasse — o contrário exato dos dias descritos por Azarias, quando Israel esteve \"sem sacerdote que o ensinasse, e sem lei\" (2Cr 15:3). É dela e dos filhos dela que sairá a congregação que, três capítulos adiante, estará em pé no pátio novo com as suas crianças e as suas mulheres (2Cr 20:13)."
    },
    pastor: {
      title: "O pastor dos primeiros caminhos de Davi e o árabe que trouxe o gado miúdo do tributo",
      subtitle: "2Cr 17:3, 11 • o campo de Belém que o cronista põe como medida do rei, e o deserto que paga em carneiros e bodes",
      text: "O veredicto sobre Jeosafá é dado por comparação com um menino de rebanho, não com um rei de palácio: \"E o Senhor era com Jeosafá; porque andou nos primeiros caminhos de Davi seu pai, e não buscou a Baalins\" (2Cr 17:3). Os primeiros caminhos de Davi são os de antes do trono — o campo de Belém, a funda, a harpa, os anos em que ele \"apascentava as ovelhas de seu pai\" (1Sm 17:34) e escrevia que o SENHOR era o seu pastor. Andar neles é medir o reinado pela juventude fiel, e não pelo poder acumulado. O outro pastor da cena chega do deserto trazendo tributo: \"também os árabes lhe trouxeram gado miúdo; sete mil e setecentos carneiros, e sete mil e setecentos bodes\" (2Cr 17:11). São nômades de fora da aliança, e trazem em rebanho o que os filisteus trazem em prata — o mesmo temor do SENHOR chegando por dois caminhos diferentes."
    },
    rebanho: {
      title: "O rebanho dos campos de Belém e os sete mil e setecentos carneiros e bodes dos árabes",
      subtitle: "2Cr 17:3, 11 • as ovelhas dos primeiros caminhos de Davi e o gado miúdo que veio do deserto sem guerra",
      text: "O primeiro rebanho está numa lembrança: Jeosafá \"andou nos primeiros caminhos de Davi seu pai\" (2Cr 17:3) — a vida de pastor em Belém, antes da unção e antes de Golias. O segundo é um número anotado com precisão de escriturário: \"também os árabes lhe trouxeram gado miúdo; sete mil e setecentos carneiros, e sete mil e setecentos bodes\" (2Cr 17:11). Quinze mil e quatrocentas cabeças entrando por conta própria pela fronteira sul, sem uma batalha para as trazer — o inverso do gado que Asa teve de tomar em Gerar no rastro de Zerá (2Cr 14:15). Este é o retrato de um reino em que a riqueza chega porque \"veio o temor do Senhor sobre todos os reinos das terras\" (2Cr 17:10), e não porque o exército saiu. Todo esse gado, aliás, é o que Acabe vai usar como isca no capítulo seguinte: \"e Acabe matou ovelhas e bois em abundância, para ele e para o povo que vinha com ele; e o persuadiu\" (2Cr 18:2)."
    },
    rei: {
      title: "Jeosafá, rei de Judá, e os reis das terras ao redor que não guerrearam contra ele",
      subtitle: "2Cr 17 • o rei que se fortificou e depois mandou ensinar, e os tronos vizinhos que ficaram quietos",
      text: "\"E Jeosafá, seu filho, reinou em seu lugar; e fortificou-se contra Israel\" (2Cr 17:1) — a primeira medida é militar, e não é a que o cronista celebra. O que ele celebra vem no versículo 3: \"E o Senhor era com Jeosafá; porque andou nos primeiros caminhos de Davi seu pai, e não buscou a Baalins\" (2Cr 17:3); e no 6: \"E exaltou-se o seu coração nos caminhos do Senhor e, ainda mais, tirou os altos e os bosques de Judá\" (2Cr 17:6) — o que o pai tinha deixado de pé (2Cr 15:17) este derruba. Depois vem a decisão que ninguém antes dele tomou: mandar príncipes, levitas e sacerdotes ensinarem com o livro da lei pelas cidades (2Cr 17:7-9). Os outros tronos aparecem no capítulo pelo que deixam de fazer: \"E veio o temor do Senhor sobre todos os reinos das terras, que estavam ao redor de Judá, e não guerrearam contra Jeosafá\" (2Cr 17:10). É um reinado que cresce sem combate — \"Cresceu, pois, Jeosafá grandemente em extremo e edificou fortalezas e cidades de provisões em Judá\" (2Cr 17:12) — e é essa prosperidade que abrirá a porta do erro seguinte: \"Tinha, pois, Jeosafá riquezas e glória em abundância, e aparentou-se com Acabe\" (2Cr 18:1)."
    },
    servo: {
      title: "Asael, o levita da comitiva; os mensageiros entre as guarnições, os escudeiros do campo da resenha e os servos das cidades de provisões",
      subtitle: "2Cr 17 • quem leva o rolo pela serra, quem guarda o celeiro e quem carrega as armas do rol",
      text: "A comitiva que sai a ensinar tem nomes de levitas, e o cronista os escreve como quem escreve uma escala de serviço: \"E com eles os levitas, Semaías, Netanias, Zebadias, Asael, Semiramote, Jônatas, Adonias, Tobias e Tobe-Adonias\" (2Cr 17:8). Nove homens carregando um rolo pesado pela serra de Judá, de aldeia em aldeia, sem escolta e sem tribuna — a autoridade deles cabe numa frase: \"levando consigo o livro da lei do Senhor\" (2Cr 17:9). Ao lado deles trabalham os servos da máquina do reino: os que fazem a ligação entre as guarnições postas \"em todas as cidades fortificadas de Judá\" e nas cidades de Efraim (2Cr 17:2); os que enchem e guardam os armazéns, porque o rei \"edificou fortalezas e cidades de provisões em Judá\" (2Cr 17:12); e os que carregam os presentes e a prata do tributo dos filisteus (2Cr 17:11) para dentro do tesouro. E, no fim, os escudeiros do campo da resenha, quando \"homens de guerra e valentes\" (2Cr 17:13) se ajuntam em Jerusalém: são eles que empilham as lanças, os arcos e os escudos das cinco colunas do rol, sem que uma só delas tenha de sair para a guerra neste capítulo."
    }
  },

  // ---------------------------------------------------------------- 2Cr 18
  18: {
    anciao: {
      title: "Um do exército celestial em pé à direita e à esquerda do trono",
      subtitle: "2Cr 18:18-21 • a corte do céu que Micaías viu deliberar sobre a morte de Acabe",
      text: "Não é figurante de palácio: é uma das figuras da sala do trono que o profeta abriu diante de dois reis assentados na porta de Samaria. \"Vi ao Senhor assentado no seu trono, e todo o exército celestial em pé à sua mão direita, e à sua esquerda\" (2Cr 18:18) — a mesma cena que Isaías veria com serafins (Is 6:1-3), que Daniel veria com milhares de milhares (Dn 7:10) e que Jó registra quando \"os filhos de Deus vieram apresentar-se perante o Senhor\" (Jó 1:6). Todos estão em pé; só um está assentado. E a corte delibera: \"Quem persuadirá a Acabe rei de Israel, para que suba, e caia em Ramote de Gileade? Um dizia desta maneira, e outro de outra\" (2Cr 18:19). O que a visão ensina é duro e é consolo ao mesmo tempo: a mentira que os quatrocentos estavam dizendo na praça já tinha sido pesada no céu, e a morte que Acabe procurava não ia acontecer fora do governo de Deus. Micaías conta tudo isso em voz alta, na cara do rei, sabendo o que lhe custaria — e custou-lhe uma bofetada e o cárcere (2Cr 18:23-26)."
    },
    anjo: {
      title: "O exército celestial à mão direita e à esquerda, e o espírito que se apresentou diante do SENHOR",
      subtitle: "2Cr 18:18-22 • a hoste em pé diante do trono e o que se ofereceu para ser espírito de mentira",
      text: "\"Vi ao Senhor assentado no seu trono, e todo o exército celestial em pé à sua mão direita, e à sua esquerda\" (2Cr 18:18): a visão é de Micaías, e nela Deus não é desenhado — o trono está em glória, e são as figuras luminosas ao redor dele que se movem. Da fila sai uma: \"Então saiu um espírito e se apresentou diante do Senhor, e disse: Eu o persuadirei. E o Senhor lhe disse: Com quê?\" (2Cr 18:20). A resposta é a frase mais assombrosa do capítulo: \"Eu sairei, e serei um espírito de mentira na boca de todos os seus profetas. E disse o Senhor: Tu o persuadirás, e ainda prevalecerás; sai, e faze-o assim\" (2Cr 18:21). O texto não faz de Deus o autor da mentira: faz da mentira o instrumento do juízo sobre um rei que já tinha escolhido só ouvir o que lhe agradava — \"eu o odeio, porque nunca profetiza de mim o que é bom\" (2Cr 18:7). Paulo descreve o mesmo mecanismo: aos que \"não receberam o amor da verdade para se salvarem\", Deus envia \"a operação do erro, para que creiam a mentira\" (2Ts 2:10-11). E a graça está em que a armadilha foi denunciada em voz alta antes de fechar: \"Agora, pois, eis que o Senhor pôs um espírito de mentira na boca destes teus profetas\" (2Cr 18:22). Acabe foi avisado, e subiu."
    },
    cavaleiro: {
      title: "Os capitães dos carros da Síria, que tinham ordem de não pelejar senão contra o rei de Israel",
      subtitle: "2Cr 18:30-32 • a cavalaria com um alvo só, que cercou o rei errado",
      text: "A ordem que receberam é a mais estreita já dada numa batalha antiga: \"Deu ordem, porém, o rei da Síria aos capitães dos carros que tinha, dizendo: Não pelejareis nem contra pequeno, nem contra grande; senão só contra o rei de Israel\" (2Cr 18:30). O plano da Síria e o plano de Acabe se anulam: um manda matar só o rei, o outro se disfarça e manda o hóspede vestido de rei (2Cr 18:29). Por isso os carros erram o alvo: \"Sucedeu que, vendo os capitães dos carros a Jeosafá, disseram: Este é o rei de Israel, e o cercaram para pelejar; porém Jeosafá clamou, e o Senhor o ajudou. E Deus os desviou dele\" (2Cr 18:31). Jeosafá não tinha estratégia nenhuma — tinha um grito, e é a única coisa que o texto lhe credita. \"Porque sucedeu que, vendo os capitães dos carros, que não era o rei de Israel, deixaram de segui-lo\" (2Cr 18:32). Toda a cavalaria da Síria buscou a noite inteira o homem que morreria naquele dia, e quem o achou não foi ela: foi uma flecha atirada sem mira."
    },
    homem: {
      title: "Os quatrocentos profetas de Acabe, Zedequias filho de Quenaaná com os chifres de ferro, e o homem que armou o arco e atirou a esmo",
      subtitle: "2Cr 18 • o coro que disse o que o rei queria ouvir e o soldado que não mirou em ninguém",
      text: "Primeiro é o coro: \"Então o rei de Israel reuniu os profetas, quatrocentos homens\" (2Cr 18:5), e a resposta vem sem uma voz destoante — \"Sobe; porque Deus a entregará na mão do rei\". Quatrocentos concordando é o primeiro sinal de que algo está errado, e Jeosafá o percebe: \"Não há ainda aqui algum profeta do Senhor, para que o consultemos?\" (2Cr 18:6). O porta-voz dos quatrocentos entende que palavra bonita rende mais com encenação: \"E Zedequias, filho de Quenaaná, fez para si uns chifres de ferro, e disse: Assim diz o Senhor: Com estes ferirás aos sírios, até de todo os consumires\" (2Cr 18:10) — usa a fórmula dos verdadeiros profetas e a imagem da bênção de José (Dt 33:17) para dizer exatamente o que o trono encomendou. Quando é contrariado, não argumenta: \"Então Zedequias, filho de Quenaaná, chegando-se, feriu a Micaías no queixo, e disse: Por que caminho passou de mim o Espírito do Senhor para falar a ti?\" (2Cr 18:23). No fim do capítulo entra o homem que decide tudo sem saber de nada: \"Então um homem armou o arco e atirou a esmo, e feriu o rei de Israel entre as junturas e a couraça\" (2Cr 18:33) — um arqueiro anônimo, uma flecha sem alvo e a única brecha de uma armadura. Os quatrocentos tinham prometido triunfo; a palavra que se cumpriu foi a do homem que estava no cárcere a pão e água."
    },
    patriarca: {
      title: "Micaías, filho de Inlá — o profeta que o rei odiava por dizer a verdade",
      subtitle: "2Cr 18:6-27 • o único que contradisse quatrocentos, e foi para a casa do cárcere a pão de angústia",
      text: "É apresentado pelo próprio rei que o manda chamar, e a apresentação é uma confissão sem querer: \"Ainda há um homem por quem podemos consultar ao Senhor; porém eu o odeio, porque nunca profetiza de mim o que é bom, senão sempre o mal; este é Micaías, filho de Inlá\" (2Cr 18:7). O critério de Acabe para um profeta não é ser verdadeiro, é ser agradável. No caminho, o oficial tenta comprá-lo com um conselho amigável — \"seja, pois, também a tua palavra como a de um deles, e fala o que é bom\" (2Cr 18:12) — e recebe a única regra do ofício, dita num beco sem plateia: \"Vive o Senhor, que o que meu Deus me disser, isso falarei\" (2Cr 18:13). Diante do trono começa com ironia, repetindo palavra por palavra o coro dos quatrocentos (2Cr 18:14), e depois abre as duas visões: \"Vi a todo o Israel disperso pelos montes, como ovelhas que não têm pastor\" (2Cr 18:16) — imagem que Jesus retomaria ao ver as multidões (Mt 9:36) — e a sala do trono do céu com o espírito de mentira (2Cr 18:18-22). Leva uma bofetada no queixo, e a ordem do rei é ração e endereço: \"Colocai este homem na casa do cárcere; e sustentai-o com pão de angústia, e com água de angústia, até que eu volte em paz\" (2Cr 18:26). Da porta do cárcere ele aposta a própria vida na palavra que falou: \"Se voltares em paz, o Senhor não tem falado por mim. Disse mais: Ouvi, povos todos!\" (2Cr 18:27)."
    },
    rebanho: {
      title: "As ovelhas e os bois abatidos no banquete de Samaria — e todo o Israel disperso como ovelhas sem pastor",
      subtitle: "2Cr 18:2, 16 • o gado da persuasão e o rebanho da visão, no mesmo capítulo",
      text: "O mesmo animal aparece duas vezes, e nas duas ele é a chave da cena. Na primeira, é banquete: \"E depois de alguns anos desceu ele para Acabe em Samaria; e Acabe matou ovelhas e bois em abundância, para ele e para o povo que vinha com ele; e o persuadiu a subir com ele a Ramote de Gileade\" (2Cr 18:2). A persuasão deste capítulo inteiro começa numa mesa farta — não houve ameaça, houve hospitalidade. Na segunda, é juízo: \"Vi a todo o Israel disperso pelos montes, como ovelhas que não têm pastor\" (2Cr 18:16), e o profeta explica a imagem no mesmo fôlego: sem senhor, cada um voltando em paz para sua casa. O pastor que falta é o rei, e o rei ainda está vivo, assentado no trono, ouvindo. Israel tem quatrocentos profetas e um exército, e não tem pastor. É a mesma dor que Moisés levou a Deus ao pedir sucessor, \"para que a congregação do Senhor não seja como ovelhas que não têm pastor\" (Nm 27:17), e que Ezequiel diria dos pastores que apascentam a si mesmos (Ez 34:5)."
    },
    rei: {
      title: "Acabe de Israel, Jeosafá de Judá e o rei da Síria diante de Ramote de Gileade",
      subtitle: "2Cr 18 • dois tronos lado a lado na porta de Samaria e um terceiro do outro lado do vale",
      text: "O capítulo começa com uma frase que estraga tudo o que o anterior tinha construído: \"Tinha, pois, Jeosafá riquezas e glória em abundância, e aparentou-se com Acabe\" (2Cr 18:1) — o rei que mandou ensinar a lei liga a sua casa à casa que Elias enfrentou, e o preço disso será Atalia, dentro do palácio de Judá, dois reinados adiante. À mesa de Samaria ele empenha tudo: \"Como tu és, serei eu; e o meu povo, como o teu povo; iremos contigo à guerra\" (2Cr 18:3) — e só depois se lembra de perguntar: \"Peço-te, consulta hoje a palavra do Senhor\" (2Cr 18:4). O retrato oficial da cena é dos dois juntos: \"E o rei de Israel, e Jeosafá, rei de Judá, estavam assentados cada um no seu trono, vestidos com suas roupas reais, e estavam assentados na praça à entrada da porta de Samaria\" (2Cr 18:9). Acabe ouve a sentença e responde com um disfarce: \"Disfarçando-me eu, então entrarei na peleja; tu, porém, veste as tuas roupas reais\" (2Cr 18:29) — deixa o aliado com o alvo nas costas. Não adianta: uma flecha atirada a esmo encontra a fresta, e \"o rei de Israel susteve-se em pé no carro defronte dos sírios até à tarde; e morreu ao tempo do pôr do sol\" (2Cr 18:34). Ninguém se esconde de uma palavra que Deus falou."
    },
    servo: {
      title: "O oficial que foi chamar Micaías, o guarda do cárcere de Samaria, o servo que disfarçou o rei e o carreteiro de Acabe",
      subtitle: "2Cr 18 • os que executam ordens dos dois lados da verdade",
      text: "O primeiro é mandado correndo: \"Então o rei de Israel chamou um oficial, e disse: Traze aqui depressa a Micaías, filho de Inlá\" (2Cr 18:8). No caminho de volta, esse mesmo homem tenta poupar o profeta e a si próprio com um conselho de bom senso: \"Eis que as palavras dos profetas, a uma voz, predizem coisas boas para o rei; seja, pois, também a tua palavra como a de um deles, e fala o que é bom\" (2Cr 18:12) — é a tentação mais comum de todas, e vem embrulhada em gentileza. Depois é a vez do carcereiro: recebe o preso e a ração, \"pão de angústia\" e \"água de angústia\" (2Cr 18:26), e tem de ouvir da porta o grito do homem que ele tranca: \"Ouvi, povos todos!\" (2Cr 18:27). No campo, são servos que tiram do rei o manto e a coroa para o disfarce (2Cr 18:29), e é um servo que fica com a última ordem da vida de Acabe, dada com a flecha ainda cravada: \"então disse ao carreteiro: Dá volta, e tira-me do exército, porque estou gravemente ferido\" (2Cr 18:33). O carreteiro não dá a volta — ou o rei muda de ideia —, e é ele quem segura o rei em pé no carro a tarde inteira, defronte dos sírios, até o pôr do sol (2Cr 18:34)."
    }
  },

  // ---------------------------------------------------------------- 2Cr 19
  19: {
    anciao: {
      title: "Os juízes postos de cidade em cidade, e Amarias, o sumo sacerdote, com os levitas e chefes dos pais em Jerusalém",
      subtitle: "2Cr 19:5-11 • o tribunal que Jeosafá montou em Judá e a instrução que o governa",
      text: "A resposta do rei à repreensão de Jeú não é uma desculpa: é uma reforma judicial. \"E estabeleceu juízes na terra, em todas as cidades fortificadas, de cidade em cidade\" (2Cr 19:5) — em Israel o tribunal era a porta da cidade, e a Lei já mandava pôr juízes: \"Juízes e oficiais porás em todas as tuas cidades\" (Dt 16:18). A instrução que ele lhes dá é a frase que fez tribunal em Judá: \"Vede o que fazeis; porque não julgais da parte do homem, senão da parte do Senhor, e ele está convosco quando julgardes\" (2Cr 19:6). E a regra de conduta vem em três negativas que descrevem o próprio Deus: \"porque não há no Senhor nosso Deus iniqüidade nem acepção de pessoas, nem aceitação de suborno\" (2Cr 19:7). Em Jerusalém monta a instância superior, com competência repartida: \"E também estabeleceu Jeosafá a alguns dos levitas e dos sacerdotes e dos chefes dos pais de Israel sobre o juízo do Senhor, e sobre as causas judiciais\" (2Cr 19:8). No topo, dois homens e duas jurisdições: \"E eis que Amarias, o sumo sacerdote, presidirá sobre vós em todo o negócio do Senhor; e Zebadias, filho de Ismael, líder da casa de Judá, em todo o negócio do rei\" (2Cr 19:11). A sentença final do capítulo é uma bênção condicional e sóbria: \"esforçai-vos, pois, e fazei-o; e o Senhor será com os bons\"."
    },
    homem: {
      title: "O morador de Jerusalém que viu o rei voltar vivo, os litigantes do portão e Zebadias, filho de Ismael, sobre o negócio do rei",
      subtitle: "2Cr 19 • quem esperava um enterro e viu uma reforma, e quem levou a sua causa ao novo tribunal",
      text: "Judá tinha mandado o seu rei para uma guerra que não era sua, ao lado de um aliado que morreu no carro. Por isso o primeiro versículo é notícia: \"E Jeosafá, rei de Judá, voltou em paz à sua casa em Jerusalém\" (2Cr 19:1). Quem estava no portão viu chegar sem arranhão o homem que os capitães dos carros tinham cercado por engano — e viu também o profeta plantado à porta para o repreender (2Cr 19:2). Os homens seguintes do capítulo são o povo que ele foi procurar de novo: \"tornou a passar pelo povo desde Berseba até as montanhas de Efraim, e fez com que tornassem ao Senhor Deus de seus pais\" (2Cr 19:4) — de ponta a ponta do reino, do poço do Neguebe à serra do norte, o rei em pessoa. Depois vêm os que usam o tribunal novo: os irmãos que trazem \"toda a diferença que vier a vós de vossos irmãos que habitam nas suas cidades, entre sangue e sangue, entre lei e mandamento, entre estatutos e juízos\" (2Cr 19:10), e o litigante que aparece com o presente na mão e encontra pela frente a regra escrita na parede: nem \"acepção de pessoas, nem aceitação de suborno\" (2Cr 19:7). E há Zebadias, filho de Ismael, líder da casa de Judá, posto \"em todo o negócio do rei\" (2Cr 19:11) — a autoridade civil separada da autoridade sacerdotal, dentro do mesmo tribunal."
    },
    mulherComum: {
      title: "A mulher de Efraim que tornou ao SENHOR quando o rei tornou a passar pelo povo",
      subtitle: "2Cr 19:4 • a segunda volta de Jeosafá, de Berseba até as montanhas de Efraim",
      text: "\"Habitou, pois, Jeosafá em Jerusalém; e tornou a passar pelo povo desde Berseba até as montanhas de Efraim, e fez com que tornassem ao Senhor Deus de seus pais\" (2Cr 19:4). O verbo é \"tornou\": ele já tinha feito isso uma vez, mandando os príncipes e os levitas com o livro da lei a todas as cidades de Judá (2Cr 17:7-9); agora vai ele mesmo, e vai mais longe — as montanhas de Efraim ficam em território que era do reino do norte, cidades que Asa tomara (2Cr 17:2). Esta mulher está na ponta norte dessa caminhada, na serra onde os altos e os bosques tinham sido o culto normal por gerações. É gente como ela que constitui, um capítulo adiante, a congregação em pé no pátio novo com \"as suas crianças, as suas mulheres, e os seus filhos\" (2Cr 20:13). E é o retrato mais preciso do arrependimento de um rei: o homem que tinha ido a Samaria banquetear com Acabe percorre agora o reino inteiro a pé, fazendo o caminho de volta que ele mesmo tinha errado."
    },
    pastor: {
      title: "O pastor das montanhas de Efraim, na clareira onde os bosques foram cortados",
      subtitle: "2Cr 19:3-4 • a prova material do elogio que Jeú achou no rei",
      text: "A repreensão de Jeú não é só ira, e o profeta faz questão de dizer o que achou de bom, apontando para uma paisagem: \"Boas coisas contudo se acharam em ti; porque tiraste os bosques da terra, e preparaste o teu coração para buscar a Deus\" (2Cr 19:3). Os bosques são as aserás, os postes sagrados plantados nos altos, e derrubá-los era mexer com o culto que dava chuva, gado e colheita na cabeça do povo — coisa que o pai dele não completou (2Cr 15:17) e que ele fez: \"tirou os altos e os bosques de Judá\" (2Cr 17:6). O pastor que apascenta na clareira aberta pelo machado é quem vive a consequência prática da reforma: o mesmo monte, o mesmo rebanho, e nenhum poste em pé para onde levar a primeira cria. É nessa serra que o rei em pessoa aparece pouco depois, quando \"tornou a passar pelo povo desde Berseba até as montanhas de Efraim\" (2Cr 19:4)."
    },
    patriarca: {
      title: "Jeú, filho de Hanani, o vidente, à porta da casa do rei",
      subtitle: "2Cr 19:2-3 • o filho do profeta que Asa prendeu, repreendendo o filho de Asa",
      text: "A cena tem uma justiça poética que o cronista não explica e não precisa: \"E Jeú, filho de Hanani, o vidente, saiu ao encontro do rei Jeosafá\" (2Cr 19:2). Hanani foi o vidente que o pai deste rei mandou lançar na casa do tronco por dizer a verdade (2Cr 16:7-10); o filho de Hanani está agora à porta de casa do filho de Asa, com a mesma coragem e o mesmo ofício, e sem nenhuma vingança na boca. A repreensão é uma pergunta: \"Devias tu ajudar ao ímpio, e amar aqueles que odeiam ao Senhor? Por isso virá sobre ti grande ira da parte do Senhor\" (2Cr 19:2) — o rei tinha voltado vivo, mas voltar vivo não era absolvição. E logo em seguida vem o que quase nenhum oráculo de juízo traz: \"Boas coisas contudo se acharam em ti; porque tiraste os bosques da terra, e preparaste o teu coração para buscar a Deus\" (2Cr 19:3). Este Jeú é o mesmo que profetizou contra a casa de Baasa uma geração antes (1Rs 16:1-4) e, no fim do reinado, é o mesmo cujas anotações guardarão a história de Jeosafá: os atos do rei estão escritos \"nas notas de Jeú, filho de Hanani, que as inseriu no livro dos reis de Israel\" (2Cr 20:34). Quem o repreendeu acabou sendo quem o registrou."
    },
    rei: {
      title: "Jeosafá, rei de Judá, de volta em paz à sua casa em Jerusalém",
      subtitle: "2Cr 19 • o rei repreendido à porta que responde percorrendo o reino e pondo juízes",
      text: "\"E Jeosafá, rei de Judá, voltou em paz à sua casa em Jerusalém\" (2Cr 19:1) — vivo por causa de um grito no meio dos carros da Síria (2Cr 18:31), e recebido em casa por um profeta com uma pergunta atravessada: \"Devias tu ajudar ao ímpio, e amar aqueles que odeiam ao Senhor?\" (2Cr 19:2). O que ele faz com a repreensão é o que faz dele um dos poucos reis bons do livro: não prende o vidente como o pai fez, não se justifica, e sai de casa. \"tornou a passar pelo povo desde Berseba até as montanhas de Efraim, e fez com que tornassem ao Senhor Deus de seus pais\" (2Cr 19:4). Depois institucionaliza o que aprendeu, pondo juízes de cidade em cidade e dizendo-lhes de quem é o tribunal: \"não julgais da parte do homem, senão da parte do Senhor, e ele está convosco quando julgardes\" (2Cr 19:6). Em Jerusalém reparte a autoridade entre o sumo sacerdote e o líder da casa de Judá (2Cr 19:11), e deixa como última palavra do capítulo o encargo com que despediu os juízes: \"Assim fazei no temor do Senhor, com fidelidade, e com coração íntegro\" (2Cr 19:9)."
    },
    servo: {
      title: "Os oficiais levitas que estavam perante os juízes, o servo que recebeu o rei no portão e os que derrubaram os bosques",
      subtitle: "2Cr 19 • quem faz a máquina do tribunal andar e quem cortou os postes da terra",
      text: "O tribunal de Jeosafá não é um homem sentado: é uma estrutura, e o próprio texto lista o pessoal de apoio no mesmo fôlego dos juízes — \"também os oficiais, os levitas, estão perante vós; esforçai-vos, pois, e fazei-o; e o Senhor será com os bons\" (2Cr 19:11). São eles que recebem a causa na porta, que chamam as partes, que guardam os dois rolos abertos — a lei e o mandamento — e que levam a Jerusalém o que a cidade pequena não consegue julgar (2Cr 19:8, 10). O encargo que ouvem é o mesmo dos juízes: \"Assim fazei no temor do Senhor, com fidelidade, e com coração íntegro\" (2Cr 19:9). Antes deles, no começo do capítulo, estão os servos do portão que veem o carro do rei entrar sem um arranhão (2Cr 19:1) e ficam calados enquanto o vidente fala. E há os que empunharam o machado na serra, porque a única coisa que o profeta elogiou tinha sido feita por mãos assim: \"porque tiraste os bosques da terra\" (2Cr 19:3) — a prova material de um coração preparado para buscar a Deus não estava num discurso, estava numa clareira."
    }
  },

  // ---------------------------------------------------------------- 2Cr 20
  20: {
    anciao: {
      title: "Os anciãos vindos de todas as cidades de Judá, os que deram nome ao vale de Beraca e os velhos da casa de Jeosafá",
      subtitle: "2Cr 20 • os cabeças de casa que subiram ao jejum, saíram a Tecoa e voltaram bendizendo",
      text: "O jejum apregoado pelo rei esvazia as aldeias e enche Jerusalém: \"E Judá se ajuntou, para pedir socorro ao Senhor; também de todas as cidades de Judá vieram para buscar ao Senhor\" (2Cr 20:4). Estes anciãos são os que fecharam a banca e trancaram a casa para vir; estão em pé no pátio quando o rei diz \"em nós não há força perante esta grande multidão que vem contra nós, e não sabemos o que faremos; porém os nossos olhos estão postos em ti\" (2Cr 20:12), e se lançam por terra com ele quando a palavra chega (2Cr 20:18). São também os que, ao quarto dia, dão nome a um lugar: \"E ao quarto dia se ajuntaram no vale de Beraca; pois ali louvaram ao Senhor. Por isso chamaram aquele lugar o vale de Beraca, até ao dia de hoje\" (2Cr 20:26) — Beraca quer dizer bênção, e o nome ficou como marco de estrada para as gerações que não estiveram lá. No fim do reinado, são os velhos da casa que veem o mesmo rei repetir o erro do meio da vida: \"Jeosafá, rei de Judá, se aliou com Acazias, rei de Israel, que procedeu com toda a impiedade\" (2Cr 20:35)."
    },
    cavaleiro: {
      title: "O chefe dos filhos de Moabe, na vanguarda que subiu de além do mar",
      subtitle: "2Cr 20:1-2, 22-23 • o comandante da invasão que se destruiu a si mesma",
      text: "\"E sucedeu que, depois disto, os filhos de Moabe, e os filhos de Amom, e com eles outros dos amonitas, vieram à peleja contra Jeosafá\" (2Cr 20:1). O aviso que chega ao rei traz a medida do problema e a distância: \"Vem contra ti uma grande multidão dalém do mar e da Síria; e eis que já estão em Hazazom-Tamar, que é En-Gedi\" (2Cr 20:2) — En-Gedi fica a dois dias de Jerusalém, subindo do mar Salgado; a vanguarda já estava dentro de casa. Moabe e Amom são parentes de Israel, filhos de Ló (Gn 19:36-38), e o rei lembra isso na oração: são justamente aqueles \"pelos quais não permitiste passar a Israel, quando vinham da terra do Egito, mas deles se desviaram e não os destruíram\" (2Cr 20:10). O fim deste chefe não vem por espada de Judá: \"Porque os filhos de Amom e de Moabe se levantaram contra os moradores das montanhas de Seir, para os destruir e exterminar; e, acabando eles com os moradores de Seir, ajudaram uns aos outros a destruir-se\" (2Cr 20:23). A coligação virou a própria emboscada."
    },
    homem: {
      title: "Os avisadores que chegaram ofegantes, os homens de Judá em jejum, os cantores diante dos armados e os corpos mortos da atalaia do deserto",
      subtitle: "2Cr 20 • quem trouxe a notícia, quem jejuou, quem cantou na primeira fila e quem não escapou",
      text: "Primeiro chegam os que trazem a má notícia com a distância medida: \"Então vieram alguns que avisaram a Jeosafá, dizendo: Vem contra ti uma grande multidão dalém do mar e da Síria; e eis que já estão em Hazazom-Tamar, que é En-Gedi\" (2Cr 20:2). Depois é o homem comum de Judá que fecha a oficina, porque o rei \"apregoou jejum em todo o Judá\" (2Cr 20:3), e sobe à casa do SENHOR sem arma na mão. Está em pé no pátio novo com a família — \"E todo o Judá estava em pé perante o Senhor, como também as suas crianças, as suas mulheres, e os seus filhos\" (2Cr 20:13) — e ouve, do meio da própria fila, a palavra que desmonta a batalha: \"a peleja não é vossa, mas de Deus\" (2Cr 20:15) e \"postai-vos, ficai parados, e vede a salvação do Senhor\" (2Cr 20:17). De manhã cedo sai ao deserto de Tecoa, e é aí que aparece o homem mais estranho do quadro: o cantor na primeira fila. \"E aconselhou-se com o povo, e ordenou cantores para o Senhor, que louvassem à Majestade santa, saindo diante dos armados, e dizendo: Louvai ao Senhor porque a sua benignidade dura para sempre\" (2Cr 20:21) — harpa à frente das lanças, coisa que nenhum comandante do mundo antigo faria. O gatilho é exatamente o canto: \"E, quando começaram a cantar e a dar louvores, o Senhor pôs emboscadas\" (2Cr 20:22). E, do alto da atalaia, o armado de Judá olha para baixo e vê o que lhe restou fazer: \"e eis que eram corpos mortos, que jaziam em terra, e nenhum escapou\" (2Cr 20:24)."
    },
    mulherComum: {
      title: "As mulheres que estavam em pé no pátio novo com as suas crianças — e Azuba, filha de Sili, mãe do rei",
      subtitle: "2Cr 20:13, 31 • a família inteira de Judá dentro da oração de guerra, e a mãe registrada no resumo do reinado",
      text: "O cronista podia ter escrito que o povo se ajuntou e pronto. Em vez disso ele conta quem estava lá: \"E todo o Judá estava em pé perante o Senhor, como também as suas crianças, as suas mulheres, e os seus filhos\" (2Cr 20:13). Não é uma assembleia de homens de guerra: é o reino inteiro, de colo a cajado, em pé diante de um Deus a quem o rei acabara de dizer \"não sabemos o que faremos\" (2Cr 20:12). Estas mulheres ouvem Jaaziel dizer que a peleja não é delas, prostram-se com o rosto em terra junto com todo o Judá (2Cr 20:18) e ficam em Jerusalém enquanto os cantores saem na frente do exército. É a mesma cena da dedicação do templo e a mesma da leitura da lei em Neemias: em Israel, a promessa é lida diante de \"os homens e as mulheres, os meninos\" (Dt 31:12). A outra mulher do capítulo está no resumo do reinado, e é nomeada como se nomeia uma rainha: \"era da idade de trinta e cinco anos quando começou a reinar e vinte e cinco anos reinou em Jerusalém; e o nome de sua mãe era Azuba, filha de Sili\" (2Cr 20:31). O cronista registra a mãe de cada rei de Judá — e depois do que Maaca fez em 2Cr 15:16 e do que Atalia faria em 2Cr 22:10, sabe-se por que esse nome importa."
    },
    multidao: {
      title: "Os levitas coatitas e coratitas que louvaram com voz muito alta, e o povo que bendisse no vale de Beraca",
      subtitle: "2Cr 20:19, 26-28 • o coro que se levantou do chão e a procissão que voltou a Jerusalém com harpas e trombetas",
      text: "Levantam-se do lugar exato onde todos estavam prostrados: \"E levantaram-se os levitas, dos filhos dos coatitas, e dos filhos dos coratitas, para louvarem ao Senhor Deus de Israel, com voz muito alta\" (2Cr 20:19) — os coatitas eram a casa que carregava a arca aos ombros (Nm 4:15) e os coratitas, os cantores cujos nomes encabeçam salmos inteiros (Sl 42; 44—49). Louvar antes de ver é a marca desta congregação. Ao quarto dia depois da batalha ela se ajunta de novo, agora num vale: \"pois ali louvaram ao Senhor. Por isso chamaram aquele lugar o vale de Beraca, até ao dia de hoje\" (2Cr 20:26). E a volta é uma procissão, com o rei abrindo o caminho: \"Então voltaram todos os homens de Judá e de Jerusalém, e Jeosafá à frente deles, e tornaram a Jerusalém com alegria; porque o Senhor os alegrara sobre os seus inimigos\" (2Cr 20:27), \"E vieram a Jerusalém com saltérios, com harpas e com trombetas, para a casa do Senhor\" (2Cr 20:28). Saíram para uma batalha e voltaram de um culto: entram pela mesma porta por onde tinham saído cantando, e vão direto ao templo, que é de onde a coisa toda partiu."
    },
    patriarca: {
      title: "Jaaziel, o levita dos filhos de Asafe; Jeú, filho de Hanani; e Eliezer, filho de Dodava, de Maressa",
      subtitle: "2Cr 20 • o que falou no meio da congregação, o que escreveu as notas do reinado e o que anunciou o naufrágio",
      text: "O primeiro não é sacerdote nem está no santuário: está na fila. \"Então veio o Espírito do Senhor, no meio da congregação, sobre Jaaziel, filho de Zacarias, filho de Benaia, filho de Jeiel, filho de Matanias, levita, dos filhos de Asafe\" (2Cr 20:14) — quatro gerações de credencial para um homem que aparece uma vez na Bíblia, e o Espírito não desce sobre o rei que orava, desce sobre um cantor no meio do povo. O que ele diz vira doutrina de guerra em Israel: \"Não temais, nem vos assusteis por causa desta grande multidão; pois a peleja não é vossa, mas de Deus\" (2Cr 20:15), e a ordem de batalha mais estranha da Escritura: \"Nesta batalha não tereis que pelejar; postai-vos, ficai parados, e vede a salvação do Senhor para convosco\" (2Cr 20:17) — o eco do que Moisés dissera à beira do mar (Êx 14:13-14). O segundo profeta do capítulo aparece como historiador: os atos do rei estão escritos \"nas notas de Jeú, filho de Hanani, que as inseriu no livro dos reis de Israel\" (2Cr 20:34). E o terceiro fecha os seis capítulos como o primeiro os abriu, com um profeta atravessando a cena: \"Porém Eliezer, filho de Dodava, de Maressa, profetizou contra Jeosafá, dizendo: Porquanto te aliaste com Acazias, o Senhor despedaçou as tuas obras. E os navios se quebraram, e não puderam ir a Társis\" (2Cr 20:37)."
    },
    rei: {
      title: "Jeosafá de Judá, Acazias de Israel e os reis das terras sobre quem veio o temor de Deus",
      subtitle: "2Cr 20 • o rei que temeu e apregoou jejum, o aliado ímpio do fim do reinado e os tronos que ficaram quietos",
      text: "O capítulo não esconde o medo do rei, e é justamente por isso que ele é grande: \"Então Jeosafá temeu, e pôs-se a buscar o Senhor, e apregoou jejum em todo o Judá\" (2Cr 20:3). Em pé na congregação, diante do pátio novo, ele faz a oração mais desarmada de um rei na Escritura — recorda a promessa da dedicação do templo (2Cr 20:9), lembra a Deus a escritura da terra dada \"para sempre à descendência de Abraão, teu amigo\" (2Cr 20:7) e termina sem plano nenhum: \"Porque em nós não há força perante esta grande multidão que vem contra nós, e não sabemos o que faremos; porém os nossos olhos estão postos em ti\" (2Cr 20:12). De manhã prega antes de marchar: \"Crede no Senhor vosso Deus, e estareis seguros; crede nos seus profetas, e prosperareis\" (2Cr 20:20). Depois da vitória, os tronos vizinhos se calam — \"E veio o temor de Deus sobre todos os reinos daquelas terras, ouvindo eles que o Senhor havia pelejado contra os inimigos de Israel\" (2Cr 20:29) — e o reino descansa: \"E o reino de Jeosafá ficou quieto; e o seu Deus lhe deu repouso ao redor\" (2Cr 20:30). O fim, porém, repete o erro do meio: o mesmo homem que se aparentou com Acabe se alia agora com o filho dele, \"Acazias, rei de Israel, que procedeu com toda a impiedade\" (2Cr 20:35), e a sociedade acaba em madeira quebrada na praia de Eziom-Geber (2Cr 20:36-37)."
    },
    servo: {
      title: "O levita do pátio novo, as crianças em pé perante o SENHOR, os tangedores da volta a Jerusalém e os carpinteiros do estaleiro de Eziom-Geber",
      subtitle: "2Cr 20 • quem serve na casa, quem carrega o despojo de três dias e quem construiu os navios que se quebraram",
      text: "O pátio novo é o átrio exterior acrescentado ao templo de Salomão, e é ali, e não dentro do santuário, que a nação inteira cabe: \"E pôs-se Jeosafá em pé na congregação de Judá e de Jerusalém, na casa do Senhor, diante do pátio novo\" (2Cr 20:5). Os levitas de serviço naquele dia veem uma coisa que não estava na escala — o Espírito do SENHOR descendo sobre um dos seus, no meio da congregação (2Cr 20:14). Ao lado deles, o cronista faz questão de pôr os pequenos: \"como também as suas crianças, as suas mulheres, e os seus filhos\" (2Cr 20:13); é a única cena de guerra da Escritura em que as crianças estão em pé na formatura. Depois da batalha vêm os que trabalham três dias sem parar: \"e tomaram para si tanto, que não podiam levar; e três dias saquearam o despojo, porque era muito\" (2Cr 20:25). E na entrada da cidade, os que tocam: \"E vieram a Jerusalém com saltérios, com harpas e com trombetas, para a casa do Senhor\" (2Cr 20:28). O último servo destes seis capítulos está longe de tudo isso, na praia do golfo de Ácaba, montando cascos para uma sociedade que Deus não abençoou: \"E aliou-se com ele, para fazerem navios que fossem a Társis; e fizeram os navios em Eziom-Geber\" (2Cr 20:36) — e ali ficaram, porque \"os navios se quebraram, e não puderam ir a Társis\" (2Cr 20:37)."
    }
  }
};
