// Fichas ESPECÍFICAS por (capítulo → papel) de 2 CRÔNICAS 32–36.
// Os cinco capítulos do fim do livro e do fim do reino. Em 32, Senaqueribe
// acampa contra as cidades fortificadas e Ezequias responde com pedreiro e
// cal — tapa as fontes de fora, edifica o muro quebrado até às torres, faz
// armas e escudos em abundância e fala ao coração do povo na praça da porta;
// depois vêm os arautos gritando EM JUDAICO contra a gente que estava em cima
// do muro, e o anjo que ceifa o arraial numa noite. Em 33, Manassés reedifica
// os altos, enche os dois átrios da casa de altares ao exército dos céus,
// passa os filhos pelo fogo em Hinom — e volta de Babilônia com ganchos na
// carne e a boca aprendida em oração. Em 34, um menino de oito anos vira rei,
// aos vinte manda derrubar os altares perante ele e moer as imagens em pó, e
// aos vinte e seis acha um livro dentro da casa que estava consertando. Em 35,
// a arca pousa e os levitas largam a carga dos ombros para a maior páscoa
// desde Samuel — e o mesmo rei morre no vale de Megido, no segundo carro. Em
// 36, quatro reis em vinte versículos, os mensageiros escarnecidos até que
// "mais nenhum remédio houve", a casa queimada, os muros derribados, a terra
// folgando nos seus sábados setenta anos — e o pregão de um rei estrangeiro.
// Cada figurante anônimo destas cenas é alguém REAL daquele capítulo: o que
// tapou a boca do manancial, o que empilhou os escudos, o cavador do aqueduto
// de Giom, o adivinho da corte, o moedor das imagens em pó, o levita que
// largou a carga dos ombros, o flecheiro de Megido, a donzela morta no
// santuário, o arauto do pregão de Ciro.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_32_36: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- 2Cr 32
  32: {
    rei: {
      title: "Senaqueribe, rei da Assíria, e Ezequias, rei de Judá — os dois tronos deste capítulo, e Manassés no último versículo",
      subtitle: "2Cr 32:1-23,33 • o campo diante das cidades fortificadas, o muro de Jerusalém e a casa do deus de Nínive",
      text: "O capítulo começa com um rei entrando e acaba com outro saindo: \"Depois destas coisas e desta verdade, veio Senaqueribe, rei da Assíria, e entrou em Judá, e acampou-se contra as cidades fortificadas, e intentou apoderar-se delas\" (2Cr 32:1) — e o Cronista faz questão dessa nota de abertura: a invasão vem depois da fidelidade, não em vez dela. Ezequias não responde com exército, responde com obra e com uma frase: \"Com ele está o braço de carne, mas conosco o Senhor nosso Deus, para nos ajudar, e para guerrear por nós\" (2Cr 32:8) — o mesmo contraste de Jeremias 17:5,7. Senaqueribe é o rei que já tinha tomado quarenta e seis cidades muradas de Judá e que fala como quem já venceu: \"nenhum deus de nação alguma, nem de reino algum, pôde livrar o seu povo da minha mão\" (2Cr 32:15). O desfecho não lhe dá batalha nenhuma: \"e envergonhado voltou à sua terra; e, entrando na casa de seu deus, alguns dos seus próprios filhos, o mataram ali à espada\" (2Cr 32:21) — Reis nomeia os filhos, Adrameleque e Sarezer, e o templo, o de Nisroque (2Rs 19:37). O terceiro rei entra calado no fim: \"e Manassés, seu filho, reinou em seu lugar\" (2Cr 32:33), e leva cinquenta e cinco anos para desfazer tudo.",
    },
    homem: {
      title: "O sentinela sobre o muro, o príncipe do conselho das fontes, o homem valente, o capitão de guerra, o arauto que gritou em judaico, o valente ceifado no arraial, o cavador do aqueduto de Giom e o embaixador de Babilônia",
      subtitle: "2Cr 32:3-31 • os homens de um cerco que se ganhou com pedreiro, com oração e com uma noite",
      text: "O primeiro homem em cena não pega em arma, pega em mapa: \"Teve conselho com os seus príncipes e os seus homens valentes, para que se tapassem as fontes das águas que havia fora da cidade; e eles o ajudaram\" (2Cr 32:3). A lógica do trabalho é dita em voz alta e é de guerra pura: \"Por que viriam os reis da Assíria, e achariam tantas águas?\" (2Cr 32:4) — sede é arma, e Judá a tira do inimigo antes de ele chegar. Depois há o homem que está em cima da muralha quando os arautos assírios param debaixo dela: \"E clamaram em alta voz em judaico contra o povo de Jerusalém, que estava em cima do muro, para os atemorizar e os perturbar, para que tomassem a cidade\" (2Cr 32:18) — falaram a língua da casa de propósito, para que o soldado do parapeito entendesse sem intérprete e a coragem caísse por dentro. Depois vem o homem que amanheceu morto sem que ninguém o tocasse: \"o Senhor enviou um anjo que destruiu a todos os homens valentes, e os líderes, e os capitàes no arraial do rei da Assíria\" (2Cr 32:21; Reis conta cento e oitenta e cinco mil, 2Rs 19:35). E ainda há dois que ninguém canta: o que abriu a rocha por baixo da cidade, porque \"o mesmo Ezequias tapou o manancial superior das águas de Giom, e as fez correr por baixo para o ocidente da cidade de Davi\" (2Cr 32:30), e o hóspede que veio de longe perguntar \"acerca do prodígio que se fez naquela terra\" (2Cr 32:31) e a quem o rei mostrou tudo o que tinha.",
    },
    servo: {
      title: "O carregador das pedras das fontes, o ferreiro das armas e escudos em abundância, o que empilhou os escudos, o escriba das cartas de blasfêmia, o servo do leito da doença, o tesoureiro, o servo dos armazéns e o que carregou a terra do túnel",
      subtitle: "2Cr 32:4-30 • as mãos que executaram o que o capítulo credita ao rei",
      text: "\"Assim muito povo se ajuntou, e tapou todas as fontes, como também o ribeiro que se estendia pelo meio da terra\" (2Cr 32:4) — e tapar fonte é serviço de enxada, laje e argamassa, feito de joelhos no barro da encosta. Depois vem a forja: \"e fez armas e escudos em abundância\" (2Cr 32:5); o texto credita ao rei, mas quem malhou o ferro e empilhou o escudo na praça de armas foi este servo. Do outro lado da linha há um que trabalha para o inimigo e cuja tarefa é escrever: \"Escreveu também cartas, para blasfemar do Senhor Deus de Israel, e para falar contra ele\" (2Cr 32:17) — alguém segurou o cálamo enquanto Senaqueribe ditava contra o Deus de Israel. Mais tarde o capítulo vira para dentro de casa e há quem vele a cabeceira: \"Naqueles dias Ezequias adoeceu mortalmente\" (2Cr 32:24). E há a equipe da prosperidade: \"proveu-se de tesouraria para prata, ouro, pedras preciosas, especiarias, escudos, e toda a espécie de objetos desejáveis. Também de armazéns para a colheita do trigo, e do vinho, e do azeite\" (2Cr 32:27-28). O último destes servos sai da cidade com cesto de terra ao ombro, tirando entulho de dentro da rocha: o aqueduto que trouxe Giom para dentro do muro (2Cr 32:30) — o túnel de Siloé, que ainda se atravessa a pé, é a obra de engenharia mais visível que Judá deixou.",
    },
    anciao: {
      title: "Os anciãos de Judá reunidos na praça da porta e o sacerdote da casa do SENHOR nos dias de Ezequias",
      subtitle: "2Cr 32:6,20,23 • o largo do discurso e o átrio do clamor",
      text: "O rei põe capitães de guerra sobre o povo, mas quem ele reúne primeiro é a cidade inteira, e os cabeças estão na frente: \"e reuniu-os na praça da porta da cidade, e falou-lhes ao coração\" (2Cr 32:6). A praça da porta é o fórum de Israel — onde o ancião se assenta, onde se julga a causa e se sela o negócio (Rt 4:1-2; Pv 31:23) —, e é ali, e não no parapeito, que Judá recebe o argumento de 32:7-8. O segundo ancião está no átrio de noite, ao lado de dois homens de cara para cima: \"Porém o rei Ezequias e o profeta Isaías, filho de Amós, oraram contra isso, e clamaram ao céu\" (2Cr 32:20) — o Cronista não descreve procissão nem jejum nacional; descreve dois homens clamando, e é essa a única arma que Judá usa no capítulo. Terminado o livramento, é este mesmo sacerdote que recebe à porta o que as nações começam a mandar: \"E muitos traziam a Jerusalém presentes ao Senhor, e coisas preciosíssimas a Ezequias, rei de Judá\" (2Cr 32:23) — presentes ao SENHOR e presentes ao rei, na mesma frase e na mesma carreta, e é aí que começa o problema do coração que se exalta (2Cr 32:25).",
    },
    multidao: {
      title: "O povo que se ajuntou e tapou todas as fontes, que descansou nas palavras do rei, que estava em cima do muro quando gritaram em judaico — e os moradores de Jerusalém livrados, que depois se humilharam com o rei",
      subtitle: "2Cr 32:4,8,18,22,26 • a cidade como personagem, do trabalho ao medo, do medo ao livramento",
      text: "Esta multidão aparece quatro vezes e muda de posição em cada uma. Primeiro está no vale, com pedra na mão: \"Assim muito povo se ajuntou, e tapou todas as fontes\" (2Cr 32:4). Depois está na praça da porta, ouvindo, e o Cronista registra o efeito exato do discurso — não entusiasmo, descanso: \"E o povo descansou nas palavras de Ezequias, rei de Judá\" (2Cr 32:8). Depois está em cima do muro, calada, enquanto os arautos gritam de baixo na sua própria língua \"para os atemorizar e os perturbar, para que tomassem a cidade\" (2Cr 32:18) — e o texto não registra uma única resposta do parapeito, o que em Reis é ordem expressa do rei: \"Não lhe respondereis\" (2Rs 18:36). E depois está livre sem ter pelejado: \"Assim livrou o Senhor a Ezequias, e aos moradores de Jerusalém, da mão de Senaqueribe, rei da Assíria, e da mão de todos; e de todos os lados os guiou\" (2Cr 32:22). A última vez em que aparece não é de vitória: \"Ezequias, porém, se humilhou pela exaltação do seu coração, ele e os habitantes de Jerusalém; e a grande ira do Senhor não veio sobre eles, nos dias de Ezequias\" (2Cr 32:26) — a cidade se humilha junto com o rei, e o adiamento do juízo é de todos.",
    },
    mulherComum: {
      title: "A mulher de Jerusalém em cima do muro, que ouviu os arautos gritarem contra o seu Deus na sua própria língua",
      subtitle: "2Cr 32:18-19 • o adarve cheio de gente, e um cerco travado por palavras",
      text: "Ela está onde o texto a põe: \"E clamaram em alta voz em judaico contra o povo de Jerusalém, que estava em cima do muro, para os atemorizar e os perturbar, para que tomassem a cidade\" (2Cr 32:18). Não é soldado; é moradora, subiu ao muro como sobe quem quer ver o que vem pela estrada, e o que ouve é feito para ela: a Assíria escolheu falar judaico justamente para que a dona de casa, o velho e o menino entendessem antes dos oficiais — o cerco começa pelo ouvido. E o que dizem é a coisa mais perigosa do capítulo: \"E falaram do Deus de Jerusalém, como dos deuses dos povos da terra, obras das mãos dos homens\" (2Cr 32:19). Põem o SENHOR na prateleira dos ídolos que a Assíria já derrubou em vinte países, e a conta parece fechar. Ela ainda deve ter ouvido a chacota anterior, que atacava justamente a reforma que a fizera guardar a páscoa em Jerusalém: \"Não é Ezequias o mesmo que tirou os seus altos e os seus altares…?\" (2Cr 32:12). Nem ela nem ninguém do muro respondeu; a resposta veio de noite, no arraial (2Cr 32:21).",
    },
    patriarca: {
      title: "Isaías, filho de Amós, o profeta que orou com o rei e escreveu a visão em que este reinado ficou registrado",
      subtitle: "2Cr 32:20,32 • o átrio do clamor de noite, e a câmara dos rolos",
      text: "O Cronista dá a Isaías duas linhas e um livro. A primeira linha é de joelhos: \"Porém o rei Ezequias e o profeta Isaías, filho de Amós, oraram contra isso, e clamaram ao céu\" (2Cr 32:20) — a única ação militar de Judá neste capítulo é uma oração de dois homens, e o versículo seguinte começa com \"Então\". A segunda é de arquivo: \"Quanto aos demais atos de Ezequias, e as suas boas obras, eis que estão escritos na visão do profeta Isaías, filho de Amós, e no livro dos reis de Judá e de Israel\" (2Cr 32:32) — o profeta é também o cronista do reinado, e o que ele escreveu está aberto na nossa Bíblia em Isaías 36 a 39. Foi ele quem levou a Ezequias a resposta do SENHOR contra Senaqueribe (\"A virgem, a filha de Sião, te despreza\", Is 37:22), quem lhe disse \"Põe em ordem a tua casa, porque morrerás\" e voltou com quinze anos a mais e o sinal da sombra que recuou dez graus (Is 38:1-8), e quem, depois da visita dos babilônios, deu o aviso que este capítulo prefere resumir em uma frase: \"Eis que virão dias em que tudo quanto houver em tua casa… será levado para babilônia\" (Is 39:6). Um século e meio depois, 2Cr 36 cumpre o recado.",
    },
    anjo: {
      title: "O anjo que o SENHOR enviou ao arraial do rei da Assíria",
      subtitle: "2Cr 32:21 • uma noite no acampamento assírio, e nenhuma palavra dita",
      text: "\"Então o Senhor enviou um anjo que destruiu a todos os homens valentes, e os líderes, e os capitàes no arraial do rei da Assíria\" (2Cr 32:21). O versículo começa com \"Então\", ligado ao clamor dos dois homens do versículo anterior, e não descreve batalha nenhuma: as tendas ficam de pé e ninguém fica de pé. Reis dá o número e a hora: \"saiu o anjo do Senhor, e feriu no arraial dos assírios a cento e oitenta e cinco mil deles; e, levantando-se pela manhã cedo, eis que todos eram cadáveres\" (2Rs 19:35). O texto não lhe põe uma palavra na boca — é o único mediador destes cinco capítulos que age em silêncio absoluto —, e por isso a cena inteira é o argumento. Este é o mesmo mensageiro que passou pelo Egito na noite da páscoa (Êx 12:23,29), o que parou de ferir junto à eira de Ornã (1Cr 21:15-16), o que abriu a prisão de Pedro (At 12:7) e o que feriu a Herodes na tribuna \"porque não deu glória a Deus\" (At 12:23). Aqui ele responde exatamente à frase de 32:19: quem chamou o SENHOR de obra das mãos dos homens perdeu, sem espada, todo o valente, todo o líder e todo o capitão que tinha.",
    },
    pastor: {
      title: "O pastor dos currais e das estrebarias de Ezequias, no tempo em que Deus lhe deu muitíssimas possessões",
      subtitle: "2Cr 32:28-29 • o terreiro fora da cidade, depois do livramento",
      text: "Depois da noite do arraial, o capítulo faz um inventário de fazenda: \"Também de armazéns para a colheita do trigo, e do vinho, e do azeite; e de estrebarias para toda a espécie de animais e de currais para os rebanhos. Edificou também cidades, e possuiu ovelhas e vacas em abundância; porque Deus lhe tinha dado muitíssimas possessões\" (2Cr 32:28-29). Este pastor é o empregado dessa conta: toca ovelha para o curral novo, conta cabeça na entrada, dorme no campo perto do gado do rei. O detalhe que o Cronista não deixa passar é a causa — \"porque Deus lhe tinha dado\" —, e é justamente a fartura que arma a armadilha do versículo 25: \"não correspondeu Ezequias ao benefício que lhe fora feito; porque o seu coração se exaltou\". Judá conhecia o risco de cor: \"E se tiverem aumentado os teus gados e os teus rebanhos… Se eleve o teu coração e te esqueças do Senhor teu Deus\" (Dt 8:13-14). O pastor não vê nada disso; vê pasto bom depois de um susto grande, e leva o rebanho para lá.",
    },
    rebanho: {
      title: "As ovelhas e as vacas em abundância de Ezequias, e o gado dos currais que ele mandou fazer",
      subtitle: "2Cr 32:28-29 • os currais e as estrebarias do rei que prosperou em todas as suas obras",
      text: "\"e de currais para os rebanhos. Edificou também cidades, e possuiu ovelhas e vacas em abundância; porque Deus lhe tinha dado muitíssimas possessões\" (2Cr 32:28-29). É o retrato de uma casa que se recompôs depressa: poucos anos antes este mesmo rei tinha tirado do templo e do palácio a prata para pagar o tributo assírio, e chegou a cortar o ouro das portas da casa do SENHOR (2Rs 18:15-16). Agora as tesourarias enchem outra vez e o pasto está cheio. Rebanho de rei não é ornamento: é a despesa do altar — foi da sua fazenda que saíram os mil novilhos e as sete mil ovelhas da páscoa do segundo mês (2Cr 30:24) —, é a mesa da corte e é a reserva de um reino que espera cerco. O versículo seguinte fecha a lista com a obra que valeu mais do que todo esse gado: o manancial de Giom trazido por baixo da rocha para dentro da cidade (2Cr 32:30). E o versículo depois desse lembra que nada disso segurou o coração do dono, quando chegaram os hóspedes de Babilônia (2Cr 32:31).",
    },
  },

  // ---------------------------------------------------------------- 2Cr 33
  33: {
    rei: {
      title: "Manassés, doze anos de idade e cinquenta e cinco de reinado; Amom, que não se humilhou; e Josias, feito rei pelo povo da terra",
      subtitle: "2Cr 33:1-25 • o trono de Judá no seu pior e mais longo reinado, e as duas sucessões que o seguem",
      text: "\"Tinha Manassés doze anos de idade, quando começou a reinar, e cinqüenta e cinco anos reinou em Jerusalém\" (2Cr 33:1) — é o reinado mais longo da história de Judá e o mais destrutivo: reedificou os altos que o pai derrubara, encheu os dois átrios da casa de altares ao exército dos céus, pôs uma imagem de escultura dentro do santuário e \"tanto fez errar a Judá e aos moradores de Jerusalém, que fizeram pior do que as nações que o Senhor tinha destruído\" (2Cr 33:9). Reis acrescenta o que Crônicas cala: \"derramou muitíssimo sangue inocente, até que encheu a Jerusalém de um ao outro extremo\" (2Rs 21:16). E então o Cronista conta o que Reis não conta: os ganchos, as cadeias, Babilônia, e a frase que nenhum leitor espera neste capítulo — \"Então conheceu Manassés que o Senhor era Deus\" (2Cr 33:13). Volta e desfaz o que pode desfazer: levanta o muro de fora bem alto, tira da casa os deuses estranhos e o ídolo, repara o altar. O filho recebe os ídolos e não recebe o arrependimento: \"Mas não se humilhou perante o Senhor, como Manassés, seu pai, se humilhara; antes multiplicou Amom os seus delitos\" (2Cr 33:23), e morre em casa pelas mãos dos servos. Sobre esse corpo o povo da terra põe na cadeira um menino de oito anos (2Cr 33:25).",
    },
    homem: {
      title: "O pedreiro dos altares dos Baalins, o servidor dos altares do átrio de fora, o adivinho e o encantador da corte, o capitão assírio dos ganchos, o pedreiro do muro de fora e o que sacrificava nos altos ao SENHOR",
      subtitle: "2Cr 33:3-17 • os homens que construíram a queda deste reinado e depois reconstruíram o muro",
      text: "O primeiro está de colher na mão dentro da casa de Deus: \"E edificou altares na casa do Senhor… Edificou altares a todo o exército dos céus, em ambos os átrios da casa do Senhor\" (2Cr 33:4-5) — não é um canto escondido, é a casa inteira ocupada, do pátio de dentro ao de fora. Os dois seguintes são oficiais de gabinete e vivem de ler o invisível: \"e usou de adivinhações e de agouros, e de feitiçarias, e consultou adivinhos e encantadores\" (2Cr 33:6), tudo o que Deuteronômio 18:10-12 lista como abominação e razão pela qual as nações foram lançadas fora daquela terra. Depois entra o homem que muda a cena: \"Assim o Senhor trouxe sobre eles os capitàes do exército do rei da Assíria, os quais prenderam a Manassés com ganchos e, amarrando-o com cadeias, o levaram para Babilônia\" (2Cr 33:11) — o gancho no lábio ou no nariz é o método assírio de conduzir preso, o mesmo que Ezequiel usaria como figura do juízo (Ez 19:4,9; 38:4). E há, no fim, o homem que trabalha com o rei convertido: \"edificou o muro de fora da cidade de Davi, ao ocidente de Giom, no vale, e à entrada da porta do peixe, e ao redor de Ofel, e o levantou muito alto\" (2Cr 33:14). O último de todos é o mais teimoso: \"Contudo o povo ainda sacrificava nos altos, mas somente ao Senhor seu Deus\" (2Cr 33:17) — meio corrigido, e é esse meio que Josias teria de acabar de derrubar.",
    },
    servo: {
      title: "O servo do átrio de Manassés, o filho levado ao fogo em Hinom, o levita que guardou a lei escondida, o carcereiro de Babilônia, os que subiram as pedras do muro de fora e os dois servos que mataram Amom em sua casa",
      subtitle: "2Cr 33:6,11-16,24 • os menores deste capítulo, e os que executaram tudo o que ele conta",
      text: "O primeiro destes não escolheu nada e é o mais novo de todos: \"Fez ele também passar seus filhos pelo fogo no vale do filho de Hinom\" (2Cr 33:6) — o mesmo vale ao sul da cidade onde Acaz já queimara os seus (2Cr 28:3), o gê-hinnom cujo nome a língua guardaria para o inferno (Jr 7:31-32; Mc 9:43-47). O segundo trabalha do outro lado: é o servo que carrega tocha, lenha e incensário para os altares que o rei plantou nos dois átrios (2Cr 33:5). O terceiro leva o rei preso e não é de Judá: fica na porta do cárcere onde \"ele, angustiado, orou deveras ao Senhor seu Deus, e humilhou-se muito perante o Deus de seus pais\" (2Cr 33:12) — um rei ajoelhado no chão de um cativeiro estrangeiro é a única imagem deste capítulo que o Cronista trata com misericórdia. Os quartos sobem pedra com o rei de volta: o muro de fora ao ocidente de Giom, à entrada da porta do peixe e ao redor de Ofel, levantado muito alto (2Cr 33:14). E os últimos entram de madrugada num quarto de palácio: \"E conspiraram contra ele os seus servos, e o mataram em sua casa\" (2Cr 33:24) — dois anos de reinado acabam pela mão de quem servia à mesa.",
    },
    anciao: {
      title: "O sacerdote da casa do SENHOR que viu o ídolo entrar no santuário, o sacerdote do altar reparado depois de Babilônia e o que ungiu o menino Josias",
      subtitle: "2Cr 33:4-7,15-16,25 • o átrio profanado, o átrio limpo e a posse de um rei de oito anos",
      text: "Este sacerdote envelheceu vendo três coisas impossíveis. A primeira: \"Também pôs uma imagem de escultura do ídolo que tinha feito, na casa de Deus, da qual Deus tinha falado a Davi e a Salomão seu filho: Nesta casa e em Jerusalém, que escolhi de todas as tribos de Israel, porei o meu nome para sempre\" (2Cr 33:7) — o Cronista põe a promessa e a profanação no mesmo versículo, e é esse contraste, e não a estátua, que dói. A segunda vem depois do exílio pessoal do rei: \"E tirou da casa do Senhor os deuses estranhos e o ídolo, como também todos os altares que tinha edificado no monte da casa do Senhor, e em Jerusalém, e os lançou fora da cidade. E reparou o altar do Senhor e ofereceu sobre ele sacrifícios de ofertas pacíficas e de louvor\" (2Cr 33:15-16) — o mesmo homem que encheu o átrio de altares desmonta um por um e manda servir ao SENHOR Deus de Israel. A terceira é uma unção às pressas sobre uma criança, com o corpo de Amom ainda quente: \"e o povo da terra fez reinar em seu lugar a Josias, seu filho\" (2Cr 33:25). Este sacerdote viu o ídolo entrar e viu o ídolo sair, e ainda pôs a mão na cabeça do menino que acharia o livro.",
    },
    multidao: {
      title: "O povo de Judá que Manassés fez errar, o povo que o recebeu de volta de Babilônia, o Judá a quem ele ordenou que servisse ao SENHOR e o povo da terra que vingou Amom",
      subtitle: "2Cr 33:9,13,16,25 • a cidade arrastada, e depois arrastada de volta",
      text: "A sentença mais dura do capítulo não é sobre o rei, é sobre o que ele fez com a rua: \"E Manassés tanto fez errar a Judá e aos moradores de Jerusalém, que fizeram pior do que as nações que o Senhor tinha destruído de diante dos filhos de Israel\" (2Cr 33:9) — pior do que os cananeus, na terra tomada dos cananeus por causa dessas mesmas coisas. Um povo aprende com o palácio, e cinquenta e cinco anos são duas gerações inteiras que nunca viram outra coisa. Depois esta mesma multidão vê voltar pela estrada do norte um rei que saíra de ganchos: \"e tornou a trazê-lo a Jerusalém, ao seu reino. Então conheceu Manassés que o Senhor era Deus\" (2Cr 33:13), e recebe dele uma ordem que ninguém esperava daquela boca: \"e ordenou a Judá que servisse ao Senhor Deus de Israel\" (2Cr 33:16). A obediência é parcial e o texto não a maquia: \"Contudo o povo ainda sacrificava nos altos, mas somente ao Senhor seu Deus\" (2Cr 33:17). E, dois reinados de dois anos depois, é este mesmo povo que faz justiça com as próprias mãos: \"Porém o povo da terra feriu a todos quantos conspiraram contra o rei Amom\" (2Cr 33:25) — a rua guarda a casa de Davi mesmo quando o rei da casa de Davi não a merece.",
    },
    mulherComum: {
      title: "A mãe que viu o filho passar pelo fogo no vale de Hinom e a mulher que subiu ao alto com a oferta na mão",
      subtitle: "2Cr 33:3,6,17 • o vale ao sul da cidade e o outeiro de fora, nos dias em que o rei mandava",
      text: "As duas mulheres deste capítulo estão nos dois lugares em que a religião de Manassés acontecia. A primeira desce ao vale: \"Fez ele também passar seus filhos pelo fogo no vale do filho de Hinom\" (2Cr 33:6). Quando o rei faz isso com os próprios filhos, a corte imita, e Jeremias descreveria o resultado poucas décadas depois, no mesmo terreno: \"E edificaram os altos de Tofete, que está no Vale do Filho de Hinom, para queimarem no fogo a seus filhos e a suas filhas, o que nunca ordenei, nem me subiu ao coração\" (Jr 7:31). A segunda sobe o outeiro com a cesta: \"tornou a edificar os altos que Ezequias, seu pai, tinha derrubado; e levantou altares aos Baalins, e fez bosques\" (2Cr 33:3) — o bosque, a aserá, é o poste do culto de fertilidade, e sempre encontrou nas mulheres da terra a sua clientela mais fiel, com o bolo, o incenso e a libação (Jr 44:19; Os 4:13). Ela tinha visto, menina, o pátio cheio de montões e a páscoa de catorze dias (2Cr 30-31); voltou ao alto porque o alto voltou. E no fim do capítulo ainda está lá, com o culto meio corrigido: \"Contudo o povo ainda sacrificava nos altos, mas somente ao Senhor seu Deus\" (2Cr 33:17).",
    },
    patriarca: {
      title: "Os videntes que falaram a Manassés no nome do SENHOR Deus de Israel, e não foram ouvidos",
      subtitle: "2Cr 33:10,18 • o salão do trono, com o incensário do ídolo fumegando atrás",
      text: "\"E falou o Senhor a Manassés e ao seu povo, porém não deram ouvidos\" (2Cr 33:10). O versículo é curto e esconde anos: Deus não ficou calado durante cinquenta e cinco anos de abominação, mandou gente falar, e o Cronista guarda os nomes desses homens num arquivo que perdemos — \"O restante dos atos de Manassés, e a sua oração ao seu Deus, e as palavras dos videntes que lhe falaram no nome do Senhor Deus de Israel, eis que estão nas crônicas dos reis de Israel\" (2Cr 33:18). Reis conserva um pedaço do que eles disseram, e é a sentença de morte de Jerusalém: \"Eis que hei de trazer um mal sobre Jerusalém e Judá, que qualquer que ouvir, lhe ficarão retinindo ambos os ouvidos… e limparei a Jerusalém, como quem limpa o prato\" (2Rs 21:12-13). A tradição judaica põe Isaías entre os profetas mortos neste reinado, e Hebreus 11:37, ao falar dos que foram \"apedrejados, serrados\", é lida desde cedo como eco disso. Este vidente prega diante de um trono que tem o ídolo ao lado e sai sem resposta — e, ainda assim, a palavra que ele levou é a que alcança o rei depois, no chão de um cárcere em Babilônia (2Cr 33:12-13).",
    },
  },

  // ---------------------------------------------------------------- 2Cr 34
  34: {
    rei: {
      title: "Josias, oito anos de idade, que aos dezesseis começou a buscar, aos vinte começou a purificar e aos vinte e seis rasgou as suas vestes",
      subtitle: "2Cr 34:1-33 • trinta e um anos de reinado contados por três idades e um livro",
      text: "\"Tinha Josias oito anos quando começou a reinar, e trinta e um anos reinou em Jerusalém. E fez o que era reto aos olhos do Senhor; e andou nos caminhos de Davi, seu pai, sem se desviar deles nem para a direita nem para a esquerda\" (2Cr 34:1-2). O Cronista datou a conversão dele: \"no oitavo ano do seu reinado, sendo ainda moço, começou a buscar o Deus de Davi, seu pai; e no duodécimo ano começou a purificar a Judá e a Jerusalém\" (2Cr 34:3) — dezesseis anos para buscar, vinte para pegar na marreta, vinte e seis para mandar consertar a casa. A purificação é feita na frente dele: \"E derrubaram perante ele os altares de Baalins\" (2Cr 34:4), e o pó das imagens é espargido sobre as sepulturas dos que lhes tinham sacrificado, e os ossos dos sacerdotes queimados sobre os seus próprios altares (2Cr 34:5) — cumprindo, à letra e com trezentos anos de atraso, a palavra do homem de Deus contra o altar de Betel: \"Eis que um filho nascerá à casa de Davi, cujo nome será Josias\" (1Rs 13:2). E então o rei que já tinha limpado tudo ouve pela primeira vez o que estava escrito: \"Sucedeu que, ouvindo o rei as palavras da lei, rasgou as suas vestes\" (2Cr 34:19). A resposta do SENHOR é sobre esse gesto: \"Porquanto o teu coração se enterneceu… também eu te ouvi\" (2Cr 34:27).",
    },
    anciao: {
      title: "Hilquias, o sumo sacerdote que achou o livro; Safã, o escrivão que o leu perante o rei; e os anciãos de Judá e de Jerusalém reunidos para ouvir a aliança",
      subtitle: "2Cr 34:9,14-22,29-30 • a câmara do dinheiro, o salão do rei e o átrio da leitura pública",
      text: "O achado não foi procurado: \"E, tirando eles o dinheiro que se tinha trazido à casa do Senhor, Hilquias, o sacerdote, achou o livro da lei do Senhor, dada pela mão de Moisés\" (2Cr 34:14) — estavam contando moeda para pagar carpinteiro, e apareceu o livro. A frase com que ele avisa o escrivão é de quem ainda não mediu o tamanho da coisa: \"Achei o livro da lei na casa do Senhor. E Hilquias deu o livro a Safã\" (2Cr 34:15). Safã faz o serviço de um funcionário exemplar: primeiro presta contas da obra — \"Teus servos fazem tudo quanto se lhes encomendou\" (2Cr 34:16) — e só depois, quase como quem se lembra, acrescenta: \"O sacerdote Hilquias entregou-me um livro. E Safã leu nele perante o rei\" (2Cr 34:18). Foi a leitura, não o achado, que rasgou as vestes do rei. Depois estes mesmos anciãos vão em delegação à casa de uma mulher, na segunda parte da cidade (2Cr 34:22), e voltam com o oráculo. E no fim são convocados todos: \"Então o rei mandou reunir todos os anciãos de Judá e Jerusalém\" (2Cr 34:29), e o próprio rei lê em voz alta, do princípio ao fim, \"todas as palavras do livro da aliança que fora achado na casa do Senhor\" (2Cr 34:30).",
    },
    homem: {
      title: "O derrubador dos altares dos Baalins, o moedor das imagens em pó, o queimador dos ossos sobre os altares, o carpinteiro e o edificador da obra, os quatro superintendentes levitas e o porteiro que guardava a entrada",
      subtitle: "2Cr 34:4-13 • o canteiro da purificação e o canteiro do conserto, com o mesmo povo nos dois",
      text: "A limpeza deste capítulo é serviço de marreta, moinho e peneira: \"e despedaçou as imagens, que estavam acima deles; e os bosques, e as imagens de escultura e de fundição quebrou e reduziu a pó, e o espargiu sobre as sepulturas dos que lhes tinham sacrificado\" (2Cr 34:4). Reduzir a pó não é destruir, é humilhar — o pó do ídolo cai em cima do túmulo de quem lhe sacrificou, e o morto fica devendo ao rei a última palavra. O trabalho seguinte é ainda mais pesado: \"E os ossos dos sacerdotes queimou sobre os seus altares\" (2Cr 34:5), o gesto que torna o lugar imundo para sempre. Depois os mesmos braços mudam de lado e passam a construir: \"E deram-no aos carpinteiros e aos edificadores, para comprarem pedras lavradas, e madeiras para as junturas e para servirem de vigas para as casas que os reis de Judá tinham destruído\" (2Cr 34:11) — repare que o estrago era interno, feito pelos próprios reis. E o Cronista faz questão de dizer como estes homens trabalhavam e quem os dirigia: \"E estes homens trabalhavam fielmente na obra; e os superintendentes sobre eles eram: Jaate e Obadias, levitas, dos filhos de Merari, como também Zacarias e Mesulão, dos filhos dos coatitas, para adiantarem a obra; e todos os levitas que eram entendidos em instrumentos de música\" (2Cr 34:12). Quem cantava no átrio tocava a obra do átrio.",
    },
    servo: {
      title: "O que espargiu o pó das imagens sobre as sepulturas, o que atiçou o fogo dos ossos sobre os altares, o carregador da obra, o escrivão levita, o porteiro da entrada e o arauto que reuniu os anciãos",
      subtitle: "2Cr 34:4-5,9,13,29 • as mãos miúdas de uma reforma que começou por fora e acabou por dentro",
      text: "\"e o espargiu sobre as sepulturas dos que lhes tinham sacrificado\" (2Cr 34:4) — alguém andou de cemitério em cemitério com um cesto de pó de ídolo, jogando punhado sobre laje. \"E os ossos dos sacerdotes queimou sobre os seus altares\" (2Cr 34:5) — alguém trouxe a lenha e abriu os túmulos. Estes servos fazem o serviço que o texto credita ao rei e ninguém quis fazer. Depois eles mudam de ofício com a mesma naturalidade: um recebe moeda à porta, porque o dinheiro da casa foi o \"que os levitas, que guardavam a entrada tinham recebido da mão de Manassés, e de Efraim, e de todo o restante de Israel, como também de todo o Judá e Benjamim\" (2Cr 34:9) — a coleta atravessou fronteiras de reinos que já não existiam. Outro carrega pedra lavrada e viga; outro lança em rolo o que entra e o que sai, porque \"Estavam também sobre os carregadores e dirigiam todos os que trabalhavam em alguma obra; e dentre os levitas havia escrivães, oficiais e porteiros\" (2Cr 34:13). E o último atravessa Judá com um recado curto na boca, cidade por cidade: \"Então o rei mandou reunir todos os anciãos de Judá e Jerusalém\" (2Cr 34:29).",
    },
    mulherComum: {
      title: "Hulda, a profetisa, mulher de Salum, guarda das vestimentas, que habitava em Jerusalém na segunda parte",
      subtitle: "2Cr 34:22-28 • a casa de onde saiu o oráculo que o sumo sacerdote e os oficiais do rei foram buscar",
      text: "O rei tinha cinco homens de confiança e mandou os cinco à casa de uma mulher: \"Então Hilquias, e os enviados do rei, foram ter com a profetisa Hulda, mulher de Salum, filho de Tocate, filho de Harás, guarda das vestimentas (e habitava ela em Jerusalém na segunda parte); e falaram-lhe a esse respeito\" (2Cr 34:22). Jeremias já profetizava em Judá havia cinco anos e Sofonias também; os enviados vieram a esta casa, e o texto não explica por quê — apenas registra que a palavra do SENHOR estava ali. Ela não os poupa, e começa com a frase mais desconcertante do capítulo: \"Dizei ao homem que vos enviou a mim\" (2Cr 34:23), sem título e sem cortesia de corte. O oráculo tem duas metades. Sobre o lugar: \"Eis que trarei mal sobre este lugar, e sobre os seus habitantes, a saber, todas as maldições que estão escritas no livro\" (2Cr 34:24), e \"o meu furor se derramou sobre este lugar, e não se apagará\" (2Cr 34:25). Sobre o homem que perguntou: \"Porquanto o teu coração se enterneceu, e te humilhaste perante Deus… e rasgaste as tuas vestes, e choraste perante mim, também eu te ouvi\" (2Cr 34:27) — a reforma não cancela o juízo, mas adia-o por uma vida. Ela é a terceira profetisa da linha de Míriam e Débora (Êx 15:20; Jz 4:4).",
    },
    multidao: {
      title: "Todo o povo, desde o maior até ao menor, que subiu à casa do SENHOR para ouvir o livro — e todos quantos se achavam em Israel, obrigados a servir ao SENHOR",
      subtitle: "2Cr 34:30-33 • o átrio da leitura pública e a terra inteira varrida",
      text: "\"E o rei subiu à casa do Senhor, com todos os homens de Judá, e os habitantes de Jerusalém, e os sacerdotes, e os levitas, e todo o povo, desde o maior até ao menor; e ele leu aos ouvidos deles todas as palavras do livro da aliança que fora achado na casa do Senhor\" (2Cr 34:30). \"desde o maior até ao menor\" é a medida exata da assembleia: não é convocação de notáveis, é a cidade toda, criança inclusive, ouvindo de uma vez o que estivera perdido dentro do próprio templo. O rei lê de pé e depois jura de pé: \"E pôs-se o rei em pé em seu lugar, e fez aliança perante o Senhor, para seguirem ao Senhor, e para guardar os seus mandamentos… com todo o seu coração, e com toda a sua alma\" (2Cr 34:31) — e então faz o que só um rei pode fazer: \"E fez com que todos quantos se achavam em Jerusalém e em Benjamim o firmassem\" (2Cr 34:32). O capítulo fecha com a ambiguidade honesta do Cronista: \"e a todos quantos se achavam em Israel obrigou a que servissem ao Senhor seu Deus. Enquanto ele viveu não se desviaram de seguir o Senhor, o Deus de seus pais\" (2Cr 34:33). Obrigou — e a obediência durou exatamente o que durou a vida dele. Jeremias, pregando a esta mesma multidão, disse que ela não voltara \"de todo o seu coração, mas falsamente\" (Jr 3:10).",
    },
  },

  // ---------------------------------------------------------------- 2Cr 35
  35: {
    rei: {
      title: "Josias, que celebrou a páscoa que não se celebrava desde os dias de Samuel — e Necó, rei do Egito, cujas palavras saíram da boca de Deus",
      subtitle: "2Cr 35:1-24 • o átrio da maior páscoa de Israel, e o vale de Megido",
      text: "\"Então Josias celebrou a páscoa ao SENHOR em Jerusalém; e mataram o cordeiro da páscoa no décimo quarto dia do primeiro mês\" (2Cr 35:1) — no dia certo, ao contrário da de Ezequias (2Cr 30:2-3), e com o rei pagando o gado do próprio bolso: \"trinta mil, por todos os que ali se achavam, e de bois três mil; isto era da fazenda do rei\" (2Cr 35:7). O veredito é sem paralelo: \"Nunca, pois, se celebrou tal páscoa em Israel, desde os dias do profeta Samuel\" (2Cr 35:18). Cinco versículos depois, o mesmo homem morre por não ouvir. Necó vai a Carquemis guerrear contra outro e manda dizer: \"Que tenho eu contigo, rei de Judá? Não é contra ti que venho hoje… e disse Deus que me apressasse; guarda-te de te opores a Deus, que é comigo, para que ele não te destrua\" (2Cr 35:21). O Cronista sela o aviso de um pagão com a frase mais dura do capítulo: \"e não deu ouvidos às palavras de Neco, que saíram da boca de Deus\" (2Cr 35:22). Deus pode falar por uma boca errada, e o rei que passara a vida obedecendo ao livro morreu por não reconhecer a voz fora dele. Josias disfarça-se — como Acabe se disfarçara em Ramote (2Cr 18:29) —, é atingido pelos flecheiros e levado no segundo carro para morrer em Jerusalém (2Cr 35:23-24).",
    },
    anciao: {
      title: "Os sacerdotes postos nos seus cargos, Hilquias e os líderes da casa de Deus que deram do seu, os que espargiram o sangue e os que se ocuparam até à noite",
      subtitle: "2Cr 35:2,8,11,14 • o átrio do sacrifício, do amanhecer até depois de escurecer",
      text: "O rei começa a festa pelo clero: \"E estabeleceu os sacerdotes nos seus cargos, e os animou ao ministério da casa do Senhor\" (2Cr 35:2) — animar é o verbo, porque este era um sacerdócio que atravessara cinquenta e cinco anos de Manassés e dois de Amom. Depois eles não só servem: pagam. \"Hilquias, e Zacarias, e Jeiel, líderes da casa de Deus, deram aos sacerdotes para os sacrifícios da páscoa duas mil e seiscentas reses de gado miúdo, e trezentos bois\" (2Cr 35:8) — os chefes do templo abrem os próprios currais para que ninguém do povo fique sem cordeiro. O trabalho do dia é de matadouro e de altar ao mesmo tempo: \"Então imolaram a páscoa; e os sacerdotes espargiram o sangue recebido das mãos dos levitas que esfolavam as reses\" (2Cr 35:11), uma corrente de mãos em que o levita entrega a bacia e o sacerdote asperge. E o versículo que mede a jornada é este: \"porque os sacerdotes, filhos de Arão, se ocuparam até à noite com o sacrifício dos holocaustos e da gordura; por isso os levitas prepararam para si e para os sacerdotes\" (2Cr 35:14) — quem serviu o dia inteiro não teve tempo de fazer a própria ceia, e outro a fez por ele.",
    },
    servo: {
      title: "O levita que largou a carga dos ombros quando a arca pousou, o que esfolava as reses, o que assou a páscoa no fogo, o cantor filho de Asafe, o porteiro de cada porta e o servo que tirou o rei do carro em Megido",
      subtitle: "2Cr 35:3-15,24 • os levitas de uma páscoa inteira, e a mão que carregou um rei ferido",
      text: "A ordem que abre o serviço deles é uma aposentadoria: \"Ponde a arca sagrada na casa que edificou Salomão, filho de Davi, rei de Israel; não tereis mais esta carga aos ombros; agora servi ao Senhor vosso Deus, e ao seu povo Israel\" (2Cr 35:3). Desde o deserto o ofício coatita era levar a arca aos ombros pelos varais (Nm 4:15; 1Cr 15:15); o rei declara a marcha terminada e o ofício convertido em ensino e em serviço. O que vem depois é trabalho pesado e miúdo: esfolar rês e passar a bacia do sangue (2Cr 35:11), pôr de parte os holocaustos por casas paternas \"como está escrito no livro de Moisés\" (2Cr 35:12), e cozinhar para um país inteiro — \"E assaram a páscoa no fogo, segundo o rito; e as ofertas sagradas cozeram em panelas, e em caldeirões e em sertãs; e prontamente as repartiram entre todo o povo\" (2Cr 35:13), assada no fogo como manda Êxodo 12:8-9, e o resto fervido. Enquanto isso outros não saem do lugar: \"E os cantores, filhos de Asafe, estavam no seu posto… como também os porteiros a cada porta; não necessitaram de se desviarem do seu ministério; porquanto seus irmãos, os levitas, preparavam o necessário para eles\" (2Cr 35:15). O último destes servos aparece num campo, e não num átrio: \"E seus servos o tiraram do carro, e o levaram no segundo carro que tinha\" (2Cr 35:24).",
    },
    homem: {
      title: "O homem do povo que recebeu a sua porção, o soldado de Judá que saiu ao encontro de Necó, o mensageiro do Egito, o flecheiro que atirou contra o rei e o homem de Judá que o pranteou",
      subtitle: "2Cr 35:12-13,20-24 • do pátio da repartição ao vale de Megido, no mesmo capítulo",
      text: "O primeiro sai do átrio com comida na mão: \"E puseram de parte os holocaustos para os darem aos filhos do povo, segundo as divisões das casas paternas\" (2Cr 35:12), e \"prontamente as repartiram entre todo o povo\" (2Cr 35:13) — a maior páscoa da história de Israel foi também a mais bem servida, e ninguém ficou na fila. O segundo põe o elmo poucos meses depois: \"subiu Neco, rei do Egito, para guerrear contra Carquemis, junto ao Eufrates; e Josias lhe saiu ao encontro\" (2Cr 35:20) — Judá entrou numa guerra que não era sua, no caminho de duas potências que disputavam a herança da Assíria, e quatro anos depois Nabucodonosor liquidaria os egípcios naquela mesma Carquemis (Jr 46:2). O terceiro chega com uma mensagem estranha na boca e é o único a acertar no capítulo: \"guarda-te de te opores a Deus, que é comigo\" (2Cr 35:21). O quarto arma o arco no vale: \"E os flecheiros atiraram contra o rei Josias. Então o rei disse a seus servos: Tirai-me daqui, porque estou gravemente ferido\" (2Cr 35:23) — o disfarce não salvou, como não salvara Acabe (2Cr 18:33). E o último está na porta da cidade quando o segundo carro chega: \"e todo o Judá e Jerusalém prantearam a Josias\" (2Cr 35:24); Zacarias ainda mediria o luto futuro de Jerusalém por este: \"como o pranto de Hadade-Rimom no vale de Megido\" (Zc 12:11).",
    },
    mulherComum: {
      title: "A mulher do povo na páscoa de Josias e a cantora das lamentações, que canta sobre este rei até ao dia de hoje",
      subtitle: "2Cr 35:13,17,25 • o pátio das mesas nos sete dias dos ázimos, e o luto que virou estatuto",
      text: "Ela come no átrio, e o texto faz questão de dizer que a comida chegou depressa e a todos: \"e prontamente as repartiram entre todo o povo\" (2Cr 35:13). Depois ficam sete dias de casa cheia: \"E os filhos de Israel que ali se acharam celebraram a páscoa naquele tempo, e a festa dos pães ázimos, durante sete dias\" (2Cr 35:17) — pão sem fermento por uma semana é uma cozinha inteira reorganizada, e essa parte da festa recai sobre as mulheres de Judá, como recaía desde a noite do Egito (Êx 12:15-20,39). Poucos meses depois ela troca a mesa pelo canto do luto: \"E Jeremias fez uma lamentação sobre Josias; e todos os cantores e cantoras, nas suas lamentações, têm falado de Josias, até ao dia de hoje; porque as estabeleceram por estatuto em Israel; e eis que estão escritas nas lamentações\" (2Cr 35:25). Note o detalhe: cantoras, no plural e nomeadas ao lado dos cantores, com ofício reconhecido — como as duzentas e quarenta e cinco que voltaram do exílio (Ed 2:65). O pranto por este rei não foi um dia de choro; foi posto em partitura, guardado por estatuto e ainda se cantava quando o Cronista escreveu, gerações depois.",
    },
    multidao: {
      title: "O povo de Judá e de Israel que se achou em Jerusalém na páscoa de Josias, e comeu os sete dias dos pães ázimos",
      subtitle: "2Cr 35:17-19 • o átrio cheio no décimo oitavo ano do reinado",
      text: "\"E os filhos de Israel que ali se acharam celebraram a páscoa naquele tempo, e a festa dos pães ázimos, durante sete dias\" (2Cr 35:17). Repare em \"filhos de Israel\": não é só Judá. Samaria tinha caído havia quase um século, e o rei tinha purificado \"as cidades de Manassés, e de Efraim, e de Simeão, e ainda até Naftali\" (2Cr 34:6); nesta páscoa há gente do Norte no pátio, vinda de aldeias em ruínas para uma festa em Jerusalém. O Cronista mede o acontecimento contra o começo de tudo: \"Nunca, pois, se celebrou tal páscoa em Israel, desde os dias do profeta Samuel; nem nenhum rei de Israel celebrou tal páscoa como a que celebrou Josias com os sacerdotes, e levitas, e todo o Judá e Israel, que ali se acharam, e os habitantes de Jerusalém\" (2Cr 35:18) — nem Davi, nem Salomão, nem Ezequias. E então põe a data, que é a mesma do achado do livro: \"No décimo oitavo ano do reinado de Josias se celebrou esta páscoa\" (2Cr 35:19). A maior festa de Israel foi feita por um povo que tinha acabado de ouvir, pela primeira vez em voz alta, o livro que mandava fazê-la (2Cr 34:30-31). E treze anos depois esse mesmo povo estaria pagando cem talentos de prata ao Egito (2Cr 36:3).",
    },
    cavaleiro: {
      title: "O cavaleiro do exército de Necó, subindo pela estrada do mar para Carquemis",
      subtitle: "2Cr 35:20-22 • a passagem do Egito por Megido, no caminho do Eufrates",
      text: "\"Depois de tudo isto, havendo Josias já preparado o templo, subiu Neco, rei do Egito, para guerrear contra Carquemis, junto ao Eufrates; e Josias lhe saiu ao encontro\" (2Cr 35:20). Este cavaleiro não vinha atacar Judá: ia atravessá-lo. A passagem obrigatória entre o Egito e o Eufrates é a planície de Jezreel, e o gargalo dessa planície chama-se Megido — a esquina em que quase todas as batalhas da Palestina foram travadas, desde Débora e Baraque (Jz 5:19) até a que dá o nome à última (Ap 16:16). O que ele carregava era um recado que Judá não quis ouvir: \"Não é contra ti que venho hoje, mas contra a casa que me faz guerra; e disse Deus que me apressasse\" (2Cr 35:21). A campanha ia socorrer os restos da Assíria contra a Babilônia que subia; quatro anos depois esse mesmo exército seria desfeito em Carquemis por Nabucodonosor, e Jeremias escreveria o poema da derrota (Jr 46:2-12). Deste encontro no vale sobra um rei de Judá ferido, um trono ocupado por decisão egípcia (2Cr 36:4) e um país que passou a pagar tributo ao Egito antes de pagá-lo à Babilônia.",
    },
    cordeiro: {
      title: "O cordeiro da páscoa, morto no décimo quarto dia do primeiro mês",
      subtitle: "2Cr 35:1,6,11 • o animal por cuja conta a festa inteira existe",
      text: "\"Então Josias celebrou a páscoa ao SENHOR em Jerusalém; e mataram o cordeiro da páscoa no décimo quarto dia do primeiro mês\" (2Cr 35:1). A data é a de Êxodo 12:6, e a ordem dada aos levitas repete a fonte: \"E imolai a páscoa, e santificai-vos, e preparai-a para vossos irmãos, fazendo conforme a palavra do Senhor, dada pela mão de Moisés\" (2Cr 35:6). O que muda em relação ao Egito é quem segura a faca: lá era o chefe de cada casa (Êx 12:3-6), aqui é o levita, e o sangue passa da mão dele à mão do sacerdote, que o asperge no altar (2Cr 35:11). Foram trinta mil cordeiros e cabritos só da fazenda do rei, mais dois mil e seiscentos dos líderes da casa de Deus e cinco mil dos chefes dos levitas — perto de quarenta mil animais num só dia, num só pátio. E todos apontam para um: \"Eis o Cordeiro de Deus, que tira o pecado do mundo\" (Jo 1:29); \"Porque Cristo, nossa páscoa, foi sacrificado por nós\" (1Co 5:7). Na cruz, nenhum osso lhe foi quebrado — a regra que este cordeiro de Josias também obedecia (Êx 12:46; Jo 19:36).",
    },
    rebanho: {
      title: "Os trinta mil cordeiros e cabritos e os três mil bois da fazenda do rei, e as reses dadas pelos príncipes e pelos chefes dos levitas",
      subtitle: "2Cr 35:7-9 • o gado de uma páscoa em que ninguém pagou a sua",
      text: "\"E ofereceu Josias, aos filhos do povo, cordeiros e cabritos do rebanho, todos para os sacrifícios da páscoa, em número de trinta mil, por todos os que ali se achavam, e de bois três mil; isto era da fazenda do rei\" (2Cr 35:7). A última frase é a que importa: da fazenda do rei — não do tesouro do templo, nem de imposto novo. Depois vem a segunda leva: \"Hilquias, e Zacarias, e Jeiel, líderes da casa de Deus, deram aos sacerdotes para os sacrifícios da páscoa duas mil e seiscentas reses de gado miúdo, e trezentos bois\" (2Cr 35:8), e a terceira: \"E Conanias, e Semaías, e Natanael, seus irmãos, como também Hasabias, e Jeiel, e Jozabade, chefe dos levitas, apresentaram aos levitas, para os sacrifícios da páscoa, cinco mil reses de gado miúdo, e quinhentos bois\" (2Cr 35:9). Somam trinta e sete mil e seiscentas cabeças de gado miúdo e três mil e oitocentos bois. O Cronista está fazendo uma conta teológica, não pecuária: a páscoa é a festa da casa, em que cada família traz o seu cordeiro (Êx 12:3), e aqui o rei, os sacerdotes e os levitas cobrem a conta do povo inteiro, para que nenhuma casa pobre ficasse de fora da maior páscoa desde Samuel (2Cr 35:18).",
    },
    pastor: {
      title: "O pastor da fazenda do rei, que tangeu trinta mil cabeças de gado miúdo do campo até o átrio",
      subtitle: "2Cr 35:7 • as estradas de Judá nos dias que antecedem o décimo quarto do primeiro mês",
      text: "Antes da páscoa houve uma boiada. \"E ofereceu Josias, aos filhos do povo, cordeiros e cabritos do rebanho, todos para os sacrifícios da páscoa, em número de trinta mil, por todos os que ali se achavam, e de bois três mil; isto era da fazenda do rei\" (2Cr 35:7) — trinta mil cabeças não aparecem em Jerusalém por decreto: alguém as apartou no campo, as tangeu pelas estradas de Judá durante dias, as manteve juntas na subida e as entregou contadas no terreiro. O rebanho da coroa vinha das terras que os reis de Judá administravam desde Davi, com feitor próprio sobre as manadas e sobre os currais (1Cr 27:29-31); Uzias tinha lavradores e vinhateiros \"porque era amigo da agricultura\" (2Cr 26:10), e Ezequias enchera currais depois do livramento (2Cr 32:28-29). Este pastor é o herdeiro desse ofício, e o serviço dele é anônimo por definição: quando o texto começa a contar a festa, o gado já está lá. Sem ele, os quarenta mil animais dos versículos 7 a 9 seriam um número no papel.",
    },
    patriarca: {
      title: "Jeremias, o profeta que fez uma lamentação sobre Josias",
      subtitle: "2Cr 35:25 • o pátio do luto de Jerusalém, com o rei morto e o reino a cair",
      text: "\"E Jeremias fez uma lamentação sobre Josias; e todos os cantores e cantoras, nas suas lamentações, têm falado de Josias, até ao dia de hoje; porque as estabeleceram por estatuto em Israel; e eis que estão escritas nas lamentações\" (2Cr 35:25). Jeremias tinha começado a profetizar no décimo terceiro ano deste rei (Jr 1:2) e enterrou o único rei de Judá que ouviu o livro. Ele mesmo diria depois, comparando pai e filhos, o que via daquele reinado: \"Julgou a causa do aflito e necessitado; então lhe sucedeu bem; porventura não é isto conhecer-me? diz o Senhor\" (Jr 22:16). E, sobre o luto certo e o luto errado, mandou não chorar o morto e sim o que ia para o exílio: \"Não choreis o morto, nem o lastimeis; chorai abundantemente aquele que sai\" (Jr 22:10). O canto que ele compôs não se conservou — as Lamentações da nossa Bíblia são sobre a destruição de Jerusalém, vinte e dois anos depois —, mas ficou por estatuto, cantado por homens e mulheres em Israel durante gerações. É o mesmo profeta diante de quem Zedequias não se humilharia (2Cr 36:12) e por cuja boca o SENHOR marcaria os setenta anos e o despertar de Ciro (2Cr 36:21-22).",
    },
  },

  // ---------------------------------------------------------------- 2Cr 36
  36: {
    rei: {
      title: "Jeoacaz, Jeoiaquim, Joaquim e Zedequias — quatro reis em vinte versículos; e, do lado de fora, Necó, Nabucodonosor e Ciro",
      subtitle: "2Cr 36:1-23 • o trono de Davi passando de mão em mão até não haver mais trono",
      text: "Nenhum destes quatro escolhe o próprio fim. Jeoacaz é posto pelo povo e tirado por estrangeiro em três meses: \"Porque o rei do Egito o depôs em Jerusalém, e condenou a terra à contribuição de cem talentos de prata e um talento de ouro\" (2Cr 36:3) — Jeremias o chama Salum e diz que não voltaria \"nunca mais\" (Jr 22:11-12). Jeoiaquim é nomeado por Necó, que lhe troca até o nome (2Cr 36:4), e acaba amarrado: \"Subiu, pois, contra ele Nabucodonosor, rei de babilônia, e o amarrou com cadeias, para o levar a babilônia\" (2Cr 36:6). Joaquim reina três meses e dez dias com oito anos de idade — Reis diz dezoito (2Rs 24:8) — e é levado \"com os mais preciosos vasos da casa do SENHOR\" (2Cr 36:10). Zedequias, o último, tem onze anos para se humilhar e não usa nenhum: \"nem se humilhou perante o profeta Jeremias, que falava da parte do Senhor. Além disto, também se rebelou contra o rei Nabucodonosor, que o tinha ajuramentado por Deus\" (2Cr 36:12-13) — quebrar aquele juramento era quebrar um juramento feito em nome do SENHOR, e Ezequiel julga o caso por esse ângulo exato (Ez 17:15-19). O livro acaba com um rei que não é de Davi e faz o que nenhum destes fez: \"despertou o Senhor o espírito de Ciro, rei da Pérsia\" (2Cr 36:22).",
    },
    homem: {
      title: "O homem do povo da terra que fez rei a Jeoacaz, o cobrador dos cem talentos, o caldeu que amarrou o rei, o escarnecedor dos mensageiros, o que matou no santuário e o judeu do cativeiro que ouviu o pregão",
      subtitle: "2Cr 36:1-23 • os homens de Judá e os homens que vieram buscá-los",
      text: "O primeiro age com pressa, sobre um corpo que acabou de chegar de Megido: \"Então o povo da terra tomou a Jeoacaz, filho de Josias, e o fez rei em lugar de seu pai, em Jerusalém\" (2Cr 36:1) — não era o mais velho, e a escolha durou três meses. O segundo aparece com balança: cem talentos de prata e um talento de ouro cobrados da terra (2Cr 36:3), e é o lavrador de Judá que paga, casa por casa, como Reis descreve (2Rs 23:35). Depois vêm os de fora, e o texto os mostra a trabalhar: um amarra o rei com cadeias (2Cr 36:6), outro escolhe os vasos que valem a pena levar (2Cr 36:10), outro entra no santuário de espada — \"o qual matou os seus jovens à espada, na casa do seu santuário, e não teve piedade nem dos jovens, nem das donzelas, nem dos velhos, nem dos decrépitos\" (2Cr 36:17). Mas o homem que decide o capítulo é o de dentro, e o que ele faz é rir: \"Eles, porém, zombaram dos mensageiros de Deus, e desprezaram as suas palavras, e mofaram dos seus profetas; até que o furor do Senhor tanto subiu contra o seu povo, que mais nenhum remédio houve\" (2Cr 36:16). Setenta anos depois, o último destes homens está longe de casa e ouve um arauto persa ler em voz alta: \"Quem há entre vós, de todo o seu povo, o Senhor seu Deus seja com ele, e suba\" (2Cr 36:23).",
    },
    anciao: {
      title: "Os chefes dos sacerdotes que contaminaram a casa, o sacerdote que serviu aos ídolos de Jeoiaquim, o velho morto no santuário e o velho de Judá levado a Babilônia",
      subtitle: "2Cr 36:14,17,20 • o clero do fim de Judá, e os que não tiveram idade para escapar",
      text: "A acusação do Cronista sobe até o alto do sacerdócio e não poupa ninguém: \"Também todos os chefes dos sacerdotes e o povo aumentavam de mais em mais as transgressões, segundo todas as abominações dos gentios; e contaminaram a casa do Senhor, que ele tinha santificado em Jerusalém\" (2Cr 36:14). Não é negligência: é o culto dos gentios celebrado dentro do santuário por quem foi ordenado para guardá-lo — Ezequiel, deportado nos mesmos anos, foi levado em visão a ver isso por dentro, os setenta anciãos com o incensário na mão numa câmara do templo (Ez 8:10-12). O juízo vem sem distinção de idade, e o versículo insiste nas quatro categorias que qualquer guerra costuma poupar: \"e não teve piedade nem dos jovens, nem das donzelas, nem dos velhos, nem dos decrépitos; a todos entregou na sua mão\" (2Cr 36:17). Quem sobrou fez a viagem: \"E os que escaparam da espada levou para babilônia; e fizeram-se servos dele e de seus filhos, até ao tempo do reino da Pérsia\" (2Cr 36:20) — velhos que tinham cantado na páscoa de Josias saíram a pé para morrer numa terra em que ninguém os enterraria com os pais.",
    },
    servo: {
      title: "O escriba dos três meses de Jeoacaz, o servo do trono de Jeoiaquim, o que pôs os vasos no templo de Babilônia, o que escolheu os mais preciosos vasos e o escriba do pregão de Ciro",
      subtitle: "2Cr 36:2-23 • os que escreveram, embalaram e leram o fim do reino",
      text: "Estes servos fazem o trabalho de registro e de embalagem de uma catástrofe. O primeiro fecha um rolo com quase nada dentro: \"Tinha Jeoacaz a idade de vinte e três anos, quando começou a reinar; e três meses reinou em Jerusalém\" (2Cr 36:2). O segundo empacota: \"Também alguns dos vasos da casa do SENHOR levou Nabucodonosor a babilônia, e pô-los no seu templo em babilônia\" (2Cr 36:7) — os utensílios do culto do Deus vivo arrumados na prateleira de outro deus, o que a Antiguidade entendia como prova de que aquele deus vencera. Foram esses mesmos vasos que Belsazar mandou trazer para uma festa, e a mão escreveu na parede naquela noite (Dn 5:2-5). O terceiro faz a seleção do segundo saque: \"e mandou trazê-lo a babilônia, com os mais preciosos vasos da casa do SENHOR\" (2Cr 36:10). E o último, setenta anos e um império depois, escreve o texto que desfaz tudo isto: Ciro \"fez passar pregão por todo o seu reino, como também por escrito\" (2Cr 36:22) — o mesmo decreto que mandaria devolver a Judá \"os utensílios da casa do Senhor, que Nabucodonosor tinha trazido de Jerusalém\", cinco mil e quatrocentas peças contadas uma a uma (Ed 1:7-11).",
    },
    mulherComum: {
      title: "A mulher de Judá que seguiu as abominações dos gentios, a donzela morta na casa do santuário, a que ficou sobre os escombros e a que foi levada a Babilônia",
      subtitle: "2Cr 36:14,17-20 • as quatro posições em que este capítulo põe as mulheres de Jerusalém",
      text: "A primeira está dentro da casa de Deus fazendo o que ali não se faz: \"Também todos os chefes dos sacerdotes e o povo aumentavam de mais em mais as transgressões, segundo todas as abominações dos gentios; e contaminaram a casa do Senhor\" (2Cr 36:14) — Ezequiel, na mesma década, viu \"mulheres assentadas chorando a Tamuz\" à porta do norte do templo (Ez 8:14), e Jeremias ouviu delas a defesa do culto da rainha dos céus, com os bolos e as libações (Jr 44:19). A segunda é a que o versículo mais duro do livro nomeia: \"e não teve piedade nem dos jovens, nem das donzelas, nem dos velhos, nem dos decrépitos\" (2Cr 36:17) — a donzela morta na casa do santuário, no lugar onde se ia justamente para não morrer. A terceira sobrevive e fica: \"E queimaram a casa de Deus, e derrubaram os muros de Jerusalém, e todos os seus palácios queimaram a fogo\" (2Cr 36:19), e é dessa mulher em cima da pedra que Lamentações fala: \"Como está sentada solitária aquela cidade, antes tão populosa! Tornou-se como viúva\" (Lm 1:1). A quarta entra na fila da estrada: \"E os que escaparam da espada levou para babilônia\" (2Cr 36:20) — e é dela e dos filhos dela que sairia, setenta anos depois, quem ouviria o pregão e subiria.",
    },
    patriarca: {
      title: "Jeremias, diante de quem o rei não se humilhou, e os mensageiros que Deus enviou constantemente e foram escarnecidos",
      subtitle: "2Cr 36:12,15-16,21-22 • o salão do trono, a porta da casa e a palavra que ficou de pé sobre a terra vazia",
      text: "\"E fez o que era mau aos olhos do Senhor seu Deus; nem se humilhou perante o profeta Jeremias, que falava da parte do Senhor\" (2Cr 36:12) — o Cronista mede o último rei de Judá por uma coisa só, e não é política: ele tinha a palavra de Deus falada na cara e não abaixou a cabeça. Atrás de Jeremias há uma multidão de mensageiros, e o motivo do envio é a frase mais terna deste capítulo terrível: \"E o Senhor Deus de seus pais, falou-lhes constantemente por intermédio dos mensageiros, porque se compadeceu do seu povo e da sua habitação\" (2Cr 36:15) — Deus insistiu por compaixão, e insistiu por muito tempo, \"Desde o dia em que vossos pais saíram da terra do Egito, até hoje, enviei-vos todos os meus servos, os profetas, todos os dias madrugando e enviando-os\" (Jr 7:25). A resposta é dada em três verbos que se acumulam: \"Eles, porém, zombaram dos mensageiros de Deus, e desprezaram as suas palavras, e mofaram dos seus profetas; até que o furor do Senhor tanto subiu contra o seu povo, que mais nenhum remédio houve\" (2Cr 36:16). É a mesma sequência da parábola dos lavradores maus, que acaba no filho (Mt 21:33-39). E o livro fecha mostrando que a palavra desprezada é a única coisa que sobrevive à cidade: os setenta anos se cumprem \"pela boca de Jeremias\" (2Cr 36:21), e é \"para que se cumprisse a palavra do Senhor pela boca de Jeremias\" que o espírito de um rei persa é despertado (2Cr 36:22).",
    },
    cavaleiro: {
      title: "O cavaleiro do exército dos caldeus, na estrada em que Judá foi levado",
      subtitle: "2Cr 36:6,17-20 • a escolta de três deportações e do cerco final",
      text: "Ele aparece três vezes na mesma estrada do norte, cada vez com mais gente atrás. Primeiro leva um rei: \"Subiu, pois, contra ele Nabucodonosor, rei de babilônia, e o amarrou com cadeias, para o levar a babilônia\" (2Cr 36:6). Depois leva outro rei e a nata do reino: \"E no decurso de um ano enviou o rei Nabucodonosor, e mandou trazê-lo a babilônia, com os mais preciosos vasos da casa do SENHOR\" (2Cr 36:10) — nessa leva foram Ezequiel e a corte inteira (2Rs 24:14-16; Ez 1:1-2). Na terceira já não há reino nenhum para levar: \"E os que escaparam da espada levou para babilônia; e fizeram-se servos dele e de seus filhos, até ao tempo do reino da Pérsia\" (2Cr 36:20). O Cronista não o descreve com ódio; descreve-o como instrumento, e é essa a chave do capítulo: \"Porque fez subir contra eles o rei dos caldeus\" (2Cr 36:17) — quem fez subir foi o SENHOR. O mesmo Nabucodonosor que Jeremias chamou de \"meu servo\" (Jr 25:9) e o mesmo cavalo que trouxe o exílio acabariam servindo ao prazo: setenta anos, contados até o dia em que outro império mandaria a mesma estrada de volta.",
    },
    pastor: {
      title: "O único que passou pela terra assolada, enquanto ela folgava nos seus sábados",
      subtitle: "2Cr 36:21 • setenta anos de campo de Judá sem lavrador e sem dono",
      text: "\"Para que se cumprisse a palavra do Senhor, pela boca de Jeremias, até que a terra se agradasse dos seus sábados; todos os dias da assolação repousou, até que os setenta anos se cumpriram\" (2Cr 36:21). Esta figura solitária no campo vazio é tudo o que o capítulo deixa vivo em Judá: um homem com o seu gado atravessando lavoura que ninguém semeia, entre muro caído e cerca sem dono. A lei tinha previsto exatamente esta cobrança: a terra devia descansar de sete em sete anos, e quem não a deixasse descansar veria \"Então a terra folgará nos seus sábados, todos os dias da sua assolação, e vós estareis na terra dos vossos inimigos; então a terra descansará, e folgará nos seus sábados\" (Lv 26:34-35). Setenta anos de descanso correspondem a setenta sábados sonegados — quatrocentos e noventa anos de lavoura sem folga —, e a conta fecha sozinha. O prazo tinha nome e prazo marcados desde antes: \"E toda esta terra virá a ser um deserto e um espanto; e estas nações servirão ao rei de babilônia setenta anos\" (Jr 25:11). Daniel leria justamente este número nos livros e se poria a orar por causa dele (Dn 9:2).",
    },
  },
};
