// Fichas ESPECÍFICAS por (capítulo → papel) de 2 CRÔNICAS 10–14.
// Cinco capítulos que começam numa praça e acabam numa estrada de despojo. Em
// Siquém, um herdeiro ouve dois conselhos em duas salas — os velhos que
// estiveram perante Salomão e os moços que cresceram com ele — e escolhe o
// dedo mínimo e os escorpiões; sai de lá com dez tribos a menos e com o
// cobrador dos tributos apedrejado na rua. Semaías, homem de Deus, impede a
// guerra entre irmãos, e o reino que sobrou se enche de muros, de armazéns de
// víveres, de azeite e de vinho, e de sacerdotes e levitas que largaram os
// arrabaldes e a possessão no Norte porque Jeroboão os lançou fora e fez
// sacerdotes para os altos, para os demônios e para os bezerros. No quinto ano
// sobe o Egito com mil e duzentos carros, e os escudos de ouro de Salomão saem
// pela porta e voltam feitos de cobre, guardados na câmara da guarda. Depois um
// rei de Judá se põe em pé em cima do monte de Zemaraim e prega à cara de
// oitocentos mil homens sobre a aliança de sal, os pães da proposição e o
// castiçal de ouro; e o filho dele derruba os altares dos deuses estranhos e
// enfrenta um milhão de etíopes no vale de Zefatá com uma oração de nove
// palavras. Cada figurante anônimo da cena é alguém REAL daquele capítulo.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_10_14: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- 2Cr 10
  10: {
    anciao: {
      title: "Os anciãos que estiveram perante Salomão enquanto viveu",
      subtitle: "2Cr 10:6-8, 13 • os conselheiros da sala em que estava a resposta certa",
      text: "São os homens que serviram no gabinete do reinado mais glorioso de Israel e que sobreviveram a ele: \"E tomou Roboão conselho com os anciãos, que estiveram perante Salomão seu pai, enquanto viveu, dizendo: Como aconselhais vós que se responda a este povo?\" (2Cr 10:6). A pergunta é boa e o endereço é o certo — e a resposta deles é o retrato mais curto que a Escritura faz do governo que dura: \"Se te fizeres benigno e afável para com este povo, e lhes falares boas palavras, todos os dias serão teus servos\" (2Cr 10:7). Em 1 Reis a frase é ainda mais crua — \"Se hoje fores servo deste povo, e o servires\" (1Rs 12:7) —, e é a mesma lógica que Jesus poria diante dos discípulos que disputavam lugares: \"E, qualquer que entre vós quiser ser o primeiro, seja vosso servo\" (Mt 20:27). Estes velhos sabiam o preço da corveia porque tinham ajudado a cobrá-la: a leva do Líbano, o cerco de obras, os anos de pedra e cedro. Aconselham a aliviar porque viram de perto o que o jugo pesado fez. E o texto marca o momento exato em que o reino se parte: \"Porém ele deixou o conselho que os anciãos lhe deram\" (2Cr 10:8), repetido como veredicto no dia da resposta — \"porque o rei Roboão deixara o conselho dos anciãos\" (2Cr 10:13). Eles não somem da cena; ficam atrás do trono, calados, vendo o rapaz repetir na praça o que aprendeu na outra sala."
    },
    homem: {
      title: "Jeroboão, filho de Nebate, o mensageiro que o foi buscar no Egito, Hadorão dos tributos e os israelitas que atiraram as pedras",
      subtitle: "2Cr 10 • quem voltou do exílio para falar pelo povo, quem foi mandado cobrar e quem voltou para a sua tenda",
      text: "O primeiro homem do capítulo entra pela estrada do sul. É Jeroboão, filho de Nebate, de quem o texto abre um parêntese para dizer de onde ele vinha — \"(o qual estava então no Egito para onde fugira da presença do rei Salomão), voltou do Egito\" (2Cr 10:2) — e ele não veio por conta própria, foi chamado: \"Porque enviaram a ele, e o chamaram; e vieram, Jeroboão e todo o Israel, e falaram a Roboão\" (2Cr 10:3). O mensageiro que atravessou o deserto para o buscar é o homem que fez a secessão possível: sem porta-voz, a queixa de Siquém teria sido só barulho. Depois vem o israelita que ouve a resposta áspera e dá as costas — \"Cada um à sua tenda, ó Israel!\" (2Cr 10:16) — e o seu contrário, o homem de Israel que ficou: \"Porém, quanto aos filhos de Israel, que habitavam nas cidades de Judá, sobre eles reinou Roboão\" (2Cr 10:17). E há o homem que o rei manda para o pior serviço do dia: \"Então o rei Roboão enviou a Hadorão, que tinha cargo dos tributos; porém os filhos de Israel o apedrejaram, e ele morreu\" (2Cr 10:18) — Hadorão é o Adonirão que estava sobre a leva desde Salomão (1Rs 4:6; 5:14), o rosto visível de vinte anos de trabalho forçado, e é nele que a raiva se descarrega. Quem levanta a pedra não é soldado nem chefe: é o mesmo israelita que dois versículos antes só pedia alívio. A conta da soberba do trono foi paga por um funcionário na rua, e o rei escapou de carro."
    },
    multidao: {
      title: "A congregação de todo o Israel reunida em Siquém para fazer o rei",
      subtitle: "2Cr 10:1-5, 16 • o povo que pediu alívio e saiu dando o grito antigo da secessão",
      text: "O herdeiro não é coroado em Jerusalém: tem de descer ao lugar em que Israel sempre tratou as suas contas. \"E foi Roboão a Siquém, porque todo o Israel se reunira ali, para fazê-lo rei\" (2Cr 10:1) — foi ali que Josué reunira as tribos e erguera a pedra do concerto debaixo do carvalho (Js 24:1, 26), e é ali que a coroa passa a depender de uma conversa. A queixa que trazem é concreta, e a oferta é honesta: \"Teu pai fez duro o nosso jugo; agora, pois, alivia tu a dura servidão de teu pai, e o pesado jugo que nos impôs, e nós te serviremos\" (2Cr 10:4). Ninguém pediu independência neste versículo; pediram alívio, e prometeram serviço em troca. Aceitam esperar sem tumulto — \"Daqui a três dias voltai a mim. Então o povo se foi\" (2Cr 10:5) — e voltam na data marcada. Só depois da resposta áspera é que a congregação vira secessão: \"Que parte temos nós com Davi? Já não temos herança no filho de Jessé. Cada um à sua tenda, ó Israel!\" (2Cr 10:16). É o mesmo grito que Seba, filho de Bicri, dera nos dias de Davi (2Sm 20:1), e desta vez ninguém o cala: \"Assim todo o Israel se foi para as suas tendas\"."
    },
    rei: {
      title: "Roboão, filho de Salomão, e Jeroboão, filho de Nebate, na praça de Siquém",
      subtitle: "2Cr 10 • o herdeiro que respondeu asperamente e o exilado que voltou para receber dez tribos",
      text: "Roboão faz tudo certo até o oitavo versículo: vai ao lugar do povo, ouve a queixa inteira, pede três dias e consulta os velhos. E então: \"Porém ele deixou o conselho que os anciãos lhe deram; e tomou conselho com os jovens, que haviam crescido com ele\" (2Cr 10:8). Repara-se que ele já reconta a queixa torta — onde o povo dissera \"e nós te serviremos\", ele pergunta só pelo alívio (2Cr 10:9): a pergunta que se faz decide a resposta que se recebe. No terceiro dia \"o rei lhes respondeu asperamente\" (2Cr 10:13) e transformou em decreto público a fanfarronice de câmara: \"meu pai vos castigou com açoites, porém eu vos castigarei com escorpiões\" (2Cr 10:14) — o escorpião era o azorrague de pontas de metal, e a promessa era piorar o que já se pedia para aliviar. Sobre tudo isso o cronista abre o teto sem desculpar ninguém: \"Assim o rei não deu ouvidos ao povo, porque esta mudança vinha de Deus, para que o Senhor confirmasse a sua palavra, a qual falara pelo ministério de Aías, o silonita, a Jeroboão, filho de Nebate\" (2Cr 10:15) — a soberania de Deus se serviu da estupidez do trono sem a absolver. O outro rei do quadro ainda não usa coroa: Jeroboão está ali como porta-voz, e sai de Siquém com dez tribos que Aías lhe prometera em dez pedaços de uma capa nova (1Rs 11:29-31). O primeiro reinou dezessete anos sobre o que sobrou; o segundo entrou na Bíblia como \"aquele que fez pecar a Israel\"."
    },
    servo: {
      title: "Os jovens que haviam crescido com Roboão e o escudeiro que atrelou o carro da fuga",
      subtitle: "2Cr 10:8-11, 18 • a geração da câmara do divã e o homem que segurou as rédeas na rua",
      text: "São a outra sala do capítulo, e o texto os define por uma coisa só: cresceram junto com o príncipe. \"tomou conselho com os jovens, que haviam crescido com ele, e estavam perante ele\" (2Cr 10:8) — não têm currículo, têm intimidade. O conselho que dão é uma aula de como falar grosso sem ter feito nada: \"Assim dirás a este povo, que te falou: Teu pai agravou o nosso jugo, tu porém alivia-nos; assim, pois, lhe falarás: O meu dedo mínimo é mais grosso do que os lombos de meu pai\" (2Cr 10:10). E fecham com a ameaça que partiu o reino: \"Assim que, se meu pai vos carregou de um jugo pesado, eu ainda aumentarei o vosso jugo; meu pai vos castigou com açoites, porém eu vos castigarei com escorpiões\" (2Cr 10:11). Nenhum deles governara coisa nenhuma; nenhum deles vira a leva subir ao Líbano. Vendiam ao amigo a imagem de força que ele queria de si mesmo, e é essa a diferença entre a câmara do divã e da harpa e o átrio do rolo aberto: uma sala dizia o que o rei precisava ouvir, a outra o que ele gostava de ouvir. O último servo do capítulo é o mais discreto e o mais útil: o homem que mantém o carro atrelado ao lado da praça e o entrega a tempo, quando \"o rei Roboão se esforçou para subir ao seu carro, e fugiu para Jerusalém\" (2Cr 10:18)."
    }
  },

  // ---------------------------------------------------------------- 2Cr 11
  11: {
    anciao: {
      title: "O levita que deixou os arrabaldes e a sua possessão, e o ancião de Hebrom",
      subtitle: "2Cr 11:13-14 • os cabeças de casa levítica que desceram do Norte com a casa às costas",
      text: "O cronista conta a migração como um censo de fidelidade: \"Também os sacerdotes e os levitas, que havia em todo o Israel, se reuniram a ele de todos os seus termos\" (2Cr 11:13). E, no versículo seguinte, diz o preço: \"Porque os levitas deixaram os seus arrabaldes, e a sua possessão, e vieram a Judá e a Jerusalém, porque Jeroboão e seus filhos os lançaram fora para que não ministrassem ao Senhor\" (2Cr 11:14). Arrabaldes e possessão não são figura de linguagem: a Lei dera a Levi quarenta e oito cidades com os campos de pasto ao redor, medidos a partir do muro — \"E os arrabaldes das cidades, que dareis aos levitas, desde o muro da cidade para fora, serão de mil côvados em redor\" (Nm 35:4) —, porque a tribo não recebeu herança de terra. Estes homens abriram mão do único chão que possuíam no mundo. Não foi promoção nem oportunidade: foi despejo, e a alternativa era ficar servindo aos bezerros. O ancião de Hebrom que aparece na fila das quinze cidades fortes recebe alguns deles em casa, porque Hebrom era exatamente uma dessas cidades levíticas, dada aos filhos de Arão junto com o seu campo (Js 21:11-13), e ao mesmo tempo o chão dos sepulcros dos patriarcas. É gente assim que sustenta o resumo do capítulo: \"Assim fortaleceram o reino de Judá\" (2Cr 11:17) — um reino se fortalece por quem chega tendo perdido tudo."
    },
    cavaleiro: {
      title: "O capitão de Benjamim dos cento e oitenta mil escolhidos, e os capitães postos nas cidades fortes",
      subtitle: "2Cr 11:1, 11-12 • o comandante que desistiu da guerra e o que ficou guarnecendo muralha",
      text: "Entra em cena com uma ordem de marcha já dada: \"Vindo, pois, Roboão a Jerusalém, reuniu, da casa de Judá e Benjamim, cento e oitenta mil escolhidos, destros na guerra, para pelejarem contra Israel, e para restituírem o reino a Roboão\" (2Cr 11:1). Benjamim está ali por inteiro — a tribo pequena que ficou com Judá quando as dez se foram, e que sempre entrou nas guerras de Israel com a mão pesada (Jz 20:16). O que este capitão faz de extraordinário é o que ele NÃO faz: ouve um homem de Deus mandar desmontar tudo e desmonta. \"Não subireis, nem pelejareis contra os vossos irmãos; volte cada um à sua casa; porque de mim proveio isto. E ouviram as palavras do Senhor, e desistiram de ir contra Jeroboão\" (2Cr 11:4) — é o único momento inteiramente obediente do reinado, e quem obedece é o exército, não só o trono. Desfeita a coluna de ataque, o mesmo oficial reaparece de guarnição: as quinze praças-fortes recebem comandantes e mantimento, \"e armazéns de víveres, de azeite, e de vinho\" (2Cr 11:11), e cada uma delas é equipada — \"E pôs em cada cidade paveses e lanças; fortificou-as grandemente; e Judá e Benjamim pertenceram-lhe\" (2Cr 11:12). Um capitão que não pôde reconquistar irmãos passou o resto da vida guardando o que sobrou."
    },
    homem: {
      title: "O soldado escolhido de Judá, os pedreiros das quinze cidades fortes, o armeiro do pavês e da lança e os sacerdotes que Jeroboão fez para os altos",
      subtitle: "2Cr 11 • quem baixou a arma à palavra do profeta, quem levantou muro por dez anos e quem ficou servindo aos bezerros",
      text: "O primeiro homem do capítulo está de arma na mão e pronto a matar parentes: é um dos \"cento e oitenta mil escolhidos, destros na guerra\" (2Cr 11:1). O recado do SENHOR não é dado só ao rei — tem endereço triplo, \"a Roboão, filho de Salomão, rei de Judá, e a todo o Israel, em Judá e Benjamim\" (2Cr 11:3) —, porque não bastava o trono desistir: quem tinha de largar a espada era ele. E largou. Depois o mesmo homem troca a lança pelo prumo: Belém, Etã e Tecoa na serra do sul; Bete-Zur, Socó e Adulão no vale onde Davi enfrentara o filisteu e se escondera na caverna; Gate, Maressa e Zife virados para a planície; Adoraim, Laquis e Azeca no sudoeste; \"E a Zorá, a Aijalom, e a Hebrom, que estavam em Judá e em Benjamim; cidades fortes\" (2Cr 11:10). O armeiro que enche cada uma delas cumpre um versículo curto e prático: \"E pôs em cada cidade paveses e lanças\" (2Cr 11:12) — pavês é o escudo grande, de corpo inteiro, o do soldado de linha. No fim do capítulo o quadro atravessa a fronteira e mostra o outro tipo de homem: o sacerdote de balcão do Norte, feito por decreto — \"E ele constituiu para si sacerdotes, para os altos, para os demônios, e para os bezerros, que fizera\" (2Cr 11:15). Um levita legítimo perdia a casa por não ministrar aos bezerros; este ganhava um posto por ministrar. E há ainda os filhos do rei espalhados pelas praças-fortes, cada um numa colina, longe do trono e longe uns dos outros (2Cr 11:23)."
    },
    mulherComum: {
      title: "Maalate, filha de Jerimote; Abiail, filha de Eliabe; Maaca, filha de Absalão; e a mulher da casa dos levitas na estrada do Sul",
      subtitle: "2Cr 11:14, 18-23 • as mulheres nomeadas da casa de Roboão e a que desceu do Norte com os filhos",
      text: "O cronista nomeia estas mulheres uma a uma porque em Judá o sangue da casa importa: \"E Roboão tomou para si, por mulher, a Maalate, filha de Jerimote, filho de Davi; e Abiail, filha de Eliabe, filho de Jessé\" (2Cr 11:18). As duas são casa de Davi por caminhos diferentes — Jerimote é filho do próprio rei Davi, e Eliabe é o irmão mais velho, aquele que repreendeu o menino no vale de Elá (1Sm 17:28). Depois entra a que muda a sucessão: \"E depois dela tomou a Maaca, filha de Absalão; esta lhe deu Abias, Atai, Ziza e Selomite\" (2Cr 11:20) — o sangue do filho rebelde de Davi voltando ao palácio pela porta do casamento. E o texto não esconde a preferência nem as suas consequências: \"E amava Roboão mais a Maaca, filha de Absalão, do que a todas as suas outras mulheres e concubinas; porque ele tinha tomado dezoito mulheres, e sessenta concubinas; e gerou vinte e oito filhos, e sessenta filhas\" (2Cr 11:21). O amor do rei virou política de Estado: por causa dela, Abias foi designado chefe entre os irmãos (2Cr 11:22). A última mulher do capítulo não tem nome e é a que mais perdeu: é a esposa do levita que fez a mudança para Judá no êxodo de que o texto diz \"Porque os levitas deixaram os seus arrabaldes, e a sua possessão, e vieram a Judá e a Jerusalém\" (2Cr 11:14) — saiu da casa de pedra que a família tinha havia gerações, com os filhos pela mão, atrás de um culto que o Norte proibira."
    },
    multidao: {
      title: "Os que, de todas as tribos de Israel, deram o seu coração a buscarem ao SENHOR",
      subtitle: "2Cr 11:16 • os leigos que vieram atrás dos levitas para sacrificar em Jerusalém",
      text: "Atrás dos sacerdotes e dos levitas vem gente que não tinha ofício nenhum no templo e nada a ganhar com a mudança: \"Depois desses também, de todas as tribos de Israel, os que deram o seu coração a buscarem ao Senhor Deus de Israel, vieram a Jerusalém, para oferecerem sacrifícios ao Senhor Deus de seus pais\" (2Cr 11:16). A expressão \"deram o seu coração\" é a chave — não foram arrastados por decreto nem expulsos por perseguição, decidiram. Vinham de todas as tribos, isto é, atravessavam a fronteira nova de um reino inimigo para chegar a um altar, exatamente o medo que fizera Jeroboão fundir os bezerros: se o povo subisse a Jerusalém para sacrificar, o coração dele voltaria à casa de Davi (1Rs 12:27). O cronista dá o resultado sem rodeio: \"Assim fortaleceram o reino de Judá e corroboraram a Roboão, filho de Salomão, por três anos; porque três anos andaram no caminho de Davi e Salomão\" (2Cr 11:17). Guarde o prazo. Três anos é tudo o que dura a coisa boa deste reinado — o capítulo seguinte abre virando esta mesma página: \"havendo-se fortalecido, deixou a lei do SENHOR\" (2Cr 12:1)."
    },
    pastor: {
      title: "O pastor dos campos de Belém, no talude onde a aldeia de Davi virou praça-forte",
      subtitle: "2Cr 11:6 • quem apascentava na primeira das quinze cidades que Roboão edificou",
      text: "A lista das fortalezas começa exatamente onde a casa reinante começou: \"Edificou, pois, a Belém, a Etã, e a Tecoa\" (2Cr 11:6). Belém era aldeia de pastores e de ceifeiros — o campo de Rute e de Boaz, o pasto em que Samuel achou o caçula que \"que está apascentando as ovelhas\" (1Sm 16:11) e de onde saiu o rapaz que matou o leão e o urso por causa de um cordeiro (1Sm 17:34-35). Este pastor sobe o talude com o rebanho e passa ao lado do andaime de uma torre nova: a terra do bisavô do rei virou guarnição de fronteira, com muro, capitão e depósito de azeite. A segunda cidade da lista fecha o desenho — Tecoa é o descampado seco de onde sairia, dois séculos depois, um homem que se apresentaria assim: \"As palavras de Amós, que estava entre os pastores de Tecoa\" (Am 1:1). E vale lembrar do que a mesma aldeia ainda era capaz de guardar: sobre estes montes, na noite do cumprimento, \"havia naquela mesma comarca pastores que estavam no campo, e guardavam, durante as vigílias da noite, o seu rebanho\" (Lc 2:8). Micaías o dissera de véspera: de Belém, \"pequena entre os milhares de Judá\", sairia o que havia de dominar em Israel (Mq 5:2)."
    },
    patriarca: {
      title: "Semaías, homem de Deus, e o sacerdote que veio do Norte a Judá",
      subtitle: "2Cr 11:2-4, 13 • o profeta que desmontou um exército com uma frase e os filhos de Arão que emigraram",
      text: "\"Porém a palavra do Senhor veio a Semaías, homem de Deus\" (2Cr 11:2) — é a primeira vez que este nome aparece em 2 Crônicas, e ele volta em dois momentos decisivos do reinado (2Cr 12:5, 7, 15). Aqui atravessa o campo de armas com uma ordem de três partes: \"Assim diz o Senhor: Não subireis, nem pelejareis contra os vossos irmãos; volte cada um à sua casa; porque de mim proveio isto\" (2Cr 11:4). A última cláusula é a mais difícil de engolir: o rei teria de aceitar que a perda das dez tribos não fora um acidente político a reverter, mas obra de Deus a acatar. E o milagre do capítulo está na frase seguinte, que quase se lê sem parar: \"E ouviram as palavras do Senhor, e desistiram de ir contra Jeroboão\". Cento e oitenta mil homens armados voltaram para casa por causa de uma palavra. O outro homem de Deus da cena vem andando na estrada do Norte com a família: é o sacerdote arãóida de uma das cidades levíticas de Efraim, de Manassés ou de Dã, que \"se reuniu\" a Judá porque lá já não podia ministrar (2Cr 11:13-14). Um profeta impediu uma guerra entre irmãos; e é a esses irmãos do outro lado da fronteira que este sacerdote pertencia."
    },
    rei: {
      title: "Roboão em Jerusalém e Jeroboão nos altos do Norte",
      subtitle: "2Cr 11 • o rei que obedeceu ao profeta e edificou muros, e o que fez sacerdotes para os bezerros",
      text: "Este é o melhor capítulo de Roboão, e ele o começa com a decisão errada: junta cento e oitenta mil escolhidos \"para pelejarem contra Israel, e para restituírem o reino a Roboão\" (2Cr 11:1). Ao ouvir Semaías, faz a única coisa inteiramente boa do seu reinado — desiste (2Cr 11:4). O que vem depois é competência sem alarde: \"E Roboão habitou em Jerusalém; e para defesa, edificou cidades em Judá\" (2Cr 11:5), quinze praças-fortes nomeadas uma a uma, com capitães, armazéns e armas em cada uma; e, no fim, prudência de pai de dinastia: espalha os filhos pelas cidades fortes \"e deu-lhes víveres em abundância; e lhes procurou muitas mulheres\" (2Cr 11:23) — nenhum herdeiro perto do trono, nenhum deles perto do outro. Do outro lado da fronteira está o rei que fez o contrário do que lhe fora prometido. Aías lhe oferecera casa firme como a de Davi, se andasse nos caminhos de Deus (1Rs 11:38); ele preferiu segurança de fabricação própria: \"E ele constituiu para si sacerdotes, para os altos, para os demônios, e para os bezerros, que fizera\" (2Cr 11:15), e lançou fora os levitas \"para que não ministrassem ao Senhor\" (2Cr 11:14). Roboão ganhou o reinado inteiro do capítulo pelo que não fez; Jeroboão perdeu o dele pelo que fabricou."
    },
    servo: {
      title: "O almoxarife das fortalezas, o carregador das obras, o filho dos levitas na estrada e Jeús, Samarias e Zaã, filhos de Maalate",
      subtitle: "2Cr 11:11, 19-23 • quem conferia o azeite e o vinho, quem carregava a pedra e as crianças das duas casas",
      text: "As quinze cidades não se seguram com muro: seguram-se com despensa. \"E fortificou estas fortalezas e pôs nelas capitàes, e armazéns de víveres, de azeite, e de vinho\" (2Cr 11:11) — o homem da lista em pé entre as talhas é quem decide se uma praça-forte aguenta um cerco de três meses ou de três semanas, e o capítulo seguinte vai dizer, sem piedade, que não aguentaram nada quando o Egito subiu (2Cr 12:4). Ao lado dele trabalha o carregador que empurrou pedra por dez anos de paz, de Belém a Hebrom. E há as crianças das duas casas. Na estrada do Norte vem o filho do levita que perdeu o arrabalde e a possessão, criança fazendo mudança para uma cidade que não conhece (2Cr 11:14). No palácio estão os três primeiros filhos de Roboão, nomeados e depois esquecidos: \"A qual lhe deu filhos: Jeús, Samarias e Zaã\" (2Cr 11:19) — nenhum deles reinará, porque o rei já escolheu o filho da mulher que amava: \"E Roboão designou Abias, filho de Maaca, para ser chefe e líder entre os seus irmãos, porque queria fazê-lo rei\" (2Cr 11:22). Os outros vinte e sete são despachados para as fortalezas do interior (2Cr 11:23), com comida farta e distância de sobra."
    }
  },

  // ---------------------------------------------------------------- 2Cr 12
  12: {
    anciao: {
      title: "Os príncipes de Judá que se ajuntaram em Jerusalém por causa de Sisaque",
      subtitle: "2Cr 12:5-6 • os chefes das casas paternas que se humilharam e disseram três palavras",
      text: "Estão em Jerusalém por medo, não por devoção: as quinze fortalezas caíram, o Egito está à porta e os cabeças de Judá se recolhem para dentro dos muros da capital — \"Então veio Semaías, o profeta, a Roboão e aos príncipes de Judá que se ajuntaram em Jerusalém por causa de Sisaque\" (2Cr 12:5). A sentença que ouvem é a mais simétrica da Escritura, e não deixa margem para negociação: \"Vós me deixastes a mim, por isso também eu vos deixei na mão de Sisaque\". E então acontece a única coisa que muda um juízo já pronunciado: \"Então se humilharam os príncipes de Israel, e o rei, e disseram: O Senhor é justo\" (2Cr 12:6). Ninguém alega circunstância, ninguém culpa o Egito, ninguém pede revisão da pena — concordam com a sentença. É a mesma confissão que Davi fez no salmo do seu pecado, \"para que sejas justificado quando falares\" (Sl 51:4), e é ela que abre a segunda palavra do profeta: \"Humilharam-se, não os destruirei\" (2Cr 12:7). Nada muda no cerco lá fora; muda a extensão do dano. Os mesmos príncipes reaparecem no fim do reinado ao lado de um rei de quem o texto dirá que \"não preparou o seu coração para buscar ao Senhor\" (2Cr 12:14) — o joelho dobrou uma vez, e o coração não ficou preparado."
    },
    cavaleiro: {
      title: "Os sessenta mil cavaleiros que subiram com Sisaque do Egito",
      subtitle: "2Cr 12:2-3 • a cavalaria do maior exército que já cercou Jerusalém neste livro",
      text: "O número está escrito para esmagar quem lê: \"Com mil e duzentos carros e com sessenta mil cavaleiros; e era inumerável o povo que vinha com ele do Egito, de líbios, suquitas e etíopes\" (2Cr 12:3). Não é uma expedição de castigo — é o Egito inteiro em campanha, com mercenários da Líbia, do deserto e da Núbia atrás dos carros. Sisaque é o faraó que uma geração antes dera asilo a Jeroboão quando ele fugia de Salomão (1Rs 11:40); volta agora como cobrador. E a cavalaria não encontra resistência: \"E tomou as cidades fortificadas, que Judá tinha; e chegou até Jerusalém\" (2Cr 12:4) — as quinze praças-fortes com capitães, paveses e lanças do capítulo anterior não seguraram o Egito nem uma semana. O cronista, porém, não deixa ninguém explicar a derrota pela contagem de carros; a razão está entre parênteses, no versículo em que a coluna aparece: \"no quinto ano do rei Roboão, Sisaque, rei do Egito, subiu contra Jerusalém (porque tinham transgredido contra o Senhor)\" (2Cr 12:2). Sessenta mil cavaleiros são o instrumento, não a causa."
    },
    homem: {
      title: "Os líbios, os suquitas e os etíopes do exército de Sisaque, os defensores das cidades fortificadas e os carregadores do despojo",
      subtitle: "2Cr 12 • o povo sem número que veio com o Egito e os homens de Judá que ficaram no caminho dele",
      text: "\"era inumerável o povo que vinha com ele do Egito, de líbios, suquitas e etíopes\" (2Cr 12:3). Os líbios vêm do deserto ocidental; os suquitas são mercenários do sul, gente de tenda; os etíopes descem da Núbia, e é um exército como este que Judá voltará a ver dois capítulos adiante, com Zerá, e desta vez cairá (2Cr 14:9-12). Do outro lado estão os homens de Judá que guarneciam Belém, Laquis, Azeca e Adoraim: o defensor caído à porta que ele mesmo ajudara a levantar dez anos antes e o morador que ficou vivo entre as pedras da sua cidade, porque \"tomou as cidades fortificadas, que Judá tinha\" (2Cr 12:4). O último homem do quadro atravessa o pátio do templo com uma carga nas costas: \"tomou os tesouros da casa do Senhor, e os tesouros da casa do rei; levou tudo; também tomou os escudos de ouro, que Salomão fizera\" (2Cr 12:9). Aqueles escudos eram duzentos paveses e trezentos escudos de ouro batido, pendurados na casa do bosque do Líbano (1Rs 10:16-17) — quarenta anos de glória saindo pela porta ao ombro de um estrangeiro anônimo."
    },
    mulherComum: {
      title: "Naamá, a amonita, mãe do rei, na fórmula que fecha o reinado",
      subtitle: "2Cr 12:13 • a rainha-mãe nomeada no mesmo versículo da cidade que o SENHOR escolheu",
      text: "O cronista põe as duas informações no mesmo fôlego, e o contraste é o comentário: \"reinou dezessete anos em Jerusalém, a cidade que o Senhor escolheu, dentre todas as tribos de Israel, para pôr ali o seu nome; e era o nome de sua mãe Naamá, amonita\" (2Cr 12:13). A cidade escolhida por Deus, e no trono dela um filho de mulher de Amom. Naamá era uma das estrangeiras que Salomão amou, das nações de que fora dito \"perverterão o vosso coração para seguirdes os seus deuses\" (1Rs 11:1-2) — e o mesmo rei que edificou um alto \"a Moloque, a abominação dos filhos de Amom\" (1Rs 11:7) teve por herdeiro o filho dela. A advertência não é sobre origem: Rute, a moabita, está na genealogia de Davi, e Judá receberá tributo dos árabes sem escândalo nenhum. É sobre o culto que entra em casa junto com o casamento, e a Escritura anota o nome duas vezes no relato paralelo (1Rs 14:21, 31) para que ninguém o perca. É esta a mulher que criou o rapaz que ouviu a sala errada em Siquém."
    },
    patriarca: {
      title: "Semaías, o profeta, e Ido, o vidente, que escreveram os atos de Roboão",
      subtitle: "2Cr 12:5-8, 15 • o homem que trouxe as duas palavras do cerco e o que guardou o reinado por escrito",
      text: "Semaías volta ao capítulo no pior momento e diz a coisa mais dura: \"Assim diz o Senhor: Vós me deixastes a mim, por isso também eu vos deixei na mão de Sisaque\" (2Cr 12:5). Quando o rei e os príncipes se humilham, ele recebe uma segunda palavra — e é aqui que se aprende o que é misericórdia sem anistia: \"Humilharam-se, não os destruirei; antes em breve lhes darei algum socorro, para que o meu furor não se derrame sobre Jerusalém, por mão de Sisaque\" (2Cr 12:7). \"Algum socorro\" é uma expressão contida de propósito, porque a sentença continua de pé em outra medida: \"Porém serão seus servos; para que conheçam a diferença da minha servidão e da servidão dos reinos da terra\" (2Cr 12:8). Judá não é livrado do jugo; é posto a comparar os dois jugos, o de Deus e o do Egito — a mesma lição que Jesus resumiria num convite: \"o meu jugo é suave e o meu fardo é leve\" (Mt 11:30). O segundo profeta do capítulo nunca fala: escreve. \"Os atos, pois, de Roboão, assim os primeiros, como os últimos, porventura não estão escritos nos livros de Semaías, o profeta, e de Ido, o vidente, na relação das genealogias?\" (2Cr 12:15). Ido é o mesmo cuja história guardará o sermão inteiro de Abias (2Cr 13:22) — em Judá, quem repreendia o rei era também quem arquivava o reinado."
    },
    rei: {
      title: "Roboão de Judá e Sisaque, rei do Egito",
      subtitle: "2Cr 12 • o rei que se fortaleceu e deixou a lei, e o faraó que trocou o ouro do templo por cobre na câmara da guarda",
      text: "O versículo de abertura não fala de fraqueza, fala de força: \"Sucedeu que, havendo Roboão confirmado o reino, e havendo-se fortalecido, deixou a lei do SENHOR, e com ele todo o Israel\" (2Cr 12:1). O perigo não veio do cerco, veio da estabilidade — e a conta chega no quinto ano, quando os três bons anos já tinham passado havia dois. Sisaque sobe, toma tudo o que Judá fortificara e para diante de Jerusalém; a cidade não é destruída, é esvaziada: \"levou tudo; também tomou os escudos de ouro, que Salomão fizera\" (2Cr 12:9). O que Roboão faz em seguida é o retrato mais exato de um reino rebaixado que a Escritura desenhou: \"E fez o rei Roboão em lugar deles escudos de cobre, e os entregou na mão dos chefes da guarda, que guardavam a porta da casa do rei\" (2Cr 12:10). A pompa continua; o metal, não. Ainda assim, a humilhação do capítulo é real e é registrada como tal: \"E humilhando-se ele, a ira do Senhor se desviou dele, para que não o destruísse de todo; porque em Judá ainda havia boas coisas\" (2Cr 12:12) — o motivo final da clemência não é o mérito do rei, é o resto de bem que havia no povo. E o veredicto sobre a vida inteira não é sobre um ato, é sobre uma omissão: \"E fez o que era mau; porquanto não preparou o seu coração para buscar ao Senhor\" (2Cr 12:14). Não preparar já é fazer."
    },
    servo: {
      title: "Os chefes da guarda que levavam e tornavam a pôr os escudos de cobre na câmara, o servo da casa do rei, o escriba das genealogias e o sepultador da cidade de Davi",
      subtitle: "2Cr 12:10-11, 15-16 • a liturgia diária de um reino que faz de conta",
      text: "É o detalhe mais triste do livro, e são servos que o executam todos os dias: \"E todas as vezes que o rei entrava na casa do Senhor, vinham os da guarda, e os levavam; depois tornavam a pô-los na câmara da guarda\" (2Cr 12:11). Tirar do arcaz, formar no corredor, acompanhar o rei, recolher e trancar — a mesma cerimônia que se fazia com os escudos de ouro batido de Salomão (1Rs 10:16-17), agora feita com cobre. Ninguém mente em voz alta; simplesmente se continua o rito como se nada tivesse mudado, e é a guarda que carrega essa ficção nos braços, entrada por entrada. Ao lado dela trabalha o servo da casa do rei que viu o ouro atravessar a porta na direção contrária. Depois vem o escriba que arquiva o reinado inteiro \"na relação das genealogias\" (2Cr 12:15) — em Judá até a decadência era registrada com método. E, no fim, os homens que abrem a porta de pedra na encosta: \"E Roboão dormiu com seus pais, e foi sepultado na cidade de Davi; e Abias, seu filho, reinou em seu lugar\" (2Cr 12:16). O rei que fugiu de Siquém num carro atrelado às pressas é enterrado, dezessete anos depois, no jazigo da casa que ele quase perdeu inteira."
    }
  },

  // ---------------------------------------------------------------- 2Cr 13
  13: {
    anciao: {
      title: "O levita que se ocupa na sua obra e o príncipe de Judá diante do trono de Abias",
      subtitle: "2Cr 13:10 • a escala de serviço que o rei alega como prova no meio de um campo de batalha",
      text: "O sermão de Zemaraim tem um argumento que não se ouve em nenhuma outra arenga militar da Escritura: o rei prova a legitimidade do seu reino pela escala de serviço do templo. \"Porém, quanto a nós, o Senhor é nosso Deus, e nunca o deixamos; e os sacerdotes que ministram ao Senhor são filhos de Arão, e os levitas se ocupam na sua obra\" (2Cr 13:10). \"Ocupam-se na sua obra\" é linguagem técnica de turno — as vinte e quatro turmas que Davi organizara, os porteiros por portas, os cantores por horários, os tesoureiros por câmaras (1Cr 23—26). Contra o sacerdócio comprado do Norte, Judá aponta para um serviço que continua acontecendo às seis da manhã e às seis da tarde, com ou sem guerra. Este levita é o homem daquela escala: não pega em arma no capítulo, e é ele que o rei cita como fiador. Ao lado dele está o príncipe de Judá, o cabeça de casa paterna que fica em Jerusalém enquanto os quatrocentos mil descem à montanha de Efraim. A vitória do capítulo será creditada exatamente a essa continuidade obstinada: \"os filhos de Judá prevaleceram, porque confiaram no Senhor Deus de seus pais\" (2Cr 13:18)."
    },
    homem: {
      title: "O guerreiro valente de Judá, o escolhido de Israel, os filhos de Belial que seguiram Jeroboão, o pretendente ao sacerdócio e os homens da emboscada",
      subtitle: "2Cr 13 • os dois exércitos do vale, o sacerdote de balcão do Norte e o morador de Betel",
      text: "A conta é de dois para um: \"E Abias ordenou a peleja com um exército de valentes guerreiros, quatrocentos mil homens escolhidos; e Jeroboão dispôs contra ele a batalha com oitocentos mil homens escolhidos, todos homens corajosos\" (2Cr 13:3) — o texto não diminui o inimigo, chama-o de corajoso. Dentro daquele arraial, porém, há gente que o rei de Judá nomeia com desprezo histórico: \"E ajuntaram-se a ele homens vadios, filhos de Belial; e fortificaram-se contra Roboão, filho de Salomão, sendo Roboão ainda jovem, e terno de coração, e não lhes podia resistir\" (2Cr 13:7). E há o homem que resume o culto do Norte numa transação: \"Qualquer que vem a consagrar-se com um novilho e sete carneiros logo se faz sacerdote daqueles que não são deuses\" (2Cr 13:9) — o pretendente chega com o gado da taxa de posse e sai ordenado, num sacerdócio em que o preço substituiu a linhagem. Depois vêm os homens da emboscada: \"Mas Jeroboão armou uma emboscada, para dar sobre eles pela retaguarda; de maneira que estavam em frente de Judá e a emboscada por detrás deles\" (2Cr 13:13). O que Judá faz cercado é a coisa mais improvável: \"então clamaram ao Senhor; e os sacerdotes tocaram as trombetas\" (2Cr 13:14), e é o grito dos homens de Judá que abre a matança — \"E os homens de Judá gritaram\" (2Cr 13:15). No fim, o chão do quadro é do escolhido de Israel: \"porque caíram feridos de Israel quinhentos mil homens escolhidos\" (2Cr 13:17), mais do que Judá tinha em armas. O último homem do capítulo está de joelhos à beira da estrada, em Betel, quando o rei de Judá passa e toma a cidade do bezerro (2Cr 13:19)."
    },
    mulherComum: {
      title: "Micaía, filha de Uriel de Gibeá, e as catorze mulheres da casa de Abias",
      subtitle: "2Cr 13:2, 21 • a rainha-mãe do sermão de Zemaraim e a casa que se fortificou em três anos",
      text: "\"Três anos reinou em Jerusalém; e era o nome de sua mãe Micaía, filha de Uriel de Gibeá; e houve guerra entre Abias e Jeroboão\" (2Cr 13:2). Micaía, filha de Uriel de Gibeá, é o nome que o cronista escolhe aqui; em 2Cr 11:20 a mãe de Abias é chamada Maaca, filha de Absalão, e a tradição judaica junta as duas pontas fazendo de Micaía a filha que Tamar, a filha de Absalão (2Sm 14:27), teria tido com Uriel de Gibeá — de modo que Absalão é o avô, e a fórmula \"filha de Absalão\" o designa como ascendente. Gibeá é cidade de Benjamim, a de Saul e a do crime de Juízes 19 — a rainha-mãe deste rei vem do lugar mais escuro do livro dos Juízes. A outra ponta do capítulo é a casa: \"Abias, porém, se fortificou, e tomou para si catorze mulheres, e gerou vinte e dois filhos e dezesseis filhas\" (2Cr 13:21). Trinta e oito filhos em três anos de reinado é um homem construindo dinastia com pressa, logo depois de pregar sobre a soberania dada a Davi \"para sempre\" por uma aliança de sal (2Cr 13:5). Ele morre no capítulo seguinte, e quem reina é Asa (2Cr 14:1)."
    },
    patriarca: {
      title: "Os sacerdotes com as trombetas de alarme e Ido, o profeta que guardou o sermão",
      subtitle: "2Cr 13:12, 14, 22 • o único exército da Escritura cuja primeira arma é um sopro",
      text: "O rei os aponta antes da batalha como se aponta a artilharia: \"E eis que Deus está conosco, à nossa frente, como também os seus sacerdotes, tocando com as trombetas, para dar alarme contra vós. Ó filhos de Israel, não pelejeis contra o Senhor Deus de vossos pais; porque não prosperareis\" (2Cr 13:12). As duas trombetas de prata batida são dos filhos de Arão, e a lei diz exatamente para que servem na guerra: \"E, quando na vossa terra sairdes a pelejar contra o inimigo, que vos oprime, também tocareis as trombetas retinindo, e perante o Senhor vosso Deus haverá lembrança de vós, e sereis salvos de vossos inimigos\" (Nm 10:9). Não é fanfarra: é memorial. E é assim que a batalha começa, com Judá cercado por diante e por detrás: \"então clamaram ao Senhor; e os sacerdotes tocaram as trombetas\" (2Cr 13:14). O que vem depois não tem tática nenhuma: \"gritando os homens de Judá, Deus feriu a Jeroboão e a todo o Israel diante de Abias e de Judá\" (2Cr 13:15). O outro profeta do capítulo trabalha depois, com pena e tinta, e é a razão de este sermão ter chegado até nós: \"Os demais atos de Abias, tanto os seus caminhos como as suas palavras, estão escritos na história do profeta Ido\" (2Cr 13:22) — \"as suas palavras\": é o único rei destes cinco capítulos de quem o arquivo guardou o discurso."
    },
    rebanho: {
      title: "O novilho e os sete carneiros com que se comprava o sacerdócio no Norte",
      subtitle: "2Cr 13:9 • a taxa de posse de um ofício que em Judá era de nascimento",
      text: "Este gado não vai para nenhum altar do SENHOR: é preço de cargo. \"Não lançastes vós fora os sacerdotes do Senhor, os filhos de Arão, e os levitas, e não fizestes para vós sacerdotes, como os povos das outras terras? Qualquer que vem a consagrar-se com um novilho e sete carneiros logo se faz sacerdote daqueles que não são deuses\" (2Cr 13:9). O detalhe cruel é que os números vêm da própria lei: a consagração de Arão e dos seus filhos pedia um novilho e dois carneiros, com sete dias de rito, sangue na orelha, no polegar e no dedo do pé, e a ordenação feita por Moisés diante da porta da tenda (Êx 29:1-35; Lv 8). No Norte a liturgia virou tabela de preços — quem trouxesse os animais entrava, viesse da tribo que viesse, porque Jeroboão \"constituiu sacerdotes dos mais baixos do povo, que não eram dos filhos de Levi\" (1Rs 12:31). É a definição mais precisa de simonia antes de Simão o mago querer comprar o dom de Deus com dinheiro (At 8:18-20). Do outro lado do vale, os sacerdotes de Judá não pagaram nada por estarem ali: nasceram de Arão, e é isso que o rei alega."
    },
    rei: {
      title: "Abias, rei de Judá, em pé sobre o monte de Zemaraim, e Jeroboão, filho de Nebate",
      subtitle: "2Cr 13 • o rei que pregou ao exército inimigo antes de pelejar e o servo de Salomão que morreu ferido de Deus",
      text: "Nenhum outro rei de Israel fez o que este fez: \"E pôs-se Abias em pé em cima do monte de Zemaraim, que está na montanha de Efraim, e disse: Ouvi-me, Jeroboão e todo o Israel\" (2Cr 13:4). O argumento é inteiro teológico. Primeiro o direito: \"o Senhor Deus de Israel deu para sempre a Davi a soberania sobre Israel, a ele e a seus filhos, por uma aliança de sal\" (2Cr 13:5) — sal é o que não apodrece, a cláusula que acompanha toda oferta no altar (Lv 2:13) e o pacto sacerdotal perpétuo (Nm 18:19). Depois a acusação, e a palavra decisiva é \"servo\": \"Contudo levantou-se Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, e se rebelou contra seu senhor\" (2Cr 13:6). Depois a comparação de cultos: os bezerros de ouro e o sacerdócio comprado de um lado; do outro, holocaustos cada manhã e cada tarde, \"incenso aromático, com os pães da proposição sobre a mesa pura, e o castiçal de ouro\" (2Cr 13:11). E a conclusão gritada do alto: \"E eis que Deus está conosco, à nossa frente\" (2Cr 13:12). A resposta de Jeroboão é uma emboscada pela retaguarda, e o desfecho não é de Abias: \"Deus feriu a Jeroboão e a todo o Israel\" (2Cr 13:15). O homem que partiu o reino sai do livro num único versículo: \"E Jeroboão não recobrou mais o seu poder nos dias de Abias; porém o Senhor o feriu, e morreu\" (2Cr 13:20)."
    },
    servo: {
      title: "O servo do arraial de Jeroboão, o escriba das genealogias e os filhos da casa de Abias",
      subtitle: "2Cr 13:20-22 • quem ficou junto ao rei ferido, quem copiou o sermão e as crianças dos três anos",
      text: "O último servo do Norte aparece numa cena de fogueira baixa: o arraial recolhido, o bezerro de ouro ainda de pé ao lado da tenda e sem socorrer ninguém, e o rei no chão — \"porém o Senhor o feriu, e morreu\" (2Cr 13:20). É o mesmo desfecho que Aías anunciara à mulher disfarçada em Siló (1Rs 14:10-11): a casa que se fez com bezerros não segurou nem o homem que a fez. Do lado de Judá, o serviço é outro. Há o escriba que passa a limpo, na casa dos rolos, o discurso inteiro de Zemaraim, para que ele fique guardado \"na história do profeta Ido\" (2Cr 13:22) — sem esse trabalho de copista não haveria capítulo 13. E há as crianças da casa que o rei construiu com pressa: \"Abias, porém, se fortificou, e tomou para si catorze mulheres, e gerou vinte e dois filhos e dezesseis filhas\" (2Cr 13:21). Trinta e oito filhos em três anos de reinado, e o herdeiro que interessa ao livro é um só: Asa, que abre o capítulo seguinte derrubando os altares que o pai deixou de pé (2Cr 14:3)."
    }
  },

  // ---------------------------------------------------------------- 2Cr 14
  14: {
    anciao: {
      title: "O ancião de Judá dos dez anos em que a terra esteve em paz",
      subtitle: "2Cr 14:1-5 • o cabeça de casa paterna que viu três reinados e uma reforma começar do altar para fora",
      text: "Este velho enterrou Abias e viu subir um menino: \"E Abias dormiu com seus pais, e o sepultaram na cidade de Davi, e Asa, seu filho, reinou em seu lugar; nos seus dias esteve a terra em paz dez anos\" (2Cr 14:1). Ele tem idade para se lembrar de Siquém, do apedrejamento de Hadorão, dos escudos de ouro saindo pela porta do templo e voltando de cobre, e da montanha de Efraim cheia de mortos. Dez anos sem guerra é coisa que a geração dele nunca tinha visto. E o que vê a seguir é raro no desfile dos reis, um veredicto sem ressalva: \"E Asa fez o que era bom e reto aos olhos do Senhor seu Deus\" (2Cr 14:2). O bom e reto tem verbos, e todos são de demolição — \"Porque tirou os altares dos deuses estranhos, e os altos; e quebrou as imagens, e cortou os bosques\" (2Cr 14:3) — e um único verbo de construção, que é o que dá sentido aos outros: \"E mandou a Judá que buscasse ao Senhor Deus de seus pais, e que observasse a lei e o mandamento\" (2Cr 14:4). O ancião é quem responde por uma casa inteira nessa ordem: ele é que tem de mandar tirar do quintal da família o poste sagrado a que a avó levava a primeira cria. O resultado é anotado como consequência, não como coincidência: \"e sob ele o reino esteve em paz\" (2Cr 14:5)."
    },
    cavaleiro: {
      title: "O capitão do exército de Asa e o cavaleiro dos trezentos carros de Zerá, o etíope",
      subtitle: "2Cr 14:8-12 • quinhentos e oitenta mil homens de um lado, um milhão e trezentos carros do outro",
      text: "O capitão de Judá comanda a maior força que este livro põe em campo pela casa de Davi: \"Tinha Asa um exército de trezentos mil de Judá, que traziam pavês e lança; e duzentos e oitenta mil de Benjamim, que traziam escudo e atiravam com arco; todos estes eram homens valentes\" (2Cr 14:8) — duas tribos, duas maneiras de pelejar, quinhentos e oitenta mil homens. E ainda assim é pouco: \"E Zerá, o etíope, saiu contra eles, com um exército de um milhão e com trezentos carros, e chegou até Maressa\" (2Cr 14:9) — o maior número que a Escritura põe num exército contra Judá, e Maressa é justamente uma das quinze cidades que Roboão fortificara três capítulos antes (2Cr 11:8). O carro de guerra era a arma que Judá não tinha, o mesmo terror que impedira as tribos de tomar os vales na conquista (Jz 1:19). Aqui ele não serve de nada: \"E o Senhor feriu os etíopes diante de Asa e diante de Judá; e os etíopes fugiram\" (2Cr 14:12). A cavalaria de Zerá acaba no chão do vale de Zefatá, e a única coisa que o texto credita a Judá antes do desfecho é uma oração de joelhos (2Cr 14:11). Guarde a lição, porque o próprio Asa a esquecerá: dois capítulos adiante ele comprará cavalaria estrangeira com a prata do templo, e ouvirá de Hanani exatamente esta cena de volta na cara (2Cr 16:8)."
    },
    homem: {
      title: "Os derrubadores dos altos e dos bosques, os edificadores dos muros, o pavesado de Judá, o frecheiro de Benjamim e os saqueadores de Gerar",
      subtitle: "2Cr 14 • as mãos que fizeram a reforma, as que levantaram torre em tempo de paz e as que voltaram carregadas",
      text: "A reforma de Asa é trabalho braçal, e são estes homens que a executam: \"Porque tirou os altares dos deuses estranhos, e os altos; e quebrou as imagens, e cortou os bosques\" (2Cr 14:3), e a limpeza não fica na capital — \"Também tirou de todas as cidades de Judá os altos e as imagens\" (2Cr 14:5). Cortar o bosque é derrubar o poste de Aserá plantado no outeiro, o culto que na cabeça do povo dava chuva e cria; quem empunha o machado está mexendo com a religião da própria aldeia. Depois os mesmos homens trocam o machado pelo prumo, porque o rei sabe que a paz é uma janela e não um estado: \"Edifiquemos estas cidades, e cerquemo-las de muros e torres, portas e ferrolhos, enquanto a terra ainda é nossa, pois buscamos ao Senhor nosso Deus; buscamo-lo, e deu-nos repouso de todos os lados. Edificaram, pois, e prosperaram\" (2Cr 14:7). No campo de armas eles se dividem em dois ofícios: o pavesado de Judá, com o escudo de corpo inteiro e a lança, e o frecheiro de Benjamim, que traz escudo e atira com arco (2Cr 14:8) — Benjamim é a tribo do arco e da funda desde os canhotos de Juízes (Jz 20:16) e desde os parentes de Saul que atiravam com ambas as mãos (1Cr 12:2). No fim, a estrada de volta: \"E Asa, e o povo que estava com ele os perseguiram até Gerar\" (2Cr 14:13), e as cidades ao redor caem sem peleja, \"porque o terror do Senhor veio sobre elas; e saquearam todas as cidades, porque havia nelas muita presa\" (2Cr 14:14)."
    },
    multidao: {
      title: "O povo de Judá a quem o rei mandou buscar ao SENHOR, e que voltou de Gerar com o despojo",
      subtitle: "2Cr 14:4, 15 • a congregação que ouviu a ordem na praça e subiu a Jerusalém atrás do gado",
      text: "A ordem que este povo recebe é a mais simples do capítulo e a que sustenta todo o resto: \"E mandou a Judá que buscasse ao Senhor Deus de seus pais, e que observasse a lei e o mandamento\" (2Cr 14:4) — primeiro buscar, depois observar; o afeto antes da regra, e a regra logo em seguida. É este mesmo povo que aparece na praça diante do livro da lei, e é dele que Asa cobra a obra dos muros no plural, incluindo-se na conta: \"Edifiquemos estas cidades\" (2Cr 14:7). Dez anos depois eles estão no vale de Zefatá, e o rei que os contou por tribo não cita um só deles na oração — fala como quem não tem exército: \"Senhor, nada para ti é ajudar, quer o poderoso quer o de nenhuma força\" (2Cr 14:11). A alegria da última cena é deles: \"Também feriram as malhadas do gado; e levaram ovelhas em abundância, e camelos, e voltaram para Jerusalém\" (2Cr 14:15). O reino que abriu este bloco vendo o seu rei fugir de Siquém num carro fecha-o subindo a pé, com o despojo do maior exército da terra atrás. E o cronista já prepara o capítulo seguinte: esse gado não ficará nos currais de Judá — setecentos bois e sete mil ovelhas dele irão para o altar no dia do juramento do terceiro mês (2Cr 15:11)."
    },
    pastor: {
      title: "O pastor das cidades de Judá sem um alto de pé e o que tocou o despojo de Gerar pela estrada",
      subtitle: "2Cr 14:5, 15 • a clareira aberta pelo machado do rei e o rebanho tomado nas malhadas do gado",
      text: "O primeiro pastor vive a consequência prática da reforma: \"Também tirou de todas as cidades de Judá os altos e as imagens; e sob ele o reino esteve em paz\" (2Cr 14:5). O alto era o outeiro do lado da aldeia, com o altar de pedra e o poste sagrado — o lugar aonde o pastor levava a primeira cria do ano pedindo chuva e crescimento. Tirado o alto, ele continua a subir o mesmo monte com o mesmo rebanho, e não há mais nada lá em cima para onde olhar senão o céu: o culto foi obrigado a descer da colina e a ir para Jerusalém, ou para lugar nenhum. O segundo pastor está na última cena do bloco, tocando pela estrada animais que não são dele: \"Também feriram as malhadas do gado; e levaram ovelhas em abundância, e camelos, e voltaram para Jerusalém\" (2Cr 14:15). Malhada é o curral de campo, o cercado onde o gado nômade dorme; os arredores de Gerar eram terra de pastagem desde os dias em que Abraão e Isaque cavaram poços por ali e discutiram com os pastores de Abimeleque (Gn 20:1; 26:17-22). Os camelos indicam que parte do despojo veio dos acampamentos árabes que seguiam o exército etíope."
    },
    patriarca: {
      title: "O sacerdote do altar que Asa achou e o que leu o livro da lei na praça",
      subtitle: "2Cr 14:2, 4 • o serviço que voltou a acontecer depois de dois reinados de descuido",
      text: "O veredicto do rei é dado no átrio, não no gabinete: \"E Asa fez o que era bom e reto aos olhos do Senhor seu Deus\" (2Cr 14:2) — e o primeiro sinal disso é fogo aceso no altar do holocausto, cada manhã e cada tarde, exatamente como Abias descrevera de cor no alto do monte de Zemaraim (2Cr 13:11). O sacerdote em cena é o herdeiro daquela escala: filho de Arão, de uma das turmas de Davi, servindo numa casa que Sisaque esvaziara de ouro no reinado do bisavô do rei. Ao lado dele está o rolo, porque a reforma de Asa não é só demolição: \"E mandou a Judá que buscasse ao Senhor Deus de seus pais, e que observasse a lei e o mandamento\" (2Cr 14:4). Alguém tinha de ler esse mandamento em voz alta na praça para que o povo soubesse o que estava sendo mandado — o mesmo trabalho que o neto de Asa institucionalizaria mandando príncipes, levitas e sacerdotes ensinarem de cidade em cidade \"levando consigo o livro da lei do Senhor\" (2Cr 17:9). É por causa de homens assim que o profeta Azarias, um capítulo adiante, poderá contrastar o presente com os dias em que Israel esteve \"sem sacerdote que o ensinasse, e sem lei\" (2Cr 15:3)."
    },
    rebanho: {
      title: "As ovelhas em abundância e os camelos tomados nas malhadas do gado de Gerar",
      subtitle: "2Cr 14:15 • o despojo que sobe a Jerusalém e que no capítulo seguinte vai para o altar",
      text: "O último versículo do bloco é uma estrada de volta com barulho de gado: \"Também feriram as malhadas do gado; e levaram ovelhas em abundância, e camelos, e voltaram para Jerusalém\" (2Cr 14:15). Malhadas são os currais de campo dos pastores do Neguebe, e o cronista faz questão de contar o despojo em animais, e não em prata: quem venceu um milhão de homens volta para casa tocando rebanho. Os camelos denunciam a composição do exército derrotado — as tropas nômades que acompanhavam Zerá — e são, na Escritura, a montaria do saque e do deserto (Jz 6:5; 1Sm 30:17). O detalhe teológico está no capítulo seguinte, e é ele que dá sentido a esta cena: nada disto ficou guardado. \"E no mesmo dia ofereceram em sacrifício ao Senhor, do despojo que trouxeram, setecentos bois e sete mil ovelhas\" (2Cr 15:11). A vitória tinha sido pedida de mãos vazias — \"em ti confiamos, e no teu nome viemos contra esta multidão\" (2Cr 14:11) —, e o lucro dela volta a quem a deu."
    },
    rei: {
      title: "Asa, rei de Judá, e Zerá, o etíope, no vale de Zefatá junto a Maressa",
      subtitle: "2Cr 14 • o rei que derribou os altos e orou nove palavras contra um milhão de homens",
      text: "Asa herda um reino em paz e não gasta a paz em festa: \"E edificou cidades fortificadas em Judá; porque a terra estava quieta, e não havia guerra contra ele naqueles anos; porquanto o Senhor lhe dera repouso\" (2Cr 14:6). Antes disso já tinha feito o que o pai e o avô não fizeram — tirar os altares dos deuses estranhos e os altos, quebrar as imagens, cortar os bosques (2Cr 14:3) — e mandado a Judá buscar ao SENHOR e observar a lei (2Cr 14:4). O discurso das obras mostra um homem que entende o calendário de Deus: \"Edifiquemos estas cidades, e cerquemo-las de muros e torres, portas e ferrolhos, enquanto a terra ainda é nossa\" (2Cr 14:7). E a janela se fecha: Zerá, o etíope, sobe com um milhão de homens e trezentos carros e chega a Maressa. Asa não espera atrás dos muros que acabou de levantar — sai e ordena a batalha no vale de Zefatá (2Cr 14:10). Então faz a oração que fica: \"Senhor, nada para ti é ajudar, quer o poderoso quer o de nenhuma força; ajuda-nos, pois, Senhor nosso Deus, porque em ti confiamos, e no teu nome viemos contra esta multidão. Senhor, tu és nosso Deus, não prevaleça contra ti o homem\" (2Cr 14:11). O rei que contara quinhentos e oitenta mil soldados não cita um só deles. E a resposta é ação muda: \"E o Senhor feriu os etíopes diante de Asa e diante de Judá; e os etíopes fugiram\" (2Cr 14:12) — o próprio Zerá desaparece do texto sem mais uma linha, e a explicação da derrota não é tática: \"porque foram destruídos diante do Senhor, e diante do seu exército\" (2Cr 14:13)."
    },
    servo: {
      title: "O carregador das obras de Asa e o sepultador que fechou a porta de pedra sobre Abias",
      subtitle: "2Cr 14:1, 6-7 • quem enterrou um rei de três anos e quem subiu pedra durante uma década de paz",
      text: "O bloco fecha com dois serviços humildes que emolduram tudo. O primeiro é de sepultura: \"E Abias dormiu com seus pais, e o sepultaram na cidade de Davi\" (2Cr 14:1) — o mesmo jazigo da encosta em que dois capítulos antes tinham posto Roboão (2Cr 12:16), a mesma porta de pedra rolada, o mesmo servo. Três anos de reinado, um sermão inteiro guardado por escrito, e a encosta de sempre. O segundo é de obra, e dura dez anos: \"E edificou cidades fortificadas em Judá; porque a terra estava quieta\" (2Cr 14:6). O carregador que sobe cesto de pedra pelo andaime é a figura desse decênio inteiro — paz não é ócio, é o tempo em que se levantam muros, torres, portas e ferrolhos \"enquanto a terra ainda é nossa\" (2Cr 14:7). O rei fala no plural com esses homens, e o texto lhes dá o crédito na mesma frase: \"Edificaram, pois, e prosperaram\". São esses muros que fazem Zerá parar em Maressa em vez de chegar a Jerusalém, e é esse mesmo servo que, no capítulo seguinte, entra pela porta do tesouro carregando \"prata, ouro e vasos\" (2Cr 15:18)."
    }
  }
};
