// Fichas ESPECÍFICAS por (capítulo → papel) de ESTER 1–5.
// Cinco capítulos inteiros dentro de um império pagão, na fortaleza de Susã,
// onde o nome de Deus NÃO APARECE UMA ÚNICA VEZ: não há profeta, não há altar,
// não há templo, não há oração dita em voz alta. O que vira a história são
// coincidências que o texto registra e nunca explica — uma rainha que diz não
// numa festa de bêbados; uma órfã judia dos levados com Jeconias que ninguém
// sabe que é judia; um feito anotado nas crônicas e esquecido no mesmo
// versículo em que é escrito; uma sorte lançada em Nisã que cai no último mês
// do ano e dá onze meses de prazo a um povo condenado; e uma forca de cinquenta
// côvados levantada de noite no quintal de quem morreria nela. As fichas
// apontam essas coincidências e param onde o livro para: nenhuma delas põe na
// boca de Ester ou de Mardoqueu palavras que eles não dizem.
// Cada figurante anônimo da cena é alguém REAL daquele capítulo: o copeiro dos
// copos de ouro todos diferentes uns dos outros, o escriba que escreveu o edito
// a cada província segundo a sua escrita, a serva que levava à moça tudo quanto
// ela desejava, o lançador do pur diante de Hamã, o judeu de província deitado
// em saco e cinza, o carpinteiro que serrou cinquenta côvados de madeira numa
// noite só.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_01_05: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- Et 1
  1: {
    anciao: {
      title: "Os governadores das cento e vinte e sete províncias, os nobres do banquete, os sábios que entendiam dos tempos, e Carsena e Setar entre os sete príncipes",
      subtitle: "Et 1 • as cabeças brancas de um império que se exibe por cento e oitenta dias e depois legisla sobre o que fazer com uma esposa",
      text: "Os primeiros são os homens que governam por procuração o maior território que o mundo conhecia: \"o poder da Pérsia e Média e os nobres e príncipes das províncias\" (Et 1:3), convocados a Susã para o banquete do terceiro ano do reinado. Ficam cento e oitenta dias vendo \"as riquezas da glória do seu reino, e o esplendor da sua excelente grandeza\" (Et 1:4) — meio ano de vitrine, que é exatamente o tempo que um império gasta quando não tem nada mais urgente a fazer. Os segundos são os juristas da corte: \"Então perguntou o rei aos sábios que entendiam dos tempos (porque assim se tratavam os negócios do rei na presença de todos os que sabiam a lei e o direito\" (Et 1:13). Entre eles estão Carsena e Setar, dois dos sete \"que viam a face do rei, e se assentavam como principais no reino\" (Et 1:14) — a expressão técnica do acesso irrestrito à pessoa do soberano, o mesmo privilégio que Ester não terá no capítulo 4, quando disser que \"nestes trinta dias não tenho sido chamada para ir ao rei\" (Et 4:11). Estes velhos são consultados para uma questão de estado e a questão é doméstica; deliberam sobre \"o que, segundo a lei, se devia fazer à rainha Vasti\" (Et 1:15) e produzem um edito irrevogável mandando que \"cada homem fosse senhor em sua casa\" (Et 1:22). O trono do mundo conhecido gastou o seu poder para decretar isso."
    },
    homem: {
      title: "Os príncipes da Média, os guardas de lança da fortaleza, os convidados deitados nos leitos de ouro, os que sabiam a lei e o direito — e Memucã, que transformou um desaforo em lei",
      subtitle: "Et 1 • os homens do salão de Susã, do soldado da porta ao conselheiro que ditou o primeiro decreto irrevogável do livro",
      text: "O quadro começa com os que estão em pé por ofício: os lanceiros da fortaleza de Susã, e \"todos os seus príncipes e seus servos, estando assim perante ele o poder da Pérsia e Média\" (Et 1:3). Depois vêm os convidados dos sete dias abertos a todo o povo, recostados num luxo que o texto descreve em detalhe e sem pressa: \"os leitos de ouro e de prata, sobre um pavimento de mármore vermelho, e azul, e branco, e preto\" (Et 1:6), com o beber \"por lei, sem constrangimento\" (Et 1:8) — a única lei persa deste capítulo que não obriga ninguém a nada. No fim do salão estão os sete: \"Carsena, Setar, Admata, Társis, Meres, Marsena, e Memucã, os sete príncipes dos persas e dos medos\" (Et 1:14), e é o último deles que fala. Memucã pega o não de uma mulher e o transforma em ameaça imperial: \"Não somente contra o rei pecou a rainha Vasti, porém também contra todos os príncipes, e contra todos os povos que há em todas as províncias do rei Assuero\" (Et 1:16), e adverte que \"a notícia do que fez a rainha chegará a todas as mulheres\" (Et 1:17). O capítulo fecha com os correios saindo pelas estradas: \"Então enviou cartas a todas as províncias do rei, a cada província segundo a sua escrita, e a cada povo segundo a sua língua\" (Et 1:22). A mesma máquina de escrivães, selos e cavalos voltará no capítulo 3 para condenar um povo inteiro, e no 8 para lhe devolver a vida."
    },
    mulherComum: {
      title: "A rainha Vasti, as convidadas do banquete da casa real e as senhoras da Pérsia e da Média",
      subtitle: "Et 1 • a mulher que disse não ao império inteiro, e as que ouviriam falar disso",
      text: "Vasti não é figura de glória e por isso a cena a desenha andando, de pé e sentada como qualquer pessoa: ela dá a sua própria festa, longe do vinho dos homens — \"Também a rainha Vasti deu um banquete às mulheres, na casa real do rei Assuero\" (Et 1:9). No sétimo dia, \"estando já o coração do rei alegre do vinho\" (Et 1:10), sete camareiros vêm buscá-la \"com a coroa real, para mostrar aos povos e aos príncipes a sua beleza, porque era formosa à vista\" (Et 1:11) — chamada não como rainha, mas como peça do mostruário que vinha sendo exibido havia cento e oitenta dias. A resposta cabe em cinco palavras e derruba o capítulo: \"Porém a rainha Vasti recusou vir conforme a palavra do rei\" (Et 1:12). O texto não diz o motivo, não a elogia nem a condena, e nunca mais a menciona senão como lembrança de um rei apaziguado (Et 2:1). Ao lado dela estão as convidadas da casa real e as \"senhoras da Pérsia e da Média\" (Et 1:18) que os conselheiros temem — o argumento de Memucã é inteiro sobre o que essas mulheres vão dizer aos maridos quando souberem. Um império que governa da Índia à Etiópia legislou às pressas porque teve medo de uma conversa entre esposas."
    },
    multidao: {
      title: "Todo o povo que se achava na fortaleza de Susã, desde o maior até ao menor",
      subtitle: "Et 1:5 • os sete dias em que o pátio do jardim do palácio real ficou aberto à cidade",
      text: "\"E, acabados aqueles dias, fez o rei um banquete a todo o povo que se achava na fortaleza de Susã, desde o maior até ao menor, por sete dias, no pátio do jardim do palácio real\" (Et 1:5). Esta é a única multidão realmente alegre do começo do livro, e a alegria é comprada: depois de meio ano exibindo o tesouro aos governadores, o rei abre os portões e deixa a cidade entrar. O texto se demora na decoração como quem filma devagar — as tapeçarias \"de pano branco, verde, e azul celeste, pendentes de cordões de linho fino e púrpura, e argolas de prata, e colunas de mármore\" (Et 1:6), os copos de ouro \"diferentes uns dos outros\" (Et 1:7), o vinho servido \"segundo a generosidade do rei\". É gente comum de Susã bebendo em louça do palácio. Essa mesma cidade reaparecerá duas vezes, e as duas de outro jeito: \"o rei e Hamã se assentaram a beber, porém a cidade de Susã estava confusa\" (Et 3:15), e depois \"a cidade de Susã exultou e se alegrou\" (Et 8:15). Entre um banquete e outro cabe o livro inteiro."
    },
    rei: {
      title: "Assuero, o rei que reinou desde a Índia até a Etiópia sobre cento e vinte e sete províncias",
      subtitle: "Et 1 • o homem mais poderoso do mundo conhecido, medido pelo tamanho do mapa e pelo tamanho da decisão",
      text: "A primeira coisa que o livro dá é a medida do homem: \"o Assuero que reinou desde a India até a Etiópia, sobre cento e vinte e sete províncias\" (Et 1:1), \"assentando-se o rei Assuero no trono do seu reino, que estava na fortaleza de Susã\" (Et 1:2). A segunda coisa é o que ele faz com esse poder: um banquete de cento e oitenta dias \"para mostrar as riquezas da glória do seu reino\" (Et 1:4), sete dias de festa para a cidade, e uma ordem dada com \"o coração do rei alegre do vinho\" (Et 1:10) para que tragam a mulher e a mostrem aos convidados. Recusado, o rei do mundo não sabe o que fazer e pergunta aos advogados (Et 1:13-15). O contraste é o retrato: o homem que decide sobre cento e vinte e sete províncias não decide nada sozinho — ao longo do livro ele será movido por Memucã (1:21), pelos servos que lhe serviam (2:2-4), por Hamã (3:10-11), pelo sono que foge (6:1), por Harbona (7:9) e por Ester (8:5). Nunca lhe atribuem um plano próprio; e nunca, em dez capítulos, ele menciona um deus."
    },
    servo: {
      title: "Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete camareiros — com o copeiro dos copos de ouro, o tesoureiro, o escriba do edito e o moço de estrebaria",
      subtitle: "Et 1 • os que servem no palácio no dia em que uma ordem do rei volta sem ter sido cumprida",
      text: "Os principais deste capítulo têm nome e são sete: \"mandou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete camareiros que serviam na presença do rei Assuero\" (Et 1:10). São eunucos da câmara real, gente de confiança absoluta, e o texto os nomeia um a um justamente porque vão voltar de mãos vazias: a recusa de Vasti se dá \"por meio dos camareiros\" (Et 1:12), e é diante deles que o furor sobe. Um desses nomes, Harbona, reaparece seis capítulos adiante para dizer a frase que enforca Hamã (Et 7:9) — o livro guarda os seus figurantes. Ao redor deles trabalha a casa inteira: o copeiro que enche os copos de ouro \"diferentes uns dos outros\" (Et 1:7), os oficiais encarregados de que o beber fosse \"conforme a vontade de cada um\" (Et 1:8), o tesoureiro que abre as arcas dos cento e oitenta dias, as servas do banquete de Vasti na casa real (Et 1:9), o escriba que copia o edito \"a cada província segundo a sua escrita\" (Et 1:22) e o moço de estrebaria que sela os cavalos dos correios. Um palácio inteiro em movimento por causa de uma palavra de duas letras."
    }
  },

  // ---------------------------------------------------------------- Et 2
  2: {
    anciao: {
      title: "Mardoqueu, filho de Jair, filho de Simei, filho de Quis, homem benjamita",
      subtitle: "Et 2:5-11 • o judeu que passeava cada dia diante do pátio da casa das mulheres",
      text: "\"Havia então um homem judeu na fortaleza de Susã, cujo nome era Mardoqueu, filho de Jair, filho de Simei, filho de Quis, homem benjamita\" (Et 2:5). A genealogia não é enfeite: Quis, benjamita, é o nome do pai de Saul (1Sm 9:1), e no capítulo seguinte entrará em cena um agagita, da casa do Agague que Saul poupou (1Sm 15:8-9). A rixa desses dois homens tem quatrocentos anos e nenhum dos dois a menciona. Mardoqueu é gente do cativeiro — \"Que fora transportado de Jerusalém, com os cativos que foram levados com Jeconias, rei de Judá\" (Et 2:6) —, um dos que 2 Reis vê saírem presos da cidade (2Rs 24:15). E é ele quem cria a órfã: \"Este criara a Hadassa (que é Ester, filha de seu tio), porque não tinha pai nem mãe\" (Et 2:7). Dá-lhe uma ordem que a protege e a compromete ao mesmo tempo — \"Ester, porém, não declarou o seu povo e a sua parentela, porque Mardoqueu lhe tinha ordenado que o não declarasse\" (Et 2:10) — e depois faz a única coisa que lhe resta: \"E passeava Mardoqueu cada dia diante do pátio da casa das mulheres, para se informar de como Ester passava, e do que lhe sucederia\" (Et 2:11). Um homem andando de um lado para o outro, do lado de fora de um muro, todos os dias."
    },
    homem: {
      title: "Os conselheiros do rei apaziguado, os oficiais que ajuntaram as moças nas províncias, os judeus de Susã levados com Jeconias — e Bigtã e Teres, os guardas da porta",
      subtitle: "Et 2 • os homens que inventaram o concurso, os que vieram do cativeiro e os dois que conspiraram e foram pendurados",
      text: "O capítulo começa com um remédio de cortesãos: \"Então disseram os servos do rei, que lhe serviam: Busquem-se para o rei moças virgens e formosas\" (Et 2:2), e a máquina imperial é posta a serviço disso — \"E ponha o rei oficiais em todas as províncias do seu reino, que ajuntem a todas as moças virgens e formosas, na fortaleza de Susã\" (Et 2:3). Os oficiais das províncias são estes homens: funcionários recolhendo meninas por decreto, com a mesma burocracia com que se recolhe tributo. Entre a gente de Susã estão os judeus do cativeiro, os \"levados com Jeconias, rei de Judá, o qual transportara Nabucodonosor\" (Et 2:6) — dois reinados depois do desterro, vivendo numa capital pagã, com um deles sentado à porta do rei. E no fim do capítulo entram os dois que dão ao livro o seu segredo mais bem guardado: \"dois camareiros do rei, dos guardas da porta, Bigtã e Teres, grandemente se indignaram, e procuraram atentar contra o rei Assuero\" (Et 2:21). Mardoqueu descobre, avisa por Ester, o caso é apurado, e \"ambos foram pendurados numa forca; e foi escrito nas crônicas perante o rei\" (Et 2:23). Ninguém agradece a Mardoqueu. Fica só a tinta no rolo, esperando quatro capítulos."
    },
    mulherComum: {
      title: "Ester, filha de Abiail, com as moças virgens ajuntadas em Susã, as sete moças de respeito dadas a ela e as concubinas da casa de Saasgaz",
      subtitle: "Et 2 • a casa das mulheres por dentro: doze meses de purificação, uma noite, e a segunda casa para o resto da vida",
      text: "Ester entra aqui sem escolha nenhuma: \"também levaram Ester à casa do rei, sob a custódia de Hegai, guarda das mulheres\" (Et 2:8) — o verbo é levar. O que ela faz de próprio é calar e agradar: \"E a moça pareceu formosa aos seus olhos, e alcançou graça perante ele\" (Et 2:9), e recebe os enfeites, os quinhões, \"sete moças de respeito da casa do rei\" e o melhor lugar da casa das mulheres. O regulamento é descrito com frieza administrativa: doze meses de purificação, \"seis meses com óleo de mirra, e seis meses com especiarias\" (Et 2:12), e depois uma noite — \"À tarde entrava, e pela manhã tornava à segunda casa das mulheres, sob os cuidados de Saasgaz, camareiro do rei, guarda das concubinas; não tornava mais ao rei, salvo se o rei a desejasse, e fosse chamada pelo nome\" (Et 2:14). As mulheres desta cena são as que ficaram naquela segunda casa: um dormitório de esquecidas, cada uma esperando um nome que quase nunca é chamado. Ester atravessa o mesmo caminho e faz uma coisa que nenhuma das outras fez: \"coisa nenhuma pediu, senão o que disse Hegai\" (Et 2:15). Sai dali com a coroa real na cabeça (Et 2:17) — e ainda sem dizer quem é."
    },
    multidao: {
      title: "Os príncipes e os servos do grande banquete de Ester",
      subtitle: "Et 2:18 • a festa da coroação de uma rainha judia que ninguém sabe que é judia",
      text: "\"Então o rei deu um grande banquete a todos os seus príncipes e aos seus servos; era o banquete de Ester; e deu alívio às províncias, e fez presentes segundo a generosidade do rei\" (Et 2:18). É a mesma corte do capítulo 1, no mesmo salão, com o mesmo vinho, celebrando a substituta da rainha que se recusou a comparecer. O detalhe administrativo — \"deu alívio às províncias\" — é um perdão de tributo ou de serviço decretado em honra dela: o império inteiro sente no bolso a chegada desta mulher. E ninguém ali sabe do que está falando. Nem os príncipes, nem os servos, nem o rei: \"Ester, porém, não declarava a sua parentela e o seu povo, como Mardoqueu lhe ordenara; porque Ester cumpria o mandado de Mardoqueu, como quando a criara\" (Et 2:20). Uma sala cheia de gente brindando a uma judia do cativeiro de Jeconias sem saber. Quando a informação finalmente aparecer, será numa mesa muito menor, com três pessoas, e custará a vida de um convidado (Et 7:3-6)."
    },
    rei: {
      title: "Assuero, apaziguado o furor, lembrando-se de Vasti",
      subtitle: "Et 2:1 • o rei que acorda da ira e descobre que assinou um decreto que não pode desfazer",
      text: "\"Passadas estas coisas, e apaziguado já o furor do rei Assuero, lembrou-se de Vasti, e do que fizera, e do que se tinha decretado a seu respeito\" (Et 2:1). Os três verbos são a chave: lembrou-se dela, do que ela fez e do que ele decretou — e o decreto foi escrito \"nas leis dos persas e dos medos\" para que \"não se revogue\" (Et 1:19). O homem mais poderoso do mundo está preso à própria assinatura, e a corte trata a saudade do rei como um problema de logística a ser resolvido com moças recolhidas nas províncias (Et 2:2-4). O mesmo mecanismo o prenderá outra vez no capítulo 8, quando quiser salvar os judeus e não puder revogar a carta de Hamã (Et 8:8). No fim deste capítulo ele ama Ester \"mais do que a todas as mulheres\" e lhe põe \"a coroa real na sua cabeça\" (Et 2:17) sem saber de que povo ela é — e manda pendurar dois conspiradores denunciados por um judeu de quem não se lembrará de agradecer, até uma noite de insônia quatro capítulos adiante (Et 6:1-3)."
    },
    servo: {
      title: "Hegai, guarda das mulheres; Saasgaz, guarda das concubinas; as servas do óleo de mirra; e o escriba que escreveu o feito de Mardoqueu nas crônicas",
      subtitle: "Et 2 • quem administra a casa das mulheres, e quem anotou no rolo a linha que salvaria um povo",
      text: "Hegai é o funcionário decisivo deste capítulo: \"aos cuidados de Hegai, camareiro do rei, guarda das mulheres\" (Et 2:3), e é dele o favor que muda a sorte de Ester — \"por isso se apressou a dar-lhe os seus enfeites, e os seus quinhões, como também em lhe dar sete moças de respeito da casa do rei; e a fez passar com as suas moças ao melhor lugar da casa das mulheres\" (Et 2:9). Do outro lado do corredor está Saasgaz, \"camareiro do rei, guarda das concubinas\" (Et 2:14), que administra a segunda casa — a das que já entraram e não voltam. Entre os dois trabalham as servas dos doze meses de purificação, as que carregam o óleo de mirra e as especiarias, e as que levavam à moça \"tudo quanto ela desejava, para levar consigo da casa das mulheres à casa do rei\" (Et 2:13). No último versículo entra o servo mais importante de todo o livro, e ele não tem nome, nem fala, nem sabe o que está fazendo: o escriba que registra a denúncia dos dois camareiros — \"e foi escrito nas crônicas perante o rei\" (Et 2:23). Um homem molhou a pena, escreveu uma linha e foi dormir. Quatro capítulos depois essa linha é lida em voz alta numa madrugada, e um povo inteiro não morre."
    }
  },

  // ---------------------------------------------------------------- Et 3
  3: {
    anciao: {
      title: "Os príncipes que se prostravam perante Hamã, o lançador do pur, os governadores que receberam o decreto — e Mardoqueu, que não se inclinava",
      subtitle: "Et 3 • os velhos que se curvam ao assento posto acima de todos, e o único que fica de pé",
      text: "\"Depois destas coisas o rei Assuero engrandeceu a Hamã, filho de Hamedata, agagita, e o exaltou, e pôs o seu assento acima de todos os príncipes que estavam com ele\" (Et 3:1). Os anciãos desta cena são esses príncipes rebaixados, homens de cabeça branca que se inclinam diante de um recém-chegado \"porque assim tinha ordenado o rei acerca dele\" (Et 3:2). No meio deles fica um só de pé: \"porém Mardoqueu não se inclinava nem se prostrava\". O texto nunca explica a recusa por piedade — não diz que era idolatria, não cita mandamento nenhum; a única razão registrada é a que Mardoqueu deu aos que o interrogavam dia após dia: \"porque ele lhes tinha declarado que era judeu\" (Et 3:4). Um benjamita da casa de Quis não se curva a um agagita, e o leitor de 1 Samuel 15 sabe por quê. Outro velho desta cena é o que assiste ao lançamento das sortes: \"se lançou Pur, isto é, a sorte, perante Hamã, para cada dia, e para cada mês, até ao duodécimo mês, que é o mês de Adar\" (Et 3:7) — em Nisã, o primeiro mês, e a sorte cai no último, dando onze meses de prazo a um povo já sentenciado. O livro não comenta o acaso; a Escritura comenta em outro lugar: \"A sorte se lança no regaço, mas do Senhor procede toda a determinação\" (Pv 16:33). E os últimos são os governadores das províncias que recebem a carta e não têm nada a fazer senão obedecer (Et 3:12)."
    },
    homem: {
      title: "Hamã, filho de Hamedata, o agagita; os guardas da porta do rei; os correios do decreto; e os moradores de Susã na rua confusa",
      subtitle: "Et 3 • o homem que comprou um povo por dez mil talentos e a cidade que ficou parada quando a carta saiu",
      text: "Hamã é apresentado por três palavras que valem por um capítulo inteiro de 1 Samuel: \"filho de Hamedata, agagita\" (Et 3:1) — descendente de Agague, rei dos amalequitas que Saul tomou vivo quando devia destruí-lo, e que Samuel despedaçou em Gilgal (1Sm 15:8, 33). Do outro lado do pátio está um benjamita da casa de Quis. Nenhum dos dois cita a história; ela apenas continua. O furor de Hamã não se contenta com um homem: \"teve como pouco, nos seus propósitos, o pôr as mãos só em Mardoqueu... Hamã, pois, procurou destruir a todos os judeus\" (Et 3:6). Diante do rei ele monta a acusação perfeita porque quase tudo nela é verdade: \"Existe espalhado e dividido entre os povos em todas as províncias do teu reino um povo, cujas leis são diferentes das leis de todos os povos, e que não cumpre as leis do rei\" (Et 3:8) — e nunca diz o nome do povo. Oferece dez mil talentos de prata; o rei nem pergunta quem morre: \"Então tirou o rei o anel da sua mão, e o deu a Hamã\" (Et 3:10). Os últimos homens da cena são os correios que saem com a ordem de \"destruíssem, matassem, e fizessem perecer a todos os judeus, desde o jovem até ao velho, crianças e mulheres, em um mesmo dia\" (Et 3:13), e a gente comum parada nas ruas: \"E o rei e Hamã se assentaram a beber, porém a cidade de Susã estava confusa\" (Et 3:15)."
    },
    mulherComum: {
      title: "As mulheres das províncias diante do decreto e as moradoras de Susã na cidade confusa",
      subtitle: "Et 3:13-15 • as que leram o próprio nome na lista, porque o edito não poupava nem crianças nem mulheres",
      text: "O decreto de Hamã não faz distinção nenhuma, e o texto guarda a lista por extenso: \"para que destruíssem, matassem, e fizessem perecer a todos os judeus, desde o jovem até ao velho, crianças e mulheres, em um mesmo dia, a treze do duodécimo mês (que é o mês de Adar), e que saqueassem os seus bens\" (Et 3:13). Estas são as mulheres que ouviram isso lido em praça pública, na sua própria língua, porque a carta foi enviada \"a cada província segundo a sua escrita, e a cada povo segundo a sua língua\" (Et 3:12) — a máquina do império traduziu a sentença com todo o cuidado, para que ninguém deixasse de entender. Uma cópia foi divulgada \"a todos os povos, para que estivessem preparados para aquele dia\" (Et 3:14): onze meses sabendo a data. Ao lado das judias estão as moradoras comuns de Susã, que não eram alvo de nada e mesmo assim pararam na rua — o versículo que fecha o capítulo é sobre a cidade inteira, e não só sobre os condenados: \"porém a cidade de Susã estava confusa\" (Et 3:15). Enquanto isso, na sala de cima, dois homens bebiam."
    },
    rei: {
      title: "Assuero, que tirou o anel da sua mão sem perguntar o nome do povo",
      subtitle: "Et 3:8-11 • o rei que vendeu uma nação inteira num diálogo de quatro versículos",
      text: "A cena que define este rei é curtíssima. Hamã descreve um povo sem o nomear (Et 3:8), oferece \"dez mil talentos de prata, para que entrem nos tesouros do rei\" (Et 3:9), e a resposta vem sem uma única pergunta: \"Então tirou o rei o anel da sua mão, e o deu a Hamã, filho de Hamedata, agagita, adversário dos judeus. E disse o rei a Hamã: Essa prata te é dada como também esse povo, para fazeres dele o que bem parecer aos teus olhos\" (Et 3:10-11). Ele não sabe quem vai morrer; não sabe que a própria rainha está na lista; não sabe que o homem que denunciou os conspiradores de 2:21 e salvou a sua vida está na lista. Entrega o anel, que é a assinatura do império — o mesmo anel que voltará à sua mão em 8:2 e será dado a Mardoqueu. E o capítulo fecha com a imagem mais dura que o livro tem sobre ele: \"E o rei e Hamã se assentaram a beber, porém a cidade de Susã estava confusa\" (Et 3:15). Dois homens à mesa, e uma cidade parada do lado de fora."
    },
    servo: {
      title: "Os servos da porta do rei que se inclinavam, o tesoureiro dos dez mil talentos, os escrivães do dia treze de Nisã e o moço de estrebaria dos correios",
      subtitle: "Et 3 • quem cumpre a ordem de se prostrar, quem conta a prata e quem copia a sentença em todas as escritas do império",
      text: "Os primeiros são os que perguntam, e perguntam por dias: \"Então os servos do rei, que estavam à porta do rei, disseram a Mardoqueu: Por que transgrides o mandado do rei? Sucedeu, pois, que, dizendo-lhe eles isto, dia após dia, e não lhes dando ele ouvidos, o fizeram saber a Hamã\" (Et 3:3-4). Não são inimigos: são colegas de porta, incomodados com o único homem que não se curva, e é a denúncia deles — feita \"para verem se as palavras de Mardoqueu se sustentariam\" — que acende o pavio. Depois vem o tesoureiro que recebe a proposta dos dez mil talentos (Et 3:9), e a sala dos copistas no dia mais burocrático da Escritura: \"Então chamaram os escrivães do rei no primeiro mês, no dia treze do mesmo e, conforme a tudo quanto Hamã mandou, se escreveu aos príncipes do rei, e aos governadores que havia sobre cada província, e aos líderes, de cada povo; a cada província segundo a sua escrita, e a cada povo segundo a sua língua; em nome do rei Assuero se escreveu, e com o anel do rei se selou\" (Et 3:12). Homens de expediente redigindo um extermínio com todo o esmero de forma. E, no pátio, o moço que sela os cavalos dos correios \"impelidos pela palavra do rei\" (Et 3:15) — o mesmo serviço, os mesmos animais e talvez os mesmos correios que no capítulo 8 sairão correndo com a carta contrária."
    }
  },

  // ---------------------------------------------------------------- Et 4
  4: {
    anciao: {
      title: "Mardoqueu de saco e cinza diante da porta do rei, e os velhos das províncias em jejum e choro",
      subtitle: "Et 4 • o homem que rasgou as vestes no meio da cidade e a pergunta que ele mandou de volta",
      text: "\"Quando Mardoqueu soube tudo quanto se havia passado, rasgou as suas vestes, e vestiu-se de saco e de cinza, e saiu pelo meio da cidade, e clamou com grande e amargo clamor\" (Et 4:1). Ele vai até onde a lei o deixa ir e para exatamente ali: \"E chegou até diante da porta do rei, porque ninguém vestido de saco podia entrar pelas portas do rei\" (Et 4:2) — um império que não admite luto na sua soleira. Ester manda roupas para lhe tirar o pano de saco, \"porém ele não as aceitou\" (Et 4:4): o luto não é para ser vestido por cima. Pelo camareiro Hatá ele manda a soma exata do dinheiro e a cópia da lei escrita (Et 4:7-8), e depois as duas frases que sustentam o livro. A primeira é uma certeza sem sujeito nomeado: \"se de todo te calares neste tempo, socorro e livramento de outra parte sairá para os judeus, mas tu e a casa de teu pai perecereis\" (Et 4:14). A segunda é o mais perto que este livro chega de nomear a providência — e é uma pergunta, não uma afirmação: \"e quem sabe se para tal tempo como este chegaste a este reino?\" (Et 4:14). Nas províncias, outros velhos fazem o mesmo que ele: \"havia entre os judeus grande luto, com jejum, e choro, e lamentação; e muitos estavam deitados em saco e em cinza\" (Et 4:3)."
    },
    homem: {
      title: "Os judeus de Susã que ouviram o clamor, os deitados em saco e cinza pelas províncias, os guardas da porta e do pátio interior, e os que jejuaram três dias com Mardoqueu",
      subtitle: "Et 4 • um povo inteiro em luto público num império onde o luto não podia passar da porta",
      text: "\"E em todas as províncias aonde a palavra do rei e a sua lei chegava, havia entre os judeus grande luto, com jejum, e choro, e lamentação; e muitos estavam deitados em saco e em cinza\" (Et 4:3). Estes homens estão deitados no chão porque leram uma data: treze de Adar, e faltam onze meses. O texto descreve o gesto inteiro do luto bíblico — vestes rasgadas, saco, cinza, jejum, clamor — e, coisa que impressiona num livro da Escritura, NÃO diz que oraram, não nomeia a quem clamam, não registra uma só palavra dirigida a Deus. O silêncio é deliberado e vale mais do que uma explicação. Outros homens da cena são os guardas: o da porta do rei, que barra qualquer um vestido de saco (Et 4:2), e o do pátio interior, encarregado da lei que Ester recita de cor — \"todo o homem ou mulher que chegar ao rei no pátio interior, sem ser chamado, não há senão uma sentença, a de morte, salvo se o rei estender para ele o cetro de ouro, para que viva\" (Et 4:11). E os últimos são os que atendem ao chamado dela: \"Vai, ajunta a todos os judeus que se acharem em Susã, e jejuai por mim, e não comais nem bebais por três dias, nem de dia nem de noite\" (Et 4:16). Três dias e três noites de mesa vazia numa cidade pagã, por uma mulher que ia entrar sem ser chamada."
    },
    mulherComum: {
      title: "Ester, a rainha, com as suas servas que jejuaram três dias, e as judias das províncias deitadas em saco e cinza",
      subtitle: "Et 4 • a mulher que soube da carta por terceiros e respondeu com a frase mais dura do livro",
      text: "Ester descobre a catástrofe pelo lado errado: não por decreto, mas por fofoca de corredor — \"Então vieram as servas de Ester, e os seus camareiros, e fizeram-na saber, do que a rainha muito se doeu\" (Et 4:4). O primeiro impulso é cobrir o problema: manda roupas para tirar o saco de Mardoqueu, e ele recusa. Depois vem o argumento que ela levanta e que qualquer pessoa levantaria: a lei do pátio interior e a morte de quem entra sem ser chamado, agravada por um detalhe pessoal que ela não precisava dizer e disse — \"e eu nestes trinta dias não tenho sido chamada para ir ao rei\" (Et 4:11). Um mês sem ser lembrada pelo marido, e vai ter de contar com a boa vontade dele para não morrer. A resposta de Mardoqueu é a pergunta de 4:14, e a dela é a decisão que o livro guarda como o seu ponto mais alto: \"Vai, ajunta a todos os judeus que se acharem em Susã, e jejuai por mim... e eu e as minhas servas também assim jejuaremos. E assim irei ter com o rei, ainda que não seja segundo a lei; e se perecer, pereci\" (Et 4:16). Ao lado dela estão as suas servas, que jejuam os três dias inteiros, e as judias das províncias deitadas em saco e cinza (Et 4:3). Nenhuma delas reza em voz alta no texto; todas jejuam."
    },
    servo: {
      title: "Hatá, o camareiro que o rei tinha posto para servir a Ester, e os camareiros que viram Mardoqueu vestido de saco",
      subtitle: "Et 4:5-12 • o eunuco que atravessou a praça da cidade cinco vezes carregando o livro inteiro",
      text: "\"Então Ester chamou a Hatá (um dos camareiros do rei, que este tinha posto para servi-la), e deu-lhe ordem para ir a Mardoqueu, para saber que era aquilo, e porquê\" (Et 4:5). Hatá é um funcionário do rei destacado para a rainha, e é o único canal que existe entre os dois protagonistas — ela não pode sair, ele não pode entrar, e nenhum dos dois aparece na mesma cena até o capítulo 8. Todo o diálogo central do livro passa pelos pés deste homem, atravessando \"à praça da cidade, que estava diante da porta do rei\" (Et 4:6) de um lado para o outro. Ele leva de volta a soma exata do dinheiro prometido por Hamã e a cópia da lei escrita publicada em Susã (Et 4:7-8); traz a objeção da lei do pátio (Et 4:11); leva a pergunta \"quem sabe se para tal tempo como este chegaste a este reino?\" (Et 4:14); e traz \"se perecer, pereci\" (Et 4:16). É um eunuco persa carregando, sem saber, a sobrevivência de um povo inteiro dentro de um recado. Os outros servos desta cena são os camareiros e servas que primeiro viram Mardoqueu de saco na praça e correram contar à rainha (Et 4:4) — e o que voltou com as roupas recusadas debaixo do braço."
    }
  },

  // ---------------------------------------------------------------- Et 5
  5: {
    anciao: {
      title: "Mardoqueu assentado à porta do rei, que não se levantou nem se moveu, e os amigos chamados à casa de Hamã",
      subtitle: "Et 5:9-14 • o velho que não se mexeu, e os conselheiros que sugeriram cinquenta côvados de forca",
      text: "Hamã sai do primeiro banquete \"alegre e de bom ânimo\" (Et 5:9) e a alegria dura o tempo de atravessar um pátio: \"porém, vendo Mardoqueu à porta do rei, e que ele não se levantara nem se movera diante dele, então Hamã se encheu de furor contra Mardoqueu\". O gesto de Mardoqueu é de uma economia total — não fala, não protesta, não faz nada: apenas continua sentado. Do lado de lá da cidade, na casa de Hamã, estão os outros velhos deste capítulo: \"e enviou, e mandou vir os seus amigos, e Zeres, sua mulher\" (Et 5:10). São eles que ouvem o inventário da vaidade — \"a glória das suas riquezas, a multidão de seus filhos, e tudo em que o rei o tinha engrandecido\" (Et 5:11) — e a queixa que anula tudo: \"Porém tudo isto não me satisfaz, enquanto eu vir o judeu Mardoqueu assentado à porta do rei\" (Et 5:13). E são eles, junto com a mulher, que dão o conselho: \"Faça-se uma forca de cinqüenta côvados de altura, e amanhã dize ao rei que nela seja enforcado Mardoqueu; e então entra alegre com o rei ao banquete\" (Et 5:14). Estes mesmos sábios voltarão no capítulo seguinte para dizer o contrário, com a cara de quem já viu o fim: \"não prevalecerás contra ele, antes certamente cairás diante dele\" (Et 6:13)."
    },
    homem: {
      title: "Hamã, o convidado único dos dois banquetes, o guarda do pátio interior e os amigos chamados à sua casa",
      subtitle: "Et 5 • o homem que se achou o preferido da rainha e mandou levantar uma forca na mesma noite",
      text: "Hamã atravessa este capítulo convencido de que está subindo. É chamado às pressas ao banquete — \"Fazei apressar a Hamã, para que se atenda ao desejo de Ester\" (Et 5:5) —, come com o rei e a rainha, é convidado outra vez para o dia seguinte, e conta isso em casa como quem conta uma promoção: \"Tampouco a rainha Ester a ninguém fez vir com o rei ao banquete que tinha preparado, senão a mim; e também para amanhã estou convidado por ela juntamente com o rei\" (Et 5:12). O leitor sabe o que ele não sabe: aquele convite é a armadilha. O outro homem da cena é o guarda do pátio interior, que cumpre a lei de que \"todo o homem ou mulher que chegar ao rei no pátio interior, sem ser chamado, não há senão uma sentença, a de morte\" (Et 4:11) e vê a rainha entrar sem convocação, de trajes reais, e ficar de pé esperando. E há os amigos convocados de noite, que aprovam a forca. O capítulo fecha num quintal: \"E este conselho bem pareceu a Hamã, que mandou fazer a forca\" (Et 5:14) — cinquenta côvados, uns vinte e dois metros, levantados às pressas antes do amanhecer, no chão da casa de quem ia morrer nela (Et 7:9-10)."
    },
    mulherComum: {
      title: "Ester, de trajes reais no pátio interior, e Zeres, mulher de Hamã",
      subtitle: "Et 5 • as duas mulheres que decidem o capítulo: uma que espera dois banquetes e outra que resolve numa noite",
      text: "\"Sucedeu, pois, que ao terceiro dia Ester se vestiu com trajes reais, e se pôs no pátio interior da casa do rei, defronte do aposento do rei\" (Et 5:1). Terceiro dia é o fim do jejum de 4:16; os trajes reais são o contrário do saco de Mardoqueu — ela não entra chorando, entra como rainha. O texto não descreve nenhum sentimento, só o que se vê: ela se põe de pé e espera. \"E o rei estendeu para Ester o cetro de ouro, que tinha na sua mão, e Ester chegou, e tocou a ponta do cetro\" (Et 5:2). Oferecida metade do reino (Et 5:3), ela pede um jantar; oferecida outra vez, pede outro jantar (Et 5:8). O livro não diz por que ela adia — e é justamente o adiamento que põe Hamã na rua no exato dia em que o rei perderia o sono. Do outro lado da cidade está Zeres, mulher de Hamã, que ouve o inventário das riquezas do marido e a queixa sobre o judeu da porta, e responde com a ideia mais prática e mais fatal do livro: \"Faça-se uma forca de cinqüenta côvados de altura\" (Et 5:14). É ela quem levanta a madeira em que ele será pendurado, e é ela quem, no capítulo seguinte, sentenciará o próprio marido (Et 6:13)."
    },
    rei: {
      title: "Assuero, que estendeu o cetro de ouro e ofereceu metade do reino duas vezes",
      subtitle: "Et 5 • o rei nos dois banquetes do vinho, perguntando o que ela quer e sem imaginar a resposta",
      text: "\"E o rei estava assentado sobre o seu trono real, na casa real, defronte da porta do aposento. E sucedeu que, vendo o rei a rainha Ester, que estava no pátio, ela alcançou graça aos seus olhos\" (Et 5:1-2). O gesto do cetro estendido é a diferença entre a vida e a morte, e o texto o registra sem uma palavra de suspense — a lei era mortal, e o rei simplesmente estende a mão. Depois vêm as duas ofertas, feitas com a mesma fórmula exagerada que ele já usara com Hamã e o dinheiro: \"Que é que queres, rainha Ester, ou qual é a tua petição? Até metade do reino se te dará\" (Et 5:3), e no banquete do vinho outra vez: \"E se fará, ainda até metade do reino\" (Et 5:6). Este é o rei que assinou, dois capítulos antes, a morte de um povo sem perguntar o nome dele, e agora oferece meio império à mulher que está naquela lista. Nada nele mudou — a mesma generosidade sem informação. Ele aceita o convite, chama Hamã às pressas, come duas vezes com o inimigo à mesa e vai dormir sem desconfiar de nada. E é nessa noite que o sono foge (Et 6:1)."
    },
    servo: {
      title: "O camareiro do pátio interior, os servos dos dois banquetes de Ester, os filhos de Hamã na casa de Susã e o carpinteiro que fez a forca de cinquenta côvados",
      subtitle: "Et 5 • quem serve o vinho na mesa dos três e quem serrou madeira a noite inteira num quintal",
      text: "Os primeiros são os da casa: o camareiro que abre o pátio interior, os que correm chamar Hamã — \"Fazei apressar a Hamã\" (Et 5:5) — e os que servem \"o banquete do vinho\" (Et 5:6) a três pessoas, sem saber que estão pondo à mesa o acusado e a acusadora. Na casa de Hamã, os servos ouvem o dono contar diante dos amigos \"a glória das suas riquezas, a multidão de seus filhos, e tudo em que o rei o tinha engrandecido\" (Et 5:11): essa multidão de filhos são dez, e o capítulo 9 os nomeará um por um, todos mortos no mesmo dia (Et 9:7-10). E o último servo deste capítulo é o que trabalha de noite: o carpinteiro que recebe a ordem \"que mandou fazer a forca\" (Et 5:14) e levanta cinquenta côvados de madeira antes do amanhecer, no quintal do seu patrão. Ele não sabe para quem está trabalhando de verdade. Dois capítulos adiante, outro criado da mesma casa, o eunuco Harbona, apontará essa forca ao rei: \"Eis que também a forca de cinqüenta côvados de altura que Hamã fizera para Mardoqueu, que falara em defesa do rei, está junto à casa de Hamã\" (Et 7:9). O livro nunca diz que isso foi providência. Só conta que a forca estava pronta."
    }
  }
};
