// Fichas ESPECÍFICAS por (capítulo → papel) de ESTER 6–10.
// O livro em que Deus não é nomeado uma única vez vira de lado numa NOITE SEM
// SONO. O texto não diz por que o sono fugiu, não diz por que o rolo se abriu
// naquela página, não diz por que Hamã estava no pátio exterior naquele exato
// momento e não diz por que a forca já estava pronta — apenas registra as
// coincidências uma atrás da outra e cala sobre todas elas. As fichas destes
// capítulos apontam o encaixe e param onde o livro para: o feito escrito em
// 2:23 e nunca pago, o rei insone que manda buscar justamente esse rolo, o
// pur lançado em Nisã que caiu em Adar e deu onze meses de prazo, e a frase
// repetida três vezes em Et 9 — "porém ao despojo não estenderam a sua mão" —
// que é o contrário exato do que Saul fez com o despojo de Amaleque (1Sm 15:9,
// 19), na briga de quatrocentos anos entre a casa de Quis e a casa de Agague.
// Cada figurante anônimo é alguém REAL daquele capítulo: o escrivão que leu as
// crônicas em voz alta na madrugada, o servo que trouxe o cavalo do rei, o
// eunuco que cobriu o rosto de Hamã, o correio sobre ginete veloz das
// cavalariças do rei, o judeu que se ajuntou na sua cidade para defender a
// vida, o pobre que recebeu dádivas no primeiro Purim, o cobrador do tributo
// das ilhas do mar.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_06_10: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- Et 6
  6: {
    anciao: {
      title: "Mardoqueu, o homem a quem coisa nenhuma se fez, e os sábios da casa de Hamã que pronunciaram a sentença",
      subtitle: "Et 6 • o velho esquecido nas crônicas e os conselheiros que perceberam o fim antes do dono da casa",
      text: "O capítulo gira sobre um nome que estava escrito e nunca fora pago: \"E achou-se escrito que Mardoqueu tinha denunciado Bigtã e Teres, dois dos camareiros do rei, da guarda da porta, que tinham procurado lançar mão do rei Assuero\" (Et 6:2). A pergunta do rei e a resposta dos servos são o eixo de tudo: \"Que honra e distinção se deu por isso a Mardoqueu? E os servos do rei, que ministravam junto a ele, disseram: Coisa nenhuma se lhe fez\" (Et 6:3). Quatro capítulos de dívida, cobrada às três da manhã. Do outro lado da cidade estão os outros velhos: os amigos e sábios que Hamã reuniu em 5:10 e que agora, ouvindo o relato da humilhação, mudam de conselho em vinte e quatro horas — \"Então os seus sábios e Zeres, sua mulher, lhe disseram: Se Mardoqueu, diante de quem já começaste a cair, é da descendência dos judeus, não prevalecerás contra ele, antes certamente cairás diante dele\" (Et 6:13). É a única vez em todo o livro que alguém enuncia uma lei de causa e efeito sobre os judeus, e quem a enuncia são pagãos numa sala de jantar — sem citar Deus, sem citar profeta, sem citar promessa. Os mesmos homens que na véspera mandaram levantar a forca."
    },
    cavaleiro: {
      title: "Mardoqueu sobre o cavalo em que o rei costuma andar montado, com a veste real e a coroa na cabeça do animal",
      subtitle: "Et 6:10-11 • o judeu da porta levado pelas ruas da cidade pelo homem que mandara fazer a sua forca",
      text: "Hamã descreve a honra que quer para si mesmo, sem saber que está redigindo a sua própria humilhação: \"Tragam a veste real que o rei costuma vestir, como também o cavalo em que o rei costuma andar montado, e ponha-se-lhe a coroa real na sua cabeça. E entregue-se a veste e o cavalo à mão de um dos príncipes mais nobres do rei... e levem-no a cavalo pelas ruas da cidade, e apregoe-se diante dele: Assim se fará ao homem a quem o rei deseja honrar!\" (Et 6:8-9). O rei fecha a armadilha com um nome e uma cláusula: \"Apressa-te, toma a veste e o cavalo, como disseste, e faze assim para com o judeu Mardoqueu, que está assentado à porta do rei; e coisa nenhuma omitas de tudo quanto disseste\" (Et 6:10). Coisa nenhuma omitas — nem a coroa, nem o pregão, nem o príncipe segurando as rédeas. E assim se faz: \"E Hamã tomou a veste e o cavalo, e vestiu a Mardoqueu, e o levou a cavalo pelas ruas da cidade, e apregoou diante dele\" (Et 6:11). O homem que passou pela cidade em saco e cinza no capítulo 4, clamando \"com grande e amargo clamor\" (Et 4:1), atravessa as mesmas ruas montado, com um agagita a pé ao lado do estribo. O livro não comenta a inversão; só a descreve, e depois manda Mardoqueu de volta ao seu banco: \"Depois disto Mardoqueu voltou para a porta do rei\" (Et 6:12)."
    },
    homem: {
      title: "O escrivão que leu as crônicas diante do rei, Hamã no pátio exterior e o príncipe mais nobre que segurou as rédeas",
      subtitle: "Et 6 • os três homens da noite em que tudo virou, e nenhum deles sabia o que estava fazendo",
      text: "O primeiro é o leitor da madrugada: \"Naquela mesma noite fugiu o sono do rei; então mandou trazer o livro de registro das crônicas, as quais se leram diante do rei\" (Et 6:1). Um funcionário acordado às pressas para ler anais a um insone, e o rolo se abre justamente na página de 2:23. O livro não diz por que o sono fugiu nem por que o leitor parou ali. O segundo é Hamã, que chega ao pátio no minuto exato: \"E Hamã tinha entrado no pátio exterior da casa do rei, para dizer ao rei que enforcassem a Mardoqueu na forca que lhe tinha preparado\" (Et 6:4). Entra para pedir uma morte e sai obrigado a organizar uma festa. A cegueira dele está escrita: \"Então Hamã disse no seu coração: De quem se agradaria o rei para lhe fazer honra mais do que a mim?\" (Et 6:6). O terceiro é \"um dos príncipes mais nobres do rei\" (Et 6:9), o oficial que segundo o próprio plano de Hamã deveria conduzir o cavalo — e a ironia é que o rei o substitui pelo autor da ideia. O capítulo fecha com o retrato de um homem desfeito: \"porém Hamã se retirou correndo à sua casa, triste, e de cabeça coberta\" (Et 6:12)."
    },
    mulherComum: {
      title: "Zeres, mulher de Hamã, que ouviu o marido chegar correndo de cabeça coberta",
      subtitle: "Et 6:13 • a mesma mulher que mandou levantar a forca, agora dizendo que ele vai cair",
      text: "Na véspera fora dela a ideia: \"Faça-se uma forca de cinqüenta côvados de altura, e amanhã dize ao rei que nela seja enforcado Mardoqueu\" (Et 5:14). Vinte e quatro horas depois, o marido volta correndo, triste e de cabeça coberta, e conta \"a Zeres, sua mulher, e a todos os seus amigos, tudo quanto lhe tinha sucedido\" (Et 6:13). A resposta dela é a profecia mais estranha do livro, porque não vem de profeta, não invoca nome nenhum e mesmo assim acerta em cheio: \"Se Mardoqueu, diante de quem já começaste a cair, é da descendência dos judeus, não prevalecerás contra ele, antes certamente cairás diante dele\". Uma persa numa sala de jantar em Susã diz, em uma frase, o que Israel tinha ouvido em Gênesis — \"amaldiçoarei os que te amaldiçoarem\" (Gn 12:3) — sem citar Gênesis, sem citar Deus e sem citar nada. Ela nomeia apenas a descendência: é o povo, não o homem. E não termina a conversa: \"E estando eles ainda falando com ele, chegaram os camareiros do rei, e se apressaram a levar Hamã ao banquete que Ester preparara\" (Et 6:14). A frase fica cortada no meio, e ele sai para morrer."
    },
    multidao: {
      title: "O povo de Susã nas ruas por onde passou o pregão",
      subtitle: "Et 6:11 • a cidade que ouviu \"assim se fará ao homem a quem o rei deseja honrar\" e viu quem ia a pé",
      text: "\"e o levou a cavalo pelas ruas da cidade, e apregoou diante dele: Assim se fará ao homem a quem o rei deseja honrar!\" (Et 6:11). Esta é a mesma população que, no capítulo 3, ficara parada quando os correios saíram com o decreto — \"porém a cidade de Susã estava confusa\" (Et 3:15) — e que vira, no capítulo 4, um velho judeu atravessar essas ruas em saco e cinza clamando \"com grande e amargo clamor\" (Et 4:1). Agora vê o mesmo homem passar montado no cavalo do rei, com a veste real, e vê quem vai a pé segurando as rédeas e gritando o pregão. Ninguém em Susã sabe ainda que a rainha é judia, nem que a forca do quintal de Hamã foi feita para o homem em cima do cavalo. A cidade só vê a cena. Dois capítulos adiante ela voltará a olhar para Mardoqueu na rua, e daquela vez saberá tudo: \"Então Mardoqueu saiu da presença do rei com veste real azul-celeste e branca, como também com uma grande coroa de ouro... e a cidade de Susã exultou e se alegrou\" (Et 8:15)."
    },
    rei: {
      title: "Assuero, o rei de quem fugiu o sono naquela mesma noite",
      subtitle: "Et 6:1-10 • o insone que mandou trazer as crônicas e perguntou a coisa certa na hora certa",
      text: "\"Naquela mesma noite fugiu o sono do rei; então mandou trazer o livro de registro das crônicas, as quais se leram diante do rei\" (Et 6:1). É o versículo em torno do qual o livro inteiro gira, e é feito de nada: um homem que não dorme e manda ler documentos administrativos para passar a madrugada. O texto não diz que Deus tirou o sono do rei. Não diz que o rolo se abriu numa página escolhida. Diz apenas que se leu, que se achou escrito o feito de Mardoqueu (Et 6:2), que o rei perguntou o que se tinha dado por isso e ouviu \"coisa nenhuma se lhe fez\" (Et 6:3) — e que, quando perguntou quem estava no pátio, quem lá estava era exatamente o homem que vinha pedir a morte de Mardoqueu (Et 6:4-5). Este rei tem um padrão: pergunta antes de saber com quem está falando. Fez isso em 3:8-11, para o mal, quando entregou o anel sem perguntar o nome do povo; faz agora, para o bem, quando pergunta \"Que se fará ao homem de cuja honra o rei se agrada?\" (Et 6:6) a um homem convencido de que a resposta é sobre ele mesmo. É a mesma ignorância nos dois casos, e ela cai dos dois lados."
    },
    servo: {
      title: "O camareiro que trouxe o livro das crônicas, os servos que ministravam junto ao rei, o que trouxe o cavalo real e os que levaram Hamã depressa ao banquete",
      subtitle: "Et 6 • quem carrega o rolo na madrugada e quem sela o cavalo da honra de outro homem",
      text: "Nenhum destes homens sabe o que está fazendo, e todos são indispensáveis. O primeiro atravessa o palácio de noite com um rolo debaixo do braço porque o rei não dorme (Et 6:1) — se tivesse trazido outro volume, ou desenrolado outro trecho, o capítulo não existiria. Os segundos são os que respondem à pergunta do rei sem floreio nenhum: \"E os servos do rei, que ministravam junto a ele, disseram: Coisa nenhuma se lhe fez\" (Et 6:3). Eles poderiam ter inventado uma recompensa esquecida; disseram a verdade seca, e a verdade seca abriu a porta. São eles também que avisam quem está lá fora — \"E os servos do rei lhe disseram: Eis que Hamã está no pátio. E disse o rei que entrasse\" (Et 6:5). Depois vêm os moços da estrebaria, que aparelham \"o cavalo em que o rei costuma andar montado\" (Et 6:8) e lhe põem a coroa real na cabeça, e o servo do guarda-roupa que tira a veste real da arca para vestir um judeu da porta. E os últimos entram para cortar uma conversa no meio: \"chegaram os camareiros do rei, e se apressaram a levar Hamã ao banquete que Ester preparara\" (Et 6:14)."
    }
  },

  // ---------------------------------------------------------------- Et 7
  7: {
    homem: {
      title: "Hamã, o opressor e o inimigo, e o oficial que cumpriu a sentença",
      subtitle: "Et 7 • o convidado que foi apontado à mesa e enforcado na forca que ele mesmo mandou fazer",
      text: "Hamã entra neste capítulo como convidado de honra e sai dele de rosto coberto. A denúncia de Ester é feita sem nome até a última palavra, e a última palavra é o nome dele: \"E disse Ester: O homem, o opressor, e o inimigo, é este mau Hamã. Então Hamã se perturbou perante o rei e a rainha\" (Et 7:6). O rei sai furioso para o jardim do palácio e o deixa sozinho com a mulher a quem ia matar: \"e Hamã se pôs em pé, para rogar à rainha Ester pela sua vida; porque viu que já o mal lhe estava determinado pelo rei\" (Et 7:7). O erro final é físico e fatal: \"Hamã tinha caído prostrado sobre o leito em que estava Ester\" (Et 7:8) — o mesmo homem diante de quem todos se prostravam (Et 3:2) acaba prostrado, e no lugar errado. O rei volta, vê e interpreta o pior: \"Porventura quereria ele também forçar a rainha perante mim nesta casa? Saindo esta palavra da boca do rei, cobriram o rosto de Hamã\" (Et 7:8). O oficial que executa a ordem faz o serviço na madeira do quintal do próprio condenado: \"Enforcaram, pois, a Hamã na forca, que ele tinha preparado para Mardoqueu\" (Et 7:10). O livro não chama isso de juízo de Deus; diz só que \"o furor do rei se aplacou\"."
    },
    mulherComum: {
      title: "Ester, a rainha, no segundo banquete do vinho",
      subtitle: "Et 7:3-6 • a mulher que pediu a própria vida como petição e o próprio povo como desejo",
      text: "Perguntada pela terceira vez o que quer, até metade do reino (Et 7:2), Ester finalmente responde — e a resposta não pede coisa nenhuma do reino: \"Se, ó rei, achei graça aos teus olhos, e se bem parecer ao rei, dê-se-me a minha vida como minha petição, e o meu povo como meu desejo\" (Et 7:3). É neste versículo que ela declara, enfim, o que Mardoqueu lhe mandara esconder desde 2:10: ao pedir o povo, diz de que povo é. Em seguida cita o decreto pelas palavras exatas dele — \"Porque fomos vendidos, eu e o meu povo, para nos destruírem, matarem, e aniquilarem de vez\" (Et 7:4), ecoando \"destruíssem, matassem, e fizessem perecer\" de 3:13 — e acrescenta a frase que mede a diferença entre escravidão e extermínio: \"se ainda por servos e por servas nos vendessem, calar-me-ia\". Ela não acusa o rei, que assinou; deixa que ele pergunte \"Quem é esse e onde está esse, cujo coração o instigou a assim fazer?\" (Et 7:5) e só então aponta o convidado sentado à mesa. Depois, calada, ela é a testemunha da cena mais grotesca do livro: o inimigo do seu povo caído sobre o seu próprio leito, rogando pela vida a quem ele mandara matar."
    },
    rei: {
      title: "Assuero no banquete do vinho, entre o jardim do palácio e a casa do banquete",
      subtitle: "Et 7 • o rei que perguntou quem tinha feito aquilo sem se lembrar de quem tinha dado o anel",
      text: "\"Então falou o rei Assuero, e disse à rainha Ester: Quem é esse e onde está esse, cujo coração o instigou a assim fazer?\" (Et 7:5). A pergunta é sincera e é absurda: quem entregou o anel foi ele (Et 3:10), quem disse \"Essa prata te é dada como também esse povo\" foi ele (Et 3:11). O livro deixa a incoerência de pé sem comentar — este rei nunca soube o que estava assinando, e continua não sabendo. A reação é a de sempre: furor e movimento sem decisão. \"E o rei no seu furor se levantou do banquete do vinho e passou para o jardim do palácio\" (Et 7:7); volta e encontra a cena que resolve tudo por ele, e a lê pela ofensa pessoal, não pelo genocídio: \"Porventura quereria ele também forçar a rainha perante mim nesta casa?\" (Et 7:8). A sentença sai de outra boca ainda — a do eunuco Harbona, que lembra a forca de cinquenta côvados de pé junto à casa de Hamã (Et 7:9) — e ao rei só resta dizer duas palavras: \"Enforcai-o nela\". O capítulo fecha com a única coisa que este homem realmente administra: \"Então o furor do rei se aplacou\" (Et 7:10)."
    },
    servo: {
      title: "Harbona, um dos camareiros que serviam diante do rei, com os servos do banquete do vinho e os que cobriram o rosto de Hamã",
      subtitle: "Et 7:8-10 • o eunuco que lembrou a forca do quintal e resolveu o livro numa frase",
      text: "Os servos deste capítulo estão à mesa dos três e veem tudo: o rei sair furioso para o jardim, Hamã ficar de pé para rogar pela vida, Hamã cair prostrado sobre o leito, e o rei voltar. São eles que executam a ordem que não precisa de palavras: \"Saindo esta palavra da boca do rei, cobriram o rosto de Hamã\" (Et 7:8) — o gesto persa do condenado, e o fim de quem tinha o assento acima de todos os príncipes. E então fala o servo mais decisivo do livro: \"Então disse Harbona, um dos camareiros que serviam diante do rei: Eis que também a forca de cinqüenta côvados de altura que Hamã fizera para Mardoqueu, que falara em defesa do rei, está junto à casa de Hamã\" (Et 7:9). Harbona é um nome que já apareceu: é um dos sete camareiros que foram buscar Vasti no primeiro capítulo (Et 1:10). Ele sabe da forca, sabe para quem foi feita, e sabe o detalhe que arremata o argumento — que Mardoqueu \"falara em defesa do rei\", isto é, o feito lido na madrugada anterior. Um eunuco de palácio junta as duas pontas e o rei diz \"Enforcai-o nela\". Os últimos servos da cena são os guardas que cumprem a ordem na madeira do quintal (Et 7:10)."
    }
  },

  // ---------------------------------------------------------------- Et 8
  8: {
    anciao: {
      title: "Mardoqueu com o anel do rei, e os anciãos dos judeus de Susã e das províncias a quem chegou a segunda carta",
      subtitle: "Et 8 • o velho que passou da porta do rei ao encargo da casa de Hamã, e os que leram a carta que devolveu a vida",
      text: "\"E tirou o rei o seu anel, que tinha tomado de Hamã, e o deu a Mardoqueu. E Ester encarregou Mardoqueu da casa de Hamã\" (Et 8:2). O anel é o mesmo objeto de 3:10 — o selo do império que condenou os judeus passa, sem uma palavra de explicação, para a mão de um judeu. E o problema jurídico continua de pé: \"o documento que se escreve em nome do rei, e que se sela com o anel do rei, não se pode revogar\" (Et 8:8), a mesma lei irrevogável dos persas e dos medos que prendeu o rei ao decreto contra Vasti (Et 1:19; 2:1). Não se apaga a primeira carta; escreve-se uma segunda. É Mardoqueu quem a dita — \"se escreveu conforme a tudo quanto ordenou Mardoqueu aos judeus, como também aos sátrapas, e aos governadores, e aos líderes das províncias\" (Et 8:9) —, e o que ela concede não é vingança gratuita, é defesa: \"que se reunissem, e se dispusessem para defenderem as suas vidas\" (Et 8:11), no mesmo dia treze de Adar marcado pelo pur. Os outros velhos da cena são os anciãos das comunidades judaicas que, onze meses depois de terem ouvido a sentença de morte lida na sua própria língua, ouvem esta segunda carta lida do mesmo modo, e leem no fim dela: \"E para os judeus houve luz, e alegria, e gozo, e honra\" (Et 8:16)."
    },
    cavaleiro: {
      title: "Os correios a cavalo sobre ginetes velozes das cavalariças do rei",
      subtitle: "Et 8:10-14 • os mesmos cavalos e as mesmas estradas do decreto de morte, agora com a carta contrária",
      text: "\"E escreveu-se em nome do rei Assuero e, selando-as com o anel do rei, enviaram as cartas pela mão de correios a cavalo, que cavalgavam sobre ginetes, que eram das cavalariças do rei\" (Et 8:10). O texto se demora nos animais de propósito: são montarias do estábulo real, criadas para velocidade, e não os cavalos comuns da posta que levaram o decreto de Hamã em 3:13. Havia pressa — a primeira carta tinha onze meses de vantagem, e as cento e vinte e sete províncias iam \"da Úndia até Etiópia\" (Et 8:9). \"Os correios, sobre ginetes velozes, saíram apressuradamente, impelidos pela palavra do rei; e esta ordem foi publicada na fortaleza de Susã\" (Et 8:14). A expressão \"impelidos pela palavra do rei\" é a mesma de 3:15, e a repetição é o ponto: o império que despachou a morte despacha agora, com o mesmo selo, pelas mesmas estradas e na mesma pressa, a licença de viver. Nada mudou na máquina; mudou quem tem o anel."
    },
    homem: {
      title: "Os escrivães do mês de Sivã, o cavalariço dos ginetes, o arauto do decreto em Susã e os homens dos povos da terra que se fizeram judeus",
      subtitle: "Et 8 • a mesma sala de copistas do capítulo 3, escrevendo desta vez o contrário",
      text: "\"Então foram chamados os escrivães do rei, naquele mesmo tempo, no terceiro mês (que é o mês de Sivã), aos vinte e três dias\" (Et 8:9). A frase é a gêmea exata de 3:12 — mesma sala, mesmo ofício, mesma fórmula de \"a cada província segundo o seu modo de escrever, e a cada povo conforme a sua língua\" —, com um acréscimo que só aparece agora: \"como também aos judeus segundo o seu modo de escrever, e conforme a sua língua\". Pela primeira vez o império escreve aos judeus na língua deles. Ao lado dos escrivães estão os cavalariços que aparelham os ginetes das cavalariças do rei (Et 8:10), o arauto que publica a ordem na fortaleza de Susã (Et 8:14) e o servo que a afixa na praça. E o capítulo fecha com uma categoria de homem que não existia antes: \"e muitos, dos povos da terra, se fizeram judeus, porque o temor dos judeus tinha caído sobre eles\" (Et 8:17). Persas, medos, gente das províncias, aderindo a um povo que onze meses antes estava marcado para morrer — e o texto dá o motivo sem sublinhar nada: o medo mudou de lado."
    },
    mulherComum: {
      title: "Ester lançada aos pés do rei, as judias de Susã que ouviram o decreto e as mulheres das províncias nos dias de folguedo",
      subtitle: "Et 8 • a rainha que chorou e suplicou depois de o inimigo já estar morto",
      text: "Hamã já fora enforcado no capítulo anterior, e ainda assim: \"Falou mais Ester perante o rei, e se lhe lançou aos seus pés; e chorou, e lhe suplicou que revogasse a maldade de Hamã, o agagita, e o intento que tinha projetado contra os judeus\" (Et 8:3). É a única vez em que o livro lhe atribui lágrimas, e elas vêm depois da vitória pessoal — a casa de Hamã já era dela (Et 8:1) —, porque a carta continuava valendo. O cetro de ouro se estende pela segunda vez (Et 8:4), e o argumento que ela apresenta é o de alguém que não consegue separar a própria vida da do seu povo: \"Pois como poderei ver o mal que sobrevirá ao meu povo? E como poderei ver a destruição da minha parentela?\" (Et 8:6). Ao redor dela estão as judias de Susã, que passaram onze meses sabendo a data da própria morte e agora ouvem a segunda carta publicada na fortaleza (Et 8:14), e as mulheres das províncias no fim do capítulo: \"havia entre os judeus alegria e gozo, banquetes e dias de folguedo\" (Et 8:17). É o contrário exato de 4:3, onde estavam \"deitados em saco e em cinza\"."
    },
    multidao: {
      title: "A cidade de Susã que exultou e se alegrou, os judeus a quem houve luz e alegria, e os povos da terra que se fizeram judeus",
      subtitle: "Et 8:15-17 • a mesma cidade que estava confusa em 3:15, agora na rua por outro motivo",
      text: "\"Então Mardoqueu saiu da presença do rei com veste real azul-celeste e branca, como também com uma grande coroa de ouro, e com uma capa de linho fino e púrpura, e a cidade de Susã exultou e se alegrou\" (Et 8:15). O versículo foi escrito para ser lido contra o de 3:15 — \"E o rei e Hamã se assentaram a beber, porém a cidade de Susã estava confusa\" —, e as duas frases fecham capítulos que são espelho um do outro: escrivães, anel, correios, decreto e, no fim, a reação da cidade. Aqui a multidão está na rua e está alegre, e não é só a comunidade judaica: é Susã inteira. O versículo seguinte é a frase mais luminosa do livro e a única que soa a bênção: \"E para os judeus houve luz, e alegria, e gozo, e honra\" (Et 8:16) — quatro palavras, e nenhuma delas atribuída a ninguém. E a última multidão do capítulo é a mais improvável: \"muitos, dos povos da terra, se fizeram judeus, porque o temor dos judeus tinha caído sobre eles\" (Et 8:17)."
    },
    rei: {
      title: "Assuero, que deu a casa de Hamã a Ester e o anel a Mardoqueu",
      subtitle: "Et 8 • o rei preso à própria lei, que não pode revogar e por isso manda escrever outra carta",
      text: "\"Naquele mesmo dia deu o rei Assuero à rainha Ester a casa de Hamã, inimigo dos judeus; e Mardoqueu veio perante o rei, porque Ester tinha declarado quem ele era\" (Et 8:1). O rei descobre agora, no mesmo movimento, que a mulher é judia e que o homem da porta é da família dela. A generosidade é imediata e a impotência também: pedido a revogar o decreto, ele responde com a lei que já o havia enredado no capítulo 2 — \"Escrevei, pois, aos judeus, como parecer bem aos vossos olhos, em nome do rei, e selai-o com o anel do rei; porque o documento que se escreve em nome do rei, e que se sela com o anel do rei, não se pode revogar\" (Et 8:8). Ele entrega a caneta e sai da frente. É o mesmo gesto de 3:10-11 — dar o anel e deixar que outro escreva —, agora com outro homem do outro lado da mesa. Este rei nunca decide o conteúdo de nada em todo o livro; decide apenas a quem entrega o selo. E o que ele diz do inimigo morto já é o resumo do capítulo 9: \"Eis que dei a Ester a casa de Hamã, e a ele penduraram numa forca, porquanto estendera as mãos contra os judeus\" (Et 8:7)."
    },
    servo: {
      title: "O servo da sala do anel, os moços da câmara dos escrivães e o que afixou o decreto na praça de Susã",
      subtitle: "Et 8 • quem carrega o selo do império de uma mão para a outra e quem prega a nova carta no muro",
      text: "Estes são os funcionários que fazem a virada acontecer no papel. Um deles é o servo da sala onde o anel é tirado do dedo do rei pela segunda vez no livro: \"E tirou o rei o seu anel, que tinha tomado de Hamã, e o deu a Mardoqueu\" (Et 8:2) — o mesmo objeto que em 3:10 selara o extermínio. Outros são os moços da câmara dos escrivães, chamados \"no terceiro mês (que é o mês de Sivã), aos vinte e três dias\" (Et 8:9), que passam o dia copiando a mesma carta em dezenas de escritas e línguas, inclusive, pela primeira vez, na dos judeus. Outros aparelham os ginetes velozes das cavalariças do rei (Et 8:10) e despacham os correios. E o último é o que sai com o rolo e a cola: \"E uma cópia da carta seria divulgada como decreto em todas as províncias, e publicada entre todos os povos\" (Et 8:13), e \"esta ordem foi publicada na fortaleza de Susã\" (Et 8:14). É o mesmo cargo, o mesmo muro e talvez o mesmo homem que onze meses antes afixara ali a sentença de morte."
    }
  },

  // ---------------------------------------------------------------- Et 9
  9: {
    anciao: {
      title: "Mardoqueu, grande na casa do rei, e os anciãos dos judeus de Susã e das províncias que estabeleceram o Purim",
      subtitle: "Et 9 • os velhos que escreveram as cartas de paz e verdade e deram nome à festa a partir da sorte de Hamã",
      text: "\"Porque Mardoqueu era grande na casa do rei, e a sua fama crescia por todas as províncias, porque o homem Mardoqueu ia sendo engrandecido\" (Et 9:4) — o mesmo verbo com que o capítulo 3 apresentara Hamã, \"o rei Assuero engrandeceu a Hamã\" (Et 3:1), agora aplicado ao homem que ele quis enforcar. No fim do capítulo, Mardoqueu vira legislador de um calendário: \"E Mardoqueu escreveu estas coisas, e enviou cartas a todos os judeus que se achavam em todas as províncias do rei Assuero, aos de perto, e aos de longe, ordenando-lhes que guardassem o dia catorze do mês de Adar, e o dia quinze do mesmo, todos os anos\" (Et 9:20-21). Os outros velhos da cena são os anciãos das comunidades que recebem essas cartas e as confirmam sobre si e sobre a descendência (Et 9:27), e os que dão o nome à festa: \"Por isso àqueles dias chamam Purim, do nome Pur\" (Et 9:26). O nome da alegria judaica vem da palavra persa para a sorte que Hamã lançou a fim de escolher o dia de matá-los (Et 3:7; 9:24). O livro registra o nome e não explica a ironia. Quem a explica é outro texto: \"A sorte se lança no regaço, mas do Senhor procede toda a determinação\" (Pv 16:33). E os últimos velhos são os que fazem questão de que a memória guarde também o começo, e não só o fim: as cartas confirmam os dias \"acerca do jejum e do seu clamor\" (Et 9:31)."
    },
    cavaleiro: {
      title: "Os correios que levaram as cartas de paz e verdade às cento e vinte e sete províncias",
      subtitle: "Et 9:30 • a terceira leva de cavaleiros do livro, e a única que não leva decreto de guerra nenhum",
      text: "\"E mandaram cartas a todos os judeus, às cento e vinte e sete províncias do reino de Assuero, com palavras de paz e verdade\" (Et 9:30). São os mesmos cavalos e as mesmas estradas de sempre — as de 3:13, quando os correios saíram \"impelidos pela palavra do rei\" com a ordem de destruir, e as de 8:14, quando saíram sobre ginetes velozes com a licença de defender a vida. Desta vez não levam decreto de morte nem autorização de guerra: levam a segunda carta do Purim, escrita \"com toda autoridade\" pela rainha Ester, filha de Abiail, e por Mardoqueu, o judeu (Et 9:29), para confirmar dois dias de festa no calendário de um povo espalhado da Índia à Etiópia. A mesma máquina imperial que serviu ao ódio de um agagita agora carrega, do outro lado do mapa, a memória de que o dia marcado para o extermínio \"se lhes mudou de tristeza em alegria, e de luto em dia de festa\" (Et 9:22)."
    },
    homem: {
      title: "Os judeus que se ajuntaram nas suas cidades, os sátrapas e governadores que os auxiliaram, os inimigos caídos no dia treze — e os dez filhos de Hamã",
      subtitle: "Et 9 • o dia marcado para acabar com eles, em que sucedeu o contrário, e a frase que o livro repete três vezes",
      text: "\"no dia em que os inimigos dos judeus esperavam assenhorear-se deles, sucedeu o contrário, porque os judeus foram os que se assenhorearam dos que os odiavam\" (Et 9:1). Estes homens não atacaram: \"os judeus nas suas cidades... se ajuntaram para pôr as mãos naqueles que procuravam o seu mal\" (Et 9:2), exatamente o que a segunda carta permitia — reunir-se e defender a vida (Et 8:11). Do lado da administração, algo que nenhum decreto obrigava: \"E todos os líderes das províncias, e os sátrapas, e os governadores, e os que faziam a obra do rei, auxiliavam os judeus; porque tinha caído sobre eles o temor de Mardoqueu\" (Et 9:3). Depois vêm os quinhentos mortos na fortaleza de Susã e os dez filhos de Hamã, nomeados um a um em três versículos — \"Parsandata, e a Dalfom e a Aspata, E a Porata, e a Adalia, e a Aridata, E a Farmasta, e a Arisai, e a Aridai, e a Vaisata\" (Et 9:7-9) —, a mesma \"multidão de seus filhos\" de que o pai se gabara em 5:11. E então a frase que o capítulo repete três vezes, em 9:10, 9:15 e 9:16, e que é o pudor do livro inteiro: \"porém ao despojo não estenderam a sua mão\". O decreto de Hamã autorizava saquear (Et 3:13) e o de Mardoqueu também (Et 8:11); eles não tocaram em nada. É o contrário exato do que Saul fez com o despojo de Amaleque — \"Saul e o povo pouparam a Agague, e ao melhor das ovelhas e das vacas\" (1Sm 15:9), \"antes te lançaste ao despojo\" (1Sm 15:19). Quatrocentos anos depois, um benjamita da casa de Quis acerta a conta que Saul errou."
    },
    mulherComum: {
      title: "Ester, a rainha, filha de Abiail; as judias que se ajuntaram nas suas cidades; e as mães que ensinaram o Purim aos filhos",
      subtitle: "Et 9 • a mulher que pediu mais um dia, e as que fizeram do dia catorze festa de presentes e dádivas aos pobres",
      text: "Este é o capítulo em que Ester deixa de suplicar e passa a pedir: \"Então disse Ester: Se bem parecer ao rei, conceda-se aos judeus que se acham em Susã que também façam amanhã conforme ao mandado de hoje; e pendurem numa forca os dez filhos de Hamã\" (Et 9:13). O pedido é duro e o texto não o suaviza; pendurar os corpos era exposição pública do fim de uma casa, e a casa em questão é a que jurara acabar com o povo dela. Depois vem a segunda carta, e nela o nome dela vem primeiro: \"Então a rainha Ester, filha de Abiail, e Mardoqueu, o judeu, escreveram com toda autoridade uma segunda vez, para confirmar a carta a respeito de Purim\" (Et 9:29), e é o mandado dela que fecha o livro: \"E o mandado de Ester estabeleceu os sucessos daquele Purim; e escreveu-se no livro\" (Et 9:32). Ao redor dela estão as judias das províncias que se ajuntaram para defender a vida junto com os seus, as que passaram de \"grande luto, com jejum, e choro\" (Et 4:3) a \"dia de alegria e de banquetes\" (Et 9:19), e as mães que a partir daquele ano ensinam a data em casa — porque a ordem é que \"estes dias seriam lembrados e guardados em cada geração, família, província e cidade\" (Et 9:28)."
    },
    multidao: {
      title: "Os judeus que descansaram no dia catorze e no dia quinze, os das aldeias que mandaram presentes uns aos outros e as famílias que tomaram sobre si o Purim",
      subtitle: "Et 9:17-28 • a multidão que fez de um dia de matança marcada um dia de banquetes e dádivas aos pobres",
      text: "O que o texto sublinha não é a vitória, é o DESCANSO: \"Sucedeu isto no dia treze do mês de Adar; e descansaram no dia catorze, e fizeram, daquele dia, dia de banquetes e de alegria\" (Et 9:17), e em Susã, que teve dois dias de luta, \"descansaram no dia quinze\" (Et 9:18) — daí a festa ter duas datas até hoje. A forma que essa alegria toma é registrada com cuidado: \"dia de alegria e de banquetes, e dia de folguedo, e de mandarem presentes uns aos outros\" (Et 9:19), e na carta de Mardoqueu acrescenta-se o que faltava: \"e dádivas aos pobres\" (Et 9:22). Um povo que não tocou no despojo dos inimigos reparte o que é seu com os seus. O motivo dado é uma inversão, não um triunfo: \"o mês que se lhes mudou de tristeza em alegria, e de luto em dia de festa\" (Et 9:22). E a multidão faz o que nenhum decreto pode fazer por ela — toma o compromisso por conta própria: \"Confirmaram os judeus, e tomaram sobre si, e sobre a sua descendência, e sobre todos os que se achegassem a eles, que não se deixaria de guardar estes dois dias\" (Et 9:27), \"e que a memória deles nunca teria fim entre os de sua descendência\" (Et 9:28)."
    },
    rei: {
      title: "Assuero, que perguntou à rainha o que mais ela queria depois do número dos mortos",
      subtitle: "Et 9:11-14 • o rei que recebe o relatório da fortaleza e concede mais um dia sem discutir",
      text: "\"No mesmo dia foi comunicado ao rei o número dos mortos na fortaleza de Susã\" (Et 9:11). É assim que este rei aparece pela última vez em ação: recebendo um número. A reação dele é a de um administrador diante de uma estatística, e faz uma conta em voz alta que só ele acharia natural: \"Na fortaleza de Susã os judeus mataram e destruíram quinhentos homens, e os dez filhos de Hamã; nas mais províncias do rei que teriam feito?\" (Et 9:12). E emenda, pela quarta vez no livro, a mesma pergunta de sempre: \"Qual é, pois, a tua petição? E dar-se-te-á. Ou qual é ainda o teu requerimento? E far-se-á\". Concedido o pedido de Ester, ele despacha em uma linha: \"Então disse o rei que assim se fizesse; e publicou-se um edito em Susã, e enforcaram os dez filhos de Hamã\" (Et 9:14). Do primeiro capítulo ao nono, Assuero foi sempre isto — um homem que assina o que lhe põem à frente, para o mal em 3:10-11 e para o bem em 8:8 e 9:14. O livro nunca lhe atribui um propósito próprio, e nunca lhe põe na boca o nome de um deus."
    },
    servo: {
      title: "Os que faziam a obra do rei nas províncias, os guardas que cumpriram o edito em Susã, os que levaram as cartas do Purim e os meninos que aprenderam a festa",
      subtitle: "Et 9 • a máquina do império virada a favor, e a primeira geração a guardar o Purim",
      text: "\"E todos os líderes das províncias, e os sátrapas, e os governadores, e os que faziam a obra do rei, auxiliavam os judeus; porque tinha caído sobre eles o temor de Mardoqueu\" (Et 9:3). Estes servos são a burocracia inteira do império — a mesma que em 3:12 copiou o decreto de extermínio e o traduziu com esmero para cada língua — agora do outro lado, ajudando por medo de um homem que onze meses antes estava sentado num banco à porta. Outros são os guardas que publicam e executam o edito do segundo dia em Susã (Et 9:14), o oficial que leva ao rei a conta dos mortos da fortaleza (Et 9:11) e os mensageiros que saem com as cartas de Mardoqueu \"aos de perto, e aos de longe\" (Et 9:20). E os últimos servos deste capítulo são os menores: as crianças da casa, a quem se ensina uma data nova e um nome estrangeiro. A ordem é explícita quanto a eles — \"E que estes dias seriam lembrados e guardados em cada geração, família, província e cidade, e que esses dias de Purim não fossem revogados entre os judeus, e que a memória deles nunca teria fim entre os de sua descendência\" (Et 9:28). Não se revoga; é a única coisa em todo o livro que se firma sem o anel do rei."
    }
  },

  // ---------------------------------------------------------------- Et 10
  10: {
    anciao: {
      title: "Mardoqueu, o judeu, o segundo depois do rei Assuero",
      subtitle: "Et 10:3 • o homem da porta do rei no último versículo do livro, procurando o bem do seu povo",
      text: "\"Porque o judeu Mardoqueu foi o segundo depois do rei Assuero, e grande entre os judeus, e estimado pela multidão de seus irmãos, procurando o bem do seu povo, e proclamando a prosperidade de toda a sua descendência\" (Et 10:3). O livro fecha com o mesmo epíteto com que o abriu: \"o judeu\" — nunca deixou de ser um transportado de Jerusalém \"com os cativos que foram levados com Jeconias\" (Et 2:6). O cargo é o mais alto que um estrangeiro podia ter na Pérsia, e o texto o descreve não pelo poder, mas pelo uso do poder: procurar o bem do seu povo e falar em favor da sua descendência. É o retrato oposto ao de Hamã, que tinha \"o seu assento acima de todos os príncipes\" (Et 3:1) e não conseguia gozar de nada \"enquanto eu vir o judeu Mardoqueu assentado à porta do rei\" (Et 5:13). E é o eco distante de outro judeu que foi segundo depois de um rei pagão e usou o cargo para alimentar os seus irmãos — José no Egito (Gn 41:40-44; 45:7). O livro termina sem nomear Deus nem uma vez, e sem explicar como um órfão do cativeiro chegou até ali."
    },
    homem: {
      title: "Os portadores do tributo das ilhas do mar, os cobradores sobre a terra e o cronista dos reis da Média e da Pérsia",
      subtitle: "Et 10:1-2 • o epílogo administrativo: o império volta a fazer o que os impérios fazem",
      text: "\"Depois disto impôs o rei Assuero tributo sobre a terra, e sobre as ilhas do mar\" (Et 10:1). Passada a crise, o livro devolve o mundo ao normal: cobradores nas províncias, fardos descarregados nos cais, o dinheiro subindo para Susã. As \"ilhas do mar\" são a orla e as ilhas do Egeu, o limite ocidental do domínio persa — o mesmo império que começou o livro exibindo as suas riquezas por cento e oitenta dias (Et 1:4) termina cobrando imposto. O último homem da cena é o funcionário dos anais, o mesmo ofício do escriba de 2:23 e do leitor da madrugada de 6:1: \"E todos os atos do seu poder e do seu valor, e o relato da grandeza de Mardoqueu, a quem o rei exaltou, porventura não estão escritos no livro das crônicas dos reis da Média e da Pérsia?\" (Et 10:2). O livro fecha remetendo o leitor a um arquivo persa — e é bom lembrar o que um arquivo desses já fez neste mesmo livro: uma linha esquecida num rolo, lida por acaso numa noite de insônia, foi o que impediu um extermínio."
    },
    mulherComum: {
      title: "Ester, a rainha, no fim do livro que leva o seu nome",
      subtitle: "Et 10 • a mulher que já não precisa aparecer, porque o mandado dela ficou escrito",
      text: "Ester não é citada nos três versículos do último capítulo, e a ausência é o próprio desfecho: o que ela tinha a fazer já está feito e já está por escrito. A última palavra sobre ela veio no capítulo anterior, e é uma palavra de autoridade legal, não de favor: \"E o mandado de Ester estabeleceu os sucessos daquele Purim; e escreveu-se no livro\" (Et 9:32). A órfã de 2:7, que não tinha pai nem mãe e foi levada à casa do rei sem que ninguém lhe perguntasse nada, termina como legisladora de uma festa que o seu povo guarda até hoje. Entre um ponto e outro há uma frase que ela disse quando ainda podia recuar — \"E assim irei ter com o rei, ainda que não seja segundo a lei; e se perecer, pereci\" (Et 4:16) — e uma pergunta que lhe fizeram e que o livro nunca responde: \"e quem sabe se para tal tempo como este chegaste a este reino?\" (Et 4:14). Fica a pergunta, e fica o resultado; o texto não junta os dois para o leitor."
    },
    multidao: {
      title: "A multidão de seus irmãos que estimou a Mardoqueu",
      subtitle: "Et 10:3 • o povo espalhado por cento e vinte e sete províncias, no último quadro do livro",
      text: "\"e grande entre os judeus, e estimado pela multidão de seus irmãos, procurando o bem do seu povo, e proclamando a prosperidade de toda a sua descendência\" (Et 10:3). Esta é a mesma gente que Hamã descreveu ao rei como \"um povo... espalhado e dividido entre os povos em todas as províncias do teu reino\" (Et 3:8) — a dispersão que ele apresentou como ameaça é agora simplesmente o mapa de uma comunidade viva. É a multidão que esteve deitada em saco e cinza em 4:3, que se ajuntou nas suas cidades para defender a vida em 9:2, que descansou no dia catorze e mandou presentes uns aos outros e dádivas aos pobres (Et 9:22), e que tomou sobre si e sobre a sua descendência a guarda de dois dias por ano \"e que a memória deles nunca teria fim\" (Et 9:28). O livro termina com eles em pé, longe de Jerusalém, sem templo, sem profeta e sem uma menção ao nome de Deus — e vivos."
    },
    rei: {
      title: "Assuero, que impôs tributo sobre a terra e sobre as ilhas do mar",
      subtitle: "Et 10:1-2 • o rei do primeiro versículo do livro, no último, fazendo o que os reis fazem",
      text: "\"Depois disto impôs o rei Assuero tributo sobre a terra, e sobre as ilhas do mar\" (Et 10:1). O livro abriu medindo este homem pelo mapa — \"reinou desde a India até a Etiópia, sobre cento e vinte e sete províncias\" (Et 1:1) — e fecha medindo-o pela receita. Nada nele mudou: continua senhor do maior império do mundo conhecido, continua sem plano próprio, continua sendo lembrado pelos anais e não pelos atos. \"E todos os atos do seu poder e do seu valor, e o relato da grandeza de Mardoqueu, a quem o rei exaltou, porventura não estão escritos no livro das crônicas dos reis da Média e da Pérsia?\" (Et 10:2) — a fórmula é a mesma dos livros dos Reis de Israel e de Judá, aplicada aqui a um monarca pagão, e o nome que ela carrega junto com o do rei é o de um judeu do cativeiro. Assuero assinou a morte de um povo sem perguntar quem era (Et 3:10-11) e assinou a sua sobrevivência sem entender direito o que assinava (Et 8:8). Em dez capítulos, nunca nomeia um deus, e nunca é dito que conheceu o que passou por debaixo do seu trono."
    },
    servo: {
      title: "O servo que descarregou o tributo no cais das ilhas do mar",
      subtitle: "Et 10:1 • quem carrega os fardos no último quadro do livro, sem saber de nada do que aconteceu",
      text: "O último servo de Ester é uma figura de rotina: um homem no cais ou na estrada, descarregando os fardos do tributo que \"impôs o rei Assuero tributo sobre a terra, e sobre as ilhas do mar\" (Et 10:1). Ele não esteve no banquete dos cento e oitenta dias, não ouviu o pregão da rua, não leu a carta de Purim; faz o mesmo serviço que faria se Hamã tivesse vencido. E é assim que este livro acaba de propósito: sem milagre, sem coro, sem voz do céu — com o império funcionando, os impostos entrando e a vida seguindo. Todo o peso da história ficou em coisas pequenas e domésticas: um rolo aberto na página certa (Et 6:1-2), um convite adiado para o dia seguinte (Et 5:8), uma forca pronta antes da hora (Et 7:9), uma sorte lançada em Nisã que caiu no último mês do ano (Et 3:7). O livro registra tudo isso e não explica nada. Quem quiser o comentário tem de buscá-lo em outro lugar da Escritura: \"A sorte se lança no regaço, mas do Senhor procede toda a determinação\" (Pv 16:33)."
    }
  }
};
