// Fichas ESPECÍFICAS por (capítulo → papel) de ESDRAS 7–10.
// Cinquenta e oito anos depois de acabada a casa entra um homem que não traz
// pedreiro nenhum: traz um ROLO. O capítulo 7 o apresenta subindo a própria
// genealogia até Arão, o sumo sacerdote, e resume quatro meses de estrada numa
// coisa que não se desenha — "segundo a boa mão do seu Deus sobre ele" —, antes
// de abrir a carta de Artaxerxes por extenso, do "rei dos reis" ao sal à
// vontade. O 8 é gente carregando fardo casa por casa, o rio que vai a Aava
// onde falta uma tribo inteira na chamada, o jejum de quem teve VERGONHA de
// pedir escolta armada, e a prata pesada duas vezes. O 9 é o chão cedendo: as
// vestes rasgadas, os cabelos arrancados, o homem assentado atônito até o
// sacrifício da tarde, e uma oração que não pede nada. O 10 é uma praça
// encharcada no nono mês, gente tremendo de frio e de medo ao mesmo tempo, e
// uma lista de nomes que acaba sem consolo nenhum. Cada figurante destas cenas
// é alguém REAL daquele capítulo — o netineu da caravana, o carregador do
// portão do rio, o moço do pátio do ensino, a mulher que saiu pela estrada no
// último versículo do livro.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_07_10: Record<number, Record<string, StageInfo>> = {
  // ----------------------------------------------------------------- Ed 7
  7: {
    patriarca: {
      title: "Esdras, o escriba hábil na lei de Moisés — e Arão, o sumo sacerdote, em quem a sua genealogia para de subir",
      subtitle: "Ed 7:1-10 • a câmara dos rolos em babilônia, dezesseis degraus de nomes acima, e o versículo que governa o livro",
      text: "O capítulo não apresenta este homem pelo cargo: apresenta-o subindo a própria linhagem, degrau por degrau, de Seraías a Azarias, a Hilquias, a Salum, a Zadoque, a Aitube, a Amarias, a Meraiote, a Zeraquias, a Uzi, a Buqui, a Abisua, até parar em \"Finéias, filho de Eleazar, filho de Arão, o sumo sacerdote\" (Ed 7:5). É por isso que o rolo na mão dele tem direito de estar ali — quem sobe de babilônia é sacerdote de nascimento e escriba de ofício: \"Este Esdras subiu de babilônia; e era escriba hábil na lei de Moisés, que o SENHOR Deus de Israel tinha dado\" (Ed 7:6). Cinquenta e oito anos separam este versículo do fim do capítulo 6, e nenhum pedreiro sobe com ele. A viagem inteira — quatro meses de estrada, do primeiro dia do primeiro mês ao primeiro dia do quinto (Ed 7:9) — é explicada por uma só coisa, que não se desenha: \"segundo a boa mão do seu Deus sobre ele\". E então vem a frase que governa o livro e ordena tudo o mais: \"Porque Esdras tinha preparado o seu coração para buscar a lei do Senhor e para cumpri-la e para ensinar em Israel os seus estatutos e os seus juízos\" (Ed 7:10) — buscar, cumprir, ensinar, nesta ordem, e nunca a terceira antes da segunda. Arão está no quadro porque é onde a subida termina: o irmão de Moisés, o da vara que floresceu e deu amêndoas (Nm 17:8), o primeiro homem a vestir o éfode. E Esdras voltará a aparecer de pé sobre um púlpito de madeira, lendo esta mesma lei desde a alva até o meio-dia (Ne 8:3-4).",
    },
    rei: {
      title: "Artaxerxes, rei dos reis, que deu a Esdras tudo quanto lhe pedira e escreveu a carta por extenso",
      subtitle: "Ed 7:6,11-26 • o pátio de audiência em Susã, o trono e o rolo que atravessa o capítulo inteiro",
      text: "Artaxerxes I, filho de Xerxes, reina sobre a Pérsia no sétimo ano do seu governo, e o texto lhe dá o único título que ele mesmo usa: \"Artaxerxes, rei dos reis, ao sacerdote Esdras, escriba da lei do Deus do céu, paz perfeita, em tal tempo\" (Ed 7:12). A carta que ele dita é o documento mais generoso que um pagão assina em toda a Escritura: quem quiser ir, vá (v. 13); leve a prata e o ouro que o rei e os seus conselheiros voluntariamente deram (v. 15); compre com o dinheiro novilhos, carneiros, cordeiros, ofertas de alimentos e libações (v. 17); restitua os utensílios (v. 19); e o que faltar, tire-se \"da casa dos tesouros do rei\" (Ed 7:20), até cem talentos de prata, cem coros de trigo, cem batos de vinho, cem batos de azeite — \"e sal à vontade\" (Ed 7:22). Ainda isenta de tributo sacerdotes, levitas, cantores, porteiros e servidores do templo (v. 24) e autoriza Esdras a nomear magistrados e juízes (v. 25). O motivo que o rei alega é dele: \"pois, para que haveria grande ira sobre o reino do rei e de seus filhos?\" (Ed 7:23) — política de império, medo de deus estrangeiro. Mas quem lê a carta não a credita a Susã: \"Bendito seja o Senhor Deus de nossos pais, que tal inspirou ao coração do rei\" (Ed 7:27). É o mesmo rei que, treze anos depois, deixará o seu copeiro Neemias ir levantar os muros (Ne 2:1-8).",
    },
    anciao: {
      title: "Os avós sacerdotais de Esdras — Seraías, Salum, Zadoque, Amarias, Buqui e Eleazar — e os anciãos do outro lado da carta: os sete conselheiros do rei, o escriba da corte, o levita que o recebeu em Jerusalém e os juízes que ele haveria de nomear",
      subtitle: "Ed 7:1-5,8,11-14,18,21-28 • a câmara dos rolos, o pátio persa e o portão de Jerusalém",
      text: "Metade destes homens está morta há séculos e só existe como degrau: Seraías, o pai, é o sumo sacerdote que Nabucodonosor matou em Ribla quando a cidade caiu (2Rs 25:18-21); Zadoque é o sacerdote que ficou com Davi na fuga de Absalão e ungiu Salomão em Giom (2Sm 15:24-29; 1Rs 1:39); Amarias é aquele de quem Josafá disse \"Amarias, o sumo sacerdote, presidirá sobre vós em todo o negócio do Senhor\" (2Cr 19:11); Eleazar é o filho de Arão que recebeu as vestes do pai no monte Hor (Nm 20:26-28). A outra metade está viva e é persa: \"és enviado da parte do rei e dos seus sete conselheiros para fazeres inquirição a respeito de Judá e de Jerusalém, conforme à lei do teu Deus, que está na tua mão\" (Ed 7:14) — sete homens do conselho do império assinando a soltura de um povo pequeno; e o escriba da chancelaria que copia o decreto aos tesoureiros dalém do rio, \"que tudo quanto vos pedir o sacerdote Esdras… prontamente se faça\" (Ed 7:21). No fim da estrada, o levita que abre o portão no quinto mês (Ed 7:8) e, adiante, os juízes que a mesma carta manda instituir: \"nomeia magistrados e juízes, que julguem a todo o povo que está dalém do rio\" (Ed 7:25). Um deles é o irmão de Esdras a quem cabe decidir o destino do que sobrar da prata: \"Também o que a ti e a teus irmãos bem parecer fazerdes do restante da prata e do ouro, o fareis conforme a vontade do vosso Deus\" (Ed 7:18) — dinheiro do império entregue sem prestação de contas ao império.",
    },
    homem: {
      title: "Aitube, Azarias, Meraiote, Uzi, Zeraquias e Finéias, degraus da linhagem — e os homens da carta: o tesoureiro do palácio, o tesoureiro-mor da casa dos tesouros, os tesoureiros dalém do rio, o mercador do portão, o cantor e o porteiro que subiram, e os chefes de Israel ajuntados para a subida",
      subtitle: "Ed 7:2-5,7,13-28 • do santuário antigo ao mercado do portão de Susã",
      text: "Os primeiros são nomes de uma escada: Finéias é o neto de Arão que deteve a praga em Sitim e recebeu a palavra \"Eis que lhe dou a minha aliança de paz\" e o sacerdócio perpétuo (Nm 25:12-13); Azarias, Meraiote, Zeraquias e Uzi são a corrente de sumos sacerdotes que 1 Crônicas 6:6-12 registra por escrito, e Aitube é o pai de Zadoque. Os outros são homens vivos, e cada um segura uma peça do decreto. O tesoureiro do palácio conta a prata e o ouro \"que o rei e os seus conselheiros voluntariamente deram ao Deus de Israel, cuja habitação está em Jerusalém\" (Ed 7:15). O tesoureiro-mor abre a conta do rei para o que faltar (v. 20), e os tesoureiros das províncias dalém do Eufrates recebem o teto: cem talentos de prata, cem coros de trigo, cem batos de vinho, cem batos de azeite, \"e sal à vontade\" (Ed 7:22). O mercador do portão é quem vende o que a carta manda comprar: \"Portanto diligentemente comprarás com este dinheiro novilhos, carneiros, cordeiros, com as suas ofertas de alimentos, e as suas libações\" (Ed 7:17). O cantor e o porteiro estão na caravana desde o versículo 7 e figuram de novo entre os isentos de tributo (v. 24) — ofícios do templo, não do palácio. E, no último versículo, os chefes de Israel que aceitam ir: \"Assim me animei, segundo a mão do Senhor meu Deus sobre mim, e ajuntei dentre Israel alguns chefes para subirem comigo\" (Ed 7:28).",
    },
    mulherComum: {
      title: "A mulher da caravana que fez os quatro meses de estrada, a que ofereceu voluntariamente na província de babilônia e a que viu a fila entrar por Jerusalém no quinto mês",
      subtitle: "Ed 7:8-9,16 • as três posições em que uma mulher aparece neste capítulo — a estrada, a oferta e o portão",
      text: "O texto conta a viagem em datas e não em cenas, e é preciso pôr gente dentro delas: \"Pois no primeiro dia do primeiro mês foi o princípio da partida de babilônia; e no primeiro dia do quinto mês chegou a Jerusalém\" (Ed 7:9). Esta mulher andou os quatro meses inteiros, sem escolta armada nenhuma (Ed 8:22), com filho pequeno e cântaro no fardo — e chegou. A segunda está na província e nunca sai dela: a carta manda a Esdras recolher \"toda a prata e o ouro que achares em toda a província de babilônia, com as ofertas voluntárias do povo e dos sacerdotes, que voluntariamente oferecerem, para a casa de seu Deus, que está em Jerusalém\" (Ed 7:16), e boa parte do que se recolhe assim sai de casa em casa, das mãos de quem não vai subir e manda o que tem no lugar do corpo. A terceira mora em Jerusalém e vê chegar, no quinto mês (Ed 7:8), gente de babilônia que ela nunca viu — a segunda leva de retornados, cinquenta e oito anos depois da primeira. Nenhuma delas tem nome. Duas gerações adiante, quando a lei for lida na praça, o texto fará questão de dizer quem estava lá: \"tanto de homens como de mulheres, e todos os que podiam ouvir com entendimento\" (Ne 8:2).",
    },
    multidao: {
      title: "Os filhos de Israel, os sacerdotes, os levitas, os cantores, os porteiros e os servidores do templo que subiram a Jerusalém no sétimo ano de Artaxerxes",
      subtitle: "Ed 7:7 • a segunda leva de retornados, contada por ofícios e não por cabeças",
      text: "\"Também subiram a Jerusalém alguns dos filhos de Israel, dos sacerdotes, dos levitas, dos cantores, dos porteiros e dos servidores do templo, no sétimo ano do rei Artaxerxes\" (Ed 7:7). O versículo é uma lista de ofícios, e é assim que este livro conta gente: não por multidão anônima, mas por função no serviço da casa. O número exato virá no capítulo seguinte, casa paterna por casa paterna, e dá pouco mais de mil e quinhentos homens (Ed 8:1-14) — nada perto dos quarenta e dois mil trezentos e sessenta da primeira volta com Zorobabel (Ed 2:64). Esta é a leva pequena, a que sobe quando já não há novidade nenhuma em subir: o templo está de pé há cinquenta e oito anos, a cidade continua sem muro, e quem parte deixa em babilônia casa feita, ofício e parentela. Cada categoria da fila reaparecerá adiante na carta do rei, isenta de tributo (Ed 7:24), e outra vez no arrolamento de Neemias 7 — porque o serviço do santuário precisava de todas: sem cantor não há canto, sem porteiro não há guarda, e sem netineu não há lenha nem água no altar.",
    },
    rebanho: {
      title: "Os novilhos, os carneiros e os cordeiros que a carta do rei manda comprar diligentemente com a prata da Pérsia",
      subtitle: "Ed 7:17 • o gado do mercado do portão, comprado com dinheiro de império para o altar de Jerusalém",
      text: "\"Portanto diligentemente comprarás com este dinheiro novilhos, carneiros, cordeiros, com as suas ofertas de alimentos, e as suas libações, e as oferecerás sobre o altar da casa de vosso Deus, que está em Jerusalém\" (Ed 7:17). O advérbio é do rei — diligentemente — e a lista que ele dita é exatamente a de Números 15:1-10: o animal nunca sobe sozinho ao altar, vai sempre acompanhado da oferta de alimentos e da libação de vinho. Um monarca persa está a especificar o ritual levítico por escrito, e o faz com o cuidado de quem não quer errar a fórmula: \"Tudo quanto se ordenar, segundo o mandado do Deus do céu, prontamente se faça para a casa do Deus dos céus\" (Ed 7:23). Este gado é comprado na feira do portão com prata voluntária de babilônia, sobe pela estrada os mesmos quatro meses e acaba em fogo no pátio de Jerusalém — e o capítulo 8 mostrará o mesmo rebanho outra vez, já do lado de lá: doze novilhos por todo o Israel, noventa e seis carneiros, setenta e sete cordeiros e doze bodes (Ed 8:35). Toda esta contabilidade de animais aponta para um só: \"Eis o Cordeiro de Deus, que tira o pecado do mundo\" (Jo 1:29).",
    },
    servo: {
      title: "O moço da câmara dos rolos em babilônia, o guarda do tesouro do rei, o guarda dos utensílios restituídos, o carregador do trigo e do vinho da conta real, o mordomo do palácio e os netineus que subiram na caravana",
      subtitle: "Ed 7:1,7-9,15-24 • as mãos que carregam o que a carta apenas escreve",
      text: "O primeiro está no cubículo de estudo do exílio, e o trabalho dele é manter o rolo aberto e o candeeiro aceso numa sala funda: é ali que a genealogia de Ed 7:1-5 é conferida nome por nome, porque sem registro de linhagem não há sacerdócio — foi por não acharem o seu registro que três casas foram excluídas do sacerdócio na primeira volta (Ed 2:62). O segundo abre a arca do tesouro do palácio quando o decreto o manda: \"E tudo mais que for necessário para a casa de teu Deus, que te convenha dar, dá-lo-ás da casa dos tesouros do rei\" (Ed 7:20). O terceiro embala os vasos do santuário que a Pérsia devolve: \"E os utensílios que te foram dados para o serviço da casa de teu Deus, restitui-os perante o Deus de Jerusalém\" (Ed 7:19) — o mesmo despojo que Nabucodonosor levara e Ciro começara a devolver a Sesbazar (Ed 1:7-11). O quarto pesa o trigo, o vinho e o azeite do teto real, e ainda o sal, que a carta não limita (Ed 7:22). E os últimos são os netineus, os servidores do templo, gente de origem estrangeira dada por Davi e pelos príncipes ao ministério dos levitas (Ed 8:20): sobem na fila do versículo 7, entram em Jerusalém no quinto mês, e a carta do rei os nomeia entre os que ficam livres de \"tributo, nem contribuição, nem renda\" (Ed 7:24) — os mais baixos do serviço, isentos por escrito junto com os sacerdotes.",
    },
  },

  // ----------------------------------------------------------------- Ed 8
  8: {
    patriarca: {
      title: "Esdras no rio que vai a Aava: o que atenta para o povo e descobre que falta uma tribo inteira, o que teve vergonha de pedir escolta e o que pesa a prata duas vezes",
      subtitle: "Ed 8:15,21-23,31-34 • três dias de acampamento, um jejum e quatro meses de estrada sem soldado nenhum",
      text: "\"E ajuntei-os perto do rio que vai a Aava, e ficamos ali acampados três dias. Então atentei para o povo e para os sacerdotes, e não achei ali nenhum dos filhos de Levi\" (Ed 8:15). O verbo é o do capítulo: ele ATENTA — passa os olhos pela sua própria gente antes de partir e vê o buraco no meio dela. Manda onze homens a Casifia, a Ido, e volta com Serebias, Hasabias e duzentos e vinte servidores do templo (v. 17-20). Depois apregoa jejum junto ao rio, \"para nos humilharmos diante da face de nosso Deus, para lhe pedirmos caminho seguro para nós, para nossos filhos e para todos os nossos bens\" (Ed 8:21), e explica por que não pediu tropa: \"Porque tive vergonha de pedir ao rei exército e cavaleiros para nos defenderem do inimigo pelo caminho\", \"porquanto tínhamos falado ao rei, dizendo: A mão do nosso Deus é sobre todos os que o buscam, para o bem deles; mas o seu poder e a sua ira contra todos os que o deixam\" (Ed 8:22). A vergonha não é de Deus: é de desdizer, diante de um pagão, uma frase que já saíra da sua boca. Então pesa a prata, o ouro e os vasos na mão de doze sacerdotes — \"Vós sois santos ao Senhor, e são santos estes utensílios\" (Ed 8:28) —, atravessa o deserto com uma fortuna e sem guarda, e manda pesar tudo outra vez ao chegar: \"Tudo foi contado e pesado; e todo o peso foi registrado na mesma ocasião\" (Ed 8:34). Não faltou nada.",
    },
    rei: {
      title: "Artaxerxes no flashback do versículo 22: o rei a quem Esdras já dissera, na cara, que a mão do seu Deus é sobre todos os que o buscam",
      subtitle: "Ed 8:22 • a sala persa lembrada de dentro do jejum, com o cavalo e a lança da escolta parados e recusados",
      text: "Este quadro é memória, não presente: enquanto o povo jejua junto ao rio Aava, Esdras se lembra da audiência em que tudo se decidiu. \"porquanto tínhamos falado ao rei, dizendo: A mão do nosso Deus é sobre todos os que o buscam, para o bem deles; mas o seu poder e a sua ira contra todos os que o deixam\" (Ed 8:22). Foi uma pregação feita diante do trono, e o preço dela chega quatro meses depois: pedir agora exército e cavaleiros seria confessar, diante do mesmo homem que assinou a carta, que a frase era de ocasião. O rei está desenhado com o que ELE OFERECIA e não foi levado — o cavalo de guerra e a lança da escolta, disponíveis, parados. A caravana atravessa o deserto carregando seiscentos e cinquenta talentos de prata, cem talentos de ouro e vasos de bom metal lustroso (Ed 8:26-27), e o único relatório de segurança do capítulo é este: \"e a mão do nosso Deus estava sobre nós, e livrou-nos da mão dos inimigos, e dos que nos armavam ciladas pelo caminho\" (Ed 8:31). Neemias, no mesmo reinado e com outra consciência, aceitaria capitães e cavaleiros sem constrangimento (Ne 2:9) — o texto não corrige nenhum dos dois.",
    },
    anciao: {
      title: "Os chefes das casas paternas que subiram com Esdras — Gérson dos filhos de Finéias, os anciãos de Secanias, de Elão, de Sefatias e de Adonicão — e Ido, o chefe em Casifia, Serebias, Hasabias, Meremote filho de Urias e o governador dalém do rio",
      subtitle: "Ed 8:1-14,17-19,24,33,36 • do portão do rio em babilônia à câmara da pesagem em Jerusalém",
      text: "\"Estes, pois, são os chefes das casas paternas e esta a genealogia dos que subiram comigo de babilônia no reinado do rei Artaxerxes\" (Ed 8:1). O que vem depois não é arquivo: é a chamada de embarque, casa por casa, feita ao amanhecer num portão de muralha. Gérson vem dos filhos de Finéias e Daniel dos de Itamar — as duas linhas sacerdotais de Arão abrem a fila (v. 2). Depois vêm Secanias, Parós, Paate-Moabe, Adim, Elão, Sefatias, Joabe, Selomite, Bebai, Azgade, Adonicão e Bigvai, cada uma com o seu ancião à frente e o seu número atrás. Falta uma inteira, e é isso que o versículo 15 descobre. Ido é o chefe em Casifia, um povoado de levitas e netineus em terra estrangeira, e é dele que saem os que faltavam: \"E trouxeram-nos, segundo a boa mão de Deus sobre nós, um homem entendido, dos filhos de Mali, filho de Levi, filho de Israel, a saber: Serebias, com os seus filhos e irmãos, dezoito\" (Ed 8:18); e logo Hasabias, com Jesaías dos filhos de Merari, e mais vinte (v. 19). Os dois entram para os doze chefes dos sacerdotes que carregam a prata (v. 24) e reaparecerão em Neemias, à frente do povo na leitura da lei e na grande confissão (Ne 8:7; 9:4-5). No fim da estrada, na câmara da pesagem, quem recebe é Meremote, filho do sacerdote Urias (Ed 8:33). E o último ancião do capítulo é persa: o governador da província dalém do rio que lê as ordens do rei e faz o inesperado — \"e estes ajudaram o povo e a casa de Deus\" (Ed 8:36).",
    },
    homem: {
      title: "Os homens da subida: Hatus dos filhos de Davi, Zacarias de Parós, Elioenai filho de Zacarias, Ebede, Jesaías, Zebadias, Obadias, o filho de Josifias, Joanã filho de Hacatã, Elifelete, Jeiel e Semaías dos últimos filhos de Adonicão, Utai e Zabude — os onze chefes enviados a Casifia, o escriba da pesagem, o sátrapa persa e o salteador que armava cilada pelo caminho",
      subtitle: "Ed 8:2-14,16-17,25-27,31,36 • a fila das casas paternas, a estrada de Casifia e a emboscada que não aconteceu",
      text: "A lista de Ed 8:2-14 tem catorze casas, e uma delas cala o quadro inteiro: \"dos filhos de Davi, Hatus\" (Ed 8:2) — a casa real de Judá sobe de babilônia como mais uma casa paterna, sem trono, sem coroa e sem nota de rodapé; 1 Crônicas 3:22 o põe entre os netos de Zorobabel, e é este o fio pelo qual a promessa a Davi atravessa o exílio até a genealogia de Mateus 1:12-13. Os outros são cabeças de família com número atrás do nome: Zacarias com cento e cinquenta, Elioenai com duzentos, Ebede com cinquenta, Jesaías com setenta, Zebadias com oitenta, Obadias com duzentos e dezoito, Joanã com cento e dez. Três deles carregam um detalhe triste: \"E dos últimos filhos de Adonicão, cujos nomes eram estes: Elifelete, Jeiel e Semaías\" (Ed 8:13) — os ÚLTIMOS, os que ficaram para trás na primeira volta e vêm agora, sessenta homens atrasados por uma geração. Os onze enviados a Casifia são gente de recado, e o texto os nomeia um a um porque a missão era delicada: convencer levitas confortáveis a largar o que tinham (v. 16). O escriba da pesagem lança em rolo os seiscentos e cinquenta talentos de prata, os cem talentos de ouro e as vinte bacias de mil dracmas (v. 26-27). O sátrapa recebe as ordens do rei no posto da província (v. 36). E o último homem do capítulo é o que não aparece: \"os que nos armavam ciladas pelo caminho\" (Ed 8:31) — a espada ficou atrás da pedra, e a caravana sem escolta passou.",
    },
    cavaleiro: {
      title: "O cavaleiro que Esdras NÃO pediu ao rei — a escolta oferecida, disponível e recusada por causa de uma frase já dita",
      subtitle: "Ed 8:22 • a lembrança da sala persa dentro do jejum junto ao rio Aava",
      text: "Esta figura está em cena por ausência, e é o único caso do livro em que o que importa é o que ficou de fora do quadro: \"Porque tive vergonha de pedir ao rei exército e cavaleiros para nos defenderem do inimigo pelo caminho\" (Ed 8:22). O caminho de babilônia a Jerusalém tem mais de mil e quinhentos quilômetros de estrada mal guardada, e a caravana leva mulheres, crianças e uma fortuna em prata e ouro — exatamente o alvo que qualquer bando esperaria. A escolta existia, era do direito dele pedi-la, e o rei que lhe dera \"tudo quanto lhe pedira\" (Ed 7:6) não lha negaria. O que o impede é a memória de uma pregação: já dissera na cara do rei que \"A mão do nosso Deus é sobre todos os que o buscam\". O cavaleiro persa é, portanto, o preço da palavra dada — e o texto não faz disso heroísmo nem regra: registra o jejum, registra a oração, e registra a resposta com a mesma secura: \"Nós, pois, jejuamos, e pedimos isto ao nosso Deus, e moveu-se pelas nossas orações\" (Ed 8:23). Neemias, no mesmo reinado, subiu com capitães do exército e cavaleiros que o rei enviou com ele (Ne 2:9), e a Escritura não repreende nenhum dos dois.",
    },
    mulherComum: {
      title: "As mulheres das casas paternas que subiram — de Paate-Moabe, de Adim, de Elão, de Selomite, de Merari — e a mulher do acampamento do rio Aava, que jejuou três dias com os filhos",
      subtitle: "Ed 8:4-10,15,21,32 • as tendas armadas fora do muro, a fila dos jumentos e a margem do rio",
      text: "A lista do capítulo conta homens — \"e com ele duzentos homens\", \"e com ele trezentos homens\" —, mas quem levanta e desmonta tenda são elas, e o próprio texto o diz quando chega ao jejum: \"para nos humilharmos diante da face de nosso Deus, para lhe pedirmos caminho seguro para nós, para nossos filhos e para todos os nossos bens\" (Ed 8:21). Para nossos filhos: são famílias inteiras na estrada, e não uma tropa. Esta mulher amarrou o fardo no lombo do jumento no portão do rio em babilônia, dormiu fora do muro na véspera, atravessou quatro meses de deserto sem soldado nenhum à frente da coluna e ficou três dias sem comer na margem de Aava com criança pequena ao lado. Chegando a Jerusalém, foi ela quem armou a última tenda: \"E chegamos a Jerusalém, e repousamos ali três dias\" (Ed 8:32). Uma geração depois, quando a lei for lida na praça, o texto fará questão de contar quem estava lá — \"perante a congregação, tanto de homens como de mulheres\" (Ne 8:2) —, e a gente que ouviu era esta, ou os filhos dela.",
    },
    multidao: {
      title: "Os números da chamada: cento e cinquenta de Parós, duzentos de Paate-Moabe, trezentos de Secanias, duzentos e dezoito de Joabe, cento e sessenta de Selomite, cento e dez de Azgade — e os duzentos e vinte servidores do templo que Davi e os príncipes deram ao ministério dos levitas",
      subtitle: "Ed 8:3-12,20 • a fila que se forma no portão do rio, casa por casa, com o número atrás de cada nome",
      text: "Cada bloco desta multidão é uma casa paterna com o seu chefe à frente e o seu número atrás: \"Dos filhos de Secanias, e dos filhos de Parós, Zacarias, e com ele, segundo a genealogia, se contaram até cento e cinqüenta homens\" (Ed 8:3), e assim por diante até Bigvai. Somados os catorze grupos, dá cerca de mil e quinhentos homens — com mulheres e crianças, talvez cinco mil pessoas na estrada. É pouco: a volta com Zorobabel tinha sido de quarenta e dois mil trezentos e sessenta (Ed 2:64). O último bloco não é de Israel de sangue: \"E dos servidores do templo que Davi e os príncipes deram para o ministério dos levitas, duzentos e vinte servidores do templo; que foram todos mencionados por seus nomes\" (Ed 8:20). Netineus — descendentes de estrangeiros dados ao serviço da casa, como os gibeonitas que Josué pôs a rachar lenha e a tirar água (Js 9:27) —, e o texto faz questão de dizer que TODOS foram mencionados por seus nomes. Duzentos e vinte homens da base do serviço, cada um chamado pelo próprio nome numa lista que nem sequer os nomeia. Na conta final da caravana, é este grupo que enche o buraco que o versículo 15 tinha aberto.",
    },
    rebanho: {
      title: "Os doze novilhos por todo o Israel, os noventa e seis carneiros, os setenta e sete cordeiros e os doze bodes do sacrifício pelo pecado",
      subtitle: "Ed 8:35 • o altar dos que voltaram do cativeiro, no pátio de Jerusalém, ainda com a poeira da estrada",
      text: "\"E os exilados, que vieram do cativeiro, ofereceram holocaustos ao Deus de Israel: doze novilhos por todo o Israel, noventa e seis carneiros, setenta e sete cordeiros, e doze bodes em sacrifício pelo pecado; tudo em holocausto ao Senhor\" (Ed 8:35). Os números são teologia. DOZE novilhos e DOZE bodes: uma gente que voltou de duas ou três tribos oferece pelas doze, porque não se reconhece como resto de Judá, e sim como Israel inteiro — a mesma conta que Elias fizera com doze pedras no Carmelo (1Rs 18:31). Noventa e seis carneiros são oito vezes doze; setenta e sete cordeiros são o número da plenitude repetido. Os bodes vêm por último e com destino declarado: sacrifício pelo pecado, o rito de Levítico 4 em que a culpa passa da cabeça do homem para a cabeça do animal. Este gado não foi comprado em Jerusalém: subiu a estrada, comprado com a prata voluntária de babilônia, como a carta do rei mandara — \"diligentemente comprarás com este dinheiro novilhos, carneiros, cordeiros\" (Ed 7:17). Chegou vivo, e é a primeira coisa que a caravana faz depois de pesar a prata: antes de qualquer reunião, o fogo.",
    },
    servo: {
      title: "Os carregadores do portão do rio, os que amarraram os fardos da partida ao meio-dia, os que levaram os seiscentos e cinquenta talentos de prata, os meninos das casas de Adim, de Paate-Moabe e de Serebias, os irmãos de Ido em Casifia, o correio do governo dalém do rio e Noadias, filho de Binui, o levita da pesagem",
      subtitle: "Ed 8:1-14,17,25-33,36 • as costas em que este capítulo inteiro viaja",
      text: "O capítulo é feito de peso, e alguém carrega cada grama dele. No portão do rio em babilônia, ao amanhecer, são estes que erguem o primeiro fardo para o lombo do jumento enquanto o rolo da genealogia é lido em voz alta. Ao meio-dia da véspera, empilham as caixas, o feixe do mantimento e o cântaro do azeite no pátio de carga. Na margem de Aava, recebem à mão o que a balança acabou de marcar: \"E pesei em suas mãos seiscentos e cinqüenta talentos de prata, e em vasos de prata cem talentos, e cem talentos de ouro\" (Ed 8:26) — mais de vinte toneladas de metal repartidas por costas humanas, sem carro de guerra e sem escolta. O encargo que recebem não é de estivador: \"Vigiai, pois, e guardai-os até que os peseis na presença dos chefes dos sacerdotes e dos levitas, e dos chefes dos pais de Israel, em Jerusalém, nas câmaras da casa do Senhor\" (Ed 8:29). Em Casifia estão os irmãos de Ido, netineus de um povoado inteiro dedicado ao serviço do templo em terra estrangeira, e é de lá que saem os duzentos e vinte (v. 17,20). Os meninos vão nas tendas, entre as casas de Adim, de Paate-Moabe e de Serebias — este último com os seus filhos e irmãos, dezoito ao todo (v. 18). E, na câmara da pesagem, Noadias, filho de Binui, é um dos dois levitas que conferem a conta contra a de babilônia, com Jozabade, filho de Jesuá (Ed 8:33).",
    },
  },

  // ----------------------------------------------------------------- Ed 9
  9: {
    patriarca: {
      title: "Esdras com as vestes rasgadas, os cabelos arrancados e assentado atônito até o sacrifício da tarde — e depois de joelhos, com as mãos estendidas",
      subtitle: "Ed 9:3-6,15 • o pátio do ensino virado do avesso, e uma oração que acaba sem pedir nada",
      text: "A notícia chega numa manhã comum, com o rolo ainda aberto sobre o estrado, e derruba o quadro inteiro: \"E, ouvindo eu tal coisa, rasguei as minhas vestes e o meu manto, e arranquei os cabelos da minha cabeça e da minha barba, e sentei-me atônito\" (Ed 9:3). São quatro gestos em fila, e o último é o mais estranho: ele não fala, não convoca, não decreta — SENTA-SE. E fica sentado horas: \"porém eu permaneci sentado atônito até ao sacrifício da tarde\" (Ed 9:4). Só à hora do holocausto vespertino é que se move, e o texto marca o corpo em cada etapa: \"me levantei da minha aflição, havendo já rasgado as minhas vestes e o meu manto, e me pus de joelhos, e estendi as minhas mãos para o Senhor meu Deus\" (Ed 9:5). A oração que sai dali não usa a terceira pessoa uma única vez — é sempre NÓS, embora ele não tenha tomado mulher estrangeira nenhuma: \"Meu Deus! Estou confuso e envergonhado, para levantar a ti a minha face, meu Deus; porque as nossas iniqüidades se multiplicaram sobre a nossa cabeça, e a nossa culpa tem crescido até aos céus\" (Ed 9:6). Fala de graça medida a colher — \"por um pequeno momento\" —, de \"uma estaca no seu santo lugar\" e de \"uma parede de proteção em Judá e em Jerusalém\" (Ed 9:8-9). E termina sem pedido nenhum, só dizendo onde estão: \"eis que estamos diante de ti, na nossa culpa, porque ninguém há que possa estar na tua presença, por causa disto\" (Ed 9:15). Nenhuma voz responde do céu neste capítulo. O que responde é uma multidão que se ajunta chorando (Ed 10:1).",
    },
    anciao: {
      title: "Os príncipes que se chegaram a Esdras com a denúncia — e o sacerdote que acendeu o sacrifício da tarde enquanto ele estava sentado atônito",
      subtitle: "Ed 9:1-2,4-5 • o alpendre do templo numa manhã comum, e o altar que continuou funcionando",
      text: "\"Acabadas, pois, estas coisas, chegaram-se a mim os príncipes, dizendo: O povo de Israel, os sacerdotes e os levitas, não se têm separado dos povos destas terras, seguindo as abominações dos cananeus, dos heteus, dos perizeus, dos jebuseus, dos amonitas, dos moabitas, dos egípcios, e dos amorreus\" (Ed 9:1). Estes anciãos não são acusados: são os que vieram contar, e a lista de povos que recitam é a de Deuteronômio 7:1-3, dita como se o exílio nunca tivesse acontecido. A frase que eles guardam para o fim é a que arrebenta o capítulo: \"e até os príncipes e magistrados foram os primeiros nesta transgressão\" (Ed 9:2) — quem devia julgar o caso é o primeiro nome do processo. O segundo ancião em cena não diz nada e não interrompe nada: é o sacerdote de turno, que às três da tarde acende o holocausto vespertino como em qualquer outro dia (Êx 29:39). É essa hora fixa, que não depende do humor de ninguém, que serve de relógio à aflição — \"perto do sacrifício da tarde me levantei da minha aflição\" (Ed 9:5). Daniel, em babilônia, tinha recebido a visão do varão Gabriel exatamente \"à hora do sacrifício da tarde\" (Dn 9:21); aqui a mesma hora não traz visão nenhuma, só permite que um homem se levante do chão.",
    },
    homem: {
      title: "Os que tremiam das palavras do Deus de Israel, o magistrado que foi o primeiro nesta transgressão, o cativo levado à espada nos dias dos pais e o homem do remanescente que escapou",
      subtitle: "Ed 9:2,4,7,13-15 • os quatro tipos de homem que a oração de Esdras põe em cena",
      text: "O primeiro chega sem ser chamado: \"Então se ajuntaram a mim todos os que tremiam das palavras do Deus de Israel por causa da transgressão dos do cativeiro\" (Ed 9:4). É gente que ainda estremece diante do que está escrito — Isaías dissera que o SENHOR olha \"para o pobre e abatido de espírito, e que treme da minha palavra\" (Is 66:2) —, e são eles que ficam de pé em volta do homem sentado no chão. O segundo é o oposto exato: um magistrado, que tinha por ofício aplicar a lei, e de quem o próprio relatório diz que \"até os príncipes e magistrados foram os primeiros nesta transgressão\" (Ed 9:2). O terceiro é memória e está no quadro da espada e do cativeiro: \"por causa das nossas iniqüidades somos entregues, nós e nossos reis e os nossos sacerdotes, na mão dos reis das terras, à espada, ao cativeiro, e ao roubo, e à confusão do rosto, como hoje se vê\" (Ed 9:7) — o avô deste homem morreu assim. E o quarto é o que a oração chama de resto: \"ainda nos deste um remanescente como este\" (Ed 9:13), \"pois ficamos qual um remanescente que escapou, como hoje se vê\" (Ed 9:15). É a palavra que atravessa os profetas — Isaías 10:20-22, Amós 5:15 — e que aqui não é consolo, é advertência: quem escapou uma vez não tem margem para repetir a coisa que o levou embora. O capítulo acaba sem que nenhum deles diga uma palavra.",
    },
    mulherComum: {
      title: "A mulher que tremia das palavras do Deus de Israel, a cativa levada nos dias dos pais e a mulher do remanescente que escapou",
      subtitle: "Ed 9:4,7,11-15 • as três mulheres da oração: a que está de pé no pátio, a que foi levada e a que ficou",
      text: "A primeira está em cena e calada: entre \"todos os que tremiam das palavras do Deus de Israel\" (Ed 9:4) há mulheres da congregação que se ajuntaram ao homem sentado no chão e ficaram ali as horas todas, até o sacrifício da tarde. A segunda é lembrança, e a oração a nomeia sem a nomear: \"Desde os dias de nossos pais até ao dia de hoje estamos em grande culpa, e por causa das nossas iniqüidades somos entregues… à espada, ao cativeiro, e ao roubo, e à confusão do rosto\" (Ed 9:7) — a avó desta gente saiu de Jerusalém amarrada. A terceira é a que ficou, e é sobre ela que a oração faz a sua única citação profética direta: \"vossas filhas não dareis a seus filhos, e suas filhas não tomareis para vossos filhos\" (Ed 9:12), palavra que vem de Deuteronômio 7:3 e de Êxodo 34:16. O problema do capítulo não é etnia — Raabe, a cananeia, e Rute, a moabita, estão na genealogia do Messias (Mt 1:5) —, é culto: o que se temia era a filha que trouxesse o deus dela para dentro de casa, como aconteceu com as mulheres estrangeiras de Salomão, que \"lhe perverteram o coração\" (1Rs 11:3-4). A oração acaba sem pedir nada, e nenhuma destas mulheres responde: quem responderá é a congregação inteira, no capítulo seguinte, chorando com grande choro.",
    },
    servo: {
      title: "O moço do pátio do ensino, que ficou com o rolo caído no chão, o pedreiro da parede de proteção em Judá e em Jerusalém, e o menino do remanescente que escapou",
      subtitle: "Ed 9:1,3,9,13 • os três serviços que continuam enquanto um homem está sentado atônito",
      text: "O primeiro é o moço que arruma o estrado do ensino: chegou de manhã, abriu o rolo, acendeu o candeeiro do canto e deixou tudo pronto — e é neste quadro arrumado que a notícia entra e derruba tudo. Quando o mestre rasga as vestes e se senta no chão, o rolo fica caído onde caiu, e ninguém o levanta até o sacrifício da tarde (Ed 9:3-5). O segundo trabalha numa imagem da própria oração: \"para levantarmos a casa do nosso Deus, e para restaurarmos as suas assolações; e para que nos desse uma parede de proteção em Judá e em Jerusalém\" (Ed 9:9). Jerusalém ainda não tem muro nesta data — faltam treze anos para Neemias —, e a \"parede de proteção\" de que Esdras fala é a benignidade dos reis da Pérsia, não pedra assentada; o pedreiro em cena assenta o pouco que se pode assentar sob licença de império. O terceiro é criança e é o argumento final da oração: \"ainda nos deste um remanescente como este\" (Ed 9:13). Este menino é o resto que escapou — neto de gente levada à espada e ao cativeiro (v. 7) —, e é dele que a pergunta do versículo 14 trata: \"até que não ficasse remanescente nem quem escapasse?\". Ele não fala; está de pé ao lado de um homem ajoelhado com as mãos estendidas, e é por causa dele que a oração dói.",
    },
  },

  // ---------------------------------------------------------------- Ed 10
  10: {
    patriarca: {
      title: "Esdras prostrado diante da casa de Deus, o que ajuramentou os chefes, o que não comeu pão nem bebeu água na câmara de Joanã e o que se levantou debaixo da chuva para falar",
      subtitle: "Ed 10:1,5-6,10-11,16-17,44 • do chão da praça à mesa da comissão que examinou o negócio de mês a mês",
      text: "Ele começa o capítulo no chão e de costas para todos: \"E enquanto Esdras orava, e fazia confissão, chorando e prostrando-se diante da casa de Deus, ajuntou-se a ele, de Israel, uma grande congregação de homens, mulheres e crianças; pois o povo chorava com grande choro\" (Ed 10:1). Quem o levanta não é ele nem uma voz do céu: é Secanias, filho de Jeiel, que lhe diz \"Levanta-te, pois, porque te pertence este negócio, e nós seremos contigo; esforça-te, e age\" (Ed 10:4). Então se levanta e ajuramenta os chefes dos sacerdotes, dos levitas e todo o Israel, \"e eles juraram\" (Ed 10:5). E, feito isso, some: entra na câmara de Joanã, filho de Eliasibe, e ali \"não comeu pão, e nem bebeu água; porque lamentava pela transgressão dos do cativeiro\" (Ed 10:6) — a mesa do quarto está vazia, e o quadro inteiro é a falta do que devia estar sobre ela. Reaparece de pé numa praça encharcada, no nono mês, aos vinte dias, para dizer a frase mais curta e mais dura do livro: \"Vós tendes transgredido, e casastes com mulheres estrangeiras, aumentando a culpa de Israel\" (Ed 10:10). Depois senta-se com os chefes dos pais no primeiro dia do décimo mês e só acaba no primeiro dia do primeiro mês — três meses de inquirição, caso a caso (v. 16-17). E o livro termina com ele calado, no versículo em que ninguém diz nada: \"Todos estes tomaram mulheres estrangeiras; e alguns deles tinham mulheres de quem tiveram filhos\" (Ed 10:44).",
    },
    anciao: {
      title: "Os anciãos da grande congregação que chorou, o conselho que fixou os três dias, os anciãos de cada cidade chamados em tempos apontados, os chefes dos pais apontados para a inquirição, Joanã filho de Eliasibe, Mesulão que se opôs — e os nomes da lista: Maaséias de Jesuá, Maaséias de Harim, Netanel de Pasur, Jozabade o levita, Malquias de Parós, Jeiel de Elão, Zabade de Zatu, Atlai de Bebai, Bezalel de Paate-Moabe, Jeremai de Hasum, Matitias de Nebo e os sete de Bani",
      subtitle: "Ed 10:1-9,14-16,18-43 • a praça, a câmara da inquirição e as casas chamadas uma a uma",
      text: "Estes anciãos aparecem em três posições diferentes, e é preciso não os confundir. Os primeiros estão na praça, na chuva, e não decidem nada: são os cabeças de família da \"grande congregação de homens, mulheres e crianças\" que se ajuntou ao homem prostrado (Ed 10:1). Os segundos governam: \"E que todo aquele que em três dias não viesse, segundo o conselho dos príncipes e dos anciãos, toda a sua fazenda se poria em interdito, e ele seria separado da congregação dos do cativeiro\" (Ed 10:8) — prazo curto e pena pesada, confisco e excomunhão. Os terceiros são chamados de fora, cidade por cidade: \"e todos os que em nossas cidades casaram com mulheres estrangeiras venham em tempos apontados, e com eles os anciãos de cada cidade, e os seus juízes\" (Ed 10:14). E os últimos estão na lista final, e não são um bloco anônimo: cada grupo é uma casa e um ofício. A lista abre pelos sacerdotes — \"Dos filhos de Jesuá, filho de Jozadaque, e seus irmãos, Maaséias, e Eliezer, e Jaribe, e Gedalias\" (Ed 10:18), a casa do sumo sacerdote que voltara com Zorobabel —, passa por Imer, Harim e Pasur, desce aos levitas, aos cantores e aos porteiros, e só então chega \"de Israel\": Parós, Elão, Zatu, Bebai, Bani, Paate-Moabe, Harim outra vez, Hasum, Bani em nove versículos seguidos e Nebo no fim. Um destes anciãos, porém, está do outro lado: \"e Mesulão, e Sabetai, levita, os ajudaram\" (Ed 10:15) — o texto guarda o nome de quem discordou. E há ainda Joanã, filho de Eliasibe, dono da câmara em que Esdras se recolheu sem comer pão nem beber água (Ed 10:6).",
    },
    homem: {
      title: "Secanias, filho de Jeiel, que falou primeiro; Jônatas, Jaseías, Mesulão e Sabetai, os quatro que se opuseram; o arauto do pregão; a voz que respondeu debaixo da chuva; o homem cuja fazenda se poria em interdito; e a lista casa por casa — Jesuá, Imer, Harim, Pasur, os levitas, o cantor, os porteiros, Parós, Elão, Zatu, Bebai, Bani, Paate-Moabe, Hasum e Nebo",
      subtitle: "Ed 10:2-4,7-15,18-43 • quem tomou a palavra, quem discordou e quem foi chamado pelo nome",
      text: "Quem abre a boca primeiro neste capítulo não é Esdras: \"Então Secanias, filho de Jeiel, um dos filhos de Elão, tomou a palavra e disse a Esdras: Nós temos transgredido contra o nosso Deus, e casamos com mulheres estrangeiras dentre os povos da terra, mas, no tocante a isto, ainda há esperança para Israel\" (Ed 10:2). É a única palavra de esperança do capítulo, e vem de uma casa que aparece na lista dos culpados três vezes (v. 26). O arauto passa em seguida: pregão por Judá e Jerusalém, três dias de prazo, e a conta começa a correr quando o som acaba (v. 7-8) — quem não vier perde a fazenda. No nono mês, aos vinte dias, a praça enche, e a resposta não vem de multidão em festa, vem de uma voz só, encharcada e prática: \"Porém o povo é muito, e também é tempo de grandes chuvas, e não se pode estar aqui fora; nem é obra de um dia nem de dois, porque somos muitos os que transgredimos neste negócio\" (Ed 10:13). Quatro homens, porém, ficam parados enquanto o resto se move: \"Porém, somente Jônatas, filho de Asael, e Jaseías, filho de Ticva, se opuseram a isto; e Mesulão, e Sabetai, levita, os ajudaram\" (Ed 10:15) — o texto podia tê-los apagado e escreveu os quatro nomes. Depois vem a lista, e cada trecho dela é uma casa com endereço: os sacerdotes de Jesuá, de Imer, de Harim e de Pasur; os levitas, entre eles \"Quelaías (este é Quelita)\" (Ed 10:23), que aparece de novo ensinando a lei ao povo em Neemias 8:7; o cantor Eliasibe e os porteiros Salum, Telém e Uri (v. 24); e então \"de Israel\", gente comum, com Bani abrindo-se em nove versículos e sendo a casa mais numerosa de todas.",
    },
    mulherComum: {
      title: "A mulher da grande congregação que chorou com grande choro, a que ouviu o pregão, a que tremeu na praça debaixo das grandes chuvas — e as mulheres estrangeiras despedidas no último versículo do livro",
      subtitle: "Ed 10:1,7,9,44 • do choro da praça à estrada por onde elas saíram, com os filhos",
      text: "As três primeiras estão do lado de dentro: \"ajuntou-se a ele, de Israel, uma grande congregação de homens, mulheres e crianças; pois o povo chorava com grande choro\" (Ed 10:1) — o texto faz questão de dizer que havia mulheres e crianças na praça, e o choro não é do líder, é do povo. Depois ouvem o pregão que corre por Judá e Jerusalém (v. 7) e voltam a sentar-se no chão molhado no nono mês: \"e todo o povo se assentou na praça da casa de Deus, tremendo por este negócio e por causa das grandes chuvas\" (Ed 10:9) — tremendo de frio e de medo ao mesmo tempo, e o versículo põe as duas causas na mesma frase, sem separar. As duas últimas estão do lado de fora, e o livro acaba nelas: \"Todos estes tomaram mulheres estrangeiras; e alguns deles tinham mulheres de quem tiveram filhos\" (Ed 10:44). É o último versículo de Esdras, e não há consolo nenhum nele: não se diz para onde foram, quem as recebeu, o que comeram no caminho, nem o que foi feito das crianças. O quadro é de saída — a porta da cidade às costas, o fardo do que coube levar no lombo do jumento, a lua por cima. A Escritura não elogia esta medida nem a repete: Malaquias, na mesma geração, dirá que o SENHOR aborrece o repúdio (Ml 2:16), e Paulo mandará o contrário ao crente casado com incrédula que consente em morar com ele (1Co 7:12-13).",
    },
    servo: {
      title: "A criança que chorou com os pais na praça, o menino que tremeu debaixo das grandes chuvas, o moço da câmara de Joanã com a mesa vazia, o moço do portão do interdito, o do altar do delito, o da câmara da inquirição — e o filho e a filha que saíram com a mãe no último versículo",
      subtitle: "Ed 10:1,6,8-9,16,19,44 • os menores desta cena, que não votaram em nada e pagaram tudo",
      text: "A criança está no primeiro versículo, e o texto a põe ali de propósito: \"uma grande congregação de homens, mulheres e crianças; pois o povo chorava com grande choro\" (Ed 10:1). Depois volta na praça alagada do nono mês, sentada no chão com os pais, \"tremendo por este negócio e por causa das grandes chuvas\" (Ed 10:9). Os moços em cena servem as salas em que o negócio se decide: um cuida da câmara de Joanã, filho de Eliasibe, e o serviço dele é não servir nada — \"não comeu pão, e nem bebeu água\" (Ed 10:6), e a mesa fica vazia dias a fio; outro guarda o portão por onde entraria a fazenda posta em interdito de quem não viesse em três dias (v. 8); outro atiça o fogo do único sacrifício do capítulo: \"E deram as suas mãos prometendo que despediriam suas mulheres; e, achando-se culpados, ofereceram um carneiro do rebanho pelo seu delito\" (Ed 10:19), a oferta pela culpa de Levítico 5:15; e o último acende o candeeiro da câmara da inquirição, que fica aceso desde cedo porque é inverno e a comissão se assenta \"no primeiro dia do décimo mês\" e só acaba três meses depois (v. 16-17). Os dois últimos servos deste livro são os que ninguém consultou: \"alguns deles tinham mulheres de quem tiveram filhos\" (Ed 10:44). Saem pela estrada com a mãe, e o livro fecha sem dizer mais nada sobre eles.",
    },
  },
};
