// Fichas ESPECÍFICAS por (capítulo → papel) de ESDRAS 1–6.
// Seis capítulos que vão do pregão de Ciro à páscoa comida dentro de uma casa
// acabada, e que quase não têm heróis: têm OFÍCIOS e CASAS PATERNAS. O perigo
// da ficha aqui é a lista — "um homem que voltou do cativeiro" trinta vezes —,
// e o remédio é o próprio texto, que teve o cuidado de escrever o nome de cada
// um: o chefe dos filhos de Parós, o homem de Anatote, o cantor de Asafe, o
// porteiro dos filhos de Salum, o netinim que Davi dera ao serviço dos levitas,
// o filho dos servos de Salomão, o que subiu de Tel-Melá e não pôde mostrar a
// casa de seus pais, os velhos que viram a primeira casa e choraram em altas
// vozes enquanto os outros jubilavam. Deus, nestes seis capítulos, nunca fala
// sem mediador: em 1:1 age calado, por dentro de um rei pagão; em 5:1-2 a
// palavra tem boca, nome e barba — Ageu e Zacarias, filho de Ido.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_01_06: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- Ed 1
  1: {
    anciao: {
      title: "Os chefes dos pais de Judá e de Benjamim, cujo espírito Deus despertou — e Sesbazar, o príncipe de Judá, que recebeu os vasos contados",
      subtitle: "Ed 1:5,8,11 • a resposta ao pregão, do lado de cá da cidade",
      text: "\"Então se levantaram os chefes dos pais de Judá e Benjamim, e os sacerdotes e os levitas, com todos aqueles cujo espírito Deus despertou, para subirem a edificar a casa do Senhor, que está em Jerusalém\" (Ed 1:5). Repare no verbo: é o MESMO do primeiro versículo — \"despertou o SENHOR o espírito de Ciro\" (Ed 1:1). Deus acorda o imperador e acorda o chefe de família com a mesma palavra, e nenhum dos dois ouve voz nenhuma. Duas tribos, e só duas: do reino do norte não se levanta ninguém, e o que sobe é o resto de Judá e de Benjamim, gente nascida em Babilônia que nunca viu a terra para onde vai. Isaías tinha descrito exatamente esta cena um século e meio antes, e sem cobrar nada por ela: \"Eu o despertei em justiça, e todos os seus caminhos endireitarei; ele edificará a minha cidade, e soltará os meus cativos, não por preço nem por presente\" (Is 45:13). O chefe da casa paterna é a autoridade real desta viagem — não há rei, não há exército, há pais de família com um decreto na mão; e à frente deles vai \"Sesbazar, príncipe de Judá\" (Ed 1:8), que recebe os utensílios peça por peça e os põe outra vez em Jerusalém.",
    },
    homem: {
      title: "O arauto que passou o pregão, o judeu do cativeiro que deu um passo à frente, o vizinho que ficou atrás e pagou a subida, e o sacerdote da casa dos deuses de Babilônia",
      subtitle: "Ed 1:1-4,6-7 • quem ouviu o decreto, quem obedeceu e quem ficou",
      text: "O decreto sai por duas vias ao mesmo tempo, e o arauto é a primeira delas: Ciro \"fez passar pregão por todo o seu reino, como também por escrito\" (Ed 1:1) — a voz para a praça, a cópia selada para o arquivo, e é justamente uma dessas cópias que reaparecerá em Acmeta cinco capítulos adiante para salvar a obra (Ed 6:2). O convite é aberto e é voluntário: \"Quem há entre vós, de todo o seu povo, seja seu Deus com ele, e suba a Jerusalém\" (Ed 1:3) — e o quadro precisa dos dois tipos de ouvinte, o que dá o passo e o que fica. Porque o decreto também pensou em quem fica: \"os homens do seu lugar o ajudarão com prata, com ouro, com bens, e com gados\" (Ed 1:4), e é o eco exato da saída do Egito, quando o povo pediu \"jóias de prata, e jóias de ouro, e roupas\" e \"o Senhor deu ao povo graça aos olhos dos egípcios\" (Êx 12:35-36). O último homem desta cena não é judeu: é o guarda do santuário babilônio que vê o próprio rei mandar abrir as portas e tirar de lá o que \"Nabucodonosor tinha trazido de Jerusalém, e que tinha posto na casa de seus deuses\" (Ed 1:7).",
    },
    multidao: {
      title: "Os do cativeiro que subiram de Babilônia para Jerusalém atrás dos vasos",
      subtitle: "Ed 1:11 • a coluna do regresso na estrada, com a cidade ainda pequena no horizonte",
      text: "\"Todos os utensílios de ouro e de prata foram cinco mil e quatrocentos; todos estes levou Sesbazar, quando os do cativeiro subiram de babilônia para Jerusalém\" (Ed 1:11). O capítulo fecha em movimento, e a gente que anda nesta estrada é, na maior parte, gente que nunca esteve em Jerusalém: nasceu junto ao rio Quebar, aprendeu o ofício em Babilônia e sobe para uma cidade que só conhece de ouvir contar. Setenta anos foi o prazo dito com número — \"estas nações servirão ao rei de babilônia setenta anos\" (Jr 25:11) —, e Daniel os achou nos livros e se pôs a orar por causa deles (Dn 9:2). O salmo que ficou desta manhã não se envergonha do espanto: \"Quando o SENHOR trouxe do cativeiro os que voltaram a Sião, estávamos como os que sonham\" (Sl 126:1). E acrescenta a única promessa que serve a uma caravana carregada de caixas e de medo: \"Aquele que leva a preciosa semente, andando e chorando, voltará, sem dúvida, com alegria, trazendo consigo os seus molhos\" (Sl 126:6).",
    },
    patriarca: {
      title: "Os sacerdotes que se levantaram para subir — a casa de Arão sem casa onde ministrar",
      subtitle: "Ed 1:5 • o sacerdócio arrumando a mudança no bairro dos exilados",
      text: "\"Então se levantaram os chefes dos pais de Judá e Benjamim, e os sacerdotes e os levitas\" (Ed 1:5). Este homem é filho ou neto de quem viu o templo arder; o seu chefe de linhagem foi levado a ferros, e o Cronista registrou-o em uma linha seca: \"E Jeozadaque foi levado cativo quando o Senhor levou presos a Judá e a Jerusalém pela mão de Nabucodonosor\" (1Cr 6:15). Durante setenta anos houve sacerdotes sem altar: uma ordem inteira preparada para um serviço que não podia acontecer em lugar nenhum, guardando de cor os ritos, os turnos e as medidas. É por isso que a primeira coisa que este povo levanta em Jerusalém não é parede — é altar (Ed 3:2), e o culto começa antes de haver uma só pedra do templo assentada (Ed 3:6). O filho de Jozadaque que vai à frente desta gente é o mesmo que Zacarias veria de pé diante do anjo do SENHOR com as vestes sujas, e a quem foi dito \"Tirai-lhe estas vestes sujas\" antes de lhe porem a mitra limpa na cabeça (Zc 3:1-5).",
    },
    rebanho: {
      title: "O gado com que os vizinhos de Babilônia firmaram as mãos dos que subiam",
      subtitle: "Ed 1:4,6 • os animais dados à porta por quem não ia",
      text: "\"E todo aquele que ficar atrás em algum lugar em que andar peregrinando, os homens do seu lugar o ajudarão com prata, com ouro, com bens, e com gados, além das dádivas voluntárias para a casa de Deus\" (Ed 1:4) — e o versículo seguinte diz que foi feito: \"E todos os que habitavam nos arredores lhes firmaram as mãos com vasos de prata, com ouro, com bens e com gado, e com coisas preciosas\" (Ed 1:6). O gado desta cena não é riqueza de exposição: é o meio de transporte, o leite da estrada e o rebanho de quem vai recomeçar do zero num campo que passou setenta anos sem dono. E é dado por quem não vai. A expressão \"firmaram as mãos\" é a chave — o mesmo par de mãos que o capítulo 4 verá ser debilitado pelo povo da terra (Ed 4:4) é aqui firmado por vizinhos que continuam em Babilônia. Duas cabeças de gado à porta de casa valem, nesta história, mais do que um discurso.",
    },
    servo: {
      title: "O escriba que copiou o pregão, o escrivão que contou os cinco mil e quatrocentos, os levitas que subiram e os carregadores dos utensílios",
      subtitle: "Ed 1:1,5,8-11 • as mãos que escrevem, contam, amarram e carregam",
      text: "Este capítulo inteiro se faz com pena e com corda. A pena é a do escriba que passa o pregão \"como também por escrito\" (Ed 1:1) e a do escrivão do tesouro persa, porque a entrega é burocrática de propósito: os utensílios saem \"pela mão de Mitredate, o tesoureiro, que os entregou contados a Sesbazar, príncipe de Judá\" (Ed 1:8), e a conta é lida em voz alta peça por peça — \"trinta travessas de ouro, mil travessas de prata, vinte e nove facas\" (Ed 1:9). A corda é a de quem amarra as caixas e as põe no lombo do jumento. Ao lado deles sobe o levita, que nesta lista aparece sem alarde — \"os sacerdotes e os levitas, com todos aqueles cujo espírito Deus despertou\" (Ed 1:5) — e que dois capítulos adiante estará com os címbalos na mão no dia do fundamento (Ed 3:10). Nada aqui é épico: é gente escrevendo linhas, conferindo números e carregando peso. Foi assim que o ouro do templo voltou para casa.",
    },
  },

  // ---------------------------------------------------------------- Ed 2
  2: {
    anciao: {
      title: "Os chefes das casas paternas e os velhos das cidades do arrolamento — os filhos de Parós, de Sefatias, de Ará, de Paate-Moabe, e os homens de Belém, de Anatote, de Micmás, de Jericó — e o governador que julgou o registro dos sacerdotes",
      subtitle: "Ed 2:3-35,63 • quem dá o número da sua casa e quem responde pela sua cidade",
      text: "Setenta versículos de nomes, e cada linha é um homem em pé diante de um contador. A lista começa por CASAS — \"Os filhos de Parós, dois mil cento e setenta e dois\" (Ed 2:3), a maior de todas — e no versículo 21 muda de eixo para CIDADES: \"Os filhos de Belém, cento e vinte e três\" (Ed 2:21), \"Os homens de Anatote, cento e vinte e oito\" (Ed 2:23), \"Os homens de Micmás, cento e vinte e dois\" (Ed 2:27). O ancião desta cena é a autoridade que restou a um povo sem rei: o chefe da casa paterna responde pelo número, pela terra e pela genealogia dos seus, e é a ele que o escriba pergunta. No fim do capítulo um deles fala e a sua frase é a mais delicada do livro: \"E o governador lhes disse que não comessem das coisas consagradas, até que houvesse sacerdote com Urim e com Tumim\" (Ed 2:63) — não é um não, é um \"ainda não\" deixado em aberto, porque o peitoral do juízo, com \"Urim e Tumim\" sobre o coração de Arão (Êx 28:30), não voltou do exílio. A mesma lista é recopiada por Neemias, quase igual, quarenta e tantos anos depois (Ne 7:6-73): num povo pequeno, o rol dos nomes é o título de propriedade da nação.",
    },
    homem: {
      title: "O lavrador de Parós, o pisador do lagar de Elão, o filho da casa de Adonicão, o homem de Ai, de Anatote, de Hadide e de Ono, o porteiro dos filhos de Salum e de Talmom, o netinim, o filho dos servos de Salomão e o que subiu de Tel-Melá sem linhagem",
      subtitle: "Ed 2:3-58,59-62 • os homens que a lista conta um a um, e os que ela não pôde contar",
      text: "\"O número dos homens do povo de Israel\" (Ed 2:2): é assim que o arrolamento se apresenta, e por isso quase toda figura masculina deste capítulo é uma linha do rol. O homem daqui é sempre alguém de um ofício ou de um lugar que o texto nomeia — o que volta ao campo de Nebo, o que desce ao vale de Senaá com os três mil seiscentos e trinta (Ed 2:35), o porteiro dos seis postos de \"Salum… Ater… Talmom… Acube… Hatita… Sobai\" (Ed 2:42), o netinim que carrega água e lenha, o filho dos servos de Salomão que herdou um ofício do tempo do rei antigo. E há, no fim, os que a lista não conseguiu contar: \"Também estes subiram de Tel-Melá e Tel-Harsa, Querube, Adã e Imer; porém não puderam provar que as suas famílias e a sua linhagem eram de Israel\" (Ed 2:59). Seiscentas e cinquenta e duas pessoas com nome, com número e sem papel, paradas do lado de fora do portão. O livro não as manda embora nem as inscreve: deixa-as ali, e é dos quadros mais honestos da Escritura sobre o que custa pertencer.",
    },
    mulherComum: {
      title: "As mulheres do arrolamento — a da casa de Ará na eira, a da casa de Zacai no poço, a mãe da casa de Jora no arraial, a que lavou no ribeiro dos netinins, a que subiu de Tel-Harsa sem linhagem — e as duzentas cantoras",
      subtitle: "Ed 2:65 • as que a soma não contou, e o único versículo em que aparecem",
      text: "A conta deste capítulo é declaradamente de homens — \"O número dos homens do povo de Israel\" (Ed 2:2) —, e as mulheres atravessam setenta versículos sem entrar na soma. Elas aparecem uma vez só, e por causa do ofício: \"Afora os seus servos e as suas servas, que foram sete mil trezentos e trinta e sete; também tinha duzentos cantores e cantoras\" (Ed 2:65). Duzentas vozes contadas porque cantam — e o cântico é serviço da casa de Deus desde Davi, \"Porque já nos dias de Davi e Asafe, desde a antiguidade, havia chefes dos cantores, e dos cânticos de louvores e de ação de graças a Deus\" (Ne 12:46). Fora dessa linha, a mulher deste capítulo está na eira a peneirar, no poço com o cântaro, na vinha, na cabana da noite com o filho ao colo, e na margem do ribeiro a lavar a roupa do serviço dos netinins — e é ela que faz a viagem inteira com as crianças. Uma delas, no versículo 59, sobe de Tel-Harsa e não consegue provar a casa de seus pais. A promessa que este povo carregava para Jerusalém contava com todas: \"Ainda nas praças de Jerusalém habitarão velhos e velhas… E as ruas da cidade se encherão de meninos e meninas, que nelas brincarão\" (Zc 8:4-5).",
    },
    multidao: {
      title: "A congregação junta dos quarenta e dois mil trezentos e sessenta, a gente de Senaá e a fila da casa de Azgade no poço",
      subtitle: "Ed 2:12,35,38,64 • a soma lida em voz alta e os grupos grandes da lista",
      text: "\"Toda esta congregação junta foi de quarenta e dois mil trezentos e sessenta\" (Ed 2:64). É pouco — pouquíssimo, para um povo que saíra do Egito com seiscentos mil homens de pé —, e o livro dá o número sem o disfarçar. Dentro dele há blocos que enchem sozinhos uma praça: \"Os filhos de Senaá, três mil seiscentos e trinta\" (Ed 2:35), o maior número da lista inteira e de um lugar que nenhum outro texto da Escritura consegue situar no mapa; \"Os filhos de Azgade, mil duzentos e vinte e dois\" (Ed 2:12); e uma só casa sacerdotal, \"Os filhos de Pasur, mil duzentos e quarenta e sete\" (Ed 2:38), maior do que muitas cidades desta mesma lista. A multidão deste capítulo não é um borrão: é a soma de casas que foram contadas uma a uma, e é por isso que o número dá tanto trabalho ao autor. Neemias copiou-o de novo, até no total: \"Toda esta congregação junta foi de quarenta e dois mil, trezentos e sessenta\" (Ne 7:66) — a mesma conta duas vezes, para que não se perdesse.",
    },
    pastor: {
      title: "O pastor dos campos de Belém, na aldeia que recebeu de volta cento e vinte e três dos seus",
      subtitle: "Ed 2:21 • a primeira cidade da lista, e a menor entre os milhares de Judá",
      text: "\"Os filhos de Belém, cento e vinte e três\" (Ed 2:21). É o primeiro nome de cidade do arrolamento, e cento e vinte e três é uma aldeia — três dezenas de famílias voltando para uma encosta de pastos e de cevada. A Escritura já tinha passado três vezes por estes campos: foi ali que \"chegaram a Belém no princípio da colheita das cevadas\" Noemi e Rute (Rt 1:22); foi dali que Samuel mandou chamar o filho mais novo de Jessé, o que faltava porque \"está apascentando as ovelhas\" (1Sm 16:11); e foi sobre esta pequenez que Miquéias falou: \"E tu, Belém Efrata, posto que pequena entre os milhares de Judá, de ti me sairá o que governará em Israel\" (Mq 5:2). Este pastor volta a apascentar num lugar de onde já saiu um rei e de onde há de sair o Rei — e nem ele nem os outros cento e vinte e dois sabem disso. Quinhentos anos depois, no mesmo campo, \"havia naquela mesma comarca pastores que estavam no campo, e guardavam, durante as vigílias da noite, o seu rebanho\" (Lc 2:8).",
    },
    patriarca: {
      title: "As quatro casas sacerdotais que voltaram — Jedaías, Imer, Pasur e Harim — e o sacerdote dos filhos de Barzilai, excluído por não achar o seu nome",
      subtitle: "Ed 2:36-39,61-63 • o adro sem paredes, com quatro mil duzentos e oitenta e nove sacerdotes",
      text: "\"Os sacerdotes: os filhos de Jedaías, da casa de Jesuá, novecentos e setenta e três\" (Ed 2:36), Imer mil e cinquenta e dois, Pasur mil duzentos e quarenta e sete, Harim mil e dezessete — quatro casas apenas, das vinte e quatro turmas que Davi tinha repartido por sorte, em que Jedaías tirou a segunda, Harim a terceira e Imer a décima sexta (1Cr 24:7-14). Pasur é a casa daquele sacerdote que mandou pôr Jeremias no tronco: \"E Pasur, filho de Imer, o sacerdote, que havia sido nomeado presidente na casa do SENHOR\" (Jr 20:1). Quatro mil duzentos e oitenta e nove homens de linho para uma casa que ainda não tem uma pedra — e ao lado deles, um sacerdote que não consegue provar que o é: os filhos de \"Barzilai, que tomou mulher das filhas de Barzilai, o gileadita, e que foi chamado do seu nome\" (Ed 2:61), o homem de oitenta anos que sustentara Davi em Maanaim (2Sm 19:32). Trocou o nome do pai pelo do sogro rico, e é esse nome que agora lhe falta no rolo: \"procuraram o seu registro entre os que estavam arrolados nas genealogias, mas não se acharam nelas; assim, por imundos, foram excluídos do sacerdócio\" (Ed 2:62).",
    },
    servo: {
      title: "Os setenta e quatro levitas, os cento e vinte e oito cantores de Asafe, os porteiros, os netinins nome por nome e os filhos dos servos de Salomão",
      subtitle: "Ed 2:40-58 • a folha inteira do serviço da casa, e o buraco que ela deixa à vista",
      text: "\"Os levitas: os filhos de Jesuá e Cadmiel, dos filhos de Hodavias, setenta e quatro\" (Ed 2:40). Setenta e quatro. Contra mil duzentos e quarenta e sete sacerdotes de uma casa só — e é este buraco que Esdras, oitenta anos depois, vai passar três dias parado junto ao rio Aava a tentar tapar (Ed 8:15). Os cantores são mais do que os levitas: \"os filhos de Asafe, cento e vinte e oito\" (Ed 2:41), herdeiros daqueles que Davi \"separou para o ministério… para profetizarem com harpas, com címbalos, e com saltérios\" (1Cr 25:1) e que ainda estavam no seu posto no tempo de Josias (2Cr 35:15). Os porteiros vêm nomeados de seis em seis (Ed 2:42), como as quatro bandas que Davi sorteara porta por porta (1Cr 26:14). E vêm os NETININS, os \"dados\" ao serviço, listados um a um durante doze versículos — gente cujos nomes ninguém decorava: são os que \"Davi e os príncipes deram para o ministério dos levitas\" (Ed 8:20), e a raiz do ofício está em Josué, que fez dos gibeonitas \"rachadores de lenha e tiradores de água para a congregação e para o altar do Senhor\" (Js 9:27). Com eles sobem os filhos dos servos de Salomão, dos povos que aquele rei \"reduziu a tributo servil\" (1Rs 9:21) — e o texto soma os dois grupos calados numa linha só: \"Todos os netinins, e os filhos dos servos de Salomão, trezentos e noventa e dois\" (Ed 2:58).",
    },
  },

  // ---------------------------------------------------------------- Ed 3
  3: {
    anciao: {
      title: "Os velhos que viram a primeira casa e choraram em altas vozes — e os chefes dos pais que vieram ao sétimo mês e pagaram aos pedreiros",
      subtitle: "Ed 3:7,12 • o versículo mais difícil do livro, em cima da linha do fundamento",
      text: "\"Porém muitos dos sacerdotes, e levitas e chefes dos pais, já idosos, que viram a primeira casa, choraram em altas vozes quando à sua vista foram lançados os fundamentos desta casa; mas muitos levantaram as vozes com júbilo e com alegria\" (Ed 3:12). Faça-se a conta: quem viu o templo de Salomão de pé tem, neste dia, mais de setenta anos. São meninos de então, e o que lhes arranca o choro não é a ruína — é a MEDIDA. O risco no chão é menor do que a casa da lembrança, e eles são os únicos ali capazes de comparar. Ageu, que estava vivo e pregou a esta mesma gente, pôs a pergunta em palavras: \"Quem há entre vós que, tendo ficado, viu esta casa na sua primeira glória? E como a vedes agora? Não é esta como nada diante dos vossos olhos, comparada com aquela?\" (Ag 2:3) — e respondeu com a única frase que cabia: \"A glória desta última casa será maior do que a da primeira\" (Ag 2:9). O mesmo ancião que chora aqui é o que, no versículo 7, contou o dinheiro \"aos pedreiros e carpinteiros\" e mandou o azeite aos sidônios: paga a obra de dia e chora sobre ela de tarde. Zacarias falaria depois exatamente para este choro: \"quem despreza o dia das coisas pequenas?\" (Zc 4:10).",
    },
    homem: {
      title: "O pedreiro da casa do SENHOR, o vigia que olhava os povos das terras, os sidônios e os tírios que desceram os cedros do Líbano, o filho de Henadade e o moço que jubilou sobre o fundamento",
      subtitle: "Ed 3:3,7,9,12 • as mãos da obra, o medo em volta dela e a alegria de quem não tinha memória",
      text: "\"E firmaram o altar sobre as suas bases, porque o terror estava sobre eles, por causa dos povos das terras\" (Ed 3:3): o primeiro homem em cena neste capítulo é um vigia, porque a obra se faz olhando por cima do ombro. Depois vêm os de fora, e o contrato é o mesmo que Salomão fizera quatro séculos antes — \"Deram, pois, o dinheiro aos pedreiros e carpinteiros, como também comida e bebida, e azeite aos sidônios, e aos tírios, para trazerem do Líbano madeira de cedro ao mar, para Jope\" (Ed 3:7), o mesmo trajeto de \"jangadas pelo mar até Jope\" da carta de Hirão (2Cr 2:16) e o mesmo reconhecimento de ofício: \"entre nós ninguém há que saiba cortar a madeira como os sidônios\" (1Rs 5:6). No canteiro, a chefia se reparte por casas: Jesuá e os seus, Cadmiel e os seus, \"bem como os filhos de Henadade, seus filhos e seus irmãos, os levitas\" (Ed 3:9). E no dia do fundamento entra o homem que este quadro não pode perder: o novo, que nunca viu templo nenhum e por isso grita — \"mas muitos levantaram as vozes com júbilo e com alegria\" (Ed 3:12). Ele não está errado; está apenas sem memória, e é isso que o deixa gritar.",
    },
    mulherComum: {
      title: "A mulher que armou a cabana de ramos na festa dos tabernáculos, no primeiro sétimo mês da volta",
      subtitle: "Ed 3:4 • a festa de gente sem casa que celebra justamente a vida em cabanas",
      text: "\"E celebraram a festa dos tabernáculos, como está escrito; ofereceram holocaustos cada dia, por ordem, conforme ao rito, cada coisa em seu dia\" (Ed 3:4). A lei dizia por que se fazia aquilo: \"Sete dias habitareis em tendas… Para que saibam as vossas gerações que eu fiz habitar os filhos de Israel em tendas, quando os tirei da terra do Egito\" (Lv 23:42-43). A ironia é boa demais para se perder: quem arma esta cabana ainda não tem casa de verdade — voltou há semanas para um país em ruínas — e passa sete dias numa cabana de ramos de propósito, para se lembrar de um êxodo antigo enquanto vive um novo. As mãos que cortam os ramos, amarram a estrutura e cozinham os sete dias são, na vida real de uma aldeia, sobretudo as dela. Neemias registraria mais tarde a mesma festa e a sua alegria: \"E toda a congregação dos que voltaram do cativeiro fizeram cabanas, e habitaram nas cabanas, porque nunca fizeram assim os filhos de Israel, desde os dias de Jesua, filho de Num, até àquele dia; e houve mui grande alegria\" (Ne 8:17).",
    },
    multidao: {
      title: "O povo ajuntado como um só homem em Jerusalém, e o som do júbilo que se ouvia de muito longe",
      subtitle: "Ed 3:1,11,13 • a praça do sétimo mês e o dia do fundamento",
      text: "\"Chegando, pois, o sétimo mês, e estando os filhos de Israel já nas cidades, ajuntou-se o povo, como um só homem, em Jerusalém\" (Ed 3:1). O capítulo anterior acabara de os espalhar, cada um para a sua cidade — e a primeira coisa que fazem com o endereço novo é largá-lo e subir. O sétimo mês é o das trombetas, da expiação e dos tabernáculos, e por isso a data importa: o povo remarca o calendário antes de remarcar o terreno. No dia do fundamento, esta mesma multidão canta em coro \"porque é bom; porque a sua benignidade dura para sempre sobre Israel\" e \"todo o povo jubilou com altas vozes, quando louvaram ao Senhor, pela fundação da casa do Senhor\" (Ed 3:11). E o capítulo não fecha numa imagem, fecha num SOM: \"De maneira que não discernia o povo as vozes do júbilo de alegria das vozes do choro do povo; porque o povo jubilava com tão altas vozes, que o som se ouvia de muito longe\" (Ed 3:13). Uma nação inteira faz um único barulho em que ninguém consegue separar a festa do luto — e Deus recebe os dois na mesma oferta.",
    },
    patriarca: {
      title: "Jesuá e os sacerdotes que edificaram o altar antes de qualquer parede, o do holocausto contínuo e o que se apresentou vestido e com trombeta no dia do fundamento",
      subtitle: "Ed 3:2-6,10 • o culto que começa em cima de um alicerce que ainda não existe",
      text: "\"E levantou-se Jesuá, filho de Jozadaque, e seus irmãos, os sacerdotes… e edificaram o altar do Deus de Israel, para oferecerem sobre ele holocaustos, como está escrito na lei de Moisés, o homem de Deus\" (Ed 3:2). A ordem das coisas é a lição do capítulo: primeiro o altar, depois a casa — e entre um e outro passa quase um ano. O versículo 6 diz a coisa mais honesta do livro: \"Desde o primeiro dia do sétimo mês começaram a oferecer holocaustos ao SENHOR; porém ainda não estavam postos os fundamentos do templo do SENHOR\". Culto de verdade em cima de um chão vazio. E o sacerdote não faz isto em paz: \"firmaram o altar sobre as suas bases, porque o terror estava sobre eles, por causa dos povos das terras\" (Ed 3:3), e mesmo assim mantém o holocausto \"pela manhã e à tarde\", as luas novas e todas as solenidades (Ed 3:3,5). No dia dos alicerces ele aparece fardado e com metal na mão: \"apresentaram-se os sacerdotes, já vestidos e com trombetas\" (Ed 3:10) — as mesmas trombetas de prata do deserto, tocadas por uma casa que passou setenta anos sem ter onde tocá-las.",
    },
    servo: {
      title: "Os levitas de vinte anos para cima postos a dirigir a obra, Cadmiel e os seus, os filhos de Asafe com címbalos, o pedreiro do altar e o carpinteiro que recebeu os cedros em Jope",
      subtitle: "Ed 3:8-11 • quem toca a obra e quem faz o som do dia do fundamento",
      text: "\"E no segundo ano da sua vinda à casa de Deus em Jerusalém, no segundo mês… começaram a obra da casa do Senhor, e constituíram os levitas da idade de vinte anos para cima, para que a dirigissem\" (Ed 3:8). Vinte anos é idade de recruta, e o levita aqui não é cantor de sacristia: é mestre de obras. Eram setenta e quatro ao todo (Ed 2:40), e no versículo seguinte o texto conta como se organizaram — \"Então se levantou Jesuá, seus filhos, e seus irmãos, Cadmiel e seus filhos, os filhos de Judá, como um só homem, para dirigirem os que faziam a obra na casa de Deus\" (Ed 3:9). No dia em que a primeira fiada foi assentada, o mesmo grupo trocou a ferramenta pelo instrumento: \"e os levitas, filhos de Asafe, com címbalos, para louvarem ao Senhor conforme à instituição de Davi, rei de Israel\" (Ed 3:10) — a instituição de um rei morto havia quinhentos anos, guardada de cor durante o exílio e executada de novo na primeira ocasião. Ao lado deles trabalha gente sem nome nenhum: o que assentou o altar sobre as bases antigas e o que recebeu na praia de Jope os toros descidos do Líbano.",
    },
  },

  // ---------------------------------------------------------------- Ed 4
  4: {
    anciao: {
      title: "O conselheiro da corte de Artaxerxes que buscou nas crônicas — e o velho de Judá que viu a obra cessar e ficou dezesseis anos olhando para as pedras",
      subtitle: "Ed 4:5,19,24 • os dois lados da mesa em que a obra foi parada",
      text: "Há dois velhos neste capítulo, e estão em salas opostas. Um é o conselheiro da corte persa, que recebe a ordem e vira o arquivo: \"E, ordenando-o eu, buscaram e acharam, que de tempos antigos aquela cidade se levantou contra os reis, e nela se têm feito rebelião e sedição\" (Ed 4:19) — e o pior é que o arquivo não mentiu; Jerusalém REALMENTE se rebelara contra Babilônia, e a acusação vence porque diz a verdade sobre o passado para esconder a verdade sobre o presente. O outro é o ancião de Judá, que vê a coisa acontecer de fora e não tem a quem recorrer: contra ele foram alugados conselheiros \"para frustrarem o seu plano, todos os dias de Ciro, rei da Pérsia, até ao reinado de Dario, rei da Pérsia\" (Ed 4:5). O capítulo fecha em cima dele: \"Então cessou a obra da casa de Deus, que estava em Jerusalém; e cessou até ao ano segundo do reinado de Dario\" (Ed 4:24). Dezesseis anos numa linha só. É a esses velhos que Ageu falará quando o silêncio se romper: \"Porventura é para vós tempo de habitardes nas vossas casas forradas, enquanto esta casa fica deserta?\" (Ag 1:4).",
    },
    homem: {
      title: "Os adversários de Judá e Benjamim, o povo da terra que debilitou as mãos, o conselheiro alugado, Bislão e Tabeel, Reum, o chanceler, e o correio que levou a resposta a Samaria",
      subtitle: "Ed 4:1-2,4-8,17,23 • quem se ofereceu, quem foi recusado e quem passou a escrever",
      text: "\"Chegaram-se a Zorobabel e aos chefes dos pais, e disseram-lhes: Deixai-nos edificar convosco, porque, como vós, buscaremos a vosso Deus; como também já lhe sacrificamos desde os dias de Esar-Hadom, rei da Assíria, que nos fez subir aqui\" (Ed 4:2). É a frase mais mansa do livro, e é verdadeira pela metade: esta gente foi mesmo trazida pela Assíria — \"o rei da Assíria trouxe gente de Babilônia, de Cuta, de Ava, de Hamate e Sefarvaim, e a fez habitar nas cidades de Samaria\" (2Rs 17:24) — e o resultado daquela mistura ficou escrito sem rodeios: \"Assim temiam ao Senhor, mas também serviam a seus deuses\" (2Rs 17:33). Recusados de frente, mudam de arma três vezes em quatro versículos: debilitam as mãos e inquietam (Ed 4:4), alugam conselheiros (Ed 4:5) e escrevem — no reinado de Assuero, depois nos dias de Artaxerxes por \"Bislão, Mitredate, Tabeel, e os outros seus companheiros\" (Ed 4:7), e enfim \"Reum, o chanceler, e Sinsai, o escrivão\" (Ed 4:8). O homem que fecha o capítulo é o correio: leva a resposta selada, e atrás dela chegam os que impedem a obra \"à força e com violência\" (Ed 4:23). Neste capítulo, a arma que funciona é papel.",
    },
    multidao: {
      title: "Os nove povos que assinaram a carta — dinaítas, afarsaquitas, tarpelitas, afarsitas, arquevitas, babilônios, susanquitas, deavitas e elamitas",
      subtitle: "Ed 4:9-10 • o espelho torto da lista de Esdras 2",
      text: "\"Então escreveu Reum, o chanceler, e Sinsai, o escrivão, e os outros seus companheiros, os dinaítas, afarsaquitas, tarpelitas, afarsitas, arquevitas, babilônios, susanquitas, deavitas, elamitas\" (Ed 4:9). Nove povos numa linha só — e o leitor que acabou de atravessar as setenta linhas do arrolamento de Esdras 2 reconhece a forma: é uma lista contra uma lista, um povo contado a se opor a outro povo contado. O versículo seguinte diz de onde eles vieram, e é a ironia inteira do capítulo: \"E os outros povos, que o grande e afamado Asnapar transportou, e que fez habitar na cidade de Samaria, e nas demais províncias dalém do rio\" (Ed 4:10). São deportados. Gente arrancada da sua terra por um império e plantada nesta, exatamente como os judeus foram arrancados desta e plantados naquela — e é contra outros deportados que escrevem. O que os separa não é a origem nem a dor: é que uns voltaram para edificar uma casa a um Deus só, e os outros \"temiam ao Senhor, mas também serviam a seus deuses\" (2Rs 17:33).",
    },
    patriarca: {
      title: "Jesuá, filho de Jozadaque, e os sacerdotes que recusaram a ajuda dos adversários",
      subtitle: "Ed 4:2-3 • o sumo sacerdote ao lado de Zorobabel na hora do não",
      text: "\"Porém Zorobabel, e Jesuá, e os outros chefes dos pais de Israel lhes disseram: Não convém que nós e vós edifiquemos casa a nosso Deus; mas nós sozinhos a edificaremos ao Senhor Deus de Israel, como nos ordenou o rei Ciro, rei da Pérsia\" (Ed 4:3). A recusa é dita por dois: o príncipe da casa de Davi e o sumo sacerdote da casa de Arão, lado a lado — é assim que este povo governa, sem rei e sem exército. E o fundamento do não não é gosto nem desprezo: é uma ordem escrita, o mesmo pregão de Ciro que os trouxe até ali. O sacerdote sabe o que está em jogo, porque a mistura dos cultos foi exatamente o que arruinou o reino do norte, e é dele o ofício de guardar a diferença entre o santo e o profano. O preço do não vem no versículo seguinte, e é alto: mãos debilitadas, conselheiros alugados, dezesseis anos de obra parada. Zacarias veria este mesmo homem, anos depois, de vestes sujas diante do anjo, e ouviria a promessa que ainda não se cumprira: \"Tirai-lhe estas vestes sujas\" (Zc 3:4).",
    },
    rei: {
      title: "Artaxerxes, rei da Pérsia, e o Assuero em cujo reinado se escreveu a primeira acusação",
      subtitle: "Ed 4:6-7,17-22 • os tronos persas de que saiu a ordem de impedir a obra",
      text: "Este capítulo é um parêntese: para juntar num só lugar toda a oposição escrita contra Jerusalém, o autor salta por cima de reinados inteiros e cita cartas do tempo de Assuero (Ed 4:6) e de Artaxerxes (Ed 4:7), que reinaram muito depois de Dario — e só no versículo 24 volta ao fio da obra parada. O rei que responde não decide por convicção religiosa nenhuma; decide por receita e por arquivo. Ouve a carta — \"A carta que nos enviastes foi explicitamente lida diante de mim\" (Ed 4:18) —, manda buscar nas crônicas, encontra a rebelião antiga e conclui pelo que lhe interessa: \"Também houve reis poderosos sobre Jerusalém que dalém do rio dominaram em todo o lugar, e se lhes pagaram direitos, tributos e pedágios\" (Ed 4:20). Aí vem a ordem, e nela está o descuido que salva a história: \"Agora, pois, dai ordem para impedirdes aqueles homens, a fim de que não se edifique aquela cidade, até que eu dê uma ordem\" (Ed 4:21). Nem este rei fecha a porta de todo — deixa-a encostada; e é por essa fresta que Dario entrará no capítulo 6.",
    },
    servo: {
      title: "Sinsai, o escrivão, que leu a carta em voz alta; o escriba da resposta do rei; e o pedreiro de Judá que largou a ferramenta e ficou de guarda ao canteiro abandonado",
      subtitle: "Ed 4:8-16,23-24 • quem escreve a carta e quem paga por ela",
      text: "Neste capítulo há duas espécies de servo, e a distância entre elas é a história inteira. Um trabalha com tinta: \"Escreveram, pois, Reum, o chanceler, e Sinsai, o escrivão, uma carta contra Jerusalém, ao rei Artaxerxes\" (Ed 4:8), e é a boca dele que lê o teor diante do rei — \"Saiba o rei que os judeus, que subiram de ti, vieram a nós em Jerusalém, e reedificam aquela rebelde e malvada cidade\" (Ed 4:12). A carta chega a confessar o seu próprio motivo sem perceber: \"porquanto somos assalariados do palácio, e não nos convém ver a desonra do rei\" (Ed 4:14) — escrevem porque comem da mão dele. O outro servo trabalha com pedra, e é ele que apanha: \"apressadamente foram eles a Jerusalém, aos judeus, e os impediram à força e com violência\" (Ed 4:23). No último quadro do capítulo, esse pedreiro é só um homem parado ao anoitecer diante de um canteiro com mato entre as pedras, e a obra fica assim até ao ano segundo de Dario (Ed 4:24). Uma folha de papel derrubou o que nenhum exército tinha tentado derrubar.",
    },
  },

  // ---------------------------------------------------------------- Ed 5
  5: {
    anciao: {
      title: "Os anciãos dos judeus sobre quem estavam os olhos de Deus — e Sesbazar, o que pusera os fundamentos e a quem a carta dá nome ao rei",
      subtitle: "Ed 5:5,9-11,14-16 • os velhos que responderam a Tatenai e não pararam a obra",
      text: "\"Porém os olhos de Deus estavam sobre os anciãos dos judeus, e não os impediram, até que o negócio chegasse a Dario, e viesse resposta por carta sobre isso\" (Ed 5:5). É a frase teológica do capítulo e não vem acompanhada de milagre nenhum: nenhum anjo, nenhuma voz, nenhum fogo — apenas um inspetor imperial que, por alguma razão que o texto atribui a Deus, não manda parar. E, perguntados, estes velhos não se apresentam por decreto: apresentam-se por dono. \"E esta foi a resposta que nos deram: Nós somos servos do Deus dos céus e da terra, e reedificamos a casa que há muitos anos foi edificada; porque um grande rei de Israel a edificou e a terminou\" (Ed 5:11). Depois contam a história inteira sem se pouparem, incluindo a parte que os incrimina — \"Mas depois que nossos pais provocaram à ira o Deus dos céus, ele os entregou nas mãos de Nabucodonosor\" (Ed 5:12) — e terminam confessando que a obra está atrasada: \"desde então para cá se está reedificando, e ainda não está acabada\" (Ed 5:16). Entre estes anciãos volta a aparecer o nome do capítulo 1: Sesbazar, \"a quem nomeou governador\" (Ed 5:14), o homem que pôs a primeira pedra e desapareceu do livro sem que se diga o que foi feito dele.",
    },
    homem: {
      title: "Tatenai, governador dalém do rio, Setar-Bozenai e os afarsaquitas; o carpinteiro que punha a madeira nas paredes e o judeu de Judá que ouviu os profetas",
      subtitle: "Ed 5:3-4,6-10,17 • a inspeção que virou testemunho a favor",
      text: "\"Naquele tempo vieram a eles Tatenai, governador dalém do rio, e Setar-Bozenai, e os seus companheiros, e disseram-lhes assim: Quem vos deu ordem para reedificardes esta casa, e restaurardes este muro?\" (Ed 5:3). E logo a segunda pergunta, que num império assusta mais do que a primeira: \"E quais são os nomes dos homens que construíram este edifício?\" (Ed 5:4) — porque uma lista de nomes, entregue à autoridade errada, é uma lista de réus. Mas o governador não é Reum: não denuncia, relata. E o relatório dele acaba por ser o melhor testemunho que a obra recebeu: \"a qual se edifica com grandes pedras, e a madeira já está sendo posta nas paredes; e esta obra vai sendo feita com diligência, e se adianta em suas mãos\" (Ed 5:8). Um funcionário persa descrevendo, sem entusiasmo e sem má vontade, uma casa que sobe depressa. E fecha pedindo arquivo em vez de pedir tropa: \"busque-se na casa dos tesouros do rei, que está em babilônia, se é verdade\" (Ed 5:17). No meio do canteiro está ainda o carpinteiro que encaixa a viga na parede e o judeu comum que voltou ao trabalho porque dois profetas lhe falaram.",
    },
    patriarca: {
      title: "Ageu e Zacarias, filho de Ido, e Jesuá, filho de Jozadaque — a palavra de Deus com boca, nome e pé no chão",
      subtitle: "Ed 5:1-2 • por que aqui não há voz do céu",
      text: "\"E os profetas Ageu e Zacarias, filho de Ido, profetizaram aos judeus que estavam em Judá, e em Jerusalém; em nome do Deus de Israel lhes profetizaram\" (Ed 5:1). Dezesseis anos de silêncio e de mato entre as pedras não são quebrados por um decreto, por um exército nem por um sinal no céu: são quebrados por duas bocas. Por isso, neste capítulo, Deus não fala do alto — fala DELES, e o quadro tem de mostrar as figuras. Sabemos o que disseram, porque os dois livrinhos ficaram: \"Este povo diz: Não veio ainda o tempo, o tempo em que a casa do Senhor deve ser edificada\" (Ag 1:2), \"Subi ao monte, e trazei madeira, e edificai a casa\" (Ag 1:8), e a Zorobabel, pela boca de Zacarias, \"Não por força nem por violência, mas sim pelo meu Espírito, diz o Senhor dos Exércitos\" (Zc 4:6). E a palavra pega no mesmo versículo seguinte: \"Então se levantaram Zorobabel, filho de Sealtiel, e Jesuá, filho de Jozadaque, e começaram a edificar a casa de Deus… e com eles os profetas de Deus, que os ajudavam\" (Ed 5:2). Os dois profetas não pregaram de fora do tapume: entraram no canteiro. O terceiro homem de linho desta cena é Jesuá, o sumo sacerdote, que Zacarias veria coroado em visão — \"faze coroas, e põe-nas na cabeça do sumo sacerdote Josué, filho de Jozadaque\" (Zc 6:11).",
    },
    servo: {
      title: "O escrivão que anotou os nomes dos edificadores, o que redigiu a carta de Tatenai a Dario, o pedreiro das grandes pedras e o que carregou os vasos para Jerusalém",
      subtitle: "Ed 5:4,7-8,10,14-16 • quem escreve o relatório e quem levanta a parede que ele descreve",
      text: "Duas mãos trabalham em paralelo neste capítulo. Uma segura o cálamo: \"Além disso, lhes perguntamos também pelos seus nomes, para tos declararmos; para que te pudéssemos escrever os nomes dos homens que entre eles são os chefes\" (Ed 5:10) — o escrivão da comitiva anota nome por nome, e depois redige a cópia que vai selada a Susã, aquela que começa por \"Toda a paz ao rei Dario\" (Ed 5:7). A outra segura a pedra, e é dela que a carta fala: \"a qual se edifica com grandes pedras, e a madeira já está sendo posta nas paredes\" (Ed 5:8). O pedreiro deste versículo não sabe que está a ser descrito num documento oficial nem que a descrição o vai salvar — só está a assentar uma fiada. A carta ainda faz voltar em memória um terceiro servo, o do capítulo 1: o que carregou os utensílios de ouro e de prata que o rei Ciro \"tirou do templo de babilônia\" e mandou entregar a Sesbazar (Ed 5:14), com a ordem que a carta cita entre aspas — \"Toma estes utensílios, vai e leva-os ao templo que está em Jerusalém, e faze reedificar a casa de Deus, no seu lugar\" (Ed 5:15).",
    },
  },

  // ---------------------------------------------------------------- Ed 6
  6: {
    anciao: {
      title: "Os anciãos dos judeus que iam edificando e prosperando pela profecia — o conselheiro da corte de Dario e o filho do cativeiro que buscou ao SENHOR",
      subtitle: "Ed 6:7-8,14,21 • os velhos a quem o rei entrega a obra e a mesa da páscoa",
      text: "O decreto de Dario faz uma coisa que nenhum outro documento do livro tinha feito: entrega a obra aos velhos de Judá pelo nome do ofício. \"Deixai que se faça a obra desta casa de Deus; que o governador dos judeus e os seus anciãos reedifiquem esta casa de Deus no seu lugar\" (Ed 6:7), e o versículo seguinte manda pagar a despesa \"com os anciãos dos judeus\" (Ed 6:8). Os mesmos homens que Tatenai interrogara passam a ser os destinatários oficiais da fazenda do rei. E o resumo do capítulo reparte o crédito com uma honestidade rara: \"E os anciãos dos judeus iam edificando e prosperando pela profecia do profeta Ageu, e de Zacarias, filho de Ido. E edificaram e terminaram a obra conforme ao mandado do Deus de Israel, e conforme ao decreto de Ciro e Dario, e de Artaxerxes, rei da Pérsia\" (Ed 6:14) — céu e chancelaria na mesma frase, sem que uma coisa envergonhe a outra. No fim, o ancião muda de lugar e senta-se: come a páscoa entre os \"que tinham voltado do cativeiro, com todos os que com eles se apartaram da imundícia dos gentios da terra, para buscarem o Senhor Deus de Israel\" (Ed 6:21). Do outro lado da mesa política, na corte de Susã, está o conselheiro que ouviu ler o rolo de Acmeta e não teve o que objetar.",
    },
    homem: {
      title: "O oficial que achou o rolo em Acmeta, o tesoureiro da casa do rei, o correio do decreto, Tatenai e Setar-Bozenai obedecendo, e o estrangeiro que se apartou da imundícia dos gentios",
      subtitle: "Ed 6:1-2,8,13,21 • os que buscaram, os que pagaram e os que se sentaram à mesa",
      text: "O capítulo abre com um império inteiro a virar papéis por causa de uma obra de província: \"Então o rei Dario deu ordem, e buscaram nos arquivos, onde se guardavam os tesouros em babilônia\" (Ed 6:1). E não acham em Babilônia: \"E em Acmeta, no palácio, que está na província de Média, se achou um rolo\" (Ed 6:2) — Ecbátana, a cidade de veraneio dos reis persas, onde Ciro passava o calor, e por isso o memorial estava lá e não onde toda a gente procurava. Depois do despacho, o homem que muda de lado é o próprio inspetor: \"Então Tatenai, o governador dalém do rio, Setar-Bozenai e os seus companheiros, assim fizeram diligentemente, conforme ao que decretara o rei Dario\" (Ed 6:13) — quem viera perguntar acaba a cumprir. E o último homem deste capítulo não tem genealogia nenhuma: é o de fora que se separou dos seus para comer a páscoa \"com todos os que com eles se apartaram da imundícia dos gentios da terra, para buscarem o Senhor Deus de Israel\" (Ed 6:21). O capítulo 2 fechou uma porta a quem não podia provar a linhagem; este abre outra a quem se aparta — e Isaías já tinha visto assim: \"E os filhos dos estrangeiros edificarão os teus muros\" (Is 60:10).",
    },
    mulherComum: {
      title: "A mulher dos filhos do cativeiro que comeu a páscoa na casa acabada — e a que se apartou da imundícia dos gentios da terra",
      subtitle: "Ed 6:19-21 • a mesa da noite de catorze de Abibe, no adro do templo novo",
      text: "\"E os filhos do cativeiro celebraram a páscoa no dia catorze do primeiro mês\" (Ed 6:19). A páscoa é, desde o Egito, uma festa de CASA e não de sacerdócio — o cordeiro é comido por família, e a lei manda que a criança pergunte e que se lhe responda. Quem prepara essa mesa, arma o pão sem fermento pelos sete dias seguintes e ensina os filhos é sobretudo esta mulher; e é a primeira vez em setenta anos que ela o faz com um templo de pé atrás de si. O versículo 21 alarga a mesa mais do que o arrolamento de Esdras 2 tinha alargado: comeram os que voltaram do cativeiro \"com todos os que com eles se apartaram da imundícia dos gentios da terra, para buscarem o Senhor Deus de Israel\" — e a lei da primeira páscoa já previa exatamente isso, o estrangeiro que se agrega. Quem não tinha papel mas se apartou, senta-se. O livro fecha esta noite com uma frase sobre alegria, não sobre pureza: \"celebraram a festa dos pães ázimos por sete dias com alegria; porque o Senhor os tinha alegrado\" (Ed 6:22).",
    },
    multidao: {
      title: "Os filhos do cativeiro que viram a casa acabada, fizeram a dedicação com alegria e celebraram os pães ázimos por sete dias",
      subtitle: "Ed 6:15-16,22 • o adro cheio diante da fachada nova, vinte e um anos depois do primeiro alicerce",
      text: "\"E acabou-se esta casa no terceiro dia do mês de Adar, no sexto ano do reinado do rei Dario\" (Ed 6:15). Adar é o último mês do inverno, e a data é dada com dia, mês e ano porque este povo aprendeu a desconfiar de promessas sem calendário: entre o fundamento do capítulo 3 e esta manhã passaram-se cerca de vinte e um anos, dos quais dezesseis foram de obra parada. \"E os filhos de Israel, os sacerdotes, os levitas, e o restante dos filhos do cativeiro, fizeram a dedicação desta casa de Deus com alegria\" (Ed 6:16) — e a palavra alegria volta duas vezes no fecho, colada a um sujeito que não é o povo: \"porque o Senhor os tinha alegrado, e tinha mudado o coração do rei da Assíria a favor deles, para lhes fortalecer as mãos na obra da casa de Deus\" (Ed 6:22). As mesmas mãos que o capítulo 4 vira serem debilitadas pelo povo da terra (Ed 4:4) são aqui fortalecidas — e por dentro de um rei pagão, exatamente como no primeiro versículo do livro. É esta a multidão em que, se olharmos bem, ainda estão os velhos que choraram sobre o alicerce: viveram o bastante para ver o telhado.",
    },
    patriarca: {
      title: "Os sacerdotes postos nas suas turmas, o que ofereceu os doze cabritos pelo pecado de todo o Israel, o que matou o cordeiro da páscoa e o que orou pela vida do rei",
      subtitle: "Ed 6:10,17-20 • o sacerdócio de volta ao seu posto, conforme ao livro de Moisés",
      text: "\"E ofereceram para a dedicação desta casa de Deus cem novilhos, duzentos carneiros, quatrocentos cordeiros, e doze cabritos por expiação do pecado de todo o Israel; segundo o número das tribos de Israel\" (Ed 6:17). Doze, e não dois — e este é o detalhe mais comovente do capítulo: quem voltou é o resto de Judá e de Benjamim, mas o sacerdote oferece pelas DOZE tribos, incluindo as dez que não estão ali e provavelmente nunca mais estarão. Ele expia por irmãos ausentes. Depois a casa recebe a sua ordem interna: \"E puseram os sacerdotes nas suas turmas e os levitas nas suas divisões, para o ministério de Deus, em Jerusalém, conforme ao que está escrito no livro de Moisés\" (Ed 6:18) — as turmas que Davi sorteara (1Cr 24:7-8) voltam ao serviço setenta anos depois, guardadas de cor. Na páscoa, este mesmo sacerdote faz o que a lei reservava ao chefe de família, porque a comunidade ainda está a recompor-se: \"e mataram o cordeiro da páscoa para todos os filhos do cativeiro, e para seus irmãos, os sacerdotes, e para si mesmos\" (Ed 6:20). E há um encargo estranho na lista de ofícios dele, escrito por mão persa: que ofereçam \"sacrifícios de cheiro suave ao Deus dos céus, e orem pela vida do rei e de seus filhos\" (Ed 6:10).",
    },
    rebanho: {
      title: "Os bezerros, carneiros e cordeiros da provisão de dia em dia, e os cem novilhos e duzentos carneiros da dedicação da casa",
      subtitle: "Ed 6:9,17 • o gado que o rei da Pérsia manda entregar à porta do templo",
      text: "\"E o que for necessário, como bezerros, carneiros, e cordeiros, para holocaustos ao Deus dos céus, trigo, sal, vinho e azeite, segundo o rito dos sacerdotes que estão em Jerusalém, dê-se-lhes, de dia em dia, para que não haja falta\" (Ed 6:9). Repare em quem paga e no que se pede: um imperador persa manda abastecer, todos os dias e sem interrupção, o altar de um Deus que não é o seu — e a frase \"para que não haja falta\" é de despenseiro, não de teólogo. Este é o mesmo tesouro de que o capítulo 4 tirara o salário dos conselheiros alugados contra a obra (Ed 4:5): o dinheiro que pagou para parar a casa agora paga o gado que arde nela. No dia da dedicação, a conta sobe de uma vez: \"cem novilhos, duzentos carneiros, quatrocentos cordeiros\" (Ed 6:17) — setecentas cabeças, e ainda assim uma fração dos vinte e dois mil bois e cento e vinte mil ovelhas da dedicação de Salomão (2Cr 7:5). O livro não esconde a diferença de tamanho em lugar nenhum; e é precisamente sobre esta casa menor que Ageu tinha dito: \"A glória desta última casa será maior do que a da primeira\" (Ag 2:9).",
    },
    rei: {
      title: "Dario, rei da Pérsia, que mandou buscar nos arquivos e baixou o decreto que fez a obra andar",
      subtitle: "Ed 6:1,6-12 • o trono de onde saiu a ordem que desfez dezesseis anos de embargo",
      text: "Dario não é convertido nem devoto; é um administrador que decidiu verificar. \"Então o rei Dario deu ordem, e buscaram nos arquivos\" (Ed 6:1) — e, achado o memorial de Ciro, cumpre-o à letra e vai além do que lhe tinham pedido. Manda o governador afastar-se: \"que habitais dalém do rio, apartai-vos dali\" (Ed 6:6). Manda a obra prosseguir: \"Deixai que se faça a obra desta casa de Deus\" (Ed 6:7). Manda pagar: \"que da fazenda do rei, dos tributos dalém do rio se pague prontamente a despesa a estes homens, para que não interrompam a obra\" (Ed 6:8). E põe uma sanção que não é decorativa: quem mudar o decreto, \"se arrancará um madeiro da sua casa, e, levantado, o pendurarão nele, e da sua casa se fará por isso um monturo\" (Ed 6:11). O mais estranho vem no fim, quando um rei pagão invoca o Deus de Israel contra os seus próprios sucessores: \"O Deus, pois, que fez habitar ali o seu nome derrube a todos os reis e povos que estenderem a sua mão para mudar o decreto… Eu, Dario, baixei o decreto; com diligência se faça\" (Ed 6:12). Ao pé da letra é o mesmo verbo do capítulo 1 outra vez: Deus não fala com o rei — trabalha por dentro dele, e o resultado sai selado em cera persa.",
    },
    servo: {
      title: "O guarda dos arquivos de Babilônia, o escriba que leu o rolo de Acmeta e o do decreto de Dario, o despenseiro da provisão de dia em dia, o pedreiro das grandes pedras e o levita posto na sua divisão",
      subtitle: "Ed 6:1-5,9,13,18,20 • as mãos que procuram, leem, pesam, assentam e servem",
      text: "Este capítulo se resolve num arquivo empoeirado. O primeiro servo em cena é o que desce com o candeeiro e revista caixotes: \"buscaram nos arquivos, onde se guardavam os tesouros em babilônia\" (Ed 6:1), e o segundo é o que lê em voz alta o que se achou, porque o rolo, ali, é o verdadeiro personagem — \"No primeiro ano do rei Ciro, este baixou o seguinte decreto\" (Ed 6:3). Depois o serviço muda de matéria: o despenseiro passa a receber, todos os dias, \"trigo, sal, vinho e azeite\" da fazenda do rei, com a ordem escrita de que \"não haja falta\" (Ed 6:9); o pedreiro volta às fiadas que Tatenai descrevera na carta; e o escrivão do governador anota a madeira. No fim, a casa acabada devolve a cada levita o seu lugar: \"E puseram os sacerdotes nas suas turmas e os levitas nas suas divisões, para o ministério de Deus, em Jerusalém, conforme ao que está escrito no livro de Moisés\" (Ed 6:18). E na véspera da páscoa faz-se a coisa que nenhum decreto persa podia mandar fazer: \"Porque os sacerdotes e levitas se purificaram como se fossem um só homem, todos estavam limpos\" (Ed 6:20).",
    },
  },
};
