// Fichas ESPECÍFICAS por (capítulo → papel) de JÓ 29–42.
// O último terço do livro, e o palco de Jó quase nunca mostra os cinco homens
// sentados na cinza: mostra o que a fala VÊ. Por isso o figurante destes
// capítulos nunca é "um homem do povo" — é a FIGURA DA IMAGEM daquele
// versículo, e a ficha tem de dizer de que imagem ele é, quem a disse e o que
// ela quer dizer. Em 29 e 30 são dois quadros opostos do mesmo homem no mesmo
// portão: os idosos que se levantavam e os moços de menos idade que agora
// cospem; a lâmpada sobre a cabeça e a lama; a harpa e o luto. Em 31, quarenta
// versículos de juramento, e cada "se" é um quadro: a aliança com os olhos, as
// balanças fiéis, o direito do servo e da serva, o bocado comido sozinho, o
// ouro, o sol e a lua, as portas abertas ao viandante, os cardos por trigo. De
// 32 a 37 entra ELIÚ, o único moço no meio de quatro velhos, e o palco enche-se
// do que ele descreve: os odres novos sem respiradouro, o barro do oleiro, a
// cama do sonho e a cama da dor, o mensageiro intérprete um entre milhares, a
// mesa em que o paladar experimenta a comida, o gado que dá notícia do temporal
// que sobe, a neve que recebe ordem e o céu firme como espelho fundido. De 38 a
// 41 o SENHOR responde de um redemoinho — sem figura, porque o redemoinho é o
// MODO da voz e não um mensageiro —, e cada figurante é a criatura ou o homem
// que a pergunta cita como testemunha: os ímpios que a alva sacode, a cabra
// montesa, o jumento montês que se ri do ruído da cidade, o boi selvagem, a
// avestruz, o cavalo que ao soar das buzinas diz "Eia!", a águia, o beemote e o
// leviatã. E em 42, a casa refeita: os irmãos que comem pão, a peça de dinheiro
// e o pendente de ouro, as três filhas nomeadas e a herança entre seus irmãos.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_29_42: Record<number, Record<string, StageInfo>> = {
  // ----------------------------------------------------------------- Jó 29
  29: {
    patriarca: {
      title: "Jó no monturo, lembrando em voz alta os meses passados — e os três amigos, que já não têm o que responder",
      subtitle: "Jó 29:1-2 • a cinzeira fora de Uz, e a memória de um homem que já foi o primeiro da cidade",
      text: "\"E prosseguiu Jó no seu discurso, dizendo: Ah! quem me dera ser como eu fui nos meses passados, como nos dias em que Deus me guardava!\" (Jó 29:1-2). O capítulo inteiro é lembrança, e é a única vez em todo o livro em que se vê como era a vida de Jó antes do capítulo 1: não um homem rico e distante, mas o cidadão a quem a cidade inteira se levantava. Ele está de saco e cinza, e a `palette` que lhe tira a coroa e a auréola diz sem palavra nenhuma o que a lembrança está a medir — a distância entre o diadema de 29:14 e o pó de 30:19. Elifaz, Bildade e Zofar estão ali, calados: desde o terceiro ciclo o debate desmanchou-se, Bildade falou seis versículos e Zofar já não abriu a boca, e daqui até 31:40 é Jó sozinho. Nenhum dos quatro se levanta do monturo; o que muda no palco é o que a fala está vendo. E o que ela está vendo, neste capítulo, é a porta da cidade num dia em que ele ainda saía de casa.",
    },
    anciao: {
      title: "Os idosos que se levantavam e se punham em pé, os nobres cuja voz se calava, e os que pranteavam e Jó consolava",
      subtitle: "Jó 29:8-10,21-25 • a praça da porta de Uz, onde a idade tem cadeira e a autoridade se mede pelo silêncio dos outros",
      text: "Estes são os velhos do lugar, e o texto marca a reverência deles por um gesto que na Antiguidade era enorme: \"Os moços me viam, e se escondiam, e até os idosos se levantavam e se punham em pé\" (Jó 29:8). Homem grisalho não se levanta para qualquer um — em Israel a lei mandava o contrário, levantar-se DIANTE do cabelo branco (Lv 19:32) —, e é justamente a inversão que Jó guarda na memória. Depois vem o mais fino: \"A voz dos nobres se calava, e a sua língua apegava-se ao seu paladar\" (Jó 29:10). Não é medo, é peso: o homem que sabia falar preferia ouvir. E ouviam de verdade: \"Ouviam-me e esperavam, e em silêncio atendiam ao meu conselho. Havendo eu falado, não replicavam, e minhas razões destilavam sobre eles\" (Jó 29:21-22). O último ancião do capítulo é o que estava de luto, porque a autoridade de Jó nunca foi só jurídica: ele fechava a sessão \"como aquele que consola os que pranteiam\" (Jó 29:25). A ironia é que os três velhos que agora se sentam à sua frente vieram exatamente para isso — \"combinaram condoer-se dele, para o consolarem\" (Jó 2:11) — e passaram vinte e nove capítulos a fazer o contrário.",
    },
    rei: {
      title: "Os príncipes que continham as suas palavras e punham a mão sobre a boca, e Jó habitando como rei entre as suas tropas",
      subtitle: "Jó 29:9,25 • o assento do chefe na rua de Uz, antes de tudo",
      text: "\"Os príncipes continham as suas palavras, e punham a mão sobre a sua boca\" (Jó 29:9). A mão sobre a boca é o gesto exato da submissão no Oriente antigo, e é o mesmo gesto que fecha o livro pelo outro lado: quando o SENHOR finalmente fala do redemoinho, é Jó quem diz \"Eis que sou vil; que te responderia eu? A minha mão ponho à boca\" (Jó 40:4). O que os príncipes de Uz faziam diante dele, ele acabará fazendo diante de Deus. O capítulo termina com a imagem mais alta que Jó se permite: \"Eu escolhia o seu caminho, assentava-me como chefe, e habitava como rei entre as suas tropas; como aquele que consola os que pranteiam\" (Jó 29:25). Ele não era rei — Uz não é um reino dele —, e por isso a frase é comparação, não título: um homem sem coroa a quem a cidade tratava como se tivesse uma. É por isso que a cena lhe dá o `diadema` de 29:14, que não é ouro: \"Vestia-me da justiça, e ela me servia de vestimenta; como manto e diadema era a minha justiça\".",
    },
    homem: {
      title: "O cego de quem Jó se fazia olhos, o coxo de quem se fazia pés, o miserável que clamava, o que ia perecendo, o moço que se escondia e o perverso cujos queixos ele quebrava",
      subtitle: "Jó 29:5,8,12-13,15,17,24 • os homens que passavam pela porta de Uz e o que ali lhes acontecia",
      text: "É o retrato mais concreto de justiça social que o livro tem, e nenhuma linha dele é abstrata. \"Eu me fazia de olhos para o cego, e de pés para o coxo\" (Jó 29:15) — não deu esmola ao cego, foi os olhos dele; não teve pena do coxo, foi os pés dele. \"Porque eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse\" (Jó 29:12): livrar quem clama é tirá-lo da mão de alguém, e o versículo seguinte diz de quem — \"E quebrava os queixos do perverso, e dos seus dentes tirava a presa\" (Jó 29:17). A imagem é de pastor arrancando a ovelha da boca do lobo, e é a mesma de Davi diante de Saul (1Sm 17:35) e de Amós (Am 3:12). Havia também os que não tinham como agradecer: \"A bênção do que ia perecendo vinha sobre mim\" (Jó 29:13). Havia os moços, que se afastavam do caminho quando ele passava (Jó 29:8), e os que nem acreditavam quando ele lhes sorria: \"Se eu ria para eles, não o criam, e a luz do meu rosto não faziam abater\" (Jó 29:24). E havia, em redor da tenda, os que o capítulo 1 já tirou de cena: \"Quando o Todo-Poderoso ainda estava comigo, e os meus filhos em redor de mim\" (Jó 29:5).",
    },
    servo: {
      title: "O servo que lavava os passos de Jó na manteiga, o que preparava a sua cadeira na rua, o órfão que não tinha quem o socorresse, o que trazia a causa desconhecida e o lavrador que esperava as suas palavras como a chuva tardia",
      subtitle: "Jó 29:6-7,12,16,23 • a casa e a rua de um homem que era pai dos necessitados",
      text: "\"Quando lavava os meus passos na manteiga, e da rocha me corriam ribeiros de azeite\" (Jó 29:6): manteiga e azeite em excesso são o modo hebraico de dizer fartura absurda — havia quem cuidasse dos pés dele com o que noutras casas era o próprio jantar. Todas as manhãs alguém saía antes dele: \"Quando eu saía para a porta da cidade, e na rua fazia preparar a minha cadeira\" (Jó 29:7); a cadeira posta na rua é o tribunal aberto, e quem a punha ali sabia a hora. Depois chegava a fila. O órfão, primeiro, que é o litigante sem ninguém para falar por ele: \"o órfão que não tinha quem o socorresse\" (Jó 29:12). Depois o que trazia um caso difícil, e aqui está a frase que separa Jó de um juiz comum: \"Dos necessitados era pai, e as causas de que eu não tinha conhecimento inquiria com diligência\" (Jó 29:16) — quando não sabia, ia averiguar, em vez de despachar. E, no fim do dia, o lavrador: \"Porque me esperavam, como à chuva; e abriam a sua boca, como à chuva tardia\" (Jó 29:23). A chuva tardia é a de março e abril, a que enche o grão já formado; perdê-la é perder a colheita inteira. Era assim que aquela gente esperava a sentença dele.",
    },
    mulherComum: {
      title: "A viúva cujo coração Jó fazia rejubilar, e as filhas de Jó em redor dele nos dias da sua mocidade",
      subtitle: "Jó 29:5,13 • a porta da cidade e a tenda sobre que estava o segredo de Deus",
      text: "\"A bênção do que ia perecendo vinha sobre mim, e eu fazia que rejubilasse o coração da viúva\" (Jó 29:13). Viúva, na sociedade antiga, é a pessoa sem representante legal: quem lhe tomasse a herança ou lhe negasse o penhor não tinha contra si mais do que a boca dela. Fazer o coração dela CANTAR — o verbo é de alegria alta, não de alívio — significa que ela saía da porta da cidade com a causa ganha, e Jó volta a jurar por isso no capítulo seguinte: \"fui o guia da viúva desde o ventre de minha mãe\" (Jó 31:18). A outra mulher deste capítulo é a que já não existe: \"Quando o Todo-Poderoso ainda estava comigo, e os meus filhos em redor de mim\" (Jó 29:5) — as três filhas que comiam e bebiam na casa do irmão mais velho quando o vento do deserto derrubou os quatro cantos (Jó 1:18-19). É o versículo em que a memória de Jó dói mais, e ele passa por ele numa linha, sem se deter.",
    },
    multidao: {
      title: "Os que ouviam Jó e o tinham por bem-aventurado, e as tropas entre as quais ele habitava como rei",
      subtitle: "Jó 29:11,25 • a praça da porta cheia, no dia em que a cidade inteira lhe dava razão",
      text: "\"Ouvindo-me algum ouvido, me tinha por bem-aventurado; vendo-me algum olho, dava testemunho de mim\" (Jó 29:11). O versículo é feito de ouvido e olho, e não de nome: quem quer que ouvisse, quem quer que visse. É a reputação de um homem numa cidade pequena, medida pelo que os desconhecidos diziam dele. E o fecho: \"assentava-me como chefe, e habitava como rei entre as suas tropas\" (Jó 29:25) — a palavra é de acampamento militar, a gente reunida em ordem em torno de quem decide. Vale olhar esta multidão sabendo o que a espera dois versículos adiante, no capítulo seguinte: a mesma cidade, o mesmo portão, e \"agora, porém, sou a sua canção, e lhes sirvo de provérbio\" (Jó 30:9). Entre os dois quadros não houve tempo nenhum e não houve crime nenhum — houve só a perda, e a perda bastou para virar a praça inteira do avesso.",
    },
  },

  // ----------------------------------------------------------------- Jó 30
  30: {
    patriarca: {
      title: "Jó lançado na lama, semelhante ao pó e à cinza, gritando ao céu que não responde",
      subtitle: "Jó 30:19-20 • o mesmo portão do capítulo 29, com a luz e o elenco invertidos",
      text: "Trinta e um versículos que são o negativo exato do capítulo anterior, e o mesmo homem no mesmo lugar. Ali, os idosos se levantavam; aqui, \"se riem de mim os de menos idade do que eu\" (Jó 30:1). Ali, a lâmpada de Deus sobre a cabeça; aqui, \"esperando eu a luz, veio a escuridão\" (Jó 30:26). Ali, os passos lavados na manteiga; aqui, \"Lançou-me na lama, e fiquei semelhante ao pó e à cinza\" (Jó 30:19). Ali, a harpa; aqui, \"A minha harpa se tornou em luto, e o meu órgão em voz dos que choram\" (Jó 30:31). No meio disso está a frase mais nua do livro inteiro, dita sem metáfora nenhuma: \"Clamo a ti, porém, tu não me respondes; estou em pé, porém, para mim não atentas\" (Jó 30:20). Jó não está a duvidar de que Deus exista — está a acusá-lo de silêncio, de pé, olhando para cima. O céu de facto não responde: nem aqui, nem em 31, nem em 37. Só em 38:1, e não com uma explicação.",
    },
    homem: {
      title: "Os de menos idade que se riem de Jó, cujos pais ele teria desdenhado de pôr com os cães do seu rebanho — os expulsos do meio dos homens, que apanhavam malvas e bramavam entre os arbustos",
      subtitle: "Jó 30:1-14 • os barrancos dos vales e as cavernas das rochas em volta de Uz, e a estrada por onde agora passa quem o despreza",
      text: "É a gente mais baixa que o livro descreve, e Jó descreve-a sem piedade nenhuma: \"Agora, porém, se riem de mim os de menos idade do que eu, cujos pais eu teria desdenhado de pôr com os cães do meu rebanho\" (Jó 30:1). São filhos de párias — \"De míngua e fome se debilitaram; e recolhiam-se para os lugares secos, tenebrosos, assolados e desertos\" (Jó 30:3) —, comem o que se colhe fora da agricultura, \"Apanhavam malvas junto aos arbustos, e o seu mantimento eram as raízes dos zimbros\" (Jó 30:4), e a cidade trata-os como se roubassem por existir: \"Do meio dos homens eram expulsos, e gritavam contra eles, como contra o ladrão\" (Jó 30:5). Moram onde os bichos moram, \"nos barrancos dos vales, e nas cavernas da terra e das rochas\" (Jó 30:6), e o verbo que Jó lhes dá não é humano — \"Bramavam entre os arbustos, e ajuntavam-se debaixo das urtigas\" (Jó 30:7), o mesmo verbo do jumento que zurra. Estes é que agora o insultam: \"Abominam-me, e fogem para longe de mim, e no meu rosto não se privam de cuspir\" (Jó 30:10); \"À direita se levantam os moços; empurram os meus pés, e preparam contra mim os seus caminhos de destruição\" (Jó 30:12). Não é só a dor que o quebra: é a ordem social invertida — quem estava debaixo dos cães está agora em cima dele.",
    },
    anciao: {
      title: "O da congregação que ouve Jó clamar por socorro em pé, no meio de todos, e não se levanta",
      subtitle: "Jó 30:28 • a assembleia de Uz, onde a cadeira de Jó agora está vazia",
      text: "\"Denegrido ando, porém não do sol; levantando-me na congregação, clamo por socorro\" (Jó 30:28). É o mesmo lugar do capítulo 29 — a assembleia da porta, onde ele se assentava como chefe e onde a voz dos nobres se calava para ele falar. Agora ele se levanta ali e pede ajuda em voz alta, diante de todos, e o versículo não registra uma única resposta. \"Denegrido\" não é do sol: é a pele enegrecida pela doença, \"Enegreceu-se a minha pele sobre mim, e os meus ossos estão queimados do calor\" (Jó 30:30) — ele entra na assembleia com o corpo a testemunhar contra ele, porque naquela teologia doença é sentença, e todo o velho ali presente já leu a sentença antes de ele abrir a boca. O homem que \"inquiria com diligência\" as causas de que não tinha conhecimento (Jó 29:16) é agora a causa que ninguém quer inquirir. É este silêncio dos anciãos que dá a medida do que Jó perdeu: não os bens, que o capítulo 1 levou, mas o direito de ser ouvido.",
    },
    mulherComum: {
      title: "A que se ajuntava debaixo das urtigas e comia as raízes dos zimbros, e a carpideira em cuja voz a harpa de Jó se tornou",
      subtitle: "Jó 30:4,7,31 • o ermo fora de Uz e a casa onde a música parou",
      text: "Duas mulheres, e são as duas pontas do capítulo. A primeira está no ermo com os expulsos: \"Apanhavam malvas junto aos arbustos, e o seu mantimento eram as raízes dos zimbros\" (Jó 30:4); \"Bramavam entre os arbustos, e ajuntavam-se debaixo das urtigas\" (Jó 30:7). Malva de sal e raiz de zimbro não são comida — são o que se rói quando não há comida —, e ajuntar-se debaixo da urtiga é dormir onde nem o gado quer pastar. A segunda é a que chora por ofício, e é a última imagem do capítulo: \"A minha harpa se tornou em luto, e o meu órgão em voz dos que choram\" (Jó 30:31). Na casa de Jó havia instrumento, e agora o instrumento serve à carpideira. É a mesma imagem que Amós usará contra Israel — \"e todos os vossos cânticos em lamentações\" (Am 8:10) —, e que fecha, sem uma palavra a mais, o quadro que o capítulo 29 tinha aberto com uma lâmpada.",
    },
    servo: {
      title: "Os que se recolhiam para os lugares secos, tenebrosos, assolados e desertos, e os que se ajuntavam debaixo das urtigas",
      subtitle: "Jó 30:3,7 • os lugares assolados em volta de Uz, onde vive quem a cidade expulsou",
      text: "Não são servos de casa nenhuma: são os que trabalhariam se alguém os quisesse, e que ninguém quer. \"De míngua e fome se debilitaram; e recolhiam-se para os lugares secos, tenebrosos, assolados e desertos\" (Jó 30:3) — a força das mãos deles já não vale nada, e Jó diz isso na cara: \"De que também me serviria a força das mãos daqueles, cujo vigor se tinha esgotado?\" (Jó 30:2). São \"filhos de doidos, e filhos de gente sem nome, e da terra foram expulsos\" (Jó 30:8): sem nome, na Bíblia, é sem linhagem, sem quem responda por eles, sem lugar na lista de ninguém. O capítulo é duríssimo com eles, e é honesto quanto a isso — Jó não os está defendendo, está medindo a própria queda pela altura de onde caiu. Mas quem lê o livro inteiro não pode deixar de ver que o homem que \"livrava o miserável, que clamava\" (Jó 29:12) e cujo bocado o órfão comia (Jó 31:17) foi parar no mesmo monturo destes, e são estes que o cospem.",
    },
    rebanho: {
      title: "O rebanho de Jó, e os cães que o guardavam — os cães com que ele não teria posto os pais daquela gente",
      subtitle: "Jó 30:1 • o pasto dos sete mil ovelhas do primeiro estado de Jó",
      text: "\"Agora, porém, se riem de mim os de menos idade do que eu, cujos pais eu teria desdenhado de pôr com os cães do meu rebanho\" (Jó 30:1). O rebanho é o de 1:3 — \"E o seu gado era de sete mil ovelhas\" —, aquele mesmo que o fogo de Deus queimou com os pastores num só dia (Jó 1:16). Os cães que o guardavam entram aqui como unidade de medida do desprezo, e é preciso saber o que cão era naquele mundo: não animal de estimação, mas bicho de rua que come cadáver (1Rs 14:11; Sl 59:6). Dizer que não se poria alguém junto dos cães do rebanho é dizer que nem para essa função ele serviria. Isaías usará a mesma figura com os vigias de Israel, \"todos são cães mudos, não podem ladrar\" (Is 56:10). O quadro na cena é o pasto vazio que a memória de Jó ainda vê: ovelhas que já não existem, guardadas por cães que valiam mais, aos olhos dele, do que os pais dos moços que agora lhe cospem no rosto.",
    },
  },

  // ----------------------------------------------------------------- Jó 31
  31: {
    patriarca: {
      title: "Jó fazendo o juramento de inocência — quarenta versículos de \"se eu fiz isto, que me aconteça aquilo\" — até \"acabaram-se as palavras de Jó\"",
      subtitle: "Jó 31:1-40 • o monturo de Uz, na última fala que ele dará antes do redemoinho",
      text: "É a peça jurídica mais completa do Antigo Testamento e funciona como um juramento de purificação: em vez de provar que é inocente, o acusado invoca sobre si mesmo a maldição correspondente a cada crime que nega. \"Se andei com falsidade… Então semeie eu e outro coma\" (Jó 31:5,8); \"Se o meu coração se deixou seduzir por uma mulher… Então moa minha mulher para outro\" (Jó 31:9-10); \"Se eu levantei a minha mão contra o órfão… Então caia do ombro a minha espádua\" (Jó 31:21-22). E ele pede o processo por escrito: \"Ah! quem me dera um que me ouvisse! Eis que o meu desejo é que o Todo-Poderoso me responda, e que o meu adversário escreva um livro\" (Jó 31:35) — e levaria a acusação ao ombro, atada por coroa, e chegaria ao juiz \"como príncipe\" (Jó 31:36-37). A lista não é de crimes visíveis: é de olhos, de coração, de intenção secreta, do direito do servo, do bocado repartido, do estrangeiro na rua. E o fim é a assinatura mais seca da Bíblia: \"Por trigo me produza cardos, e por cevada joio. Acabaram-se as palavras de Jó\" (Jó 31:40). Ele cala-se, e o silêncio dura até um moço se levantar no capítulo seguinte.",
    },
    homem: {
      title: "O viandante a quem Jó abria as portas, o que perecia por falta de roupa, o órfão que cresceu com ele como com seu pai, o dono da terra cuja alma ele não sufocou e o que tinha ódio dele e o mal o atingiu",
      subtitle: "Jó 31:8,10,18-19,29,32,39 • os homens que passaram pela porta e pelo campo de Jó, e a conta que ele faz de cada um",
      text: "Todo homem desta lista é uma oportunidade de pecar que Jó jura não ter tomado. O forasteiro é o primeiro: \"O estrangeiro não passava a noite na rua; as minhas portas abria ao viandante\" (Jó 31:32) — hospitalidade não era cortesia, era a diferença entre viver e morrer no ermo, e é o crime de Sodoma medido pelo avesso (Ez 16:49). Depois o que passa frio: \"Se alguém vi perecer por falta de roupa, e ao necessitado por não ter coberta, Se os seus lombos não me abençoaram, se ele não se aquentava com as peles dos meus cordeiros\" (Jó 31:19-20) — as peles do rebanho DELE nas costas de outro. Depois o órfão, criado dentro de casa: \"desde a minha mocidade cresceu comigo como com seu pai\" (Jó 31:18). Depois o inimigo, e aqui Jó vai mais longe do que a lei exigia: \"Se me alegrei da desgraça do que me tem ódio, e se exultei quando o mal o atingiu (Também não deixei pecar a minha boca, desejando a sua morte com maldição)\" (Jó 31:29-30) — não se alegrar com a ruína do adversário é o que Provérbios pede (Pv 24:17) e o que o Sermão do Monte tornará mandamento (Mt 5:44). E, por último, o lavrador de quem ele comprou a terra: \"Se comi os seus frutos sem dinheiro, e sufoquei a alma dos seus donos\" (Jó 31:39). O contrário disto é o que Acabe fez com Nabote.",
    },
    servo: {
      title: "O servo e a serva cujo direito Jó não desprezou, o órfão que comeu do seu bocado, a gente da sua tenda e o lavrador cujos frutos ele não comeu sem dinheiro",
      subtitle: "Jó 31:13-17,31,39 • a tenda, a mesa e o campo de Jó, e o direito de quem trabalhava neles",
      text: "O versículo 13 é dos mais radicais do Antigo Testamento: \"Se desprezei o direito do meu servo ou da minha serva, quando eles contendiam comigo\". Contender COM O SENHOR é o servo abrir processo contra o dono — coisa que no direito antigo simplesmente não existia, porque o escravo não era parte, era propriedade. Jó não só admite o processo como dá a razão de o admitir, e a razão é a criação: \"Aquele que me formou no ventre não o fez também a ele? Ou não nos formou do mesmo modo na madre?\" (Jó 31:15). É o mesmo argumento de Provérbios 22:2 e o fundamento a que Paulo apelará contra os senhores de escravos: \"o Senhor deles e vosso está no céu, e que para com ele não há acepção de pessoas\" (Ef 6:9). Na mesa, a mesma lógica: \"Ou se, sozinho comi o meu bocado, e o órfão não comeu dele\" (Jó 31:17) — comer sozinho é o pecado, não a riqueza. E a gente da tenda dá o testemunho da fartura pelo avesso, dizendo que nunca faltou carne: \"Se a gente da minha tenda não disse: Ah! quem nos dará da sua carne? Nunca nos fartaríamos dela\" (Jó 31:31). No campo, enfim, o trabalhador a quem se paga: \"Se comi os seus frutos sem dinheiro\" (Jó 31:39) — o salário retido é o clamor que Tiago ouvirá subir aos ouvidos do Senhor dos Exércitos (Tg 5:4).",
    },
    mulherComum: {
      title: "A virgem em que Jó não fixou os olhos, a serva cujo direito ele não desprezou, a viúva de quem foi guia — e a sua própria mulher, na maldição que ele invoca sobre si",
      subtitle: "Jó 31:1,9-10,13,16,18 • a aliança feita com os olhos, e a única maldição que Jó põe sobre outra pessoa",
      text: "O capítulo abre pela intenção, não pelo ato: \"Fiz aliança com os meus olhos; como, pois, os fixaria numa virgem?\" (Jó 31:1). É um pacto com a própria vista, e é o mesmo território que Jesus abrirá em Mateus 5:28 — o adultério que começa antes de qualquer gesto. Adiante, o pecado hipotético é com mulher casada, e a maldição correspondente é a mais brutal do capítulo, porque cai sobre a esposa dele: \"Então moa minha mulher para outro, e outros se encurvem sobre ela\" (Jó 31:10) — moer é trabalho de escrava, e o verbo seguinte não deixa dúvida sobre o resto. A serva aparece com direito de processo, ao lado do servo (Jó 31:13), e Jó fundamenta esse direito no ventre em que Deus formou os dois. E a viúva aparece duas vezes: \"ou fiz desfalecer os olhos da viúva\" (Jó 31:16) — desfalecer de tanto esperar uma resposta que não vem — e \"fui o guia da viúva desde o ventre de minha mãe\" (Jó 31:18). A lei de Israel repete a mesma tríade em toda parte: o estrangeiro, o órfão e a viúva (Dt 24:17). Jó jura por todos os três.",
    },
    anciao: {
      title: "Os juízes a quem pertence o delito da infâmia — os que julgariam Jó se alguma coisa daquela lista fosse verdade",
      subtitle: "Jó 31:11,28 • o tribunal da porta de Uz, invocado por um réu que quer ser processado",
      text: "Duas vezes o juramento interrompe-se para nomear o foro. Na questão do adultério: \"Porque é uma infâmia, e é delito pertencente aos juízes\" (Jó 31:11). Na questão da idolatria secreta do sol e da lua: \"Também isto seria delito à punição de juízes; pois assim negaria a Deus que está lá em cima\" (Jó 31:28). Jó está a dizer que aqueles dois pecados não são assunto de consciência particular — têm pena legal, e ele aceita o tribunal. É o oposto exato do que os amigos supõem dele. Elifaz tinha-o acusado à distância, sem instrução nenhuma: \"Porventura não é grande a tua malícia, e sem termo as tuas iniqüidades?\" (Jó 22:5). Jó responde convocando o júri e pedindo autos: \"que o meu adversário escreva um livro\" (Jó 31:35). Estes anciãos são os que se assentavam com ele à porta no capítulo 29 e que no capítulo 30 o viram levantar-se na congregação a clamar por socorro sem que ninguém se mexesse. Agora ele os chama de volta, e nenhum vem: a única resposta virá do redemoinho, e não será a que ele pediu.",
    },
    multidao: {
      title: "A grande multidão que Jó temia, e o desprezo das famílias que o apavorava — o medo que ele jura não ter tido",
      subtitle: "Jó 31:34 • a praça cheia de Uz, e a porta de que ele não se calou",
      text: "Perto do fim da lista aparece um pecado que quase nenhuma lei antiga previa: a covardia social. \"Porque eu temia a grande multidão, e o desprezo das famílias me apavorava, e eu me calei, e não saí da porta\" (Jó 31:34). A frase está na forma condicional do juramento — se eu tivesse feito isso —, e o que ela nega é o silêncio de quem sabe da injustiça e não vai à porta dizê-la, com medo do que as famílias importantes da cidade vão comentar. Para o homem que se assentava como chefe (Jó 29:25), esse era o pecado mais fácil e mais invisível de todos: bastava não aparecer. É a mesma coisa que Isaías cobrará dos príncipes de Jerusalém, \"não fazem justiça ao órfão, e não chega perante eles a causa da viúva\" (Is 1:23), e o que Provérbios pede em duas linhas: \"Abre a tua boca a favor do mudo, pela causa de todos que são designados à destruição\" (Pv 31:8). A multidão em cena é a mesma que no capítulo 30 o transformou em canção e provérbio — e diante da qual ele jura, agora, nunca ter recuado.",
    },
  },

  // ----------------------------------------------------------------- Jó 32
  32: {
    homem: {
      title: "Eliú, filho de Baraquel, o buzita, da família de Rão — o quinto homem do monturo, o único moço no meio de quatro velhos; e o homem em quem há um espírito",
      subtitle: "Jó 32:2-9,18-19 • a cinzeira de Uz, no silêncio que se abre quando os três param de responder",
      text: "\"Então aqueles três homens cessaram de responder a Jó; porque era justo aos seus próprios olhos\" (Jó 32:1) — e no silêncio levanta-se alguém que ninguém tinha apresentado e que estava ali desde o capítulo 3. Ele é `homem` e não `patriarca` porque o texto insiste nisso duas vezes: \"Eliú, porém, esperou para falar a Jó, porquanto tinham mais idade do que ele\" (Jó 32:4), e \"Eu sou de menos idade, e vós sois idosos; receei-me e temi de vos declarar a minha opinião\" (Jó 32:6). A ira dele acende-se duas vezes, e por motivos opostos: contra Jó, \"porque se justificava a si mesmo, mais do que a Deus\" (Jó 32:2), e contra os três, \"porque, não achando que responder, todavia condenavam a Jó\" (Jó 32:3). A tese que o autoriza a falar é a única coisa nova que o livro põe na boca de um homem até aqui: \"Na verdade, há um espírito no homem, e a inspiração do TodoPoderoso o faz entendido. Os grandes não são os sábios, nem os velhos entendem o que é direito\" (Jó 32:8-9). E a imagem com que ele se descreve é a mais física do bloco: \"Eis que dentro de mim sou como o mosto, sem respiradouro, prestes a arrebentar, como odres novos\" (Jó 32:19). Guarde-se um detalhe para o capítulo 42: quando o SENHOR repreender \"a Elifaz, o temanita… e contra os teus dois amigos\" (Jó 42:7), Eliú não é nomeado, não é repreendido e não tem de oferecer holocausto nenhum.",
    },
    patriarca: {
      title: "Jó, justo aos seus próprios olhos, e os três amigos que cessaram de responder — pasmados, sem palavras",
      subtitle: "Jó 32:1,12,15-16 • o monturo, no fim do debate e antes da resposta do céu",
      text: "Os quatro velhos estão em cena e nenhum deles fala neste capítulo. Jó calou-se em 31:40 — \"acabaram-se as palavras de Jó\" — e não voltará a abrir a boca até 40:3. Os três consoladores ficaram sem argumento, e o texto diz isso três vezes, o que é raro: \"cessaram de responder a Jó; porque era justo aos seus próprios olhos\" (Jó 32:1); \"eis que nenhum de vós há que possa convencer a Jó, nem que responda às suas razões\" (Jó 32:12); \"Estão pasmados, não respondem mais, faltam-lhes as palavras\" (Jó 32:15). Eliú ainda lhes tira a última saída, que era atribuir o fim do debate a uma vitória teológica: \"Para que não digais: Achamos a sabedoria; Deus o derrubou, e não homem algum\" (Jó 32:13). E marca a diferença da sua própria posição: \"Ora ele não dirigiu contra mim palavra alguma, nem lhe responderei com as vossas palavras\" (Jó 32:14). No palco, os quatro estão sentados ou curvados nas pedras da roda, e Jó continua de saco e cinza — não voltou ao seu traje desde 1:20, e só sairá dele em 42:10.",
    },
    anciao: {
      title: "Os anciãos de Uz, cujos dias deviam falar e cuja multidão de anos devia ensinar a sabedoria",
      subtitle: "Jó 32:6-7 • a praça da porta, onde a idade tinha o direito da primeira palavra",
      text: "\"Dizia eu: Falem os dias, e a multidão dos anos ensine a sabedoria\" (Jó 32:7). É a regra inteira daquela cultura numa linha, e é por ela que Eliú passou trinta capítulos calado no fundo do quadro. Quem se assenta à porta e fala primeiro é o velho; quem tem menos anos ouve e espera. A mesma ordem aparece em Levítico 19:32, em Provérbios 16:31 e no cuidado que Paulo pede a Timóteo, que era moço num lugar de autoridade (1Tm 4:12; 5:1). O que Eliú faz em seguida é derrubar a regra sem faltar ao respeito devido: esperou tudo o que devia esperar, e então diz \"Os grandes não são os sábios, nem os velhos entendem o que é direito\" (Jó 32:9). A sabedoria não vem do tempo, vem do sopro — \"a inspiração do TodoPoderoso o faz entendido\" (Jó 32:8). Estes anciãos em cena são os que estariam sentados nas pedras da roda enquanto o moço fala em pé: a autoridade que se calou porque ficou sem resposta, e não porque cedeu o lugar.",
    },
    servo: {
      title: "O servo que guarda os odres novos do mosto, cheios e sem respiradouro, prestes a arrebentar",
      subtitle: "Jó 32:19 • a adega de Uz, no retrato que Eliú faz de si mesmo",
      text: "\"Eis que dentro de mim sou como o mosto, sem respiradouro, prestes a arrebentar, como odres novos\" (Jó 32:19). Quem cuidava do vinho conhecia o perigo exato de que ele fala: mosto é suco em plena fermentação, e a fermentação faz gás; um odre novo, ainda elástico, aguenta a pressão, mas um odre já usado e endurecido rasga — é a figura que Jesus usará em Mateus 9:17. Eliú inverte a imagem: ele é o odre novo, cheio até em cima, e o que lhe falta é a abertura por onde o gás sai. Por isso o versículo seguinte é um alívio pedido, não uma bravata: \"Falarei, para que ache alívio; abrirei os meus lábios, e responderei\" (Jó 32:20). O servo da adega é quem está ali para abrir o respiradouro na hora certa, e a cena o põe entre os odres inchados como quem sabe quanto tempo mais aquilo aguenta. Depois de arrebentar, o moço promete uma coisa que nenhum dos três velhos prometeu: \"Que não faça eu acepção de pessoas, nem use de palavras lisonjeiras com o homem! Porque não sei usar de lisonjas; em breve me levaria o meu Criador\" (Jó 32:21-22).",
    },
  },

  // ----------------------------------------------------------------- Jó 33
  33: {
    homem: {
      title: "Eliú, formado do barro como Jó; o homem sobre quem cai sono profundo, o que na cama é castigado com dores, o que tem os pés postos no tronco, e aquele a quem o intérprete declara a sua retidão",
      subtitle: "Jó 33:6,11,15,19,23-25 • as duas maneiras de Deus falar — o sonho da noite e a dor na cama",
      text: "Eliú é o único que chama Jó pelo nome, e a primeira coisa que faz é tirar-se do pedestal de onde os três falavam: \"Eis que vim de Deus, como tu; do barro também eu fui formado. Eis que não te perturbará o meu terror, nem será pesada sobre ti a minha mão\" (Jó 33:6-7). Depois cita Jó de cor, inclusive a queixa do cepo — \"Põe no tronco os meus pés, e observa todas as minhas veredas\" (Jó 33:11) — e responde que Deus fala, sim, e de dois modos. O primeiro é o sonho: \"Em sonho ou em visão noturna, quando cai sono profundo sobre os homens, e adormecem na cama. Então o revela ao ouvido dos homens, e lhes sela a sua instrução\" (Jó 33:15-16), e a finalidade não é informar, é desviar — \"Para apartar o homem daquilo que faz, e esconder do homem a soberba\" (Jó 33:17). O segundo é a dor, descrita de dentro do corpo: \"Também na sua cama é castigado com dores; e com incessante contenda nos seus ossos… Desaparece a sua carne a olhos vistos, e os seus ossos, que não se viam, agora aparecem\" (Jó 33:19,21). E entre a cova e o homem entra a figura mais surpreendente do bloco: \"Se com ele, pois, houver um mensageiro, um intérprete, um entre milhares, para declarar ao homem a sua retidão, Então terá misericórdia dele, e lhe dirá: Livra-o, para que não desça à cova; já achei resgate\" (Jó 33:23-24). Um entre milhares, que interpreta e apresenta resgate — é o eco mais próximo que o Antigo Testamento tem do ofício dos anjos como \"espíritos ministradores\" (Hb 1:14) e do único Mediador que se deu a si mesmo em resgate (1Tm 2:5-6). E o resultado: \"Sua carne se reverdecerá mais do que era na mocidade, e tornará aos dias da sua juventude\" (Jó 33:25).",
    },
    patriarca: {
      title: "Jó, chamado pelo nome — \"Assim, na verdade, ó Jó, ouve as minhas razões\" — e os três amigos calados a ouvir",
      subtitle: "Jó 33:1,31-33 • o monturo, no primeiro discurso que trata Jó como interlocutor e não como réu",
      text: "\"Assim, na verdade, ó Jó, ouve as minhas razões, e dá ouvidos a todas as minhas palavras\" (Jó 33:1). Nos vinte e nove capítulos anteriores, nenhum dos três amigos chamou Jó pelo nome uma única vez; falaram dele na terceira pessoa e com ele em generalidades sobre o ímpio. O moço começa pelo nome e acaba com uma frase que nenhum deles disse: \"Se tens alguma coisa que dizer, responde-me; fala, porque desejo justificar-te\" (Jó 33:32). Desejo justificar-te — quer dizer, quero que saias daqui com razão. O que ele contesta é uma coisa só, e é bem escolhida: não o sofrimento de Jó, mas a acusação de que Deus se calou. \"Por que razão contendes com ele, sendo que não responde acerca de todos os seus feitos? Antes Deus fala uma e duas vezes; porém ninguém atenta para isso\" (Jó 33:13-14). Jó continua de saco e cinza, sem um único balão neste bloco inteiro; Elifaz, Bildade e Zofar, que já cessaram de responder, ficam em pé, curvados ou de joelhos, calados até o SENHOR se dirigir a eles em 42:7.",
    },
    servo: {
      title: "O guarda que observa todas as veredas do preso no tronco, o servo que traz a comida apetecível que o doente recusa, e o moço que ouviu no vale a confissão do restituído",
      subtitle: "Jó 33:11,20,27 • o cepo, a cabeceira e a praça — os três lugares em que o capítulo se passa",
      text: "Três serviços humildes, e cada um deles é uma cena inteira. O primeiro é o carcereiro da imagem que Jó usou contra Deus: \"Põe no tronco os meus pés, e observa todas as minhas veredas\" (Jó 33:11) — tronco é o cepo de madeira em que se prendiam os pés do preso, o mesmo em que Jeremias passou uma noite (Jr 20:2) e em que Paulo e Silas cantaram à meia-noite (At 16:24); o guarda que anota cada passo é a figura de um Deus que Jó, naquele momento, sente como vigia e não como pai. O segundo está à cabeceira: \"De modo que a sua vida abomina até o pão, e a sua alma a comida apetecível\" (Jó 33:20) — alguém prepara o melhor prato da casa e leva-o ao quarto, e o doente vira o rosto; é o detalhe pelo qual se reconhece uma doença que já não é passageira. O terceiro está na rua, quando o homem se levanta curado e faz em público o que fez em segredo: \"Olhará para os homens, e dirá: Pequei, e perverti o direito, o que de nada me aproveitou. Porém Deus livrou a minha alma de ir para a cova, e a minha vida verá a luz\" (Jó 33:27-28). O moço que ouve essa confissão é quem leva a história adiante — é assim que o testemunho corre numa cidade pequena.",
    },
  },

  // ----------------------------------------------------------------- Jó 34
  34: {
    homem: {
      title: "Eliú falando aos sábios; e os homens da sua tese — o poderoso tomado não por mão humana, o forte quebrantado sem inquirição, o que voltou para o pó, o ímpio batido à vista dos espectadores e o que procura esconderijo onde não há trevas",
      subtitle: "Jó 34:14-15,20,22,24-26 • o tribunal que Eliú monta no monturo, com o mundo inteiro por prova",
      text: "Neste capítulo Eliú deixa de falar a Jó e vira-se para a assistência: \"Ouvi, vós, sábios, as minhas razões; e vós, entendidos, inclinai os ouvidos para mim\" (Jó 34:2). A tese é a justiça de Deus — \"Longe de Deus esteja o praticar a maldade e do Todo-Poderoso o cometer a perversidade!\" (Jó 34:10) — e a prova é a dependência absoluta de tudo o que respira: \"Se ele pusesse o seu coração contra o homem, e recolhesse para si o seu espírito e o seu fôlego, Toda a carne juntamente expiraria, e o homem voltaria para o pó\" (Jó 34:14-15). Não é preciso que Deus faça nada para acabar o mundo: basta que retome o que emprestou; é o mesmo pensamento do Salmo 104:29 e de Eclesiastes 12:7. Daí sai o resto dos homens desta cena. O poderoso: \"Eles num momento morrem; e até à meia-noite os povos são perturbados, e passam, e os poderosos serão tomados não por mão humana\" (Jó 34:20). O forte deposto sem processo: \"Quebranta aos fortes, sem que se possa inquirir, e põe outros em seu lugar\" (Jó 34:24). O que se esconde: \"Não há trevas nem sombra de morte, onde se escondam os que praticam a iniqüidade\" (Jó 34:22). E o castigo público: \"Ele os bate como ímpios que são, à vista dos espectadores\" (Jó 34:26). O veredito sobre Jó, no fim, é o mais duro que o moço dará: \"Jó falou sem conhecimento; e às suas palavras falta prudência\" (Jó 34:35).",
    },
    anciao: {
      title: "Os sábios e os entendidos a quem Eliú declara as suas razões, e os homens de entendimento que hão de julgar com ele",
      subtitle: "Jó 34:2-4,10,16,34 • a roda dos que ouvem, e o rolo das razões aberto no alpendre",
      text: "\"Ouvi, vós, sábios, as minhas razões; e vós, entendidos, inclinai os ouvidos para mim\" (Jó 34:2). Eliú muda de destinatário e, com isso, muda o gênero do discurso: já não é conversa de cabeceira, é sessão pública. A imagem que ele usa para explicar o método é doméstica e exata: \"Porque o ouvido prova as palavras, como o paladar experimenta a comida\" (Jó 34:3) — o ouvido tem de mastigar antes de engolir, e a mesma figura reaparecerá em Hebreus 5:14, nos que \"os quais, em razão do costume, têm os sentidos exercitados para discernir tanto o bem como o mal\". A proposta que ele põe à mesa é de júri, não de sermão: \"O que é direito escolhamos para nós; e conheçamos entre nós o que é bom\" (Jó 34:4). E no fim ele reclama o veredito da própria assistência: \"Os homens de entendimento dirão comigo, e o homem sábio que me ouvir: Jó falou sem conhecimento\" (Jó 34:34-35). Estes anciãos são o público que o palco monta em volta do monturo, e a ironia é que o Juiz que eles supõem estar a representar dará, no capítulo 42, uma sentença que nenhum deles previu.",
    },
    rei: {
      title: "O rei a quem não se diria \"Oh! Vil\", os príncipes a quem não se diria \"Oh! ímpios\" — e o homem hipócrita que nunca mais há de reinar",
      subtitle: "Jó 34:18-19,30 • a corte que Eliú convoca só para mostrar que o trono não protege ninguém",
      text: "O argumento é de escada: se nem a um rei se atira a cara \"Oh! Vil\", nem aos príncipes \"Oh! ímpios\" (Jó 34:18), quanto menos a Deus — e a razão de Deus estar acima disso não é ser mais alto, é não ter preferidos: \"àquele, que não faz acepção das pessoas de príncipes, nem estima o rico mais do que o pobre; porque todos são obras de suas mãos\" (Jó 34:19). Todos são obras de suas mãos: é a mesma frase que Jó usou para defender o direito do servo (Jó 31:15), e a que o Novo Testamento repete sobre Deus não fazer acepção de pessoas (At 10:34; Rm 2:11). Do outro lado da escada está o trono que cai: \"Para que o homem hipócrita nunca mais reine, e não haja laços no povo\" (Jó 34:30). Laços — armadilhas — é o que um governo ímpio arma para os seus, e tirá-lo do trono é desarmar o campo. Vale notar quem Eliú diz que Deus exalta, no capítulo seguinte do seu próprio discurso: \"Do justo não tira os seus olhos; antes estão com os reis no trono; ali os assenta para sempre\" (Jó 36:7).",
    },
    servo: {
      title: "O pobre cujo clamor subiu até ele, os aflitos que ele ouviu, o povo perturbado à meia-noite e o povo livrado dos laços do hipócrita",
      subtitle: "Jó 34:19-20,28,30 • as ruas da cidade em que o argumento de Eliú se verifica",
      text: "A prova de que Deus julga com retidão, para Eliú, não está no céu: está em quem é ouvido. \"De sorte que o clamor do pobre subisse até ele, e que ouvisse o clamor dos aflitos\" (Jó 34:28) — e o versículo antes diz o motivo do juízo, que é ter fechado o ouvido: \"Porquanto se desviaram dele, e não compreenderam nenhum de seus caminhos\" (Jó 34:27). Este pobre é o mesmo de 34:19, e o argumento que o protege é o mais simples possível: o rico não vale mais, \"porque todos são obras de suas mãos\". Depois há o povo que acorda no meio de uma queda de governo: \"Eles num momento morrem; e até à meia-noite os povos são perturbados, e passam, e os poderosos serão tomados não por mão humana\" (Jó 34:20) — meia-noite é a hora bíblica das viradas súbitas, a mesma do Egito (Êx 12:29) e da prisão de Filipos (At 16:25). E há o povo do lado de fora da armadilha desmontada: \"Para que o homem hipócrita nunca mais reine, e não haja laços no povo\" (Jó 34:30). São estes, e não os príncipes, que sustentam a tese do capítulo.",
    },
    mulherComum: {
      title: "A aflita cujo clamor ele ouviu, e a mulher cuja carne expiraria juntamente com toda a carne se Deus recolhesse o seu fôlego",
      subtitle: "Jó 34:15,28 • o pátio de onde sobe o clamor, e a criatura inteira dependurada num sopro",
      text: "\"E que ouvisse o clamor dos aflitos\" (Jó 34:28): a palavra abrange precisamente quem não tem a quem recorrer, e na sociedade antiga isso quer dizer, antes de mais ninguém, a mulher sem marido e sem filho adulto — a mesma viúva por quem Jó jurou em 31:16 e a mesma cujo coração ele fazia rejubilar em 29:13. O clamor sobe: é a linguagem do sangue de Abel (Gn 4:10) e do gemido de Israel no Egito (Êx 2:23), e em ambos os casos o texto diz que Deus ouviu. A outra imagem em que esta mulher está incluída é a mais universal do capítulo, e não distingue ninguém: \"Se ele pusesse o seu coração contra o homem, e recolhesse para si o seu espírito e o seu fôlego, Toda a carne juntamente expiraria, e o homem voltaria para o pó\" (Jó 34:14-15). Toda a carne, juntamente, no mesmo instante — o rico e o pobre, o príncipe e a aflita do pátio. É a igualdade que o argumento de Eliú tem por fundamento, e a mesma que Paulo levará ao Areópago: \"nele vivemos, e nos movemos, e existimos\" (At 17:28).",
    },
    pastor: {
      title: "O pastor do vale — a quem se pergunta quem lhe entregou o governo da terra",
      subtitle: "Jó 34:13 • a encosta em volta de Uz, na pergunta que não tem resposta humana",
      text: "\"Quem lhe entregou o governo da terra? E quem fez todo o mundo?\" (Jó 34:13). A pergunta é de procuração: um administrador responde perante quem o nomeou, e Eliú está a mostrar que sobre Deus não há nomeante nenhum — não há a quem Ele preste contas, e por isso não há como acusá-lo de abuso de mandato. A figura em cena é a de quem recebe terra para guardar e a devolve com contas: o pastor a quem se entrega um vale, um rebanho e um prazo. Toda a Escritura pensa a criação assim, do jardim que Adão devia lavrar e guardar (Gn 2:15) às parábolas dos lavradores e dos talentos (Mt 21:33; 25:14). A diferença é o degrau de cima: o pastor tem dono, e o Dono não tem. Vale ler ao lado a única resposta que o livro dará a esta pergunta, e virá do redemoinho, na mesma forma interrogativa: \"Onde estavas tu, quando eu fundava a terra?\" (Jó 38:4).",
    },
    patriarca: {
      title: "Jó, de quem Eliú diz que bebe a zombaria como água, e os três amigos que já não respondem",
      subtitle: "Jó 34:5-9,35-37 • o monturo, no capítulo em que Jó é julgado à revelia sem se defender",
      text: "Eliú faz o que nenhum dos três tinha feito: cita Jó textualmente antes de o contradizer. \"Porque Jó disse: Sou justo, e Deus tirou o meu direito\" (Jó 34:5) — e é verdade, está em 27:2. \"Apesar do meu direito sou considerado mentiroso; a minha ferida é incurável, embora eu esteja sem transgressão\" (Jó 34:6). E também a frase mais perigosa que Jó soltou: \"Porque disse: De nada aproveita ao homem o comprazer-se em Deus\" (Jó 34:9) — que é, palavra por palavra, a tese que Satanás propôs no capítulo 1 e que todo o livro existe para desmentir. Sobre isso Eliú é severo: \"Que homem há como Jó, que bebe a zombaria como água? E caminha em companhia dos que praticam a iniqüidade\" (Jó 34:7-8), e pede que a prova continue: \"Pai meu! Provado seja Jó até ao fim\" (Jó 34:36). Jó não responde uma palavra — está calado desde 31:40 —, e o leitor sabe o que nenhum dos cinco sabe: o SENHOR, no fim, dirá exatamente o contrário sobre ele, \"como o meu servo Jó\" (Jó 42:7-8).",
    },
  },

  // ----------------------------------------------------------------- Jó 35
  35: {
    homem: {
      title: "Eliú mandando olhar para as mais altas nuvens; o outro tal como tu a quem a tua impiedade faria mal, o grande cujo braço oprime, e o homem que recebe salmos durante a noite",
      subtitle: "Jó 35:5-10 • o capítulo mais curto e mais frio do bloco, e a única linha quente que há nele",
      text: "O argumento de Jó 35 é uma correção de escala, e começa mandando levantar a cabeça: \"Atenta para os céus, e vê; e contempla as mais altas nuvens, que são mais altas do que tu\" (Jó 35:5). Se a nuvem já está fora do alcance, o Altíssimo está a que distância? Daí as duas perguntas gêmeas: \"Se pecares, que efetuarás contra ele? Se as tuas transgressões se multiplicarem, que lhe farás? Se fores justo, que lhe darás, ou que receberá ele da tua mão?\" (Jó 35:6-7). A resposta é a frase que dá a este homem o seu lugar em cena: \"A tua impiedade faria mal a outro tal como tu; e a tua justiça aproveitaria ao filho do homem\" (Jó 35:8). O mal e o bem que fazemos atingem o vizinho, não o Altíssimo — o que não é indiferença de Deus, é dignidade do próximo. Depois vem o oprimido que clama sem rezar: \"Por causa das muitas opressões os homens clamam por causa do braço dos grandes. Porém ninguém diz: Onde está Deus que me criou, que dá salmos durante a noite\" (Jó 35:9-10). Grita-se contra o braço que aperta e não se pergunta pelo Criador — e é aqui que o capítulo frio solta a sua única imagem quente, a de um Deus que põe canção dentro da noite de quem sofre, como o cântico de Paulo e Silas à meia-noite (At 16:25) e o \"de noite a sua canção estará comigo\" do Salmo 42:8.",
    },
    servo: {
      title: "O oprimido que clama por causa do braço dos grandes, e não é respondido por causa da arrogância dos maus",
      subtitle: "Jó 35:9,12-13 • o pátio dos que gritam, no capítulo em que o grito não basta",
      text: "\"Por causa das muitas opressões os homens clamam por causa do braço dos grandes\" (Jó 35:9). O braço dos grandes é o poder concreto do latifundiário, do credor, do magistrado — o mesmo braço que Jó jurou nunca ter levantado contra o órfão (Jó 31:21). O clamor é legítimo, e a Escritura garante em toda parte que Deus o ouve (Êx 3:7; Tg 5:4). O que Eliú acrescenta é duro e é preciso ler com cuidado: \"Clamam, porém ele não responde, por causa da arrogância dos maus. Certo é que Deus não ouvirá a vaidade, nem atentará para ela o Todo-Poderoso\" (Jó 35:12-13). Não é que o oprimido não seja ouvido; é que existe um grito que é só dor e não procura ninguém — \"ninguém diz: Onde está Deus que me criou\" (Jó 35:10). Este servo em cena é o que grita para o alto sem endereço, e a cena o põe no pátio, de mãos erguidas, com Eliú na borda a apontar para as nuvens mais altas do que ele. Se o argumento é justo com Jó, é outra questão: o SENHOR, no capítulo 42, não dirá que Jó falou de menos — dirá que os outros falaram errado.",
    },
    mulherComum: {
      title: "A aflita do pátio que clamou junto com os oprimidos por causa do braço dos grandes",
      subtitle: "Jó 35:9-10 • a mesma opressão vista de quem tem ainda menos recurso",
      text: "\"Por causa das muitas opressões os homens clamam por causa do braço dos grandes\" (Jó 35:9). No pátio de onde sobe esse clamor está quem, naquela sociedade, tinha menos meio de resistir a um braço forte: a mulher sem quem a defendesse. É dela que a lei de Israel fala quando ameaça o opressor com a viuvez e a orfandade dos próprios filhos — \"e a minha ira se acenderá, e vos matarei à espada; e vossas mulheres ficarão viúvas, e vossos filhos órfãos\" (Êx 22:22-24). Eliú não nega a legitimidade do clamor; aponta o que falta nele: \"Porém ninguém diz: Onde está Deus que me criou, que dá salmos durante a noite\" (Jó 35:10). É uma censura que soa fria dita a quem está debaixo do braço, e o livro não a endossa nem a desmente aqui. O que o palco mostra é a figura de pé no pátio, com as mãos erguidas, debaixo de um céu de nuvens altas — e a promessa, escondida no meio da repreensão, de que há canção que se dá de noite.",
    },
    rebanho: {
      title: "Os animais da terra e as aves dos céus, a quem Deus também ensina — mas menos do que ao homem",
      subtitle: "Jó 35:11 • o pasto e o bando, na comparação que mede o que o homem recebeu",
      text: "\"Que nos ensina mais do que aos animais da terra e nos faz mais sábios do que as aves dos céus?\" (Jó 35:11). O versículo pressupõe que o bicho também é ensinado — o instinto que leva a cegonha a saber o seu tempo (Jr 8:7) e a formiga a preparar o pão no verão (Pv 6:6-8) é instrução de Deus, e não acaso —, e afirma que ao homem foi dado mais. Esse mais é exatamente aquilo que Eliú acusa Jó e os oprimidos de não estarem usando: a capacidade de perguntar \"Onde está Deus que me criou\" (Jó 35:10). O animal geme sem endereço porque não tem outro; o homem, que tem, faz o mesmo. Vale ler ao lado o começo de Isaías, que faz a comparação virar acusação: \"O boi conhece o seu possuidor, e o jumento a manjedoura do seu dono; mas Israel não tem conhecimento, o meu povo não entende\" (Is 1:3). Em cena, o rebanho é o pasto tranquilo no fundo do quadro enquanto o homem clama em primeiro plano — a criatura muda a fazer, sem palavra nenhuma, o que a criatura falante deixou de fazer.",
    },
    patriarca: {
      title: "Jó, de quem Eliú diz que em vão abre a sua boca e sem ciência multiplica palavras",
      subtitle: "Jó 35:2-4,16 • o monturo, no capítulo em que a acusação se afina",
      text: "Eliú abre o capítulo repetindo o que ouviu de Jó, e afina a acusação a um ponto que os três amigos nunca alcançaram: \"Tens por direito dizeres: Maior é a minha justiça do que a de Deus?\" (Jó 35:2). Jó nunca disse essa frase com essas palavras, mas disse coisas que a implicam — \"Sou justo, e Deus tirou o meu direito\" (Jó 34:5) — e é sobre a implicação que o moço trabalha. Depois cita a queixa de proveito: \"Porque disseste: De que me serviria? Que proveito tiraria mais do que do meu pecado?\" (Jó 35:3). E anuncia que a resposta é para os quatro: \"Eu te darei resposta, a ti e aos teus amigos contigo\" (Jó 35:4) — os três velhos continuam em cena e continuam calados. O fecho é o veredito mais curto do bloco: \"Logo Jó em vão abre a sua boca, e sem ciência multiplica palavras\" (Jó 35:16). Sem ciência: é palavra por palavra o que o SENHOR dirá do redemoinho três capítulos adiante — \"Quem é este que escurece o conselho com palavras sem conhecimento?\" (Jó 38:2) —, e é a única vez em que um discurso humano deste livro antecipa a acusação divina.",
    },
  },

  // ----------------------------------------------------------------- Jó 36
  36: {
    homem: {
      title: "O preso em grilhões, amarrado com cordas de aflição, a quem Deus abre o ouvido pela própria corda; o convidado à mesa cheia de gordura em lugar espaçoso; e o que não ouviu e à espada foi passado",
      subtitle: "Jó 36:8-16 • a cadeia, a mesa e o campo, nos três desfechos que Eliú põe lado a lado",
      text: "A parte mais original do discurso de Eliú está aqui, e é uma ideia que nenhum dos três amigos teve: a aflição não é só castigo, é comunicação. \"E se estão presos em grilhões, amarrados com cordas de aflição, Então lhes faz saber a obra deles, e as suas transgressões, porquanto prevaleceram nelas. Abre-lhes também os seus ouvidos, para sua disciplina, e ordena-lhes que se convertam da maldade\" (Jó 36:8-10). O ouvido abre-se pela mesma corda que aperta — é a doutrina que Hebreus 12:5-11 desenvolverá e que o Salmo 119:71 resume, \"foi-me bom ter sido afligido\". Dali saem duas estradas. A primeira: \"Se o ouvirem, e o servirem, acabarão seus dias em bem, e os seus anos em delícias\" (Jó 36:11), e a mesa correspondente é larga — \"te desviará da boca da angústia para um lugar espaçoso, em que não há aperto, e as iguarias da tua mesa serão cheias de gordura\" (Jó 36:16). A segunda: \"Porém se não o ouvirem, à espada serão passados, e expirarão sem conhecimento\" (Jó 36:12). E entre as duas há o que se recusa a gritar mesmo amarrado: \"E os hipócritas de coração amontoam para si a ira; e amarrando-os ele, não clamam por socorro. A sua alma morre na mocidade, e a sua vida perece entre os impuros\" (Jó 36:13-14). O que Eliú não vê é que a aflição de Jó não estava em nenhuma das duas colunas.",
    },
    servo: {
      title: "O aflito a quem ele livra da sua aflição e na opressão se revela aos ouvidos; o homem sobre quem as nuvens gotejam abundantemente; e o tesoureiro do ouro que não compra livramento nenhum",
      subtitle: "Jó 36:15,19,28 • a porta, a arca do tesouro e o campo debaixo da chuva",
      text: "\"Ao aflito livra da sua aflição, e na opressão se revela aos seus ouvidos\" (Jó 36:15). A frase é de uma precisão notável: não diz que Deus se revela DEPOIS da opressão, diz que se revela NELA — dentro do aperto, e pelo ouvido. É a mesma coisa que 36:10 tinha dito da cadeia, e é o miolo de toda a teologia de Eliú. Contra isso ele põe o que não serve: \"Estimaria ele tanto tuas riquezas? Não, nem ouro, nem todas as forças do poder\" (Jó 36:19), e antes já tinha avisado que \"nem com resgate algum te livrarias dele\" (Jó 36:18) — o que Pedro dirá com outras palavras, que não fomos resgatados \"com coisas corruptíveis, como prata ou ouro\" (1Pe 1:18). O terceiro servo desta cena está no campo, e é o que recebe de graça o que o ouro não compra: \"Porque faz miúdas as gotas das águas que, do seu vapor, derramam a chuva, A qual as nuvens destilam e gotejam sobre o homem abundantemente\" (Jó 36:27-28). Do versículo 27 em diante o discurso deixa de argumentar e vira hino, e o palco muda com ele: entra o vapor, a nuvem, a gota, e o temporal que o capítulo 37 vai fechar.",
    },
    anciao: {
      title: "O velho que acabou os seus dias em bem, o conselheiro que viu o justo ser exaltado e o homem que se lembrou de engrandecer a obra que todos contemplam",
      subtitle: "Jó 36:7,11,24-25 • o trono dos justos e o mirante de onde se vê a obra",
      text: "Eliú tem uma versão do fim da vida do justo, e é a que Jó julgava ter perdido: \"Do justo não tira os seus olhos; antes estão com os reis no trono; ali os assenta para sempre, e assim são exaltados\" (Jó 36:7), e \"Se o ouvirem, e o servirem, acabarão seus dias em bem, e os seus anos em delícias\" (Jó 36:11). É boa doutrina em geral e péssima aplicada ao homem sentado à frente dele — e o livro termina, curiosamente, dando razão à doutrina no caso concreto, porque Jó acabará \"velho e farto de dias\" (Jó 42:17), só que por um caminho que Eliú não previu. O outro ancião desta cena é o que sabe olhar: \"Lembra-te de engrandecer a sua obra, que os homens contemplam. Todos os homens a vêem, e o homem a enxerga de longe\" (Jó 36:24-25). Engrandecer a obra é o ofício do louvor, e o verbo aqui é o mesmo que abre tantos salmos (Sl 34:3). É também o que prepara o capítulo seguinte: quem passou a vida a olhar para o céu está pronto para ouvir o trovão como voz e não como ruído.",
    },
    pastor: {
      title: "O pastor que viu o temporal subir, avisado pelo gado; o que recebeu a chuva na encosta; e o pastor do vale a quem Deus, sendo mui grande, não despreza",
      subtitle: "Jó 36:5,27-28,33 • a encosta em volta de Uz, no vestíbulo do redemoinho",
      text: "O pastor é a figura certa para o fim deste capítulo, porque o fim deste capítulo é meteorologia. \"Porque faz miúdas as gotas das águas que, do seu vapor, derramam a chuva, A qual as nuvens destilam e gotejam sobre o homem abundantemente\" (Jó 36:27-28) — o ciclo inteiro, do vapor à gota, descrito com uma exatidão que só quem vive fora de casa tem. E o remate é o versículo mais estranho e mais bonito do capítulo: \"O que nos dá a entender o seu pensamento, como também ao gado, acerca do temporal que sobe\" (Jó 36:33). O gado sente a tempestade antes do homem — inquieta-se, ajunta-se, procura abrigo —, e Eliú diz que esse pressentimento é aviso de Deus, dado ao bicho e dado a nós. Quem pastoreia sabe ler o rebanho como quem lê o céu. O primeiro versículo do capítulo já tinha posto este homem no seu lugar: \"Eis que Deus é mui grande, contudo a ninguém despreza; grande é em força e sabedoria\" (Jó 36:5). Grande e sem desprezo pelo pequeno — é a dobradiça de que todo o discurso depende, e é o que a cena mostra pondo o pastor do vale debaixo de um céu que já está a fechar.",
    },
    rebanho: {
      title: "O gado que dá notícia do temporal que sobe",
      subtitle: "Jó 36:33 • a última imagem do capítulo, e a porta de entrada do trovão",
      text: "\"O que nos dá a entender o seu pensamento, como também ao gado, acerca do temporal que sobe\" (Jó 36:33). É um dos versículos mais curiosos do Antigo Testamento: o gado é posto como destinatário de um aviso divino, a par do homem. Qualquer criador conhece o fenômeno — o rebanho inquieta-se, junta-se, procura o barranco e o abrigo antes de a primeira nuvem escurecer, e quem trabalha com animais confia mais neles do que no próprio olho. Eliú lê nisso um pensamento comunicado, e não um reflexo: o mesmo Deus que abre o ouvido do preso pela corda que o prende (Jó 36:10) dá notícia da tempestade ao boi. A Escritura volta a essa sabedoria dos bichos em Provérbios 30:24-28, em Jeremias 8:7 e na acusação de Isaías 1:3. Na cena, o gado inquieto no meio do quadro é o último objeto tranquilo antes de tudo se fechar: no versículo seguinte já é o coração de Eliú que treme e salta do seu lugar (Jó 37:1), e três capítulos depois o SENHOR responderá do redemoinho.",
    },
    rei: {
      title: "Os reis em cujo trono Deus assenta os justos para sempre",
      subtitle: "Jó 36:7 • o trono, na única promessa alta que Eliú faz",
      text: "\"Do justo não tira os seus olhos; antes estão com os reis no trono; ali os assenta para sempre, e assim são exaltados\" (Jó 36:7). É uma promessa de reversão social completa, e ecoa o cântico de Ana — \"levanta o pobre do pó, e desde o monturo exalta o necessitado, para o fazer assentar entre os príncipes\" (1Sm 2:8) — e o Salmo 113:7-8, que usa a mesma palavra: monturo. A ironia é violenta, porque o homem a quem Eliú diz isto está literalmente sentado num monturo, e a promessa parece-lhe uma provocação. O trono em cena não é o de Jó: é o dos reis a que a fala se refere, posto no quadro como imagem do que o discurso afirma. Lido do fim do livro para trás, o versículo não estava errado — Jó voltará à mesa, à casa e ao gado, e os seus dias serão \"velho e farto de dias\" (Jó 42:17). Estava errado no uso: Eliú faz da promessa uma condição, e Deus a cumprirá como puro dom, depois de Jó ter orado pelos amigos que o acusaram (Jó 42:10).",
    },
    mulherComum: {
      title: "A aflita a quem ele faz justiça, e a quem se revela aos ouvidos dentro da própria opressão",
      subtitle: "Jó 36:6,15 • a porta onde a causa dos que não têm ninguém é julgada",
      text: "\"Ele não preserva a vida do ímpio, e faz justiça aos aflitos\" (Jó 36:6). É o par que a Escritura repete de ponta a ponta: o ímpio não se sustenta, e o aflito é julgado com favor — \"Faz justiça ao órfão e à viúva\" (Dt 10:18), \"O Senhor faz justiça e juízo a todos os oprimidos\" (Sl 103:6). A figura em cena é a que estava por trás de todo o capítulo 31 de Jó: a mulher sem marido, cuja causa se decide à porta e cujo penhor se toma sem que ela tenha como reclamar. O que Eliú acrescenta é a promessa de 36:15, e ela é mais interior do que jurídica: \"Ao aflito livra da sua aflição, e na opressão se revela aos seus ouvidos\". Revela-se aos ouvidos, dentro da opressão — a mesma ideia do ouvido aberto pela corda (Jó 36:10) e dos salmos dados durante a noite (Jó 35:10). É a única coisa que Eliú diz que Jó, que clamou \"tu não me respondes\" (Jó 30:20), precisaria mesmo de ouvir; e é a única que se cumprirá, embora não pela boca dele.",
    },
    multidao: {
      title: "Os povos a quem ele julga por estas coisas e a quem dá mantimento em abundância",
      subtitle: "Jó 36:31 • a chuva sobre as nações, no mesmo gesto com que as julga",
      text: "\"Porque por estas coisas julga os povos e lhes dá mantimento em abundância\" (Jó 36:31). O versículo põe as duas coisas na mesma mão e no mesmo instrumento: a mesma nuvem que julga é a que alimenta. Chuva a tempo é colheita; chuva a destempo, ou a falta dela, é fome — e é por isso que a bênção e a maldição de Deuteronômio 28 se decidem sobre o céu (\"os teus céus, que estão sobre a cabeça, serão de bronze\", Dt 28:23). A multidão em cena é a humanidade inteira debaixo de um céu carregado, e não só Uz: Eliú saiu do caso particular de Jó para o governo do mundo. Jesus dirá a mesma coisa com a mesma imagem, e para provar que o amor de Deus não faz seleção: \"faz que o seu sol se levante sobre maus e bons, e a chuva desça sobre justos e injustos\" (Mt 5:45). E Paulo, em Listra, resumirá o argumento inteiro deste capítulo numa frase: \"não se deixou a si mesmo sem testemunho, beneficiando-vos lá do céu, dando-vos chuvas e tempos frutíferos\" (At 14:17).",
    },
    patriarca: {
      title: "Jó, a quem Eliú diz \"espera-me um pouco\", e os três amigos no monturo já debaixo da nuvem",
      subtitle: "Jó 36:2-4 • a cinzeira de Uz, no último trecho antes de o céu tomar a palavra",
      text: "\"Espera-me um pouco, e mostrar-te-ei que ainda há razões a favor de Deus\" (Jó 36:2). O moço pede mais tempo — o discurso já vai no quinto capítulo — e faz uma afirmação de si mesmo que é quase impertinente: \"Porque na verdade, as minhas palavras não serão falsas; contigo está um que tem perfeito conhecimento\" (Jó 36:4). Jó continua calado, de saco e cinza, sem um único balão desde 31:40; os três amigos continuam sentados, sem uma palavra desde 25:6. O que muda no palco não é o elenco, é o céu: `storm` sobe capítulo a capítulo, a chuva entra no discurso a partir de 36:27 e o gado começa a dar notícia do temporal em 36:33. Este é o último capítulo em que um homem explica Deus a Jó. Do capítulo 38 em diante ninguém mais explica nada: o SENHOR responde de um redemoinho, e a única fala humana que resta é a de Jó com a mão na boca (Jó 40:4) e o \"agora te vêem os meus olhos\" (Jó 42:5).",
    },
  },

  // ----------------------------------------------------------------- Jó 37
  37: {
    homem: {
      title: "Eliú com o coração a tremer e a saltar do seu lugar; e o homem que não estendeu os céus com ele, que nada pode pôr em boa ordem por causa das trevas e que não tem notícia do equilíbrio das grossas nuvens",
      subtitle: "Jó 37:1,16,18-19 • o trovão sobre Uz, no capítulo que é todo vestíbulo do redemoinho",
      text: "\"Sobre isto também treme o meu coração, e salta do seu lugar\" (Jó 37:1). O capítulo começa com o corpo do próprio orador a reagir, e daí em diante é tudo imagem: \"Atentamente ouvi a indignação da sua voz, e o sonido que sai da sua boca. Ele o envia por debaixo de todos os céus, e a sua luz até aos confins da terra. Depois disto ruge uma voz; ele troveja com a sua voz majestosa\" (Jó 37:2-4). O trovão como voz é o modo bíblico de dizer presença — é o que Israel ouviu no Sinai (Êx 19:16-19) e o que a multidão ouviu em João 12:29. E o homem, aqui, é sempre o que não sabe: \"Tens tu notícia do equilíbrio das grossas nuvens e das maravilhas daquele que é perfeito nos conhecimentos?\" (Jó 37:16); \"Ou estendeste com ele os céus, que estão firmes como espelho fundido?\" (Jó 37:18) — espelho fundido é bronze polido, uma abóbada dura e brilhante, e a comparação diz que o céu tem a solidez de uma peça de fundição. E o rendimento final: \"Ensina-nos o que lhe diremos: porque nós nada poderemos pôr em boa ordem, por causa das trevas\" (Jó 37:19). O moço que arrebentava como odre novo em 32:19 acaba dizendo que não sabe o que dizer — e o versículo seguinte já é o redemoinho.",
    },
    servo: {
      title: "O lavrador cuja mão foi selada pela neve, o que pisou as largas águas congeladas, o viajante apanhado pelo tufão da recâmara do sul e aquele cujas roupas aquecem quando do sul há calma",
      subtitle: "Jó 37:7-10,17,21 • o campo parado pelo inverno, quando Deus sela a mão de todo o homem",
      text: "\"Ele sela as mãos de todo o homem, para que conheçam todos os homens a sua obra\" (Jó 37:7). Selar a mão é parar o trabalho: quando a neve cai e o gelo fecha o chão, o lavrador não sai, e o ócio forçado tem, no argumento de Eliú, uma finalidade — que o homem, sem nada para fazer com as mãos, veja o que Deus faz. \"Porque à neve diz: Cai sobre a terra; como também à garoa e à sua forte chuva\" (Jó 37:6): à neve se DIZ, e ela cai; é a mesma linguagem de mando do Salmo 147:16-18. Depois o frio endurece a água: \"Pelo sopro de Deus se dá a geada, e as largas águas se congelam\" (Jó 37:10) — o rio que se atravessava a vau vira chão. Os ventos entram pelo par cardeal: \"Da recâmara do sul sai o tufão, e do norte o frio\" (Jó 37:9), e o sul volta como calor: \"Ou de como as tuas roupas aquecem, quando do sul há calma sobre a terra?\" (Jó 37:17). E, no fim, o sol depois do temporal, forte demais para se olhar: \"E agora não se pode olhar para o sol, que resplandece nas nuvens, quando o vento, tendo passado, o deixa limpo\" (Jó 37:21). Todos estes homens são figuras de uma coisa só: o trabalho humano interrompido, para que se veja de quem é o mundo.",
    },
    pastor: {
      title: "O pastor que viu as feras entrarem nos seus esconderijos, e o que recebeu a chuva por misericórdia",
      subtitle: "Jó 37:8,13 • a encosta em volta de Uz, entre a tempestade e a graça",
      text: "\"E as feras entram nos seus esconderijos e ficam nas suas cavernas\" (Jó 37:8). É o quadro que segue o selar das mãos do homem: quando o temporal sobe, o mundo inteiro se recolhe — o lavrador para, o bicho entra na caverna, e o pastor é o único que ainda está fora, contando o rebanho. Ele conhece o outro lado do versículo 8 também, porque a mesma escuridão que abriga a fera é a que faz o predador sair de noite: \"Ordenas a escuridão, e faz-se noite, na qual saem todos os animais da selva\" (Sl 104:20). E é ele quem entende o versículo mais teológico do capítulo, que dá três motivos alternativos para a mesma chuva: \"Seja que por vara, ou para a sua terra, ou por misericórdia as faz vir\" (Jó 37:13). Vara é castigo, \"para a sua terra\" é providência ordinária, misericórdia é dom — e nenhum dos três se distingue do outro pelo aspecto da nuvem. Quem vive de chuva sabe disso melhor do que quem discute sobre ela: a mesma água que salva a colheita de um afoga a de outro, e não há como ler no céu qual das três é.",
    },
    anciao: {
      title: "O homem de Uz que teme o Todo-Poderoso — e a quem Deus não respeita quando se julga sábio de coração",
      subtitle: "Jó 37:23-24 • o fecho do discurso de Eliú, e o último versículo humano antes do redemoinho",
      text: "\"Ao Todo-Poderoso não podemos alcançar; grande é em poder; porém a ninguém oprime em juízo e grandeza de justiça. Por isso o temem os homens; ele não respeita os que se julgam sábios de coração\" (Jó 37:23-24). São as últimas palavras que um homem diz neste livro antes de Deus falar, e são duas: Ele é inalcançável, e não oprime ninguém. O temor que daí decorre é o mesmo que Jó 28:28 tinha dado como definição de sabedoria — \"eis que o temor do Senhor é a sabedoria\" —, e a ferroada final é contra os que se acham sábios, o que apanha os três velhos sentados na roda e, se ele soubesse, também o próprio Eliú. O ancião em cena é o que sabe temer sem entender: a figura oposta à do sábio de coração. Vale reparar no que acontece na linha seguinte do texto: acabada a frase, \"Depois disto o SENHOR respondeu a Jó de um redemoinho\" (Jó 38:1). A tempestade que Eliú vinha descrevendo capítulo a capítulo já estava em cima deles, e o que ele tomava por assunto era a chegada.",
    },
    patriarca: {
      title: "Jó, a quem se manda parar e considerar as maravilhas de Deus, e os três amigos debaixo do temporal",
      subtitle: "Jó 37:14 • o monturo de Uz já dentro da tempestade, no beat que entrega o palco ao capítulo 38",
      text: "\"A isto, ó Jó, inclina os teus ouvidos; para, e considera as maravilhas de Deus\" (Jó 37:14). É a última coisa que se pede a Jó antes de o céu tomar a palavra, e é um mandado de duas sílabas no meio de um hino: PARA. Depois dele vêm sete perguntas seguidas — sabes tu como Deus as opera, tens tu notícia do equilíbrio das nuvens, estendeste com ele os céus — que são, em forma e em tom, o ensaio exato do interrogatório do redemoinho. Jó não responde a nenhuma; está calado desde 31:40 e continuará calado até 40:3. Os três amigos, calados desde 25:6, estão nas pedras molhadas do mesmo monturo, e a cena os põe debaixo de nuvens fechadas, com a torre da cidade a sumir no escuro. Jó continua de saco e cinza. É deste quadro, e não de outro, que o próximo versículo parte: \"Depois disto o SENHOR respondeu a Jó de um redemoinho\" (Jó 38:1).",
    },
  },

  // ----------------------------------------------------------------- Jó 38
  38: {
    patriarca: {
      title: "Jó, mandado cingir os lombos como homem — e os três amigos, testemunhas mudas da resposta que nenhum deles pediu",
      subtitle: "Jó 38:1-3 • o monturo debaixo do redemoinho, no capítulo em que o céu finalmente fala e não responde nada do que se perguntou",
      text: "\"Depois disto o SENHOR respondeu a Jó de um redemoinho, dizendo: Quem é este que escurece o conselho com palavras sem conhecimento? Agora cinge os teus lombos, como homem; e perguntar-te-ei, e tu me ensinarás\" (Jó 38:1-3). Trinta e cinco capítulos de homens a discutir, e a resposta vem — mas não é resposta a nenhuma das perguntas de Jó. Ninguém explica a Jó por que perdeu os filhos, ninguém menciona o capítulo 1, ninguém o acusa dos pecados que os amigos inventaram. O que vem é um interrogatório de setenta perguntas sobre a criação, e cingir os lombos é o gesto de quem arregaça a túnica no cinto para trabalhar ou lutar: prepara-te, que a partir de agora quem pergunta sou eu. Importa ver como a cena desenha isto: o SENHOR fala de um redemoinho, e o redemoinho é o MODO da voz, não um mensageiro — não há anjo, não há profeta, não há objeto que fale por Ele. Por isso o balão é dourado, centralizado e SEM figura, com a tempestade dominando o ambiente, e Jó fica pequeno na borda do quadro, curvado no pó, de saco e cinza. O centro do palco é sempre a criatura ou o elemento de que a pergunta fala: Deus não é desenhado uma única vez; o que se vê é o mundo que Ele está a citar como testemunha.",
    },
    homem: {
      title: "Os ímpios que a alva sacode das extremidades da terra, aquele de quem se desvia a sua luz e o braço altivo que se quebranta — e Eliú, calado, no primeiro versículo em que o céu fala",
      subtitle: "Jó 38:12-15 • a madrugada que pega na terra pelas pontas e a sacode como quem sacode um pano",
      text: "A imagem é doméstica e assustadora ao mesmo tempo: a madrugada pega a terra pelas bordas e sacode-a, e o que cai são os que trabalham de noite. \"Ou desde os teus dias deste ordem à madrugada, ou mostraste à alva o seu lugar; Para que pegasse nas extremidades da terra, e os ímpios fossem sacudidos dela\" (Jó 38:12-13). O ladrão, o adúltero e o assassino são gente do escuro — \"Assim como o olho do adúltero aguarda o crepúsculo, dizendo: Não me verá olho nenhum\" (Jó 24:15), como o próprio Jó tinha dito —, e a luz do dia é o que os desmancha: \"E dos ímpios se desvie a sua luz, e o braço altivo se quebrante\" (Jó 38:15). A luz do ímpio é o escuro; tirar-lha é acender o sol. Junto a isso vem a metáfora do selo: \"E se transformasse como o barro sob o selo, e se pusessem como vestidos\" (Jó 38:14) — a terra, que de noite não tinha relevo, recebe forma com a primeira luz como o barro que o carimbo imprime. E há, na borda do quadro, um homem que não é figura de imagem nenhuma: Eliú, que acabou de falar no versículo anterior e a quem nunca mais o livro dá uma palavra. Ele não é repreendido em 42:7 nem mandado oferecer holocausto — simplesmente cala-se quando o céu abre a boca.",
    },
  },

  // ----------------------------------------------------------------- Jó 39
  39: {
    rebanho: {
      title: "As cabras montesas que parem no rochedo, as cervas nas suas dores, e os filhos que enrijam, saem e nunca mais tornam para elas",
      subtitle: "Jó 39:1-4 • o rochedo alto, no primeiro quadro do bestiário do redemoinho",
      text: "\"Sabes tu o tempo em que as cabras montesas têm filhos, ou observastes as cervas quando dão suas crias? Contarás os meses que cumprem, ou sabes o tempo do seu parto?\" (Jó 39:1-2). A pergunta é escolhida com cuidado: o parto da cabra do rochedo acontece onde nenhum pastor chega, sem ninguém para contar os meses, sem parteira, sem testemunha — e acontece certo. \"Quando se encurvam, produzem seus filhos, e lançam de si as suas dores\" (Jó 39:3). Depois vem o desfecho, que é o que dá a este quadro o seu tom: \"Seus filhos enrijam, crescem com o trigo; saem, e nunca mais tornam para elas\" (Jó 39:4). Os filhotes crescem e vão-se embora para sempre, e nem por isso a espécie falha. Todo o bestiário de Jó 39 é feito de animais que não servem para nada a ninguém — não se ordenham, não se aram, não se montam, não se contam no inventário de casa — e a força do argumento está exatamente aí: Deus governa e sustenta um mundo inteiro que não passa pelas mãos do homem, e do qual o homem nem sabe as datas. Diante de um homem que perdeu dez filhos num dia, a escolha do parto como primeira pergunta não é acidental.",
    },
    homem: {
      title: "O condutor a quem o jumento montês não ouve, o lavrador que quis amarrar o boi selvagem ao arado, o caminhante cujo pé pode pisar os ovos da avestruz, e o armado ao encontro de quem o cavalo sai",
      subtitle: "Jó 39:7,9-12,15,21-25 • os homens deste capítulo, que aparecem todos como aquilo que o bicho dispensa",
      text: "Nenhum homem aqui está em cena por si: cada um está para mostrar aquilo de que a criatura não precisa. O condutor, primeiro, com a corda e a voz: o jumento montês \"Ri-se do ruído da cidade; não ouve os muitos gritos do condutor\" (Jó 39:7). O lavrador, depois, com o arado: \"Ou, querer-te-á servir o boi selvagem? Ou ficará no teu curral? Ou com corda amarrarás, no arado, ao boi selvagem?… Ou fiarás dele que te torne o que semeaste e o recolha na tua eira?\" (Jó 39:9-12) — o mesmo bicho que domesticado é a base da economia inteira, selvagem não faz nada disso e continua vivo. O caminhante entra por descuido: a avestruz \"deixa os seus ovos na terra, e os aquenta no pó, E se esquece de que algum pé os pode pisar, ou que os animais do campo os podem calcar\" (Jó 39:14-15) — e o veredito é o mais desconcertante do capítulo, \"Porque Deus a privou de sabedoria, e não lhe deu entendimento\" (Jó 39:17), Deus assumindo a autoria de uma criatura tola, que ainda assim, \"a seu tempo se levanta ao alto; ri-se do cavalo, e do que vai montado nele\" (Jó 39:18). E, por fim, o soldado, que é o único homem deste capítulo que o bicho procura em vez de evitar: o cavalo \"Escarva a terra, e folga na sua força, e sai ao encontro dos armados. Ri-se do temor, e não se espanta, e não torna atrás por causa da espada\" (Jó 39:21-22).",
    },
    cavaleiro: {
      title: "O cavalo a quem o SENHOR deu a força e revestiu o pescoço de crinas — que ao soar das buzinas diz \"Eia!\" — e o cavalo com o seu montado, de que a avestruz se ri",
      subtitle: "Jó 39:18-25 • o vale onde ele escarva a terra, no quadro mais eufórico de todo o livro",
      text: "\"Ou darás tu força ao cavalo, ou revestirás o seu pescoço com crinas? Ou espantá-lo-ás, como ao gafanhoto? Terrível é o fogoso respirar das suas ventas\" (Jó 39:19-20). O retrato do cavalo de guerra é o trecho mais elétrico do livro, e é todo feito de som e de fôlego: a terra escavada, a aljava que range, \"o ferro flamante da lança e do dardo\" (Jó 39:23), e o versículo que ninguém esquece — \"Ao soar das buzinas diz: Eia! E cheira de longe a guerra, e o trovão dos capitàes, e o alarido\" (Jó 39:25). O cavalo é a única criatura do bestiário que serve ao homem, e mesmo essa não é obra do homem: a coragem que o faz não recuar diante da espada não foi treinada, foi dada. E o capítulo já o tinha humilhado antes, de propósito, pela boca do bicho mais tolo de todos: a avestruz, que Deus privou de sabedoria, \"a seu tempo se levanta ao alto; ri-se do cavalo, e do que vai montado nele\" (Jó 39:18) — em corrida limpa ela deixa os dois para trás. É a Escritura a dizer, de dentro de um poema, o que dirá em Provérbios sem rodeio: \"Prepara-se o cavalo para o dia da batalha, porém do Senhor vem a vitória\" (Pv 21:31).",
    },
    multidao: {
      title: "O povo do mercado, cujo alarido o jumento montês despreza",
      subtitle: "Jó 39:7 • a praça da cidade vista de longe, do alto da região montanhosa",
      text: "\"Ri-se do ruído da cidade; não ouve os muitos gritos do condutor\" (Jó 39:7). A cidade entra neste capítulo pelo ouvido, e entra como aquilo de que se pode rir. O jumento doméstico é o animal mais amarrado que existe naquele mundo — mó, carga, feira, estrada —, e o texto põe ao lado dele o mesmo bicho solto: \"Quem despediu livre o jumento montês, e quem soltou as prisões ao jumento bravo, Ao qual dei o ermo por casa, e a terra salgada por morada?\" (Jó 39:5-6). Quem lhe deu o ermo por casa foi Deus, e a liberdade dele é dádiva e não fuga. Daí a piada do versículo 7: do alto da região montanhosa, que \"é o seu pasto\" (Jó 39:8), o barulho do mercado — o pregão, o regateio, os gritos do arreador — é só um zumbido lá em baixo. A multidão em cena é a banca cheia e a praça cheia, tudo o que uma cidade tem de importante, reduzido, do ponto de vista do animal e da pergunta, a ruído. É o mesmo movimento de toda a resposta do redemoinho: tirar o homem do centro do quadro sem lhe tirar o valor.",
    },
    patriarca: {
      title: "Jó ouvindo o bestiário, pequeno na borda do quadro, sem responder uma palavra",
      subtitle: "Jó 39:1-30 • o monturo debaixo do redemoinho, num capítulo inteiro de perguntas sem resposta",
      text: "Em Jó 39 o interrogado não diz nada, e é preciso ver que a cena o desenha assim de propósito: Jó pequeno, na borda, curvado no pó, de saco e cinza, enquanto o centro do palco é o bicho de cada versículo. São trinta versículos e nove criaturas — a cabra montesa, a cerva, o jumento montês, o boi selvagem, a avestruz, o cavalo, o gafanhoto, o gavião e a águia —, e nenhuma delas tem qualquer utilidade para a economia doméstica de um homem rico de Uz. É esse o argumento: o mundo é maior do que a contabilidade de quem o habita, e é governado numa escala que não passa pela justiça retributiva que os cinco homens vinham discutindo. O capítulo fecha na águia, e o fecho é sombrio de propósito: \"Nas penhas mora e habita; no cume das penhas, e nos lugares seguros. Dali descobre a presa; seus olhos a avistam de longe. E seus filhos chupam o sangue, e onde há mortos, ali está ela\" (Jó 39:28-30). Deus alimenta os filhotes da águia com o que a morte deixa no campo, e não pede desculpa por isso. Jó responderá dois versículos depois do fim deste capítulo, e a resposta será a mão na boca (Jó 40:4).",
    },
  },

  // ----------------------------------------------------------------- Jó 40
  40: {
    patriarca: {
      title: "Jó com a mão à boca — \"Eis que sou vil; que te responderia eu?\" — e os três amigos que assistem",
      subtitle: "Jó 40:3-5 • o monturo debaixo do redemoinho, na primeira resposta de Jó em nove capítulos",
      text: "\"Então Jó respondeu ao Senhor, dizendo: Eis que sou vil; que te responderia eu? A minha mão ponho à boca. Uma vez tenho falado, e não replicarei; ou ainda duas vezes, porém não prosseguirei\" (Jó 40:3-5). É o mesmo gesto que os príncipes de Uz faziam diante dele nos seus dias bons — \"Os príncipes continham as suas palavras, e punham a mão sobre a sua boca\" (Jó 29:9) —, e agora é ele quem o faz. Mas ainda não é o arrependimento do capítulo 42: aqui Jó só se cala, e por isso o SENHOR não aceita a rendição e recomeça: \"Então o Senhor respondeu a Jó de um redemoinho, dizendo: Cinge agora os teus lombos como homem; eu te perguntarei, e tu me explicarás\" (Jó 40:6-7). A segunda rodada muda de assunto: já não é sobre poder, é sobre juízo — \"Porventura também tornarás tu vão o meu juízo, ou tu me condenarás, para te justificares?\" (Jó 40:8). E o convite que se segue é ironia pura, e é a chave do capítulo: se és capaz de governar o mundo, então governa — \"Orna-te, pois, de excelência e alteza; e veste-te de majestade e de glória\" (Jó 40:10). Jó, de saco e cinza, está a ser convidado a vestir a roupa de Deus.",
    },
    homem: {
      title: "O soberbo que Jó teria de abater, o ímpio atropelado no seu lugar, e o caçador que quis furar o nariz do beemote com laços",
      subtitle: "Jó 40:11-13,24 • o desafio irônico do redemoinho e o esconderijo das canas e da lama",
      text: "\"Derrama os furores da tua ira, e atenta para todo o soberbo, e abate-o. Olha para todo o soberbo, e humilha-o, e atropela os ímpios no seu lugar. Esconde-os juntamente no pó; ata-lhes os rostos em oculto\" (Jó 40:11-13). É um desafio, e é o único lugar da Bíblia em que Deus manda um homem tentar fazer o Seu trabalho: julgar o mundo. A condição vem em seguida, e é impiedosa: \"Então também eu a ti confessarei que a tua mão direita te poderá salvar\" (Jó 40:14). Jó tinha reclamado do governo do mundo; o redemoinho passa-lhe o governo e espera. Depois, para mostrar de que tamanho é a menor das criaturas que ele teria de manejar, entra o beemote — que come erva como o boi, tem a força nos lombos, move a cauda como cedro e cujos ossos são \"como tubos de bronze\" (Jó 40:18) —, e o capítulo termina numa pergunta de caçador: \"Podê-lo-iam porventura caçar à vista de seus olhos, ou com laços lhe furar o nariz?\" (Jó 40:24). Furar o nariz e passar corda é o que se faz ao boi manso. O homem em cena é quem tentou: um caçador com laços na mão diante de um bicho que se deita na lama sem pressa, porque \"Eis que um rio transborda, e ele não se apressa, confiando ainda que o Jordão se levante até à sua boca\" (Jó 40:23).",
    },
    rebanho: {
      title: "Os animais do campo que folgam nos pastos que os montes produzem para o beemote",
      subtitle: "Jó 40:20 • a encosta e o ribeiro dos salgueiros, onde o maior dos bichos come erva",
      text: "\"Em verdade os montes lhe produzem pastos, onde todos os animais do campo folgam\" (Jó 40:20). É um detalhe que o poema podia ter dispensado e não dispensou: onde pasta a criatura mais poderosa da terra firme, pastam também todos os outros bichos, à vontade. O beemote come erva como o boi (Jó 40:15), deita-se \"debaixo das árvores sombrias, no esconderijo das canas e da lama\" (Jó 40:21), e não persegue ninguém — a sua força, descrita com tubos de bronze e barras de ferro, não se usa contra o rebanho ao lado. O texto chama-o de \"obra-prima dos caminhos de Deus\" (Jó 40:19), e o quadro que monta é de convivência e não de terror. Vale ler ao lado o Salmo 104, que é o irmão gêmeo destes capítulos e que descreve o mesmo mundo: \"Faz crescer a erva para o gado, e a verdura para o serviço do homem\" (Sl 104:14) e \"Os altos montes são para as cabras monteses\" (Sl 104:18). É a mesma tese que a cena mostra: o mundo é maior do que o homem, é povoado de criaturas que não lhe prestam serviço nenhum, e é bom.",
    },
  },

  // ----------------------------------------------------------------- Jó 41
  41: {
    homem: {
      title: "O pescador que quis tirar o leviatã com anzol, os companheiros que fariam dele um banquete, os negociantes que o repartiriam, o frecheiro cuja seta não o faz fugir e os valentes que tremem quando ele se levanta",
      subtitle: "Jó 41:1-9,25-29 • a praia e a barca, diante de trinta e quatro versículos de um só animal",
      text: "O capítulo inteiro é sobre um bicho, e todos os homens que aparecem nele estão a perder. Primeiro o pescador: \"Poderás tirar com anzol o leviatã, ou ligarás a sua língua com uma corda? Podes pôr um anzol no seu nariz, ou com um gancho furar a sua queixada?\" (Jó 41:1-2), e mais adiante, \"Encherás a sua pele de ganchos, ou a sua cabeça com arpões de pescadores?\" (Jó 41:7). Depois a sociedade comercial que já contava com o lucro: \"Os teus companheiros farão dele um banquete, ou o repartirão entre os negociantes?\" (Jó 41:6) — o arpoador, o cozinheiro e o comprador, todos ridicularizados na mesma linha. Depois o soldado: \"Se alguém lhe tocar com a espada, essa não poderá penetrar, nem lança, dardo ou flecha… Ele considera o ferro como palha, e o cobre como pau podre. A seta o não fará fugir; as pedras das fundas se lhe tornam em restolho\" (Jó 41:26-28). E, por último, os valentes: \"Levantando-se ele, tremem os valentes; em razão dos seus abalos se purificam\" (Jó 41:25). O aviso, no meio, vale por todo o capítulo: \"Põe a tua mão sobre ele, lembra-te da peleja, e nunca mais tal intentarás\" (Jó 41:8).",
    },
    mulherComum: {
      title: "A menina para quem ninguém prende o leviatã — \"Brincarás com ele, como se fora um passarinho\"",
      subtitle: "Jó 41:5 • a pergunta doméstica no meio do poema mais terrível do livro",
      text: "\"Brincarás com ele, como se fora um passarinho, ou o prenderás para tuas meninas?\" (Jó 41:5). No meio de trinta e quatro versículos de escamas seladas, tochas na boca e mar fervido como panela, entra de repente uma cena de casa: o pai que amarra um passarinho por uma linha para as filhas brincarem. Era coisa comum — a mesma imagem aparece no mundo greco-latino, e o riso do versículo está em pôr o monstro no lugar do pássaro. A ironia é mais afiada do que parece, porque o homem a quem a pergunta é feita teve três filhas, perdeu-as no capítulo 1 e terá outras três no capítulo 42, cada uma com nome dado e herança entre os irmãos (Jó 42:14-15). O redemoinho não está a zombar dele: está a mostrar-lhe a distância entre o que uma criatura de Deus é e o que o homem consegue domesticar. E a mesma criatura reaparece noutro lugar da Escritura brincando ela própria, sem perigo nenhum, dentro do mar que Deus fez: \"Ali andam os navios; e o leviatã que formaste para nele folgar\" (Sl 104:26). Isaías, do outro lado, promete o dia em que a espada dura do SENHOR castigará \"o leviatã, serpente veloz\" (Is 27:1).",
    },
    patriarca: {
      title: "Jó calado diante do leviatã — rei sobre todos os filhos da soberba",
      subtitle: "Jó 41:10-11,34 • o último quadro do redemoinho, antes de Jó abrir a boca pela última vez",
      text: "No meio do poema do leviatã há dois versículos que não falam do bicho, e são o eixo do livro inteiro: \"Ninguém há tão atrevido, que a despertá-lo se atreva; quem, pois, é aquele que ousa erguer-se diante de mim? Quem primeiro me deu, para que eu haja de retribuir-lhe? Pois o que está debaixo de todos os céus é meu\" (Jó 41:10-11). Se ninguém desperta o crocodilo, quem se levanta diante de Quem o fez — e, mais fundo, ninguém adiantou nada a Deus para depois lhe cobrar. É a resposta última à contabilidade que os cinco homens vinham fazendo, e é o versículo que Paulo cita para fechar Romanos 11: \"Ou quem lhe deu primeiro a ele, para que lhe seja recompensado?\" (Rm 11:35). O fecho do capítulo é a coroação do animal: \"Na terra não há coisa que se lhe possa comparar, pois foi feito para estar sem pavor. Ele vê tudo que é alto; é rei sobre todos os filhos da soberba\" (Jó 41:33-34). Jó está na borda do quadro, pequeno, de saco e cinza, e não diz nada — a próxima palavra dele é a última do debate: \"Com o ouvir dos meus ouvidos ouvi, mas agora te vêem os meus olhos\" (Jó 42:5).",
    },
  },

  // ----------------------------------------------------------------- Jó 42
  42: {
    patriarca: {
      title: "Jó, que se abomina e se arrepende no pó e na cinza, e ora pelos amigos que o acusaram — e Elifaz, Bildade e Zofar, que trazem sete bezerros e sete carneiros",
      subtitle: "Jó 42:5-10 • o monturo, no versículo em que o cativeiro se vira",
      text: "\"Com o ouvir dos meus ouvidos ouvi, mas agora te vêem os meus olhos. Por isso me abomino e me arrependo no pó e na cinza\" (Jó 42:5-6). Não é a confissão de um crime — o SENHOR dirá dois versículos adiante que Jó falou dele \"o que era reto\" —, é o que acontece a um homem quando o que ele sabia de ouvir vira coisa vista; a mesma reação de Isaías no templo (\"Ai de mim! pois estou perdido\", Is 6:5) e de Pedro na barca (\"Senhor, ausenta-te de mim, que sou um homem pecador\", Lc 5:8). Depois o céu vira-se para os consoladores: \"A minha ira se acendeu contra ti, e contra os teus dois amigos, porque não falastes de mim o que era reto, como o meu servo Jó\" (Jó 42:7). Três homens que passaram trinta capítulos a defender Deus contra Jó são repreendidos por Deus a favor de Jó, e a sentença é humilhante e curativa ao mesmo tempo: \"Tomai, pois, sete bezerros e sete carneiros, e ide ao meu servo Jó… e o meu servo Jó orará por vós\" (Jó 42:8). O réu vira sacerdote dos seus acusadores. E o versículo dobradiça do livro inteiro põe as duas coisas na mesma linha: \"E o Senhor virou o cativeiro de Jó, quando orava pelos seus amigos\" (Jó 42:10). Não quando entendeu, não quando foi indenizado: quando orou por eles. É daqui em diante que a `palette` do saco sai do palco — o homem volta ao seu traje, à sua casa, à sua mesa e ao seu gado.",
    },
    mulherComum: {
      title: "Jemima, Quezia e Quéren-Hapuque, as três filhas do último estado de Jó, a quem seu pai deu herança entre seus irmãos — e as irmãs que vieram comer pão com ele",
      subtitle: "Jó 42:11,13-15 • a casa refeita, e o versículo mais extraordinário do fim do livro",
      text: "\"Também teve sete filhos e três filhas. E chamou o nome da primeira Jemima, e o nome da segunda Quezia, e o nome da terceira Quéren-Hapuque\" (Jó 42:13-14). Os sete filhos não são nomeados; as três filhas são — e os nomes são todos de beleza e de perfume: Jemima é \"pomba\" ou \"dia claro\"; Quezia é a cássia, a casca aromática usada no óleo santo (Êx 30:24); Quéren-Hapuque é literalmente \"frasco de pintura de olhos\", o pote do antimônio com que se realçavam as pálpebras. Um homem que passou o livro inteiro coberto de cinza chama à filha \"caixinha de maquiagem\". \"E em toda a terra não se acharam mulheres tão formosas como as filhas de Jó; e seu pai lhes deu herança entre seus irmãos\" (Jó 42:15) — e esta última linha é jurídica, não sentimental. Filha, naquele direito, herdava apenas quando não havia filho homem, e mesmo assim por exceção conquistada a duras penas pelas filhas de Zelofeade (Nm 27:1-11; Js 17:3-6). Jó tem sete filhos varões vivos e mesmo assim dá herança às três. É o mesmo homem que jurou em 31:13 que não desprezou o direito do servo nem da serva, porque \"Aquele que me formou no ventre não o fez também a ele?\". A outra mulher da cena é a que voltou: \"Então vieram a ele todos os seus irmãos, e todas as suas irmãs… e comeram com ele pão em sua casa, e se condoeram dele, e o consolaram\" (Jó 42:11) — o consolo que os amigos não souberam dar em trinta capítulos, a irmã dá numa refeição.",
    },
    homem: {
      title: "Os que dantes o conheceram e voltaram, cada um com uma peça de dinheiro e um pendente de ouro — e os sete filhos do último estado de Jó",
      subtitle: "Jó 42:11,13 • a casa de Jó cheia outra vez, e a mesa em que comeram pão com ele",
      text: "\"Então vieram a ele todos os seus irmãos, e todas as suas irmãs, e todos quantos dantes o conheceram, e comeram com ele pão em sua casa, e se condoeram dele, e o consolaram acerca de todo o mal que o Senhor lhe havia enviado; e cada um deles lhe deu uma peça de dinheiro, e um pendente de ouro\" (Jó 42:11). Vale ler devagar quem são estes homens: são exatamente os que sumiram. Jó tinha-os descrito no capítulo 19 — \"Os meus parentes me deixaram, e os meus conhecidos se esqueceram de mim\" (Jó 19:14) — e no 30, quando a cidade inteira o fez provérbio. Agora estão à mesa, e o texto não os censura nem os elogia: só regista que vieram, comeram, se condoeram e deram. A \"peça de dinheiro\" traduz uma unidade antiga que aparece também em Gênesis 33:19 e Josué 24:32, nas duas compras de terra dos patriarcas — é dinheiro de escritura, não moeda miúda —, e o pendente de ouro é a argola de nariz ou de orelha, jóia de valor real. Aquilo é o começo do capital do segundo estado de Jó. E há os sete filhos novos: \"Também teve sete filhos e três filhas\" (Jó 42:13) — o mesmo número do capítulo 1, e a nota mais delicada de todo o epílogo, porque o gado veio em dobro e os filhos não. Dez filhos perdidos não se substituem por vinte; os que morreram continuam sendo dele.",
    },
    servo: {
      title: "O filho mais moço da casa refeita e o neto de Jó da quarta geração",
      subtitle: "Jó 42:16 • o pátio da casa em que ele viveu cento e quarenta anos depois de tudo",
      text: "\"E depois disto viveu Jó cento e quarenta anos; e viu a seus filhos, e aos filhos de seus filhos, até à quarta geração\" (Jó 42:16). Estes são os meninos que correm pela casa no último quadro do livro: filhos e netos e bisnetos, gente que nasceu depois do monturo e que só conhece a história de ouvir contar. Ver a quarta geração é, na Escritura, a fórmula da vida completa — foi o que Deus prometeu a Jeú (2Rs 10:30) e é o que o Salmo 128:6 chama de bênção, \"E verás os filhos de teus filhos\". Para um homem que enterrou dez filhos num único dia, é uma frase que custa a ler sem parar: a casa que o vento derrubou foi refeita, e refeita até quatro andares de gente. O epílogo não explica nada do que aconteceu — não conta a Jó o que se passou no capítulo 1, não lhe entrega uma teoria do sofrimento e não desfaz a perda. Dá-lhe tempo, e dá-lhe gente. E a última linha é a mais serena do livro: \"Então morreu Jó, velho e farto de dias\" (Jó 42:17) — farto, saciado, como quem se levanta da mesa por já ter comido bastante, e é assim que a Bíblia despede Abraão (Gn 25:8) e Isaque (Gn 35:29).",
    },
    multidao: {
      title: "Os irmãos e as irmãs de Jó e todos quantos dantes o conheceram, comendo pão com ele em sua casa",
      subtitle: "Jó 42:11 • a mesa cheia, no primeiro quadro alegre do livro desde o capítulo 1",
      text: "\"Então vieram a ele todos os seus irmãos, e todas as suas irmãs, e todos quantos dantes o conheceram, e comeram com ele pão em sua casa\" (Jó 42:11). O livro começa numa festa de família — os sete filhos que \"iam seus filhos à casa uns dos outros e faziam banquetes cada um por sua vez\" e mandavam chamar as três irmãs para comer e beber com eles (Jó 1:4) — e a festa acaba no versículo 19 do mesmo capítulo, com o vento do deserto e os quatro cantos da casa. Trinta e nove capítulos depois, a mesa volta a estar posta. Comer pão em casa de alguém, no Oriente, é o gesto máximo de reconciliação e de pertença: quem come contigo já não te acusa. E o que faltava a Jó não era dinheiro — era exatamente isto, gente à mesa; ele tinha dito no capítulo 19 que até a sua respiração era estranha à mulher e que os meninos da rua zombavam dele (Jó 19:17-18). Note-se também o que o texto diz que eles fizeram: \"se condoeram dele, e o consolaram acerca de todo o mal que o Senhor lhe havia enviado\". É palavra por palavra o que os três amigos tinham vindo fazer em 2:11 e não conseguiram. O consolo, no fim, veio de gente comum que não trouxe teoria nenhuma — trouxe pão, uma peça de dinheiro e um pendente de ouro.",
    },
    rebanho: {
      title: "As catorze mil ovelhas, os seis mil camelos, as mil juntas de bois e as mil jumentas do último estado de Jó — e os sete bezerros e sete carneiros do holocausto dos amigos",
      subtitle: "Jó 42:8,12 • o pasto refeito, com exatamente o dobro do capítulo 1",
      text: "\"E assim abençoou o Senhor o último estado de Jó, mais do que o primeiro; pois teve catorze mil ovelhas, e seis mil camelos, e mil juntas de bois, e mil jumentas\" (Jó 42:12). Conferindo com o inventário de abertura — \"sete mil ovelhas, três mil camelos, quinhentas juntas de bois e quinhentas jumentas\" (Jó 1:3) — vê-se que é o dobro exato de cada linha, e o dobro é, na lei de Israel, o valor da restituição que o ladrão devia pagar (Êx 22:4). O rebanho de 42:12 é uma sentença de tribunal escrita em ovelhas. Antes dele há outro grupo de animais em cena, e esse é o mais importante dos dois: \"Tomai, pois, sete bezerros e sete carneiros, e ide ao meu servo Jó, e oferecei holocaustos por vós\" (Jó 42:8). Catorze cabeças, um sacrifício de peso, levadas pelos três velhos até ao monturo do homem que eles acusaram — e não bastavam sem a oração dele: \"e o meu servo Jó orará por vós; porque deveras a ele aceitarei\". Na cena, os quatro grupos do pasto contam-se em rebanhos separados, e não em uma multidão só: catorze mil ovelhas de um lado, os camelos e as jumentas de outro, as juntas de bois no seu curral. Cada marca de `rebanho` é um grupo, não um bicho.",
    },
  },
};
