// Fichas ESPECÍFICAS por (capítulo → papel) de JÓ 1–14.
// Este bloco é de um livro que não se parece com nenhum outro do palco. Só os
// dois primeiros capítulos são narrativa — Uz, o maior de todos os do oriente,
// os banquetes dos filhos e os holocaustos da madrugada, a corte celestial com
// Satanás entre os filhos de Deus, as quatro notícias que chegam uma por cima
// da outra, os tumores desde a planta do pé até ao alto da cabeça, o caco de
// telha na cinza e os três amigos calados sete dias e sete noites. Do capítulo
// 3 em diante o palco quase nunca mostra os quatro homens assentados na cinza:
// mostra O QUE A FALA VÊ. Cada versículo de discurso virou o quadro da sua
// própria imagem — o leão que perece sem presa, o espírito que passa na noite,
// a fagulha que sobe, o ribeiro que seca e as caravanas de Temá envergonhadas,
// a lançadeira do tecelão, o papiro no lodo, a teia de aranha, a Ursa e o
// Órion, o leite que se coalha, a árvore cortada que ao cheiro das águas torna
// a brotar e as águas que gastam as pedras.
//
// Por isso a regra destas fichas é outra: o figurante de um beat de discurso
// NÃO é "um homem do povo" — é a FIGURA DA IMAGEM daquele versículo. O
// jornaleiro que espera a sua paga, o preso que não ouve a voz do exator, o rei
// que edificou para si casas em lugares assolados, o insensato cuja habitação
// Elifaz amaldiçoou, o correio que corre mais que os dias de Jó. A ficha diz de
// que imagem ele é, QUEM a disse e o que ela quer dizer dentro do argumento —
// porque em Jó o argumento é a ação.
//
// PAPEL `patriarca`: não tem entrada aqui em nenhum capítulo, de propósito. Nos
// catorze capítulos ele resolve sempre para `jo`, `elifaz-o-temanita`,
// `bildade-o-suita` ou `zofar-o-naamatita`, que têm verbete próprio em
// CHAR_INFO e vencem esta camada. O mesmo vale para `mulher-de-jo` (1:20-21;
// 2:7-10) e para os quatro mensageiros de 1:14-19.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_01_14: Record<number, Record<string, StageInfo>> = {
  // ------------------------------------------------------------------ Jó 1
  1: {
    homem: {
      title: "Os sete filhos de Jó nos banquetes por turno, e os sabeus e os caldeus que caíram sobre o seu gado",
      subtitle: "Jó 1:4,13,15,17-19 • a casa do irmão primogênito e as duas hostes que vieram de rumos opostos",
      text: "\"E iam seus filhos à casa uns dos outros e faziam banquetes cada um por sua vez; e mandavam convidar as suas três irmãs a comerem e beberem com eles\" (Jó 1:4). São sete rapazes com casa própria e um calendário de festa que gira entre eles; o mais velho é o anfitrião do último dia — \"em casa de seu irmão primogênito\" (1:18) — e é sobre esse telhado que o vento dará nos quatro cantos. Nada no texto os acusa: o pai apenas temia, e por isso \"se levantava de madrugada, e oferecia holocaustos segundo o número de todos eles\" (1:5). Os outros homens desta cena vêm de fora e dos dois extremos do mundo conhecido de Uz. Do sul, os sabeus, gente das caravanas de ouro e especiarias da Arábia (cf. 1Rs 10:1-2), que \"deram sobre eles... e aos servos feriram ao fio da espada\" (1:15). Do norte, os caldeus da Mesopotâmia, a terra de onde saíra Abraão (Gn 11:28) e cujo nome daria depois o império \"amarga e impetuosa\" de Habacuque (Hc 1:6): estes não vieram em bando, vieram em formação — \"Ordenando os caldeus três tropas, deram sobre os camelos\" (1:17). Entre o banquete e o saque não há capítulo nenhum: é o mesmo dia.",
    },
    mulherComum: {
      title: "As três filhas de Jó, convidadas a comer e beber com os irmãos",
      subtitle: "Jó 1:2,4,13,18-19 • as três que morreram na casa do primogênito",
      text: "\"E nasceram-lhe sete filhos e três filhas\" (Jó 1:2). O detalhe que a Escritura guarda delas é pequeno e diz muito: os irmãos \"mandavam convidar as suas três irmãs a comerem e beberem com eles\" (1:4) — numa casa do oriente antigo, mulheres chamadas por escrito a cada rodada de banquete são gente de posição, e a família de Jó era unida o bastante para não deixá-las de fora. Estão à mesa quando a notícia chega ao pai: \"Estando teus filhos e tuas filhas comendo e bebendo vinho, em casa de seu irmão primogênito\" (1:18), e morrem debaixo do mesmo teto que caiu sobre os jovens (1:19). O pai as santificava junto com os irmãos, sem distinção, nos holocaustos da madrugada (1:5). No fim do livro, quando \"o Senhor virou o cativeiro de Jó\" (42:10), voltam a nascer três — e desta vez com nome: Jemima, Quezia e Quéren-Hapuque, \"E em toda a terra não se acharam mulheres tão formosas como as filhas de Jó; e seu pai lhes deu herança entre seus irmãos\" (42:14-15).",
    },
    pastor: {
      title: "Os pastores das sete mil ovelhas — os que dormiam no campo quando o fogo caiu do céu",
      subtitle: "Jó 1:3,16 • os servos queimados com o rebanho, e o único que escapou",
      text: "\"E o seu gado era de sete mil ovelhas\" (Jó 1:3), e sete mil cabeças não se guardam com dois homens: é gente espalhada por vários apriscos, dormindo ao relento com o rebanho, como os pastores de Belém que \"guardavam, durante as vigílias da noite, o seu rebanho\" (Lc 2:8). São eles a segunda notícia do dia: \"Fogo de Deus caiu do céu, e queimou as ovelhas e os servos, e os consumiu, e só eu escapei para trazer-te a nova\" (1:16). Note-se a ordem em que o mensageiro conta — primeiro as ovelhas, depois os servos: o inventário e os homens caem na mesma frase, e é o próprio sobrevivente quem batiza o desastre de FOGO DE DEUS, sem saber o que o leitor sabe desde 1:12. O pastor que aparece na cena é, portanto, de duas espécies ao mesmo tempo: o que ficou lá, consumido com o gado que guardava, e o que veio pela estrada com a roupa cheirando a queimado dar a notícia a um homem que já estava ouvindo outra.",
    },
    rebanho: {
      title: "As sete mil ovelhas, os três mil camelos e as quinhentas juntas de bois — a fazenda do maior de todos os do oriente",
      subtitle: "Jó 1:3,10,14-17 • o gado que a sebe cercava e que se perdeu num dia",
      text: "\"E o seu gado era de sete mil ovelhas, três mil camelos, quinhentas juntas de bois e quinhentas jumentas; eram também muitíssimos os servos a seu serviço, de maneira que este homem era maior do que todos os do oriente\" (Jó 1:3). O texto conta a grandeza de Jó em bichos, e não em prata: as ovelhas são a lã e a carne, os camelos são o comércio de longa distância, as juntas de bois são a lavoura — \"Os bois lavravam, e as jumentas pastavam junto a eles\" (1:14) — e as jumentas são o transporte de casa. É exatamente esse gado que o adversário aponta no céu como prova de que a piedade de Jó tem preço: \"Porventura tu não cercaste de sebe, a ele, e a sua casa, e a tudo quanto tem? A obra de suas mãos abençoaste e o seu gado se tem aumentado na terra\" (1:10). Aberta a sebe, os quatro rebanhos somem em quatro frases: os bois e as jumentas pelos sabeus (1:15), as ovelhas pelo fogo (1:16), os camelos pelos caldeus (1:17). No fim, o mesmo Deus lhe devolve tudo em dobro — \"catorze mil ovelhas, e seis mil camelos, e mil juntas de bois, e mil jumentas\" (42:12).",
    },
    servo: {
      title: "Os muitíssimos servos de Jó: o mordomo da casa, o boiadeiro do sulco, o cameleiro, o que servia o vinho do banquete, o que ajudava no holocausto da madrugada e o que ficava ao portão de Uz",
      subtitle: "Jó 1:3,5,14-17 • a criadagem que fazia daquela casa a maior do oriente — e a que morreu ao fio da espada",
      text: "\"Eram também muitíssimos os servos a seu serviço\" (Jó 1:3) — e é por eles que o texto mede a casa antes de medi-la pelo gado. Cada rebanho tem a sua gente: o boiadeiro atrás das quinhentas juntas quando \"os bois lavravam\" (1:14), o cameleiro do acampamento dos três mil camelos, o pastor das sete mil ovelhas, e o mordomo que responde pela porta por onde entram, um atrás do outro, os quatro mensageiros. Havia ainda o serviço da casa: o que servia o vinho no banquete que girava entre os sete irmãos (1:4) e o que preparava o fogo dos holocaustos que Jó oferecia de madrugada \"segundo o número de todos eles\" (1:5) — dez animais por rodada, uma vida inteira de manhãs, \"assim fazia Jó continuamente\". A dureza do capítulo é que este pessoal não é cenário: duas das quatro notícias dizem que \"aos servos feriram ao fio da espada\" (1:15,17) e uma diz que o fogo \"queimou as ovelhas e os servos\" (1:16). Quando Jó perde tudo, o \"tudo\" inclui os homens que trabalhavam para ele — e ele saberá disso a vida inteira: \"Se desprezei o direito do meu servo ou da minha serva... que faria eu quando Deus se levantasse?\" (31:13-14).",
    },
  },

  // ------------------------------------------------------------------ Jó 2
  2: {
    servo: {
      title: "O servo que veio de longe com os três amigos, e que os viu não reconhecer o dono da casa",
      subtitle: "Jó 2:11-13 • a comitiva que chegou de Temã, de Suá e de Naamá",
      text: "\"Ouvindo, pois, três amigos de Jó todo este mal que tinha vindo sobre ele, vieram cada um do seu lugar\" (Jó 2:11) — três homens de posse, vindos de três terras diferentes, e ninguém atravessava o deserto sozinho: quem carrega o odre, arma a tenda e trata os animais é este servo, que fica de fora da conversa e vê tudo. O que ele vê primeiro é a coisa mais terrível do capítulo: \"levantando de longe os seus olhos, não o conheceram\" (2:12). O homem sentado no monturo estava tão desfigurado pelas úlceras que os amigos de uma vida inteira precisaram chegar perto para ter certeza de que era ele. Depois vem o luto à maneira antiga — a voz levantada, o pranto, os mantos rasgados, o pó lançado ao ar sobre as cabeças (2:12) — e, por fim, sete dias inteiros de silêncio: \"assentaram-se com ele na terra, sete dias e sete noites; e nenhum lhe dizia palavra alguma, porque viam que a dor era muito grande\" (2:13). Sete dias é o tempo do luto por um morto (cf. Gn 50:10; 1Sm 31:13). Enquanto ficaram calados, os três amigos fizeram tudo certo; o livro só começa a dar errado quando abrem a boca.",
    },
  },

  // ------------------------------------------------------------------ Jó 3
  3: {
    anciao: {
      title: "Os conselheiros da terra que jazem com os reis nas casas que edificaram em lugares assolados",
      subtitle: "Jó 3:14 • o repouso que a morte teria sido, na primeira fala de Jó",
      text: "\"Com os reis e conselheiros da terra, que para si edificam casas nos lugares assolados\" (Jó 3:14). Jó está descrevendo o sossego que teria tido se houvesse morrido ao nascer, e a companhia que imagina é a mais alta possível: os homens de conselho, os que decidiam a vida dos povos sentados ao lado do trono. A ironia da imagem está na palavra ASSOLADOS — o que estes homens edificaram para si, e onde agora jazem, são monumentos em lugares hoje desertos, ruína no meio do nada. O que ele quer dizer é que a morte iguala: aquele conselheiro e o menino abortado estão no mesmo lugar, e ali \"os maus cessam de perturbar; e ali repousam os cansados\" (3:17). É o mesmo veredicto do Pregador diante das obras que se levantam para durar: \"olhei eu para todas as obras que fizeram as minhas mãos... e eis que tudo era vaidade\" (Ec 2:11). Note-se o que Jó NÃO diz: em nenhum momento amaldiçoa Deus. Ele amaldiçoa o seu dia (3:1), e a inveja que confessa é dos mortos, não dos vivos.",
    },
    homem: {
      title: "As figuras do capítulo do dia amaldiçoado: os que estão prontos para suscitar o pranto, os cansados que repousam, os presos que não ouvem a voz do exator, os que cavam em procura da morte e o homem cujo caminho é oculto",
      subtitle: "Jó 3:8,17-18,20-23 • as imagens que Jó vê depois de sete dias calado",
      text: "Depois de sete dias de silêncio, \"abriu Jó a sua boca, e amaldiçoou o seu dia\" (Jó 3:1), e o palco passa a mostrar o que ele vê. Primeiro os encantadores de mau agouro que ele convoca contra a sua data de nascimento: \"Amaldiçoem-na aqueles que amaldiçoam o dia, que estão prontos para suscitar o seu pranto\" (3:8). Depois os habitantes do lugar onde ele queria estar: \"Ali os maus cessam de perturbar; e ali repousam os cansados. Ali os presos juntamente repousam, e não ouvem a voz do exator\" (3:17-18) — o exator é o cobrador de trabalho forçado, o mesmo ofício dos que punham cargas sobre Israel no Egito (Êx 5:6,13); a única liberdade que Jó consegue enxergar é a do túmulo, onde o capataz não entra. Depois os que procuram a morte como quem escava atrás de tesouro: \"esperam a morte, e ela não vem; e cavam em procura dela mais do que de tesouros ocultos; que de alegria saltam, e exultam, achando a sepultura\" (3:21-22). E por fim ele mesmo, sem se nomear: \"Por que se dá luz ao homem, cujo caminho é oculto, e a quem Deus o encobriu?\" (3:23) — não é a dor que o mata, é não saber por quê. É a pergunta que o livro inteiro vai levar até o redemoinho de 38:1.",
    },
    mulherComum: {
      title: "A mãe que o recebeu nos joelhos e lhe deu os peitos, no versículo em que Jó pergunta por quê",
      subtitle: "Jó 3:10-12 • as portas do ventre que não se fecharam",
      text: "\"Porque não fechou as portas do ventre; nem escondeu dos meus olhos a canseira... Por que me receberam os joelhos? E por que os peitos, para que mamasse?\" (Jó 3:10-12). Receber o recém-nascido sobre os joelhos é o gesto antigo de acolhê-lo na família — é assim que Raquel fala do filho que Bila teria \"sobre meus joelhos\" (Gn 30:3) e assim que José vê os netos (Gn 50:23). Jó não está acusando a mãe: está desmontando, um a um, todos os cuidados que o mantiveram vivo, e é isso que torna o capítulo tão sombrio — ele deseja que o próprio começo não tivesse acontecido. A figura em cena é a mulher que fez o que qualquer mãe faz, e cujo gesto de amor virou, na boca do filho arrasado, um argumento contra a vida. Vale ler ao lado o Salmo que diz o contrário sem negar a dor: \"Pois possuíste os meus rins; cobriste-me no ventre de minha mãe\" (Sl 139:13). O próprio Jó voltará a esta cena no capítulo 10, e ali com outra ternura: \"As tuas mãos me fizeram e me formaram completamente\" (10:8).",
    },
    rei: {
      title: "Os reis que edificaram casas em lugares assolados, os príncipes que encheram de prata as suas casas, e o grande que jaz ao lado do pequeno",
      subtitle: "Jó 3:14-15,19 • a igualdade da sepultura, na boca de quem perdeu tudo",
      text: "\"Com os reis e conselheiros da terra, que para si edificam casas nos lugares assolados, ou com os príncipes que possuem ouro, que enchem as suas casas de prata\" (Jó 3:14-15). Jó não está criticando os poderosos: está listando com quem estaria deitado se tivesse morrido ao nascer. O contraste é deliberado — casas cheias de prata e casas em lugares desertos, o ouro e o pó, tudo no mesmo parágrafo. E a conclusão é a frase mais nivelada da Escritura: \"Ali está o pequeno e o grande, e o servo livre de seu senhor\" (3:19). O rei em cena é, portanto, uma figura de argumento: aquele diante de quem todos se levantavam, agora sem nada que o distinga do escravo que ele possuía. É a mesma leitura do salmista — \"ele vê que os sábios morrem; perecem igualmente tanto o louco como o brutal, e deixam a outros os seus bens\" (Sl 49:10) — e a razão pela qual Jó pode dizer, sentado numa cinza, o que nenhum príncipe de casa cheia de prata jamais precisou dizer: \"nu saí do ventre de minha mãe e nu tornarei para lá\" (1:21).",
    },
    servo: {
      title: "O servo livre de seu senhor na sepultura, e o que guardava a prata do príncipe enquanto ele vivia",
      subtitle: "Jó 3:15,19 • a alforria que só a morte deu",
      text: "\"Ali está o pequeno e o grande, e o servo livre de seu senhor\" (Jó 3:19). É a única alforria que Jó consegue enxergar do fundo do monturo, e ela custa a vida: no túmulo o escravo deixa de pertencer a alguém. A figura que o acompanha é a do homem que passava os dias guardando a fortuna alheia — \"os príncipes que possuem ouro, que enchem as suas casas de prata\" (3:15) — e que não levava nada dela, mas também não era levado por ela. Ao lado dele estão os presos que \"não ouvem a voz do exator\" (3:18), o cobrador de trabalho forçado. Este é um dos poucos lugares do Antigo Testamento em que a servidão aparece pelo avesso, vista do lado de quem serve; e vale lembrar que quem fala aqui foi, até dias atrás, o maior patrão do oriente, com \"muitíssimos os servos a seu serviço\" (1:3). É o mesmo homem que mais adiante dirá, sobre esses mesmos servos: \"Aquele que me formou no ventre não o fez também a ele?\" (31:15).",
    },
  },

  // ------------------------------------------------------------------ Jó 4
  4: {
    anciao: {
      title: "O ancião que se assentava com Jó à porta de Uz, no tempo em que ele ensinava a muitos",
      subtitle: "Jó 4:3-5 • a memória com que Elifaz abre o primeiro discurso",
      text: "\"Eis que ensinaste a muitos, e tens fortalecido as mãos fracas\" (Jó 4:3). Antes de acusar, Elifaz descreve o que Jó era na praça: um homem procurado por conselho, cuja palavra endireitava gente que ia caindo. O próprio Jó desenhará depois essa cena com todos os detalhes — \"Quando eu saía para a porta da cidade, e na rua fazia preparar a minha cadeira, Os moços me viam, e se escondiam, e até os idosos se levantavam e se punham em pé\" (29:7-8) —, e nela até os príncipes \"continham as suas palavras, e punham a mão sobre a sua boca\" (29:9). Este ancião é um deles: colega de banco, testemunha de anos de bom julgamento. E é justamente por isso que o argumento de Elifaz corta: \"Mas agora, que se trata de ti, te enfadas; e tocando-te a ti, te perturbas\" (4:5). O consolo que ele oferece é o de um tribunal — se a tua doutrina servia para os outros, sirva agora para ti. O que não lhe ocorre é que o caso à sua frente não cabe na doutrina.",
    },
    homem: {
      title: "As figuras do primeiro discurso de Elifaz: as mãos fracas e os joelhos desfalecentes que Jó firmou, o inocente que jamais pereceu, o que lavra iniquidade e sega o mesmo, e os que habitam em casas de lodo",
      subtitle: "Jó 4:3-4,7-8,19 • a doutrina da retribuição posta em imagens",
      text: "Elifaz constrói o seu caso em três quadros. O primeiro é elogio: \"As tuas palavras firmaram os que tropeçavam e os joelhos desfalecentes tens fortalecido\" (Jó 4:4) — homens que estavam indo ao chão e ficaram de pé por causa de Jó. O segundo é a tese, e é uma pergunta que soa irrespondível: \"Lembra-te agora qual é o inocente que jamais pereceu? E onde foram os sinceros destruídos?\" (4:7). Dela sai o lavrador que é a figura mais dura do capítulo: \"Segundo eu tenho visto, os que lavram iniqüidade, e semeiam mal, segam o mesmo\" (4:8) — a mesma lei que Oseias resume em \"semearam vento, e segarão tormenta\" (Os 8:7) e Paulo em \"tudo o que o homem semear, isso também ceifará\" (Gl 6:7). O erro de Elifaz não é a lei; é o uso dela ao contrário, para deduzir do sofrimento de um homem o pecado que ele teria semeado. O terceiro quadro vem da visão da noite e é o mais belo e o mais desolado: \"àqueles que habitam em casas de lodo, cujo fundamento está no pó, e são esmagados como a traça!\" (4:19) — a carne humana como taipa que não se sustenta, o mesmo pó de Gn 3:19 e o mesmo barro de que Paulo diz \"temos, porém, este tesouro em vasos de barro\" (2Co 4:7).",
    },
    pastor: {
      title: "O pastor que fugiu do covil, no versículo em que o leão velho perece por falta de presa",
      subtitle: "Jó 4:10-11 • a imagem com que Elifaz descreve a queda dos violentos",
      text: "\"O rugido do leão, e a voz do leão feroz, e os dentes dos leõezinhos se quebram. Perece o leão velho, porque não tem presa; e os filhos da leoa andam dispersos\" (Jó 4:10-11). Cinco palavras diferentes para leão em dois versículos: Elifaz está pintando uma família inteira de predadores — o que ruge, o feroz, os filhotes, o velho, a leoa — e mostrando todos eles acabando pelo lado mais humilhante possível, não pela lança de um caçador, mas pela FOME. A figura em cena é quem convive com esse bicho: o pastor do oriente antigo, que perdia ovelhas para o leão e às vezes ia buscá-las de dentro da boca dele, como Davi contou a Saul (1Sm 17:34-35). O que Elifaz quer dizer é claro: por mais forte que seja o ímpio, Deus o desmonta e a casa toda se dispersa. É a imagem que Naum aplicará a Nínive — \"Onde está agora o covil dos leões... onde passeava o leão velho, e o filhote do leão, sem haver ninguém que os espantasse?\" (Na 2:11). E é o avesso da promessa do salmo: \"Os filhos dos leões necessitam e sofrem fome, mas àqueles que buscam ao Senhor bem nenhum faltará\" (Sl 34:10).",
    },
    servo: {
      title: "O aprendiz que Jó ensinava ao portão, o ceifeiro da messe dos que semeiam o mal, o homem sobre quem cai o sono profundo e o vizinho esmagado como a traça",
      subtitle: "Jó 4:3,8,13,19 • as mãos que aparecem no discurso de Elifaz",
      text: "\"Eis que ensinaste a muitos\" (Jó 4:3) — e entre esses muitos estava o moço que ficava de pé, ouvindo, enquanto os anciãos se assentavam. Depois o palco vira lavoura: o ceifeiro que corta a messe daqueles que \"lavram iniqüidade, e semeiam mal\" e \"segam o mesmo\" (4:8), e que morrem \"com o hálito de Deus\" e \"com o sopro da sua ira\" (4:9) — um só bafo, e a colheita inteira se desfaz. Depois o quadro escurece para a única experiência que Elifaz alega ter: \"Entre pensamentos vindos de visões da noite, quando cai sobre os homens o sono profundo\" (4:13) — o mesmo torpor pesado que caiu sobre Abrão no corte da aliança (Gn 15:12) e sobre Adão quando lhe foi tirada a costela (Gn 2:21); aqui, porém, não é Deus quem fala, é um vulto sem feição, e é dele que Elifaz tira a sua autoridade. E fecha com o mais frágil de todos os figurantes: o homem de \"casas de lodo, cujo fundamento está no pó\", esmagado \"como a traça\", que \"desde a manhã até à tarde\" é despedaçado \"e eternamente perecem sem que disso se faça caso\" (4:19-20). Um bicho de pano que se mata sem querer, entre o café e o anoitecer.",
    },
  },

  // ------------------------------------------------------------------ Jó 5
  5: {
    anciao: {
      title: "O velho que chega à sepultura como o feixe de trigo se recolhe a seu tempo",
      subtitle: "Jó 5:26 • a última promessa do discurso de Elifaz",
      text: "\"Na velhice irás à sepultura, como se recolhe o feixe de trigo a seu tempo\" (Jó 5:26). É a imagem mais bonita que Elifaz produz no livro inteiro: a morte não como corte, mas como colheita — o feixe que se ata quando o grão já está pronto, no dia certo, sem pressa e sem desperdício. Esse velho em cena é o retrato do fim que a doutrina de Elifaz promete a quem aceitar a correção: descendência \"como a erva da terra\" (5:25), tenda em paz (5:24), e por último a ceifa madura. Nada nisso é falso — é exatamente assim que a Escritura descreve a morte de Abraão, \"em boa velhice, velho e farto de dias\" (Gn 25:8), e de Davi, \"cheio de dias, riquezas e glória\" (1Cr 29:28). O problema é o endereço: Elifaz oferece esse fim a um homem que acabou de enterrar dez filhos e a quem ele mesmo, três versículos antes, disse que a aflição não brota da terra por acaso (5:6). Uma promessa verdadeira dita à pessoa errada, na hora errada, vira acusação.",
    },
    homem: {
      title: "O louco que Elifaz viu lançar raízes, o astuto apanhado na própria astúcia, o abatido posto num lugar alto, o necessitado livrado da espada e o homem a quem Deus faz a chaga e ele mesmo liga",
      subtitle: "Jó 5:2-5,11-21 • o mundo em ordem que Elifaz descreve — e a ordem em que Jó não cabe",
      text: "O capítulo 5 é um mundo inteiro em duas colunas. Na primeira, o insensato: \"Bem vi eu o louco lançar raízes; porém logo amaldiçoei a sua habitação. Seus filhos estão longe da salvação; e são despedaçados às portas, e não há quem os livre. A sua messe, o faminto a devora... e o salteador traga a sua fazenda\" (Jó 5:3-5) — e o ouvinte que acabou de perder os filhos numa casa que caiu entende perfeitamente de quem Elifaz está falando. Com ele vêm os astutos cujas imaginações Deus aniquila e que \"de dia encontram as trevas; e ao meio-dia andam às apalpadelas como de noite\" (5:14), e os sábios que ele \"apanha na sua própria astúcia\" — a única frase de Jó que o Novo Testamento cita como Escritura (1Co 3:19). Na segunda coluna, os salvos: os abatidos postos \"num lugar alto\", os enlutados que \"se exaltem na salvação\" (5:11), o necessitado livrado \"da espada, e da boca deles, e da mão do forte\" (5:15), o pobre para quem \"há esperança\" (5:16), e o homem ferido e curado pela mesma mão — \"ele faz a chaga, e ele mesmo a liga; ele fere, e as suas mãos curam\" (5:18), palavra que Provérbios repete como carinho de pai (Pv 3:11-12) e Hebreus como sinal de filiação (Hb 12:6). Tudo verdadeiro. E nada disso explica por que Jó está sentado na cinza.",
    },
    rebanho: {
      title: "Os animais da terra que não temerás e as feras do campo que serão pacíficas contigo",
      subtitle: "Jó 5:22-23 • a paz com a criação prometida ao homem corrigido",
      text: "\"Da assolação e da fome te rirás, e os animais da terra não temerás. Porque até com as pedras do campo terás o teu acordo, e as feras do campo serão pacíficas contigo\" (Jó 5:22-23). Elifaz está oferecendo a Jó a reconciliação com tudo o que, no oriente antigo, ameaçava um criador de gado: a pedra que quebra o arado e estraga a lavoura, e a fera que come as ovelhas — as mesmas que quatro versículos antes ele descreveu de dentes quebrados (4:10-11). É uma promessa de aliança com o campo, parente da que Oseias põe na boca de Deus: \"naquele dia farei por eles aliança com as feras do campo, e com as aves do céu, e com os répteis da terra\" (Os 2:18), e do quadro de Isaías em que \"morará o lobo com o cordeiro\" (Is 11:6). A crueldade não está no conteúdo: está em quem ouve. Jó já ouviu, poucos dias antes, que os sabeus levaram os bois, o fogo queimou as ovelhas e os caldeus tomaram os camelos (1:14-17). O amigo lhe promete um campo pacífico quando ele já não tem gado nenhum para pôr nele.",
    },
    servo: {
      title: "O que atiça a fogueira de que sobem as faíscas, o lavrador que rega o campo com as águas que Deus envia, o irmão do despedaçado às portas e os filhos da posteridade que se multiplica como a erva",
      subtitle: "Jó 5:4,7,10,25 • as mãos que aparecem dentro das imagens de Elifaz",
      text: "\"Mas o homem nasce para a tribulação, como as faíscas se levantam para voar\" (Jó 5:7). Alguém tem de estar atiçando esse fogo para que as fagulhas subam, e é essa figura curvada sobre a brasa que o palco mostra: a frase de Elifaz é uma lei da natureza dita à beira de uma fogueira — o que sobe, sobe; o que nasce homem, sofre. Ao lado dele está o lavrador do versículo mais generoso do discurso: \"Ele dá a chuva sobre a terra, e envia águas sobre os campos\" (5:10), o mesmo Deus que, segundo o Sermão do Monte, \"faz que o seu sol se levante sobre maus e bons, e a chuva desça sobre justos e injustos\" (Mt 5:45). Depois o palco escurece: o irmão dos filhos do insensato, \"despedaçados às portas, e não há quem os livre\" (5:4) — a porta da cidade é o tribunal, e o que ele descreve é gente que perdeu a causa e ninguém apareceu para defender. E, no fim, os filhos da promessa: \"se multiplicará a tua descendência e a tua posteridade como a erva da terra\" (5:25). Elifaz põe no mesmo discurso os filhos que morrem às portas e os filhos que se multiplicam como erva, e deixa Jó escolher de que lado quer estar — como se estivesse ao alcance dele.",
    },
  },

  // ------------------------------------------------------------------ Jó 6
  6: {
    homem: {
      title: "Os caminhantes de Tema que procuram o ribeiro, o hóspede diante da comida insípida, o amigo que poderia oferecer presentes e o opressor de cujas mãos Jó nada pediu",
      subtitle: "Jó 6:6-7,19-20,22-23 • a resposta de Jó a Elifaz, dita por imagens de estrada e de mesa",
      text: "A figura central deste capítulo é uma caravana. \"Os caminhantes de Tema os vêem; os passageiros de Sabá esperam por eles. Ficam envergonhados, por terem confiado e, chegando ali, se confundem\" (Jó 6:19-20). Tema é um oásis do norte da Arábia, ponto de parada de quem cruza o deserto — \"moradores da terra de Tema, saí com pão ao encontro dos fugitivos\" (Is 21:14) —, e a rota de Sabá vinha do sul. O que essa gente faz é o que qualquer viajante faria: contar com o ribeiro que estava lá no inverno. Só que o ribeiro do oriente é uádi: cheio de gelo e neve na estação fria (6:16), e no calor \"se desfazem, e em se aquentando, desaparecem do seu lugar\" (6:17). Chegam ao leito e acham pedra seca. É esse o retrato que Jó faz dos três amigos: \"Meus irmãos aleivosamente me trataram, como um ribeiro, como a torrente dos ribeiros que passam\" (6:15). Ao lado dele estão o hóspede diante do prato sem gosto — \"Ou comer-se-á sem sal o que é insípido?\" (6:6) — e as duas figuras que Jó invoca só para dizer que nunca precisou delas: o amigo rico e o opressor. \"Acaso disse eu: Dai-me ou oferecei-me presentes de vossos bens? Ou livrai-me das mãos do opressor?\" (6:22-23). Ele não pediu dinheiro nem resgate; pediu companhia, e recebeu doutrina.",
    },
    rebanho: {
      title: "O jumento montês junto à relva e o boi que muge junto ao seu pasto",
      subtitle: "Jó 6:5 • os dois bichos com que Jó defende o direito de se queixar",
      text: "\"Porventura zurrará o jumento montês junto à relva? Ou mugirá o boi junto ao seu pasto?\" (Jó 6:5). É o argumento mais simples e mais afiado da resposta a Elifaz: bicho satisfeito não faz barulho. O jumento selvagem, que Deus mais tarde descreverá como o animal a quem \"Ao qual dei o ermo por casa, e a terra salgada por morada?\" (39:6), só zurra quando falta pasto; o boi só muge quando o cocho está vazio. Se Jó está gritando, portanto, não é falta de piedade nem excesso de palavra — é fome. A queixa é sintoma, não pecado. Vale notar de onde vêm as figuras: Jó era dono de \"quinhentas juntas de bois\" (1:3) e sabe do que fala; e o mesmo homem que aqui usa dois animais para explicar a própria dor vai mandar os amigos aprenderem com eles em 12:7 — \"pergunta agora às alimárias, e cada uma delas te ensinará\". Em Jó, os bichos entendem de Deus mais depressa do que os teólogos.",
    },
    servo: {
      title: "O carregador que pesaria a mágoa contra a areia dos mares, o caminhante cuja vereda sobe ao vácuo, e o órfão sobre quem se lançam sortes",
      subtitle: "Jó 6:2-3,18,27 • os figurantes da queixa de Jó contra os amigos",
      text: "\"Oh! se a minha mágoa retamente se pesasse, e a minha miséria juntamente se pusesse numa balança! Porque, na verdade, mais pesada seria, do que a areia dos mares\" (Jó 6:2-3). O primeiro em cena é o homem da balança e do saco: Jó não quer que o compadeçam, quer que o PESEM — que alguém ponha a dor dele num prato e a areia do mar no outro, e veja de que lado desce. O segundo é o caminhante perdido: \"Desviam-se as veredas dos seus caminhos; sobem ao vácuo, e perecem\" (6:18) — as caravanas saem da estrada atrás da água que não existe mais, sobem para o nada e ficam lá. O terceiro é o mais duro, porque é acusação direta: \"Mas antes lançais sortes sobre o órfão; e cavais uma cova para o amigo\" (6:27). Lançar sortes sobre o órfão é o que Joel descreve como o cúmulo da crueldade dos povos — \"lançaram sortes sobre o meu povo, e deram um menino por uma meretriz\" (Jl 3:3) —, e é isso que Jó diz que os três estão fazendo com ele: negociando um homem que não tem quem o defenda, e abrindo cova para um amigo vivo.",
    },
  },

  // ------------------------------------------------------------------ Jó 7
  7: {
    homem: {
      title: "O jornaleiro cujos dias são a medida da vida humana, o vizinho cujos olhos agora o veem e não o verão mais, e a guarda posta sobre o mar e sobre a baleia",
      subtitle: "Jó 7:1-2,8,12 • as três imagens com que Jó fala de si a Deus",
      text: "\"Porventura não tem o homem guerra sobre a terra? E não são os seus dias como os dias do jornaleiro?\" (Jó 7:1). O jornaleiro é o trabalhador que não tem contrato: ganha por dia, e a lei mandava pagá-lo antes do pôr do sol justamente porque não teria como jantar — \"a paga do diarista não ficará contigo até pela manhã\" (Lv 19:13); \"No seu dia lhe pagarás a sua diária, e o sol não se porá sobre isso... porquanto pobre é, e sua vida depende disso\" (Dt 24:15). Jó diz que a vida inteira é assim: turno duro, pagamento no fim, e nada garantido no meio. O segundo é o vizinho que ainda o vê sentado ali: \"Os olhos dos que agora me vêem não me verão mais; os teus olhos estarão sobre mim, porém não serei mais\" (7:8). O terceiro é o mais amargo e o mais irônico: \"Sou eu porventura o mar, ou a baleia, para que me ponhas uma guarda?\" (7:12) — nos mitos do oriente, o mar e o monstro marinho eram o caos que precisava de sentinela; Jó pergunta desde quando um homem coberto de feridas passou a ser perigoso a ponto de merecer vigilância divina de dia e de noite.",
    },
    servo: {
      title: "O servo que suspira pela sombra, o jornaleiro que espera pela sua paga e o tecelão cuja lançadeira corre mais depressa do que os dias de Jó",
      subtitle: "Jó 7:2,6 • o trabalho braçal como medida do tempo que resta",
      text: "\"Como o servo que suspira pela sombra, e como o jornaleiro que espera pela sua paga\" (Jó 7:2). São dois desejos de fim de expediente, e nada mais: a sombra que vai chegando na parede oposta e o dinheiro na mão ao entardecer. Jó pega o alívio mais modesto que um homem pode ter e diz que nem isso lhe dão — \"assim me deram por herança meses de vaidade; e noites de trabalho me prepararam\" (7:3). A terceira figura é a que ficou famosa: \"Os meus dias são mais velozes do que a lançadeira do tecelão, e acabam-se, sem esperança\" (7:6). A lançadeira é a peça que atravessa o tear de um lado ao outro, rápida demais para o olho acompanhar; e o fio que ela deixa acaba quando o rolo acaba. Ezequias usará a mesma oficina para dizer a mesma coisa na sua doença: \"cortei a minha vida como tecelão; ele me cortará do tear\" (Is 38:12). O que Jó acrescenta é o fim da frase — \"sem esperança\" —, e é dela que ele vai tentar sair nos capítulos seguintes.",
    },
  },

  // ------------------------------------------------------------------ Jó 8
  8: {
    anciao: {
      title: "As gerações passadas a quem Bildade manda perguntar, e os pais cuja inquirição é a sua autoridade",
      subtitle: "Jó 8:8-10 • \"nós somos de ontem, e nada sabemos\"",
      text: "\"Pois, eu te peço, pergunta agora às gerações passadas; e prepara-te para a inquirição de seus pais. Porque nós somos de ontem, e nada sabemos; porquanto nossos dias sobre a terra são como a sombra. Porventura não te ensinarão eles, e não te falarão, e do seu coração não tirarão palavras?\" (Jó 8:8-10). Onde Elifaz apelou para uma visão que teve de noite, Bildade apela para a tradição: o que os antigos sempre souberam vale mais do que o que qualquer homem vivo pode alegar. É um princípio bom — \"pergunta a teu pai, e ele te informará; aos teus anciãos, e eles te dirão\" (Dt 32:7) — e a Escritura o repete muito. O ancião em cena é essa cadeia de memória: o velho da porta que guarda os provérbios e sabe como o mundo funciona. O que Bildade não percebe é que acabou de escolher uma testemunha que não pode ser interrogada. O caso de Jó é EXATAMENTE aquilo que a tradição não previu, e nenhum pai que morreu antes dele jamais viu um homem íntegro ser entregue nas mãos do adversário por causa da sua integridade.",
    },
    homem: {
      title: "O suplicante que de madrugada busca a Deus, o hipócrita que se encosta à sua casa e ela não subsiste, o reto que Deus não rejeitará e o inimigo que se vestirá de confusão",
      subtitle: "Jó 8:5-6,13-15,20-22 • as duas fileiras em que Bildade divide os homens",
      text: "O discurso inteiro de Bildade cabe em duas figuras opostas. De um lado, o homem que se dobra: \"se tu de madrugada buscares a Deus, e ao Todo-Poderoso pedires misericórdia; se fores puro e reto, certamente logo despertará por ti, e restaurará a morada da tua justiça\" (Jó 8:5-6) — note-se a madrugada, exatamente a hora em que o Jó do capítulo 1 se levantava para oferecer holocaustos pelos filhos (1:5); Bildade está mandando fazer o que ele já fazia. Do outro lado, o hipócrita: \"a esperança do hipócrita perecerá. Cuja esperança fica frustrada; e a sua confiança será como a teia de aranha. Encostar-se-á à sua casa, mas ela não subsistirá; apegar-se-á a ela, mas não ficará em pé\" (8:13-15). A teia de aranha é a imagem exata da coisa que parece estrutura e não segura peso nenhum — Isaías a usará contra os que confiam nas próprias obras: \"as suas teias não prestam para vestes\" (Is 59:6). E o fecho promete a Jó riso e júbilo enquanto \"os que te odeiam se vestirão de confusão, e a tenda dos ímpios não existirá mais\" (8:22). Dito a um homem cuja casa acabara de cair sobre dez filhos, o quadro da casa que não fica em pé é mais do que uma metáfora infeliz: é 8:4 outra vez, agora sem dizer o nome.",
    },
    rebanho: {
      title: "O gado do último estado que cresceria em extremo",
      subtitle: "Jó 8:7 • a restauração que Bildade promete se Jó se arrepender",
      text: "\"O teu princípio, na verdade, terá sido pequeno, porém o teu último estado crescerá em extremo\" (Jó 8:7). Bildade oferece um negócio: reconheça a culpa, e a fazenda volta maior do que era. O rebanho em cena é essa promessa em carne e lã — os currais recompostos, o gado que se multiplica outra vez na terra, como \"o seu gado se tem aumentado na terra\" que o próprio adversário reconhecera diante de Deus (1:10). O espantoso é que Bildade acerta o desfecho e erra tudo o mais: no último capítulo o Senhor \"abençoou o Senhor o último estado de Jó, mais do que o primeiro; pois teve catorze mil ovelhas, e seis mil camelos, e mil juntas de bois, e mil jumentas\" (42:12) — o dobro exato. Só que isso não veio porque Jó confessou um pecado escondido; veio depois de Deus dizer a Elifaz e aos dois amigos que \"não falastes de mim o que era reto, como o meu servo Jó\" (42:7), e quando Jó orou por eles (42:10). A conta de Bildade fecha; a teologia dele, não.",
    },
    servo: {
      title: "O jardineiro da planta viçosa perante o sol, cujas raízes se entrelaçam junto à fonte",
      subtitle: "Jó 8:11-12,16-19 • o papiro sem lodo, o junco sem água e o lugar que nega a planta arrancada",
      text: "\"Porventura cresce o junco sem lodo? Ou cresce a espadana sem água?\" (Jó 8:11). Bildade tira as suas imagens de uma horta e de um brejo, e o servo em cena é quem cuida delas. Primeiro o papiro e a espadana, que parecem fortes e são inteiramente dependentes do charco: baixe a água e, \"estando ainda no seu verdor, ainda que não cortada, todavia antes de qualquer outra erva se seca\" (8:12) — morre em pé, verde, antes de todas as outras. Depois a trepadeira do jardim, e este é o quadro mais bem feito do capítulo: \"Ele é viçoso perante o sol, e os seus renovos saem sobre o seu jardim; as suas raízes se entrelaçam, junto à fonte; para o pedregal atenta\" (8:16-17). Um pé de planta agarrado à pedra com raiz de sobra, ocupando o canteiro inteiro. E então a frase que Bildade guardou para o fim: \"Se Deus o consumir do seu lugar, negá-lo-á este, dizendo: Nunca te vi!\" (8:18). O chão finge que nunca conheceu a planta que estava ali no dia anterior. É o avesso exato do que Jó dirá no capítulo 14 sobre a árvore cortada que \"ao cheiro das águas brotará\" (14:9) — os dois usam o mesmo canteiro para provar coisas opostas.",
    },
  },

  // ------------------------------------------------------------------ Jó 9
  9: {
    anciao: {
      title: "Os juízes cujo rosto Deus cobre, no versículo em que Jó diz que a terra foi entregue nas mãos do ímpio",
      subtitle: "Jó 9:24 • a acusação mais perigosa que Jó faz",
      text: "\"A terra é entregue nas mãos do ímpio; ele cobre o rosto dos juízes; se não é ele, quem é, logo?\" (Jó 9:24). Cobrir o rosto do juiz é deixá-lo julgar às cegas — o oposto exato do que a lei exigia da porta da cidade, onde \"não torcerás o juízo, não farás acepção de pessoas, nem receberás peitas\" (Dt 16:19). O ancião em cena é esse magistrado de olhos tapados, e a pergunta que Jó pendura ao lado dele é a mais ousada do livro até aqui: se o mundo está torto e não é Deus quem o entortou, quem é? Jó não está negando a existência de Deus; está negando que o mundo, do jeito que ele o vê da cinza, prove a justiça de Deus. É a mesma pergunta que Jeremias fará sem rodeios — \"Por que prospera o caminho dos ímpios, e vivem em paz todos os que procedem aleivosamente?\" (Jr 12:1) — e que Asafe quase perdeu a fé tentando responder até entrar no santuário (Sl 73:2-3,17). O livro de Jó não corrige essa pergunta com uma teoria: corrige-a com uma voz que vem do redemoinho, e que nunca explica o capítulo 1 a Jó.",
    },
    homem: {
      title: "Os auxiliadores soberbos que se encurvam debaixo dele, o dono a quem a presa é arrebatada, o inocente de cuja prova se zomba e o perfeito que é consumido junto com o ímpio",
      subtitle: "Jó 9:12-13,22-24 • as figuras da resposta a Bildade, sobre o Deus com quem não se pode contender",
      text: "O capítulo 9 é sobre um poder diante do qual não há recurso, e as figuras são todas de gente vencida antes de abrir a boca. \"Eis que arrebata a presa; quem lha fará restituir? Quem lhe dirá: Que é o que fazes?\" (Jó 9:12) — o dono do bem levado nem sequer tem a quem reclamar. \"Deus não revogará a sua ira; debaixo dele se encurvam os auxiliadores soberbos\" (9:13): os fortes que se juntam para ajudar o caos acabam curvados, e o verbo é de dobradiça, não de reverência. E então vem a frase que os amigos jamais admitiriam: \"A coisa é esta; por isso eu digo que ele consome ao perfeito e ao ímpio. Quando o açoite mata de repente, então ele zomba da prova dos inocentes\" (9:22-23). Jó está dizendo, em cima da cinza, que a vida não separa os dois — e o próprio prólogo lhe dá razão, porque o leitor sabe desde 1:8 que o golpe caiu justamente sobre aquele de quem Deus se gabou. O que falta a Jó não é uma tese melhor: é uma pessoa. \"Porque ele não é homem, como eu, a quem eu responda, vindo juntamente a juízo. Não há entre nós árbitro que ponha a mão sobre nós ambos\" (9:32-33) — o buraco que 1Tm 2:5 preencheria: \"há um só Deus, e um só Mediador entre Deus e os homens, Jesus Cristo homem\".",
    },
    servo: {
      title: "O correio que corre mais depressa do que os dias de Jó",
      subtitle: "Jó 9:25-26 • o mensageiro, o navio veleiro e a águia que se lança à comida",
      text: "\"E os meus dias são mais velozes do que um correio; fugiram, e não viram o bem. Passam como navios veleiros; como águia que se lança à comida\" (Jó 9:25-26). O correio é o portador de despachos reais, o homem mais rápido do mundo antigo — os que corriam de posta em posta com a carta do rei, como os correios de Assuero, que \"sobre ginetes velozes, saíram apressuradamente, impelidos pela palavra do rei\" (Et 8:14). Jó põe esse homem em cena para dizer que os seus dias o ultrapassam. E, para não deixar dúvida, empilha mais duas velocidades: o navio de vela empurrado pelo vento e a águia que fecha as asas e despenca sobre a caça. Três imagens de pressa e nenhuma de destino: \"fugiram, e não viram o bem\". Vale notar a diferença entre este correio e o do capítulo 1: lá, quatro mensageiros chegaram um atrás do outro trazendo notícia de tudo o que se perdera; aqui, o mensageiro já não traz nada — ele é apenas a medida do tempo que passou por cima de um homem que continua sentado no mesmo monturo.",
    },
  },

  // ----------------------------------------------------------------- Jó 10
  10: {
    homem: {
      title: "As testemunhas que Deus renova contra Jó",
      subtitle: "Jó 10:17 • \"Tu renovas contra mim as tuas testemunhas\"",
      text: "\"Tu renovas contra mim as tuas testemunhas, e multiplicas contra mim a tua ira; reveses e combate estão comigo\" (Jó 10:17). A cena é um tribunal em que a acusação nunca fecha: cada vez que uma testemunha termina o depoimento, entra outra — e o réu não sabe do que é acusado, porque a pergunta dele é justamente \"Direi a Deus: Não me condenes; faze-me saber por que contendes comigo\" (10:2). No mundo de Jó, as testemunhas que se renovam são as chagas: cada nova ferida é um depoimento a mais contra ele diante dos que olham. Os três amigos leem esses corpos de delito exatamente assim, e é por isso que a defesa de Jó tem de correr contra o tempo. O mesmo homem que aqui vê só acusadores dirá, poucos capítulos adiante, que há alguém do outro lado: \"Eis que também agora a minha testemunha está no céu, e nas alturas o meu testemunho está\" (16:19). É a mesma imagem virada do avesso — e o começo da resposta que ele não terá em 10:17.",
    },
    rebanho: {
      title: "O rebanho de que vem o leite, no versículo em que Jó fala de como foi feito",
      subtitle: "Jó 10:10 • \"Porventura não me vazaste como leite, e como queijo não me coalhaste?\"",
      text: "\"Porventura não me vazaste como leite, e como queijo não me coalhaste? De pele e carne me vestiste, e de ossos e nervos me teceste\" (Jó 10:10-11). A imagem vem do curral e da cozinha, não do templo: a ordenha, o leite que se despeja na vasilha, o coalho que o firma até virar massa. Jó está descrevendo a própria gestação como um trabalho artesanal feito por mãos que sabiam o que estavam fazendo, e o rebanho em cena é a origem daquela metáfora — as cabras e ovelhas de que se tirava o leite todos os dias na casa de um homem que possuía sete mil ovelhas (1:3). O argumento é este: o Deus que me formou com esse cuidado é o mesmo que agora me desfaz, e é isso que não fecha — \"As tuas mãos me fizeram e me formaram completamente; contudo me consomes\" (10:8). O Salmo 139 percorre o mesmo caminho e chega ao louvor: \"cobriste-me no ventre de minha mãe... de um modo assombroso, e tão maravilhoso fui feito\" (Sl 139:13-14). Jó percorre-o e chega a uma pergunta: \"Por que, pois, me tiraste da madre?\" (10:18). O material é o mesmo; o que muda é onde o homem está sentado quando o diz.",
    },
    servo: {
      title: "O escrivão da inquirição da iniquidade de Jó e o queijeiro que coalha o leite no pátio",
      subtitle: "Jó 10:6,10 • o processo que se instaura e as mãos que o formaram",
      text: "Duas mãos muito diferentes trabalham neste capítulo. A primeira é a do escrivão do processo: \"Para te informares da minha iniqüidade, e averiguares o meu pecado?\" (Jó 10:6) — Jó imagina Deus abrindo inquérito, juntando peças, tomando termo, e acha o quadro absurdo justamente porque não há o que averiguar: \"Bem sabes tu que eu não sou iníquo; todavia ninguém há que me livre da tua mão\" (10:7). Deus não precisa investigar, e ainda assim o trata como suspeito. A segunda mão é a do queijeiro, e é de uma ternura que o capítulo não consegue sustentar: o leite vazado na vasilha e coalhado até tomar corpo (10:10), o tecelão de ossos e nervos (10:11), o dono da casa que dá \"vida e misericórdia\" e cujo \"cuidado guardou o meu espírito\" (10:12). Jó põe o escrivão e o queijeiro lado a lado de propósito: como pode a mesma pessoa ter feito as duas coisas? É a pergunta que ele carrega até 42:5 — \"Com o ouvir dos meus ouvidos ouvi, mas agora te vêem os meus olhos\".",
    },
  },

  // ----------------------------------------------------------------- Jó 11
  11: {
    anciao: {
      title: "O ancião da praça que ouve a multidão de palavras e o escriba que guarda os segredos da sabedoria",
      subtitle: "Jó 11:2,6 • a plateia que Zofar convoca contra Jó",
      text: "\"Porventura não se dará resposta à multidão de palavras? E o homem falador será justificado?\" (Jó 11:2). Zofar abre a boca falando como quem preside uma assembleia: há falatório demais, alguém tem de pôr ordem. O ancião em cena é essa autoridade da praça, o homem cuja função é ouvir as partes e dizer quem tem razão — e Zofar apela para ele como quem apela para o bom senso público contra um sujeito que já falou demais. Ao lado dele está o guardião do saber antigo, porque o que Zofar deseja para Jó é uma aula: \"quem dera que Deus falasse e abrisse os seus lábios contra ti! E te fizesse saber os segredos da sabedoria, que é multíplice em eficácia\" (11:5-6). O desejo é atendido, mas não como ele imaginava: Deus de fato abre os lábios, em 38:1, e o que sai de lá não dá razão a Zofar nem uma vez (42:7). E a frase que ele emenda em seguida — \"sabe, pois, que Deus exige de ti menos do que merece a tua iniqüidade\" (11:6) — é a coisa mais dura dita a Jó no livro inteiro, inclusive pela mulher.",
    },
    homem: {
      title: "O homem falador que Zofar quer ver envergonhado, o que não alcança os caminhos de Deus, o que nasce como a cria do jumento montês, e o que estende as mãos e depois repousa seguro",
      subtitle: "Jó 11:2-3,7-12,13-19 • as duas metades do discurso de Zofar",
      text: "A primeira metade do capítulo é feita de homens pequenos diante de uma medida grande demais. \"Porventura alcançarás os caminhos de Deus, ou chegarás à perfeição do Todo-Poderoso? Como as alturas dos céus é a sua sabedoria; que poderás tu fazer? É mais profunda do que o inferno, que poderás tu saber? Mais comprida é a sua medida do que a terra, e mais larga do que o mar\" (Jó 11:7-9). Quatro dimensões — altura, profundidade, comprimento e largura — e o homem no meio delas sem régua nenhuma; é o mesmo esquema que Paulo usará para dizer o contrário, que se pode \"compreender... qual seja a largura, e o comprimento, e a altura, e a profundidade\" do amor de Cristo (Ef 3:18). Zofar remata com a frase mais desdenhosa que dirige a Jó: \"Mas o homem vão é falto de entendimento; sim, o homem nasce como a cria do jumento montês\" (11:12) — nasce burro e selvagem, e assim continua. A segunda metade é a oferta: prepare o coração, estenda as mãos, lance para longe a iniquidade da sua mão (11:13-14), e então \"o teu rosto levantarás sem mácula\", \"te esquecerás do cansaço, e lembrar-te-ás dele como das águas que já passaram\" (11:15-16), e \"deitar-te-ás, e ninguém te espantará\" (11:19). Um homem dormindo sem susto: é tudo o que Jó queria (cf. 7:13-14) — e vem embrulhado numa acusação que ele não pode aceitar sem mentir.",
    },
    servo: {
      title: "O oficial do juízo à porta de Uz, o mercador que parou para ouvir a contenda, o que varre a tenda em que não há de habitar a injustiça e o que suplica o favor do que repousa seguro",
      subtitle: "Jó 11:10,14,18-19 • os figurantes da praça no discurso de Zofar",
      text: "\"Se ele passar, aprisionar, ou chamar a juízo, quem o impedirá?\" (Jó 11:10). O oficial em cena é o braço que executa essa ordem — o homem que prende e leva à porta da cidade, onde os processos corriam; Zofar está dizendo que contra a citação de Deus não há embargo. Ao lado dele está a praça em volta: os que pararam de negociar para ouvir a contenda dos quatro, porque em Uz um caso assim se julga em público e ninguém perde o espetáculo. Depois o palco entra na casa: \"Se há iniqüidade na tua mão, lança-a para longe de ti e não deixes habitar a injustiça nas tuas tendas\" (11:14) — a injustiça é tratada como moradora, e alguém tem de varrê-la para fora, o que dá a medida de quanto Zofar acredita haver sujeira ali dentro. E, no fim, a promessa: \"olharás em volta e repousarás seguro. E deitar-te-ás, e ninguém te espantará; muitos suplicarão o teu favor\" (11:18-19). Os suplicantes que baterão à porta do restaurado são a imagem do que Jó foi um dia — e ele mesmo contará, no capítulo 29, o que fazia com essa gente: \"eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse\" (29:12).",
    },
  },

  // ----------------------------------------------------------------- Jó 12
  12: {
    anciao: {
      title: "Os acreditados a quem se tira a fala, os anciãos a quem se tira o entendimento, os conselheiros levados despojados e os sacerdotes levados despojados",
      subtitle: "Jó 12:12,17,19-20 • a lista de autoridades que Deus desmonta",
      text: "Jó começa concedendo aos amigos a premissa deles — \"Com os idosos está a sabedoria, e na longevidade o entendimento\" (Jó 12:12) — e depois derruba a premissa inteira com uma lista de sete linhas em que Deus desfaz, uma a uma, todas as instituições de que essa sabedoria depende: \"Aos conselheiros leva despojados, e aos juízes faz desvairar... Aos sacerdotes leva despojados, aos poderosos transtorna. Aos acreditados tira a fala, e tira o entendimento aos anciãos\" (12:17,19-20). \"Acreditados\" são os homens de confiança, aqueles cuja palavra bastava; Deus lhes tira a fala. Aos anciãos — os que Bildade mandara consultar em 8:8 — tira o entendimento. Ao sacerdote, que era o único que tinha acesso ao santo, tira as vestes e leva descalço, do jeito que se leva prisioneiro de guerra (cf. Is 20:4). A força do argumento é esta: se é o próprio Deus quem esvazia os conselheiros e os velhos, então a tradição a que Bildade apelou não é tribunal de recurso nenhum — e o caso de Jó continua sem juiz.",
    },
    homem: {
      title: "O justo que serve de zombaria, a tocha desprezível na opinião do que está descansado, o que erra e o que o faz errar, e os que apalpam nas trevas e desatinam como ébrios",
      subtitle: "Jó 12:4-6,16,24-25 • a resposta em que Jó tira a sabedoria dos amigos e a devolve a Deus",
      text: "\"Eu sou motivo de riso para os meus amigos; eu, que invoco a Deus, e ele me responde; o justo e perfeito serve de zombaria\" (Jó 12:4). Em seguida vem a imagem mais precisa que o livro faz da crueldade dos confortáveis: \"Tocha desprezível é, na opinião do que está descansado, aquele que está pronto a vacilar com os pés\" (12:5) — para quem está firme, o que já vai caindo é um archote sujo que se joga fora. E o mundo, visto do monturo, está de cabeça para baixo: \"As tendas dos assoladores têm descanso, e os que provocam a Deus estão seguros\" (12:6). Depois Jó leva o argumento ao extremo: se tudo vem da mão de Deus, então dela vem também o extravio — \"seu é o que erra e o que o faz errar\" (12:16) —, e o fim da lista mostra chefes de povos vagando \"pelos desertos, sem caminho\", que \"nas trevas andam às apalpadelas, sem terem luz, e os faz desatinar como ébrios\" (12:24-25). É exatamente a cegueira que Elifaz atribuía apenas aos astutos (5:14); Jó a estende aos príncipes das nações. O que ele está dizendo aos três é simples e devastador: vocês estão explicando com um provérbio um Deus que desmonta impérios.",
    },
    mulherComum: {
      title: "A mulher das nações que Deus multiplica e faz perecer, dispersa e de novo reconduz",
      subtitle: "Jó 12:23 • o povo inteiro como figura de um só verbo",
      text: "\"Multiplica as nações e as faz perecer; dispersa as nações, e de novo as reconduz\" (Jó 12:23). Quatro verbos, e cada um deles é a vida inteira de milhares de famílias: crescer, acabar, ser espalhado, ser trazido de volta. A figura em cena é a gente comum a quem essas coisas acontecem sem que ninguém lhe pergunte nada — a mulher que teve filhos numa nação que se multiplicava e os viu morrer quando ela pereceu, a que caminhou no cativeiro e a que voltou. Jó está usando a história dos povos como prova contra a doutrina dos amigos: se o destino de nações inteiras sobe e desce assim, não se pode ler a sorte de um homem como boletim do seu caráter. A Escritura conta a mesma coisa do lado de dentro em Israel — \"aumentou o seu povo em grande maneira\" (Sl 105:24) e depois \"os entregou nas mãos dos gentios\" (Sl 106:41), e por fim os \"que congregou das terras do oriente e do ocidente, do norte e do sul\" (Sl 107:3). Nas mãos de Jó, porém, a lista não é consolo: é a demonstração de que a mão que faz isto tudo não presta contas a ninguém.",
    },
    pastor: {
      title: "O pastor que ouve o que as alimárias ensinam, e o que sabe que a alma de tudo quanto vive está na mão do Senhor",
      subtitle: "Jó 12:7-10 • \"pergunta agora às alimárias, e cada uma delas te ensinará\"",
      text: "\"Mas, pergunta agora às alimárias, e cada uma delas te ensinará; e às aves dos céus, e elas te farão saber; ou fala com a terra, e ela te ensinará; até os peixes do mar te contarão\" (Jó 12:7-8). É a resposta mais irônica que Jó dá aos amigos: aquilo que vocês me ensinam com tanto empenho, qualquer bicho já sabe. O pastor em cena é o homem que passa a vida entre esses professores — vê o rebanho, as aves e a terra o dia inteiro — e sabe a lição sem precisar de discurso: \"Quem não entende, por todas estas coisas, que a mão do Senhor fez isto? Na sua mão está a alma de tudo quanto vive, e o espírito de toda a carne humana\" (12:9-10). É a mesma escola a que Provérbios manda o preguiçoso — \"Vai ter com a formiga, ó preguiçoso; olha para os seus caminhos, e sê sábio\" (Pv 6:6) — e a mesma que Deus abrirá em pessoa nos capítulos 38 a 41, levando Jó pelo leão, pelo corvo, pela cabra montês, pela avestruz, pelo cavalo e pela águia. A diferença é o resultado: quando os bichos são citados por Jó, servem de argumento; quando são apresentados pelo Criador, calam a boca dele (40:4).",
    },
    rebanho: {
      title: "As alimárias a que Jó manda perguntar e tudo quanto vive, cuja alma está na mão do Senhor",
      subtitle: "Jó 12:7,10 • os animais como testemunhas de acusação contra os três amigos",
      text: "\"Pergunta agora às alimárias, e cada uma delas te ensinará\" (Jó 12:7). O rebanho em cena não é cenário: é o corpo de testemunhas que Jó convoca. Ele acaba de ouvir três discursos sobre como Deus governa o mundo e responde que essa informação está disponível em qualquer pasto — os bichos, as aves, a terra e até os peixes do mar sabem de quem depende o fôlego que têm. E o versículo que fecha a convocação é dos mais amplos da Escritura: \"Na sua mão está a alma de tudo quanto vive, e o espírito de toda a carne humana\" (12:10). Tudo o que respira está seguro pela mesma mão, o boi e o homem; o Salmo diz a mesma coisa pelo avesso — \"se lhes tiras o fôlego, morrem, e voltam para o seu pó\" (Sl 104:29). Jó está a poucos capítulos de ouvir o próprio Deus abrir um desfile de animais selvagens para lhe mostrar quanto do mundo funciona sem que o homem sequer o veja. Aqui, ele ainda usa os bichos para vencer uma discussão; lá, os bichos vencerão a discussão dele.",
    },
    rei: {
      title: "O rei cuja autoridade Deus solta e a quem ata o cinto aos lombos, o príncipe sobre quem se derrama desprezo e o chefe dos povos a quem se tira o entendimento",
      subtitle: "Jó 12:18,21,24 • a corte inteira desmontada em três versículos",
      text: "\"Solta a autoridade dos reis, e ata o cinto aos seus lombos\" (Jó 12:18). O verso é uma troca de roupa: tira-se a faixa de comando e amarra-se aos rins a tanga do cativo — o mesmo homem, de manhã no trono, à tarde na corda. \"Derrama desprezo sobre os príncipes, e afrouxa o cinto dos fortes\" (12:21): afrouxar o cinto de um guerreiro é desarmá-lo, porque era nele que iam a espada e a bainha. E o fim da lista é o pior: \"Tira o entendimento aos chefes dos povos da terra, e os faz vaguear pelos desertos, sem caminho\" (12:24) — não são derrotados em batalha, são esvaziados por dentro e postos a andar em círculo, como Nabucodonosor lançado fora dos homens até que soubesse \"que o Altíssimo tem domínio sobre o reino dos homens\" (Dn 4:25). Jó não está celebrando isso: está mostrando aos amigos que o Deus de quem eles falam com tanta confiança é o mesmo que faz reis e desfaz reis sem consultar a doutrina de ninguém — e é por isso que a resposta que ele quer não cabe num provérbio.",
    },
    servo: {
      title: "O servo do arraial dos que provocam a Deus e estão seguros, o que ata o cinto aos lombos do rei destronado e o morador da casa que Deus derruba e ninguém há que edifique",
      subtitle: "Jó 12:6,14,18 • as mãos dentro das imagens da resposta de Jó",
      text: "\"As tendas dos assoladores têm descanso, e os que provocam a Deus estão seguros; nas suas mãos Deus lhes põe tudo\" (Jó 12:6). O primeiro servo em cena é o que trabalha nesse acampamento: alimenta os animais, arruma o saque e dorme tranquilo num arraial de gente que vive de destruir os outros — a prova viva de que a conta dos amigos não fecha. O segundo é o carrasco doméstico do versículo 18, aquele que \"ata o cinto\" aos lombos do rei que acabou de perder a autoridade: alguém tem de amarrar a corda, e é sempre um servo. O terceiro está debaixo de escombros: \"Eis que ele derruba, e ninguém há que edifique; prende um homem, e ninguém há que o solte\" (12:14) — a casa caída de que ninguém vai levantar a parede é a mesma imagem que Jó carrega desde 1:19, quando o vento deu nos quatro cantos e a casa caiu sobre os jovens. Ele não a usa por acaso: é o único argumento que ele não precisa provar.",
    },
  },

  // ----------------------------------------------------------------- Jó 13
  13: {
    anciao: {
      title: "Os inventores de mentiras e os médicos que não valem nada: os que contendem por Deus fazendo acepção da sua pessoa, e o escrivão que escreve contra Jó coisas amargas",
      subtitle: "Jó 13:4,7-10,26 • a repreensão de Jó aos três amigos, e a queixa que ele leva a Deus",
      text: "\"Vós, porém, sois inventores de mentiras, e vós todos médicos que não valem nada\" (Jó 13:4). É a sentença mais famosa que Jó pronuncia contra os amigos, e ela os julga no ofício que eles próprios escolheram: vieram \"para o consolarem\" (2:11) e receitaram veneno. Em seguida ele diz por que a defesa que eles fazem de Deus é ímpia: \"Porventura por Deus falareis perversidade e por ele falareis mentiras? Fareis acepção da sua pessoa? Contendereis por Deus?\" (13:7-8) — fazer acepção da pessoa é o que a lei proibia ao juiz (Lv 19:15; Dt 16:19), e Jó acusa os três de puxarem o processo para o lado do mais forte, como advogados que sabem quem paga. E o aviso é sério: \"Certamente vos repreenderá, se em oculto fizerdes acepção de pessoas\" (13:10) — palavra que se cumpriu ao pé da letra em 42:7. Junto deles está a figura que Jó vê do outro lado do processo, o escrivão do céu: \"Por que escreves contra mim coisas amargas e me fazes herdar as culpas da minha mocidade?\" (13:26). Ele não pede absolvição barata; pede o auto, a peça, a lista — qualquer coisa que se possa ler e responder.",
    },
    homem: {
      title: "O hipócrita que não virá perante ele, no versículo em que Jó aposta a vida em Deus",
      subtitle: "Jó 13:15-16 • \"Ainda que ele me mate, nele esperarei\"",
      text: "\"Ainda que ele me mate, nele esperarei; contudo os meus caminhos defenderei diante dele. Também ele será a minha salvação; porém o hipócrita não virá perante ele\" (Jó 13:15-16). É o ponto mais alto do bloco inteiro, e convém notar que as duas metades da frase andam juntas: Jó não desiste de discutir com Deus, mas o único a quem ele confia o desfecho é o próprio Deus com quem discute. A figura em cena é o contraste que ele mesmo escolhe — o hipócrita, o homem de dois rostos que jamais se aproximaria de um tribunal onde tudo é sabido. Jó está dizendo: se eu fosse o que vocês dizem que sou, seria o último a querer chegar perto dele; o meu desejo de comparecer é a minha defesa. E é isso que separa este versículo de qualquer resignação: \"Eis que já tenho ordenado a minha causa, e sei que serei achado justo\" (13:18). O mesmo homem que quer o processo já sabe onde a esperança se apoia, e o dirá em cheio poucos capítulos depois: \"eu sei que o meu Redentor vive, e que por fim se levantará sobre a terra\" (19:25).",
    },
    servo: {
      title: "O guarda que põe os pés de Jó no tronco e marca os sinais dos seus passos",
      subtitle: "Jó 13:27 • a vigilância descrita como carceragem",
      text: "\"Também pões os meus pés no tronco, e observas todos os meus caminhos, e marcas os sinais dos meus pés\" (Jó 13:27). O tronco é o cepo de madeira em que se prendiam os pés do preso — o mesmo instrumento em que puseram Jeremias (Jr 20:2) e, séculos depois, Paulo e Silas em Filipos, quando o carcereiro lhes \"segurou os pés no tronco\" (At 16:24). O servo em cena é esse carcereiro: o homem que fecha a madeira sobre os tornozelos e depois passa a noite conferindo as marcas de quem não pode ir a lugar nenhum. Jó usa a imagem para descrever o cuidado de Deus pelo avesso: o que em outros lugares é consolo — \"Tu sabes o meu assentar e o meu levantar\" (Sl 139:2) — aqui é sentinela em cima de um homem imobilizado. E ele já dissera a mesma coisa com outra figura, três capítulos antes: \"Sou eu porventura o mar, ou a baleia, para que me ponhas uma guarda?\" (7:12). Vigiado, marcado e preso, sem que ninguém lhe diga do que é acusado — é essa a queixa que ele quer levar a juízo.",
    },
  },

  // ----------------------------------------------------------------- Jó 14
  14: {
    homem: {
      title: "O homem nascido da mulher, que sai como a flor e murcha e foge como a sombra; o lenhador diante da árvore cortada que ainda se renova; e o que se deita e não se levanta até que não haja mais céus",
      subtitle: "Jó 14:1-2,7-12 • o capítulo em que Jó pergunta se, morrendo o homem, tornará a viver",
      text: "\"O homem, nascido da mulher, é de poucos dias e farto de inquietação. Sai como a flor, e murcha; foge também como a sombra, e não permanece\" (Jó 14:1-2). Duas imagens e nenhuma delas dura até o fim do dia: a flor do campo, que a Escritura reencontra em \"toda a carne é erva e toda a sua beleza como a flor do campo\" (Is 40:6; cf. 1Pe 1:24; Tg 1:10-11), e a sombra que se estica e some, que o salmista também escolheu — \"Os meus dias são como a sombra que declina\" (Sl 102:11). Contra isso Jó põe o lenhador e o cepo, e este é o coração do capítulo: \"Porque há esperança para a árvore que, se for cortada, ainda se renovará, e não cessarão os seus renovos. Se envelhecer na terra a sua raiz, e o seu tronco morrer no pó, ao cheiro das águas brotará, e dará ramos como uma planta\" (14:7-9). A árvore tem uma segunda chance que o homem não tem: \"Porém, morto o homem, é consumido; sim, rendendo o homem o espírito, então onde está ele?\" (14:10), e \"assim o homem se deita, e não se levanta; até que não haja mais céus, não acordará\" (14:12). E, no meio da negativa, escapa a pergunta que a Escritura levaria séculos para responder: \"Morrendo o homem, porventura tornará a viver? Todos os dias de meu combate esperaria, até que viesse a minha mudança\" (14:14). A resposta chega em Daniel — \"muitos dos que dormem no pó da terra ressuscitarão\" (Dn 12:2) — e no Cordeiro que fez do cepo cortado uma raiz viva.",
    },
    mulherComum: {
      title: "A mulher de quem nasce o homem de poucos dias e farto de inquietação",
      subtitle: "Jó 14:1,4 • a origem que o capítulo põe no primeiro verso",
      text: "\"O homem, nascido da mulher, é de poucos dias e farto de inquietação\" (Jó 14:1). A expressão \"nascido da mulher\" atravessa o livro sempre com o mesmo peso — Elifaz a usa em 15:14 e Bildade em 25:4, \"como seria puro aquele que nasce de mulher?\" — e não é desprezo pela mãe: é a maneira antiga de dizer HOMEM, criatura, o que veio ao mundo por parto e portanto está no relógio desde o primeiro minuto. A mulher em cena é essa origem: a que dá à luz um filho de dias contados e sabe, antes de qualquer teólogo, o preço que a vida custa para começar. Do nascimento Jó tira em seguida a pergunta da impureza herdada: \"Quem do imundo tirará o puro? Ninguém\" (14:4) — não uma acusação contra a mãe, mas a constatação de que ninguém escapa do que já vem no material. É a mesma linha que Davi confessa no salmo do arrependimento (Sl 51:5) e a que Paulo desata pelo outro lado, quando escreve que Deus \"enviou seu Filho, nascido de mulher\" (Gl 4:4) — a única vez em que a frase de Jó 14:1 muda de sentido.",
    },
    multidao: {
      title: "O povo de Uz que honra os filhos de um homem sem que ele o saiba",
      subtitle: "Jó 14:21 • a praça vista por quem já morreu",
      text: "\"Os seus filhos recebem honra, sem que ele o saiba; são humilhados, sem que ele o perceba\" (Jó 14:21). O quadro é a praça da cidade em dia de acontecimento — um filho subindo na estima de todos, ou caindo na vergonha de todos — e um pai que não está mais lá para ver nem uma coisa nem outra. Jó está dizendo o que a morte tira além da vida: tira a notícia. Não é só que o morto acaba; é que o mundo continua sem ele e não lhe manda recado. E há uma dor a mais escondida na escolha da imagem: quem fala é um homem cujos dez filhos morreram antes dele (1:18-19), e que portanto está descrevendo, ao contrário, a única coisa pior do que não ver os filhos serem honrados — ter visto a casa cair sobre eles. O versículo seguinte fecha o capítulo sem consolo nenhum: \"Mas a sua carne nele tem dores, e a sua alma nele lamenta\" (14:22). É esta multidão indiferente, seguindo a sua vida na praça, que dá a medida do isolamento em que o livro deixa Jó no fim da sua terceira fala.",
    },
    servo: {
      title: "O jornaleiro que espera o contentamento do seu dia, o oleiro da obra de tuas mãos, o guarda que amontoa os sacos das iniquidades, o oficial que conta os passos e o coveiro do homem consumido",
      subtitle: "Jó 14:6,10,15-17 • os ofícios em que Jó traduz o trato de Deus com ele",
      text: "\"Desvia-te dele, para que tenha repouso, até que, como o jornaleiro, tenha contentamento no seu dia\" (Jó 14:6). Volta o diarista do capítulo 7 e volta pelo lado do descanso: tudo o que Jó pede é o fim do turno, a hora em que o trabalhador para e recebe — a paga que a lei mandava não reter até o dia seguinte (Lv 19:13; Dt 24:15). Ao lado dele está o oleiro, na única frase carinhosa do capítulo: \"Chamar-me-ias, e eu te responderia, e terias afeto à obra de tuas mãos\" (14:15) — o mesmo barro de 10:9 e o mesmo ofício com que Isaías descreve a aliança inteira: \"nós o barro e tu o nosso oleiro; e todos nós a obra das tuas mãos\" (Is 64:8). Depois o quadro endurece em dois servos de repartição: o guarda do depósito, porque \"a minha transgressão está selada num saco, e amontoas as minhas iniqüidades\" (14:17) — sacos lacrados que se empilham e ninguém abre —, e o fiscal que anota tudo: \"Mas agora contas os meus passos; porventura não vigias sobre o meu pecado?\" (14:16). E, no fim da fila, o coveiro, que é o único que ainda tem serviço a fazer com o corpo de \"morto o homem, é consumido; sim, rendendo o homem o espírito, então onde está ele?\" (14:10).",
    },
  },
};
