// Fichas ESPECÍFICAS por (capítulo → papel) de JÓ 15–28.
// O segundo e o terceiro ciclo do debate, e o poema da sabedoria que os fecha.
// O palco de Jó quase nunca mostra os quatro homens sentados na cinza: mostra o
// que a fala VÊ. Cada versículo de discurso virou o quadro da sua própria
// imagem, e por isso o figurante de um beat não é "um homem do povo" — é a
// FIGURA DAQUELA IMAGEM: o ímpio de pescoço engrossado que Elifaz desenha, o
// flecheiro que cerca o alvo, o primogênito da morte, a viúva despedida vazia
// da porta, o pobre que sai à obra como jumento montês, o mineiro pendurado no
// poço. As fichas abaixo dizem de que imagem cada figura é, quem a disse e o
// que ela quer dizer no argumento — porque num livro de discursos é o argumento
// que é a ação.
//
// Nota de direção: em nenhum destes catorze capítulos há `by: "deus"`. Deus não
// fala em Jó 15–28; a voz do céu só volta no capítulo 38, do meio do redemoinho.
// Todos os balões daqui são de Jó, de Elifaz, de Bildade e de Zofar, sempre
// pelo `id` — e as fichas dos quatro vivem em CHAR_INFO, não aqui.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_15_28: Record<number, Record<string, StageInfo>> = {
  // ----------------------------------------------------------------- Jó 15
  15: {
    anciao: {
      title: "Os encanecidos e idosos do portão, mais idosos do que o pai de Jó, e os sábios que anunciaram o que ouviram de seus pais",
      subtitle: "Jó 15:10,18 • as cabeças brancas que Elifaz chama para a sua banca de testemunhas",
      text: "Quando Elifaz volta a falar, a cortesia do capítulo 4 acabou e a argumentação também: o que ele tem agora é idade. \"Também há entre nós encanecidos e idosos, muito mais idosos do que teu pai\" (Jó 15:10) — e não é figura de retórica, é a autoridade inteira do discurso. Estes velhos são os anciãos do banco do portão, o lugar onde no Oriente antigo se julgava e se ensinava (Rt 4:1-2; Jó 29:7-8), e Elifaz põe-nos ali para valerem por argumento. Ao lado deles estão os outros a quem ele apela, uma geração mais atrás ainda: \"O que os sábios anunciaram, ouvindo-o de seus pais, e o não ocultaram; aos quais somente se dera a terra, e nenhum estranho passou por entre eles\" (15:18-19) — uma tradição pura, sem contaminação de fora, que ele opõe à experiência de um homem só. É a tese central do amigo: o que os pais disseram basta, e quem contradiz a tradição é que está errado. O livro vai dar-lhe a resposta mais dura possível no capítulo 42, quando Deus disser aos três: \"a minha ira se acendeu contra ti... porque não falastes de mim o que era reto\" (Jó 42:7). Um deles, em cena, é o velho de quem Elifaz diz que enche do vento oriental o ventre — a acusação de 15:2 devolvida em figura."
    },
    homem: {
      title: "O ímpio do retrato de Elifaz: o que bebe a iniquidade como a água, o que anda vagueando por pão, o de rosto coberto de gordura, o que habitou em cidades assoladas — e o vinhateiro da vide que sacode as uvas verdes",
      subtitle: "Jó 15:16-34 • as doze figuras do quadro que Elifaz pinta para Jó se ver dentro",
      text: "Dois terços do capítulo são um só retrato, e ele é longo e feio de propósito: Elifaz quer que Jó se reconheça nele. É o homem \"abominável e corrupto\" que \"bebe a iniqüidade como a água\" (15:16), com a naturalidade de quem tem sede. É o atormentado de 15:20-24: \"Todos os dias o ímpio é atormentado\", \"o sonido dos horrores está nos seus ouvidos; até na paz lhe sobrevém o assolador\", \"não crê que tornará das trevas, mas que o espera a espada\", e \"anda vagueando por pão, dizendo: Onde está?\". É o que se atreveu contra o alto: \"porque estendeu a sua mão contra Deus, e contra o Todo-Poderoso se embraveceu\" — arremetendo \"com a dura cerviz, e contra os pontos grossos dos seus escudos\" (15:25-26), a cerviz dura de quem investe contra uma parede de escudos. É o gordo de 15:27, \"porquanto cobriu o seu rosto com a sua gordura, e criou gordura nas ilhargas\". É o que se instalou onde não se mora: \"habitou em cidades assoladas, em casas em que ninguém morava, que estavam a ponto de fazer-se montões de ruínas\" (15:28). E é, no fim, o vinhateiro da parábola agrícola com que Elifaz fecha: \"Sacudirá as suas uvas verdes, como as da vide, e deixará cair a sua flor como a oliveira\" (15:33) — a colheita perdida antes de amadurecer, duas vezes na mesma imagem. Nada disto descreve o Jó do capítulo 1, que o próprio Deus chamou \"íntegro e reto\" (Jó 1:8); é o retrato de um homem que Elifaz precisa que exista para que a sua doutrina se sustente."
    },
    mulherComum: {
      title: "A mulher de quem nasce o que não é justo",
      subtitle: "Jó 15:14 • a mãe do argumento que corta pela raiz",
      text: "\"Que é o homem, para que seja puro? E o que nasce da mulher, para ser justo?\" (Jó 15:14). É a segunda vez que Elifaz usa esta frase — já a tinha ouvido, diz ele, na visão do capítulo 4: \"Seria porventura o homem mais justo do que Deus?\" (Jó 4:17) — e é a mesma que Bildade repetirá no capítulo 25 e que o próprio Jó já dissera de outro modo em 14:1, \"o homem, nascido da mulher, é de poucos dias e farto de inquietação\". A mulher em cena não é acusada de nada; ela é o começo de uma cadeia que o argumento quer fechar antes de discutir o caso concreto. O passo seguinte é o de Elifaz: \"eis que ele não confia nos seus santos, e nem os céus são puros aos seus olhos\" (15:15) — se nem o céu passa no exame, um filho de mulher não tem hipótese. O raciocínio é verdadeiro e a aplicação é falsa: Davi dirá o mesmo em Sl 51:5, e o Novo Testamento nasce exatamente dali — \"nascido de mulher\" (Gl 4:4) é a descrição de Cristo, e o único a quem a frase de Elifaz não alcança."
    },
    rei: {
      title: "O rei preparado para a peleja e o tirano para quem se reserva um certo número de anos",
      subtitle: "Jó 15:20,24 • as duas figuras de poder que Elifaz usa como imagem do medo",
      text: "Elifaz não tem um rei na cena de Uz — tem duas figuras de coroa dentro do seu próprio discurso, e as duas são medo. A primeira é o prazo contado: \"Todos os dias o ímpio é atormentado, e se reserva, para o tirano, um certo número de anos\" (Jó 15:20) — o homem que manda e que sabe, exatamente como o resto do mundo sabe, que os anos dele estão numerados por outro. A segunda é a angústia armada: \"Assombram-no a angústia e a tribulação; prevalecem contra ele, como o rei preparado para a peleja\" (15:24). Não é um rei que ataca: é o aparato do rei — o carro atrelado, a lança, o estandarte — usado como medida do terror que cai sobre um homem sozinho. Que Elifaz precise de imagens de guerra para descrever a consciência de um ímpio diz muito do que ele acha que Jó tem por dentro. E o livro já mostrou, no capítulo 1, quem de fato veio de fora com tropa: sabeus e caldeus, em três levas (Jó 1:15-17) — desastre real, não parábola."
    },
    servo: {
      title: "O ouvinte da praça a quem a língua dos astutos se dirige",
      subtitle: "Jó 15:5-6 • a testemunha pública da acusação, porque a acusação é pública",
      text: "\"Porque a tua boca declara a tua iniqüidade; e tu escolhes a língua dos astutos. A tua boca te condena, e não eu, e os teus lábios testificam contra ti\" (Jó 15:5-6). O quadro é uma praça de propósito: Elifaz não está a censurar um amigo em particular, está a fazer com que o próprio réu forneça a prova diante de terceiros. Este servo é o homem comum que passa, ouve e leva embora o que ouviu — e a humilhação de Jó, que no capítulo 17 se queixará de ter virado \"um provérbio dos povos\" (17:6), começa em cenas exatamente assim. A técnica é antiga e o livro conhece-a: o mesmo Jó dirá aos três \"todos vós sois consoladores molestos\" (16:2), e Deus, no fim, mandará que sejam eles a levar sete novilhos e sete carneiros e a pedir que Jó ore por eles (Jó 42:8). O que se ouviu na praça teve de ser desdito na praça."
    }
  },

  // ----------------------------------------------------------------- Jó 16
  16: {
    homem: {
      title: "Os flecheiros que cercam Jó pela direita e pela esquerda, o valente que arremete com brecha sobre brecha, o que range os dentes e o que fere nos queixos com desprezo",
      subtitle: "Jó 16:9-14 • o cerco de figuras em que Jó descreve o que lhe está a acontecer",
      text: "Este é o capítulo em que o livro faz a sua curva, e o meio dele é o quadro mais violento do bloco. Jó não descreve doença: descreve um cerco militar. \"Descansado estava eu, porém ele me quebrantou; e pegou-me pela cerviz, e me despedaçou; também me pôs por seu alvo. Cercam-me os seus flecheiros; atravessa-me os rins, e não me poupa, e o meu fel derrama sobre a terra\" (Jó 16:12-13) — um homem posto de pé no meio do campo para servir de alvo, com os arqueiros em roda. Depois vem o assalto à muralha: \"Fere-me com ferimento sobre ferimento; arremete contra mim como um valente\" (16:14), brecha sobre brecha, como quem abre um muro. À volta disso estão os homens de carne e osso: \"rangeu os seus dentes contra mim; aguça o meu adversário os seus olhos contra mim. Abrem a sua boca contra mim; com desprezo me feriram nos queixos, e contra mim se ajuntam todos\" (16:9-10) — matilha, não tribunal. E há a acusação mais pesada de todas, dita sem rodeios: \"Entrega-me Deus ao perverso, e nas mãos dos ímpios me faz cair\" (16:11). Nenhuma destas figuras é Deus, que o livro nunca desenha; são o que a fala vê. O bofetão no queixo e a boca aberta contra o justo voltarão, palavra por palavra, no Servo de Is 50:6 e no pátio de Mc 14:65."
    },
    servo: {
      title: "O servo da companhia de Jó que foi assolada e o que se ajunta com os outros contra ele",
      subtitle: "Jó 16:7,10 • os dois lados da casa que já não existe",
      text: "\"Na verdade, agora tu me tens fatigado; tu assolaste toda a minha companhia\" (Jó 16:7). A palavra é de casa, não de exército: a companhia de Jó era a gente do capítulo 1 — os moços que araram com as quinhentas juntas de bois, os que guardavam os três mil camelos, os que morreram ao fio da espada e de que só escapou um de cada vez para trazer a notícia (Jó 1:14-19). Um destes servos é o que sobrou; o quadro dá-lhe o que restou da casa, que é um montão. O outro está do lado contrário, e dói mais: \"contra mim se ajuntam todos\" (16:10). Gente que comia do pão dele agora faz parte da roda que zomba — o mesmo que Jó dirá por extenso no capítulo 19, \"os meus domésticos e as minhas servas me reputaram como um estranho\" (19:15), e no capítulo 30, \"agora, porém, se riem de mim os de menos idade do que eu\" (30:1). Perder a fazenda é uma coisa; ver os próprios criados passar para a fila dos escarnecedores é outra."
    }
  },

  // ----------------------------------------------------------------- Jó 17
  17: {
    homem: {
      title: "O zombador que cerca Jó na praça, o que denuncia os seus amigos para serem despojados — e os retos que pasmarão, o inocente que se levantará e o justo que seguirá o seu caminho firmemente",
      subtitle: "Jó 17:2-9 • a roda que ri e os três versículos limpos no meio dela",
      text: "\"Deveras estou cercado de zombadores, e os meus olhos contemplam as suas provocações\" (Jó 17:2), e o pior é o lugar: \"a mim me pôs por um provérbio dos povos, de modo que me tornei uma abominação para eles\" (17:6). Virar provérbio é ser dito por gente que nunca o conheceu — a desgraça de um homem transformada em ditado de feira. Ao lado dos zombadores está o delator, num provérbio que Jó devolve aos amigos: \"O que denuncia os seus amigos, a fim de serem despojados, também os olhos de seus filhos desfalecerão\" (17:5); é uma acusação direta a quem está sentado na cinza com ele, negociando a reputação dele em troca de ter razão. E então, no meio do capítulo mais escuro do bloco, abrem-se três linhas de luz que o livro não explica e não retira: \"Os retos pasmarão disto, e o inocente se levantará contra o hipócrita. E o justo seguirá o seu caminho firmemente, e o puro de mãos irá crescendo em força\" (17:8-9). É Jó a afirmar, no fundo do poço, que a integridade continua a valer a pena para outros — a mesma teimosia que dirá em 27:5, \"até que eu expire, nunca apartarei de mim a minha integridade\"."
    },
    servo: {
      title: "O segundo zombador cujas provocações Jó contempla e o filho do delator cujos olhos desfalecerão",
      subtitle: "Jó 17:2,5 • quem está de pé em volta de um homem que só tem a sepultura diante de si",
      text: "O capítulo abre com a frase mais curta e mais seca do bloco: \"O meu espírito se vai consumindo, os meus dias se vão apagando, e só tenho perante mim a sepultura\" (Jó 17:1). É em volta desse homem que estas figuras estão. Uma é o segundo da roda dos escarnecedores, aquele cujas provocações ele diz contemplar de olhos abertos (17:2) — não passam por ele, ele vê-as uma a uma. A outra é o filho do delator, que não fez nada e entra na frase porque o provérbio antigo cobrava a conta na geração seguinte: \"também os olhos de seus filhos desfalecerão\" (17:5). É a mesma lógica que os três amigos aplicam a Jó o tempo todo — os filhos dele morreram, logo houve pecado — e que Jó não aceita: no capítulo 21 exigirá que Deus faça o ímpio beber o próprio cálice em vez de o guardar para os filhos (21:19-20). Aqui ele usa a arma dos adversários contra os adversários, e depois volta a estender a cama nas trevas: \"Se eu esperar, a sepultura será a minha casa\" (17:13)."
    }
  },

  // ----------------------------------------------------------------- Jó 18
  18: {
    homem: {
      title: "O ímpio de Bildade e as armadilhas que o esperam: o que por seus próprios pés é lançado na rede, o primogênito da morte, os assombros que o espantam de todos os lados, e os do ocidente e do oriente que se espantam do seu dia",
      subtitle: "Jó 18:5-21 • um capítulo inteiro de ciladas, e uma só figura no meio delas",
      text: "Bildade responde com um capítulo que é quase todo caça: rede, malha, laço, corda e arapuca, e um homem no meio. \"Porque por seus próprios pés é lançado na rede, e andará nos fios enredados. O laço o apanhará pelo calcanhar, e a armadilha o prenderá. Está escondida debaixo da terra uma corda, e uma armadilha na vereda\" (Jó 18:8-10). Repare em quem arma e em quem anda: ninguém o empurra, ele entra por si. Antes disso apagou-se-lhe a casa — \"a luz se escurecerá nas suas tendas, e a sua lâmpada sobre ele se apagará\" (18:6) —, e é por isso que, no beat desse versículo, o candeeiro teve de sair de cena: o motor desenha sempre a chama acesa, e com ele em cena a luz do ímpio continuava a arder no versículo que diz que ela se apaga. Depois vêm os assombros, que \"o espantarão de todos os lados, e o perseguirão a cada passo\" (18:11), e a figura mais estranha do livro: \"sim, o primogênito da morte devorará os seus membros\" (18:13) — a doença personificada como filho mais velho da própria Morte, e por isso desenhada como homem de veste escura, nunca como mensageiro de asas. O fim é o apagamento do nome: \"a sua memória perecerá da terra, e pelas praças não terá nome\" (18:17), \"não terá filho nem neto entre o seu povo\" (18:19) — dito na cara de um homem que acabara de enterrar dez filhos. Do dia dele espantam-se \"os do ocidente\" e \"os do oriente\" (18:20): o mundo inteiro comenta, e ninguém o socorre."
    },
    rebanho: {
      title: "O rebanho a que Bildade se diz igualado diante de Jó",
      subtitle: "Jó 18:3 • \"Por que somos tratados como animais, e como imundos aos vossos olhos?\"",
      text: "\"Por que somos tratados como animais, e como imundos aos vossos olhos?\" (Jó 18:3). A cena põe no quadro exatamente a ofensa de Bildade: a malhada de bichos com que ele se sente comparado. Vale reparar no que o ofende — não a injustiça feita a Jó, nem os dez túmulos, nem a doença: o que o move a responder é ter sido tratado sem consideração no debate. É a queixa de quem está a perder a discussão. E há uma ironia que o livro guarda para o fim: quando Deus finalmente falar do redemoinho, será para desfilar animais diante dos homens — a corça, o jumento montês, o avestruz, o cavalo, o falcão, o boi montês (Jó 39) —, e o argumento será justamente que o homem não os entende nem os governa. Bildade acha ofensivo ser posto ao lado de um rebanho; quatro discursos depois, os rebanhos é que darão a lição."
    },
    servo: {
      title: "O moço da praça que nunca ouviu o nome do ímpio e o morador estranho que fica na sua tenda",
      subtitle: "Jó 18:15,17 • os dois figurantes do apagamento",
      text: "Bildade fecha o retrato com duas figuras que dizem o mesmo por lados opostos. A primeira mora onde não é dono: \"Morará na sua mesma tenda, o que não lhe pertence; espalhar-se-á enxofre sobre a sua habitação\" (Jó 18:15) — um estranho instalado na casa de um homem que ainda está vivo para ver. O enxofre é palavra pesada e Bildade sabe-o: é o de Sodoma e Gomorra (Gn 19:24), o sinal de terra que não torna a dar fruto (Dt 29:23). A segunda figura é o moço do largo, e é a mais cruel: \"a sua memória perecerá da terra, e pelas praças não terá nome\" (18:17). Um rapaz que passa e a quem aquele nome não diz nada — o modo mais completo de um homem acabar. Bildade diz isto diante de alguém cuja casa caiu sobre os filhos num só dia (Jó 1:19), e o livro deixa a crueldade sem comentário, porque a resposta virá de outra boca: no capítulo 19, Jó pedirá que as suas palavras sejam gravadas na rocha para sempre (19:23-24), que é a resposta exata a quem lhe prometeu esquecimento."
    }
  },

  // ----------------------------------------------------------------- Jó 19
  19: {
    homem: {
      title: "Os irmãos que Deus pôs longe de Jó, os conhecidos que se apartaram como estranhos, os homens da sua confidência que o abominam e os homens de armas das tropas acampadas em redor da sua tenda",
      subtitle: "Jó 19:12-19 • o inventário do abandono, um parente de cada vez",
      text: "O capítulo do Redentor começa por um censo de perdas, feito com o cuidado de quem conta dinheiro. Primeiro o cerco: \"Juntas vieram as suas tropas, e prepararam contra mim o seu caminho, e se acamparam ao redor da minha tenda\" (Jó 19:12) — sitiado dentro de casa, como uma cidade. Depois a família, nome a nome: \"pôs longe de mim a meus irmãos, e os que me conhecem, como estranhos se apartaram de mim. Os meus parentes me deixaram, e os meus conhecidos se esqueceram de mim\" (19:13-14). E o círculo mais apertado de todos: \"Todos os homens da minha confidência me abominam, e até os que eu amava se tornaram contra mim\" (19:19) — os do conselho íntimo, os que sabiam dele o que ninguém sabia. No meio disso está a frase que sobreviveu à língua portuguesa: \"Os meus ossos se apegaram à minha pele e à minha carne, e escapei só com a pele dos meus dentes\" (19:20). Nada disto é figura: é o que acontece a um homem doente numa sociedade em que a doença era lida como sentença. E é deste chão, sem nada nas mãos, que sai o versículo 25."
    },
    mulherComum: {
      title: "A mulher de Jó, a quem o seu hálito se fez estranho, e as servas a cujos olhos ele veio a ser um estrangeiro",
      subtitle: "Jó 19:15,17 • a casa por dentro, quando o dono já não é de casa",
      text: "\"Os meus domésticos e as minhas servas me reputaram como um estranho, e vim a ser um estrangeiro aos seus olhos\" (Jó 19:15). E, um versículo adiante, a linha mais íntima do livro: \"O meu hálito se fez estranho à minha mulher; tanto que supliquei o interesse dos filhos do meu corpo\" (19:17). A mulher de Jó aparece três vezes no livro e nunca com nome: enterra dez filhos no capítulo 1, diz \"amaldiçoa a Deus, e morre\" no capítulo 2 (Jó 2:9) — a frase pela qual é lembrada e julgada há vinte e cinco séculos — e reaparece aqui, num verso em que quem se afasta é ela e quem suplica é ele. Não há condenação no texto: há uma casa em que o cheiro da doença já não se suporta. As servas são as mesmas do capítulo 1, gente da fazenda grande, e o que mudou não foi a lealdade delas — foi que o homem a quem serviam deixou de parecer o mesmo homem. Em 42:11 a casa volta a encher-se: \"então vieram a ele todos os seus irmãos, e todas as suas irmãs, e todos quantos dantes o conheceram\", e comeram pão com ele."
    },
    servo: {
      title: "O criado que não respondeu quando Jó o chamou, o doméstico que o reputou estranho e os pequeninos da viela que falam contra ele",
      subtitle: "Jó 19:16,18 • o dia em que a autoridade de um homem dentro da própria casa acaba",
      text: "\"Chamei a meu criado, e ele não me respondeu; cheguei a suplicar-lhe com a minha própria boca\" (Jó 19:16). Este é o verso em que se percebe que Jó já não é o senhor de nada: um homem que tinha \"muitíssimos os servos a seu serviço\" (Jó 1:3) chama um criado e tem de passar do chamado à súplica — e mesmo assim não é atendido. Depois vêm os meninos: \"Até os pequeninos me desprezam, e, levantando-me eu, falam contra mim\" (19:18). Crianças da viela, que aprendem o desprezo dos adultos e o dizem sem filtro; quando ele se levanta para passar, elas comentam. O capítulo 29 guardará a memória do contrário exato — \"os moços me viam, e se escondiam, e até os idosos se levantavam e se punham em pé\" (29:8) —, e o 30 dirá que agora até os filhos dos que ele não poria com os cães do seu rebanho fazem dele canção (30:1,9). Entre uma coisa e a outra não há culpa nenhuma provada: há apenas uma reputação que caiu, e uma rua que se ajustou depressa."
    }
  },

  // ----------------------------------------------------------------- Jó 20
  20: {
    homem: {
      title: "O ímpio de Zofar: o que engoliu riquezas e as vomitará, o que tem o mal doce na boca, o que oprimiu e desamparou os pobres, o que foge das armas de ferro — e o pobre que ele oprimiu",
      subtitle: "Jó 20:5-28 • o último discurso de Zofar, escrito inteiro em digestão e em armas",
      text: "Zofar fala pela última vez no livro e escolhe duas linguagens: a da comida e a da guerra. A tese está no início: \"O júbilo dos ímpios é breve, e a alegria dos hipócritas momentânea\" (Jó 20:5); o homem \"como um sonho voará, e não será achado, e será afugentado como uma visão da noite\" (20:8). Depois vem a imagem que ninguém esquece: \"Ainda que o mal lhe seja doce na boca, e ele o esconda debaixo da sua língua... contudo a sua comida se mudará nas suas entranhas; fel de áspides será interiormente\" (20:12-14). E o que ele juntou sai por onde entrou: \"Engoliu riquezas, porém vomitá-las-á; do seu ventre Deus as lançará\" (20:15). O motivo é dito sem rodeios e é o que dá peso ao discurso: \"porquanto oprimiu e desamparou os pobres, e roubou a casa que não edificou\" (20:19) — este pobre também está em cena, e é a única vítima nomeada num capítulo de acusação. O fim é armaria: \"ainda que fuja das armas de ferro, o arco de bronze o atravessará. Desembainhará a espada que sairá do seu corpo\" (20:24-25), e nem os prazeres simples lhe sobram: \"não verá as correntes, os rios e os ribeiros de mel e manteiga\" (20:17). Tudo verdadeiro em geral, e tudo dirigido ao homem errado — que é o problema do livro inteiro."
    },
    multidao: {
      title: "Os hipócritas cuja alegria dura um momento",
      subtitle: "Jó 20:5 • a única festa do discurso de Zofar, e dura um versículo",
      text: "\"O júbilo dos ímpios é breve, e a alegria dos hipócritas momentânea\" (Jó 20:5). É o único lugar deste discurso em que uma multidão cabe em cena, e cabe justamente porque o texto diz júbilo e alegria — que é como o motor sempre desenha a multidão, de braços erguidos. A tese de Zofar é temporal, não moral: ele não nega que o ímpio se alegre; nega que a alegria dure. É a doutrina da retribuição na sua forma mais crua — a prosperidade do mau é uma janela que fecha —, e é exatamente contra ela que Jó vai levantar o capítulo seguinte, com a pergunta que os três não conseguem responder: \"Por que razão vivem os ímpios, envelhecem, e ainda se robustecem em poder?\" (Jó 21:7). Entre esta festa de um versículo e as casas em paz de 21:9 está a distância entre a doutrina de gabinete e o que se vê na rua. O Salmo 73 percorre o mesmo caminho e leva o salmista ao santuário antes de achar a resposta (Sl 73:2-3,17)."
    },
    servo: {
      title: "Os filhos do ímpio que restituem os bens aos pobres e o servo que transporta as riquezas da casa",
      subtitle: "Jó 20:10,28 • quem carrega para fora o que o dono juntou",
      text: "Duas cenas de mudança, uma no princípio e outra no fim do discurso. A primeira é uma restituição feita tarde: \"Os seus filhos procurarão agradar aos pobres, e as suas mãos restituirão os seus bens\" (Jó 20:10) — a geração seguinte à porta, devolvendo o que o pai tomou, para comprar uma paz que já não é dela. A segunda é o esvaziamento: \"As riquezas de sua casa serão transportadas; no dia da sua ira todas se derramarão\" (20:28); o jumento carregado ao portão, os fardos a sair, e o dono nem aparece no quadro. Zofar está a descrever um despejo. Jó ouviu isto tudo tendo perdido a fazenda inteira em três levas num só dia (Jó 1:14-17) — o que faz da imagem menos um argumento do que uma reencenação —, e responderá no capítulo 21 com a pergunta que desmonta o mecanismo: e quando a casa do ímpio continua cheia, e ele morre \"com seus baldes cheios de leite\" (21:24), a doutrina onde fica?"
    }
  },

  // ----------------------------------------------------------------- Jó 21
  21: {
    anciao: {
      title: "O ímpio que vive, envelhece e ainda se robustece em poder",
      subtitle: "Jó 21:7 • a pergunta que vira a mesa do debate inteiro",
      text: "\"Por que razão vivem os ímpios, envelhecem, e ainda se robustecem em poder?\" (Jó 21:7). Esta cabeça branca é a resposta de Jó a três discursos seguidos: não um ímpio castigado, mas um ímpio velho, forte e respeitado, que a doutrina dos amigos não consegue explicar. É a observação, contra a teoria — e é radical, porque a teoria era a de todos: Elifaz jurara que o número de anos do tirano estava contado (15:20), Bildade que a lâmpada dele se apagaria (18:5-6) e Zofar que o júbilo dele era breve (20:5). Jó responde com um homem que ninguém consegue encaixar nisso, e leva a coisa até ao fim: eles morrem sossegados (21:23), descem à sepultura num momento sem sofrer (21:13), e o túmulo é vigiado com honras (21:32). A Escritura conhece bem este espinho: é o Salmo 73 — \"eu tinha inveja dos néscios, quando via a prosperidade dos ímpios\" (Sl 73:3) — e é Jr 12:1, \"Por que prospera o caminho dos ímpios\". O livro de Jó não fecha a questão; abre-a diante de Deus e deixa-a aberta até o capítulo 38."
    },
    homem: {
      title: "O que morre na força da sua plenitude, sossegado e tranquilo, e o que morre na amargura sem haver provado do bem; o ímpio que diz a Deus \"retira-te de nós\"; o tangedor do tamboril; e o caminhante a quem Jó manda perguntar pelos sinais",
      subtitle: "Jó 21:11-33 • dois homens que acabam no mesmo pó, e a estrada onde se confere a conta",
      text: "O centro do capítulo são dois funerais postos lado a lado. \"Um morre na força da sua plenitude, estando inteiramente sossegado e tranqüilo. Com seus baldes cheios de leite, e a medula dos seus ossos umedecida. E outro, ao contrário, morre na amargura do seu coração, não havendo provado do bem\" (Jó 21:23-25) — e então a frase que os iguala e que desmonta a doutrina inteira dos três: \"Juntamente jazem no pó, e os vermes os cobrem\" (21:26). Antes disso, a casa próspera: as crianças que saem \"como a um rebanho\", os filhos que \"andam saltando\", a voz que se levanta \"ao som do tamboril e da harpa\" (21:11-12) — e o dono, que sustenta tudo isto dizendo a Deus na cara: \"Retira-te de nós; porque não desejamos ter conhecimento dos teus caminhos. Quem é o Todo-Poderoso, para que nós o sirvamos?\" (21:14-15). Jó não inveja aquilo — \"esteja longe de mim o conselho dos ímpios!\" (21:16) —, apenas se recusa a fingir que não existe. E manda os amigos conferirem com quem anda por aí: \"Porventura não perguntastes aos que passam pelo caminho, e não conheceis os seus sinais\" (21:29). A verificação está na estrada, não no argumento."
    },
    mulherComum: {
      title: "A mulher da casa do ímpio, que tem paz e não tem temor",
      subtitle: "Jó 21:9 • \"as suas casas têm paz, sem temor\"",
      text: "\"As suas casas têm paz, sem temor; e a vara de Deus não está sobre eles\" (Jó 21:9). A mulher deste quadro é a peça mais incômoda do argumento de Jó, porque não é personagem de acusação nenhuma: é uma dona de casa tranquila, num pátio bem posto, num dia bom. O verso anterior diz que \"a sua descendência se estabelece com eles perante a sua face\" (21:8) e o seguinte que o gado não falha (21:10) — a bênção inteira do Deuteronômio a funcionar na casa de gente que declarou não querer saber de Deus. É esta a cena que os três amigos não conseguem olhar. Jó põe-na diante deles sem comentário, e é a serenidade dela que faz o argumento: se a doutrina fosse verdadeira, este pátio não podia existir. A mesma paz aparece no Salmo 73: \"Eis que estes são ímpios, e prosperam no mundo; aumentam em riquezas\" (Sl 73:12) — e ali também demorou a ser respondida."
    },
    multidao: {
      title: "As crianças do ímpio, que saem como a um rebanho e andam saltando",
      subtitle: "Jó 21:11-12 • a festa que Jó põe diante dos amigos para eles explicarem",
      text: "\"Fazem sair as suas crianças, como a um rebanho, e seus filhos andam saltando. Levantam a voz, ao som do tamboril e da harpa, e alegram-se ao som do órgão\" (Jó 21:11-12). É o único quadro de festa dos capítulos 15 a 28, e a multidão cabe aqui porque o texto literalmente diz que saltam e se alegram — que é como o motor sempre a desenha. A crueldade da cena, dentro do livro, é do tamanho do livro: quem a descreve enterrou dez filhos que estavam exatamente assim, \"comendo e bebendo vinho, em casa de seu irmão primogênito\", quando o vento do deserto derrubou a casa sobre eles (Jó 1:18-19). Jó não está a dizer que aquelas crianças mereçam menos; está a dizer aos três que a régua deles não mede o mundo real. E a resposta que Zofar e Elifaz dariam — que os filhos pagam pelo pai — Jó já a tinha recusado no versículo 19: \"Deus guarda a sua violência para seus filhos, e dá-lhe o pago, para que o conheça\", e ele quer que o pago vá ao pai, não à criança."
    },
    pastor: {
      title: "O pastor do gado do ímpio, cujo touro gera e não falha",
      subtitle: "Jó 21:10 • a malhada que a doutrina dos amigos não explica",
      text: "\"O seu touro gera, e não falha; pare a sua vaca, e não aborta\" (Jó 21:10). Este pastor cuida do gado que devia estar amaldiçoado e não está. Num mundo agrário, é este o termômetro: a fecundidade do rebanho era a medida visível do favor de Deus — o Deuteronômio promete-a a quem obedece (\"as crias das tuas vacas e das tuas ovelhas\", Dt 28:4) e ameaça retirá-la a quem não obedece (Dt 28:18). Jó aponta um curral em que tudo pare e nada se perde, na casa de quem diz a Deus \"retira-te de nós\" (21:14). O quadro é sereno de propósito, e é o argumento: não há aqui nenhum sinal de juízo para o pastor ver. Quem já perdeu tudo o que tinha em quatro horas de um dia — sete mil ovelhas, três mil camelos, quinhentas juntas de bois (Jó 1:3,14-17) — sabe reconhecer um rebanho intacto quando vê um."
    },
    rebanho: {
      title: "O gado do ímpio, o touro que gera e a vaca que não aborta",
      subtitle: "Jó 21:10 • a prosperidade que Jó manda os amigos olharem",
      text: "\"O seu touro gera, e não falha; pare a sua vaca, e não aborta\" (Jó 21:10). São bichos gordos ao sol, junto de um poço cheio, e a razão de estarem no palco é serem a prova material do argumento de Jó: a bênção agrícola inteira, a funcionar na fazenda de quem dispensou Deus por escrito. O contraste é com a manhã do capítulo 1, em que os sabeus levaram as juntas de bois e as jumentas, o fogo de Deus queimou as ovelhas e os moços, e os caldeus levaram os camelos, tudo em três notícias seguidas (Jó 1:14-17). Este rebanho é o que Jó já não tem, na mão de quem, pela doutrina dos amigos, não devia tê-lo. E é por isso que o capítulo se fecha com a resposta mais seca do livro aos três: \"Como, pois, me consolais com vaidade? Pois nas vossas respostas ainda resta a transgressão\" (21:34)."
    },
    servo: {
      title: "O filho do ímpio estabelecido perante a sua face, o renovo que cresce perante os seus olhos, o guarda que vigia o túmulo e o companheiro do caminhante que conhece os sinais",
      subtitle: "Jó 21:8,29-32 • a casa que continua e o enterro com honras",
      text: "\"A sua descendência se estabelece com eles perante a sua face; e os seus renovos perante os seus olhos\" (Jó 21:8) — o ímpio de Jó vê os filhos crescerem e os netos assentarem casa, que era a definição bíblica de vida cumprida (Sl 128:6). No fim do capítulo entra o outro figurante, e é o que mais irrita Jó: \"Finalmente é levado à sepultura, e vigiam-lhe o túmulo\" (21:32). Um guarda de honra ao pé da campa de um homem que disse a Deus \"retira-te de nós\", e a terra ainda lhe é doce: \"os torrões do vale lhe são doces, e o seguirão todos os homens\" (21:33). Entre uma coisa e outra está o companheiro do viajante, aquele que Jó manda os amigos consultar: \"Porventura não perguntastes aos que passam pelo caminho, e não conheceis os seus sinais\" (21:29). Quem anda por estradas vê muitas casas, e o que vê não confirma a doutrina de quem só fala sentado."
    }
  },

  // ----------------------------------------------------------------- Jó 22
  22: {
    anciao: {
      title: "O poderoso para quem era a terra, e que nela habitava",
      subtitle: "Jó 22:8 • o retrato do latifundiário que Elifaz cola em Jó",
      text: "\"Mas para o poderoso era a terra, e o homem tido em respeito habitava nela\" (Jó 22:8). Este é o único versículo em que Elifaz descreve o que ele imagina que Jó foi: o grande homem da região, dono do chão, o notável que a terra servia. É dito com desprezo, e é a moldura em que ele vai pendurar as acusações concretas que inventa nos versos seguintes. O incômodo é que a descrição é quase verdadeira: Jó era \"maior do que todos os do oriente\" (Jó 1:3) e sentava-se na praça com os príncipes a calar-se diante dele (29:9-10). O que Elifaz faz é converter a grandeza em prova de crime — se era grande, tomou de alguém —, e é aqui que o discurso se separa de vez do texto. O capítulo 29 vai desmentir linha a linha: \"eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse... Eu me fazia de olhos para o cego, e de pés para o coxo\" (29:12,15)."
    },
    homem: {
      title: "O cansado a quem não deram água a beber, o faminto a quem retiveram o pão, o irmão penhorado sem causa, o homem iníquo que pisou a vereda antiga e o inocente que escarnece dos ímpios",
      subtitle: "Jó 22:6-19 • os pecados concretos que Elifaz inventa, um figurante por acusação",
      text: "Este é o momento mais baixo dos três amigos: sem prova nenhuma, Elifaz passa da doutrina geral à lista de crimes específicos. \"Porque sem causa penhoraste a teus irmãos, e aos nus despojaste as vestes. Não deste ao cansado água a beber, e ao faminto retiveste o pão\" (Jó 22:6-7). Cada figura em cena é uma dessas acusações de pé: o homem sedento a quem se negou a bilha, o faminto de mãos vazias, o irmão de quem se tomou a capa em penhor — coisa que a Lei proibia expressamente devolver depois do pôr do sol (Êx 22:26-27; Dt 24:12-13). Elifaz não viu nada disto acontecer; deduziu-o do sofrimento de Jó, porque a doutrina dele exige uma causa. Depois manda-o olhar para cima — \"olha para a altura das estrelas; quão elevadas estão\" (22:12) — e para trás, à \"vereda antiga, que pisaram os homens iníquos\", os do dilúvio, \"arrebatados antes do seu tempo\" (22:15-16). E acrescenta o inocente que ri da ruína alheia (22:19), como se fosse virtude. O capítulo 31 será a resposta de Jó, ponto por ponto: \"Se retive o que os pobres desejavam, ou fiz desfalecer os olhos da viúva... o órfão não comeu dele\" (31:16-17)."
    },
    mulherComum: {
      title: "A viúva despedida vazia da porta",
      subtitle: "Jó 22:9 • a pior frase que sai da boca dos três em todo o livro",
      text: "\"As viúvas despediste vazias, e os braços dos órfãos foram quebrados\" (Jó 22:9). A viúva e o órfão são, na Lei, os dois nomes que Deus toma como seus: \"A nenhuma viúva nem órfão afligireis. Se de algum modo os afligires, e eles clamarem a mim, eu certamente ouvirei o seu clamor. E a minha ira se acenderá\" (Êx 22:22-24), e a maldição pública de Dt 27:19 cai sobre quem lhes perverte o direito. Elifaz sabe disso — é justamente por isso que escolhe esta acusação: é a mais grave que se podia fazer a um homem do Oriente antigo. E é falsa. O próprio Jó dirá no capítulo 29 que fazia \"que rejubilasse o coração da viúva\" (29:13), e no 31 chegará a chamar sobre si a maldição se mentir: \"caia do ombro a minha espádua, e separe-se o meu braço do osso\" (31:22). A mulher em cena, com o cântaro vazio no degrau, é uma acusação de pé — e é o retrato do que a doutrina da retribuição faz a quem a leva às últimas: obriga a inventar um crime para justificar uma dor."
    },
    multidao: {
      title: "Os justos que o veem e se alegram",
      subtitle: "Jó 22:19 • a alegria com a desgraça alheia, apresentada como piedade",
      text: "\"Os justos o vêem, e se alegram, e o inocente escarnece deles\" (Jó 22:19). Elifaz cita isto como coisa boa, e é aí que o discurso se denuncia: a comunidade dos direitos reunida a comemorar a ruína dos outros. É uma multidão de braços erguidos numa cena que devia ser de luto — e o que a torna insuportável é que Jó está a ouvir, sentado na cinza, na condição exata daquele de quem se ri. A Escritura julga esta alegria em vários lugares: \"quando cair o teu inimigo, não te alegres\" (Pv 24:17), e Obadias acusa Edom precisamente de se ter alegrado no dia da calamidade do irmão (Ob 12). No fim do livro estes mesmos justos terão de levar sete novilhos e sete carneiros e pedir que o homem de quem escarneceram ore por eles: \"o meu servo Jó orará por vós; porque deveras a ele aceitarei\" (Jó 42:8)."
    },
    servo: {
      title: "O órfão cujos braços foram quebrados",
      subtitle: "Jó 22:9 • o menino da segunda metade da acusação",
      text: "\"As viúvas despediste vazias, e os braços dos órfãos foram quebrados\" (Jó 22:9). O braço quebrado é a imagem exata do que se faz a quem não tem defensor: tira-se-lhe a única coisa com que se podia sustentar. No mundo do livro, o órfão sem terra e sem parente que o reclamasse era carne de penhor — e é essa a cena que Jó descreverá com todos os detalhes no capítulo 24, quando disser que \"do órfão levam o jumento\" e que \"ao orfãozinho arrancam dos peitos\" (24:3,9). A diferença é decisiva: em 24 Jó denuncia o que os ímpios fazem a estes meninos; em 22 Elifaz diz que quem lhes fez isso foi o próprio Jó. Não há uma palavra no livro que sustente a acusação, e há duas que a contradizem — a de Deus, chamando-o \"íntegro e reto\" duas vezes (Jó 1:8; 2:3), e a dele próprio: \"eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse\" (29:12)."
    }
  },

  // ----------------------------------------------------------------- Jó 24
  24: {
    anciao: {
      title: "O poderoso que Deus arrasta com a sua força",
      subtitle: "Jó 24:22-24 • o grande que também acaba cortado como cabeça de espiga",
      text: "\"Até aos poderosos arrasta com a sua força; se ele se levanta, não há vida segura\" (Jó 24:22), e o remate: \"Por um pouco se exaltam, e logo desaparecem; são abatidos, encerrados como todos os demais; e cortados como as cabeças das espigas\" (24:24). Depois de vinte versículos de denúncia social, Jó fecha o capítulo com o único consolo que consegue formular: o grande também cai — mas repare em quando. Não cai no meio do crime; cai \"por um pouco\" depois, encerrado como todos os demais, do mesmo modo e no mesmo dia que qualquer um. É precisamente o que os amigos não aceitam: eles querem uma queda que se veja e que ensine. Jó concede a queda e recusa o calendário. É a mesma resposta do Salmo 37 — \"não te indignes por causa dos malfeitores... porque cedo serão ceifados como a erva\" (Sl 37:1-2) — dita por um homem que não tem certeza nenhuma de estar vivo para ver."
    },
    homem: {
      title: "Os pobres que saem à obra como jumentos monteses, os nus que passam a noite sem roupa, os que levam os molhos e têm fome, os que pisam os lagares e têm sede — e o homicida de madrugada, o adúltero do crepúsculo e o que mina as casas nas trevas",
      subtitle: "Jó 24:2-17 • o capítulo mais social da Bíblia poética, um quadro por versículo",
      text: "Jó abre o capítulo com a pergunta de fundo — \"por que, os que o conhecem, não vêem os seus dias?\" (24:1) — e responde com um inventário do mundo tal como ele funciona. Do lado das vítimas: \"os pobres da terra juntos se escondem\" (24:4); \"como jumentos monteses no deserto, saem à sua obra, madrugando para a presa; a campina dá mantimento a eles e aos seus filhos\" (24:5) — homens reduzidos à condição de asno bravo, que caça o que come; \"ao nu fazem passar a noite sem roupa, não tendo ele coberta contra o frio. Pelas chuvas das montanhas são molhados e, não tendo refúgio, abraçam-se com as rochas\" (24:7-8); \"fazem com que os nus vão sem roupa e aos famintos tiram as espigas\" (24:10) — carregam o pão dos outros e não comem dele; \"dentro das suas paredes espremem o azeite; pisam os lagares, e ainda têm sede\" (24:11), que é o verso mais amargo do capítulo: fazem o vinho do mundo inteiro e passam sede. Do lado dos que fazem: \"de madrugada se levanta o homicida, mata o pobre e necessitado, e de noite é como o ladrão\" (24:14); o adúltero: \"Assim como o olho do adúltero aguarda o crepúsculo, dizendo: Não me verá olho nenhum; e oculta o rosto\" (24:15); e os que \"nas trevas minam as casas, que de dia se marcaram\" (24:16). E a linha que fecha o retrato desta gente: \"porque a manhã para todos eles é como sombra de morte\" (24:17) — para quem vive do escuro, o nascer do sol é o pior que pode acontecer. Nada disto está no discurso dos amigos, e é tudo verdade."
    },
    mulherComum: {
      title: "A viúva cujo boi tomam em penhor, a mãe de quem arrancam o orfãozinho dos peitos, a molhada das chuvas das montanhas que se abraça com a rocha e a estéril a quem o ímpio aflige",
      subtitle: "Jó 24:3-21 • as mulheres do inventário, uma por crime",
      text: "\"Do órfão levam o jumento; tomam em penhor o boi da viúva\" (Jó 24:3) — o boi era o arado, e tirar o boi de uma viúva é tirar-lhe a próxima colheita, não um bem. Depois: \"Ao orfãozinho arrancam dos peitos, e tomam o penhor do pobre\" (24:9), a criança de colo levada como garantia de dívida, que é a coisa mais brutal deste capítulo e talvez do livro. A terceira mulher é a das encostas: \"Pelas chuvas das montanhas são molhados e, não tendo refúgio, abraçam-se com as rochas\" (24:8) — sem casa e sem coberta, agarrada à pedra para passar a noite. E a última é a que ninguém defende: \"Aflige à estéril que não dá à luz, e à viúva não faz bem\" (24:21); numa sociedade em que o direito de uma mulher passava pelo marido e pelos filhos, a estéril e a viúva eram as duas sem ninguém para as reclamar — exatamente por isso a Lei as põe debaixo da guarda direta de Deus (Êx 22:22-24; Dt 10:18). Jó não está a acusar Deus de fazer isto: está a perguntar por que é que ele deixa. A pergunta fica em aberto até 24:12, \"e contudo Deus lho não imputa como loucura\"."
    },
    rebanho: {
      title: "O rebanho roubado que os ímpios apascentam",
      subtitle: "Jó 24:2 • gado furtado a pastar tranquilamente no pasto de outro",
      text: "\"Até os limites removem; roubam os rebanhos, e os apascentam\" (Jó 24:2). São duas ações num verso e a segunda é a que faz o retrato: não basta roubar o gado — depois levam-no a pastar à vista de todos, com a naturalidade de dono. O crime começa numa pedra fora do lugar: o marco de divisa, cuja remoção a Lei amaldiçoa em público — \"Maldito aquele que remover os limites do seu próximo\" (Dt 27:17; cf. Dt 19:14; Pv 22:28) —, justamente porque é um roubo silencioso, que ninguém vê acontecer e que muda a terra de dono para sempre. O que Jó denuncia não é a violência espetacular: é a impunidade tranquila. E é isso que o capítulo inteiro cobra: se Deus tem tempos marcados, \"por que, os que o conhecem, não vêem os seus dias?\" (24:1)."
    },
    servo: {
      title: "O órfão de quem levam o jumento, o orfãozinho arrancado dos peitos, o que espreme o azeite dentro das paredes do ímpio e o filho do pobre a quem a campina dá mantimento",
      subtitle: "Jó 24:3-11 • os pequenos do inventário, que trabalham e não comem",
      text: "\"Do órfão levam o jumento\" (Jó 24:3): não é um animal de estimação, é a única força de trabalho que um menino sem pai podia ter, e sem ela ele passa de pequeno proprietário a jornaleiro. \"Ao orfãozinho arrancam dos peitos\" (24:9) — o penhor humano, uma criança de colo tomada por dívida. \"Dentro das suas paredes espremem o azeite; pisam os lagares, e ainda têm sede\" (24:11): o trabalhador dentro da propriedade do rico, fabricando exatamente aquilo que lhe falta. E o filho do pobre, que come do que a terra dá por si: \"a campina dá mantimento a eles e aos seus filhos\" (24:5) — não o senhor, não o salário: a campina. Toda esta gente está no lado de dentro da economia e do lado de fora da mesa, e é Jó, o antigo grande da região, que a põe no palco — o mesmo que dirá em 31:13 \"se desprezei o direito do meu servo ou da minha serva, quando eles contendiam comigo\", e em 31:15 a razão: \"não nos formou do mesmo modo na madre?\""
    }
  },

  // ----------------------------------------------------------------- Jó 25
  25: {
    homem: {
      title: "O nascido de mulher que não seria puro, e o homem que é um verme",
      subtitle: "Jó 25:4-6 • o discurso mais curto do livro, e o sinal de que o debate acabou",
      text: "Bildade fala pela terceira e última vez e gasta seis versículos — depois disto, nenhum dos três volta a abrir a boca em todo o livro. É o sinal de que os argumentos se esgotaram: em vez de responder à denúncia social do capítulo 24, ele recua para a única coisa que ainda tem, a distância entre Deus e o homem. \"Como, pois, seria justo o homem para com Deus, e como seria puro aquele que nasce de mulher? Eis que até a lua não resplandece, e as estrelas não são puras aos seus olhos. E quanto menos o homem, que é um verme, e o filho do homem, que é um vermezinho!\" (Jó 25:4-6). A figura em cena é esse homem-verme, minúsculo entre duas lajes de pedra. E o mais importante: cada frase é verdadeira e nenhuma responde à pergunta. Jó nunca disse que era puro diante de Deus; disse que não tinha feito o que lhe imputavam. Reduzir um homem a verme é um modo eficaz de não ter de o ouvir — e é a última coisa que os amigos conseguem fazer. Sl 22:6 usará a mesma palavra na boca de outro sofredor: \"mas eu sou verme, e não homem\"."
    },
    mulherComum: {
      title: "A mulher de quem nasce o que não seria puro",
      subtitle: "Jó 25:4 • a mãe que Bildade põe no argumento pela terceira vez no livro",
      text: "\"Como seria puro aquele que nasce de mulher?\" (Jó 25:4). É a terceira vez que esta frase é usada nestes catorze capítulos — Elifaz em 15:14, Jó a seu modo em 14:1, e agora Bildade a fechar com ela o debate inteiro. A cena põe a mulher com o filho à porta da tenda, de noite, e é bom que ela esteja em cena: o argumento fala dela sem nunca a olhar. Não há nenhuma acusação a esta mãe; ela é apenas o elo por onde a impureza supostamente entra, num raciocínio que serve para desqualificar qualquer resposta que Jó possa dar. A Escritura conhece a verdade da frase — \"em pecado me concebeu minha mãe\" (Sl 51:5) — e conhece também o seu limite: \"nascido de mulher\" é exatamente como Paulo descreve a vinda do Filho (Gl 4:4), e é de mulher que nasce aquele que Jó, seis capítulos antes, disse que vive e há de levantar-se sobre a terra (Jó 19:25)."
    }
  },

  // ----------------------------------------------------------------- Jó 26
  26: {
    anciao: {
      title: "Aquele que não tinha sabedoria, a quem Bildade aconselhou",
      subtitle: "Jó 26:3 • a ironia com que Jó agradece o discurso de seis versículos",
      text: "\"Como aconselhaste aquele que não tinha sabedoria, e plenamente fizeste saber a causa, assim como era?\" (Jó 26:3). É sarcasmo puro, e é raro no livro: Jó agradece a Bildade um conselho que não recebeu. A cena desenha exatamente o que não aconteceu — o rolo aberto sobre a mesa da assembleia, a lamparina acesa, e o assento vazio de quem devia estar ali a ensinar. Este ancião é o próprio Jó na figura em que os amigos o puseram: o homem sem entendimento, a quem se explica o óbvio. A resposta dele às três palestras é começar, dois versículos depois, o hino mais alto do livro sobre o poder de Deus — \"o inferno está nu perante ele\" (26:6), \"suspende a terra sobre o nada\" (26:7) —, mostrando que sabe do assunto muito mais do que quem lho veio ensinar. O fecho é o desmonte cortês: \"eis que isto são apenas as orlas dos seus caminhos\" (26:14). Quem fala assim não precisava do curso."
    },
    homem: {
      title: "Aquele que não tinha força, a quem Bildade diz ter ajudado, e os mortos que tremem debaixo das águas",
      subtitle: "Jó 26:2,5 • o socorro que não houve, e o que existe no fundo do mar",
      text: "\"Como ajudaste aquele que não tinha força, e sustentaste o braço que não tinha vigor?\" (Jó 26:2) — e a cena põe no pátio o homem caído, ao meio-dia, sem ninguém a segurá-lo: o auxílio de Bildade desenhado exatamente como não aconteceu. Logo depois o capítulo muda de escala e desce ao lugar mais fundo que a poesia hebraica conhece: \"Os mortos tremem debaixo das águas, com os seus moradores\" (26:5). São os refains, as sombras dos que se foram, alojadas debaixo do grande mar — e o ponto de Jó é que nem ali há esconderijo: \"o inferno está nu perante ele, e não há coberta para a perdição\" (26:6). É a mesma afirmação do Salmo 139:8, \"se fizer no inferno a minha cama, eis que tu ali estás\", e de Am 9:2. Jó está a dizer aos amigos que o alcance de Deus, que eles usam para o esmagar, ele conhece melhor do que eles — e que isso é precisamente o que torna a sua situação insuportável, não o que a explica."
    },
    servo: {
      title: "O braço sem vigor que ninguém sustentou e o morador das águas que treme com os mortos",
      subtitle: "Jó 26:2,5 • as duas figuras do capítulo do hino cósmico",
      text: "As duas pontas do capítulo, e é uma queda enorme entre elas. A primeira é doméstica e irônica: um homem desfalecido no chão de um pátio, que é o \"braço que não tinha vigor\" a quem Bildade se gaba de ter sustentado (Jó 26:2). A segunda é cósmica: \"os mortos tremem debaixo das águas, com os seus moradores\" (26:5) — os habitantes do fundo, na antiga geografia do mundo, presos debaixo do oceano e visíveis a Deus como se não houvesse água por cima. Entre uma coisa e outra está tudo o que este capítulo faz: mostrar que quem veio dar lições sobre a grandeza de Deus não sabe do que fala. Jó estende o inventário — o norte sobre o vazio, a terra sobre o nada, as águas presas nas nuvens, as colunas do céu a tremer, o mar fendido, a serpente enroscadiça formada pela mão dele — e depois chama a tudo isso \"apenas as orlas dos seus caminhos\" (26:14)."
    }
  },

  // ----------------------------------------------------------------- Jó 27
  27: {
    homem: {
      title: "O ímpio que amontoa prata como pó, o rico que se deita e não será recolhido, o hipócrita avaro a quem Deus arranca a alma, o justo que vestirá as roupas do ímpio — e o inimigo que Jó deseja que seja como o perverso",
      subtitle: "Jó 27:7-23 • Jó jura pela sua integridade e depois usa a doutrina dos amigos contra eles",
      text: "O capítulo abre com o juramento mais firme do livro: \"até que eu expire, nunca apartarei de mim a minha integridade. À minha justiça me apegarei e não a largarei; não me reprovará o meu coração em toda a minha vida\" (Jó 27:5-6). Só então ele começa a descrever a sorte do ímpio — e a surpresa é que a descrição é dura como a de Zofar. A diferença está em quem a diz e para quê: Jó aceita que o mau acaba mal, e recusa apenas a inversão que os amigos fazem dela, a de ler para trás a partir da dor de um homem. As figuras em cena: o avarento a quem \"Deus lhe arrancar a sua alma\" e cujo clamor não será ouvido (27:8-9); o que \"amontoar prata como pó, e aparelhar roupas como lodo\" e para quem a frase seguinte é uma sentença — \"ele as aparelhará, porém o justo as vestirá, e o inocente repartirá a prata\" (27:16-17); o rico da última noite: \"Rico se deita, e não será recolhido; abre os seus olhos, e nada terá\" (27:19). E há a figura mais violenta: \"Seja como o ímpio o meu inimigo, e como o perverso o que se levantar contra mim\" (27:7) — dita a três homens sentados à frente dele, que se tinham levantado contra ele durante nove discursos. A grande imagem do capítulo é de construção: \"edificará a sua casa como a traça, e como o guarda que faz a cabana\" (27:18) — a casa de pano da traça e a barraca de quatro paus que o guarda da vinha arma para uma estação e desmancha na outra."
    },
    mulherComum: {
      title: "A viúva do ímpio, que não chorará",
      subtitle: "Jó 27:15 • o enterro sem pranto, que é o pior enterro possível",
      text: "\"Os que ficarem dele na morte serão enterrados, e as suas viúvas não chorarão\" (Jó 27:15). No mundo do livro, o pranto no funeral não era sentimento privado: era ofício e era honra — havia carpideiras, havia dias contados de luto, e não ter quem chorasse era a marca de um fim maldito. Jeremias promete o mesmo a Jeoaquim: \"Não o lamentarão, dizendo: Ai, meu irmão\" e será \"Em sepultura de jumento será sepultado\" (Jr 22:19). A dureza do quadro está no que falta nele: a cova aberta, o cântaro quebrado, e ninguém em volta. A mulher que o texto põe aqui é viúva de um homem por quem não tem lágrima nenhuma — o que diz da casa em que ela viveu mais do que qualquer acusação. E o contraste com o próprio Jó é deliberado: quando ele morrer, no último verso do livro, será \"velho e farto de dias\" (Jó 42:17), depois de ter visto \"a seus filhos, e aos filhos de seus filhos, até à quarta geração\"."
    },
    multidao: {
      title: "A gente que bate palmas e assobia contra o ímpio",
      subtitle: "Jó 27:23 • o último quadro do debate, e a única multidão que cabe nele",
      text: "\"Cada um baterá palmas contra ele e assobiará tirando-o do seu lugar\" (Jó 27:23). É o versículo que fecha o discurso, e a multidão cabe aqui porque o texto diz literalmente que se batem palmas — só que não é aplauso: no Oriente antigo bater palmas e assobiar era vaia, o gesto público de expulsar alguém da comunidade. Lamentações usa exatamente o par diante da Jerusalém arruinada: \"Todos os que passam pelo caminho batem palmas, assobiam e meneiam as suas cabeças\" (Lm 2:15), e Sofonias promete-o a Nínive (Sf 2:15). O quadro é a praça no dia seguinte, com o homem a sair pelo seu pé enquanto a cidade inteira o despede assim. O que dá espessura à cena é lembrar quem a descreve: um homem que virou \"provérbio dos povos\" (Jó 17:6) e de quem os meninos da viela falam quando ele se levanta (19:18). Jó sabe exatamente como soa este assobio, porque já o ouviu."
    },
    rei: {
      title: "O tirano que recebe a herança do Todo-Poderoso",
      subtitle: "Jó 27:13 • a porção do homem ímpio, entregue de mão beijada",
      text: "\"Esta, pois, é a porção do homem ímpio da parte de Deus, e a herança, que os tiranos receberão do Todo-Poderoso\" (Jó 27:13). Jó usa aqui, palavra por palavra, a linguagem com que Zofar tinha fechado o discurso dele — \"esta, da parte de Deus, é a porção do homem ímpio; esta é a herança que Deus lhe decretou\" (20:29) —, e é de propósito: ele devolve aos amigos a fórmula deles. O que se vê no quadro é a herança posta no chão como um espólio a repartir: as arcas, os cântaros, a espada por cima de tudo. Este rei não conquistou nada; recebeu. E o inventário que se segue é todo de perdas — os filhos para a espada e a prole que não se farta de pão (27:14), a prata que o justo vestirá (27:17), a casa que é uma cabana de guarda (27:18), a tempestade que o arrebata de noite (27:20). A diferença entre Jó e Zofar não está na descrição do fim do ímpio: está em Jó recusar que se leia a vida de um homem de trás para a frente, a partir do que lhe aconteceu."
    },
    servo: {
      title: "O filho do ímpio que é para a espada, o guarda da vinha que faz a cabana e o inocente que repartirá a prata",
      subtitle: "Jó 27:14-18 • os três figurantes da herança que ninguém quer",
      text: "\"Se os seus filhos se multiplicarem, será para a espada, e a sua prole não se fartará de pão\" (Jó 27:14) — o primeiro é o filho contado como carne de guerra, num verso em que a fecundidade deixa de ser bênção. O segundo é a figura que dá nome ao capítulo: \"edificará a sua casa como a traça, e como o guarda que faz a cabana\" (27:18). O guarda da vinha é gente real do calendário agrícola: quando o cacho amadurece, arma-se uma barraca de quatro paus e ramos no meio da vinha e alguém dorme ali até à vindima; passada a estação, desmancha-se. Isaías usa a mesma imagem para a Jerusalém abandonada, \"como a cabana na vinha\" (Is 1:8). É esse o tamanho da casa do ímpio, diz Jó: uma temporada. O terceiro é o herdeiro que ele não escolheu: \"ele as aparelhará, porém o justo as vestirá, e o inocente repartirá a prata\" (27:17) — o mesmo princípio de Pv 13:22, \"a riqueza do pecador é depositada para o justo\"."
    }
  },

  // ----------------------------------------------------------------- Jó 28
  28: {
    anciao: {
      title: "O ancião da terra dos viventes que a procurou e não a achou",
      subtitle: "Jó 28:12-13 • o velho que passou a vida a procurar e volta de mãos vazias",
      text: "\"Porém onde se achará a sabedoria, e onde está o lugar da inteligência? O homem não conhece o seu valor, e nem ela se acha na terra dos viventes\" (Jó 28:12-13). Este ancião é a resposta em pessoa à primeira metade do poema: o homem sabe cortar o monte pela raiz, sabe achar a veia da prata debaixo de trezentos metros de pedra, sabe pendurar-se num poço em lugares esquecidos do pé — e não sabe onde está a sabedoria. A engenharia chega ao fundo da terra; a sabedoria não está lá. A \"terra dos viventes\" é o mundo dos vivos, com toda a sua praça, o seu mercado e a sua experiência acumulada, e o poema diz duas vezes que ali ela não se acha (28:13,21). Só há um lugar de onde ela vem, e o verso 23 diz qual: \"Deus entende o seu caminho, e ele sabe o seu lugar\". Este velho é a figura do que Eclesiastes repetirá a vida inteira — \"apliquei o meu coração a esquadrinhar, e a informar-me com sabedoria de tudo quanto sucede debaixo do céu\" (Ec 1:13) — e do que Provérbios responde na primeira página: \"O temor do Senhor é o princípio do conhecimento\" (Pv 1:7)."
    },
    homem: {
      title: "Os mineiros do poema: o que põe fim às trevas, o que pende e oscila longe dos homens, o que revolve os montes desde as raízes, o que faz sair rios dos rochedos, o que acha o lugar da safira — e a Perdição e a Morte, que só ouviram a fama",
      subtitle: "Jó 28:3-22 • o capítulo mais desenhável do livro, e o mais antigo relato técnico de mineração da Escritura",
      text: "A primeira metade do poema é engenharia pura, e é espantosa pela data: \"Ele põe fim às trevas, e toda a extremidade ele esquadrinha, a pedra da escuridão e a da sombra da morte. Abre um poço de mina longe dos homens, em lugares esquecidos do pé; ficando pendentes longe dos homens, oscilam de um lado para outro\" (Jó 28:3-4). É o mineiro suspenso numa corda dentro de um poço vertical, longe de qualquer casa, a balançar no vazio — e não há na Bíblia outro retrato como este. Segue-se o corte transversal: \"Da terra procede o pão, mas por baixo é revolvida como por fogo\" (28:5), a lavoura em cima e a galeria em brasa por baixo. Depois a força bruta: \"Ele estende a sua mão contra o rochedo, e revolve os montes desde as suas raízes\" (28:9), e a hidráulica: \"Dos rochedos faz sair rios\" (28:10) e \"os rios tapa, e nem uma gota sai deles, e tira à luz o que estava escondido\" (28:11) — desvia o curso da água para trabalhar em seco. Este homem chega onde nenhum bicho chega: \"essa vereda a ave de rapina a ignora, e não a viram os olhos da gralha. Nunca a pisaram filhos de animais altivos, nem o feroz leão passou por ela\" (28:7-8). E, no fundo do abismo, as duas últimas figuras: \"A perdição e a morte dizem: Ouvimos com os nossos ouvidos a sua fama\" (28:22) — nem os lugares mais fundos a têm; têm apenas notícia de ouvido. O homem que fura a terra inteira não acha o que procura, e é esse o argumento."
    },
    mulherComum: {
      title: "A moradora da terra dos viventes que não conhece o valor da sabedoria e a que traz o coral e as pérolas à mesa do avaliador",
      subtitle: "Jó 28:13-18 • a cidade cheia de gente, e a sabedoria não está ali",
      text: "\"O homem não conhece o seu valor, e nem ela se acha na terra dos viventes\" (Jó 28:13). A primeira destas mulheres é a cidade inteira em figura: a porta, a torre, a banca com as romãs e as uvas, gente a comprar e a vender — toda esta vida, e o que se procura não está aqui. A segunda entra no inventário do avaliador, e traz a mercadoria mais fina que o mundo antigo conhecia: \"não se fará menção de coral nem de pérolas; porque o valor da sabedoria é melhor que o dos rubis\" (28:18). O poema faz a conta com cuidado: ouro fino, prata pesada, ouro de Ofir, ônix precioso, safira, cristal, joia de ouro fino, coral, pérolas, rubis, topázio da Etiópia, ouro puro (28:15-19). É o tesouro real de uma corte inteira, e não compra uma grama do que se procura. A mesma economia aparece em Pv 3:14-15 — \"é melhor a sua mercadoria do que artigos de prata... Mais preciosa é do que os rubis\" — e no evangelho, na pérola de grande valor por que o mercador vendeu tudo quanto tinha (Mt 13:45-46)."
    },
    rei: {
      title: "O avaliador que pesa o ouro e a prata por ela",
      subtitle: "Jó 28:15-19 • o homem da balança diante da única coisa que não tem preço",
      text: "\"Não se dará por ela ouro fino, nem se pesará prata em troca dela\" (Jó 28:15). Esta figura é a autoridade do mercado: quem determina o valor das coisas, com a balança na mão e o tesouro na mesa. O poema põe diante dele tudo o que se podia pôr — \"nem se pode comprar por ouro fino de Ofir, nem pelo precioso ônix, nem pela safira\" (28:16), \"não se lhe igualará o topázio da Etiópia, nem se pode avaliar por ouro puro\" (28:19) — e o homem da balança não consegue formar um preço. Ofir era o extremo do comércio conhecido, o destino das frotas de Salomão que voltavam com quatrocentos e vinte talentos de ouro (1Rs 9:28); o topázio da Etiópia e o ônix vinham do outro extremo. Reunir isto tudo numa mesa é reunir o poder de compra do mundo — e o poema declara-o insuficiente. É aqui que o capítulo dá a volta: se não se compra, tem de ser dado, e o verso 23 diz por quem — \"Deus entende o seu caminho, e ele sabe o seu lugar\"."
    },
    servo: {
      title: "O fundidor que refina o ouro, o ferreiro que funde o cobre da pedra, o lavrador de cuja terra procede o pão, e os que trazem o ônix e a safira de Ofir, o topázio da Etiópia e a joia de ouro fino",
      subtitle: "Jó 28:1-19 • os ofícios do poema, do fundo da mina à mesa do avaliador",
      text: "\"Na verdade, há veios de onde se extrai a prata, e lugar onde se refina o ouro. O ferro tira-se da terra, e da pedra se funde o cobre\" (Jó 28:1-2). O poema começa por uma cadeia de trabalho, e cada elo tem aqui a sua figura: o fundidor, que separa o metal da escória no fogo — a mesma operação que Jó usara cinco capítulos antes para falar de si próprio, \"provando-me ele, sairei como o ouro\" (23:10); o ferreiro do cobre, que trabalha à luz da fornalha; o lavrador da superfície, \"da terra procede o pão\" (28:5), que ara por cima da galeria sem saber o que se passa por baixo; e os servos do fim da cadeia, os que põem sobre a mesa do avaliador o ônix, a safira, o ouro de Ofir, o topázio da Etiópia e a joia de ouro fino (28:16-19). É a economia inteira de um mundo, do buraco no chão à vitrina — montada em vinte versículos para dizer, no versículo 20, que nada dali serve: \"Donde, pois, vem a sabedoria, e onde está o lugar da inteligência?\" A resposta é a última linha do capítulo, e é a única que o poema entrega de graça: \"Eis que o temor do Senhor é a sabedoria, e apartar-se do mal é a inteligência\" (28:28) — que é, palavra por palavra, a descrição que o narrador deu de Jó no primeiro versículo do livro: \"temente a Deus e desviava-se do mal\" (Jó 1:1)."
    }
  }
};
