// Fichas ESPECÍFICAS por (capítulo → papel) de NEEMIAS 1–7.
// Sete capítulos que começam num corredor de palácio persa e acabam numa cidade
// larga de espaço com pouco povo dentro dela. Não há voz do céu em nenhum
// versículo: Deus não fala uma única vez em todo o livro, e a providência
// aparece só na frase que o copeiro repete — "segundo a boa mão de Deus sobre
// mim" (Ne 2:8). O perigo da ficha aqui é o capítulo 3, que parece lista de
// nomes e é um MAPA DE OFÍCIOS dando a volta ao muro, porta a porta: o sumo
// sacerdote na porta do gado, os filhos de Hassenaá com as fechaduras e os
// ferrolhos, os nobres dos tecoítas que não submeteram a cerviz, o ourives, o
// boticário, Salum e as suas filhas, os netineus de Ofel, os mercadores da
// subida da esquina. Cada versículo tem a sua ferramenta, e a ficha tem de
// dizer qual é.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_01_07: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- Ne 1
  1: {
    homem: {
      title: "O guarda da porta da fortaleza de Susã, os homens de Judá que chegaram com Hanani, e o sobrevivente do cativeiro que ficou lá na província",
      subtitle: "Ne 1:1-3 • o mês de Quislev em Susã, e a notícia que veio pela estrada",
      text: "\"E sucedeu no mês de Quislev, no ano vigésimo, estando eu em Susã, a fortaleza\" (Ne 1:1) — é inverno, e o lugar é o mesmo palácio em que Assuero se assentara no trono do seu reino (Et 1:2). O guarda desta porta vê passar uma caravana pequena e empoeirada: \"veio Hanani, um de meus irmãos, ele e alguns de Judá\" (Ne 1:2), gente que gastou quatro meses de estrada, o mesmo tempo da subida de Esdras (Ed 7:9), só que na direção contrária. O que o copeiro pergunta não é sobre o templo, que já estava de pé havia setenta anos: pergunta \"pelos judeus que escaparam, e que restaram do cativeiro, e acerca de Jerusalém\". E a resposta, dita por estes homens, é a frase que põe o livro inteiro em movimento: \"Os restantes, que ficaram do cativeiro, lá na província estão em grande miséria e desprezo; e o muro de Jerusalém fendido e as suas portas queimadas a fogo\" (Ne 1:3). Cento e quarenta anos depois de Nabucodonosor derrubar os muros em redor de Jerusalém (2Rs 25:10), e poucos anos depois de Reum e Sinsai terem ido \"apressadamente\" impedir a obra \"à força e com violência\" (Ed 4:23), a cidade continua aberta. O sobrevivente desta cena é o homem que mora nela.",
    },
    mulherComum: {
      title: "A mulher que restou na província de Judá, entre os que escaparam do cativeiro",
      subtitle: "Ne 1:3 • do outro lado da notícia, na cidade que não tem porta que se feche",
      text: "\"Os restantes, que ficaram do cativeiro, lá na província estão em grande miséria e desprezo\" (Ne 1:3). Ela é o rosto dessa frase. Viver sem muro, no mundo antigo, não é uma questão de estética: é acordar todas as noites sabendo que qualquer bando de Samaria, de Amom ou de Asdode entra sem encontrar porta — porque as portas foram queimadas a fogo, e Jeremias já tinha visto isso acontecer: \"As suas portas caíram por terra; ele destruiu e quebrou os seus ferrolhos\" (Lm 2:9). Ao mesmo tempo, a promessa que a Escritura guardava para esta mesma cidade partia justamente da falta de muro: \"Jerusalém será habitada como as aldeias sem muros, por causa da multidão dos homens e dos animais que haverá nela. Pois eu, diz o Senhor, serei para ela um muro de fogo em redor\" (Zc 2:4-5). Entre a ruína do versículo 3 e o muro de fogo de Zacarias corre o livro todo — e ela é quem espera nesse meio, na província, sem saber que a quatro meses de distância um homem está a chorar por causa dela.",
    },
    servo: {
      title: "O servo do paço de Susã e o segundo dos homens de Judá que subiram com Hanani",
      subtitle: "Ne 1:1-2,11 • o corredor persa onde servia o copeiro do rei",
      text: "\"Estando eu em Susã, a fortaleza\" (Ne 1:1): quem trabalha aqui trabalha dentro da capital de inverno do maior império que o mundo tinha visto, e a última linha do capítulo diz o ofício do narrador sem alarde nenhum — \"Então era eu copeiro do rei\" (Ne 1:11). Copeiro é o homem que prova o vinho antes de o rei o beber; vive a poucos passos do trono e é escolhido pela confiança, não pela linhagem. O servo desta cena é do mesmo corredor: acende as lâmpadas, leva as bacias, abre as portas dos aposentos, e vê um funcionário judeu sentar-se no chão e chorar. \"E sucedeu que, ouvindo eu estas palavras, assentei-me e chorei, e lamentei por alguns dias; e estive jejuando e orando perante o Deus dos céus\" (Ne 1:4). O outro servo desta cena não é persa: é o segundo dos homens que vieram de Judá com Hanani, um viajante que acabou de descer da estrada com a notícia da cidade aberta na boca.",
    },
  },

  // ---------------------------------------------------------------- Ne 2
  2: {
    anciao: {
      title: "Os governadores dalém do rio que receberam as cartas, e os sacerdotes, os nobres e os magistrados de Jerusalém a quem Neemias ainda não tinha declarado coisa alguma",
      subtitle: "Ne 2:7-9,16 • a estrada da Síria e os três dias calados dentro da cidade",
      text: "Há dois tipos de autoridade neste capítulo, e nenhuma delas sabe o que se passa. Do lado de fora estão os governadores da satrapia: \"dêem-se-me cartas para os governadores dalém do rio, para que me permitam passar até que chegue a Judá\" (Ne 2:7), e \"Então fui aos governadores dalém do rio, e dei-lhes as cartas do rei\" (Ne 2:9) — \"dalém do rio\" é o nome oficial persa da província a oeste do Eufrates, a mesma de onde Tatenai escrevera a Dario no tempo do templo (Ed 5:3). Do lado de dentro estão os chefes de Jerusalém, e a ficha deles é o silêncio: \"E não souberam os magistrados aonde eu fora nem o que eu fazia; porque ainda nem aos judeus, nem aos sacerdotes, nem aos nobres, nem aos magistrados, nem aos mais que faziam a obra, até então tinha declarado coisa alguma\" (Ne 2:16). Três dias de boca fechada numa cidade pequena onde toda a gente se conhece. Só depois de ter visto a ruína com os próprios olhos é que ele fala — e a frase que os levanta não começa por ordem, começa por diagnóstico partilhado: \"Bem vedes vós a miséria em que estamos\" (Ne 2:17).",
    },
    cavaleiro: {
      title: "O cavaleiro da escolta que o rei Artaxerxes enviou com Neemias",
      subtitle: "Ne 2:9 • a coluna persa que sobe pela estrada, com as cartas na mão",
      text: "\"e o rei tinha enviado comigo capitàes do exército e cavaleiros\" (Ne 2:9). É um detalhe que Neemias regista e Esdras registou pelo contrário: quando o escriba subiu, envergonhou-se de pedir escolta — \"Porque tive vergonha de pedir ao rei exército e cavaleiros para nos defenderem do inimigo pelo caminho\" (Ed 8:22). Não é contradição, é ofício: Esdras subiu como sacerdote com uma oferta de prata, Neemias sobe como funcionário do império com uma comissão administrativa, e a cavalaria faz parte do pacote. Ela também serve de recado: quem vir esta coluna entrar em Jerusalém entende, sem uma palavra, que o homem que a comanda traz a assinatura de Artaxerxes atrás de si — e é exatamente por isso que Sambalate e Tobias ficam sabendo no mesmo dia, e \"lhes desagradou extremamente que alguém viesse a procurar o bem dos filhos de Israel\" (Ne 2:10).",
    },
    homem: {
      title: "Asafe, guarda da floresta do rei, o capitão do exército de Artaxerxes, o vigia do alto de Sambalate, o morador que recebeu Neemias, os poucos homens da ronda noturna e o judeu que disse Levantemo-nos, e edifiquemos",
      subtitle: "Ne 2:8-18 • da floresta real até a praça de Jerusalém, passando por uma noite às escuras",
      text: "O capítulo começa em papelada e acaba em mãos calejadas. Primeiro há Asafe, um funcionário persa que nunca mais aparece na Escritura e sem o qual não haveria portas: \"Como também uma carta para Asafe, guarda da floresta do rei, para que me dê madeira para cobrir as portas do paço da casa, para o muro da cidade\" (Ne 2:8) — e o versículo fecha com a única teologia que este livro se permite: \"E o rei mas deu, segundo a boa mão de Deus sobre mim\". Depois há a escolta e o capitão. Depois, dentro da cidade, três dias de silêncio, e então a ronda: \"E de noite me levantei, eu e poucos homens comigo, e não declarei a ninguém o que o meu Deus me pôs no coração para fazer em Jerusalém\" (Ne 2:12). Estes poucos homens são o círculo mais estreito do livro — andam pela porta do vale, pela fonte do dragão, pela porta do monturo, e chegam a um ponto em que o entulho vence a montaria: \"não havia lugar por onde pudesse passar o animal em que estava montado\" (Ne 2:14). No fim vem o homem que responde na praça: \"então disseram: Levantemo-nos, e edifiquemos. E esforçaram as suas mãos para o bem\" (Ne 2:18). Do outro lado do vale, um vigia de Sambalate vê a mesma poeira e corre a contar.",
    },
    mulherComum: {
      title: "A rainha assentada junto ao rei quando Neemias pediu para ir a Judá",
      subtitle: "Ne 2:6 • a única mulher da sala em que se decide a reconstrução de Jerusalém",
      text: "\"Então o rei me disse, estando a rainha assentada junto a ele: Quanto durará a tua viagem, e quando voltarás?\" (Ne 2:6). Meia linha, e Neemias não a deixou cair. Nenhum outro momento do livro tem uma testemunha assim registada: a rainha está presente, o que indica que não é audiência de trono cheio, é refeição, círculo íntimo, e que o copeiro está a jogar a vida num pedido feito na hora certa. Ele acabara de temer sobremaneira (Ne 2:2) e de orar no meio da frase — \"E o rei me disse: Que me pedes agora? Então orei ao Deus dos céus\" (Ne 2:4), a oração mais curta da Escritura, feita de olhos abertos entre uma pergunta e uma resposta. O que sai da sala é uma data: \"E aprouve ao rei enviar-me, apontando-lhe eu um certo tempo\". Doze anos depois o próprio livro conta quanto foi esse tempo — \"desde o ano vinte, até ao ano trinta e dois do rei Artaxerxes, doze anos\" (Ne 5:14).",
    },
    multidao: {
      title: "O povo de Jerusalém que ouviu o relato e esforçou as suas mãos para o bem",
      subtitle: "Ne 2:17-18 • a praça em que a cidade decide levantar-se",
      text: "\"Então lhes disse: Bem vedes vós a miséria em que estamos, que Jerusalém está assolada, e que as suas portas têm sido queimadas a fogo; vinde, pois, e reedifiquemos o muro de Jerusalém, e não sejamos mais um opróbrio\" (Ne 2:17). Repare em quantas vezes ele diz \"nós\": não veio de Susã dizer a esta gente o que ela devia ter feito, veio pôr-se dentro da vergonha dela. E o argumento não é estratégico, é biográfico: \"Então lhes declarei como a mão do meu Deus me fora favorável, como também as palavras do rei\" (Ne 2:18) — primeiro a mão de Deus, depois a autorização do império, nessa ordem. A resposta é uma frase de duas palavras e um gesto: \"Levantemo-nos, e edifiquemos. E esforçaram as suas mãos para o bem\". Esta mesma multidão é a que, setenta e cinco versículos adiante, estará com a espada cingida aos lombos, e é a que voltará a esta praça no capítulo 8 para ouvir a lei em pé.",
    },
    servo: {
      title: "O servo que serviu o vinho no banquete de Artaxerxes, o escriba das cartas do rei, o lenhador e o carregador da floresta real, Tobias o servo amonita, e o segundo homem da ronda noturna",
      subtitle: "Ne 2:1-12 • as mãos que servem, escrevem, cortam, carregam e conspiram",
      text: "\"Sucedeu, pois, no mês de Nisã, no ano vigésimo do rei Artaxerxes, que estava posto vinho diante dele, e eu peguei o vinho e o dei ao rei; porém eu nunca estivera triste diante dele\" (Ne 2:1). Quatro meses depois de Quislev, o copeiro faz o gesto de sempre — e desta vez deixa o rosto trair-se, o que num paço persa é indisciplina grave: \"então temi sobremaneira\" (Ne 2:2). Ao lado dele há a criadagem do banquete, e depois o escrivão que lavra as cartas para os governadores e a carta para Asafe. Na floresta real há um lenhador e um carregador — a madeira que vai cobrir as portas do muro de Jerusalém sai de um bosque do rei da Pérsia, cortada por gente que não faz ideia do que está a serrar. E há um servo que não serve: \"Tobias, o servo amonita\" (Ne 2:10), chamado assim por Neemias com desprezo calculado, porque é o segundo homem mais poderoso do outro lado desta história. Por fim, na ronda das três da manhã, um segundo homem caminha ao lado do governador pelas ruínas, sem tocha e sem dizer nada.",
    },
  },

  // ---------------------------------------------------------------- Ne 3
  3: {
    anciao: {
      title: "Eliasibe e os seus irmãos sacerdotes na porta do gado, os nobres dos tecoítas que não submeteram a cerviz, Reum filho de Bani, os sacerdotes da campina e os sacerdotes da porta dos cavalos",
      subtitle: "Ne 3:1,5,17,22,28 • a volta do muro vista do lado de quem manda",
      text: "A obra abre pelo mais alto: \"E levantou-se Eliasibe, o sumo sacerdote, com os seus irmãos, os sacerdotes, e reedificaram a porta do gado, a qual consagraram\" (Ne 3:1). O sumo sacerdote a assentar pedra é a imagem que governa o capítulo — e é também um aviso, porque o mesmo Eliasibe vai aparecer no capítulo 13 a preparar uma câmara dentro da casa de Deus para Tobias (Ne 13:4-7). Onze versículos depois, o texto guarda a única nota de vergonha da lista: \"E ao seu lado repararam os tecoítas; porém os seus nobres não submeteram a cerviz ao serviço de seu Senhor\" (Ne 3:5). Os homens de Tecoa trabalharam, e trabalharam duas vezes (Ne 3:27); os fidalgos deles não desceram do lugar — e o Espírito Santo mandou escrever isso, com nome de cidade, para sempre. Depois vêm os líderes de distrito, que aqui não governam, carregam: Reum e Hasabias pela metade de Queila (Ne 3:17), os sacerdotes que vieram da campina (Ne 3:22) e os que repararam \"desde acima da porta dos cavalos… cada um defronte da sua casa\" (Ne 3:28). A regra do capítulo inteiro é essa: quem manda reparte trecho como toda a gente.",
    },
    homem: {
      title: "Zacur filho de Imri, os filhos de Hassenaá na porta do peixe, Uziel dos ourives, Hananias filho de um dos boticários, Salum e as suas filhas, Malquias na torre dos fornos, Semaías guarda da porta oriental, os ourives e os mercadores da subida da esquina",
      subtitle: "Ne 3:2-32 • o mapa dos ofícios dando a volta à cidade, porta a porta",
      text: "Este capítulo não é uma lista de nomes: é uma planta da cidade com o ofício de cada mão. Os homens de Jericó e Zacur, filho de Imri, ao lado da porta do gado (Ne 3:2); os filhos de Hassenaá na porta do peixe, \"a qual emadeiraram, e levantaram as suas portas com as suas fechaduras e os seus ferrolhos\" (Ne 3:3) — carpintaria e serralharia no mesmo versículo. Depois vêm dois artesãos que ninguém esperaria num andaime: \"Ao seu lado reparou Uziel, filho de Haraías, um dos ourives; e ao seu lado reparou Hananias, filho de um dos boticários\" (Ne 3:8) — o homem que trabalha ouro a fio e o que mede resinas de perfume, ambos a assentar pedra até ao muro largo. Hanum e os moradores de Zanoa fazem a porta do vale e mais \"mil côvados do muro\" (Ne 3:13), o maior trecho do capítulo. Malquias, filho de Recabe, faz a porta do monturo, a saída do lixo da cidade (Ne 3:14). Baruque, filho de Zabai, é o único de quem se diz COMO trabalhou: \"reparou com grande ardor\" (Ne 3:20). E o fecho junta duas classes que não costumam aparecer juntas: \"E entre a câmara do canto e a porta do gado, repararam os ourives e os mercadores\" (Ne 3:32) — o circuito fecha exatamente onde o sumo sacerdote o abriu.",
    },
    mulherComum: {
      title: "As filhas de Salum, filho de Haloés, que repararam o muro com o pai — e as moradoras das casas defronte das quais os homens trabalhavam",
      subtitle: "Ne 3:10,12,23 • o único lugar da Bíblia em que filhas aparecem a levantar um muro",
      text: "\"E ao seu lado reparou Salum, filho de Haloés, líder da outra meia parte de Jerusalém, ele e suas filhas\" (Ne 3:12). Três palavras — \"ele e suas filhas\" — e não há paralelo em toda a Escritura: mulheres nomeadas dentro de um relatório de obra pública, no trecho de muro de um chefe de distrito, ao lado de ourives, de boticários e de sacerdotes. Não são as servas dele nem as mulheres da casa a trazer água: o versículo põe-nas como coautoras da reparação, exatamente na mesma fórmula com que nomeia todos os outros. O capítulo tem ainda um segundo tipo de mulher, que é a de quem trabalha à sua própria porta: \"defronte de sua casa e ao seu lado reparou Hatus\" (Ne 3:10), \"Depois reparou Benjamim e Hasube, defronte da sua casa; depois dele reparou Azarias, filho de Maaséias… junto à sua casa\" (Ne 3:23). Quem mora ali cozinha para o canteiro, varre o pó das pedras queimadas da soleira e vê o muro subir a três passos da janela. É a estratégia inteira de Neemias em uma linha: cada família repara o pedaço de que depende a sua própria porta.",
    },
    multidao: {
      title: "O povo que fechou a volta inteira do muro, de porta em porta, até à câmara do canto",
      subtitle: "Ne 3:32 • o circuito completo, visto de cima",
      text: "O capítulo 3 tem trinta e dois versículos e mais de quarenta trechos de obra, e a sua estrutura é geográfica: começa na porta do gado, ao norte, e roda pela porta do peixe, pela porta velha, pelo muro largo, pela torre dos fornos, pela porta do vale, pela porta do monturo, pela porta da fonte, pelos degraus da cidade de Davi, pelos sepulcros de Davi, por Ofel, pela porta das águas, pela porta dos cavalos, pela porta oriental, pela porta de Mifcade, e fecha onde tinha aberto: \"E entre a câmara do canto e a porta do gado, repararam os ourives e os mercadores\" (Ne 3:32). Ninguém edificou o muro; cada um edificou o seu bocado, e a soma dos bocados é que fez o muro. Estão ali sacerdotes, levitas, netineus, ourives, perfumistas, mercadores, gente de Jericó, de Tecoa, de Gibeom, de Mizpá, de Zanoa, de Bete-Haquerém, de Bete-Zur, de Queila — cidades inteiras a mandar turmas para reparar um muro que não é o delas. É a razão pela qual cinquenta e dois dias chegaram.",
    },
    servo: {
      title: "Os carregadores de pedra e de madeira de cada porta, os aprendizes dos ourives, os levitas de Queila, o guarda da casa das armas, os netineus que habitavam em Ofel e o servidor do templo junto aos mercadores",
      subtitle: "Ne 3:1-31 • as costas em que o muro subiu",
      text: "Por trás de cada nome do capítulo há duas ou três pessoas sem nome nenhum, e o texto deixa-as ver pelo que carregam. Cada porta reerguida traz a mesma fórmula técnica — \"a qual emadeiraram, e levantaram as suas portas com as suas fechaduras e os seus ferrolhos\" (Ne 3:3,6,13,14,15) —, e isso significa toras trazidas da floresta do rei, ferragem quente e homens de escada. Os levitas aparecem como turma de carga sob Reum e Hasabias (Ne 3:17-18). Um trecho passa \"defronte da subida à casa das armas, à esquina\" (Ne 3:19), onde há sempre um guarda. E há os netineus, que são os \"dados\" ao serviço da casa de Deus desde Davi e cuja aldeia dentro da cidade o versículo situa com precisão: \"E os servidores do templo que habitavam em Ofel, até defronte da porta das águas, para o oriente, e até à torre alta\" (Ne 3:26); um deles reaparece no fim, ao pé da porta de Mifcade, \"até à casa dos servidores do templo e mercadores\" (Ne 3:31). Estes homens tiram água e rachavam lenha desde Josué (Js 9:27) — e agora assentam pedra.",
    },
  },

  // ---------------------------------------------------------------- Ne 4
  4: {
    anciao: {
      title: "Os nobres e os magistrados de Judá a quem Neemias disse Não os temais, e os líderes que ficavam por detrás de toda a casa de Judá",
      subtitle: "Ne 4:14,16,19 • a chefia que deixa de estar à frente e passa a estar atrás",
      text: "O capítulo tem duas falas dirigidas a estes homens, e as duas os tiram do lugar confortável. A primeira é o discurso do meio da crise: \"E olhei, e levantei-me, e disse aos nobres, aos magistrados, e ao restante do povo: Não os temais; lembrai-vos do grande e terrível Senhor, e pelejai pelos vossos irmãos, vossos filhos, vossas mulheres e vossas casas\" (Ne 4:14). Note a ordem do argumento: primeiro lembrar quem é Deus, depois pelejar pelo que é concreto — irmão, filho, mulher, casa. A segunda é a lição de comando: \"e os líderes estavam por detrás de toda a casa de Judá\" (Ne 4:16). Retaguarda, não vanguarda: o chefe fica onde consegue ver a linha inteira e acudir ao ponto que ceder. E a terceira frase é o reconhecimento honesto da fraqueza da posição: \"Grande e extensa é a obra, e nós estamos apartados do muro, longe uns dos outros\" (Ne 4:19) — quatro quilómetros de perímetro e turmas pequenas espalhadas, o que faz da buzina do versículo seguinte a única coisa que mantém a cidade unida.",
    },
    homem: {
      title: "Os soldados do exército de Samaria diante de quem Sambalate escarneceu, os árabes, amonitas e asdoditas que se ligaram entre si, Judá que disse Já desfaleceram as forças, e o edificador que numa das mãos fazia a obra e na outra tinha as armas",
      subtitle: "Ne 4:2-23 • a zombaria, o desânimo de dentro e a espada cingida aos lombos",
      text: "O ataque começa por palavras, e diante de plateia: \"E falou na presença de seus irmãos, e do exército de Samaria, e disse: Que fazem estes fracos judeus? Permitir-se-lhes-á isto? Sacrificarão? Acabá-lo-ão num só dia? Vivificarão dos montões do pó as pedras que foram queimadas?\" (Ne 4:2) — e Tobias remata com a piada que ficou: \"Ainda que edifiquem, contudo, vindo uma raposa, derrubará facilmente o seu muro de pedra\" (Ne 4:3). Depois a zombaria vira conspiração de quatro frentes — Sambalate ao norte, os amonitas a leste, os árabes ao sul, os asdoditas a oeste (Ne 4:7-8) —, e Jerusalém fica cercada de todos os lados do mapa. Mas o golpe mais perigoso vem de dentro, dito por um homem de Judá no meio do estaleiro: \"Já desfaleceram as forças dos carregadores, e o pó é muito, e nós não poderemos edificar o muro\" (Ne 4:10). A resposta não é um discurso: é uma reorganização. \"Os que edificavam o muro, os que traziam as cargas e os que carregavam, cada um com uma das mãos fazia a obra e na outra tinha as armas\" (Ne 4:17), \"e os edificadores cada um trazia a sua espada cingida aos lombos, e edificavam; e o que tocava a trombeta estava junto comigo\" (Ne 4:18). Metade trabalha, metade segura lança, escudo, arco e couraça — \"desde a subida da alva até ao sair das estrelas\" (Ne 4:21).",
    },
    mulherComum: {
      title: "A mulher das aldeias que veio avisar dez vezes, e a mulher por quem se manda pelejar no muro",
      subtitle: "Ne 4:12,14 • quem trouxe o aviso e por quem se pega em armas",
      text: "Há duas mulheres neste capítulo e as duas estão no centro da defesa. A primeira é a que vive fora, no meio dos inimigos, e faz a viagem para avisar: \"E sucedeu que, vindo os judeus que habitavam entre eles, dez vezes nos disseram: De todos os lugares, tornarão contra nós\" (Ne 4:12). Dez vezes — não é um recado, é uma rede de gente das aldeias de Judá que atravessa território hostil repetidamente para dizer o que ouviu. A segunda está na frase que Neemias grita aos nobres: \"pelejai pelos vossos irmãos, vossos filhos, vossas mulheres e vossas casas\" (Ne 4:14). Ele podia ter dito \"pelejai pela cidade\", ou \"pela lei\", ou \"pelo nome de Deus\"; disse quatro palavras concretas, e três delas moram dentro da casa. O muro de Jerusalém não é, neste capítulo, um monumento nacional: é a parede que fica entre a espada de Sambalate e a mulher que está a fazer o pão a duzentos metros dali.",
    },
    servo: {
      title: "Os carregadores cujas forças desfaleceram debaixo do pó, e os servos que ficaram em Jerusalém para servirem de guarda à noite e de dia na obra",
      subtitle: "Ne 4:10,22-23 • quem carrega o entulho e quem dorme vestido",
      text: "O trabalho mais duro do muro não é assentar pedra, é tirar pedra: cento e quarenta anos de ruína viraram \"montões do pó\" (Ne 4:2), e cada metro de fundação limpo custa cestos e cestos de escombro. É por isso que o desânimo do capítulo tem nome de ofício: \"Já desfaleceram as forças dos carregadores, e o pó é muito\" (Ne 4:10). A resposta de Neemias tira a estes homens até a viagem para casa: \"Cada um com o seu servo fique em Jerusalém, para que à noite nos sirvam de guarda, e de dia na obra\" (Ne 4:22) — quem morava nas aldeias em volta deixa de descer ao fim da tarde e passa a dormir dentro da cidade. E o versículo que fecha o capítulo é dos mais físicos da Escritura: \"E nem eu, nem meus irmãos, nem meus servos, nem os homens da guarda que me seguiam largávamos as nossas vestes; cada um tinha suas armas e água\" (Ne 4:23). Semanas seguidas sem tirar a roupa, com a arma e o cantil ao lado. O governador dorme igual ao carregador.",
    },
  },

  // ---------------------------------------------------------------- Ne 5
  5: {
    anciao: {
      title: "Os nobres e os magistrados usurários com quem Neemias pelejou, os sacerdotes que tomaram o juramento, e os cento e cinquenta homens que comiam à mesa do governador",
      subtitle: "Ne 5:7,12,17 • o único capítulo em que o inimigo é de dentro",
      text: "O muro está a subir e o cerco é externo em todo o livro — menos aqui. \"E considerei comigo mesmo no meu coração; depois pelejei com os nobres e com os magistrados, e disse-lhes: Sois usurários cada um para com seu irmão. E convoquei contra eles uma grande assembléia\" (Ne 5:7). O verbo é o mesmo que ele usará contra Sambalate e contra os que profanavam o sábado: contende. E o crime não é técnico, é familiar: emprestar a juro ao próprio irmão, o que a lei proibira com todas as letras. Diante da assembleia inteira eles calam-se: \"Então se calaram, e não acharam que responder\" (Ne 5:8). A restituição é imediata e é jurada perante quem tem de a registar: \"Então chamei os sacerdotes, e os fiz jurar que fariam conforme a esta palavra\" (Ne 5:12). O mesmo estrato social reaparece doze versículos adiante do outro lado da mesa — \"Também dos judeus e dos magistrados, cento e cinqüenta homens… se punham à minha mesa\" (Ne 5:17) —, comendo à custa de um governador que se recusou a cobrar-lhes o pão do governo.",
    },
    homem: {
      title: "O pai de família que empenhou as terras, as vinhas e a casa por trigo, o que tomou emprestado para o tributo do rei, o credor que ficou com a herança do irmão e o judeu que fora resgatado das nações",
      subtitle: "Ne 5:1-11 • o clamor do povo contra os seus irmãos judeus",
      text: "\"Foi, porém, grande o clamor do povo e de suas mulheres, contra os judeus, seus irmãos\" (Ne 5:1). Seguem-se três queixas, em degraus: primeiro a fome pura — \"Nós, nossos filhos e nossas filhas, somos muitos; então tomemos trigo, para que comamos e vivamos\" (Ne 5:2); depois a hipoteca — \"As nossas terras, as nossas vinhas e as nossas casas empenhamos, para tomarmos trigo nesta fome\" (Ne 5:3); depois o imposto persa, que não perdoa ano de seca — \"Tomamos emprestado dinheiro até para o tributo do rei, sobre as nossas terras e as nossas vinhas\" (Ne 5:4). E o fundo do poço: \"eis que sujeitamos nossos filhos e nossas filhas para serem servos\" (Ne 5:5). Neemias devolve-lhes o argumento que os condena: \"Nós resgatamos os judeus, nossos irmãos, que foram vendidos às nações, segundo nossas posses; e vós outra vez venderíeis a vossos irmãos, ou vender-se-iam a nós?\" (Ne 5:8) — pagava-se resgate para tirar judeu de mão estrangeira enquanto se fabricavam escravos judeus dentro de casa. A ordem é devolver tudo no mesmo dia: \"Restituí-lhes hoje, vos peço, as suas terras, as suas vinhas, os seus olivais e as suas casas\" (Ne 5:11).",
    },
    mulherComum: {
      title: "As mulheres cujo clamor abriu o capítulo, a mãe dos filhos que eram muitos para o trigo, e a filha sujeita que já não estava no poder das mãos de seu pai",
      subtitle: "Ne 5:1-5,15 • a fome vista de dentro da casa",
      text: "\"Foi, porém, grande o clamor do povo e de suas mulheres, contra os judeus, seus irmãos\" (Ne 5:1). É o único lugar do livro em que as mulheres aparecem como parte declarada de um protesto — e faz sentido, porque a conta chega primeiro à cozinha: \"Nós, nossos filhos e nossas filhas, somos muitos; então tomemos trigo, para que comamos e vivamos\" (Ne 5:2). A frase mais dura do capítulo é sobre uma filha, e Neemias escreveu-a com a gramática do desespero: \"e até algumas de nossas filhas são tão sujeitas, que já não estão no poder de nossas mãos\" (Ne 5:5) — vendida por dívida, e sem possibilidade de resgate. A lei previa a servidão por dívida como último recurso e limitava-a; o que o capítulo mostra é a lei transformada em negócio entre parentes. E há ainda a mulher a quem os governadores anteriores tiravam o jantar: \"Mas os primeiros governadores, que foram antes de mim, oprimiram o povo, e tomaram-lhe pão e vinho\" (Ne 5:15).",
    },
    multidao: {
      title: "A congregação que disse Amém e louvou ao Senhor quando Neemias sacudiu as suas vestes",
      subtitle: "Ne 5:13 • a grande assembleia no fim do julgamento dos usurários",
      text: "\"Também sacudi as minhas vestes, e disse: Assim sacuda Deus todo o homem da sua casa e do seu trabalho que não confirmar esta palavra, e assim seja sacudido e vazio. E toda a congregação disse: Amém! E louvaram ao Senhor; e o povo fez conforme a esta palavra\" (Ne 5:13). O gesto é um sinal profético em corpo: ele segura as abas da veste, sacode-as diante de todos e deixa cair o que estava dentro — é o que Deus fará ao que não cumprir. Paulo faria o mesmo em Corinto, \"sacudiu as vestes\" (At 18:6). O que torna esta cena rara é a resposta: nem discussão, nem prazo, nem comissão. Um Amém coletivo, louvor, e execução — \"e o povo fez conforme a esta palavra\". É a única vez em toda a história de Israel em que uma reforma económica desta ordem é aceite na hora e cumprida, e não há profeta a ameaçar nem rei a impor: há um governador que abriu mão do próprio salário antes de exigir seja o que for.",
    },
    rebanho: {
      title: "O boi e as seis ovelhas escolhidas que se preparavam cada dia para a mesa do governador",
      subtitle: "Ne 5:18 • a despesa que Neemias pagou do seu bolso durante doze anos",
      text: "\"E o que se preparava para cada dia era um boi e seis ovelhas escolhidas; também aves se me preparavam e, de dez em dez dias, muito vinho de todas as espécies; e nem por isso exigi o pão do governador, porquanto a servidão deste povo era grande\" (Ne 5:18). Este é o orçamento diário de uma casa que alimenta cento e cinquenta homens mais os estrangeiros de passagem, e a conta corre doze anos seguidos — \"desde o ano vinte, até ao ano trinta e dois do rei Artaxerxes\" (Ne 5:14). O direito do cargo era cobrar tudo isso ao povo, como os governadores anteriores faziam, e mais \"quarenta siclos de prata\" (Ne 5:15). Neemias não cobrou nada, e diz porquê em quatro palavras: \"porquanto a servidão deste povo era grande\". O rebanho desta cena é o preço concreto dessa recusa, contado cabeça a cabeça, e o capítulo fecha com o primeiro dos quatro pedidos que são a assinatura do livro: \"Lembra-te de mim para bem, ó meu Deus, e de tudo quanto fiz a este povo\" (Ne 5:19).",
    },
    rei: {
      title: "Os primeiros governadores, que foram antes de Neemias, e oprimiram o povo",
      subtitle: "Ne 5:15 • o cargo como ele era antes de mudar de mão",
      text: "\"Mas os primeiros governadores, que foram antes de mim, oprimiram o povo, e tomaram-lhe pão e vinho e, além disso, quarenta siclos de prata, como também os seus servos dominavam sobre o povo; porém eu assim não fiz, por causa do temor de Deus\" (Ne 5:15). É um retrato administrativo em três camadas: o governador cobrava a subsistência da casa, cobrava por cima disso quarenta siclos de prata por dia ou por mês, e ainda deixava a criadagem tiranizar por conta própria — porque quem tem procuração do palácio tem, na prática, mão livre na província. Judá era uma província pequena entre o Eufrates e o Egito, e a linha entre imposto e extorsão dependia inteiramente do homem que assinava. Neemias corta a corrente pelo motivo que dá em cinco palavras e sem retórica nenhuma: \"por causa do temor de Deus\". Não é filantropia nem programa político; é um homem que sabe diante de quem vai prestar contas, e a diferença aparece na conta de mercearia.",
    },
    servo: {
      title: "O moço que servia à mesa do governador e preparava o boi e as aves cada dia, o escrivão que lançava a dívida sobre as terras, e os servos de Neemias que se ajuntaram todos à obra do muro",
      subtitle: "Ne 5:4,14-18 • quem escritura a dívida e quem cozinha para cento e cinquenta",
      text: "Há três criadagens neste capítulo, e elas dizem tudo. A primeira é a do credor: alguém tem de lavrar o penhor das terras e das vinhas e de cobrar o tributo do rei sobre elas (Ne 5:4) — a dívida antiga não vive de memória, vive de papel. A segunda é a dos governadores anteriores, e o texto acusa-a explicitamente: \"como também os seus servos dominavam sobre o povo\" (Ne 5:15); a opressão de um cargo distribui-se sempre pelos subalternos. A terceira é a de Neemias, e faz duas coisas ao mesmo tempo: cozinha \"um boi e seis ovelhas escolhidas\" por dia para uma mesa que ele paga do seu bolso (Ne 5:18) e vai para o andaime — \"Como também na obra deste muro fiz reparação, e terra nenhuma compramos; e todos os meus servos se ajuntaram ali à obra\" (Ne 5:16). \"Terra nenhuma compramos\" é a linha de um homem que sabia que numa fome se compra barato o campo do vizinho arruinado, e não comprou.",
    },
  },

  // ---------------------------------------------------------------- Ne 6
  6: {
    anciao: {
      title: "O sacerdote do adro que viu Neemias recusar entrar no templo, Secanias filho de Ará, sogro de Tobias, e os nobres de Judá que lhe escreviam cartas",
      subtitle: "Ne 6:11,17-18 • a rede de parentesco que atravessava o muro",
      text: "O capítulo mostra que a fronteira mais difícil de defender não era de pedra. \"Porque muitos em Judá lhe eram ajuramentados, porque era genro de Secanias filho de Ará; e seu filho Joanã se casara com a filha de Mesulão, filho de Berequias\" (Ne 6:18). Tobias, o amonita, é genro de um chefe de casa paterna cujo nome está no rol dos que voltaram do cativeiro (Ed 2:5; Ne 7:10), e o filho dele casou com a filha de um homem que reparou duas porções do muro com as próprias mãos (Ne 3:4,30). Por isso as cartas correm nos dois sentidos: \"alguns nobres de Judá escreveram muitas cartas que iam para Tobias; e as cartas de Tobias vinham para eles\" (Ne 6:17), e o que se conta ao governador são as boas ações do inimigo (Ne 6:19). Do outro lado está o adro do templo, onde um sacerdote vê Neemias parar à porta e recusar entrar para se esconder: \"Um homem como eu fugiria? E quem há, como eu, que entre no templo para que viva? De maneira nenhuma entrarei\" (Ne 6:11) — ele não é sacerdote, e sabe que o santo lugar não é abrigo de quem tem medo.",
    },
    homem: {
      title: "Semaías filho de Delaías, que estava encerrado em casa e foi subornado para o atemorizar, os profetas alugados contra Neemias, o gentio que ouviu ler a carta aberta, e os chefes das nações em redor que se abateram muito a seus próprios olhos",
      subtitle: "Ne 6:6-16 • as cinco armadilhas, e o muro acabado em cinquenta e dois dias",
      text: "O capítulo é uma sequência de emboscadas cada vez mais finas. Quatro convites para descer ao vale de Ono, e quatro vezes a mesma resposta, que é uma das grandes frases do livro: \"Faço uma grande obra, de modo que não poderei descer; por que cessaria esta obra, enquanto eu a deixasse, e fosse ter convosco?\" (Ne 6:3). Depois a chantagem pública: uma carta ABERTA, na mão de um moço, para ser lida por todos no caminho, acusando-o de se fazer rei (Ne 6:5-7). Depois a armadilha religiosa, e é a pior, porque vem de dentro do templo: \"E, entrando eu em casa de Semaías, filho de Delaías, o filho de Meetabel (que estava encerrado), disse ele: Vamos juntamente à casa de Deus, ao meio do templo, e fechemos as portas do templo; porque virão matar-te\" (Ne 6:10) — e Neemias percebe a mão que paga: \"E percebi que não era Deus quem o enviara; mas esta profecia falou contra mim, porquanto Tobias e Sambalate o subornaram\" (Ne 6:12). O fim é seco e é o clímax de todo o livro: \"Acabou-se, pois, o muro aos vinte e cinco do mês de Elul; em cinqüenta e dois dias\" (Ne 6:15). E os inimigos leram a conta certa: \"abateram-se muito a seus próprios olhos; porque reconheceram que o nosso Deus fizera esta obra\" (Ne 6:16).",
    },
    mulherComum: {
      title: "Noadia, a profetisa que procurou atemorizar Neemias, e a filha de Mesulão casada com o filho de Tobias",
      subtitle: "Ne 6:14,18 • duas mulheres do lado errado do muro",
      text: "\"Lembra-te, meu Deus, de Tobias e de Sambalate, conforme a estas suas obras, e também da profetisa Noadia, e dos mais profetas que procuraram atemorizar-me\" (Ne 6:14). É tudo o que se sabe dela, e é muito: uma mulher com ofício profético reconhecido em Jerusalém, no mesmo posto de Débora, de Hulda e de Ana, e a usá-lo para dizer a um governador que fuja. A Escritura tem profetisas que salvaram um povo e tem esta, que foi alugada contra a obra — e nomeia-a com o mesmo título, sem o suavizar. A segunda mulher é uma noiva: \"e seu filho Joanã se casara com a filha de Mesulão, filho de Berequias\" (Ne 6:18). O pai dela reparou o muro em dois trechos e tem o nome escrito na lista de honra do capítulo 3; a filha está casada com o filho do amonita que zombava desse muro. Não há acusação nenhuma contra ela no texto: ela é a prova de que a fronteira passava por dentro das famílias, e é o problema que o capítulo 13 voltará a encontrar em cima da mesa.",
    },
    multidao: {
      title: "O povo de Judá em cima do muro acabado, aos vinte e cinco dias do mês de Elul",
      subtitle: "Ne 6:15-16 • cinquenta e dois dias depois do primeiro cesto de entulho",
      text: "\"Acabou-se, pois, o muro aos vinte e cinco do mês de Elul; em cinqüenta e dois dias\" (Ne 6:15). Cinquenta e dois dias — menos de dois meses para fechar o perímetro inteiro de uma cidade que estava aberta havia cento e quarenta anos, com metade da mão de obra armada e o resto a subir e a descer cestos de escombro. O texto não celebra a engenharia: entrega o crédito na frase seguinte, e coloca-a na boca dos adversários. \"E sucedeu que, ouvindo-o todos os nossos inimigos, todos os povos que havia em redor de nós temeram, e abateram-se muito a seus próprios olhos; porque reconheceram que o nosso Deus fizera esta obra\" (Ne 6:16). Quem faz a confissão de fé deste capítulo não é Judá em cima do muro: são os que estão em baixo a olhar. E o que os abate não é o exército de Jerusalém, que não existe — é a conta dos dias.",
    },
    servo: {
      title: "Os mensageiros que foram e vieram quatro vezes ao vale de Ono, o moço que trouxe a carta aberta na sua mão, o escrivão do suborno e os portadores das cartas de Tobias",
      subtitle: "Ne 6:2-5,17-19 • as pernas e as mãos das cinco armadilhas",
      text: "Este capítulo é feito de correios. \"Sambalate e Gesém mandaram dizer-me: Vem, e congreguemo-nos juntamente nas aldeias, no vale de Ono\" (Ne 6:2) — Ono fica a um dia largo de Jerusalém, em terreno neutro e longe de qualquer socorro; o convite volta \"do mesmo modo… quatro vezes\" (Ne 6:4), e quatro vezes um mensageiro de Neemias desce a estrada com a mesma recusa. À quinta, o método muda: \"Então Sambalate ainda pela quinta vez me enviou seu servo com uma carta aberta na sua mão\" (Ne 6:5). ABERTA é o ponto: uma carta selada é diplomacia, uma carta aberta na mão de um moço é um panfleto que se lê em cada aldeia do caminho, acusando Jerusalém de rebelião contra o rei — a mesma acusação que já tinha parado a obra uma vez (Ed 4:12-13). Depois há o escrivão que lavra o pagamento a Semaías, e há os dois carteiros permanentes do capítulo, que levam cartas dos nobres de Judá a Tobias e trazem as respostas (Ne 6:17). Uma obra pode acabar em cinquenta e dois dias; um correio destes leva anos a fechar.",
    },
  },

  // ---------------------------------------------------------------- Ne 7
  7: {
    anciao: {
      title: "Os levitas estabelecidos no serviço da cidade, o escriba que leu o livro da genealogia dos que subiram primeiro, os chefes das casas paternas do rol, os sacerdotes de Jedaías, Imer, Pasur e Harim, o cantor de Asafe, o sacerdote chamado do nome de Barzilai e o governador que vedou as coisas sagradas",
      subtitle: "Ne 7:1-5,39-44,63-65,70-71 • o rolo achado dentro de uma cidade vazia",
      text: "Acabado o muro, o problema deixa de ser a pedra: \"E era a cidade larga de espaço, e grande, porém pouco povo havia dentro dela; e ainda as casas não estavam edificadas\" (Ne 7:4). É deste vazio que nasce o capítulo: \"Então o meu Deus me pôs no coração que ajuntasse os nobres, os magistrados e o povo, para registrar as genealogias; e achei o livro da genealogia dos que subiram primeiro\" (Ne 7:5). O rol que se segue é quase igual ao de Esdras 2 — mas a função é outra. Em Esdras, a lista era o manifesto de embarque de uma caravana que ia partir; aqui é um documento ACHADO, noventa anos depois, e lido dentro de muros novos para saber quem tem direito e obrigação de vir povoar a cidade. Por isso os nomes que interessam a este ancião são casas e cidades: quem é dos filhos de Parós, quem é dos homens de Anatote, qual das quatro casas sacerdotais é a sua. E por isso dói tanto o caso de Barzilai, o sacerdote que tomou o nome do sogro rico e perdeu o do pai: \"Estes buscaram o seu registro nos livros genealógicos, porém não se achou; então, como imundos, foram excluídos do sacerdócio\" (Ne 7:64). O governador não os manda embora; deixa a porta encostada: \"até que se apresentasse o sacerdote com Urim e Tumim\" (Ne 7:65).",
    },
    homem: {
      title: "Hananias, líder da fortaleza, homem fiel e temente a Deus mais do que muitos, os moradores postos de guarda cada um diante da sua casa, os chefes das casas paternas do rol e o que subiu de Tel-Melá sem poder provar a linhagem",
      subtitle: "Ne 7:2-3,8-38,61-62 • quem guarda a cidade e quem consta do livro",
      text: "A primeira decisão depois do muro é de pessoal, e o critério está escrito: \"Eu nomeei a Hanani, meu irmão, e a Hananias, líder da fortaleza, sobre Jerusalém; porque ele era homem fiel e temente a Deus, mais do que muitos\" (Ne 7:2). Não se diz que era competente, corajoso ou bem relacionado: diz-se que era fiel e temente a Deus mais do que muitos, e é esse o currículo. A ordem que ele recebe é de uma prudência quase paranoica: \"Não se abram as portas de Jerusalém até que o sol aqueça\" (Ne 7:3) — o costume antigo era abrir de madrugada; aqui espera-se pela luz plena, quando toda a gente já está acordada e um assalto não pode passar despercebido. E cada morador vira sentinela do seu próprio pedaço de rua: \"ponham-se guardas dos moradores de Jerusalém, cada um na sua guarda, e cada um diante da sua casa\". Depois entram os homens do rol, casa a casa e cidade a cidade — os filhos de Parós, os de Paate-Moabe, os homens de Micmás, os de Betel e Ai. E, no fim, os que ficaram de fora: \"Também estes subiram de Tel-Melá, e Tel-Harsa, Querube, Adom, Imer; porém não puderam provar que a casa de seus pais e a sua linhagem, eram de Israel\" (Ne 7:61).",
    },
    mulherComum: {
      title: "As mulheres das casas paternas do rol, a que havia de tirar água do poço do pátio, a que subia ao terraço por cobrir, as duzentas e quarenta e cinco cantoras e a filha de Barzilai, o gileadita",
      subtitle: "Ne 7:8-38,63,67 • as que hão de mudar para uma cidade sem casas edificadas",
      text: "A conta deste capítulo é declaradamente de homens, e as mulheres atravessam setenta versículos fora da soma — aparecem uma vez, e por causa do ofício: \"Afora os seus servos e as suas servas, que foram sete mil, trezentos e trinta e sete; e tinham duzentos e quarenta e cinco cantores e cantoras\" (Ne 7:67). Mas o que muda tudo aqui é o versículo 4: a cidade está larga de espaço, com pouco povo dentro e \"ainda as casas não estavam edificadas\". Mudar-se para Jerusalém, nesta altura, é ir viver num lote sem telhado, tirar água de um poço partilhado num pátio vazio e cobrir um terraço antes das chuvas. É a mulher da casa paterna quem faz essa mudança acontecer, e é ela que, no capítulo 11, será sorteada com o marido para deixar a herança do campo e vir habitar a cidade santa. Há ainda uma mulher no meio de um caso jurídico: a filha de Barzilai, o gileadita, aquele velho de oitenta anos que sustentara Davi em Maanaim — \"os filhos de Barzilai, que tomara uma mulher das filhas de Barzilai, o gileadita, e que foi chamado do seu nome\" (Ne 7:63). O casamento dela apagou o nome de uma casa sacerdotal do registro.",
    },
    multidao: {
      title: "A congregação de quarenta e dois mil trezentos e sessenta do rolo, e o povo que habitou nas suas cidades",
      subtitle: "Ne 7:66,73 • a soma lida em voz alta dentro de uma cidade quase vazia",
      text: "\"Toda esta congregação junta foi de quarenta e dois mil, trezentos e sessenta\" (Ne 7:66) — a mesma soma que Esdras dera (Ed 2:64), copiada de novo para que não se perdesse. É pouco: um povo que saíra do Egito com seiscentos mil homens de pé cabe agora numa cidade média. E o capítulo fecha exatamente onde o problema começa: \"E habitaram os sacerdotes, os levitas, os porteiros, os cantores, alguns do povo, os servidores do templo, e todo o Israel nas suas cidades\" (Ne 7:73). Nas SUAS cidades — quer dizer, não em Jerusalém. O muro está de pé, as portas estão levantadas, os porteiros e os cantores estão estabelecidos, e o interior continua vazio. É por isso que o capítulo 11 terá de lançar sortes para tirar um de cada dez e trazê-lo para dentro. Entre este versículo e aquele há a praça do capítulo 8, onde esta mesma multidão se ajunta \"como um só homem\" (Ne 8:1) — a cidade enche-se primeiro para ouvir, e só depois para morar.",
    },
    pastor: {
      title: "Os homens de Belém e de Netofa, os pastores das aldeias do planalto a oeste e os dos outeiros de Betel, que hão de subir a Jerusalém",
      subtitle: "Ne 7:26,29,32 • as aldeias de pasto que o rol conta uma a uma",
      text: "A partir do versículo 25 a lista muda de eixo: deixa de contar casas paternas e passa a contar LUGARES. \"Os homens de Belém e de Netofa, cento e oitenta e oito\" (Ne 7:26) — cento e oitenta e oito para as duas aldeias juntas, uma encosta de cevada e de pastos onde Rute respigou e de onde Samuel mandou chamar o filho mais novo de Jessé, o que faltava porque estava com as ovelhas. \"Os homens de Quiriate-Jearim, Quefira e Beerote, setecentos e quarenta e três\" (Ne 7:29): as três antigas cidades gibeonitas do planalto a oeste, cujos habitantes tinham enganado Josué com pão bolorento e ficaram rachadores de lenha e tiradores de água (Js 9:27). \"Os homens de Betel e Ai, cento e vinte e três\" (Ne 7:32). O pastor destas linhas é um homem que tem rebanho num campo herdado, e que dentro de quatro capítulos poderá ser sorteado para largar tudo isto e ir morar dentro de muros. É o que faz do capítulo 11 uma coisa cara: cada nome deste rol tem uma encosta atrás de si.",
    },
    servo: {
      title: "Os porteiros e os cantores estabelecidos sobre as portas, os setenta e quatro levitas de Jesuá e Cadmiel, os cento e trinta e oito porteiros das seis casas, os netineus nome por nome, os filhos dos servos de Salomão e os arrieiros dos seis mil setecentos e vinte jumentos",
      subtitle: "Ne 7:1,43-60,68-69 • a folha inteira do serviço da casa e da caravana",
      text: "\"Sucedeu que, depois que o muro foi edificado, eu levantei as portas; e foram estabelecidos os porteiros, os cantores e os levitas\" (Ne 7:1). Repare na ordem: as portas primeiro, e logo os homens que as guardam e o coro que canta nelas — para Neemias, a segurança e o culto entram na cidade no mesmo dia. Depois vem o rol, e nele o buraco de sempre: \"Os levitas: Os filhos de Jesuá, de Cadmiel, dos filhos de Hodeva, setenta e quatro\" (Ne 7:43) — setenta e quatro levitas contra mais de quatro mil sacerdotes. Os cantores de Asafe são o dobro deles, cento e quarenta e oito (Ne 7:44), e os porteiros, cento e trinta e oito, vêm nomeados de seis em seis casas (Ne 7:45). Seguem-se os NETINEUS, os \"dados\" ao serviço, listados casa por casa durante onze versículos — gente cujos nomes ninguém decorava, e que o texto teve o cuidado de escrever —, e com eles os filhos dos servos de Salomão, dos povos que aquele rei reduzira a tributo servil, somados numa linha só: \"trezentos e noventa e dois\" (Ne 7:60). No fim, a logística da caravana antiga: setecentos e trinta e seis cavalos, duzentos e quarenta e cinco mulos, quatrocentos e trinta e cinco camelos e \"jumentos, seis mil, setecentos e vinte\" (Ne 7:69).",
    },
  },
};
