// Fichas ESPECÍFICAS por (capítulo → papel) de NEEMIAS 8–13.
// Seis capítulos em que o muro já está de pé e o assunto passa a ser o que
// mora dentro dele. A praça diante da porta das águas com um púlpito de
// madeira e um povo que se põe em pé quando o livro se abre; a maior oração de
// recapitulação da Bíblia, recitada pelos levitas do lugar alto e terminada na
// frase mais dura do pós-exílio — "eis que hoje somos servos"; os oitenta e
// três que selam a firme aliança e as cláusulas que escrevem; as sortes que
// tiram um de dez para povoar a cidade santa; os dois grandes coros andando
// sobre o muro em direções opostas até pararem ambos na casa de Deus; e o
// regresso de Neemias, que acha tudo desfeito e fecha o Antigo Testamento
// histórico com três pedidos: "lembra-te de mim, Deus meu, para bem".
// Deus não fala nem aqui: quem tem voz é o livro lido em voz alta.
import type { StageInfo } from "@/lib/rpgStageInfo";

export const CHAPTER_ACTORS_08_13: Record<number, Record<string, StageInfo>> = {
  // ---------------------------------------------------------------- Ne 8
  8: {
    anciao: {
      title: "Hilquias e Zacarias, dos treze homens que estavam em pé junto a Esdras sobre o púlpito, os treze levitas que ensinavam o povo na lei e os chefes dos pais que no dia seguinte se ajuntaram para atentar nas palavras",
      subtitle: "Ne 8:4,7,13 • os que estavam à direita e à esquerda do escriba",
      text: "Esdras não leu sozinho, e o texto teve o cuidado de contar quem estava de cada lado: \"e estava em pé junto a ele, à sua mão direita, Matitias, Sema, Anaías, Urias, Hilquias e Maaséias; e à sua mão esquerda, Pedaías, Misael, Melquias, Hasum, Hasbadana, Zacarias e Mesulão\" (Ne 8:4). Treze homens de pé num estrado, seis de um lado e sete do outro, durante uma leitura que vai \"desde a alva até ao meio-dia\" (Ne 8:3). Depois vem a segunda equipa, e é ela que faz o trabalho mais fino: \"E Jesuá, Bani, Serebias, Jamim, Acube, Sabetai, Hodias, Maaséias, Quelita, Azarias, Jozabade, Hanã, Pelaías, e os levitas ensinavam o povo na lei; e o povo estava no seu lugar\" (Ne 8:7). Treze levitas circulando pela praça, grupo a grupo — porque o hebraico do livro já era língua de estudo para gente criada a falar aramaico. \"E leram no livro, na lei de Deus; e declarando, e explicando o sentido, faziam que, lendo, se entendesse\" (Ne 8:8): é a definição mais antiga do que é pregar. No dia seguinte, os chefes dos pais voltam sozinhos para estudar mais devagar (Ne 8:13) — e é nesse estudo que descobrem a festa das cabanas.",
    },
    homem: {
      title: "O homem do povo que pediu o livro da lei, o que se pôs em pé quando o livro se abriu, o que chorava ouvindo as palavras, o que não tinha nada preparado para si e o pregoeiro que publicou o pregão dos ramos",
      subtitle: "Ne 8:1-16 • a praça diante da porta das águas, do primeiro ao sétimo dia",
      text: "\"E chegado o sétimo mês, e estando os filhos de Israel nas suas cidades, todo o povo se ajuntou como um só homem, na praça, diante da porta das águas; e disseram a Esdras, o escriba, que trouxesse o livro da lei de Moisés\" (Ne 8:1). Ninguém convocou esta assembleia: o pedido parte de baixo, e é o povo que manda buscar o livro. O gesto que se segue é o coração do capítulo: \"E Esdras abriu o livro perante à vista de todo o povo; porque estava acima de todo o povo; e, abrindo-o ele, todo o povo se pôs em pé\" (Ne 8:5) — de pé durante seis horas, e não porque alguém mandasse. Depois: \"Amém, Amém! levantando as suas mãos; e inclinaram suas cabeças, e adoraram ao Senhor, com os rostos em terra\" (Ne 8:6). E então a lei entendida faz o que a lei entendida faz: \"Porque todo o povo chorava, ouvindo as palavras da lei\" (Ne 8:9). É contra este choro que vem a ordem mais inesperada da Escritura — \"Ide, comei as gorduras, e bebei as doçuras, e enviai porções aos que não têm nada preparado para si… porque a alegria do Senhor é a vossa força\" (Ne 8:10). O homem que não tinha nada preparado para si está nesta praça, e é por causa dele que a festa tem endereço.",
    },
    mulherComum: {
      title: "As mulheres que se ajuntaram na praça e podiam ouvir com entendimento, as que choraram ouvindo a lei e as que levaram porções a quem nada tinha preparado",
      subtitle: "Ne 8:2-3,10 • a congregação tanto de homens como de mulheres",
      text: "O texto faz questão de dizer duas vezes quem estava a ouvir: \"E Esdras, o sacerdote, trouxe a lei perante a congregação, tanto de homens como de mulheres, e todos os que podiam ouvir com entendimento\" (Ne 8:2), e outra vez no versículo seguinte, \"perante homens e mulheres, e os que podiam entender\" (Ne 8:3). Não é uma nota de cortesia: é a lei de Moisés a ser cumprida à letra, porque o mandamento da leitura pública mandava ajuntar \"os homens e as mulheres, os meninos e os estrangeiros que estão dentro das tuas portas, para que ouçam e aprendam\" (Dt 31:12). Seis horas em pé numa praça, com crianças ao colo, ouvindo um livro em hebraico traduzido frase a frase por treze levitas. E quando a leitura acaba, a primeira aplicação prática do dia santo passa pelas mãos delas: \"e enviai porções aos que não têm nada preparado para si\" (Ne 8:10) — alguém tem de cozinhar em dobro e mandar a travessa para a casa do vizinho pobre. Uma semana depois, é ela quem corta os ramos de murta e arma a cabana no terraço da sua própria casa (Ne 8:16).",
    },
    multidao: {
      title: "Todo o povo ajuntado como um só homem na praça, que respondeu Amém, Amém e depois fez grande regozijo porque entendeu as palavras",
      subtitle: "Ne 8:1,6,12,17 • o maior culto do pós-exílio, e a alegria como consequência do entendimento",
      text: "\"Todo o povo se ajuntou como um só homem, na praça, diante da porta das águas\" (Ne 8:1) — no mesmo lugar em que os netineus de Ofel tinham reparado o muro (Ne 3:26), e sem templo pelo meio: a lei é lida ao ar livre, na cidade, e não no adro. A resposta é coletiva e corporal: em pé quando o livro se abre, mãos levantadas, cabeças inclinadas, rostos em terra (Ne 8:5-6). E o versículo que explica a festa liga-a ao entendimento, não à emoção: \"Então todo o povo se foi a comer, a beber, a enviar porções e a fazer grande regozijo; porque entenderam as palavras que lhes fizeram saber\" (Ne 8:12). A semana acaba em cabanas de ramos por toda a cidade — nos terraços, nos pátios, nos átrios da casa de Deus, na praça da porta das águas e na praça da porta de Efraim (Ne 8:16) — e o autor faz uma afirmação que assusta: \"porque nunca fizeram assim os filhos de Israel, desde os dias de Jesua, filho de Num, até àquele dia; e houve mui grande alegria\" (Ne 8:17). Mil anos sem uma festa das cabanas como esta.",
    },
    servo: {
      title: "Os moços da praça diante da porta das águas, os que subiram ao monte buscar ramos de oliveira, de zambujeiro, de murta e de palmeira, e os que reparteram as porções do dia santo",
      subtitle: "Ne 8:10,15-16 • as mãos que montam o púlpito, cortam os ramos e levam as travessas",
      text: "Antes da leitura, alguém teve de construir o estrado: \"E Esdras, o escriba, estava sobre um púlpito de madeira, que fizeram para aquele fim\" (Ne 8:4) — feito de propósito para aquele dia, por carpinteiros que ficaram sem nome. Durante o dia santo, o mandamento gera trabalho imediato de criadagem: \"enviai porções aos que não têm nada preparado para si\" (Ne 8:10), e a praça enche-se de moços a atravessar a cidade com travessas. Na semana seguinte vem a corrida ao monte: \"Assim publicaram, e fizeram passar pregão por todas as suas cidades, e em Jerusalém, dizendo: Saí ao monte, e trazei ramos de oliveiras, e ramos de zambujeiros, e ramos de murtas, e ramos de palmeiras, e ramos de árvores espessas, para fazer cabanas, como está escrito\" (Ne 8:15). Cinco espécies, nomeadas uma a uma, cortadas nas encostas em volta e carregadas às costas para dentro dos muros — e é assim que se cumpre o \"Sete dias habitareis em tendas\" de Levítico 23:42, mil anos depois, numa cidade que acabou de aprender a fechar as suas portas.",
    },
  },

  // ---------------------------------------------------------------- Ne 9
  9: {
    anciao: {
      title: "Jesuá, Bani, Cadmiel e os levitas que se puseram em pé no lugar alto e clamaram em alta voz, os que leram uma quarta parte do dia, e o profeta que testificava contra o povo",
      subtitle: "Ne 9:3-5,29 • os oito que recitaram a história inteira de Israel em voz alta",
      text: "O dia é de saco e de cinza — \"ajuntaram-se os filhos de Israel com jejum e com sacos, e traziam terra sobre si\" (Ne 9:1) — e o horário é de resistência: \"leram no livro da lei do Senhor seu Deus uma quarta parte do dia; e na outra quarta parte fizeram confissão, e adoraram ao Senhor seu Deus\" (Ne 9:3). Três horas de leitura e três horas de confissão. Depois sobem ao estrado os que vão dizer a oração mais longa da Escritura: \"E Jesuá, Bani, Cadmiel, Sebanias, Buni, Serebias, Bani e Quenani se puseram em pé no lugar alto dos levitas, e clamaram em alta voz ao Senhor seu Deus\" (Ne 9:4). O que eles recitam não é um pedido: é a história de Israel contada a Deus de trás para a frente, de Abrão em Ur até ao imposto persa daquele mês. E dentro dessa história há um personagem que aparece sempre no mesmo papel e sempre com o mesmo fim: \"E testificaste contra eles, para que voltassem para a tua lei; porém eles se houveram soberbamente… viraram o ombro, endureceram a sua cerviz, e não quiseram ouvir\" (Ne 9:29). O ancião desta cena é o levita que já é velho e sabe de cor a lista inteira dos que não ouviram.",
    },
    cavaleiro: {
      title: "Os perseguidores que foram lançados nas profundezas, como uma pedra nas águas violentas",
      subtitle: "Ne 9:11 • o Mar Vermelho recitado na praça de Jerusalém mil anos depois",
      text: "\"E o mar fendeste perante eles, e passaram pelo meio do mar, em seco; e lançaste os seus perseguidores nas profundezas, como uma pedra nas águas violentas\" (Ne 9:11). Os levitas não estão a contar uma lenda antiga: estão a recitar a certidão de nascimento do povo que está ali ajuntado com saco e cinza. A imagem da PEDRA vem do próprio cântico de Moisés, e o relato original é seco: \"Porque as águas, tornando, cobriram os carros e os cavaleiros de todo o exército de Faraó, que os haviam seguido no mar; nenhum deles ficou\" (Êx 14:28). Estes cavaleiros são o único exército que o Egito tinha no encalço dos escravos fugidos, e desapareceram em silêncio numa madrugada. Quem recita isto está debaixo de outro império, paga tributo a outro rei e sabe muito bem o que está a dizer: o Deus que fende o mar continua a ser o mesmo — e a oração acabará, mesmo assim, com uma confissão de servidão e não com um pedido de milagre.",
    },
    homem: {
      title: "Abrão tirado de Ur dos caldeus, o israelita que passou o mar em seco, o que ajuntou o pão dos céus, o de cerviz endurecida que levantou um capitão para voltar ao Egito, o que se curvou ao bezerro de fundição e o que lançou a lei para trás das costas",
      subtitle: "Ne 9:7-30 • a história inteira de Israel encenada na praça, versículo a versículo",
      text: "A oração corre como um filme e cada versículo é um quadro. Começa em Ur: \"Tu és o Senhor, o Deus, que elegeste a Abrão, e o tiraste de Ur dos caldeus, e lhe puseste por nome Abraão\" (Ne 9:7). Passa pelo Egito, pelo mar, pela coluna, pelo Sinai, e chega ao deserto, onde o texto faz um retrato que é dos mais delicados de toda a Escritura: \"De tal modo os sustentaste quarenta anos no deserto; nada lhes faltou; as suas roupas não se envelheceram, e os seus pés não se incharam\" (Ne 9:21) — quarenta anos de caminhada sem sapato rasgado nem pé inchado, e é isso que a oração escolhe lembrar. Mas o mesmo homem que come o maná é o que endurece a cerviz: \"na sua rebelião, levantaram um capitão, a fim de voltarem para a sua servidão\" (Ne 9:17); é o que funde o bezerro e diz \"Este é o teu Deus, que te tirou do Egito\" (Ne 9:18); é o que entra na terra, come, farta-se, engorda, vive em delícias (Ne 9:25) e depois \"lançaram a tua lei para trás das suas costas, e mataram os teus profetas\" (Ne 9:26). O ciclo repete-se quatro vezes na oração: pecado, entrega na mão do adversário, clamor, libertador. E acaba onde o povo está: \"Eis que hoje somos servos\" (Ne 9:36).",
    },
    mulherComum: {
      title: "A mulher de Israel afligida no Egito, a que passou o mar em seco, a que encheu o cântaro na água da penha, a que deu o ouro para o bezerro e a que viveu quarenta anos com a mesma roupa",
      subtitle: "Ne 9:9-25 • a recitação vista do lado de quem carregava os filhos",
      text: "A oração dos levitas conta a história pelo que aconteceu a um povo inteiro, e metade desse povo é ela. \"E viste a aflição de nossos pais no Egito, e ouviste o seu clamor junto ao Mar Vermelho\" (Ne 9:9) — a aflição do Egito era, em primeiro lugar, uma sentença contra os filhos recém-nascidos. Depois vem a travessia com as crianças pela mão, e o deserto, onde a lista das provisões é doméstica e não militar: \"E pão dos céus lhes deste na sua fome, e água da penha lhes produziste na sua sede\" (Ne 9:15) — o pão que se ajunta de manhã e a água que se traz da rocha em cântaro. E vem a frase da roupa, que só quem lava e remenda entende bem: \"as suas roupas não se envelheceram, e os seus pés não se incharam\" (Ne 9:21), o mesmo milagre miúdo que Moisés já registara em Deuteronômio 8:4. Há também a linha do ouro do bezerro, que saiu dos brincos das mulheres e dos filhos (Êx 32:2). E há a fartura da terra, com \"casas cheias de toda a fartura, cisternas cavadas, vinhas e olivais\" (Ne 9:25) — casa cheia que ninguém encheu.",
    },
    rebanho: {
      title: "O rebanho que atravessou o deserto com Israel durante quarenta anos, e o gado de Judá sobre o qual os reis agora dominam",
      subtitle: "Ne 9:21,37 • a mesma criação, no meio da oração e no fim dela",
      text: "O gado aparece duas vezes nesta oração e as duas medem a distância entre o que Israel foi e o que Israel é. No meio da recitação está a travessia: quarenta anos de deserto com rebanhos atrás, e a frase que os cobre a todos — \"De tal modo os sustentaste quarenta anos no deserto; nada lhes faltou\" (Ne 9:21). No fim está o presente, e é uma queixa fiscal: \"E ela multiplica os seus produtos para os reis, que puseste sobre nós, por causa dos nossos pecados; e conforme a sua vontade dominam sobre os nossos corpos e sobre o nosso gado; e estamos numa grande angústia\" (Ne 9:37). A terra prometida continua a dar, mas o que ela dá vai para um rei que mora a mil e quinhentos quilómetros dali; e o poder dele alcança não só a colheita, mas o corpo do lavrador e a cabeça de gado no curral. É o degrau mais baixo da oração, e vem logo antes da decisão de fazer uma firme aliança e escrevê-la (Ne 9:38): não se pede libertação política nenhuma — assina-se obediência dentro da servidão.",
    },
    rei: {
      title: "Os reis e os povos da terra entregues na mão de Israel, e os reis de Judá que não guardaram a lei nem deram ouvidos aos mandamentos",
      subtitle: "Ne 9:24,34 • as duas realezas da recitação, a vencida e a culpada",
      text: "A oração usa a palavra \"reis\" duas vezes, e em posições opostas. Primeiro na conquista: \"Assim os filhos entraram e possuíram aquela terra; e abateste perante eles os moradores da terra, os cananeus, e lhos entregaste na mão, como também os reis e os povos da terra, para fazerem deles conforme a sua vontade\" (Ne 9:24) — trinta e um reis derrotados no livro de Josué, cada um com a sua cidade fortificada, e o mérito é todo do verbo \"abateste\". Depois na confissão, e agora os reis são de casa: \"E os nossos reis, os nossos príncipes, os nossos sacerdotes, e os nossos pais não guardaram a tua lei, e não deram ouvidos aos teus mandamentos e aos teus testemunhos, que testificaste contra eles\" (Ne 9:34). Repare que a lista está em ordem de responsabilidade descendente: primeiro o rei, depois o príncipe, depois o sacerdote, e só no fim \"os nossos pais\". Quatrocentos anos de dinastia davídica resumidos numa acusação — e a oração não pede a restauração do trono. Pede que Deus não tenha em pouca conta a aflição (Ne 9:32).",
    },
    servo: {
      title: "O moço de Judá com saco e cinza, o israelita carregado de tijolo no Egito, o menino levado pelo mar em seco, o que recebeu o maná de manhã, o vindimador das vinhas que não plantou e o lavrador que hoje é servo na própria terra",
      subtitle: "Ne 9:1-36 • a servidão no princípio da recitação e no fim dela",
      text: "A oração abre e fecha com a mesma palavra, e é essa a sua arquitetura. No princípio, a servidão é egípcia: \"E viste a aflição de nossos pais no Egito\" (Ne 9:9) — tijolo, palha e capatazes. Depois vem tudo o que Deus fez para a desfazer: o mar fendido, a coluna, o Sinai, o maná, a água da penha, a terra tomada com \"cidades fortificadas e terra fértil\" e vinhas e olivais que outros plantaram (Ne 9:25). E então, depois de trinta versículos de libertação, o remate: \"Eis que hoje somos servos; e até na terra que deste a nossos pais, para comerem o seu fruto e o seu bem, eis que somos servos nela\" (Ne 9:36). É a frase mais dura do pós-exílio: o povo está de volta à terra, com o templo de pé e o muro acabado, e chama-se a si mesmo servo dentro de casa. O moço de saco e cinza que está de pé nesta praça é a última figura da lista — e o que ele faz a seguir não é revolta, é assinatura: \"E, todavia fizemos uma firme aliança, e o escrevemos\" (Ne 9:38).",
    },
  },

  // ---------------------------------------------------------------- Ne 10
  10: {
    anciao: {
      title: "Os vinte e um sacerdotes que selaram a aliança — Seraías, Azarias, Jeremias, Pasur, Amarias, Harim, Semaías —, os levitas de Jesuá filho de Azanias e Cadmiel, os chefes do povo e o sacerdote que tomou o anátema e o juramento",
      subtitle: "Ne 10:1-29 • os oitenta e três selos ao pé do documento",
      text: "\"E os que selaram foram: Neemias, o governador, filho de Hacalias, e Zedequias\" (Ne 10:1), e a seguir vinte e um sacerdotes, dezassete levitas e quarenta e quatro chefes do povo — oitenta e três nomes, um por um, num documento que ninguém foi obrigado a assinar. É a única vez em toda a Escritura em que Israel se compromete por escrito, com lista de signatários, e não por aclamação diante de um rei. O que os liga não é lealdade a um homem: \"Firmemente aderiram a seus irmãos os mais nobres dentre eles, e convieram num anátema e num juramento, de que andariam na lei de Deus, que foi dada pelo ministério de Moisés, servo de Deus\" (Ne 10:29). ANÁTEMA é a palavra pesada: chamam sobre si a maldição se falharem. Vários destes nomes são casas antigas — Pasur é a casa do sacerdote que mandou pôr Jeremias no tronco (Jr 20:1), Harim e Jedaías são turmas sorteadas por Davi (1Cr 24:8,7) —, e vários voltarão no capítulo 12 na dedicação do muro. O ancião desta cena é o homem que assina em nome de uma casa inteira e sabe que a assinatura vai ser cobrada aos netos.",
    },
    homem: {
      title: "O pai de família que aderiu à aliança com toda a sua casa, o que jurou não dar a filha aos povos da terra, o que nada compraria no sábado, o que pôs sobre si a terça parte de um siclo e o lavrador que trouxe as primícias e o dízimo",
      subtitle: "Ne 10:28-39 • as cláusulas do contrato, uma a uma",
      text: "Depois dos oitenta e três selos, a aliança abre-se a toda a gente: \"E o restante do povo, os sacerdotes, os levitas, os porteiros, os cantores, os servidores do templo, todos os que se tinham separado dos povos das terras para a lei de Deus, suas mulheres, seus filhos e suas filhas, todos os que tinham conhecimento e entendimento\" (Ne 10:28). Depois vêm as cláusulas, e são todas concretas. Casamento: \"que não daríamos as nossas filhas aos povos da terra, nem tomaríamos as filhas deles para os nossos filhos\" (Ne 10:30). Sábado, e é a cláusula mais cara de todas, porque atinge o mercado: \"trazendo os povos da terra no dia de sábado qualquer mercadoria, e qualquer grão para venderem, nada compraríamos deles no sábado\" (Ne 10:31) — e no mesmo fôlego o ano sabático e o perdão de \"toda e qualquer cobrança\". Imposto voluntário: \"impondo-nos cada ano a terça parte de um siclo, para o ministério da casa do nosso Deus\" (Ne 10:32). Primícias, primogénitos, dízimos (Ne 10:35-38). E a frase que fecha tudo e resume o capítulo inteiro: \"e que assim não desampararíamos a casa do nosso Deus\" (Ne 10:39). Três capítulos adiante, Neemias volta de viagem e descobre que desampararam.",
    },
    mulherComum: {
      title: "As mulheres e as filhas que aderiram à aliança com a sua casa, a filha de Judá que não seria dada aos povos da terra e a que passaria pela banca do vendedor no sábado sem comprar",
      subtitle: "Ne 10:28,30-31 • as cláusulas que se cumprem dentro de casa e no mercado",
      text: "A adesão à aliança é nominalmente doméstica: \"suas mulheres, seus filhos e suas filhas, todos os que tinham conhecimento e entendimento\" (Ne 10:28) — o critério não é sexo nem idade, é entender o que se está a jurar. E duas das cláusulas caem diretamente sobre a vida dela. A primeira decide com quem os filhos casam: \"que não daríamos as nossas filhas aos povos da terra, nem tomaríamos as filhas deles para os nossos filhos\" (Ne 10:30) — numa província pequena, cercada de amonitas, asdoditas e samaritanos, isso reduz drasticamente o campo de escolha de cada família, e é por isso que a cláusula cai tantas vezes. A segunda decide o dia de feira: \"nada compraríamos deles no sábado, nem no dia santificado\" (Ne 10:31). Quem faz as compras da casa passa a ter de as fazer antes do pôr do sol de sexta-feira, e a ver a banca montada do lado de fora da porta no sábado sem lá ir. É uma disciplina que se cumpre na cozinha e no cesto, e no capítulo 13 será a primeira a quebrar-se.",
    },
    multidao: {
      title: "O povo que jurou não desamparar a casa do nosso Deus",
      subtitle: "Ne 10:39 • a última linha da firme aliança",
      text: "\"Porque àquelas câmaras os filhos de Israel e os filhos de Levi devem trazer ofertas alçadas do grão, do mosto e do azeite; porquanto ali estão os vasos do santuário, como também os sacerdotes que ministram, os porteiros e os cantores; e que assim não desampararíamos a casa do nosso Deus\" (Ne 10:39). O capítulo, que começou em oitenta e três selos de cera, acaba numa promessa coletiva de logística: alguém tem de trazer o grão, alguém tem de guardar o vaso, alguém tem de estar à porta e alguém tem de cantar — e para isso alguém tem de comer. O verbo DESAMPARAR é o que liga esta linha ao resto do livro: é exatamente a palavra que Neemias usará ao voltar de Susã e encontrar os levitas fugidos para os seus campos — \"Por que se desamparou a casa de Deus?\" (Ne 13:11). Entre a promessa e a acusação passam poucos anos. A multidão que jura aqui é sincera, e é a mesma que falha; e é essa a razão pela qual o Antigo Testamento acaba a pedir a Deus que se lembre, em vez de anunciar que o problema ficou resolvido.",
    },
    rebanho: {
      title: "Os primogénitos do gado e das ovelhas apartados para serem trazidos à casa do nosso Deus",
      subtitle: "Ne 10:36 • a cláusula que sai do curral antes de sair do bolso",
      text: "\"E os primogênitos dos nossos filhos, e os do nosso gado, como está escrito na lei; e que os primogênitos do nosso gado e das nossas ovelhas traríamos à casa do nosso Deus, aos sacerdotes, que ministram na casa do nosso Deus\" (Ne 10:36). A lei do primogénito é a mais antiga memória do Êxodo: pertence a Deus o primeiro que abre a madre, porque numa noite no Egito a casa de Israel foi poupada e a do Egito não. Para um lavrador do pós-exílio, isso quer dizer separar a melhor cabeça da primeira cria — não a que sobra, a PRIMEIRA — e subir com ela a Jerusalém. Neste capítulo, a cláusula do gado vem colada à das primícias da terra e das árvores (Ne 10:35) e à do dízimo da lavoura (Ne 10:37), formando um sistema completo de sustento para os sacerdotes, os levitas, os porteiros e os cantores. Todo o edifício assenta em animais e sacos de grão que sobem por estradas de montanha, e por isso desmorona depressa: no capítulo 13 os quinhões deixam de ser dados e os levitas voltam para o campo.",
    },
    servo: {
      title: "O moço que guardou o rolo da aliança, o que levou a prata do siclo ao ministério da casa, o que trouxe a lenha sorteada e o levita do holocausto contínuo dos sábados",
      subtitle: "Ne 10:32-38 • as sortes lançadas sobre a oferta da lenha, e o resto da rotina",
      text: "As cláusulas desta aliança não se cumprem com boa vontade: cumprem-se com um calendário e com gente escalada. A mais curiosa é a da lenha, e o método é o sorteio: \"Também lançamos sortes entre os sacerdotes, levitas, e o povo, acerca da oferta da lenha que se havia de trazer à casa do nosso Deus, segundo as casas de nossos pais, a tempos determinados, de ano em ano, para se queimar sobre o altar do Senhor nosso Deus, como está escrito na lei\" (Ne 10:34). O fogo do altar tinha de arder sem parar, e em Judá a madeira é escassa: alguém tem de subir ao monte, cortar, atar e carregar feixes, e a sorte diz qual casa o faz em que semana. Ao lado disso corre a rotina inteira do santuário, e o versículo 33 é a lista de compras dela — \"os pães da proposição… a contínua oferta de alimentos… o contínuo holocausto dos sábados, das luas novas, para as festas solenes\". E há a prata: a terça parte de um siclo por cabeça e por ano (Ne 10:32), recolhida e levada por moços à casa do tesouro, onde ficará guardada — até que Eliasibe esvazie uma daquelas câmaras para fazer quarto a Tobias (Ne 13:5).",
    },
  },

  // ---------------------------------------------------------------- Ne 11
  11: {
    anciao: {
      title: "Os chefes do povo que já habitavam em Jerusalém e lançaram as sortes, Seraías filho de Hilquias, líder da casa de Deus, Sabetai e Jozabade sobre a obra de fora, e o ancião das aldeias do Neguebe",
      subtitle: "Ne 11:1,11,16,28 • quem já morava dentro e quem manda vir de fora",
      text: "\"E os líderes do povo habitaram em Jerusalém, porém o restante do povo lançou sortes, para tirar um de dez, que habitasse na santa cidade de Jerusalém, e as nove partes nas outras cidades\" (Ne 11:1). A chefia já está dentro — não se sorteia quem manda —, e sorteia-se o resto: um em cada dez larga a herança do campo e muda-se para uma cidade que ainda tem casas por edificar. Dentro dela, o capítulo desenha o organograma inteiro: \"Seraías, filho de Hilquias… líder da casa de Deus\" (Ne 11:11), com oitocentos e vinte e dois irmãos que faziam a obra do santuário; \"Sabetai, e Jozabade, dos chefes dos levitas, presidiam sobre a obra de fora da casa de Deus\" (Ne 11:16) — a administração externa, os dízimos, os campos, as contas; Uzi, filho de Bani, superintendente dos levitas (Ne 11:22); e Zia e Gispa sobre os netineus de Ofel (Ne 11:21). Fora dos muros, o capítulo estende-se num mapa que vai do sul ao norte — \"Acamparam-se desde Berseba até ao vale de Hinom\" (Ne 11:30) —, e o ancião de cada aldeia responde pela sua.",
    },
    homem: {
      title: "Ataías dos filhos de Perez, Maaséias filho de Baruque, Salu filho de Mesulão, os quatrocentos e sessenta e oito homens valentes de Judá, Matanias que iniciava as ações de graças na oração, Acube e Talmom com os cento e setenta e dois porteiros, e os artífices do vale de Lode e Ono",
      subtitle: "Ne 11:4-36 • quem foi morar na cidade santa e o que fazia lá dentro",
      text: "O capítulo é o censo da cidade repovoada, e cada nome traz um ofício. Dos filhos de Judá vem a casa de Perez, e o número é militar: \"Todos os filhos de Perez, que habitaram em Jerusalém, foram quatrocentos e sessenta e oito homens valentes\" (Ne 11:6). De Benjamim, Salu e os seus, novecentos e vinte e oito, com Joel, filho de Zicri, como superintendente e Judá, filho de Senua, \"o segundo sobre a cidade\" (Ne 11:9). Entre os levitas há um homem com um cargo que só existe aqui: \"E Matanias, filho de Mica, filho de Zabdi, filho de Asafe, o chefe, que iniciava as ações de graças na oração\" (Ne 11:17) — o que dá o tom, começa o cântico e o coro segue. Os porteiros são cento e setenta e dois (Ne 11:19), e os cantores têm o horário fixado por decreto imperial: \"Porque havia um mandado do rei acerca deles, e uma certa regra para os cantores, cada qual no seu dia\" (Ne 11:23). Nas aldeias, o mapa acaba com uma nota de ofício que ficou como topónimo: \"Em Lode e em Ono, no vale dos artífices\" (Ne 11:35) — um vale inteiro de gente que trabalhava com as mãos.",
    },
    mulherComum: {
      title: "A mulher do voluntário que se ofereceu para mudar de aldeia para Jerusalém, e as mulheres de Judá que ficaram na herança do campo, de Dibom a Jarmute e de Hazar-Sual a Zeboim",
      subtitle: "Ne 11:2,20,25-34 • quem faz a mudança e quem fica na terra dos pais",
      text: "\"E o povo bendisse a todos os homens que voluntariamente se ofereciam para habitar em Jerusalém\" (Ne 11:2). É um versículo que só se entende sabendo o que custava: mudar para a cidade santa significava deixar a casa de pedra que a família tinha no campo, a vinha plantada por um avô e a cisterna cavada, para ir viver dentro de muros novos onde \"ainda as casas não estavam edificadas\" (Ne 7:4) e onde não há terra para semear. Quem se oferece muda com a mulher e os filhos, e por isso o povo os BENDIZ — a bênção pública substitui a compensação que ninguém tinha para dar. Do outro lado, o capítulo lista aldeia por aldeia quem ficou: \"E o restante de Israel, dos sacerdotes e levitas, habitou em todas as cidades de Judá, cada um na sua herança\" (Ne 11:20), e os nomes vêm em fila — Quiriate-Arba, Dibom, Jecabzeel, Molada, Bete-Pelete, Hazar-Sual, Berseba, Ziclague, En-Rimom, Zorá, Jarmute, Zanoa, Adulão, Laquis, Azeca. A mulher que fica nesses lugares é quem mantém a colheita de pé para que a cidade tenha o que comer.",
    },
    multidao: {
      title: "O povo que bendisse a todos os homens que voluntariamente se ofereciam para habitar em Jerusalém",
      subtitle: "Ne 11:2 • o dia das sortes, do lado de quem ficou",
      text: "\"E o povo bendisse a todos os homens que voluntariamente se ofereciam para habitar em Jerusalém\" (Ne 11:2). Não é uma frase decorativa: é o único agradecimento que estes homens vão receber. As sortes tinham tirado um de dez — \"e as nove partes nas outras cidades\" (Ne 11:1) —, e além dos sorteados houve quem se apresentasse por vontade própria. A multidão que os bendiz é, exatamente, a das nove partes que ficam: gente que volta para a sua aldeia, para a sua vinha e para a sua casa, sabendo que aqueles vão viver numa cidade em obras, exposta ao primeiro exército que apareça, e com o custo de vida de uma capital. Nas Escrituras, Jerusalém é sempre desejada de longe — \"Alegrei-me quando me disseram: Vamos á casa do SENHOR\" (Sl 122:1) —, mas ir morar lá, neste momento da história, é sacrifício e não privilégio. É por isso que o capítulo os conta um a um e escreve o nome da casa paterna de cada um: quem se oferece para o lugar difícil fica registado.",
    },
    rebanho: {
      title: "O rebanho da herança nas cidades de Judá e nas aldeias do sul, de Berseba até ao vale de Hinom",
      subtitle: "Ne 11:20,25-30 • o que sustenta a cidade santa e fica fora dos seus muros",
      text: "Uma cidade que tira um de cada dez para viver dentro de muros precisa de nove que fiquem no campo, e é isso que o mapa do fim do capítulo desenha: \"E o restante de Israel, dos sacerdotes e levitas, habitou em todas as cidades de Judá, cada um na sua herança\" (Ne 11:20). A lista desce ao Neguebe — Molada, Bete-Pelete, Hazar-Sual, Berseba — e o texto fecha o traçado com uma linha de geografia: \"Acamparam-se desde Berseba até ao vale de Hinom\" (Ne 11:30). De Berseba, no deserto do sul, ao vale de Hinom, que é o barranco colado à muralha de Jerusalém: a província inteira num fôlego. Nesse território, a riqueza não é dinheiro, é rebanho e cevada, e é dele que sairão os primogénitos, os dízimos e as primícias que a aliança do capítulo 10 acabou de prometer. O gado destas encostas é o que faz o holocausto contínuo continuar, e é a ele que Neemias voltará a olhar no capítulo 13, quando os celeiros do templo estiverem vazios e os levitas tiverem fugido cada um para o seu campo.",
    },
    servo: {
      title: "O moço que carregou a mudança dos sorteados para Jerusalém, os netineus que habitavam em Ofel debaixo de Zia e Gispa, o segundo cantor dos filhos de Asafe e o escriba dos negócios do povo diante do rei",
      subtitle: "Ne 11:1,21-24 • quem carrega, quem serve o altar e quem trata com a Pérsia",
      text: "A mudança de um em cada dez faz-se em jumentos e às costas: cestos, esteiras, potes, a arca da roupa e as ferramentas do ofício sobem a estrada da montanha para dentro de uma cidade sem casas prontas. Lá dentro, o capítulo situa a colónia dos netineus com endereço: \"E os servidores do templo, habitaram em Ofel; e Zia e Gispa presidiam sobre os servidores do templo\" (Ne 11:21) — o mesmo esporão de rocha ao sul do templo em que eles tinham reparado o muro (Ne 3:26). Os cantores estão \"ao serviço da casa de Deus\" com turno diário fixado por decreto (Ne 11:22-23). E há um cargo que quase passa despercebido e explica muito: \"E Petaías, filho de Mesezabeel, dos filhos de Zerá, filho de Judá, estava à mão do rei, em todos os negócios do povo\" (Ne 11:24). Um judeu de Jerusalém encarregado de despachar com a corte persa tudo o que dissesse respeito à província — o canal por onde correm as licenças, as queixas e as cartas, e sem o qual nada do que Neemias fez teria durado um ano.",
    },
  },

  // ---------------------------------------------------------------- Ne 12
  12: {
    anciao: {
      title: "Jesuá, o sumo sacerdote que subiu com Zorobabel, os chefes dos pais dos dias de Joiaquim, o escriba que registrou a geração dos sumos sacerdotes até Jadua, Hasabias e Serabias, chefes dos levitas do louvor, e os sacerdotes das trombetas da dedicação",
      subtitle: "Ne 12:1-26,41 • cem anos de turnos, do primeiro regresso à dedicação do muro",
      text: "O capítulo abre com a lista da primeira leva, a de sessenta anos antes de Neemias: \"Estes são sacerdotes e levitas que subiram com Zorobabel, filho de Sealtiel, e com Jesuá: Seraías, Jeremias, Esdras\" (Ne 12:1) — vinte e dois nomes de casas, e a nota que os fecha, \"estes foram os chefes dos sacerdotes e de seus irmãos, nos dias de Jesuá\" (Ne 12:7). Depois o texto salta uma geração e dá a mesma lista \"nos dias de Joiaquim\" (Ne 12:12), casa por casa, para mostrar que os turnos se mantiveram: de Seraías, Meraías; de Jeremias, Hananias; de Esdras, Mesulão. E há a linha dos sumos sacerdotes, que é a espinha cronológica do pós-exílio: \"E Jesuá gerou a Joiaquim, e Joiaquim gerou a Eliasibe, e Eliasibe gerou a Joiada, e Joiada gerou a Jônatas, e Jônatas gerou a Jadua\" (Ne 12:10-11). Cinco gerações registadas \"até ao reinado de Dario, o persa\" (Ne 12:22) — um arquivo mantido por escribas dentro de uma província sem rei próprio, para que ninguém pudesse depois inventar linhagem. O louvor tem o mesmo cuidado: \"segundo o mandado de Davi, homem de Deus; guarda contra guarda\" (Ne 12:24).",
    },
    homem: {
      title: "Os cantores ajuntados das aldeias de Netofati, os príncipes de Judá que subiram sobre o muro, Zacarias filho de Jônatas com as trombetas, Hanani e os que iam com os instrumentos musicais de Davi, e Jezraías, o superintendente dos cantores",
      subtitle: "Ne 12:27-43 • a dedicação do muro, com dois grandes coros em direções opostas",
      text: "\"E na dedicação dos muros de Jerusalém buscaram os levitas de todos os seus lugares, para trazê-los, a fim de fazerem a dedicação com alegria, com louvores e com canto, saltérios, címbalos e com harpas\" (Ne 12:27). Os cantores tinham feito aldeias para si nos arredores (Ne 12:29) e agora sobem todos. Purificam-se os sacerdotes e os levitas, e depois \"purificaram o povo, as portas e o muro\" (Ne 12:30) — a pedra também é consagrada. Então vem a cena mais bonita do livro: \"Então fiz subir os príncipes de Judá sobre o muro, e ordenei dois grandes coros em procissão, um à mão direita sobre o muro do lado da porta do monturo\" (Ne 12:31). Duas procissões a andar EM CIMA do muro acabado, em sentidos contrários, cada uma com metade dos príncipes, os seus trombeteiros e os seus harpistas, cobrindo o perímetro inteiro que cinquenta e dois dias antes era entulho — e Esdras, o escriba, a ir adiante de um deles (Ne 12:36). As duas param no mesmo sítio: \"Então ambos os coros pararam na casa de Deus\" (Ne 12:40). E a cidade ouve-se de longe: \"a alegria de Jerusalém se ouviu até de longe\" (Ne 12:43).",
    },
    mulherComum: {
      title: "As mulheres das aldeias dos cantores em Azmavete, as que se purificaram para a dedicação e as que se alegraram no dia em que a alegria de Jerusalém se ouviu de longe",
      subtitle: "Ne 12:29-30,43 • o versículo em que o texto conta as mulheres e os meninos",
      text: "\"E ofereceram, no mesmo dia, grandes sacrifícios e se alegraram; porque Deus os alegrara com grande alegria; e até as mulheres e os meninos se alegraram, de modo que a alegria de Jerusalém se ouviu até de longe\" (Ne 12:43). É uma frase que o autor não precisava de escrever, e escreveu: no dia da dedicação, a festa não foi dos sacerdotes nem dos príncipes que andaram em cima do muro — foi de toda a casa, e o texto para para o dizer. Antes disso, ela aparece nas aldeias que os cantores tinham construído em volta da cidade: \"porque os cantores edificaram para si aldeias nos arredores de Jerusalém\" (Ne 12:29), lugares como Azmavete e os campos de Geba, de onde a família inteira sobe para o dia grande. E aparece na purificação: \"E purificaram-se os sacerdotes e os levitas; e logo purificaram o povo, as portas e o muro\" (Ne 12:30) — o povo inclui-a, com lavagens e roupa limpa, antes de o cortejo se pôr a andar. O som que sai daqui é o oposto exato do choro de Esdras 3:12: desta vez ninguém está a comparar com nada.",
    },
    multidao: {
      title: "Os cantores que se faziam ouvir na casa de Deus, e o povo alegre no dia da dedicação do muro",
      subtitle: "Ne 12:42-43 • as duas procissões unidas no adro",
      text: "\"Como também, Maaséias, Semaías, Eleazar, Uzi, Joanã, Malquias, Elão e Ezer; e faziam-se ouvir os cantores, juntamente com Jezraías, o seu superintendente\" (Ne 12:42). Os dois coros que tinham dado a volta ao muro em sentidos contrários encontram-se e cantam juntos, com sacerdotes de trombeta de um lado e os instrumentos musicais de Davi do outro. \"E ofereceram, no mesmo dia, grandes sacrifícios e se alegraram; porque Deus os alegrara com grande alegria\" (Ne 12:43) — a alegria é atribuída a Deus como causa, não ao muro. E o efeito é acústico: \"de modo que a alegria de Jerusalém se ouviu até de longe\". De longe quer dizer, muito concretamente, até Samaria e até Amom, onde ainda vivem Sambalate e Tobias. Doze anos antes, o barulho que saía desta cidade era o de pedras a serem arrastadas debaixo de escárnio; agora é um coro em cima do próprio muro que eles disseram que uma raposa derrubaria (Ne 4:3).",
    },
    servo: {
      title: "O moço que carregou as harpas dos cantores vindos das aldeias, o levita do címbalo sobre o muro, os porteiros das tesourarias das portas e o moço que levou as primícias às câmaras",
      subtitle: "Ne 12:25,27-31,44 • quem transporta, guarda e arruma no dia da festa",
      text: "Uma dedicação destas mede-se em carga. Os levitas são buscados \"de todos os seus lugares\" (Ne 12:27) e vêm com \"saltérios, címbalos e com harpas\" — instrumentos que alguém tem de embalar, transportar por estradas de montanha e afinar à chegada. No cortejo, cada coro leva o seu próprio aparelho de som sobre uma parede estreita, e há moços a subir e a descer as escadas da cidade de Davi com o que faltou (Ne 12:37). Nas portas ficam os que não podem ir: \"Matanias, Bacbuquias, Obadias, Mesulão, Talmom e Acube, eram porteiros, que faziam a guarda às tesourarias das portas\" (Ne 12:25) — enquanto a cidade canta em cima do muro, alguém está a tomar conta do que está guardado em baixo. E no fim da festa começa a arrumação, que é o assunto sério do capítulo: \"Também no mesmo dia se nomearam homens sobre as câmaras, dos tesouros, das ofertas alçadas, das primícias, dos dízimos, para ajuntarem nelas, dos campos das cidades, as partes da lei para os sacerdotes e para os levitas\" (Ne 12:44).",
    },
  },

  // ---------------------------------------------------------------- Ne 13
  13: {
    anciao: {
      title: "O levita que leu no livro de Moisés aos ouvidos do povo, Eliasibe que se aparentara com Tobias, os magistrados com quem Neemias contendeu, os nobres de Judá que profanavam o sábado e Selemias, o sacerdote posto por tesoureiro",
      subtitle: "Ne 13:1,4,11,13,17 • o regresso, e tudo desfeito",
      text: "O capítulo começa com uma leitura pública — \"Naquele dia leu-se no livro de Moisés, aos ouvidos do povo; e achou-se escrito nele que os amonitas e os moabitas não entrassem jamais na congregação de Deus\" (Ne 13:1) — e o pior é que a Escritura acabara de ser lida contra um homem que estava com um quarto dentro do templo: \"Ora, antes disto, Eliasibe, sacerdote, que presidia sobre a câmara da casa do nosso Deus, se tinha aparentado com Tobias\" (Ne 13:4), o amonita. O mesmo Eliasibe que abrira o capítulo 3 a consagrar a porta do gado. Neemias tinha ido a Susã prestar contas ao rei (Ne 13:6) e, ao voltar, encontra a câmara das ofertas transformada em aposento particular, os dízimos por dar, os levitas fugidos, os lagares a laborar ao sábado e os filhos a falar asdodita. A resposta é contenda atrás de contenda: \"Então contendi com os magistrados, e disse: Por que se desamparou a casa de Deus?\" (Ne 13:11); \"E contendi com os nobres de Judá, e lhes disse: Que mal é este que fazeis, profanando o dia de sábado?\" (Ne 13:17). E a reforma acaba com quatro nomes achados fiéis: Selemias, Zadoque, Pedaías e Hanã (Ne 13:13).",
    },
    homem: {
      title: "O judeu que ouviu a leitura do livro de Moisés, o carregador de feixes no dia de sábado, o tírio que vendia peixe, o negociante que passou a noite fora do muro, o judeu que casou com mulher asdodita e o filho de Joiada, genro de Sambalate",
      subtitle: "Ne 13:1-28 • as quatro coisas que Neemias achou desfeitas ao voltar",
      text: "A ruína chegou por rotina, não por invasão. Primeiro os quinhões: \"Também entendi que os quinhões dos levitas não se lhes davam, de maneira que os levitas e os cantores, que faziam a obra, tinham fugido cada um para a sua terra\" (Ne 13:10) — o coro da dedicação está a cavar a sua horta. Depois o sábado: \"Naqueles dias vi em Judá os que pisavam lagares ao sábado e traziam feixes que carregavam sobre os jumentos; como também vinho, uvas e figos, e toda a espécie de cargas\" (Ne 13:15), e dentro da cidade \"habitavam em Jerusalém tírios que traziam peixe e toda a mercadoria, que vendiam no sábado aos filhos de Judá\" (Ne 13:16). A solução é física: fecham-se as portas ao anoitecer da véspera, e quando os negociantes acampam do lado de fora à espera, ele avisa uma única vez — \"Se outra vez o fizerdes, hei de lançar mão de vós. Daquele tempo em diante não vieram no sábado\" (Ne 13:21). Por último, o casamento, e a prova é linguística: \"E seus filhos falavam meio asdodita, e não podiam falar judaico\" (Ne 13:24). Uma geração e a língua da lei desaparece. O caso mais grave está no palácio sacerdotal: um neto do sumo sacerdote é genro de Sambalate, \"por isso o afugentei de mim\" (Ne 13:28).",
    },
    mulherComum: {
      title: "A mulher de Jerusalém que ouviu a leitura da lei, a filha de Judá que comprava no sábado, e as mulheres asdoditas, amonitas e moabitas com quem os judeus tinham casado",
      subtitle: "Ne 13:1-3,16,23-27 • a cláusula do capítulo 10 quebrada em casa",
      text: "Duas cláusulas da firme aliança caíram, e as duas passam por ela. A do sábado quebra-se no mercado, porque a banca do tírio está montada e o peixe é fresco: \"habitavam em Jerusalém tírios que traziam peixe e toda a mercadoria, que vendiam no sábado aos filhos de Judá\" (Ne 13:16). A do casamento quebra-se dentro de casa: \"Vi também naqueles dias judeus que tinham casado com mulheres asdoditas, amonitas e moabitas. E seus filhos falavam meio asdodita, e não podiam falar judaico, senão segundo a língua de cada povo\" (Ne 13:23-24). Não é uma questão de raça: é que a mãe ensina a língua, e com a língua vai a lei que se lê nela — sem judaico, aquelas crianças não podem ouvir o livro que o pai delas ouviu de pé na praça da porta das águas. O argumento de Neemias não é étnico, é histórico, e vai buscar o homem mais sábio de Israel: \"Porventura não pecou nisto Salomão, rei de Israel, não havendo entre muitas nações rei semelhante a ele, e sendo ele amado de seu Deus… E contudo as mulheres estrangeiras o fizeram pecar\" (Ne 13:26).",
    },
    rei: {
      title: "Artaxerxes, rei de babilônia, a quem Neemias foi ter no ano trinta e dois, e de quem tornou a alcançar licença",
      subtitle: "Ne 13:6 • o versículo que explica como tudo se desfez",
      text: "\"Mas durante tudo isto não estava eu em Jerusalém, porque no ano trinta e dois de Artaxerxes, rei de babilônia, fui ter com o rei; mas após alguns dias tornei a alcançar licença do rei\" (Ne 13:6). É a única explicação que o livro dá para o desmoronamento do capítulo: o governador ausentou-se. Doze anos de mandato (Ne 5:14) e depois a viagem obrigatória de volta à corte para prestar contas — e bastou isso. Repare no título estranho: \"Artaxerxes, rei de babilônia\", e não da Pérsia; é a forma como um súbdito da satrapia nomeia o senhor do território que já foi o império que levou os seus avós. O mesmo rei que dera as cartas no capítulo 2 dá agora a licença para voltar. Toda a autoridade humana desta história é emprestada e revogável, e Neemias sabe-o: por isso as três últimas frases do livro não são dirigidas ao rei que assina as licenças, mas ao único que não muda — \"Por isto, Deus meu, lembra-te de mim e não risques as beneficências que eu fiz à casa de meu Deus\" (Ne 13:14), \"lembra-te de mim e perdoa-me segundo a abundância da tua benignidade\" (Ne 13:22), \"lembra-te de mim, Deus meu, para bem\" (Ne 13:31).",
    },
    servo: {
      title: "O moço que carregou os móveis de Tobias para a câmara e depois os viu lançados fora, o levita que perdeu a câmara do seu dízimo, o cantor que fugiu para o seu campo e os servos de Neemias postos às portas no sábado",
      subtitle: "Ne 13:5-9,19 • as mãos que arrumam, as que fogem e as que trancam a porta",
      text: "A ocupação da casa de Deus fez-se com carregadores: alguém esvaziou uma câmara grande \"onde dantes se depositavam as ofertas de alimentos, o incenso, os utensílios, os dízimos do grão, do mosto e do azeite, que se ordenaram para os levitas, cantores e porteiros\" (Ne 13:5) e subiu com os móveis de Tobias pelas escadas do templo. O despejo faz-se do mesmo modo, e a frase é de quem não delegou: \"O que muito me desagradou; de sorte que lancei todos os móveis da casa de Tobias fora da câmara\" (Ne 13:8). Depois vem a limpeza e a devolução: \"E, ordenando-o eu, purificaram as câmaras; e tornei a trazer para ali os utensílios da casa de Deus, com as ofertas de alimentos e o incenso\" (Ne 13:9). Do outro lado da mesma história estão os que se foram embora porque a despensa ficou vazia — \"os levitas e os cantores, que faziam a obra, tinham fugido cada um para a sua terra\" (Ne 13:10) —, e voltam quando o dízimo volta. E no fim, aos portões, os homens de confiança do governador: \"e pus às portas alguns de meus servos, para que nenhuma carga entrasse no dia de sábado\" (Ne 13:19).",
    },
  },
};
