-- Create table for custom reading plans generated by AI
CREATE TABLE public.custom_reading_plans (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  plan_name TEXT NOT NULL,
  plan_description TEXT,
  selected_books TEXT[] NOT NULL,
  total_days INTEGER NOT NULL,
  total_chapters INTEGER NOT NULL,
  chapters_per_day INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  is_active BOOLEAN DEFAULT true
);

-- Enable RLS
ALTER TABLE public.custom_reading_plans ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own custom plans" 
ON public.custom_reading_plans 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own custom plans" 
ON public.custom_reading_plans 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own custom plans" 
ON public.custom_reading_plans 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own custom plans" 
ON public.custom_reading_plans 
FOR DELETE 
USING (auth.uid() = user_id);

-- Create table to track plan completions and bonus points
CREATE TABLE public.plan_completions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  plan_type TEXT NOT NULL, -- '90', '184', '365', 'nt60', 'at90', 'custom'
  custom_plan_id UUID REFERENCES public.custom_reading_plans(id),
  bonus_points INTEGER NOT NULL DEFAULT 10,
  completed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.plan_completions ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own plan completions" 
ON public.plan_completions 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own plan completions" 
ON public.plan_completions 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);